// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 5000 to 5499 of {@link Language}.
 */
final class LanguageData10 {
  private LanguageData10() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("okc", "Kobo", "I", "L", null, null, null, null));
    out.add(new Language("okd", "Okodia", "I", "L", null, null, null, null));
    out.add(new Language("oke", "Okpe (Southwestern Edo)", "I", "L", null, null, null, null));
    out.add(new Language("okg", "Koko Babangk", "I", "E", null, null, null, null));
    out.add(new Language("okh", "Koresh-e Rostam", "I", "L", null, null, null, null));
    out.add(new Language("oki", "Okiek", "I", "L", null, null, null, null));
    out.add(new Language("okj", "Oko-Juwoi", "I", "E", null, null, null, null));
    out.add(new Language("okk", "Kwamtim One", "I", "L", null, null, "One, Kwamtim", null));
    out.add(new Language("okl", "Old Kentish Sign Language", "I", "E", null, null, "Kentish Sign Language, Old", null));
    out.add(new Language("okm", "Middle Korean (10th-16th cent.)", "I", "H", null, null, "Korean, Middle (10th-16th cent.)", null));
    out.add(new Language("okn", "Oki-No-Erabu", "I", "L", null, null, null, null));
    out.add(new Language("oko", "Old Korean (3rd-9th cent.)", "I", "H", null, null, "Korean, Old (3rd-9th cent.)", null));
    out.add(new Language("okr", "Kirike", "I", "L", null, null, null, null));
    out.add(new Language("oks", "Oko-Eni-Osayen", "I", "L", null, null, null, null));
    out.add(new Language("oku", "Oku", "I", "L", null, null, null, null));
    out.add(new Language("okv", "Orokaiva", "I", "L", null, null, null, null));
    out.add(new Language("okx", "Okpe (Northwestern Edo)", "I", "L", null, null, null, null));
    out.add(new Language("okz", "Old Khmer", "I", "H", null, null, "Khmer, Old", null));
    out.add(new Language("ola", "Walungge", "I", "L", null, null, null, null));
    out.add(new Language("old", "Mochi", "I", "L", null, null, null, null));
    out.add(new Language("ole", "Olekha", "I", "L", null, null, null, null));
    out.add(new Language("olk", "Olkol", "I", "E", null, null, null, null));
    out.add(new Language("olm", "Oloma", "I", "L", null, null, null, null));
    out.add(new Language("olo", "Livvi", "I", "L", null, null, null, null));
    out.add(new Language("olr", "Olrat", "I", "L", null, null, null, null));
    out.add(new Language("olt", "Old Lithuanian", "I", "H", null, null, "Lithuanian, Old", null));
    out.add(new Language("olu", "Kuvale", "I", "L", null, null, null, null));
    out.add(new Language("oma", "Omaha-Ponca", "I", "L", null, null, null, null));
    out.add(new Language("omb", "East Ambae", "I", "L", null, null, "Ambae, East", null));
    out.add(new Language("omc", "Mochica", "I", "E", null, null, null, null));
    out.add(new Language("omg", "Omagua", "I", "L", null, null, null, null));
    out.add(new Language("omi", "Omi", "I", "L", null, null, null, null));
    out.add(new Language("omk", "Omok", "I", "E", null, null, null, null));
    out.add(new Language("oml", "Ombo", "I", "L", null, null, null, null));
    out.add(new Language("omn", "Minoan", "I", "H", null, null, null, null));
    out.add(new Language("omo", "Utarmbung", "I", "L", null, null, null, null));
    out.add(new Language("omp", "Old Manipuri", "I", "H", null, null, "Manipuri, Old", null));
    out.add(new Language("omr", "Old Marathi", "I", "H", null, null, "Marathi, Old", null));
    out.add(new Language("omt", "Omotik", "I", "L", null, null, null, null));
    out.add(new Language("omu", "Omurano", "I", "E", null, null, null, null));
    out.add(new Language("omw", "South Tairora", "I", "L", null, null, "Tairora, South", null));
    out.add(new Language("omx", "Old Mon", "I", "H", null, null, "Mon, Old", null));
    out.add(new Language("omy", "Old Malay", "I", "H", null, null, "Malay, Old", null));
    out.add(new Language("ona", "Ona", "I", "L", null, null, null, null));
    out.add(new Language("onb", "Lingao", "I", "L", null, null, null, null));
    out.add(new Language("one", "Oneida", "I", "L", null, null, null, null));
    out.add(new Language("ong", "Olo", "I", "L", null, null, null, null));
    out.add(new Language("oni", "Onin", "I", "L", null, null, null, null));
    out.add(new Language("onj", "Onjob", "I", "L", null, null, null, null));
    out.add(new Language("onk", "Kabore One", "I", "L", null, null, "One, Kabore", null));
    out.add(new Language("onn", "Onobasulu", "I", "L", null, null, null, null));
    out.add(new Language("ono", "Onondaga", "I", "L", null, null, null, null));
    out.add(new Language("onp", "Sartang", "I", "L", null, null, null, null));
    out.add(new Language("onr", "Northern One", "I", "L", null, null, "One, Northern", null));
    out.add(new Language("ons", "Ono", "I", "L", null, null, null, null));
    out.add(new Language("ont", "Ontenu", "I", "L", null, null, null, null));
    out.add(new Language("onu", "Unua", "I", "L", null, null, null, null));
    out.add(new Language("onw", "Old Nubian", "I", "H", null, null, "Nubian, Old", null));
    out.add(new Language("onx", "Onin Based Pidgin", "I", "L", null, null, null, null));
    out.add(new Language("ood", "Tohono O'odham", "I", "L", null, null, null, null));
    out.add(new Language("oog", "Ong", "I", "L", null, null, null, null));
    out.add(new Language("oon", "Önge", "I", "L", null, null, null, null));
    out.add(new Language("oor", "Oorlams", "I", "L", null, null, null, null));
    out.add(new Language("oos", "Old Ossetic", "I", "H", null, null, "Ossetic, Old", null));
    out.add(new Language("opa", "Okpamheri", "I", "L", null, null, null, null));
    out.add(new Language("opk", "Kopkaka", "I", "L", null, null, null, null));
    out.add(new Language("opm", "Oksapmin", "I", "L", null, null, null, null));
    out.add(new Language("opo", "Opao", "I", "L", null, null, null, null));
    out.add(new Language("opt", "Opata", "I", "E", null, null, null, null));
    out.add(new Language("opy", "Ofayé", "I", "L", null, null, null, null));
    out.add(new Language("ora", "Oroha", "I", "L", null, null, null, null));
    out.add(new Language("orc", "Orma", "I", "L", null, null, null, null));
    out.add(new Language("ore", "Orejón", "I", "L", null, null, null, null));
    out.add(new Language("org", "Oring", "I", "L", null, null, null, null));
    out.add(new Language("orh", "Oroqen", "I", "L", null, null, null, null));
    out.add(new Language("ori", "Oriya (macrolanguage)", "M", "L", "or", null, null, null));
    out.add(new Language("orm", "Oromo", "M", "L", "om", null, null, null));
    out.add(new Language("orn", "Orang Kanaq", "I", "L", null, null, null, null));
    out.add(new Language("oro", "Orokolo", "I", "L", null, null, null, null));
    out.add(new Language("orr", "Oruma", "I", "L", null, null, null, null));
    out.add(new Language("ors", "Orang Seletar", "I", "L", null, null, null, null));
    out.add(new Language("ort", "Adivasi Oriya", "I", "L", null, null, "Oriya, Adivasi", null));
    out.add(new Language("oru", "Ormuri", "I", "L", null, null, null, null));
    out.add(new Language("orv", "Old Russian", "I", "H", null, null, "Russian, Old", null));
    out.add(new Language("orw", "Oro Win", "I", "L", null, null, null, null));
    out.add(new Language("orx", "Oro", "I", "L", null, null, null, null));
    out.add(new Language("ory", "Odia", "I", "L", null, null, null, null));
    out.add(new Language("orz", "Ormu", "I", "L", null, null, null, null));
    out.add(new Language("osa", "Osage", "I", "L", null, null, null, null));
    out.add(new Language("osc", "Oscan", "I", "H", null, null, null, null));
    out.add(new Language("osi", "Osing", "I", "L", null, null, null, null));
    out.add(new Language("osn", "Old Sundanese", "I", "H", null, null, "Sundanese, Old", null));
    out.add(new Language("oso", "Ososo", "I", "L", null, null, null, null));
    out.add(new Language("osp", "Old Spanish", "I", "H", null, null, "Spanish, Old", null));
    out.add(new Language("oss", "Ossetian", "I", "L", "os", null, null, null));
    out.add(new Language("ost", "Osatu", "I", "L", null, null, null, null));
    out.add(new Language("osu", "Southern One", "I", "L", null, null, "One, Southern", null));
    out.add(new Language("osx", "Old Saxon", "I", "H", null, null, "Saxon, Old", null));
    out.add(new Language("ota", "Ottoman Turkish (1500-1928)", "I", "H", null, null, "Turkish, Ottoman (1500-1928)", null));
    out.add(new Language("otb", "Old Tibetan", "I", "H", null, null, "Tibetan, Old", null));
    out.add(new Language("otd", "Ot Danum", "I", "L", null, null, null, null));
    out.add(new Language("ote", "Mezquital Otomi", "I", "L", null, null, "Otomi, Mezquital", null));
    out.add(new Language("oti", "Oti", "I", "E", null, null, null, null));
    out.add(new Language("otk", "Old Turkish", "I", "H", null, null, "Turkish, Old", null));
    out.add(new Language("otl", "Tilapa Otomi", "I", "L", null, null, "Otomi, Tilapa", null));
    out.add(new Language("otm", "Eastern Highland Otomi", "I", "L", null, null, "Otomi, Eastern Highland", null));
    out.add(new Language("otn", "Tenango Otomi", "I", "L", null, null, "Otomi, Tenango", null));
    out.add(new Language("otq", "Querétaro Otomi", "I", "L", null, null, "Otomi, Querétaro", null));
    out.add(new Language("otr", "Otoro", "I", "L", null, null, null, null));
    out.add(new Language("ots", "Estado de México Otomi", "I", "L", null, null, "Otomi, Estado de México", null));
    out.add(new Language("ott", "Temoaya Otomi", "I", "L", null, null, "Otomi, Temoaya", null));
    out.add(new Language("otu", "Otuke", "I", "E", null, null, null, null));
    out.add(new Language("otw", "Ottawa", "I", "L", null, null, null, null));
    out.add(new Language("otx", "Texcatepec Otomi", "I", "L", null, null, "Otomi, Texcatepec", null));
    out.add(new Language("oty", "Old Tamil", "I", "H", null, null, "Tamil, Old", null));
    out.add(new Language("otz", "Ixtenco Otomi", "I", "L", null, null, "Otomi, Ixtenco", null));
    out.add(new Language("oua", "Tagargrent", "I", "L", null, null, null, null));
    out.add(new Language("oub", "Glio-Oubi", "I", "L", null, null, null, null));
    out.add(new Language("oue", "Oune", "I", "L", null, null, null, null));
    out.add(new Language("oui", "Old Uighur", "I", "H", null, null, "Uighur, Old", null));
    out.add(new Language("oum", "Ouma", "I", "E", null, null, null, null));
    out.add(new Language("ovd", "Elfdalian", "I", "L", null, null, null, null));
    out.add(new Language("owi", "Owiniga", "I", "L", null, null, null, null));
    out.add(new Language("owl", "Old Welsh", "I", "H", null, null, "Welsh, Old", null));
    out.add(new Language("oyb", "Oy", "I", "L", null, null, null, null));
    out.add(new Language("oyd", "Oyda", "I", "L", null, null, null, null));
    out.add(new Language("oym", "Wayampi", "I", "L", null, null, null, null));
    out.add(new Language("oyy", "Oya'oya", "I", "L", null, null, null, null));
    out.add(new Language("ozm", "Koonzime", "I", "L", null, null, null, null));
    out.add(new Language("pab", "Parecís", "I", "L", null, null, null, null));
    out.add(new Language("pac", "Pacoh", "I", "L", null, null, null, null));
    out.add(new Language("pad", "Paumarí", "I", "L", null, null, null, null));
    out.add(new Language("pae", "Pagibete", "I", "L", null, null, null, null));
    out.add(new Language("paf", "Paranawát", "I", "E", null, null, null, null));
    out.add(new Language("pag", "Pangasinan", "I", "L", null, null, null, null));
    out.add(new Language("pah", "Tenharim", "I", "L", null, null, null, null));
    out.add(new Language("pai", "Pe", "I", "L", null, null, null, null));
    out.add(new Language("pak", "Parakanã", "I", "L", null, null, null, null));
    out.add(new Language("pal", "Pahlavi", "I", "H", null, null, null, null));
    out.add(new Language("pam", "Pampanga", "I", "L", null, null, null, null));
    out.add(new Language("pan", "Panjabi", "I", "L", "pa", null, null, null));
    out.add(new Language("pao", "Northern Paiute", "I", "L", null, null, "Paiute, Northern", null));
    out.add(new Language("pap", "Papiamento", "I", "L", null, null, null, null));
    out.add(new Language("paq", "Parya", "I", "L", null, null, null, null));
    out.add(new Language("par", "Panamint", "I", "L", null, null, null, null));
    out.add(new Language("pas", "Papasena", "I", "L", null, null, null, null));
    out.add(new Language("pau", "Palauan", "I", "L", null, null, null, null));
    out.add(new Language("pav", "Pakaásnovos", "I", "L", null, null, null, null));
    out.add(new Language("paw", "Pawnee", "I", "L", null, null, null, null));
    out.add(new Language("pax", "Pankararé", "I", "E", null, null, null, null));
    out.add(new Language("pay", "Pech", "I", "L", null, null, null, null));
    out.add(new Language("paz", "Pankararú", "I", "E", null, null, null, null));
    out.add(new Language("pbb", "Páez", "I", "L", null, null, null, null));
    out.add(new Language("pbc", "Patamona", "I", "L", null, null, null, null));
    out.add(new Language("pbe", "Mezontla Popoloca", "I", "L", null, null, "Popoloca, Mezontla", null));
    out.add(new Language("pbf", "Coyotepec Popoloca", "I", "L", null, null, "Popoloca, Coyotepec", null));
    out.add(new Language("pbg", "Paraujano", "I", "E", null, null, null, null));
    out.add(new Language("pbh", "E'ñapa Woromaipu", "I", "L", null, null, null, null));
    out.add(new Language("pbi", "Parkwa", "I", "L", null, null, null, null));
    out.add(new Language("pbl", "Mak (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("pbm", "Puebla Mazatec", "I", "L", null, null, "Mazatec, Puebla", null));
    out.add(new Language("pbn", "Kpasam", "I", "L", null, null, null, null));
    out.add(new Language("pbo", "Papel", "I", "L", null, null, null, null));
    out.add(new Language("pbp", "Badyara", "I", "L", null, null, null, null));
    out.add(new Language("pbr", "Pangwa", "I", "L", null, null, null, null));
    out.add(new Language("pbs", "Central Pame", "I", "L", null, null, "Pame, Central", null));
    out.add(new Language("pbt", "Southern Pashto", "I", "L", null, null, "Pashto, Southern", null));
    out.add(new Language("pbu", "Northern Pashto", "I", "L", null, null, "Pashto, Northern", null));
    out.add(new Language("pbv", "Pnar", "I", "L", null, null, null, null));
    out.add(new Language("pby", "Pyu (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("pca", "Santa Inés Ahuatempan Popoloca", "I", "L", null, null, "Popoloca, Santa Inés Ahuatempan", null));
    out.add(new Language("pcb", "Pear", "I", "L", null, null, null, null));
    out.add(new Language("pcc", "Bouyei", "I", "L", null, null, null, null));
    out.add(new Language("pcd", "Picard", "I", "L", null, null, null, null));
    out.add(new Language("pce", "Ruching Palaung", "I", "L", null, null, "Palaung, Ruching", null));
    out.add(new Language("pcf", "Paliyan", "I", "L", null, null, null, null));
    out.add(new Language("pcg", "Paniya", "I", "L", null, null, null, null));
    out.add(new Language("pch", "Pardhan", "I", "L", null, null, null, null));
    out.add(new Language("pci", "Duruwa", "I", "L", null, null, null, null));
    out.add(new Language("pcj", "Parenga", "I", "L", null, null, null, null));
    out.add(new Language("pck", "Paite Chin", "I", "L", null, null, "Chin, Paite", null));
    out.add(new Language("pcl", "Pardhi", "I", "L", null, null, null, null));
    out.add(new Language("pcm", "Nigerian Pidgin", "I", "L", null, null, "Pidgin, Nigerian", null));
    out.add(new Language("pcn", "Piti", "I", "L", null, null, null, null));
    out.add(new Language("pcp", "Pacahuara", "I", "L", null, null, null, null));
    out.add(new Language("pcw", "Pyapun", "I", "L", null, null, null, null));
    out.add(new Language("pda", "Anam", "I", "L", null, null, null, null));
    out.add(new Language("pdc", "Pennsylvania German", "I", "L", null, null, "German, Pennsylvania", null));
    out.add(new Language("pdi", "Pa Di", "I", "L", null, null, null, null));
    out.add(new Language("pdn", "Podena", "I", "L", null, null, null, null));
    out.add(new Language("pdo", "Padoe", "I", "L", null, null, null, null));
    out.add(new Language("pdt", "Plautdietsch", "I", "L", null, null, null, null));
    out.add(new Language("pdu", "Kayan", "I", "L", null, null, null, null));
    out.add(new Language("pea", "Peranakan Indonesian", "I", "L", null, null, "Indonesian, Peranakan", null));
    out.add(new Language("peb", "Eastern Pomo", "I", "E", null, null, "Pomo, Eastern", null));
    out.add(new Language("ped", "Mala (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("pee", "Taje", "I", "L", null, null, null, null));
    out.add(new Language("pef", "Northeastern Pomo", "I", "E", null, null, "Pomo, Northeastern", null));
    out.add(new Language("peg", "Pengo", "I", "L", null, null, null, null));
    out.add(new Language("peh", "Bonan", "I", "L", null, null, null, null));
    out.add(new Language("pei", "Chichimeca-Jonaz", "I", "L", null, null, null, null));
    out.add(new Language("pej", "Northern Pomo", "I", "E", null, null, "Pomo, Northern", null));
    out.add(new Language("pek", "Penchal", "I", "L", null, null, null, null));
    out.add(new Language("pel", "Pekal", "I", "L", null, null, null, null));
    out.add(new Language("pem", "Phende", "I", "L", null, null, null, null));
    out.add(new Language("peo", "Old Persian (ca. 600-400 B.C.)", "I", "H", null, null, "Persian, Old (ca. 600-400 B.C.)", null));
    out.add(new Language("pep", "Kunja", "I", "L", null, null, null, null));
    out.add(new Language("peq", "Southern Pomo", "I", "L", null, null, "Pomo, Southern", null));
    out.add(new Language("pes", "Iranian Persian", "I", "L", null, null, "Persian, Iranian", null));
    out.add(new Language("pev", "Pémono", "I", "L", null, null, null, null));
    out.add(new Language("pex", "Petats", "I", "L", null, null, null, null));
    out.add(new Language("pey", "Petjo", "I", "L", null, null, null, null));
    out.add(new Language("pez", "Eastern Penan", "I", "L", null, null, "Penan, Eastern", null));
    out.add(new Language("pfa", "Pááfang", "I", "L", null, null, null, null));
    out.add(new Language("pfe", "Pere", "I", "L", null, null, null, null));
    out.add(new Language("pfl", "Pfaelzisch", "I", "L", null, null, null, null));
    out.add(new Language("pga", "Sudanese Creole Arabic", "I", "L", null, null, "Creole Arabic, Sudanese", null));
    out.add(new Language("pgd", "Gāndhārī", "I", "H", null, null, null, null));
    out.add(new Language("pgg", "Pangwali", "I", "L", null, null, null, null));
    out.add(new Language("pgi", "Pagi", "I", "L", null, null, null, null));
    out.add(new Language("pgk", "Rerep", "I", "L", null, null, null, null));
    out.add(new Language("pgl", "Primitive Irish", "I", "H", null, null, "Irish, Primitive", null));
    out.add(new Language("pgn", "Paelignian", "I", "H", null, null, null, null));
    out.add(new Language("pgs", "Pangseng", "I", "L", null, null, null, null));
    out.add(new Language("pgu", "Pagu", "I", "L", null, null, null, null));
    out.add(new Language("pgz", "Papua New Guinean Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("pha", "Pa-Hng", "I", "L", null, null, null, null));
    out.add(new Language("phd", "Phudagi", "I", "L", null, null, null, null));
    out.add(new Language("phg", "Phuong", "I", "L", null, null, null, null));
    out.add(new Language("phh", "Phukha", "I", "L", null, null, null, null));
    out.add(new Language("phj", "Pahari", "I", "L", null, null, null, null));
    out.add(new Language("phk", "Phake", "I", "L", null, null, null, null));
    out.add(new Language("phl", "Phalura", "I", "L", null, null, null, null));
    out.add(new Language("phm", "Phimbi", "I", "L", null, null, null, null));
    out.add(new Language("phn", "Phoenician", "I", "H", null, null, null, null));
    out.add(new Language("pho", "Phunoi", "I", "L", null, null, null, null));
    out.add(new Language("phq", "Phana'", "I", "L", null, null, null, null));
    out.add(new Language("phr", "Pahari-Potwari", "I", "L", null, null, null, null));
    out.add(new Language("pht", "Phu Thai", "I", "L", null, null, null, null));
    out.add(new Language("phu", "Phuan", "I", "L", null, null, null, null));
    out.add(new Language("phv", "Pahlavani", "I", "L", null, null, null, null));
    out.add(new Language("phw", "Phangduwali", "I", "L", null, null, null, null));
    out.add(new Language("pia", "Pima Bajo", "I", "L", null, null, null, null));
    out.add(new Language("pib", "Yine", "I", "L", null, null, null, null));
    out.add(new Language("pic", "Pinji", "I", "L", null, null, null, null));
    out.add(new Language("pid", "Piaroa", "I", "L", null, null, null, null));
    out.add(new Language("pie", "Piro", "I", "E", null, null, null, null));
    out.add(new Language("pif", "Pingelapese", "I", "L", null, null, null, null));
    out.add(new Language("pig", "Pisabo", "I", "L", null, null, null, null));
    out.add(new Language("pih", "Pitcairn-Norfolk", "I", "L", null, null, null, null));
    out.add(new Language("pij", "Pijao", "I", "E", null, null, null, null));
    out.add(new Language("pil", "Yom", "I", "L", null, null, null, null));
    out.add(new Language("pim", "Powhatan", "I", "E", null, null, null, null));
    out.add(new Language("pin", "Piame", "I", "L", null, null, null, null));
    out.add(new Language("pio", "Piapoco", "I", "L", null, null, null, null));
    out.add(new Language("pip", "Pero", "I", "L", null, null, null, null));
    out.add(new Language("pir", "Piratapuyo", "I", "L", null, null, null, null));
    out.add(new Language("pis", "Pijin", "I", "L", null, null, null, null));
    out.add(new Language("pit", "Pitta Pitta", "I", "E", null, null, null, null));
    out.add(new Language("piu", "Pintupi-Luritja", "I", "L", null, null, null, null));
    out.add(new Language("piv", "Pileni", "I", "L", null, null, null, null));
    out.add(new Language("piw", "Pimbwe", "I", "L", null, null, null, null));
    out.add(new Language("pix", "Piu", "I", "L", null, null, null, null));
    out.add(new Language("piy", "Piya-Kwonci", "I", "L", null, null, null, null));
    out.add(new Language("piz", "Pije", "I", "L", null, null, null, null));
    out.add(new Language("pjt", "Pitjantjatjara", "I", "L", null, null, null, null));
    out.add(new Language("pka", "Ardhamāgadhī Prākrit", "I", "H", null, null, "Prākrit, Ardhamāgadhī", null));
    out.add(new Language("pkb", "Pokomo", "I", "L", null, null, null, null));
    out.add(new Language("pkc", "Paekche", "I", "H", null, null, null, null));
    out.add(new Language("pkg", "Pak-Tong", "I", "L", null, null, null, null));
    out.add(new Language("pkh", "Pankhu", "I", "L", null, null, null, null));
    out.add(new Language("pkn", "Pakanha", "I", "L", null, null, null, null));
    out.add(new Language("pko", "Pökoot", "I", "L", null, null, null, null));
    out.add(new Language("pkp", "Pukapuka", "I", "L", null, null, null, null));
    out.add(new Language("pkr", "Attapady Kurumba", "I", "L", null, null, "Kurumba, Attapady", null));
    out.add(new Language("pks", "Pakistan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("pkt", "Maleng", "I", "L", null, null, null, null));
    out.add(new Language("pku", "Paku", "I", "L", null, null, null, null));
    out.add(new Language("pla", "Miani", "I", "L", null, null, null, null));
    out.add(new Language("plb", "Polonombauk", "I", "L", null, null, null, null));
    out.add(new Language("plc", "Central Palawano", "I", "L", null, null, "Palawano, Central", null));
    out.add(new Language("pld", "Polari", "I", "L", null, null, null, null));
    out.add(new Language("ple", "Palu'e", "I", "L", null, null, null, null));
    out.add(new Language("plg", "Pilagá", "I", "L", null, null, null, null));
    out.add(new Language("plh", "Paulohi", "I", "L", null, null, null, null));
    out.add(new Language("pli", "Pali", "I", "H", "pi", null, null, null));
    out.add(new Language("plk", "Kohistani Shina", "I", "L", null, null, "Shina, Kohistani", null));
    out.add(new Language("pll", "Shwe Palaung", "I", "L", null, null, "Palaung, Shwe", null));
    out.add(new Language("pln", "Palenquero", "I", "L", null, null, null, null));
    out.add(new Language("plo", "Oluta Popoluca", "I", "L", null, null, "Popoluca, Oluta", null));
    out.add(new Language("plq", "Palaic", "I", "H", null, null, null, null));
    out.add(new Language("plr", "Palaka Senoufo", "I", "L", null, null, "Senoufo, Palaka", null));
    out.add(new Language("pls", "San Marcos Tlacoyalco Popoloca", "I", "L", null, null, "Popoloca, San Marcos Tlacoyalco", null));
    out.add(new Language("plt", "Plateau Malagasy", "I", "L", null, null, "Malagasy, Plateau", null));
    out.add(new Language("plu", "Palikúr", "I", "L", null, null, null, null));
    out.add(new Language("plv", "Southwest Palawano", "I", "L", null, null, "Palawano, Southwest", null));
    out.add(new Language("plw", "Brooke's Point Palawano", "I", "L", null, null, "Palawano, Brooke's Point", null));
    out.add(new Language("ply", "Bolyu", "I", "L", null, null, null, null));
    out.add(new Language("plz", "Paluan", "I", "L", null, null, null, null));
    out.add(new Language("pma", "Paama", "I", "L", null, null, null, null));
    out.add(new Language("pmb", "Pambia", "I", "L", null, null, null, null));
    out.add(new Language("pmd", "Pallanganmiddang", "I", "E", null, null, null, null));
    out.add(new Language("pme", "Pwaamei", "I", "L", null, null, null, null));
    out.add(new Language("pmf", "Pamona", "I", "L", null, null, null, null));
    out.add(new Language("pmh", "Māhārāṣṭri Prākrit", "I", "H", null, null, "Prākrit, Māhārāṣṭri", null));
    out.add(new Language("pmi", "Northern Pumi", "I", "L", null, null, "Pumi, Northern", null));
    out.add(new Language("pmj", "Southern Pumi", "I", "L", null, null, "Pumi, Southern", null));
    out.add(new Language("pml", "Lingua Franca", "I", "E", null, null, null, null));
    out.add(new Language("pmm", "Pomo", "I", "L", null, null, null, null));
    out.add(new Language("pmn", "Pam", "I", "L", null, null, null, null));
    out.add(new Language("pmo", "Pom", "I", "L", null, null, null, null));
    out.add(new Language("pmq", "Northern Pame", "I", "L", null, null, "Pame, Northern", null));
    out.add(new Language("pmr", "Paynamar", "I", "L", null, null, null, null));
    out.add(new Language("pms", "Piemontese", "I", "L", null, null, null, null));
    out.add(new Language("pmt", "Tuamotuan", "I", "L", null, null, null, null));
    out.add(new Language("pmw", "Plains Miwok", "I", "L", null, null, "Miwok, Plains", null));
    out.add(new Language("pmx", "Poumei Naga", "I", "L", null, null, "Naga, Poumei", null));
    out.add(new Language("pmy", "Papuan Malay", "I", "L", null, null, "Malay, Papuan", null));
    out.add(new Language("pmz", "Southern Pame", "I", "E", null, null, "Pame, Southern", null));
    out.add(new Language("pna", "Punan Bah-Biau", "I", "L", null, null, null, null));
    out.add(new Language("pnb", "Western Panjabi", "I", "L", null, null, "Panjabi, Western", null));
    out.add(new Language("pnc", "Pannei", "I", "L", null, null, null, null));
    out.add(new Language("pnd", "Mpinda", "I", "L", null, null, null, null));
    out.add(new Language("pne", "Western Penan", "I", "L", null, null, "Penan, Western", null));
    out.add(new Language("png", "Pangu", "I", "L", null, null, null, null));
    out.add(new Language("pnh", "Penrhyn", "I", "L", null, null, null, null));
    out.add(new Language("pni", "Aoheng", "I", "L", null, null, null, null));
    out.add(new Language("pnj", "Pinjarup", "I", "E", null, null, null, null));
    out.add(new Language("pnk", "Paunaka", "I", "L", null, null, null, null));
    out.add(new Language("pnl", "Paleni", "I", "L", null, null, null, null));
    out.add(new Language("pnm", "Punan Batu 1", "I", "L", null, null, null, null));
    out.add(new Language("pnn", "Pinai-Hagahai", "I", "L", null, null, null, null));
    out.add(new Language("pno", "Panobo", "I", "E", null, null, null, null));
    out.add(new Language("pnp", "Pancana", "I", "L", null, null, null, null));
    out.add(new Language("pnq", "Pana (Burkina Faso)", "I", "L", null, null, null, null));
    out.add(new Language("pnr", "Panim", "I", "L", null, null, null, null));
    out.add(new Language("pns", "Ponosakan", "I", "L", null, null, null, null));
    out.add(new Language("pnt", "Pontic", "I", "L", null, null, null, null));
    out.add(new Language("pnu", "Jiongnai Bunu", "I", "L", null, null, "Bunu, Jiongnai", null));
    out.add(new Language("pnv", "Pinigura", "I", "L", null, null, null, null));
    out.add(new Language("pnw", "Banyjima", "I", "L", null, null, null, null));
    out.add(new Language("pnx", "Phong-Kniang", "I", "L", null, null, null, null));
    out.add(new Language("pny", "Pinyin", "I", "L", null, null, null, null));
    out.add(new Language("pnz", "Pana (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("poc", "Poqomam", "I", "L", null, null, null, null));
    out.add(new Language("poe", "San Juan Atzingo Popoloca", "I", "L", null, null, "Popoloca, San Juan Atzingo", null));
    out.add(new Language("pof", "Poke", "I", "L", null, null, null, null));
    out.add(new Language("pog", "Potiguára", "I", "E", null, null, null, null));
    out.add(new Language("poh", "Poqomchi'", "I", "L", null, null, null, null));
    out.add(new Language("poi", "Highland Popoluca", "I", "L", null, null, "Popoluca, Highland", null));
    out.add(new Language("pok", "Pokangá", "I", "L", null, null, null, null));
    out.add(new Language("pol", "Polish", "I", "L", "pl", null, null, null));
    out.add(new Language("pom", "Southeastern Pomo", "I", "L", null, null, "Pomo, Southeastern", null));
    out.add(new Language("pon", "Pohnpeian", "I", "L", null, null, null, null));
    out.add(new Language("poo", "Central Pomo", "I", "E", null, null, "Pomo, Central", null));
    out.add(new Language("pop", "Pwapwâ", "I", "L", null, null, null, null));
    out.add(new Language("poq", "Texistepec Popoluca", "I", "L", null, null, "Popoluca, Texistepec", null));
    out.add(new Language("por", "Portuguese", "I", "L", "pt", null, null, null));
    out.add(new Language("pos", "Sayula Popoluca", "I", "L", null, null, "Popoluca, Sayula", null));
    out.add(new Language("pot", "Potawatomi", "I", "L", null, null, null, null));
    out.add(new Language("pov", "Upper Guinea Crioulo", "I", "L", null, null, "Crioulo, Upper Guinea", null));
    out.add(new Language("pow", "San Felipe Otlaltepec Popoloca", "I", "L", null, null, "Popoloca, San Felipe Otlaltepec", null));
    out.add(new Language("pox", "Polabian", "I", "E", null, null, null, null));
    out.add(new Language("poy", "Pogolo", "I", "L", null, null, null, null));
    out.add(new Language("ppe", "Papi", "I", "L", null, null, null, null));
    out.add(new Language("ppi", "Paipai", "I", "L", null, null, null, null));
    out.add(new Language("ppk", "Uma", "I", "L", null, null, null, null));
    out.add(new Language("ppl", "Pipil", "I", "L", null, null, null, null));
    out.add(new Language("ppm", "Papuma", "I", "L", null, null, null, null));
    out.add(new Language("ppn", "Papapana", "I", "L", null, null, null, null));
    out.add(new Language("ppo", "Folopa", "I", "L", null, null, null, null));
    out.add(new Language("ppp", "Pelende", "I", "L", null, null, null, null));
    out.add(new Language("ppq", "Pei", "I", "L", null, null, null, null));
    out.add(new Language("pps", "San Luís Temalacayuca Popoloca", "I", "L", null, null, "Popoloca, San Luís Temalacayuca", null));
    out.add(new Language("ppt", "Pare", "I", "L", null, null, null, null));
    out.add(new Language("ppu", "Papora", "I", "E", null, null, null, null));
    out.add(new Language("pqa", "Pa'a", "I", "L", null, null, null, null));
    out.add(new Language("pqm", "Malecite-Passamaquoddy", "I", "L", null, null, null, null));
    out.add(new Language("prc", "Parachi", "I", "L", null, null, null, null));
    out.add(new Language("prd", "Parsi-Dari", "I", "L", null, null, null, null));
    out.add(new Language("pre", "Principense", "I", "L", null, null, null, null));
    out.add(new Language("prf", "Paranan", "I", "L", null, null, null, null));
    out.add(new Language("prg", "Prussian", "I", "L", null, null, null, null));
    out.add(new Language("prh", "Porohanon", "I", "L", null, null, null, null));
    out.add(new Language("pri", "Paicî", "I", "L", null, null, null, null));
    out.add(new Language("prk", "Parauk", "I", "L", null, null, null, null));
    out.add(new Language("prl", "Peruvian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("prm", "Kibiri", "I", "L", null, null, null, null));
    out.add(new Language("prn", "Prasuni", "I", "L", null, null, null, null));
    out.add(new Language("pro", "Old Provençal (to 1500)", "I", "H", null, null, "Provençal, Old (to 1500)", null));
    out.add(new Language("prq", "Ashéninka Perené", "I", "L", null, null, null, null));
    out.add(new Language("prr", "Puri", "I", "E", null, null, null, null));
    out.add(new Language("prs", "Dari", "I", "L", null, null, null, null));
    out.add(new Language("prt", "Phai", "I", "L", null, null, null, null));
    out.add(new Language("pru", "Puragi", "I", "L", null, null, null, null));
    out.add(new Language("prw", "Parawen", "I", "L", null, null, null, null));
    out.add(new Language("prx", "Purik", "I", "L", null, null, null, null));
    out.add(new Language("prz", "Providencia Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psa", "Asue Awyu", "I", "L", null, null, "Awyu, Asue", null));
    out.add(new Language("psc", "Iranian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psd", "Plains Indian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("pse", "Central Malay", "I", "L", null, null, "Malay, Central", null));
    out.add(new Language("psg", "Penang Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psh", "Southwest Pashai", "I", "L", null, null, "Pashai, Southwest", null));
    out.add(new Language("psi", "Southeast Pashai", "I", "L", null, null, "Pashai, Southeast", null));
    out.add(new Language("psl", "Puerto Rican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psm", "Pauserna", "I", "E", null, null, null, null));
    out.add(new Language("psn", "Panasuan", "I", "L", null, null, null, null));
    out.add(new Language("pso", "Polish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psp", "Philippine Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("psq", "Pasi", "I", "L", null, null, null, null));
    out.add(new Language("psr", "Portuguese Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("pss", "Kaulong", "I", "L", null, null, null, null));
    out.add(new Language("pst", "Central Pashto", "I", "L", null, null, "Pashto, Central", null));
    out.add(new Language("psu", "Sauraseni Prākrit", "I", "H", null, null, "Prākrit, Sauraseni", null));
    out.add(new Language("psw", "Port Sandwich", "I", "L", null, null, null, null));
    out.add(new Language("psy", "Piscataway", "I", "E", null, null, null, null));
    out.add(new Language("pta", "Pai Tavytera", "I", "L", null, null, null, null));
    out.add(new Language("pth", "Pataxó Hã-Ha-Hãe", "I", "E", null, null, null, null));
    out.add(new Language("pti", "Pindiini", "I", "L", null, null, null, null));
    out.add(new Language("ptn", "Patani", "I", "L", null, null, null, null));
    out.add(new Language("pto", "Zo'é", "I", "L", null, null, null, null));
    out.add(new Language("ptp", "Patep", "I", "L", null, null, null, null));
    out.add(new Language("ptq", "Pattapu", "I", "L", null, null, null, null));
    out.add(new Language("ptr", "Piamatsina", "I", "L", null, null, null, null));
    out.add(new Language("ptt", "Enrekang", "I", "L", null, null, null, null));
    out.add(new Language("ptu", "Bambam", "I", "L", null, null, null, null));
    out.add(new Language("ptv", "Port Vato", "I", "L", null, null, null, null));
    out.add(new Language("ptw", "Pentlatch", "I", "E", null, null, null, null));
    out.add(new Language("pty", "Pathiya", "I", "L", null, null, null, null));
    out.add(new Language("pua", "Western Highland Purepecha", "I", "L", null, null, "Purepecha, Western Highland", null));
    out.add(new Language("pub", "Purum", "I", "L", null, null, null, null));
    out.add(new Language("puc", "Punan Merap", "I", "L", null, null, null, null));
    out.add(new Language("pud", "Punan Aput", "I", "L", null, null, null, null));
    out.add(new Language("pue", "Puelche", "I", "E", null, null, null, null));
    out.add(new Language("puf", "Punan Merah", "I", "L", null, null, null, null));
    out.add(new Language("pug", "Phuie", "I", "L", null, null, null, null));
    out.add(new Language("pui", "Puinave", "I", "L", null, null, null, null));
    out.add(new Language("puj", "Punan Tubu", "I", "L", null, null, null, null));
    out.add(new Language("pum", "Puma", "I", "L", null, null, null, null));
    out.add(new Language("puo", "Puoc", "I", "L", null, null, null, null));
    out.add(new Language("pup", "Pulabu", "I", "L", null, null, null, null));
    out.add(new Language("puq", "Puquina", "I", "E", null, null, null, null));
    out.add(new Language("pur", "Puruborá", "I", "L", null, null, null, null));
    out.add(new Language("pus", "Pushto", "M", "L", "ps", null, null, null));
    out.add(new Language("put", "Putoh", "I", "L", null, null, null, null));
    out.add(new Language("puu", "Punu", "I", "L", null, null, null, null));
    out.add(new Language("puw", "Puluwatese", "I", "L", null, null, null, null));
    out.add(new Language("pux", "Puare", "I", "L", null, null, null, null));
    out.add(new Language("puy", "Purisimeño", "I", "E", null, null, null, null));
    out.add(new Language("pwa", "Pawaia", "I", "L", null, null, null, null));
    out.add(new Language("pwb", "Panawa", "I", "L", null, null, null, null));
    out.add(new Language("pwg", "Gapapaiwa", "I", "L", null, null, null, null));
    out.add(new Language("pwi", "Patwin", "I", "E", null, null, null, null));
    out.add(new Language("pwm", "Molbog", "I", "L", null, null, null, null));
    out.add(new Language("pwn", "Paiwan", "I", "L", null, null, null, null));
    out.add(new Language("pwo", "Pwo Western Karen", "I", "L", null, null, "Karen, Pwo Western", null));
    out.add(new Language("pwr", "Powari", "I", "L", null, null, null, null));
    out.add(new Language("pww", "Pwo Northern Karen", "I", "L", null, null, "Karen, Pwo Northern", null));
    out.add(new Language("pxm", "Quetzaltepec Mixe", "I", "L", null, null, "Mixe, Quetzaltepec", null));
    out.add(new Language("pye", "Pye Krumen", "I", "L", null, null, "Krumen, Pye", null));
    out.add(new Language("pym", "Fyam", "I", "L", null, null, null, null));
    out.add(new Language("pyn", "Poyanáwa", "I", "L", null, null, null, null));
    out.add(new Language("pys", "Paraguayan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("pyu", "Puyuma", "I", "L", null, null, null, null));
    out.add(new Language("pyx", "Pyu (Myanmar)", "I", "H", null, null, null, null));
    out.add(new Language("pyy", "Pyen", "I", "L", null, null, null, null));
    out.add(new Language("pze", "Pesse", "I", "L", null, null, null, null));
    out.add(new Language("pzh", "Pazeh", "I", "L", null, null, null, null));
    out.add(new Language("pzn", "Jejara Naga", "I", "L", null, null, "Naga, Jejara", null));
    out.add(new Language("qua", "Quapaw", "I", "L", null, null, null, null));
    out.add(new Language("qub", "Huallaga Huánuco Quechua", "I", "L", null, null, "Quechua, Huallaga Huánuco", null));
    out.add(new Language("quc", "K'iche'", "I", "L", null, null, null, null));
    out.add(new Language("qud", "Calderón Highland Quichua", "I", "L", null, null, "Quichua, Calderón Highland", null));
    out.add(new Language("que", "Quechua", "M", "L", "qu", null, null, null));
    out.add(new Language("quf", "Lambayeque Quechua", "I", "L", null, null, "Quechua, Lambayeque", null));
    out.add(new Language("qug", "Chimborazo Highland Quichua", "I", "L", null, null, "Quichua, Chimborazo Highland", null));
    out.add(new Language("quh", "South Bolivian Quechua", "I", "L", null, null, "Quechua, South Bolivian", null));
    out.add(new Language("qui", "Quileute", "I", "L", null, null, null, null));
    out.add(new Language("quk", "Chachapoyas Quechua", "I", "L", null, null, "Quechua, Chachapoyas", null));
    out.add(new Language("qul", "North Bolivian Quechua", "I", "L", null, null, "Quechua, North Bolivian", null));
    out.add(new Language("qum", "Sipacapense", "I", "L", null, null, null, null));
    out.add(new Language("qun", "Quinault", "I", "E", null, null, null, null));
    out.add(new Language("qup", "Southern Pastaza Quechua", "I", "L", null, null, "Quechua, Southern Pastaza", null));
    out.add(new Language("quq", "Quinqui", "I", "L", null, null, null, null));
    out.add(new Language("qur", "Yanahuanca Pasco Quechua", "I", "L", null, null, "Quechua, Yanahuanca Pasco", null));
    out.add(new Language("qus", "Santiago del Estero Quichua", "I", "L", null, null, "Quichua, Santiago del Estero", null));
    out.add(new Language("quv", "Sacapulteco", "I", "L", null, null, null, null));
    out.add(new Language("quw", "Tena Lowland Quichua", "I", "L", null, null, "Quichua, Tena Lowland", null));
    out.add(new Language("qux", "Yauyos Quechua", "I", "L", null, null, "Quechua, Yauyos", null));
    out.add(new Language("quy", "Ayacucho Quechua", "I", "L", null, null, "Quechua, Ayacucho", null));
    out.add(new Language("quz", "Cusco Quechua", "I", "L", null, null, "Quechua, Cusco", null));
    out.add(new Language("qva", "Ambo-Pasco Quechua", "I", "L", null, null, "Quechua, Ambo-Pasco", null));
    out.add(new Language("qvc", "Cajamarca Quechua", "I", "L", null, null, "Quechua, Cajamarca", null));
    out.add(new Language("qve", "Eastern Apurímac Quechua", "I", "L", null, null, "Quechua, Eastern Apurímac", null));
    out.add(new Language("qvh", "Huamalíes-Dos de Mayo Huánuco Quechua", "I", "L", null, null, "Quechua, Huamalíes-Dos de Mayo Huánuco", null));
    out.add(new Language("qvi", "Imbabura Highland Quichua", "I", "L", null, null, "Quichua, Imbabura Highland", null));
    out.add(new Language("qvj", "Loja Highland Quichua", "I", "L", null, null, "Quichua, Loja Highland", null));
    out.add(new Language("qvl", "Cajatambo North Lima Quechua", "I", "L", null, null, "Quechua, Cajatambo North Lima", null));
    out.add(new Language("qvm", "Margos-Yarowilca-Lauricocha Quechua", "I", "L", null, null, "Quechua, Margos-Yarowilca-Lauricocha", null));
  }
}
