// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 6500 to 6999 of {@link Language}.
 */
final class LanguageData13 {
  private LanguageData13() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("tod", "Toma", "I", "L", null, null, null, null));
    out.add(new Language("tof", "Gizrra", "I", "L", null, null, null, null));
    out.add(new Language("tog", "Tonga (Nyasa)", "I", "L", null, null, null, null));
    out.add(new Language("toh", "Gitonga", "I", "L", null, null, null, null));
    out.add(new Language("toi", "Tonga (Zambia)", "I", "L", null, null, null, null));
    out.add(new Language("toj", "Tojolabal", "I", "L", null, null, null, null));
    out.add(new Language("tok", "Toki Pona", "I", "C", null, null, null, null));
    out.add(new Language("tol", "Tolowa", "I", "E", null, null, null, null));
    out.add(new Language("tom", "Tombulu", "I", "L", null, null, null, null));
    out.add(new Language("ton", "Tonga (Tonga Islands)", "I", "L", "to", null, null, null));
    out.add(new Language("too", "Xicotepec De Juárez Totonac", "I", "L", null, null, "Totonac, Xicotepec De Juárez", null));
    out.add(new Language("top", "Papantla Totonac", "I", "L", null, null, "Totonac, Papantla", null));
    out.add(new Language("toq", "Toposa", "I", "L", null, null, null, null));
    out.add(new Language("tor", "Togbo-Vara Banda", "I", "L", null, null, "Banda, Togbo-Vara", null));
    out.add(new Language("tos", "Highland Totonac", "I", "L", null, null, "Totonac, Highland", null));
    out.add(new Language("tou", "Tho", "I", "L", null, null, null, null));
    out.add(new Language("tov", "Upper Taromi", "I", "L", null, null, "Taromi, Upper", null));
    out.add(new Language("tow", "Jemez", "I", "L", null, null, null, null));
    out.add(new Language("tox", "Tobian", "I", "L", null, null, null, null));
    out.add(new Language("toy", "Topoiyo", "I", "L", null, null, null, null));
    out.add(new Language("toz", "To", "I", "L", null, null, null, null));
    out.add(new Language("tpa", "Taupota", "I", "L", null, null, null, null));
    out.add(new Language("tpc", "Azoyú Me'phaa", "I", "L", null, null, "Me'phaa, Azoyú", null));
    out.add(new Language("tpe", "Tippera", "I", "L", null, null, null, null));
    out.add(new Language("tpf", "Tarpia", "I", "L", null, null, null, null));
    out.add(new Language("tpg", "Kula", "I", "L", null, null, null, null));
    out.add(new Language("tpi", "Tok Pisin", "I", "L", null, null, null, null));
    out.add(new Language("tpj", "Tapieté", "I", "L", null, null, null, null));
    out.add(new Language("tpk", "Tupinikin", "I", "E", null, null, null, null));
    out.add(new Language("tpl", "Tlacoapa Me'phaa", "I", "L", null, null, "Me'phaa, Tlacoapa", null));
    out.add(new Language("tpm", "Tampulma", "I", "L", null, null, null, null));
    out.add(new Language("tpn", "Tupinambá", "I", "E", null, null, null, null));
    out.add(new Language("tpo", "Tai Pao", "I", "L", null, null, null, null));
    out.add(new Language("tpp", "Pisaflores Tepehua", "I", "L", null, null, "Tepehua, Pisaflores", null));
    out.add(new Language("tpq", "Tukpa", "I", "L", null, null, null, null));
    out.add(new Language("tpr", "Tuparí", "I", "L", null, null, null, null));
    out.add(new Language("tpt", "Tlachichilco Tepehua", "I", "L", null, null, "Tepehua, Tlachichilco", null));
    out.add(new Language("tpu", "Tampuan", "I", "L", null, null, null, null));
    out.add(new Language("tpv", "Tanapag", "I", "L", null, null, null, null));
    out.add(new Language("tpx", "Acatepec Me'phaa", "I", "L", null, null, "Me'phaa, Acatepec", null));
    out.add(new Language("tpy", "Trumai", "I", "L", null, null, null, null));
    out.add(new Language("tpz", "Tinputz", "I", "L", null, null, null, null));
    out.add(new Language("tqb", "Tembé", "I", "L", null, null, null, null));
    out.add(new Language("tql", "Lehali", "I", "L", null, null, null, null));
    out.add(new Language("tqm", "Turumsa", "I", "L", null, null, null, null));
    out.add(new Language("tqn", "Tenino", "I", "L", null, null, null, null));
    out.add(new Language("tqo", "Toaripi", "I", "L", null, null, null, null));
    out.add(new Language("tqp", "Tomoip", "I", "L", null, null, null, null));
    out.add(new Language("tqq", "Tunni", "I", "L", null, null, null, null));
    out.add(new Language("tqr", "Torona", "I", "E", null, null, null, null));
    out.add(new Language("tqt", "Western Totonac", "I", "L", null, null, "Totonac, Western", null));
    out.add(new Language("tqu", "Touo", "I", "L", null, null, null, null));
    out.add(new Language("tqw", "Tonkawa", "I", "E", null, null, null, null));
    out.add(new Language("tra", "Tirahi", "I", "L", null, null, null, null));
    out.add(new Language("trb", "Terebu", "I", "L", null, null, null, null));
    out.add(new Language("trc", "Copala Triqui", "I", "L", null, null, "Triqui, Copala", null));
    out.add(new Language("trd", "Turi", "I", "L", null, null, null, null));
    out.add(new Language("tre", "East Tarangan", "I", "L", null, null, "Tarangan, East", null));
    out.add(new Language("trf", "Trinidadian Creole English", "I", "L", null, null, "Creole English, Trinidadian", null));
    out.add(new Language("trg", "Lishán Didán", "I", "L", null, null, null, null));
    out.add(new Language("trh", "Turaka", "I", "L", null, null, null, null));
    out.add(new Language("tri", "Trió", "I", "L", null, null, null, null));
    out.add(new Language("trj", "Toram", "I", "L", null, null, null, null));
    out.add(new Language("trl", "Traveller Scottish", "I", "L", null, null, "Scottish, Traveller", null));
    out.add(new Language("trm", "Tregami", "I", "L", null, null, null, null));
    out.add(new Language("trn", "Trinitario", "I", "L", null, null, null, null));
    out.add(new Language("tro", "Tarao Naga", "I", "L", null, null, "Naga, Tarao", null));
    out.add(new Language("trp", "Kok Borok", "I", "L", null, null, null, null));
    out.add(new Language("trq", "San Martín Itunyoso Triqui", "I", "L", null, null, "Triqui, San Martín Itunyoso", null));
    out.add(new Language("trr", "Taushiro", "I", "L", null, null, null, null));
    out.add(new Language("trs", "Chicahuaxtla Triqui", "I", "L", null, null, "Triqui, Chicahuaxtla", null));
    out.add(new Language("trt", "Tunggare", "I", "L", null, null, null, null));
    out.add(new Language("tru", "Turoyo", "I", "L", null, null, null, null));
    out.add(new Language("trv", "Sediq", "I", "L", null, null, null, null));
    out.add(new Language("trw", "Torwali", "I", "L", null, null, null, null));
    out.add(new Language("trx", "Tringgus-Sembaan Bidayuh", "I", "L", null, null, "Bidayuh, Tringgus-Sembaan", null));
    out.add(new Language("try", "Turung", "I", "E", null, null, null, null));
    out.add(new Language("trz", "Torá", "I", "E", null, null, null, null));
    out.add(new Language("tsa", "Tsaangi", "I", "L", null, null, null, null));
    out.add(new Language("tsb", "Tsamai", "I", "L", null, null, null, null));
    out.add(new Language("tsc", "Tswa", "I", "L", null, null, null, null));
    out.add(new Language("tsd", "Tsakonian", "I", "L", null, null, null, null));
    out.add(new Language("tse", "Tunisian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tsg", "Tausug", "I", "L", null, null, null, null));
    out.add(new Language("tsh", "Tsuvan", "I", "L", null, null, null, null));
    out.add(new Language("tsi", "Tsimshian", "I", "L", null, null, null, null));
    out.add(new Language("tsj", "Tshangla", "I", "L", null, null, null, null));
    out.add(new Language("tsk", "Tseku", "I", "L", null, null, null, null));
    out.add(new Language("tsl", "Ts'ün-Lao", "I", "L", null, null, null, null));
    out.add(new Language("tsm", "Turkish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tsn", "Tswana", "I", "L", "tn", null, null, null));
    out.add(new Language("tso", "Tsonga", "I", "L", "ts", null, null, null));
    out.add(new Language("tsp", "Northern Toussian", "I", "L", null, null, "Toussian, Northern", null));
    out.add(new Language("tsq", "Thai Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tsr", "Akei", "I", "L", null, null, null, null));
    out.add(new Language("tss", "Taiwan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tst", "Tondi Songway Kiini", "I", "L", null, null, "Songway Kiini, Tondi", null));
    out.add(new Language("tsu", "Tsou", "I", "L", null, null, null, null));
    out.add(new Language("tsv", "Tsogo", "I", "L", null, null, null, null));
    out.add(new Language("tsw", "Tsishingini", "I", "L", null, null, null, null));
    out.add(new Language("tsx", "Mubami", "I", "L", null, null, null, null));
    out.add(new Language("tsy", "Tebul Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tsz", "Purepecha", "I", "L", null, null, null, null));
    out.add(new Language("tta", "Tutelo", "I", "E", null, null, null, null));
    out.add(new Language("ttb", "Gaa", "I", "L", null, null, null, null));
    out.add(new Language("ttc", "Tektiteko", "I", "L", null, null, null, null));
    out.add(new Language("ttd", "Tauade", "I", "L", null, null, null, null));
    out.add(new Language("tte", "Bwanabwana", "I", "L", null, null, null, null));
    out.add(new Language("ttf", "Tuotomb", "I", "L", null, null, null, null));
    out.add(new Language("ttg", "Tutong", "I", "L", null, null, null, null));
    out.add(new Language("tth", "Upper Ta'oih", "I", "L", null, null, "Ta'oih, Upper", null));
    out.add(new Language("tti", "Tobati", "I", "L", null, null, null, null));
    out.add(new Language("ttj", "Tooro", "I", "L", null, null, null, null));
    out.add(new Language("ttk", "Totoro", "I", "L", null, null, null, null));
    out.add(new Language("ttl", "Totela", "I", "L", null, null, null, null));
    out.add(new Language("ttm", "Northern Tutchone", "I", "L", null, null, "Tutchone, Northern", null));
    out.add(new Language("ttn", "Towei", "I", "L", null, null, null, null));
    out.add(new Language("tto", "Lower Ta'oih", "I", "L", null, null, "Ta'oih, Lower", null));
    out.add(new Language("ttp", "Tombelala", "I", "L", null, null, null, null));
    out.add(new Language("ttq", "Tawallammat Tamajaq", "I", "L", null, null, "Tamajaq, Tawallammat", null));
    out.add(new Language("ttr", "Tera", "I", "L", null, null, null, null));
    out.add(new Language("tts", "Northeastern Thai", "I", "L", null, null, "Thai, Northeastern", null));
    out.add(new Language("ttt", "Muslim Tat", "I", "L", null, null, "Tat, Muslim", null));
    out.add(new Language("ttu", "Torau", "I", "L", null, null, null, null));
    out.add(new Language("ttv", "Titan", "I", "L", null, null, null, null));
    out.add(new Language("ttw", "Long Wat", "I", "L", null, null, null, null));
    out.add(new Language("tty", "Sikaritai", "I", "L", null, null, null, null));
    out.add(new Language("ttz", "Tsum", "I", "L", null, null, null, null));
    out.add(new Language("tua", "Wiarumus", "I", "L", null, null, null, null));
    out.add(new Language("tub", "Tübatulabal", "I", "E", null, null, null, null));
    out.add(new Language("tuc", "Mutu", "I", "L", null, null, null, null));
    out.add(new Language("tud", "Tuxá", "I", "E", null, null, null, null));
    out.add(new Language("tue", "Tuyuca", "I", "L", null, null, null, null));
    out.add(new Language("tuf", "Central Tunebo", "I", "L", null, null, "Tunebo, Central", null));
    out.add(new Language("tug", "Tunia", "I", "L", null, null, null, null));
    out.add(new Language("tuh", "Taulil", "I", "L", null, null, null, null));
    out.add(new Language("tui", "Tupuri", "I", "L", null, null, null, null));
    out.add(new Language("tuj", "Tugutil", "I", "L", null, null, null, null));
    out.add(new Language("tuk", "Turkmen", "I", "L", "tk", null, null, null));
    out.add(new Language("tul", "Tula", "I", "L", null, null, null, null));
    out.add(new Language("tum", "Tumbuka", "I", "L", null, null, null, null));
    out.add(new Language("tun", "Tunica", "I", "L", null, null, null, null));
    out.add(new Language("tuo", "Tucano", "I", "L", null, null, null, null));
    out.add(new Language("tuq", "Tedaga", "I", "L", null, null, null, null));
    out.add(new Language("tur", "Turkish", "I", "L", "tr", null, null, null));
    out.add(new Language("tus", "Tuscarora", "I", "L", null, null, null, null));
    out.add(new Language("tuu", "Tututni", "I", "L", null, null, null, null));
    out.add(new Language("tuv", "Turkana", "I", "L", null, null, null, null));
    out.add(new Language("tux", "Tuxináwa", "I", "E", null, null, null, null));
    out.add(new Language("tuy", "Tugen", "I", "L", null, null, null, null));
    out.add(new Language("tuz", "Turka", "I", "L", null, null, null, null));
    out.add(new Language("tva", "Vaghua", "I", "L", null, null, null, null));
    out.add(new Language("tvd", "Tsuvadi", "I", "L", null, null, null, null));
    out.add(new Language("tve", "Te'un", "I", "L", null, null, null, null));
    out.add(new Language("tvi", "Tulai", "I", "L", null, null, null, null));
    out.add(new Language("tvk", "Southeast Ambrym", "I", "L", null, null, "Ambrym, Southeast", null));
    out.add(new Language("tvl", "Tuvalu", "I", "L", null, null, null, null));
    out.add(new Language("tvm", "Tela-Masbuar", "I", "L", null, null, null, null));
    out.add(new Language("tvn", "Tavoyan", "I", "L", null, null, null, null));
    out.add(new Language("tvo", "Tidore", "I", "L", null, null, null, null));
    out.add(new Language("tvs", "Taveta", "I", "L", null, null, null, null));
    out.add(new Language("tvt", "Tutsa Naga", "I", "L", null, null, "Naga, Tutsa", null));
    out.add(new Language("tvu", "Tunen", "I", "L", null, null, null, null));
    out.add(new Language("tvw", "Sedoa", "I", "L", null, null, null, null));
    out.add(new Language("tvx", "Taivoan", "I", "E", null, null, null, null));
    out.add(new Language("tvy", "Timor Pidgin", "I", "E", null, null, "Pidgin, Timor", null));
    out.add(new Language("twa", "Twana", "I", "E", null, null, null, null));
    out.add(new Language("twb", "Western Tawbuid", "I", "L", null, null, "Tawbuid, Western", null));
    out.add(new Language("twc", "Teshenawa", "I", "E", null, null, null, null));
    out.add(new Language("twd", "Twents", "I", "L", null, null, null, null));
    out.add(new Language("twe", "Tewa (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("twf", "Northern Tiwa", "I", "L", null, null, "Tiwa, Northern", null));
    out.add(new Language("twg", "Tereweng", "I", "L", null, null, null, null));
    out.add(new Language("twh", "Tai Dón", "I", "L", null, null, null, null));
    out.add(new Language("twi", "Twi", "I", "L", "tw", null, null, null));
    out.add(new Language("twl", "Tawara", "I", "L", null, null, null, null));
    out.add(new Language("twm", "Tawang Monpa", "I", "L", null, null, "Monpa, Tawang", null));
    out.add(new Language("twn", "Twendi", "I", "L", null, null, null, null));
    out.add(new Language("two", "Tswapong", "I", "L", null, null, null, null));
    out.add(new Language("twp", "Ere", "I", "L", null, null, null, null));
    out.add(new Language("twq", "Tasawaq", "I", "L", null, null, null, null));
    out.add(new Language("twr", "Southwestern Tarahumara", "I", "L", null, null, "Tarahumara, Southwestern", null));
    out.add(new Language("twt", "Turiwára", "I", "E", null, null, null, null));
    out.add(new Language("twu", "Termanu", "I", "L", null, null, null, null));
    out.add(new Language("tww", "Tuwari", "I", "L", null, null, null, null));
    out.add(new Language("twx", "Tewe", "I", "L", null, null, null, null));
    out.add(new Language("twy", "Tawoyan", "I", "L", null, null, null, null));
    out.add(new Language("txa", "Tombonuo", "I", "L", null, null, null, null));
    out.add(new Language("txb", "Tokharian B", "I", "H", null, null, null, null));
    out.add(new Language("txc", "Tsetsaut", "I", "E", null, null, null, null));
    out.add(new Language("txe", "Totoli", "I", "L", null, null, null, null));
    out.add(new Language("txg", "Tangut", "I", "H", null, null, null, null));
    out.add(new Language("txh", "Thracian", "I", "H", null, null, null, null));
    out.add(new Language("txi", "Ikpeng", "I", "L", null, null, null, null));
    out.add(new Language("txj", "Tarjumo", "I", "L", null, null, null, null));
    out.add(new Language("txm", "Tomini", "I", "L", null, null, null, null));
    out.add(new Language("txn", "West Tarangan", "I", "L", null, null, "Tarangan, West", null));
    out.add(new Language("txo", "Toto", "I", "L", null, null, null, null));
    out.add(new Language("txq", "Tii", "I", "L", null, null, null, null));
    out.add(new Language("txr", "Tartessian", "I", "H", null, null, null, null));
    out.add(new Language("txs", "Tonsea", "I", "L", null, null, null, null));
    out.add(new Language("txt", "Citak", "I", "L", null, null, null, null));
    out.add(new Language("txu", "Kayapó", "I", "L", null, null, null, null));
    out.add(new Language("txx", "Tatana", "I", "L", null, null, null, null));
    out.add(new Language("txy", "Tanosy Malagasy", "I", "L", null, null, "Malagasy, Tanosy", null));
    out.add(new Language("tya", "Tauya", "I", "L", null, null, null, null));
    out.add(new Language("tye", "Kyanga", "I", "L", null, null, null, null));
    out.add(new Language("tyh", "O'du", "I", "L", null, null, null, null));
    out.add(new Language("tyi", "Teke-Tsaayi", "I", "L", null, null, null, null));
    out.add(new Language("tyj", "Tai Do", "I", "L", null, null, null, null));
    out.add(new Language("tyl", "Thu Lao", "I", "L", null, null, null, null));
    out.add(new Language("tyn", "Kombai", "I", "L", null, null, null, null));
    out.add(new Language("typ", "Thaypan", "I", "E", null, null, null, null));
    out.add(new Language("tyr", "Tai Daeng", "I", "L", null, null, null, null));
    out.add(new Language("tys", "Tày Sa Pa", "I", "L", null, null, null, null));
    out.add(new Language("tyt", "Tày Tac", "I", "L", null, null, null, null));
    out.add(new Language("tyu", "Kua", "I", "L", null, null, null, null));
    out.add(new Language("tyv", "Tuvinian", "I", "L", null, null, null, null));
    out.add(new Language("tyx", "Teke-Tyee", "I", "L", null, null, null, null));
    out.add(new Language("tyy", "Tiyaa", "I", "L", null, null, null, null));
    out.add(new Language("tyz", "Tày", "I", "L", null, null, null, null));
    out.add(new Language("tza", "Tanzanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("tzh", "Tzeltal", "I", "L", null, null, null, null));
    out.add(new Language("tzj", "Tz'utujil", "I", "L", null, null, null, null));
    out.add(new Language("tzl", "Talossan", "I", "C", null, null, null, null));
    out.add(new Language("tzm", "Central Atlas Tamazight", "I", "L", null, null, "Tamazight, Central Atlas", null));
    out.add(new Language("tzn", "Tugun", "I", "L", null, null, null, null));
    out.add(new Language("tzo", "Tzotzil", "I", "L", null, null, null, null));
    out.add(new Language("tzx", "Tabriak", "I", "L", null, null, null, null));
    out.add(new Language("uam", "Uamué", "I", "E", null, null, null, null));
    out.add(new Language("uan", "Kuan", "I", "L", null, null, null, null));
    out.add(new Language("uar", "Tairuma", "I", "L", null, null, null, null));
    out.add(new Language("uba", "Ubang", "I", "L", null, null, null, null));
    out.add(new Language("ubi", "Ubi", "I", "L", null, null, null, null));
    out.add(new Language("ubl", "Buhi'non Bikol", "I", "L", null, null, "Bikol, Buhi'non", null));
    out.add(new Language("ubr", "Ubir", "I", "L", null, null, null, null));
    out.add(new Language("ubu", "Umbu-Ungu", "I", "L", null, null, null, null));
    out.add(new Language("uby", "Ubykh", "I", "E", null, null, null, null));
    out.add(new Language("uda", "Uda", "I", "L", null, null, null, null));
    out.add(new Language("ude", "Udihe", "I", "L", null, null, null, null));
    out.add(new Language("udg", "Muduga", "I", "L", null, null, null, null));
    out.add(new Language("udi", "Udi", "I", "L", null, null, null, null));
    out.add(new Language("udj", "Ujir", "I", "L", null, null, null, null));
    out.add(new Language("udl", "Wuzlam", "I", "L", null, null, null, null));
    out.add(new Language("udm", "Udmurt", "I", "L", null, null, null, null));
    out.add(new Language("udu", "Uduk", "I", "L", null, null, null, null));
    out.add(new Language("ues", "Kioko", "I", "L", null, null, null, null));
    out.add(new Language("ufi", "Ufim", "I", "L", null, null, null, null));
    out.add(new Language("uga", "Ugaritic", "I", "H", null, null, null, null));
    out.add(new Language("ugb", "Kuku-Ugbanh", "I", "E", null, null, null, null));
    out.add(new Language("uge", "Ughele", "I", "L", null, null, null, null));
    out.add(new Language("ugh", "Kubachi", "I", "L", null, null, null, null));
    out.add(new Language("ugn", "Ugandan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ugo", "Ugong", "I", "L", null, null, null, null));
    out.add(new Language("ugy", "Uruguayan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("uha", "Uhami", "I", "L", null, null, null, null));
    out.add(new Language("uhn", "Damal", "I", "L", null, null, null, null));
    out.add(new Language("uig", "Uighur", "I", "L", "ug", null, null, null));
    out.add(new Language("uis", "Uisai", "I", "L", null, null, null, null));
    out.add(new Language("uiv", "Iyive", "I", "L", null, null, null, null));
    out.add(new Language("uji", "Tanjijili", "I", "L", null, null, null, null));
    out.add(new Language("uka", "Kaburi", "I", "L", null, null, null, null));
    out.add(new Language("ukg", "Ukuriguma", "I", "L", null, null, null, null));
    out.add(new Language("ukh", "Ukhwejo", "I", "L", null, null, null, null));
    out.add(new Language("uki", "Kui (India)", "I", "L", null, null, null, null));
    out.add(new Language("ukk", "Muak Sa-aak", "I", "L", null, null, null, null));
    out.add(new Language("ukl", "Ukrainian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ukp", "Ukpe-Bayobiri", "I", "L", null, null, null, null));
    out.add(new Language("ukq", "Ukwa", "I", "L", null, null, null, null));
    out.add(new Language("ukr", "Ukrainian", "I", "L", "uk", null, null, null));
    out.add(new Language("uks", "Urubú-Kaapor Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("uku", "Ukue", "I", "L", null, null, null, null));
    out.add(new Language("ukv", "Kuku", "I", "L", null, null, null, null));
    out.add(new Language("ukw", "Ukwuani-Aboh-Ndoni", "I", "L", null, null, null, null));
    out.add(new Language("uky", "Kuuk-Yak", "I", "E", null, null, null, null));
    out.add(new Language("ula", "Fungwa", "I", "L", null, null, null, null));
    out.add(new Language("ulb", "Ulukwumi", "I", "L", null, null, null, null));
    out.add(new Language("ulc", "Ulch", "I", "L", null, null, null, null));
    out.add(new Language("ule", "Lule", "I", "E", null, null, null, null));
    out.add(new Language("ulf", "Usku", "I", "L", null, null, null, null));
    out.add(new Language("uli", "Ulithian", "I", "L", null, null, null, null));
    out.add(new Language("ulk", "Meriam Mir", "I", "L", null, null, null, null));
    out.add(new Language("ull", "Ullatan", "I", "L", null, null, null, null));
    out.add(new Language("ulm", "Ulumanda'", "I", "L", null, null, null, null));
    out.add(new Language("uln", "Unserdeutsch", "I", "L", null, null, null, null));
    out.add(new Language("ulu", "Uma' Lung", "I", "L", null, null, null, null));
    out.add(new Language("ulw", "Ulwa", "I", "L", null, null, null, null));
    out.add(new Language("uly", "Buli", "I", "L", null, null, null, null));
    out.add(new Language("uma", "Umatilla", "I", "L", null, null, null, null));
    out.add(new Language("umb", "Umbundu", "I", "L", null, null, null, null));
    out.add(new Language("umc", "Marrucinian", "I", "H", null, null, null, null));
    out.add(new Language("umd", "Umbindhamu", "I", "E", null, null, null, null));
    out.add(new Language("umg", "Morrobalama", "I", "E", null, null, null, null));
    out.add(new Language("umi", "Ukit", "I", "L", null, null, null, null));
    out.add(new Language("umm", "Umon", "I", "L", null, null, null, null));
    out.add(new Language("umn", "Makyan Naga", "I", "L", null, null, "Naga, Makyan", null));
    out.add(new Language("umo", "Umotína", "I", "E", null, null, null, null));
    out.add(new Language("ump", "Umpila", "I", "L", null, null, null, null));
    out.add(new Language("umr", "Umbugarla", "I", "E", null, null, null, null));
    out.add(new Language("ums", "Pendau", "I", "L", null, null, null, null));
    out.add(new Language("umu", "Munsee", "I", "L", null, null, null, null));
    out.add(new Language("una", "North Watut", "I", "L", null, null, "Watut, North", null));
    out.add(new Language("und", "Undetermined", "S", "S", null, null, null, null));
    out.add(new Language("une", "Uneme", "I", "L", null, null, null, null));
    out.add(new Language("ung", "Ngarinyin", "I", "L", null, null, null, null));
    out.add(new Language("uni", "Uni", "I", "L", null, null, null, null));
    out.add(new Language("unk", "Enawené-Nawé", "I", "L", null, null, null, null));
    out.add(new Language("unm", "Unami", "I", "E", null, null, null, null));
    out.add(new Language("unn", "Kurnai", "I", "L", null, null, null, null));
    out.add(new Language("unr", "Mundari", "I", "L", null, null, null, null));
    out.add(new Language("unu", "Unubahe", "I", "L", null, null, null, null));
    out.add(new Language("unx", "Munda", "I", "L", null, null, null, null));
    out.add(new Language("unz", "Unde Kaili", "I", "L", null, null, "Kaili, Unde", null));
    out.add(new Language("uon", "Kulon", "I", "E", null, null, null, null));
    out.add(new Language("upi", "Umeda", "I", "L", null, null, null, null));
    out.add(new Language("upv", "Uripiv-Wala-Rano-Atchin", "I", "L", null, null, null, null));
    out.add(new Language("ura", "Urarina", "I", "L", null, null, null, null));
    out.add(new Language("urb", "Urubú-Kaapor", "I", "L", null, null, null, null));
    out.add(new Language("urc", "Urningangg", "I", "E", null, null, null, null));
    out.add(new Language("urd", "Urdu", "I", "L", "ur", null, null, null));
    out.add(new Language("ure", "Uru", "I", "L", null, null, null, null));
    out.add(new Language("urf", "Uradhi", "I", "E", null, null, null, null));
    out.add(new Language("urg", "Urigina", "I", "L", null, null, null, null));
    out.add(new Language("urh", "Urhobo", "I", "L", null, null, null, null));
    out.add(new Language("uri", "Urim", "I", "L", null, null, null, null));
    out.add(new Language("urk", "Urak Lawoi'", "I", "L", null, null, null, null));
    out.add(new Language("url", "Urali", "I", "L", null, null, null, null));
    out.add(new Language("urm", "Urapmin", "I", "L", null, null, null, null));
    out.add(new Language("urn", "Uruangnirin", "I", "L", null, null, null, null));
    out.add(new Language("uro", "Ura (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("urp", "Uru-Pa-In", "I", "L", null, null, null, null));
    out.add(new Language("urr", "Lehalurup", "I", "L", null, null, null, null));
    out.add(new Language("urt", "Urat", "I", "L", null, null, null, null));
    out.add(new Language("uru", "Urumi", "I", "E", null, null, null, null));
    out.add(new Language("urv", "Uruava", "I", "E", null, null, null, null));
    out.add(new Language("urw", "Sop", "I", "L", null, null, null, null));
    out.add(new Language("urx", "Urimo", "I", "L", null, null, null, null));
    out.add(new Language("ury", "Orya", "I", "L", null, null, null, null));
    out.add(new Language("urz", "Uru-Eu-Wau-Wau", "I", "L", null, null, null, null));
    out.add(new Language("usa", "Usarufa", "I", "L", null, null, null, null));
    out.add(new Language("ush", "Ushojo", "I", "L", null, null, null, null));
    out.add(new Language("usi", "Usui", "I", "L", null, null, null, null));
    out.add(new Language("usk", "Usaghade", "I", "L", null, null, null, null));
    out.add(new Language("usp", "Uspanteco", "I", "L", null, null, null, null));
    out.add(new Language("uss", "us-Saare", "I", "L", null, null, null, null));
    out.add(new Language("usu", "Uya", "I", "L", null, null, null, null));
    out.add(new Language("uta", "Otank", "I", "L", null, null, null, null));
    out.add(new Language("ute", "Ute-Southern Paiute", "I", "L", null, null, null, null));
    out.add(new Language("uth", "ut-Hun", "I", "L", null, null, null, null));
    out.add(new Language("utp", "Amba (Solomon Islands)", "I", "L", null, null, null, null));
    out.add(new Language("utr", "Etulo", "I", "L", null, null, null, null));
    out.add(new Language("utu", "Utu", "I", "L", null, null, null, null));
    out.add(new Language("uum", "Urum", "I", "L", null, null, null, null));
    out.add(new Language("uur", "Ura (Vanuatu)", "I", "L", null, null, null, null));
    out.add(new Language("uuu", "U", "I", "L", null, null, null, null));
    out.add(new Language("uve", "West Uvean", "I", "L", null, null, "Uvean, West", null));
    out.add(new Language("uvh", "Uri", "I", "L", null, null, null, null));
    out.add(new Language("uvl", "Lote", "I", "L", null, null, null, null));
    out.add(new Language("uwa", "Kuku-Uwanh", "I", "L", null, null, null, null));
    out.add(new Language("uya", "Doko-Uyanga", "I", "L", null, null, null, null));
    out.add(new Language("uzb", "Uzbek", "M", "L", "uz", null, null, null));
    out.add(new Language("uzn", "Northern Uzbek", "I", "L", null, null, "Uzbek, Northern", null));
    out.add(new Language("uzs", "Southern Uzbek", "I", "L", null, null, "Uzbek, Southern", null));
    out.add(new Language("vaa", "Vaagri Booli", "I", "L", null, null, null, null));
    out.add(new Language("vae", "Vale", "I", "L", null, null, null, null));
    out.add(new Language("vaf", "Vafsi", "I", "L", null, null, null, null));
    out.add(new Language("vag", "Vagla", "I", "L", null, null, null, null));
    out.add(new Language("vah", "Varhadi-Nagpuri", "I", "L", null, null, null, null));
    out.add(new Language("vai", "Vai", "I", "L", null, null, null, null));
    out.add(new Language("vaj", "Sekele", "I", "L", null, null, null, null));
    out.add(new Language("val", "Vehes", "I", "L", null, null, null, null));
    out.add(new Language("vam", "Vanimo", "I", "L", null, null, null, null));
    out.add(new Language("van", "Valman", "I", "L", null, null, null, null));
    out.add(new Language("vao", "Vao", "I", "L", null, null, null, null));
    out.add(new Language("vap", "Vaiphei", "I", "L", null, null, null, null));
    out.add(new Language("var", "Huarijio", "I", "L", null, null, null, null));
    out.add(new Language("vas", "Vasavi", "I", "L", null, null, null, null));
    out.add(new Language("vau", "Vanuma", "I", "L", null, null, null, null));
    out.add(new Language("vav", "Varli", "I", "L", null, null, null, null));
    out.add(new Language("vay", "Wayu", "I", "L", null, null, null, null));
    out.add(new Language("vbb", "Southeast Babar", "I", "L", null, null, "Babar, Southeast", null));
    out.add(new Language("vbk", "Southwestern Bontok", "I", "L", null, null, "Bontok, Southwestern", null));
    out.add(new Language("vec", "Venetian", "I", "L", null, null, null, null));
    out.add(new Language("ved", "Veddah", "I", "L", null, null, null, null));
    out.add(new Language("vel", "Veluws", "I", "L", null, null, null, null));
    out.add(new Language("vem", "Vemgo-Mabas", "I", "L", null, null, null, null));
    out.add(new Language("ven", "Venda", "I", "L", "ve", null, null, null));
    out.add(new Language("veo", "Ventureño", "I", "E", null, null, null, null));
    out.add(new Language("vep", "Veps", "I", "L", null, null, null, null));
    out.add(new Language("ver", "Mom Jango", "I", "L", null, null, null, null));
    out.add(new Language("vgr", "Vaghri", "I", "L", null, null, null, null));
    out.add(new Language("vgt", "Vlaamse Gebarentaal", "I", "L", null, null, null, null));
    out.add(new Language("vic", "Virgin Islands Creole English", "I", "L", null, null, "Creole English, Virgin Islands", null));
    out.add(new Language("vid", "Vidunda", "I", "L", null, null, null, null));
    out.add(new Language("vie", "Vietnamese", "I", "L", "vi", null, null, null));
    out.add(new Language("vif", "Vili", "I", "L", null, null, null, null));
    out.add(new Language("vig", "Viemo", "I", "L", null, null, null, null));
    out.add(new Language("vil", "Vilela", "I", "L", null, null, null, null));
    out.add(new Language("vin", "Vinza", "I", "L", null, null, null, null));
    out.add(new Language("vis", "Vishavan", "I", "L", null, null, null, null));
    out.add(new Language("vit", "Viti", "I", "L", null, null, null, null));
    out.add(new Language("viv", "Iduna", "I", "L", null, null, null, null));
    out.add(new Language("vjk", "Bajjika", "I", "L", null, null, null, null));
    out.add(new Language("vka", "Kariyarra", "I", "E", null, null, null, null));
    out.add(new Language("vkj", "Kujarge", "I", "L", null, null, null, null));
    out.add(new Language("vkk", "Kaur", "I", "L", null, null, null, null));
    out.add(new Language("vkl", "Kulisusu", "I", "L", null, null, null, null));
    out.add(new Language("vkm", "Kamakan", "I", "E", null, null, null, null));
    out.add(new Language("vkn", "Koro Nulu", "I", "L", null, null, null, null));
    out.add(new Language("vko", "Kodeoha", "I", "L", null, null, null, null));
    out.add(new Language("vkp", "Korlai Creole Portuguese", "I", "L", null, null, "Creole Portuguese, Korlai", null));
    out.add(new Language("vkt", "Tenggarong Kutai Malay", "I", "L", null, null, "Malay, Tenggarong Kutai", null));
    out.add(new Language("vku", "Kurrama", "I", "L", null, null, null, null));
    out.add(new Language("vkz", "Koro Zuba", "I", "L", null, null, null, null));
    out.add(new Language("vlp", "Valpei", "I", "L", null, null, null, null));
    out.add(new Language("vls", "Vlaams", "I", "L", null, null, null, null));
    out.add(new Language("vma", "Martuyhunira", "I", "E", null, null, null, null));
    out.add(new Language("vmb", "Barbaram", "I", "E", null, null, null, null));
    out.add(new Language("vmc", "Juxtlahuaca Mixtec", "I", "L", null, null, "Mixtec, Juxtlahuaca", null));
    out.add(new Language("vmd", "Mudu Koraga", "I", "L", null, null, "Koraga, Mudu", null));
    out.add(new Language("vme", "East Masela", "I", "L", null, null, "Masela, East", null));
    out.add(new Language("vmf", "Mainfränkisch", "I", "L", null, null, null, null));
    out.add(new Language("vmg", "Lungalunga", "I", "L", null, null, null, null));
    out.add(new Language("vmh", "Maraghei", "I", "L", null, null, null, null));
    out.add(new Language("vmi", "Miwa", "I", "E", null, null, null, null));
    out.add(new Language("vmj", "Ixtayutla Mixtec", "I", "L", null, null, "Mixtec, Ixtayutla", null));
    out.add(new Language("vmk", "Makhuwa-Shirima", "I", "L", null, null, null, null));
    out.add(new Language("vml", "Malgana", "I", "E", null, null, null, null));
    out.add(new Language("vmm", "Mitlatongo Mixtec", "I", "L", null, null, "Mixtec, Mitlatongo", null));
    out.add(new Language("vmp", "Soyaltepec Mazatec", "I", "L", null, null, "Mazatec, Soyaltepec", null));
    out.add(new Language("vmq", "Soyaltepec Mixtec", "I", "L", null, null, "Mixtec, Soyaltepec", null));
    out.add(new Language("vmr", "Marenje", "I", "L", null, null, null, null));
    out.add(new Language("vms", "Moksela", "I", "E", null, null, null, null));
    out.add(new Language("vmu", "Muluridyi", "I", "E", null, null, null, null));
    out.add(new Language("vmv", "Valley Maidu", "I", "E", null, null, "Maidu, Valley", null));
    out.add(new Language("vmw", "Makhuwa", "I", "L", null, null, null, null));
    out.add(new Language("vmx", "Tamazola Mixtec", "I", "L", null, null, "Mixtec, Tamazola", null));
    out.add(new Language("vmy", "Ayautla Mazatec", "I", "L", null, null, "Mazatec, Ayautla", null));
    out.add(new Language("vmz", "Mazatlán Mazatec", "I", "L", null, null, "Mazatec, Mazatlán", null));
    out.add(new Language("vnk", "Vano", "I", "L", null, null, null, null));
    out.add(new Language("vnm", "Vinmavis", "I", "L", null, null, null, null));
    out.add(new Language("vnp", "Vunapu", "I", "L", null, null, null, null));
    out.add(new Language("vol", "Volapük", "I", "C", "vo", null, null, null));
    out.add(new Language("vor", "Voro", "I", "L", null, null, null, null));
    out.add(new Language("vot", "Votic", "I", "L", null, null, null, null));
    out.add(new Language("vra", "Vera'a", "I", "L", null, null, null, null));
    out.add(new Language("vro", "Võro", "I", "L", null, null, null, null));
    out.add(new Language("vrs", "Varisi", "I", "L", null, null, null, null));
    out.add(new Language("vrt", "Burmbar", "I", "L", null, null, null, null));
    out.add(new Language("vsi", "Moldova Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("vsl", "Venezuelan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("vsn", "Vedic Sanskrit", "I", "H", null, null, null, null));
    out.add(new Language("vsv", "Valencian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("vto", "Vitou", "I", "L", null, null, null, null));
    out.add(new Language("vum", "Vumbu", "I", "L", null, null, null, null));
    out.add(new Language("vun", "Vunjo", "I", "L", null, null, null, null));
    out.add(new Language("vut", "Vute", "I", "L", null, null, null, null));
    out.add(new Language("vwa", "Awa (China)", "I", "L", null, null, null, null));
    out.add(new Language("waa", "Walla Walla", "I", "L", null, null, null, null));
    out.add(new Language("wab", "Wab", "I", "L", null, null, null, null));
    out.add(new Language("wac", "Wasco-Wishram", "I", "E", null, null, null, null));
    out.add(new Language("wad", "Wamesa", "I", "L", null, null, null, null));
    out.add(new Language("wae", "Walser", "I", "L", null, null, null, null));
    out.add(new Language("waf", "Wakoná", "I", "E", null, null, null, null));
    out.add(new Language("wag", "Wa'ema", "I", "L", null, null, null, null));
    out.add(new Language("wah", "Watubela", "I", "L", null, null, null, null));
    out.add(new Language("wai", "Wares", "I", "L", null, null, null, null));
    out.add(new Language("waj", "Waffa", "I", "L", null, null, null, null));
    out.add(new Language("wal", "Wolaytta", "I", "L", null, null, null, null));
    out.add(new Language("wam", "Wampanoag", "I", "E", null, null, null, null));
    out.add(new Language("wan", "Wan", "I", "L", null, null, null, null));
    out.add(new Language("wao", "Wappo", "I", "E", null, null, null, null));
    out.add(new Language("wap", "Wapishana", "I", "L", null, null, null, null));
    out.add(new Language("waq", "Wagiman", "I", "L", null, null, null, null));
    out.add(new Language("war", "Waray (Philippines)", "I", "L", null, null, null, null));
    out.add(new Language("was", "Washo", "I", "L", null, null, null, null));
    out.add(new Language("wat", "Kaninuwa", "I", "L", null, null, null, null));
    out.add(new Language("wau", "Waurá", "I", "L", null, null, null, null));
    out.add(new Language("wav", "Waka", "I", "L", null, null, null, null));
    out.add(new Language("waw", "Waiwai", "I", "L", null, null, null, null));
    out.add(new Language("wax", "Watam", "I", "L", null, null, null, null));
    out.add(new Language("way", "Wayana", "I", "L", null, null, null, null));
    out.add(new Language("waz", "Wampur", "I", "L", null, null, null, null));
    out.add(new Language("wba", "Warao", "I", "L", null, null, null, null));
    out.add(new Language("wbb", "Wabo", "I", "L", null, null, null, null));
    out.add(new Language("wbe", "Waritai", "I", "L", null, null, null, null));
    out.add(new Language("wbf", "Wara", "I", "L", null, null, null, null));
    out.add(new Language("wbh", "Wanda", "I", "L", null, null, null, null));
    out.add(new Language("wbi", "Vwanji", "I", "L", null, null, null, null));
    out.add(new Language("wbj", "Alagwa", "I", "L", null, null, null, null));
    out.add(new Language("wbk", "Waigali", "I", "L", null, null, null, null));
    out.add(new Language("wbl", "Wakhi", "I", "L", null, null, null, null));
    out.add(new Language("wbm", "Wa", "I", "L", null, null, null, null));
    out.add(new Language("wbp", "Warlpiri", "I", "L", null, null, null, null));
    out.add(new Language("wbq", "Waddar", "I", "L", null, null, null, null));
    out.add(new Language("wbr", "Wagdi", "I", "L", null, null, null, null));
    out.add(new Language("wbs", "West Bengal Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("wbt", "Warnman", "I", "L", null, null, null, null));
    out.add(new Language("wbv", "Wajarri", "I", "L", null, null, null, null));
    out.add(new Language("wbw", "Woi", "I", "L", null, null, null, null));
  }
}
