// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 7500 to 7922 of {@link Language}.
 */
final class LanguageData15 {
  private LanguageData15() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("yaa", "Yaminahua", "I", "L", null, null, null, null));
    out.add(new Language("yab", "Yuhup", "I", "L", null, null, null, null));
    out.add(new Language("yac", "Pass Valley Yali", "I", "L", null, null, "Yali, Pass Valley", null));
    out.add(new Language("yad", "Yagua", "I", "L", null, null, null, null));
    out.add(new Language("yae", "Pumé", "I", "L", null, null, null, null));
    out.add(new Language("yaf", "Yaka (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("yag", "Yámana", "I", "L", null, null, null, null));
    out.add(new Language("yah", "Yazgulyam", "I", "L", null, null, null, null));
    out.add(new Language("yai", "Yagnobi", "I", "L", null, null, null, null));
    out.add(new Language("yaj", "Banda-Yangere", "I", "L", null, null, null, null));
    out.add(new Language("yak", "Yakama", "I", "L", null, null, null, null));
    out.add(new Language("yal", "Yalunka", "I", "L", null, null, null, null));
    out.add(new Language("yam", "Yamba", "I", "L", null, null, null, null));
    out.add(new Language("yan", "Mayangna", "I", "L", null, null, null, null));
    out.add(new Language("yao", "Yao", "I", "L", null, null, null, null));
    out.add(new Language("yap", "Yapese", "I", "L", null, null, null, null));
    out.add(new Language("yaq", "Yaqui", "I", "L", null, null, null, null));
    out.add(new Language("yar", "Yabarana", "I", "L", null, null, null, null));
    out.add(new Language("yas", "Nugunu (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("yat", "Yambeta", "I", "L", null, null, null, null));
    out.add(new Language("yau", "Yuwana", "I", "L", null, null, null, null));
    out.add(new Language("yav", "Yangben", "I", "L", null, null, null, null));
    out.add(new Language("yaw", "Yawalapití", "I", "L", null, null, null, null));
    out.add(new Language("yax", "Yauma", "I", "L", null, null, null, null));
    out.add(new Language("yay", "Agwagwune", "I", "L", null, null, null, null));
    out.add(new Language("yaz", "Lokaa", "I", "L", null, null, null, null));
    out.add(new Language("yba", "Yala", "I", "L", null, null, null, null));
    out.add(new Language("ybb", "Yemba", "I", "L", null, null, null, null));
    out.add(new Language("ybe", "West Yugur", "I", "L", null, null, "Yugur, West", null));
    out.add(new Language("ybh", "Yakha", "I", "L", null, null, null, null));
    out.add(new Language("ybi", "Yamphu", "I", "L", null, null, null, null));
    out.add(new Language("ybj", "Hasha", "I", "L", null, null, null, null));
    out.add(new Language("ybk", "Bokha", "I", "L", null, null, null, null));
    out.add(new Language("ybl", "Yukuben", "I", "L", null, null, null, null));
    out.add(new Language("ybm", "Yaben", "I", "L", null, null, null, null));
    out.add(new Language("ybn", "Yabaâna", "I", "E", null, null, null, null));
    out.add(new Language("ybo", "Yabong", "I", "L", null, null, null, null));
    out.add(new Language("ybx", "Yawiyo", "I", "L", null, null, null, null));
    out.add(new Language("yby", "Yaweyuha", "I", "L", null, null, null, null));
    out.add(new Language("ych", "Chesu", "I", "L", null, null, null, null));
    out.add(new Language("ycl", "Lolopo", "I", "L", null, null, null, null));
    out.add(new Language("ycn", "Yucuna", "I", "L", null, null, null, null));
    out.add(new Language("ycp", "Chepya", "I", "L", null, null, null, null));
    out.add(new Language("ycr", "Yilan Creole", "I", "L", null, null, null, null));
    out.add(new Language("yda", "Yanda", "I", "E", null, null, null, null));
    out.add(new Language("ydd", "Eastern Yiddish", "I", "L", null, null, "Yiddish, Eastern", null));
    out.add(new Language("yde", "Yangum Dey", "I", "L", null, null, null, null));
    out.add(new Language("ydg", "Yidgha", "I", "L", null, null, null, null));
    out.add(new Language("ydk", "Yoidik", "I", "L", null, null, null, null));
    out.add(new Language("yea", "Ravula", "I", "L", null, null, null, null));
    out.add(new Language("yec", "Yeniche", "I", "L", null, null, null, null));
    out.add(new Language("yee", "Yimas", "I", "L", null, null, null, null));
    out.add(new Language("yei", "Yeni", "I", "E", null, null, null, null));
    out.add(new Language("yej", "Yevanic", "I", "L", null, null, null, null));
    out.add(new Language("yel", "Yela", "I", "L", null, null, null, null));
    out.add(new Language("yer", "Tarok", "I", "L", null, null, null, null));
    out.add(new Language("yes", "Nyankpa", "I", "L", null, null, null, null));
    out.add(new Language("yet", "Yetfa", "I", "L", null, null, null, null));
    out.add(new Language("yeu", "Yerukula", "I", "L", null, null, null, null));
    out.add(new Language("yev", "Yapunda", "I", "L", null, null, null, null));
    out.add(new Language("yey", "Yeyi", "I", "L", null, null, null, null));
    out.add(new Language("yga", "Malyangapa", "I", "E", null, null, null, null));
    out.add(new Language("ygi", "Yiningayi", "I", "E", null, null, null, null));
    out.add(new Language("ygl", "Yangum Gel", "I", "L", null, null, null, null));
    out.add(new Language("ygm", "Yagomi", "I", "L", null, null, null, null));
    out.add(new Language("ygp", "Gepo", "I", "L", null, null, null, null));
    out.add(new Language("ygr", "Yagaria", "I", "L", null, null, null, null));
    out.add(new Language("ygs", "Yolŋu Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ygu", "Yugul", "I", "L", null, null, null, null));
    out.add(new Language("ygw", "Yagwoia", "I", "L", null, null, null, null));
    out.add(new Language("yha", "Baha Buyang", "I", "L", null, null, "Buyang, Baha", null));
    out.add(new Language("yhd", "Judeo-Iraqi Arabic", "I", "L", null, null, "Arabic, Judeo-Iraqi", null));
    out.add(new Language("yhl", "Hlepho Phowa", "I", "L", null, null, "Phowa, Hlepho", null));
    out.add(new Language("yhs", "Yan-nhaŋu Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("yia", "Yinggarda", "I", "L", null, null, null, null));
    out.add(new Language("yid", "Yiddish", "M", "L", "yi", null, null, null));
    out.add(new Language("yif", "Ache", "I", "L", null, null, null, null));
    out.add(new Language("yig", "Wusa Nasu", "I", "L", null, null, "Nasu, Wusa", null));
    out.add(new Language("yih", "Western Yiddish", "I", "E", null, null, "Yiddish, Western", null));
    out.add(new Language("yii", "Yidiny", "I", "L", null, null, null, null));
    out.add(new Language("yij", "Yindjibarndi", "I", "L", null, null, null, null));
    out.add(new Language("yik", "Dongshanba Lalo", "I", "L", null, null, "Lalo, Dongshanba", null));
    out.add(new Language("yil", "Yindjilandji", "I", "E", null, null, null, null));
    out.add(new Language("yim", "Yimchungru Naga", "I", "L", null, null, "Naga, Yimchungru", null));
    out.add(new Language("yin", "Riang Lai", "I", "L", null, null, null, null));
    out.add(new Language("yip", "Pholo", "I", "L", null, null, null, null));
    out.add(new Language("yiq", "Miqie", "I", "L", null, null, null, null));
    out.add(new Language("yir", "North Awyu", "I", "L", null, null, "Awyu, North", null));
    out.add(new Language("yis", "Yis", "I", "L", null, null, null, null));
    out.add(new Language("yit", "Eastern Lalu", "I", "L", null, null, "Lalu, Eastern", null));
    out.add(new Language("yiu", "Awu", "I", "L", null, null, null, null));
    out.add(new Language("yiv", "Northern Nisu", "I", "L", null, null, "Nisu, Northern", null));
    out.add(new Language("yix", "Axi Yi", "I", "L", null, null, "Yi, Axi", null));
    out.add(new Language("yiz", "Azhe", "I", "L", null, null, null, null));
    out.add(new Language("yka", "Yakan", "I", "L", null, null, null, null));
    out.add(new Language("ykg", "Northern Yukaghir", "I", "L", null, null, "Yukaghir, Northern", null));
    out.add(new Language("ykh", "Khamnigan Mongol", "I", "L", null, null, null, null));
    out.add(new Language("yki", "Yoke", "I", "L", null, null, null, null));
    out.add(new Language("ykk", "Yakaikeke", "I", "L", null, null, null, null));
    out.add(new Language("ykl", "Khlula", "I", "L", null, null, null, null));
    out.add(new Language("ykm", "Kap", "I", "L", null, null, null, null));
    out.add(new Language("ykn", "Kua-nsi", "I", "L", null, null, null, null));
    out.add(new Language("yko", "Yasa", "I", "L", null, null, null, null));
    out.add(new Language("ykr", "Yekora", "I", "L", null, null, null, null));
    out.add(new Language("ykt", "Kathu", "I", "L", null, null, null, null));
    out.add(new Language("yku", "Kuamasi", "I", "L", null, null, null, null));
    out.add(new Language("yky", "Yakoma", "I", "L", null, null, null, null));
    out.add(new Language("yla", "Yaul", "I", "L", null, null, null, null));
    out.add(new Language("ylb", "Yaleba", "I", "L", null, null, null, null));
    out.add(new Language("yle", "Yele", "I", "L", null, null, null, null));
    out.add(new Language("ylg", "Yelogu", "I", "L", null, null, null, null));
    out.add(new Language("yli", "Angguruk Yali", "I", "L", null, null, "Yali, Angguruk", null));
    out.add(new Language("yll", "Yil", "I", "L", null, null, null, null));
    out.add(new Language("ylm", "Limi", "I", "L", null, null, null, null));
    out.add(new Language("yln", "Langnian Buyang", "I", "L", null, null, "Buyang, Langnian", null));
    out.add(new Language("ylo", "Naluo Yi", "I", "L", null, null, "Yi, Naluo", null));
    out.add(new Language("ylr", "Yalarnnga", "I", "E", null, null, null, null));
    out.add(new Language("ylu", "Aribwaung", "I", "L", null, null, null, null));
    out.add(new Language("yly", "Nyâlayu", "I", "L", null, null, null, null));
    out.add(new Language("ymb", "Yambes", "I", "L", null, null, null, null));
    out.add(new Language("ymc", "Southern Muji", "I", "L", null, null, "Muji, Southern", null));
    out.add(new Language("ymd", "Muda", "I", "L", null, null, null, null));
    out.add(new Language("yme", "Yameo", "I", "E", null, null, null, null));
    out.add(new Language("ymg", "Yamongeri", "I", "L", null, null, null, null));
    out.add(new Language("ymh", "Mili", "I", "L", null, null, null, null));
    out.add(new Language("ymi", "Moji", "I", "L", null, null, null, null));
    out.add(new Language("ymk", "Makwe", "I", "L", null, null, null, null));
    out.add(new Language("yml", "Iamalele", "I", "L", null, null, null, null));
    out.add(new Language("ymm", "Maay", "I", "L", null, null, null, null));
    out.add(new Language("ymn", "Yamna", "I", "L", null, null, null, null));
    out.add(new Language("ymo", "Yangum Mon", "I", "L", null, null, null, null));
    out.add(new Language("ymp", "Yamap", "I", "L", null, null, null, null));
    out.add(new Language("ymq", "Qila Muji", "I", "L", null, null, "Muji, Qila", null));
    out.add(new Language("ymr", "Malasar", "I", "L", null, null, null, null));
    out.add(new Language("yms", "Mysian", "I", "H", null, null, null, null));
    out.add(new Language("ymx", "Northern Muji", "I", "L", null, null, "Muji, Northern", null));
    out.add(new Language("ymz", "Muzi", "I", "L", null, null, null, null));
    out.add(new Language("yna", "Aluo", "I", "L", null, null, null, null));
    out.add(new Language("ynb", "Yamben", "I", "L", null, null, null, null));
    out.add(new Language("ynd", "Yandruwandha", "I", "E", null, null, null, null));
    out.add(new Language("yne", "Lang'e", "I", "L", null, null, null, null));
    out.add(new Language("yng", "Yango", "I", "L", null, null, null, null));
    out.add(new Language("ynk", "Naukan Yupik", "I", "L", null, null, "Yupik, Naukan", null));
    out.add(new Language("ynl", "Yangulam", "I", "L", null, null, null, null));
    out.add(new Language("ynn", "Yana", "I", "E", null, null, null, null));
    out.add(new Language("yno", "Yong", "I", "L", null, null, null, null));
    out.add(new Language("ynq", "Yendang", "I", "L", null, null, null, null));
    out.add(new Language("yns", "Yansi", "I", "L", null, null, null, null));
    out.add(new Language("ynu", "Yahuna", "I", "E", null, null, null, null));
    out.add(new Language("yob", "Yoba", "I", "E", null, null, null, null));
    out.add(new Language("yog", "Yogad", "I", "L", null, null, null, null));
    out.add(new Language("yoi", "Yonaguni", "I", "L", null, null, null, null));
    out.add(new Language("yok", "Yokuts", "I", "L", null, null, null, null));
    out.add(new Language("yol", "Yola", "I", "E", null, null, null, null));
    out.add(new Language("yom", "Yombe", "I", "L", null, null, null, null));
    out.add(new Language("yon", "Yongkom", "I", "L", null, null, null, null));
    out.add(new Language("yor", "Yoruba", "I", "L", "yo", null, null, null));
    out.add(new Language("yot", "Yotti", "I", "L", null, null, null, null));
    out.add(new Language("yox", "Yoron", "I", "L", null, null, null, null));
    out.add(new Language("yoy", "Yoy", "I", "L", null, null, null, null));
    out.add(new Language("ypa", "Phala", "I", "L", null, null, null, null));
    out.add(new Language("ypb", "Labo Phowa", "I", "L", null, null, "Phowa, Labo", null));
    out.add(new Language("ypg", "Phola", "I", "L", null, null, null, null));
    out.add(new Language("yph", "Phupha", "I", "L", null, null, null, null));
    out.add(new Language("ypm", "Phuma", "I", "L", null, null, null, null));
    out.add(new Language("ypn", "Ani Phowa", "I", "L", null, null, "Phowa, Ani", null));
    out.add(new Language("ypo", "Alo Phola", "I", "L", null, null, "Phola, Alo", null));
    out.add(new Language("ypp", "Phupa", "I", "L", null, null, null, null));
    out.add(new Language("ypz", "Phuza", "I", "L", null, null, null, null));
    out.add(new Language("yra", "Yerakai", "I", "L", null, null, null, null));
    out.add(new Language("yrb", "Yareba", "I", "L", null, null, null, null));
    out.add(new Language("yre", "Yaouré", "I", "L", null, null, null, null));
    out.add(new Language("yrk", "Nenets", "I", "L", null, null, null, null));
    out.add(new Language("yrl", "Nhengatu", "I", "L", null, null, null, null));
    out.add(new Language("yrm", "Yirrk-Mel", "I", "L", null, null, null, null));
    out.add(new Language("yrn", "Yerong", "I", "L", null, null, null, null));
    out.add(new Language("yro", "Yaroamë", "I", "L", null, null, null, null));
    out.add(new Language("yrs", "Yarsun", "I", "L", null, null, null, null));
    out.add(new Language("yrw", "Yarawata", "I", "L", null, null, null, null));
    out.add(new Language("yry", "Yarluyandi", "I", "L", null, null, null, null));
    out.add(new Language("ysc", "Yassic", "I", "E", null, null, null, null));
    out.add(new Language("ysd", "Samatao", "I", "L", null, null, null, null));
    out.add(new Language("ysg", "Sonaga", "I", "L", null, null, null, null));
    out.add(new Language("ysl", "Yugoslavian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ysm", "Myanmar Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ysn", "Sani", "I", "L", null, null, null, null));
    out.add(new Language("yso", "Nisi (China)", "I", "L", null, null, null, null));
    out.add(new Language("ysp", "Southern Lolopo", "I", "L", null, null, "Lolopo, Southern", null));
    out.add(new Language("ysr", "Sirenik Yupik", "I", "E", null, null, "Yupik, Sirenik", null));
    out.add(new Language("yss", "Yessan-Mayo", "I", "L", null, null, null, null));
    out.add(new Language("ysy", "Sanie", "I", "L", null, null, null, null));
    out.add(new Language("yta", "Talu", "I", "L", null, null, null, null));
    out.add(new Language("ytl", "Tanglang", "I", "L", null, null, null, null));
    out.add(new Language("ytp", "Thopho", "I", "L", null, null, null, null));
    out.add(new Language("ytw", "Yout Wam", "I", "L", null, null, null, null));
    out.add(new Language("yty", "Yatay", "I", "E", null, null, null, null));
    out.add(new Language("yua", "Yucateco", "I", "L", null, null, null, null));
    out.add(new Language("yub", "Yugambal", "I", "E", null, null, null, null));
    out.add(new Language("yuc", "Yuchi", "I", "L", null, null, null, null));
    out.add(new Language("yud", "Judeo-Tripolitanian Arabic", "I", "L", null, null, "Arabic, Judeo-Tripolitanian", null));
    out.add(new Language("yue", "Yue Chinese", "I", "L", null, null, "Chinese, Yue", null));
    out.add(new Language("yuf", "Havasupai-Walapai-Yavapai", "I", "L", null, null, null, null));
    out.add(new Language("yug", "Yug", "I", "E", null, null, null, null));
    out.add(new Language("yui", "Yurutí", "I", "L", null, null, null, null));
    out.add(new Language("yuj", "Karkar-Yuri", "I", "L", null, null, null, null));
    out.add(new Language("yuk", "Yuki", "I", "E", null, null, null, null));
    out.add(new Language("yul", "Yulu", "I", "L", null, null, null, null));
    out.add(new Language("yum", "Quechan", "I", "L", null, null, null, null));
    out.add(new Language("yun", "Bena (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("yup", "Yukpa", "I", "L", null, null, null, null));
    out.add(new Language("yuq", "Yuqui", "I", "L", null, null, null, null));
    out.add(new Language("yur", "Yurok", "I", "E", null, null, null, null));
    out.add(new Language("yut", "Yopno", "I", "L", null, null, null, null));
    out.add(new Language("yuw", "Yau (Morobe Province)", "I", "L", null, null, null, null));
    out.add(new Language("yux", "Southern Yukaghir", "I", "L", null, null, "Yukaghir, Southern", null));
    out.add(new Language("yuy", "East Yugur", "I", "L", null, null, "Yugur, East", null));
    out.add(new Language("yuz", "Yuracare", "I", "L", null, null, null, null));
    out.add(new Language("yva", "Yawa", "I", "L", null, null, null, null));
    out.add(new Language("yvt", "Yavitero", "I", "E", null, null, null, null));
    out.add(new Language("ywa", "Kalou", "I", "L", null, null, null, null));
    out.add(new Language("ywg", "Yinhawangka", "I", "L", null, null, null, null));
    out.add(new Language("ywl", "Western Lalu", "I", "L", null, null, "Lalu, Western", null));
    out.add(new Language("ywn", "Yawanawa", "I", "L", null, null, null, null));
    out.add(new Language("ywq", "Wuding-Luquan Yi", "I", "L", null, null, "Yi, Wuding-Luquan", null));
    out.add(new Language("ywr", "Yawuru", "I", "L", null, null, null, null));
    out.add(new Language("ywt", "Xishanba Lalo", "I", "L", null, null, "Lalo, Xishanba", null));
    out.add(new Language("ywu", "Wumeng Nasu", "I", "L", null, null, "Nasu, Wumeng", null));
    out.add(new Language("yww", "Yawarawarga", "I", "E", null, null, null, null));
    out.add(new Language("yxa", "Mayawali", "I", "E", null, null, null, null));
    out.add(new Language("yxg", "Yagara", "I", "E", null, null, null, null));
    out.add(new Language("yxl", "Yardliyawarra", "I", "E", null, null, null, null));
    out.add(new Language("yxm", "Yinwum", "I", "E", null, null, null, null));
    out.add(new Language("yxu", "Yuyu", "I", "E", null, null, null, null));
    out.add(new Language("yxy", "Yabula Yabula", "I", "E", null, null, null, null));
    out.add(new Language("yyr", "Yir Yoront", "I", "E", null, null, null, null));
    out.add(new Language("yyu", "Yau (Sandaun Province)", "I", "L", null, null, null, null));
    out.add(new Language("yyz", "Ayizi", "I", "L", null, null, null, null));
    out.add(new Language("yzg", "E'ma Buyang", "I", "L", null, null, "Buyang, E'ma", null));
    out.add(new Language("yzk", "Zokhuo", "I", "L", null, null, null, null));
    out.add(new Language("zaa", "Sierra de Juárez Zapotec", "I", "L", null, null, "Zapotec, Sierra de Juárez", null));
    out.add(new Language("zab", "Western Tlacolula Valley Zapotec", "I", "L", null, null, "Zapotec, Western Tlacolula Valley", null));
    out.add(new Language("zac", "Ocotlán Zapotec", "I", "L", null, null, "Zapotec, Ocotlán", null));
    out.add(new Language("zad", "Cajonos Zapotec", "I", "L", null, null, "Zapotec, Cajonos", null));
    out.add(new Language("zae", "Yareni Zapotec", "I", "L", null, null, "Zapotec, Yareni", null));
    out.add(new Language("zaf", "Ayoquesco Zapotec", "I", "L", null, null, "Zapotec, Ayoquesco", null));
    out.add(new Language("zag", "Zaghawa", "I", "L", null, null, null, null));
    out.add(new Language("zah", "Zangwal", "I", "L", null, null, null, null));
    out.add(new Language("zai", "Isthmus Zapotec", "I", "L", null, null, "Zapotec, Isthmus", null));
    out.add(new Language("zaj", "Zaramo", "I", "L", null, null, null, null));
    out.add(new Language("zak", "Zanaki", "I", "L", null, null, null, null));
    out.add(new Language("zal", "Zauzou", "I", "L", null, null, null, null));
    out.add(new Language("zam", "Miahuatlán Zapotec", "I", "L", null, null, "Zapotec, Miahuatlán", null));
    out.add(new Language("zao", "Ozolotepec Zapotec", "I", "L", null, null, "Zapotec, Ozolotepec", null));
    out.add(new Language("zap", "Zapotec", "M", "L", null, null, null, null));
    out.add(new Language("zaq", "Aloápam Zapotec", "I", "L", null, null, "Zapotec, Aloápam", null));
    out.add(new Language("zar", "Rincón Zapotec", "I", "L", null, null, "Zapotec, Rincón", null));
    out.add(new Language("zas", "Santo Domingo Albarradas Zapotec", "I", "L", null, null, "Zapotec, Santo Domingo Albarradas", null));
    out.add(new Language("zat", "Tabaa Zapotec", "I", "L", null, null, "Zapotec, Tabaa", null));
    out.add(new Language("zau", "Zangskari", "I", "L", null, null, null, null));
    out.add(new Language("zav", "Yatzachi Zapotec", "I", "L", null, null, "Zapotec, Yatzachi", null));
    out.add(new Language("zaw", "Mitla Zapotec", "I", "L", null, null, "Zapotec, Mitla", null));
    out.add(new Language("zax", "Xadani Zapotec", "I", "L", null, null, "Zapotec, Xadani", null));
    out.add(new Language("zay", "Zayse-Zergulla", "I", "L", null, null, null, null));
    out.add(new Language("zaz", "Zari", "I", "L", null, null, null, null));
    out.add(new Language("zba", "Balaibalan", "I", "C", null, null, null, null));
    out.add(new Language("zbc", "Central Berawan", "I", "L", null, null, "Berawan, Central", null));
    out.add(new Language("zbe", "East Berawan", "I", "L", null, null, "Berawan, East", null));
    out.add(new Language("zbl", "Blissymbols", "I", "C", null, null, null, null));
    out.add(new Language("zbt", "Batui", "I", "L", null, null, null, null));
    out.add(new Language("zbu", "Bu (Bauchi State)", "I", "L", null, null, null, null));
    out.add(new Language("zbw", "West Berawan", "I", "L", null, null, "Berawan, West", null));
    out.add(new Language("zca", "Coatecas Altas Zapotec", "I", "L", null, null, "Zapotec, Coatecas Altas", null));
    out.add(new Language("zcd", "Las Delicias Zapotec", "I", "L", null, null, "Zapotec, Las Delicias", null));
    out.add(new Language("zch", "Central Hongshuihe Zhuang", "I", "L", null, null, "Zhuang, Central Hongshuihe", null));
    out.add(new Language("zdj", "Ngazidja Comorian", "I", "L", null, null, "Comorian, Ngazidja", null));
    out.add(new Language("zea", "Zeeuws", "I", "L", null, null, null, null));
    out.add(new Language("zeg", "Zenag", "I", "L", null, null, null, null));
    out.add(new Language("zeh", "Eastern Hongshuihe Zhuang", "I", "L", null, null, "Zhuang, Eastern Hongshuihe", null));
    out.add(new Language("zem", "Zeem", "I", "L", null, null, null, null));
    out.add(new Language("zen", "Zenaga", "I", "L", null, null, null, null));
    out.add(new Language("zga", "Kinga", "I", "L", null, null, null, null));
    out.add(new Language("zgb", "Guibei Zhuang", "I", "L", null, null, "Zhuang, Guibei", null));
    out.add(new Language("zgh", "Standard Moroccan Tamazight", "I", "L", null, null, "Tamazight, Standard Moroccan", null));
    out.add(new Language("zgm", "Minz Zhuang", "I", "L", null, null, "Zhuang, Minz", null));
    out.add(new Language("zgn", "Guibian Zhuang", "I", "L", null, null, "Zhuang, Guibian", null));
    out.add(new Language("zgr", "Magori", "I", "L", null, null, null, null));
    out.add(new Language("zha", "Zhuang", "M", "L", "za", null, null, null));
    out.add(new Language("zhb", "Zhaba", "I", "L", null, null, null, null));
    out.add(new Language("zhd", "Dai Zhuang", "I", "L", null, null, "Zhuang, Dai", null));
    out.add(new Language("zhi", "Zhire", "I", "L", null, null, null, null));
    out.add(new Language("zhn", "Nong Zhuang", "I", "L", null, null, "Zhuang, Nong", null));
    out.add(new Language("zho", "Chinese", "M", "L", "zh", null, null, "chi"));
    out.add(new Language("zhw", "Zhoa", "I", "L", null, null, null, null));
    out.add(new Language("zia", "Zia", "I", "L", null, null, null, null));
    out.add(new Language("zib", "Zimbabwe Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("zik", "Zimakani", "I", "L", null, null, null, null));
    out.add(new Language("zil", "Zialo", "I", "L", null, null, null, null));
    out.add(new Language("zim", "Mesme", "I", "L", null, null, null, null));
    out.add(new Language("zin", "Zinza", "I", "L", null, null, null, null));
    out.add(new Language("ziw", "Zigula", "I", "L", null, null, null, null));
    out.add(new Language("ziz", "Zizilivakan", "I", "L", null, null, null, null));
    out.add(new Language("zka", "Kaimbulawa", "I", "L", null, null, null, null));
    out.add(new Language("zkd", "Kadu", "I", "L", null, null, null, null));
    out.add(new Language("zkg", "Koguryo", "I", "H", null, null, null, null));
    out.add(new Language("zkh", "Khorezmian", "I", "H", null, null, null, null));
    out.add(new Language("zkk", "Karankawa", "I", "E", null, null, null, null));
    out.add(new Language("zkn", "Kanan", "I", "L", null, null, null, null));
    out.add(new Language("zko", "Kott", "I", "E", null, null, null, null));
    out.add(new Language("zkp", "São Paulo Kaingáng", "I", "E", null, null, "Kaingáng, São Paulo", null));
    out.add(new Language("zkr", "Zakhring", "I", "L", null, null, null, null));
    out.add(new Language("zkt", "Kitan", "I", "H", null, null, null, null));
    out.add(new Language("zku", "Kaurna", "I", "L", null, null, null, null));
    out.add(new Language("zkv", "Krevinian", "I", "E", null, null, null, null));
    out.add(new Language("zkz", "Khazar", "I", "H", null, null, null, null));
    out.add(new Language("zla", "Zula", "I", "L", null, null, null, null));
    out.add(new Language("zlj", "Liujiang Zhuang", "I", "L", null, null, "Zhuang, Liujiang", null));
    out.add(new Language("zlm", "Malay (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("zln", "Lianshan Zhuang", "I", "L", null, null, "Zhuang, Lianshan", null));
    out.add(new Language("zlq", "Liuqian Zhuang", "I", "L", null, null, "Zhuang, Liuqian", null));
    out.add(new Language("zlu", "Zul", "I", "L", null, null, null, null));
    out.add(new Language("zma", "Manda (Australia)", "I", "L", null, null, null, null));
    out.add(new Language("zmb", "Zimba", "I", "L", null, null, null, null));
    out.add(new Language("zmc", "Margany", "I", "E", null, null, null, null));
    out.add(new Language("zmd", "Maridan", "I", "L", null, null, null, null));
    out.add(new Language("zme", "Mangerr", "I", "E", null, null, null, null));
    out.add(new Language("zmf", "Mfinu", "I", "L", null, null, null, null));
    out.add(new Language("zmg", "Marti Ke", "I", "L", null, null, null, null));
    out.add(new Language("zmh", "Makolkol", "I", "E", null, null, null, null));
    out.add(new Language("zmi", "Negeri Sembilan Malay", "I", "L", null, null, null, null));
    out.add(new Language("zmj", "Maridjabin", "I", "L", null, null, null, null));
    out.add(new Language("zmk", "Mandandanyi", "I", "E", null, null, null, null));
    out.add(new Language("zml", "Matngala", "I", "E", null, null, null, null));
    out.add(new Language("zmm", "Marimanindji", "I", "L", null, null, null, null));
    out.add(new Language("zmn", "Mbangwe", "I", "L", null, null, null, null));
    out.add(new Language("zmo", "Molo", "I", "L", null, null, null, null));
    out.add(new Language("zmp", "Mbuun", "I", "L", null, null, null, null));
    out.add(new Language("zmq", "Mituku", "I", "L", null, null, null, null));
    out.add(new Language("zmr", "Maranunggu", "I", "L", null, null, null, null));
    out.add(new Language("zms", "Mbesa", "I", "L", null, null, null, null));
    out.add(new Language("zmt", "Maringarr", "I", "L", null, null, null, null));
    out.add(new Language("zmu", "Muruwari", "I", "E", null, null, null, null));
    out.add(new Language("zmv", "Mbariman-Gudhinma", "I", "E", null, null, null, null));
    out.add(new Language("zmw", "Mbo (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("zmx", "Bomitaba", "I", "L", null, null, null, null));
    out.add(new Language("zmy", "Mariyedi", "I", "L", null, null, null, null));
    out.add(new Language("zmz", "Mbandja", "I", "L", null, null, null, null));
    out.add(new Language("zna", "Zan Gula", "I", "L", null, null, null, null));
    out.add(new Language("zne", "Zande (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("zng", "Mang", "I", "L", null, null, null, null));
    out.add(new Language("znk", "Manangkari", "I", "E", null, null, null, null));
    out.add(new Language("zns", "Mangas", "I", "L", null, null, null, null));
    out.add(new Language("zoc", "Copainalá Zoque", "I", "L", null, null, "Zoque, Copainalá", null));
    out.add(new Language("zoh", "Chimalapa Zoque", "I", "L", null, null, "Zoque, Chimalapa", null));
    out.add(new Language("zom", "Zou", "I", "L", null, null, null, null));
    out.add(new Language("zoo", "Asunción Mixtepec Zapotec", "I", "L", null, null, "Zapotec, Asunción Mixtepec", null));
    out.add(new Language("zoq", "Tabasco Zoque", "I", "L", null, null, "Zoque, Tabasco", null));
    out.add(new Language("zor", "Rayón Zoque", "I", "L", null, null, "Zoque, Rayón", null));
    out.add(new Language("zos", "Francisco León Zoque", "I", "L", null, null, "Zoque, Francisco León", null));
    out.add(new Language("zpa", "Lachiguiri Zapotec", "I", "L", null, null, "Zapotec, Lachiguiri", null));
    out.add(new Language("zpb", "Yautepec Zapotec", "I", "L", null, null, "Zapotec, Yautepec", null));
    out.add(new Language("zpc", "Choapan Zapotec", "I", "L", null, null, "Zapotec, Choapan", null));
    out.add(new Language("zpd", "Southeastern Ixtlán Zapotec", "I", "L", null, null, "Zapotec, Southeastern Ixtlán", null));
    out.add(new Language("zpe", "Petapa Zapotec", "I", "L", null, null, "Zapotec, Petapa", null));
    out.add(new Language("zpf", "San Pedro Quiatoni Zapotec", "I", "L", null, null, "Zapotec, San Pedro Quiatoni", null));
    out.add(new Language("zpg", "Guevea De Humboldt Zapotec", "I", "L", null, null, "Zapotec, Guevea De Humboldt", null));
    out.add(new Language("zph", "Totomachapan Zapotec", "I", "L", null, null, "Zapotec, Totomachapan", null));
    out.add(new Language("zpi", "Santa María Quiegolani Zapotec", "I", "L", null, null, "Zapotec, Santa María Quiegolani", null));
    out.add(new Language("zpj", "Quiavicuzas Zapotec", "I", "L", null, null, "Zapotec, Quiavicuzas", null));
    out.add(new Language("zpk", "Tlacolulita Zapotec", "I", "L", null, null, "Zapotec, Tlacolulita", null));
    out.add(new Language("zpl", "Lachixío Zapotec", "I", "L", null, null, "Zapotec, Lachixío", null));
    out.add(new Language("zpm", "Mixtepec Zapotec", "I", "L", null, null, "Zapotec, Mixtepec", null));
    out.add(new Language("zpn", "Santa Inés Yatzechi Zapotec", "I", "L", null, null, "Zapotec, Santa Inés Yatzechi", null));
    out.add(new Language("zpo", "Amatlán Zapotec", "I", "L", null, null, "Zapotec, Amatlán", null));
    out.add(new Language("zpp", "El Alto Zapotec", "I", "L", null, null, "Zapotec, El Alto", null));
    out.add(new Language("zpq", "Zoogocho Zapotec", "I", "L", null, null, "Zapotec, Zoogocho", null));
    out.add(new Language("zpr", "Santiago Xanica Zapotec", "I", "L", null, null, "Zapotec, Santiago Xanica", null));
    out.add(new Language("zps", "Coatlán Zapotec", "I", "L", null, null, "Zapotec, Coatlán", null));
    out.add(new Language("zpt", "San Vicente Coatlán Zapotec", "I", "L", null, null, "Zapotec, San Vicente Coatlán", null));
    out.add(new Language("zpu", "Yalálag Zapotec", "I", "L", null, null, "Zapotec, Yalálag", null));
    out.add(new Language("zpv", "Chichicapan Zapotec", "I", "L", null, null, "Zapotec, Chichicapan", null));
    out.add(new Language("zpw", "Zaniza Zapotec", "I", "L", null, null, "Zapotec, Zaniza", null));
    out.add(new Language("zpx", "San Baltazar Loxicha Zapotec", "I", "L", null, null, "Zapotec, San Baltazar Loxicha", null));
    out.add(new Language("zpy", "Mazaltepec Zapotec", "I", "L", null, null, "Zapotec, Mazaltepec", null));
    out.add(new Language("zpz", "Texmelucan Zapotec", "I", "L", null, null, "Zapotec, Texmelucan", null));
    out.add(new Language("zqe", "Qiubei Zhuang", "I", "L", null, null, "Zhuang, Qiubei", null));
    out.add(new Language("zra", "Kara (Korea)", "I", "H", null, null, null, null));
    out.add(new Language("zrg", "Mirgan", "I", "L", null, null, null, null));
    out.add(new Language("zrn", "Zerenkel", "I", "L", null, null, null, null));
    out.add(new Language("zro", "Záparo", "I", "L", null, null, null, null));
    out.add(new Language("zrp", "Zarphatic", "I", "E", null, null, null, null));
    out.add(new Language("zrs", "Mairasi", "I", "L", null, null, null, null));
    out.add(new Language("zsa", "Sarasira", "I", "L", null, null, null, null));
    out.add(new Language("zsk", "Kaskean", "I", "H", null, null, null, null));
    out.add(new Language("zsl", "Zambian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("zsm", "Standard Malay", "I", "L", null, null, "Malay, Standard", null));
    out.add(new Language("zsr", "Southern Rincon Zapotec", "I", "L", null, null, "Zapotec, Southern Rincon", null));
    out.add(new Language("zsu", "Sukurum", "I", "L", null, null, null, null));
    out.add(new Language("zte", "Elotepec Zapotec", "I", "L", null, null, "Zapotec, Elotepec", null));
    out.add(new Language("ztg", "Xanaguía Zapotec", "I", "L", null, null, "Zapotec, Xanaguía", null));
    out.add(new Language("ztl", "Lapaguía-Guivini Zapotec", "I", "L", null, null, "Zapotec, Lapaguía-Guivini", null));
    out.add(new Language("ztm", "San Agustín Mixtepec Zapotec", "I", "L", null, null, "Zapotec, San Agustín Mixtepec", null));
    out.add(new Language("ztn", "Santa Catarina Albarradas Zapotec", "I", "L", null, null, "Zapotec, Santa Catarina Albarradas", null));
    out.add(new Language("ztp", "Loxicha Zapotec", "I", "L", null, null, "Zapotec, Loxicha", null));
    out.add(new Language("ztq", "Quioquitani-Quierí Zapotec", "I", "L", null, null, "Zapotec, Quioquitani-Quierí", null));
    out.add(new Language("zts", "Tilquiapan Zapotec", "I", "L", null, null, "Zapotec, Tilquiapan", null));
    out.add(new Language("ztt", "Tejalapan Zapotec", "I", "L", null, null, "Zapotec, Tejalapan", null));
    out.add(new Language("ztu", "Güilá Zapotec", "I", "L", null, null, "Zapotec, Güilá", null));
    out.add(new Language("ztx", "Zaachila Zapotec", "I", "L", null, null, "Zapotec, Zaachila", null));
    out.add(new Language("zty", "Yatee Zapotec", "I", "L", null, null, "Zapotec, Yatee", null));
    out.add(new Language("zuh", "Tokano", "I", "L", null, null, null, null));
    out.add(new Language("zul", "Zulu", "I", "L", "zu", null, null, null));
    out.add(new Language("zum", "Kumzari", "I", "L", null, null, null, null));
    out.add(new Language("zun", "Zuni", "I", "L", null, null, null, null));
    out.add(new Language("zuy", "Zumaya", "I", "L", null, null, null, null));
    out.add(new Language("zwa", "Zay", "I", "L", null, null, null, null));
    out.add(new Language("zxx", "No linguistic content", "S", "S", null, null, null, null));
    out.add(new Language("zyb", "Yongbei Zhuang", "I", "L", null, null, "Zhuang, Yongbei", null));
    out.add(new Language("zyg", "Yang Zhuang", "I", "L", null, null, "Zhuang, Yang", null));
    out.add(new Language("zyj", "Youjiang Zhuang", "I", "L", null, null, "Zhuang, Youjiang", null));
    out.add(new Language("zyn", "Yongnan Zhuang", "I", "L", null, null, "Zhuang, Yongnan", null));
    out.add(new Language("zyp", "Zyphe Chin", "I", "L", null, null, "Chin, Zyphe", null));
    out.add(new Language("zza", "Zaza", "M", "L", null, null, null, null));
    out.add(new Language("zzj", "Zuojiang Zhuang", "I", "L", null, null, "Zhuang, Zuojiang", null));
  }
}
