// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 0 to 499 of {@link Language}.
 */
final class LanguageData0 {
  private LanguageData0() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("aaa", "Ghotuo", "I", "L", null, null, null, null));
    out.add(new Language("aab", "Alumu-Tesu", "I", "L", null, null, null, null));
    out.add(new Language("aac", "Ari", "I", "L", null, null, null, null));
    out.add(new Language("aad", "Amal", "I", "L", null, null, null, null));
    out.add(new Language("aae", "Arbëreshë Albanian", "I", "L", null, null, "Albanian, Arbëreshë", null));
    out.add(new Language("aaf", "Aranadan", "I", "L", null, null, null, null));
    out.add(new Language("aag", "Ambrak", "I", "L", null, null, null, null));
    out.add(new Language("aah", "Abu' Arapesh", "I", "L", null, null, "Arapesh, Abu'", null));
    out.add(new Language("aai", "Arifama-Miniafia", "I", "L", null, null, null, null));
    out.add(new Language("aak", "Ankave", "I", "L", null, null, null, null));
    out.add(new Language("aal", "Afade", "I", "L", null, null, null, null));
    out.add(new Language("aan", "Anambé", "I", "L", null, null, null, null));
    out.add(new Language("aao", "Algerian Saharan Arabic", "I", "L", null, null, "Arabic, Algerian Saharan", null));
    out.add(new Language("aap", "Pará Arára", "I", "L", null, null, "Arára, Pará", null));
    out.add(new Language("aaq", "Eastern Abnaki", "I", "E", null, null, "Abnaki, Eastern", null));
    out.add(new Language("aar", "Afar", "I", "L", "aa", null, null, null));
    out.add(new Language("aas", "Aasáx", "I", "L", null, null, null, null));
    out.add(new Language("aat", "Arvanitika Albanian", "I", "L", null, null, "Albanian, Arvanitika", null));
    out.add(new Language("aau", "Abau", "I", "L", null, null, null, null));
    out.add(new Language("aaw", "Solong", "I", "L", null, null, null, null));
    out.add(new Language("aax", "Mandobo Atas", "I", "L", null, null, null, null));
    out.add(new Language("aaz", "Amarasi", "I", "L", null, null, null, null));
    out.add(new Language("aba", "Abé", "I", "L", null, null, null, null));
    out.add(new Language("abb", "Bankon", "I", "L", null, null, null, null));
    out.add(new Language("abc", "Ambala Ayta", "I", "L", null, null, "Ayta, Ambala", null));
    out.add(new Language("abd", "Manide", "I", "L", null, null, null, null));
    out.add(new Language("abe", "Western Abnaki", "I", "L", null, null, "Abnaki, Western", null));
    out.add(new Language("abf", "Abai Sungai", "I", "L", null, null, null, null));
    out.add(new Language("abg", "Abaga", "I", "L", null, null, null, null));
    out.add(new Language("abh", "Tajiki Arabic", "I", "L", null, null, "Arabic, Tajiki", null));
    out.add(new Language("abi", "Abidji", "I", "L", null, null, null, null));
    out.add(new Language("abj", "Aka-Bea", "I", "E", null, null, null, null));
    out.add(new Language("abk", "Abkhazian", "I", "L", "ab", null, null, null));
    out.add(new Language("abl", "Lampung Nyo", "I", "L", null, null, null, null));
    out.add(new Language("abm", "Abanyom", "I", "L", null, null, null, null));
    out.add(new Language("abn", "Abua", "I", "L", null, null, null, null));
    out.add(new Language("abo", "Abon", "I", "L", null, null, null, null));
    out.add(new Language("abp", "Abellen Ayta", "I", "L", null, null, "Ayta, Abellen", null));
    out.add(new Language("abq", "Abaza", "I", "L", null, null, null, null));
    out.add(new Language("abr", "Abron", "I", "L", null, null, null, null));
    out.add(new Language("abs", "Ambonese Malay", "I", "L", null, null, "Malay, Ambonese", null));
    out.add(new Language("abt", "Ambulas", "I", "L", null, null, null, null));
    out.add(new Language("abu", "Abure", "I", "L", null, null, null, null));
    out.add(new Language("abv", "Baharna Arabic", "I", "L", null, null, "Arabic, Baharna", null));
    out.add(new Language("abw", "Pal", "I", "L", null, null, null, null));
    out.add(new Language("abx", "Inabaknon", "I", "L", null, null, null, null));
    out.add(new Language("aby", "Aneme Wake", "I", "L", null, null, null, null));
    out.add(new Language("abz", "Abui", "I", "L", null, null, null, null));
    out.add(new Language("aca", "Achagua", "I", "L", null, null, null, null));
    out.add(new Language("acb", "Áncá", "I", "L", null, null, null, null));
    out.add(new Language("acd", "Gikyode", "I", "L", null, null, null, null));
    out.add(new Language("ace", "Achinese", "I", "L", null, null, null, null));
    out.add(new Language("acf", "Saint Lucian Creole French", "I", "L", null, null, "Creole French, Saint Lucian", null));
    out.add(new Language("ach", "Acoli", "I", "L", null, null, null, null));
    out.add(new Language("aci", "Aka-Cari", "I", "E", null, null, null, null));
    out.add(new Language("ack", "Aka-Kora", "I", "E", null, null, null, null));
    out.add(new Language("acl", "Akar-Bale", "I", "E", null, null, null, null));
    out.add(new Language("acm", "Mesopotamian Arabic", "I", "L", null, null, "Arabic, Mesopotamian", null));
    out.add(new Language("acn", "Achang", "I", "L", null, null, null, null));
    out.add(new Language("acp", "Eastern Acipa", "I", "L", null, null, "Acipa, Eastern", null));
    out.add(new Language("acq", "Ta'izzi-Adeni Arabic", "I", "L", null, null, "Arabic, Ta'izzi-Adeni", null));
    out.add(new Language("acr", "Achi", "I", "L", null, null, null, null));
    out.add(new Language("acs", "Acroá", "I", "E", null, null, null, null));
    out.add(new Language("act", "Achterhoeks", "I", "L", null, null, null, null));
    out.add(new Language("acu", "Achuar-Shiwiar", "I", "L", null, null, null, null));
    out.add(new Language("acv", "Achumawi", "I", "L", null, null, null, null));
    out.add(new Language("acw", "Hijazi Arabic", "I", "L", null, null, "Arabic, Hijazi", null));
    out.add(new Language("acx", "Omani Arabic", "I", "L", null, null, "Arabic, Omani", null));
    out.add(new Language("acy", "Cypriot Arabic", "I", "L", null, null, "Arabic, Cypriot", null));
    out.add(new Language("acz", "Acheron", "I", "L", null, null, null, null));
    out.add(new Language("ada", "Adangme", "I", "L", null, null, null, null));
    out.add(new Language("adb", "Atauran", "I", "L", null, null, null, null));
    out.add(new Language("add", "Lidzonka", "I", "L", null, null, null, null));
    out.add(new Language("ade", "Adele", "I", "L", null, null, null, null));
    out.add(new Language("adf", "Dhofari Arabic", "I", "L", null, null, "Arabic, Dhofari", null));
    out.add(new Language("adg", "Andegerebinha", "I", "L", null, null, null, null));
    out.add(new Language("adh", "Adhola", "I", "L", null, null, null, null));
    out.add(new Language("adi", "Adi", "I", "L", null, null, null, null));
    out.add(new Language("adj", "Adioukrou", "I", "L", null, null, null, null));
    out.add(new Language("adl", "Galo", "I", "L", null, null, null, null));
    out.add(new Language("adn", "Adang", "I", "L", null, null, null, null));
    out.add(new Language("ado", "Abu", "I", "L", null, null, null, null));
    out.add(new Language("adq", "Adangbe", "I", "L", null, null, null, null));
    out.add(new Language("adr", "Adonara", "I", "L", null, null, null, null));
    out.add(new Language("ads", "Adamorobe Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("adt", "Adnyamathanha", "I", "L", null, null, null, null));
    out.add(new Language("adu", "Aduge", "I", "L", null, null, null, null));
    out.add(new Language("adw", "Amundava", "I", "L", null, null, null, null));
    out.add(new Language("adx", "Amdo Tibetan", "I", "L", null, null, "Tibetan, Amdo", null));
    out.add(new Language("ady", "Adyghe", "I", "L", null, null, null, null));
    out.add(new Language("adz", "Adzera", "I", "L", null, null, null, null));
    out.add(new Language("aea", "Areba", "I", "E", null, null, null, null));
    out.add(new Language("aeb", "Tunisian Arabic", "I", "L", null, null, "Arabic, Tunisian", null));
    out.add(new Language("aec", "Saidi Arabic", "I", "L", null, null, "Arabic, Saidi", null));
    out.add(new Language("aed", "Argentine Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("aee", "Northeast Pashai", "I", "L", null, null, "Pashai, Northeast", null));
    out.add(new Language("aek", "Haeke", "I", "L", null, null, null, null));
    out.add(new Language("ael", "Ambele", "I", "L", null, null, null, null));
    out.add(new Language("aem", "Arem", "I", "L", null, null, null, null));
    out.add(new Language("aen", "Armenian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("aeq", "Aer", "I", "L", null, null, null, null));
    out.add(new Language("aer", "Eastern Arrernte", "I", "L", null, null, "Arrernte, Eastern", null));
    out.add(new Language("aes", "Alsea", "I", "E", null, null, null, null));
    out.add(new Language("aeu", "Akeu", "I", "L", null, null, null, null));
    out.add(new Language("aew", "Ambakich", "I", "L", null, null, null, null));
    out.add(new Language("aey", "Amele", "I", "L", null, null, null, null));
    out.add(new Language("aez", "Aeka", "I", "L", null, null, null, null));
    out.add(new Language("afb", "Gulf Arabic", "I", "L", null, null, "Arabic, Gulf", null));
    out.add(new Language("afd", "Andai", "I", "L", null, null, null, null));
    out.add(new Language("afe", "Putukwam", "I", "L", null, null, null, null));
    out.add(new Language("afg", "Afghan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("afh", "Afrihili", "I", "C", null, null, null, null));
    out.add(new Language("afi", "Akrukay", "I", "L", null, null, null, null));
    out.add(new Language("afk", "Nanubae", "I", "L", null, null, null, null));
    out.add(new Language("afn", "Defaka", "I", "L", null, null, null, null));
    out.add(new Language("afo", "Eloyi", "I", "L", null, null, null, null));
    out.add(new Language("afp", "Tapei", "I", "L", null, null, null, null));
    out.add(new Language("afr", "Afrikaans", "I", "L", "af", null, null, null));
    out.add(new Language("afs", "Afro-Seminole Creole", "I", "L", null, null, "Creole, Afro-Seminole", null));
    out.add(new Language("aft", "Afitti", "I", "L", null, null, null, null));
    out.add(new Language("afu", "Awutu", "I", "L", null, null, null, null));
    out.add(new Language("afz", "Obokuitai", "I", "L", null, null, null, null));
    out.add(new Language("aga", "Aguano", "I", "E", null, null, null, null));
    out.add(new Language("agb", "Legbo", "I", "L", null, null, null, null));
    out.add(new Language("agc", "Agatu", "I", "L", null, null, null, null));
    out.add(new Language("agd", "Agarabi", "I", "L", null, null, null, null));
    out.add(new Language("age", "Angal", "I", "L", null, null, null, null));
    out.add(new Language("agf", "Arguni", "I", "L", null, null, null, null));
    out.add(new Language("agg", "Angor", "I", "L", null, null, null, null));
    out.add(new Language("agh", "Ngelima", "I", "L", null, null, null, null));
    out.add(new Language("agi", "Agariya", "I", "L", null, null, null, null));
    out.add(new Language("agj", "Argobba", "I", "L", null, null, null, null));
    out.add(new Language("agk", "Isarog Agta", "I", "L", null, null, "Agta, Isarog", null));
    out.add(new Language("agl", "Fembe", "I", "L", null, null, null, null));
    out.add(new Language("agm", "Angaataha", "I", "L", null, null, null, null));
    out.add(new Language("agn", "Agutaynen", "I", "L", null, null, null, null));
    out.add(new Language("ago", "Tainae", "I", "L", null, null, null, null));
    out.add(new Language("agq", "Aghem", "I", "L", null, null, null, null));
    out.add(new Language("agr", "Aguaruna", "I", "L", null, null, null, null));
    out.add(new Language("ags", "Esimbi", "I", "L", null, null, null, null));
    out.add(new Language("agt", "Central Cagayan Agta", "I", "L", null, null, "Agta, Central Cagayan", null));
    out.add(new Language("agu", "Aguacateco", "I", "L", null, null, null, null));
    out.add(new Language("agv", "Remontado Dumagat", "I", "L", null, null, "Dumagat, Remontado", null));
    out.add(new Language("agw", "Kahua", "I", "L", null, null, null, null));
    out.add(new Language("agx", "Aghul", "I", "L", null, null, null, null));
    out.add(new Language("agy", "Southern Alta", "I", "L", null, null, "Alta, Southern", null));
    out.add(new Language("agz", "Mt. Iriga Agta", "I", "L", null, null, "Agta, Mt. Iriga", null));
    out.add(new Language("aha", "Ahanta", "I", "L", null, null, null, null));
    out.add(new Language("ahb", "Axamb", "I", "L", null, null, null, null));
    out.add(new Language("ahg", "Qimant", "I", "L", null, null, null, null));
    out.add(new Language("ahh", "Aghu", "I", "L", null, null, null, null));
    out.add(new Language("ahi", "Tiagbamrin Aizi", "I", "L", null, null, "Aizi, Tiagbamrin", null));
    out.add(new Language("ahk", "Akha", "I", "L", null, null, null, null));
    out.add(new Language("ahl", "Igo", "I", "L", null, null, null, null));
    out.add(new Language("ahm", "Mobumrin Aizi", "I", "L", null, null, "Aizi, Mobumrin", null));
    out.add(new Language("ahn", "Àhàn", "I", "L", null, null, null, null));
    out.add(new Language("aho", "Ahom", "I", "E", null, null, null, null));
    out.add(new Language("ahp", "Aproumu Aizi", "I", "L", null, null, "Aizi, Aproumu", null));
    out.add(new Language("ahr", "Ahirani", "I", "L", null, null, null, null));
    out.add(new Language("ahs", "Ashe", "I", "L", null, null, null, null));
    out.add(new Language("aht", "Ahtena", "I", "L", null, null, null, null));
    out.add(new Language("aia", "Arosi", "I", "L", null, null, null, null));
    out.add(new Language("aib", "Ainu (China)", "I", "L", null, null, null, null));
    out.add(new Language("aic", "Ainbai", "I", "L", null, null, null, null));
    out.add(new Language("aid", "Alngith", "I", "E", null, null, null, null));
    out.add(new Language("aie", "Amara", "I", "L", null, null, null, null));
    out.add(new Language("aif", "Agi", "I", "L", null, null, null, null));
    out.add(new Language("aig", "Antigua and Barbuda Creole English", "I", "L", null, null, "Creole English, Antigua and Barbuda", null));
    out.add(new Language("aih", "Ai-Cham", "I", "L", null, null, null, null));
    out.add(new Language("aii", "Assyrian Neo-Aramaic", "I", "L", null, null, "Neo-Aramaic, Assyrian", null));
    out.add(new Language("aij", "Lishanid Noshan", "I", "L", null, null, null, null));
    out.add(new Language("aik", "Ake", "I", "L", null, null, null, null));
    out.add(new Language("ail", "Aimele", "I", "L", null, null, null, null));
    out.add(new Language("aim", "Aimol", "I", "L", null, null, null, null));
    out.add(new Language("ain", "Ainu (Japan)", "I", "L", null, null, null, null));
    out.add(new Language("aio", "Aiton", "I", "L", null, null, null, null));
    out.add(new Language("aip", "Burumakok", "I", "L", null, null, null, null));
    out.add(new Language("aiq", "Aimaq", "I", "L", null, null, null, null));
    out.add(new Language("air", "Airoran", "I", "L", null, null, null, null));
    out.add(new Language("ait", "Arikem", "I", "E", null, null, null, null));
    out.add(new Language("aiw", "Aari", "I", "L", null, null, null, null));
    out.add(new Language("aix", "Aighon", "I", "L", null, null, null, null));
    out.add(new Language("aiy", "Ali", "I", "L", null, null, null, null));
    out.add(new Language("aja", "Aja (South Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("ajg", "Aja (Benin)", "I", "L", null, null, null, null));
    out.add(new Language("aji", "Ajië", "I", "L", null, null, null, null));
    out.add(new Language("ajn", "Andajin", "I", "L", null, null, null, null));
    out.add(new Language("ajs", "Algerian Jewish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("aju", "Judeo-Moroccan Arabic", "I", "L", null, null, "Arabic, Judeo-Moroccan", null));
    out.add(new Language("ajw", "Ajawa", "I", "E", null, null, null, null));
    out.add(new Language("ajz", "Amri Karbi", "I", "L", null, null, "Karbi, Amri", null));
    out.add(new Language("aka", "Akan", "M", "L", "ak", null, null, null));
    out.add(new Language("akb", "Batak Angkola", "I", "L", null, null, null, null));
    out.add(new Language("akc", "Mpur", "I", "L", null, null, null, null));
    out.add(new Language("akd", "Ukpet-Ehom", "I", "L", null, null, null, null));
    out.add(new Language("ake", "Akawaio", "I", "L", null, null, null, null));
    out.add(new Language("akf", "Akpa", "I", "L", null, null, null, null));
    out.add(new Language("akg", "Anakalangu", "I", "L", null, null, null, null));
    out.add(new Language("akh", "Angal Heneng", "I", "L", null, null, null, null));
    out.add(new Language("aki", "Aiome", "I", "L", null, null, null, null));
    out.add(new Language("akj", "Aka-Jeru", "I", "E", null, null, null, null));
    out.add(new Language("akk", "Akkadian", "I", "H", null, null, null, null));
    out.add(new Language("akl", "Aklanon", "I", "L", null, null, null, null));
    out.add(new Language("akm", "Aka-Bo", "I", "E", null, null, null, null));
    out.add(new Language("ako", "Akurio", "I", "L", null, null, null, null));
    out.add(new Language("akp", "Siwu", "I", "L", null, null, null, null));
    out.add(new Language("akq", "Ak", "I", "L", null, null, null, null));
    out.add(new Language("akr", "Araki", "I", "L", null, null, null, null));
    out.add(new Language("aks", "Akaselem", "I", "L", null, null, null, null));
    out.add(new Language("akt", "Akolet", "I", "L", null, null, null, null));
    out.add(new Language("aku", "Akum", "I", "L", null, null, null, null));
    out.add(new Language("akv", "Akhvakh", "I", "L", null, null, null, null));
    out.add(new Language("akw", "Akwa", "I", "L", null, null, null, null));
    out.add(new Language("akx", "Aka-Kede", "I", "E", null, null, null, null));
    out.add(new Language("aky", "Aka-Kol", "I", "E", null, null, null, null));
    out.add(new Language("akz", "Alabama", "I", "L", null, null, null, null));
    out.add(new Language("ala", "Alago", "I", "L", null, null, null, null));
    out.add(new Language("alc", "Qawasqar", "I", "L", null, null, null, null));
    out.add(new Language("ald", "Alladian", "I", "L", null, null, null, null));
    out.add(new Language("ale", "Aleut", "I", "L", null, null, null, null));
    out.add(new Language("alf", "Alege", "I", "L", null, null, null, null));
    out.add(new Language("alh", "Alawa", "I", "L", null, null, null, null));
    out.add(new Language("ali", "Amaimon", "I", "L", null, null, null, null));
    out.add(new Language("alj", "Alangan", "I", "L", null, null, null, null));
    out.add(new Language("alk", "Alak", "I", "L", null, null, null, null));
    out.add(new Language("all", "Allar", "I", "L", null, null, null, null));
    out.add(new Language("alm", "Amblong", "I", "L", null, null, null, null));
    out.add(new Language("aln", "Gheg Albanian", "I", "L", null, null, "Albanian, Gheg", null));
    out.add(new Language("alo", "Larike-Wakasihu", "I", "L", null, null, null, null));
    out.add(new Language("alp", "Alune", "I", "L", null, null, null, null));
    out.add(new Language("alq", "Algonquin", "I", "L", null, null, null, null));
    out.add(new Language("alr", "Alutor", "I", "L", null, null, null, null));
    out.add(new Language("als", "Tosk Albanian", "I", "L", null, null, "Albanian, Tosk", null));
    out.add(new Language("alt", "Southern Altai", "I", "L", null, null, "Altai, Southern", null));
    out.add(new Language("alu", "'Are'are", "I", "L", null, null, null, null));
    out.add(new Language("alw", "Alaba-K’abeena", "I", "L", null, null, null, null));
    out.add(new Language("alx", "Amol", "I", "L", null, null, null, null));
    out.add(new Language("aly", "Alyawarr", "I", "L", null, null, null, null));
    out.add(new Language("alz", "Alur", "I", "L", null, null, null, null));
    out.add(new Language("ama", "Amanayé", "I", "E", null, null, null, null));
    out.add(new Language("amb", "Ambo", "I", "L", null, null, null, null));
    out.add(new Language("amc", "Amahuaca", "I", "L", null, null, null, null));
    out.add(new Language("ame", "Yanesha'", "I", "L", null, null, null, null));
    out.add(new Language("amf", "Hamer-Banna", "I", "L", null, null, null, null));
    out.add(new Language("amg", "Amurdak", "I", "L", null, null, null, null));
    out.add(new Language("amh", "Amharic", "I", "L", "am", null, null, null));
    out.add(new Language("ami", "Amis", "I", "L", null, null, null, null));
    out.add(new Language("amj", "Amdang", "I", "L", null, null, null, null));
    out.add(new Language("amk", "Ambai", "I", "L", null, null, null, null));
    out.add(new Language("aml", "War-Jaintia", "I", "L", null, null, null, null));
    out.add(new Language("amm", "Ama (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("amn", "Amanab", "I", "L", null, null, null, null));
    out.add(new Language("amo", "Amo", "I", "L", null, null, null, null));
    out.add(new Language("amp", "Alamblak", "I", "L", null, null, null, null));
    out.add(new Language("amq", "Amahai", "I", "L", null, null, null, null));
    out.add(new Language("amr", "Amarakaeri", "I", "L", null, null, null, null));
    out.add(new Language("ams", "Southern Amami-Oshima", "I", "L", null, null, "Amami-Oshima, Southern", null));
    out.add(new Language("amt", "Amto", "I", "L", null, null, null, null));
    out.add(new Language("amu", "Guerrero Amuzgo", "I", "L", null, null, "Amuzgo, Guerrero", null));
    out.add(new Language("amv", "Ambelau", "I", "L", null, null, null, null));
    out.add(new Language("amw", "Western Neo-Aramaic", "I", "L", null, null, "Neo-Aramaic, Western", null));
    out.add(new Language("amx", "Anmatyerre", "I", "L", null, null, null, null));
    out.add(new Language("amy", "Ami", "I", "L", null, null, null, null));
    out.add(new Language("amz", "Atampaya", "I", "E", null, null, null, null));
    out.add(new Language("ana", "Andaqui", "I", "E", null, null, null, null));
    out.add(new Language("anb", "Andoa", "I", "E", null, null, null, null));
    out.add(new Language("anc", "Ngas", "I", "L", null, null, null, null));
    out.add(new Language("and", "Ansus", "I", "L", null, null, null, null));
    out.add(new Language("ane", "Xârâcùù", "I", "L", null, null, null, null));
    out.add(new Language("anf", "Animere", "I", "L", null, null, null, null));
    out.add(new Language("ang", "Old English (ca. 450-1100)", "I", "H", null, null, "English, Old (ca. 450-1100)", null));
    out.add(new Language("anh", "Nend", "I", "L", null, null, null, null));
    out.add(new Language("ani", "Andi", "I", "L", null, null, null, null));
    out.add(new Language("anj", "Anor", "I", "L", null, null, null, null));
    out.add(new Language("ank", "Goemai", "I", "L", null, null, null, null));
    out.add(new Language("anl", "Anu-Hkongso Chin", "I", "L", null, null, "Chin, Anu-Hkongso", null));
    out.add(new Language("anm", "Anal", "I", "L", null, null, null, null));
    out.add(new Language("ann", "Obolo", "I", "L", null, null, null, null));
    out.add(new Language("ano", "Andoque", "I", "L", null, null, null, null));
    out.add(new Language("anp", "Angika", "I", "L", null, null, null, null));
    out.add(new Language("anq", "Jarawa (India)", "I", "L", null, null, null, null));
    out.add(new Language("anr", "Andh", "I", "L", null, null, null, null));
    out.add(new Language("ans", "Anserma", "I", "E", null, null, null, null));
    out.add(new Language("ant", "Antakarinya", "I", "L", null, null, null, null));
    out.add(new Language("anu", "Anuak", "I", "L", null, null, null, null));
    out.add(new Language("anv", "Denya", "I", "L", null, null, null, null));
    out.add(new Language("anw", "Anaang", "I", "L", null, null, null, null));
    out.add(new Language("anx", "Andra-Hus", "I", "L", null, null, null, null));
    out.add(new Language("any", "Anyin", "I", "L", null, null, null, null));
    out.add(new Language("anz", "Anem", "I", "L", null, null, null, null));
    out.add(new Language("aoa", "Angolar", "I", "L", null, null, null, null));
    out.add(new Language("aob", "Abom", "I", "L", null, null, null, null));
    out.add(new Language("aoc", "Pemon", "I", "L", null, null, null, null));
    out.add(new Language("aod", "Andarum", "I", "L", null, null, null, null));
    out.add(new Language("aoe", "Angal Enen", "I", "L", null, null, null, null));
    out.add(new Language("aof", "Bragat", "I", "L", null, null, null, null));
    out.add(new Language("aog", "Angoram", "I", "L", null, null, null, null));
    out.add(new Language("aoi", "Anindilyakwa", "I", "L", null, null, null, null));
    out.add(new Language("aoj", "Mufian", "I", "L", null, null, null, null));
    out.add(new Language("aok", "Arhö", "I", "L", null, null, null, null));
    out.add(new Language("aol", "Alor", "I", "L", null, null, null, null));
    out.add(new Language("aom", "Ömie", "I", "L", null, null, null, null));
    out.add(new Language("aon", "Bumbita Arapesh", "I", "L", null, null, "Arapesh, Bumbita", null));
    out.add(new Language("aor", "Aore", "I", "E", null, null, null, null));
    out.add(new Language("aos", "Taikat", "I", "L", null, null, null, null));
    out.add(new Language("aot", "Atong (India)", "I", "L", null, null, null, null));
    out.add(new Language("aou", "A'ou", "I", "L", null, null, null, null));
    out.add(new Language("aox", "Atorada", "I", "L", null, null, null, null));
    out.add(new Language("aoz", "Uab Meto", "I", "L", null, null, null, null));
    out.add(new Language("apb", "Sa'a", "I", "L", null, null, null, null));
    out.add(new Language("apc", "Levantine Arabic", "I", "L", null, null, "Arabic, Levantine", null));
    out.add(new Language("apd", "Sudanese Arabic", "I", "L", null, null, "Arabic, Sudanese", null));
    out.add(new Language("ape", "Bukiyip", "I", "L", null, null, null, null));
    out.add(new Language("apf", "Pahanan Agta", "I", "L", null, null, "Agta, Pahanan", null));
    out.add(new Language("apg", "Ampanang", "I", "L", null, null, null, null));
    out.add(new Language("aph", "Athpariya", "I", "L", null, null, null, null));
    out.add(new Language("api", "Apiaká", "I", "L", null, null, null, null));
    out.add(new Language("apj", "Jicarilla Apache", "I", "L", null, null, "Apache, Jicarilla", null));
    out.add(new Language("apk", "Kiowa Apache", "I", "L", null, null, "Apache, Kiowa", null));
    out.add(new Language("apl", "Lipan Apache", "I", "L", null, null, "Apache, Lipan", null));
    out.add(new Language("apm", "Mescalero-Chiricahua Apache", "I", "L", null, null, "Apache, Mescalero-Chiricahua", null));
    out.add(new Language("apn", "Apinayé", "I", "L", null, null, null, null));
    out.add(new Language("apo", "Ambul", "I", "L", null, null, null, null));
    out.add(new Language("app", "Apma", "I", "L", null, null, null, null));
    out.add(new Language("apq", "A-Pucikwar", "I", "L", null, null, null, null));
    out.add(new Language("apr", "Arop-Lokep", "I", "L", null, null, null, null));
    out.add(new Language("aps", "Arop-Sissano", "I", "L", null, null, null, null));
    out.add(new Language("apt", "Apatani", "I", "L", null, null, null, null));
    out.add(new Language("apu", "Apurinã", "I", "L", null, null, null, null));
    out.add(new Language("apv", "Alapmunte", "I", "E", null, null, null, null));
    out.add(new Language("apw", "Western Apache", "I", "L", null, null, "Apache, Western", null));
    out.add(new Language("apx", "Aputai", "I", "L", null, null, null, null));
    out.add(new Language("apy", "Apalaí", "I", "L", null, null, null, null));
    out.add(new Language("apz", "Safeyoka", "I", "L", null, null, null, null));
    out.add(new Language("aqc", "Archi", "I", "L", null, null, null, null));
    out.add(new Language("aqd", "Ampari Dogon", "I", "L", null, null, "Dogon, Ampari", null));
    out.add(new Language("aqg", "Arigidi", "I", "L", null, null, null, null));
    out.add(new Language("aqk", "Aninka", "I", "L", null, null, null, null));
    out.add(new Language("aqm", "Atohwaim", "I", "L", null, null, null, null));
    out.add(new Language("aqn", "Northern Alta", "I", "L", null, null, "Alta, Northern", null));
    out.add(new Language("aqp", "Atakapa", "I", "E", null, null, null, null));
    out.add(new Language("aqr", "Arhâ", "I", "L", null, null, null, null));
    out.add(new Language("aqt", "Angaité", "I", "L", null, null, null, null));
    out.add(new Language("aqz", "Akuntsu", "I", "L", null, null, null, null));
    out.add(new Language("ara", "Arabic", "M", "L", "ar", null, null, null));
    out.add(new Language("arb", "Standard Arabic", "I", "L", null, null, "Arabic, Standard", null));
    out.add(new Language("arc", "Official Aramaic (700-300 BCE)", "I", "H", null, null, "Aramaic, Official (700-300 BCE)", null));
    out.add(new Language("ard", "Arabana", "I", "E", null, null, null, null));
    out.add(new Language("are", "Western Arrarnta", "I", "L", null, null, "Arrarnta, Western", null));
    out.add(new Language("arg", "Aragonese", "I", "L", "an", null, null, null));
    out.add(new Language("arh", "Arhuaco", "I", "L", null, null, null, null));
    out.add(new Language("ari", "Arikara", "I", "L", null, null, null, null));
    out.add(new Language("arj", "Arapaso", "I", "E", null, null, null, null));
    out.add(new Language("ark", "Arikapú", "I", "L", null, null, null, null));
    out.add(new Language("arl", "Arabela", "I", "L", null, null, null, null));
    out.add(new Language("arn", "Mapudungun", "I", "L", null, null, null, null));
    out.add(new Language("aro", "Araona", "I", "L", null, null, null, null));
    out.add(new Language("arp", "Arapaho", "I", "L", null, null, null, null));
    out.add(new Language("arq", "Algerian Arabic", "I", "L", null, null, "Arabic, Algerian", null));
    out.add(new Language("arr", "Karo (Brazil)", "I", "L", null, null, null, null));
    out.add(new Language("ars", "Najdi Arabic", "I", "L", null, null, "Arabic, Najdi", null));
    out.add(new Language("aru", "Aruá (Amazonas State)", "I", "E", null, null, null, null));
    out.add(new Language("arv", "Arbore", "I", "L", null, null, null, null));
    out.add(new Language("arw", "Arawak", "I", "L", null, null, null, null));
    out.add(new Language("arx", "Aruá (Rodonia State)", "I", "L", null, null, null, null));
    out.add(new Language("ary", "Moroccan Arabic", "I", "L", null, null, "Arabic, Moroccan", null));
    out.add(new Language("arz", "Egyptian Arabic", "I", "L", null, null, "Arabic, Egyptian", null));
    out.add(new Language("asa", "Asu (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("asb", "Assiniboine", "I", "L", null, null, null, null));
    out.add(new Language("asc", "Casuarina Coast Asmat", "I", "L", null, null, "Asmat, Casuarina Coast", null));
    out.add(new Language("ase", "American Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("asf", "Auslan", "I", "L", null, null, null, null));
    out.add(new Language("asg", "Cishingini", "I", "L", null, null, null, null));
    out.add(new Language("ash", "Abishira", "I", "E", null, null, null, null));
    out.add(new Language("asi", "Buruwai", "I", "L", null, null, null, null));
    out.add(new Language("asj", "Sari", "I", "L", null, null, null, null));
    out.add(new Language("ask", "Ashkun", "I", "L", null, null, null, null));
    out.add(new Language("asl", "Asilulu", "I", "L", null, null, null, null));
    out.add(new Language("asm", "Assamese", "I", "L", "as", null, null, null));
    out.add(new Language("asn", "Xingú Asuriní", "I", "L", null, null, "Asuriní, Xingú", null));
    out.add(new Language("aso", "Dano", "I", "L", null, null, null, null));
    out.add(new Language("asp", "Algerian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("asq", "Austrian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("asr", "Asuri", "I", "L", null, null, null, null));
    out.add(new Language("ass", "Ipulo", "I", "L", null, null, null, null));
    out.add(new Language("ast", "Asturian", "I", "L", null, null, null, null));
    out.add(new Language("asu", "Tocantins Asurini", "I", "L", null, null, "Asurini, Tocantins", null));
    out.add(new Language("asv", "Asoa", "I", "L", null, null, null, null));
    out.add(new Language("asw", "Australian Aborigines Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("asx", "Muratayak", "I", "L", null, null, null, null));
    out.add(new Language("asy", "Yaosakor Asmat", "I", "L", null, null, "Asmat, Yaosakor", null));
    out.add(new Language("asz", "As", "I", "L", null, null, null, null));
    out.add(new Language("ata", "Pele-Ata", "I", "L", null, null, null, null));
    out.add(new Language("atb", "Zaiwa", "I", "L", null, null, null, null));
    out.add(new Language("atc", "Atsahuaca", "I", "E", null, null, null, null));
    out.add(new Language("atd", "Ata Manobo", "I", "L", null, null, "Manobo, Ata", null));
    out.add(new Language("ate", "Atemble", "I", "L", null, null, null, null));
    out.add(new Language("atg", "Ivbie North-Okpela-Arhe", "I", "L", null, null, null, null));
    out.add(new Language("ati", "Attié", "I", "L", null, null, null, null));
    out.add(new Language("atj", "Atikamekw", "I", "L", null, null, null, null));
    out.add(new Language("atk", "Ati", "I", "L", null, null, null, null));
    out.add(new Language("atl", "Mt. Iraya Agta", "I", "L", null, null, "Agta, Mt. Iraya", null));
    out.add(new Language("atm", "Ata", "I", "L", null, null, null, null));
    out.add(new Language("atn", "Ashtiani", "I", "L", null, null, null, null));
    out.add(new Language("ato", "Atong (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("atp", "Pudtol Atta", "I", "L", null, null, "Atta, Pudtol", null));
    out.add(new Language("atq", "Aralle-Tabulahan", "I", "L", null, null, null, null));
    out.add(new Language("atr", "Waimiri-Atroari", "I", "L", null, null, null, null));
    out.add(new Language("ats", "Gros Ventre", "I", "L", null, null, null, null));
    out.add(new Language("att", "Pamplona Atta", "I", "L", null, null, "Atta, Pamplona", null));
    out.add(new Language("atu", "Reel", "I", "L", null, null, null, null));
    out.add(new Language("atv", "Northern Altai", "I", "L", null, null, "Altai, Northern", null));
    out.add(new Language("atw", "Atsugewi", "I", "L", null, null, null, null));
    out.add(new Language("atx", "Arutani", "I", "L", null, null, null, null));
    out.add(new Language("aty", "Aneityum", "I", "L", null, null, null, null));
    out.add(new Language("atz", "Arta", "I", "L", null, null, null, null));
    out.add(new Language("aua", "Asumboa", "I", "L", null, null, null, null));
    out.add(new Language("aub", "Alugu", "I", "L", null, null, null, null));
    out.add(new Language("auc", "Waorani", "I", "L", null, null, null, null));
    out.add(new Language("aud", "Anuta", "I", "L", null, null, null, null));
    out.add(new Language("aug", "Aguna", "I", "L", null, null, null, null));
    out.add(new Language("auh", "Aushi", "I", "L", null, null, null, null));
    out.add(new Language("aui", "Anuki", "I", "L", null, null, null, null));
    out.add(new Language("auj", "Awjilah", "I", "L", null, null, null, null));
    out.add(new Language("auk", "Heyo", "I", "L", null, null, null, null));
    out.add(new Language("aul", "Aulua", "I", "L", null, null, null, null));
    out.add(new Language("aum", "Asu (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("aun", "Molmo One", "I", "L", null, null, "One, Molmo", null));
    out.add(new Language("auo", "Auyokawa", "I", "E", null, null, null, null));
    out.add(new Language("aup", "Makayam", "I", "L", null, null, null, null));
    out.add(new Language("auq", "Anus", "I", "L", null, null, null, null));
    out.add(new Language("aur", "Aruek", "I", "L", null, null, null, null));
    out.add(new Language("aut", "Austral", "I", "L", null, null, null, null));
    out.add(new Language("auu", "Auye", "I", "L", null, null, null, null));
    out.add(new Language("auw", "Awyi", "I", "L", null, null, null, null));
    out.add(new Language("aux", "Aurá", "I", "E", null, null, null, null));
    out.add(new Language("auy", "Awiyaana", "I", "L", null, null, null, null));
    out.add(new Language("auz", "Uzbeki Arabic", "I", "L", null, null, "Arabic, Uzbeki", null));
    out.add(new Language("ava", "Avaric", "I", "L", "av", null, null, null));
    out.add(new Language("avb", "Avau", "I", "L", null, null, null, null));
    out.add(new Language("avd", "Alviri-Vidari", "I", "L", null, null, null, null));
    out.add(new Language("ave", "Avestan", "I", "H", "ae", null, null, null));
    out.add(new Language("avi", "Avikam", "I", "L", null, null, null, null));
    out.add(new Language("avk", "Kotava", "I", "C", null, null, null, null));
    out.add(new Language("avl", "Eastern Egyptian Bedawi Arabic", "I", "L", null, null, "Arabic, Eastern Egyptian Bedawi", null));
    out.add(new Language("avm", "Angkamuthi", "I", "E", null, null, null, null));
    out.add(new Language("avn", "Avatime", "I", "L", null, null, null, null));
    out.add(new Language("avo", "Agavotaguerra", "I", "E", null, null, null, null));
    out.add(new Language("avs", "Aushiri", "I", "E", null, null, null, null));
    out.add(new Language("avt", "Au", "I", "L", null, null, null, null));
    out.add(new Language("avu", "Avokaya", "I", "L", null, null, null, null));
    out.add(new Language("avv", "Avá-Canoeiro", "I", "L", null, null, null, null));
    out.add(new Language("awa", "Awadhi", "I", "L", null, null, null, null));
    out.add(new Language("awb", "Awa (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("awc", "Cicipu", "I", "L", null, null, null, null));
    out.add(new Language("awe", "Awetí", "I", "L", null, null, null, null));
    out.add(new Language("awg", "Anguthimri", "I", "E", null, null, null, null));
    out.add(new Language("awh", "Awbono", "I", "L", null, null, null, null));
    out.add(new Language("awi", "Aekyom", "I", "L", null, null, null, null));
    out.add(new Language("awk", "Awabakal", "I", "E", null, null, null, null));
    out.add(new Language("awm", "Arawum", "I", "L", null, null, null, null));
    out.add(new Language("awn", "Awngi", "I", "L", null, null, null, null));
    out.add(new Language("awo", "Awak", "I", "L", null, null, null, null));
    out.add(new Language("awr", "Awera", "I", "L", null, null, null, null));
    out.add(new Language("aws", "South Awyu", "I", "L", null, null, "Awyu, South", null));
    out.add(new Language("awt", "Araweté", "I", "L", null, null, null, null));
    out.add(new Language("awu", "Central Awyu", "I", "L", null, null, "Awyu, Central", null));
    out.add(new Language("awv", "Jair Awyu", "I", "L", null, null, "Awyu, Jair", null));
    out.add(new Language("aww", "Awun", "I", "L", null, null, null, null));
    out.add(new Language("awx", "Awara", "I", "L", null, null, null, null));
    out.add(new Language("awy", "Edera Awyu", "I", "L", null, null, "Awyu, Edera", null));
    out.add(new Language("axb", "Abipon", "I", "E", null, null, null, null));
    out.add(new Language("axe", "Ayerrerenge", "I", "E", null, null, null, null));
    out.add(new Language("axg", "Mato Grosso Arára", "I", "E", null, null, "Arára, Mato Grosso", null));
    out.add(new Language("axk", "Yaka (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("axl", "Lower Southern Aranda", "I", "E", null, null, "Aranda, Lower Southern", null));
    out.add(new Language("axm", "Middle Armenian", "I", "H", null, null, "Armenian, Middle", null));
    out.add(new Language("axx", "Xârâgurè", "I", "L", null, null, null, null));
    out.add(new Language("aya", "Awar", "I", "L", null, null, null, null));
    out.add(new Language("ayb", "Ayizo Gbe", "I", "L", null, null, "Gbe, Ayizo", null));
    out.add(new Language("ayc", "Southern Aymara", "I", "L", null, null, "Aymara, Southern", null));
    out.add(new Language("ayd", "Ayabadhu", "I", "E", null, null, null, null));
    out.add(new Language("aye", "Ayere", "I", "L", null, null, null, null));
    out.add(new Language("ayg", "Ginyanga", "I", "L", null, null, null, null));
    out.add(new Language("ayh", "Hadrami Arabic", "I", "L", null, null, "Arabic, Hadrami", null));
    out.add(new Language("ayi", "Leyigha", "I", "L", null, null, null, null));
    out.add(new Language("ayk", "Akuku", "I", "L", null, null, null, null));
    out.add(new Language("ayl", "Libyan Arabic", "I", "L", null, null, "Arabic, Libyan", null));
    out.add(new Language("aym", "Aymara", "M", "L", "ay", null, null, null));
    out.add(new Language("ayn", "Sanaani Arabic", "I", "L", null, null, "Arabic, Sanaani", null));
    out.add(new Language("ayo", "Ayoreo", "I", "L", null, null, null, null));
    out.add(new Language("ayp", "North Mesopotamian Arabic", "I", "L", null, null, "Arabic, North Mesopotamian", null));
    out.add(new Language("ayq", "Ayi (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("ayr", "Central Aymara", "I", "L", null, null, "Aymara, Central", null));
    out.add(new Language("ays", "Sorsogon Ayta", "I", "L", null, null, "Ayta, Sorsogon", null));
    out.add(new Language("ayt", "Magbukun Ayta", "I", "L", null, null, "Ayta, Magbukun", null));
    out.add(new Language("ayu", "Ayu", "I", "L", null, null, null, null));
    out.add(new Language("ayz", "Mai Brat", "I", "L", null, null, null, null));
    out.add(new Language("aza", "Azha", "I", "L", null, null, null, null));
    out.add(new Language("azb", "South Azerbaijani", "I", "L", null, null, "Azerbaijani, South", null));
  }
}
