// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 6000 to 6499 of {@link Language}.
 */
final class LanguageData12 {
  private LanguageData12() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("sop", "Songe", "I", "L", null, null, null, null));
    out.add(new Language("soq", "Kanasi", "I", "L", null, null, null, null));
    out.add(new Language("sor", "Somrai", "I", "L", null, null, null, null));
    out.add(new Language("sos", "Seeku", "I", "L", null, null, null, null));
    out.add(new Language("sot", "Southern Sotho", "I", "L", "st", null, "Sotho, Southern", null));
    out.add(new Language("sou", "Southern Thai", "I", "L", null, null, "Thai, Southern", null));
    out.add(new Language("sov", "Sonsorol", "I", "L", null, null, null, null));
    out.add(new Language("sow", "Sowanda", "I", "L", null, null, null, null));
    out.add(new Language("sox", "Swo", "I", "L", null, null, null, null));
    out.add(new Language("soy", "Miyobe", "I", "L", null, null, null, null));
    out.add(new Language("soz", "Temi", "I", "L", null, null, null, null));
    out.add(new Language("spa", "Spanish", "I", "L", "es", null, null, null));
    out.add(new Language("spb", "Sepa (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("spc", "Sapé", "I", "L", null, null, null, null));
    out.add(new Language("spd", "Saep", "I", "L", null, null, null, null));
    out.add(new Language("spe", "Sepa (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("spg", "Sian", "I", "L", null, null, null, null));
    out.add(new Language("spi", "Saponi", "I", "L", null, null, null, null));
    out.add(new Language("spk", "Sengo", "I", "L", null, null, null, null));
    out.add(new Language("spl", "Selepet", "I", "L", null, null, null, null));
    out.add(new Language("spm", "Akukem", "I", "L", null, null, null, null));
    out.add(new Language("spn", "Sanapaná", "I", "L", null, null, null, null));
    out.add(new Language("spo", "Spokane", "I", "L", null, null, null, null));
    out.add(new Language("spp", "Supyire Senoufo", "I", "L", null, null, "Senoufo, Supyire", null));
    out.add(new Language("spq", "Loreto-Ucayali Spanish", "I", "L", null, null, "Spanish, Loreto-Ucayali", null));
    out.add(new Language("spr", "Saparua", "I", "L", null, null, null, null));
    out.add(new Language("sps", "Saposa", "I", "L", null, null, null, null));
    out.add(new Language("spt", "Spiti Bhoti", "I", "L", null, null, "Bhoti, Spiti", null));
    out.add(new Language("spu", "Sapuan", "I", "L", null, null, null, null));
    out.add(new Language("spv", "Sambalpuri", "I", "L", null, null, null, null));
    out.add(new Language("spx", "South Picene", "I", "H", null, null, "Picene, South", null));
    out.add(new Language("spy", "Sabaot", "I", "L", null, null, null, null));
    out.add(new Language("sqa", "Shama-Sambuga", "I", "L", null, null, null, null));
    out.add(new Language("sqh", "Shau", "I", "L", null, null, null, null));
    out.add(new Language("sqi", "Albanian", "M", "L", "sq", null, null, "alb"));
    out.add(new Language("sqk", "Albanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sqm", "Suma", "I", "L", null, null, null, null));
    out.add(new Language("sqn", "Susquehannock", "I", "E", null, null, null, null));
    out.add(new Language("sqo", "Sorkhei", "I", "L", null, null, null, null));
    out.add(new Language("sqq", "Sou", "I", "L", null, null, null, null));
    out.add(new Language("sqr", "Siculo Arabic", "I", "H", null, null, "Arabic, Siculo", null));
    out.add(new Language("sqs", "Sri Lankan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sqt", "Soqotri", "I", "L", null, null, null, null));
    out.add(new Language("squ", "Squamish", "I", "L", null, null, null, null));
    out.add(new Language("sqx", "Kufr Qassem Sign Language (KQSL)", "I", "L", null, null, null, null));
    out.add(new Language("sra", "Saruga", "I", "L", null, null, null, null));
    out.add(new Language("srb", "Sora", "I", "L", null, null, null, null));
    out.add(new Language("src", "Logudorese Sardinian", "I", "L", null, null, "Sardinian, Logudorese", null));
    out.add(new Language("srd", "Sardinian", "M", "L", "sc", null, null, null));
    out.add(new Language("sre", "Sara", "I", "L", null, null, null, null));
    out.add(new Language("srf", "Nafi", "I", "L", null, null, null, null));
    out.add(new Language("srg", "Sulod", "I", "L", null, null, null, null));
    out.add(new Language("srh", "Sarikoli", "I", "L", null, null, null, null));
    out.add(new Language("sri", "Siriano", "I", "L", null, null, null, null));
    out.add(new Language("srk", "Serudung Murut", "I", "L", null, null, null, null));
    out.add(new Language("srl", "Isirawa", "I", "L", null, null, null, null));
    out.add(new Language("srm", "Saramaccan", "I", "L", null, null, null, null));
    out.add(new Language("srn", "Sranan Tongo", "I", "L", null, null, null, null));
    out.add(new Language("sro", "Campidanese Sardinian", "I", "L", null, null, "Sardinian, Campidanese", null));
    out.add(new Language("srp", "Serbian", "I", "L", "sr", null, null, null));
    out.add(new Language("srq", "Sirionó", "I", "L", null, null, null, null));
    out.add(new Language("srr", "Serer", "I", "L", null, null, null, null));
    out.add(new Language("srs", "Sarsi", "I", "L", null, null, null, null));
    out.add(new Language("srt", "Sauri", "I", "L", null, null, null, null));
    out.add(new Language("sru", "Suruí", "I", "L", null, null, null, null));
    out.add(new Language("srv", "Southern Sorsoganon", "I", "L", null, null, "Sorsoganon, Southern", null));
    out.add(new Language("srw", "Serua", "I", "L", null, null, null, null));
    out.add(new Language("srx", "Sirmauri", "I", "L", null, null, null, null));
    out.add(new Language("sry", "Sera", "I", "L", null, null, null, null));
    out.add(new Language("srz", "Shahmirzadi", "I", "L", null, null, null, null));
    out.add(new Language("ssb", "Southern Sama", "I", "L", null, null, "Sama, Southern", null));
    out.add(new Language("ssc", "Suba-Simbiti", "I", "L", null, null, null, null));
    out.add(new Language("ssd", "Siroi", "I", "L", null, null, null, null));
    out.add(new Language("sse", "Balangingi", "I", "L", null, null, null, null));
    out.add(new Language("ssf", "Thao", "I", "L", null, null, null, null));
    out.add(new Language("ssg", "Seimat", "I", "L", null, null, null, null));
    out.add(new Language("ssh", "Shihhi Arabic", "I", "L", null, null, "Arabic, Shihhi", null));
    out.add(new Language("ssi", "Sansi", "I", "L", null, null, null, null));
    out.add(new Language("ssj", "Sausi", "I", "L", null, null, null, null));
    out.add(new Language("ssk", "Sunam", "I", "L", null, null, null, null));
    out.add(new Language("ssl", "Western Sisaala", "I", "L", null, null, "Sisaala, Western", null));
    out.add(new Language("ssm", "Semnam", "I", "L", null, null, null, null));
    out.add(new Language("ssn", "Waata", "I", "L", null, null, null, null));
    out.add(new Language("sso", "Sissano", "I", "L", null, null, null, null));
    out.add(new Language("ssp", "Spanish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ssq", "So'a", "I", "L", null, null, null, null));
    out.add(new Language("ssr", "Swiss-French Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sss", "Sô", "I", "L", null, null, null, null));
    out.add(new Language("sst", "Sinasina", "I", "L", null, null, null, null));
    out.add(new Language("ssu", "Susuami", "I", "L", null, null, null, null));
    out.add(new Language("ssv", "Shark Bay", "I", "L", null, null, null, null));
    out.add(new Language("ssw", "Swati", "I", "L", "ss", null, null, null));
    out.add(new Language("ssx", "Samberigi", "I", "L", null, null, null, null));
    out.add(new Language("ssy", "Saho", "I", "L", null, null, null, null));
    out.add(new Language("ssz", "Sengseng", "I", "L", null, null, null, null));
    out.add(new Language("sta", "Settla", "I", "L", null, null, null, null));
    out.add(new Language("stb", "Northern Subanen", "I", "L", null, null, "Subanen, Northern", null));
    out.add(new Language("std", "Sentinel", "I", "L", null, null, null, null));
    out.add(new Language("ste", "Liana-Seti", "I", "L", null, null, null, null));
    out.add(new Language("stf", "Seta", "I", "L", null, null, null, null));
    out.add(new Language("stg", "Trieng", "I", "L", null, null, null, null));
    out.add(new Language("sth", "Shelta", "I", "L", null, null, null, null));
    out.add(new Language("sti", "Bulo Stieng", "I", "L", null, null, "Stieng, Bulo", null));
    out.add(new Language("stj", "Matya Samo", "I", "L", null, null, "Samo, Matya", null));
    out.add(new Language("stk", "Arammba", "I", "L", null, null, null, null));
    out.add(new Language("stl", "Stellingwerfs", "I", "L", null, null, null, null));
    out.add(new Language("stm", "Setaman", "I", "L", null, null, null, null));
    out.add(new Language("stn", "Owa", "I", "L", null, null, null, null));
    out.add(new Language("sto", "Stoney", "I", "L", null, null, null, null));
    out.add(new Language("stp", "Southeastern Tepehuan", "I", "L", null, null, "Tepehuan, Southeastern", null));
    out.add(new Language("stq", "Saterfriesisch", "I", "L", null, null, null, null));
    out.add(new Language("str", "Straits Salish", "I", "L", null, null, "Salish, Straits", null));
    out.add(new Language("sts", "Shumashti", "I", "L", null, null, null, null));
    out.add(new Language("stt", "Budeh Stieng", "I", "L", null, null, "Stieng, Budeh", null));
    out.add(new Language("stu", "Samtao", "I", "L", null, null, null, null));
    out.add(new Language("stv", "Silt'e", "I", "L", null, null, null, null));
    out.add(new Language("stw", "Satawalese", "I", "L", null, null, null, null));
    out.add(new Language("sty", "Siberian Tatar", "I", "L", null, null, "Tatar, Siberian", null));
    out.add(new Language("sua", "Sulka", "I", "L", null, null, null, null));
    out.add(new Language("sub", "Suku", "I", "L", null, null, null, null));
    out.add(new Language("suc", "Western Subanon", "I", "L", null, null, "Subanon, Western", null));
    out.add(new Language("sue", "Suena", "I", "L", null, null, null, null));
    out.add(new Language("sug", "Suganga", "I", "L", null, null, null, null));
    out.add(new Language("sui", "Suki", "I", "L", null, null, null, null));
    out.add(new Language("suj", "Shubi", "I", "L", null, null, null, null));
    out.add(new Language("suk", "Sukuma", "I", "L", null, null, null, null));
    out.add(new Language("sun", "Sundanese", "I", "L", "su", null, null, null));
    out.add(new Language("suo", "Bouni", "I", "L", null, null, null, null));
    out.add(new Language("suq", "Tirmaga-Chai Suri", "I", "L", null, null, "Suri, Tirmaga-Chai", null));
    out.add(new Language("sur", "Mwaghavul", "I", "L", null, null, null, null));
    out.add(new Language("sus", "Susu", "I", "L", null, null, null, null));
    out.add(new Language("sut", "Subtiaba", "I", "E", null, null, null, null));
    out.add(new Language("suv", "Puroik", "I", "L", null, null, null, null));
    out.add(new Language("suw", "Sumbwa", "I", "L", null, null, null, null));
    out.add(new Language("sux", "Sumerian", "I", "H", null, null, null, null));
    out.add(new Language("suy", "Suyá", "I", "L", null, null, null, null));
    out.add(new Language("suz", "Sunwar", "I", "L", null, null, null, null));
    out.add(new Language("sva", "Svan", "I", "L", null, null, null, null));
    out.add(new Language("svb", "Ulau-Suain", "I", "L", null, null, null, null));
    out.add(new Language("svc", "Vincentian Creole English", "I", "L", null, null, "Creole English, Vincentian", null));
    out.add(new Language("sve", "Serili", "I", "L", null, null, null, null));
    out.add(new Language("svk", "Slovakian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("svm", "Slavomolisano", "I", "L", null, null, null, null));
    out.add(new Language("svs", "Savosavo", "I", "L", null, null, null, null));
    out.add(new Language("svx", "Skalvian", "I", "H", null, null, null, null));
    out.add(new Language("swa", "Swahili (macrolanguage)", "M", "L", "sw", null, null, null));
    out.add(new Language("swb", "Maore Comorian", "I", "L", null, null, "Comorian, Maore", null));
    out.add(new Language("swc", "Congo Swahili", "I", "L", null, null, "Swahili, Congo", null));
    out.add(new Language("swe", "Swedish", "I", "L", "sv", null, null, null));
    out.add(new Language("swf", "Sere", "I", "L", null, null, null, null));
    out.add(new Language("swg", "Swabian", "I", "L", null, null, null, null));
    out.add(new Language("swh", "Swahili (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("swi", "Sui", "I", "L", null, null, null, null));
    out.add(new Language("swj", "Sira", "I", "L", null, null, null, null));
    out.add(new Language("swk", "Malawi Sena", "I", "L", null, null, "Sena, Malawi", null));
    out.add(new Language("swl", "Swedish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("swm", "Samosa", "I", "L", null, null, null, null));
    out.add(new Language("swn", "Sawknah", "I", "L", null, null, null, null));
    out.add(new Language("swo", "Shanenawa", "I", "L", null, null, null, null));
    out.add(new Language("swp", "Suau", "I", "L", null, null, null, null));
    out.add(new Language("swq", "Sharwa", "I", "L", null, null, null, null));
    out.add(new Language("swr", "Saweru", "I", "L", null, null, null, null));
    out.add(new Language("sws", "Seluwasan", "I", "L", null, null, null, null));
    out.add(new Language("swt", "Sawila", "I", "L", null, null, null, null));
    out.add(new Language("swu", "Suwawa", "I", "L", null, null, null, null));
    out.add(new Language("swv", "Shekhawati", "I", "L", null, null, null, null));
    out.add(new Language("sww", "Sowa", "I", "E", null, null, null, null));
    out.add(new Language("swx", "Suruahá", "I", "L", null, null, null, null));
    out.add(new Language("swy", "Sarua", "I", "L", null, null, null, null));
    out.add(new Language("sxb", "Suba", "I", "L", null, null, null, null));
    out.add(new Language("sxc", "Sicanian", "I", "H", null, null, null, null));
    out.add(new Language("sxe", "Sighu", "I", "L", null, null, null, null));
    out.add(new Language("sxg", "Shuhi", "I", "L", null, null, null, null));
    out.add(new Language("sxk", "Southern Kalapuya", "I", "E", null, null, "Kalapuya, Southern", null));
    out.add(new Language("sxl", "Selian", "I", "E", null, null, null, null));
    out.add(new Language("sxm", "Samre", "I", "L", null, null, null, null));
    out.add(new Language("sxn", "Sangir", "I", "L", null, null, null, null));
    out.add(new Language("sxo", "Sorothaptic", "I", "H", null, null, null, null));
    out.add(new Language("sxr", "Saaroa", "I", "L", null, null, null, null));
    out.add(new Language("sxs", "Sasaru", "I", "L", null, null, null, null));
    out.add(new Language("sxu", "Upper Saxon", "I", "L", null, null, "Saxon, Upper", null));
    out.add(new Language("sxw", "Saxwe Gbe", "I", "L", null, null, "Gbe, Saxwe", null));
    out.add(new Language("sya", "Siang", "I", "L", null, null, null, null));
    out.add(new Language("syb", "Central Subanen", "I", "L", null, null, "Subanen, Central", null));
    out.add(new Language("syc", "Classical Syriac", "I", "H", null, null, "Syriac, Classical", null));
    out.add(new Language("syi", "Seki", "I", "L", null, null, null, null));
    out.add(new Language("syk", "Sukur", "I", "L", null, null, null, null));
    out.add(new Language("syl", "Sylheti", "I", "L", null, null, null, null));
    out.add(new Language("sym", "Maya Samo", "I", "L", null, null, "Samo, Maya", null));
    out.add(new Language("syn", "Senaya", "I", "L", null, null, null, null));
    out.add(new Language("syo", "Suoy", "I", "L", null, null, null, null));
    out.add(new Language("syr", "Syriac", "M", "L", null, null, null, null));
    out.add(new Language("sys", "Sinyar", "I", "L", null, null, null, null));
    out.add(new Language("syw", "Kagate", "I", "L", null, null, null, null));
    out.add(new Language("syx", "Samay", "I", "L", null, null, null, null));
    out.add(new Language("syy", "Al-Sayyid Bedouin Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sza", "Semelai", "I", "L", null, null, null, null));
    out.add(new Language("szb", "Ngalum", "I", "L", null, null, null, null));
    out.add(new Language("szc", "Semaq Beri", "I", "L", null, null, null, null));
    out.add(new Language("sze", "Seze", "I", "L", null, null, null, null));
    out.add(new Language("szg", "Sengele", "I", "L", null, null, null, null));
    out.add(new Language("szl", "Silesian", "I", "L", null, null, null, null));
    out.add(new Language("szn", "Sula", "I", "L", null, null, null, null));
    out.add(new Language("szp", "Suabo", "I", "L", null, null, null, null));
    out.add(new Language("szs", "Solomon Islands Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("szv", "Isu (Fako Division)", "I", "L", null, null, null, null));
    out.add(new Language("szw", "Sawai", "I", "L", null, null, null, null));
    out.add(new Language("szy", "Sakizaya", "I", "L", null, null, null, null));
    out.add(new Language("taa", "Lower Tanana", "I", "L", null, null, "Tanana, Lower", null));
    out.add(new Language("tab", "Tabassaran", "I", "L", null, null, null, null));
    out.add(new Language("tac", "Lowland Tarahumara", "I", "L", null, null, "Tarahumara, Lowland", null));
    out.add(new Language("tad", "Tause", "I", "L", null, null, null, null));
    out.add(new Language("tae", "Tariana", "I", "L", null, null, null, null));
    out.add(new Language("taf", "Tapirapé", "I", "L", null, null, null, null));
    out.add(new Language("tag", "Tagoi", "I", "L", null, null, null, null));
    out.add(new Language("tah", "Tahitian", "I", "L", "ty", null, null, null));
    out.add(new Language("taj", "Eastern Tamang", "I", "L", null, null, "Tamang, Eastern", null));
    out.add(new Language("tak", "Tala", "I", "L", null, null, null, null));
    out.add(new Language("tal", "Tal", "I", "L", null, null, null, null));
    out.add(new Language("tam", "Tamil", "I", "L", "ta", null, null, null));
    out.add(new Language("tan", "Tangale", "I", "L", null, null, null, null));
    out.add(new Language("tao", "Yami", "I", "L", null, null, null, null));
    out.add(new Language("tap", "Taabwa", "I", "L", null, null, null, null));
    out.add(new Language("taq", "Tamasheq", "I", "L", null, null, null, null));
    out.add(new Language("tar", "Central Tarahumara", "I", "L", null, null, "Tarahumara, Central", null));
    out.add(new Language("tas", "Tay Boi", "I", "E", null, null, null, null));
    out.add(new Language("tat", "Tatar", "I", "L", "tt", null, null, null));
    out.add(new Language("tau", "Upper Tanana", "I", "L", null, null, "Tanana, Upper", null));
    out.add(new Language("tav", "Tatuyo", "I", "L", null, null, null, null));
    out.add(new Language("taw", "Tai", "I", "L", null, null, null, null));
    out.add(new Language("tax", "Tamki", "I", "L", null, null, null, null));
    out.add(new Language("tay", "Atayal", "I", "L", null, null, null, null));
    out.add(new Language("taz", "Tocho", "I", "L", null, null, null, null));
    out.add(new Language("tba", "Aikanã", "I", "L", null, null, null, null));
    out.add(new Language("tbc", "Takia", "I", "L", null, null, null, null));
    out.add(new Language("tbd", "Kaki Ae", "I", "L", null, null, null, null));
    out.add(new Language("tbe", "Tanimbili", "I", "L", null, null, null, null));
    out.add(new Language("tbf", "Mandara", "I", "L", null, null, null, null));
    out.add(new Language("tbg", "North Tairora", "I", "L", null, null, "Tairora, North", null));
    out.add(new Language("tbh", "Dharawal", "I", "E", null, null, null, null));
    out.add(new Language("tbi", "Gaam", "I", "L", null, null, null, null));
    out.add(new Language("tbj", "Tiang", "I", "L", null, null, null, null));
    out.add(new Language("tbk", "Calamian Tagbanwa", "I", "L", null, null, "Tagbanwa, Calamian", null));
    out.add(new Language("tbl", "Tboli", "I", "L", null, null, null, null));
    out.add(new Language("tbm", "Tagbu", "I", "L", null, null, null, null));
    out.add(new Language("tbn", "Barro Negro Tunebo", "I", "L", null, null, "Tunebo, Barro Negro", null));
    out.add(new Language("tbo", "Tawala", "I", "L", null, null, null, null));
    out.add(new Language("tbp", "Taworta", "I", "L", null, null, null, null));
    out.add(new Language("tbr", "Tumtum", "I", "L", null, null, null, null));
    out.add(new Language("tbs", "Tanguat", "I", "L", null, null, null, null));
    out.add(new Language("tbt", "Tembo (Kitembo)", "I", "L", null, null, null, null));
    out.add(new Language("tbu", "Tubar", "I", "E", null, null, null, null));
    out.add(new Language("tbv", "Tobo", "I", "L", null, null, null, null));
    out.add(new Language("tbw", "Tagbanwa", "I", "L", null, null, null, null));
    out.add(new Language("tbx", "Kapin", "I", "L", null, null, null, null));
    out.add(new Language("tby", "Tabaru", "I", "L", null, null, null, null));
    out.add(new Language("tbz", "Ditammari", "I", "L", null, null, null, null));
    out.add(new Language("tca", "Ticuna", "I", "L", null, null, null, null));
    out.add(new Language("tcb", "Tanacross", "I", "L", null, null, null, null));
    out.add(new Language("tcc", "Datooga", "I", "L", null, null, null, null));
    out.add(new Language("tcd", "Tafi", "I", "L", null, null, null, null));
    out.add(new Language("tce", "Southern Tutchone", "I", "L", null, null, "Tutchone, Southern", null));
    out.add(new Language("tcf", "Malinaltepec Me'phaa", "I", "L", null, null, "Me'phaa, Malinaltepec", null));
    out.add(new Language("tcg", "Tamagario", "I", "L", null, null, null, null));
    out.add(new Language("tch", "Turks And Caicos Creole English", "I", "L", null, null, "Creole English, Turks And Caicos", null));
    out.add(new Language("tci", "Wára", "I", "L", null, null, null, null));
    out.add(new Language("tck", "Tchitchege", "I", "L", null, null, null, null));
    out.add(new Language("tcl", "Taman (Myanmar)", "I", "E", null, null, null, null));
    out.add(new Language("tcm", "Tanahmerah", "I", "L", null, null, null, null));
    out.add(new Language("tcn", "Tichurong", "I", "L", null, null, null, null));
    out.add(new Language("tco", "Taungyo", "I", "L", null, null, null, null));
    out.add(new Language("tcp", "Tawr Chin", "I", "L", null, null, "Chin, Tawr", null));
    out.add(new Language("tcq", "Kaiy", "I", "L", null, null, null, null));
    out.add(new Language("tcs", "Torres Strait Creole", "I", "L", null, null, "Creole, Torres Strait", null));
    out.add(new Language("tct", "T'en", "I", "L", null, null, null, null));
    out.add(new Language("tcu", "Southeastern Tarahumara", "I", "L", null, null, "Tarahumara, Southeastern", null));
    out.add(new Language("tcw", "Tecpatlán Totonac", "I", "L", null, null, "Totonac, Tecpatlán", null));
    out.add(new Language("tcx", "Toda", "I", "L", null, null, null, null));
    out.add(new Language("tcy", "Tulu", "I", "L", null, null, null, null));
    out.add(new Language("tcz", "Thado Chin", "I", "L", null, null, "Chin, Thado", null));
    out.add(new Language("tda", "Tagdal", "I", "L", null, null, null, null));
    out.add(new Language("tdb", "Panchpargania", "I", "L", null, null, null, null));
    out.add(new Language("tdc", "Emberá-Tadó", "I", "L", null, null, null, null));
    out.add(new Language("tdd", "Tai Nüa", "I", "L", null, null, null, null));
    out.add(new Language("tde", "Tiranige Diga Dogon", "I", "L", null, null, "Dogon, Tiranige Diga", null));
    out.add(new Language("tdf", "Talieng", "I", "L", null, null, null, null));
    out.add(new Language("tdg", "Western Tamang", "I", "L", null, null, "Tamang, Western", null));
    out.add(new Language("tdh", "Thulung", "I", "L", null, null, null, null));
    out.add(new Language("tdi", "Tomadino", "I", "L", null, null, null, null));
    out.add(new Language("tdj", "Tajio", "I", "L", null, null, null, null));
    out.add(new Language("tdk", "Tambas", "I", "L", null, null, null, null));
    out.add(new Language("tdl", "Sur", "I", "L", null, null, null, null));
    out.add(new Language("tdm", "Taruma", "I", "L", null, null, null, null));
    out.add(new Language("tdn", "Tondano", "I", "L", null, null, null, null));
    out.add(new Language("tdo", "Teme", "I", "L", null, null, null, null));
    out.add(new Language("tdq", "Tita", "I", "L", null, null, null, null));
    out.add(new Language("tdr", "Todrah", "I", "L", null, null, null, null));
    out.add(new Language("tds", "Doutai", "I", "L", null, null, null, null));
    out.add(new Language("tdt", "Tetun Dili", "I", "L", null, null, null, null));
    out.add(new Language("tdv", "Toro", "I", "L", null, null, null, null));
    out.add(new Language("tdx", "Tandroy-Mahafaly Malagasy", "I", "L", null, null, "Malagasy, Tandroy-Mahafaly", null));
    out.add(new Language("tdy", "Tadyawan", "I", "L", null, null, null, null));
    out.add(new Language("tea", "Temiar", "I", "L", null, null, null, null));
    out.add(new Language("teb", "Tetete", "I", "E", null, null, null, null));
    out.add(new Language("tec", "Terik", "I", "L", null, null, null, null));
    out.add(new Language("ted", "Tepo Krumen", "I", "L", null, null, "Krumen, Tepo", null));
    out.add(new Language("tee", "Huehuetla Tepehua", "I", "L", null, null, "Tepehua, Huehuetla", null));
    out.add(new Language("tef", "Teressa", "I", "L", null, null, null, null));
    out.add(new Language("teg", "Teke-Tege", "I", "L", null, null, null, null));
    out.add(new Language("teh", "Tehuelche", "I", "L", null, null, null, null));
    out.add(new Language("tei", "Torricelli", "I", "L", null, null, null, null));
    out.add(new Language("tek", "Ibali Teke", "I", "L", null, null, "Teke, Ibali", null));
    out.add(new Language("tel", "Telugu", "I", "L", "te", null, null, null));
    out.add(new Language("tem", "Timne", "I", "L", null, null, null, null));
    out.add(new Language("ten", "Tama (Colombia)", "I", "E", null, null, null, null));
    out.add(new Language("teo", "Teso", "I", "L", null, null, null, null));
    out.add(new Language("tep", "Tepecano", "I", "E", null, null, null, null));
    out.add(new Language("teq", "Temein", "I", "L", null, null, null, null));
    out.add(new Language("ter", "Tereno", "I", "L", null, null, null, null));
    out.add(new Language("tes", "Tengger", "I", "L", null, null, null, null));
    out.add(new Language("tet", "Tetum", "I", "L", null, null, null, null));
    out.add(new Language("teu", "Soo", "I", "L", null, null, null, null));
    out.add(new Language("tev", "Teor", "I", "L", null, null, null, null));
    out.add(new Language("tew", "Tewa (USA)", "I", "L", null, null, null, null));
    out.add(new Language("tex", "Tennet", "I", "L", null, null, null, null));
    out.add(new Language("tey", "Tulishi", "I", "L", null, null, null, null));
    out.add(new Language("tez", "Tetserret", "I", "L", null, null, null, null));
    out.add(new Language("tfi", "Tofin Gbe", "I", "L", null, null, "Gbe, Tofin", null));
    out.add(new Language("tfn", "Tanaina", "I", "L", null, null, null, null));
    out.add(new Language("tfo", "Tefaro", "I", "L", null, null, null, null));
    out.add(new Language("tfr", "Teribe", "I", "L", null, null, null, null));
    out.add(new Language("tft", "Ternate", "I", "L", null, null, null, null));
    out.add(new Language("tga", "Sagalla", "I", "L", null, null, null, null));
    out.add(new Language("tgb", "Tobilung", "I", "L", null, null, null, null));
    out.add(new Language("tgc", "Tigak", "I", "L", null, null, null, null));
    out.add(new Language("tgd", "Ciwogai", "I", "L", null, null, null, null));
    out.add(new Language("tge", "Eastern Gorkha Tamang", "I", "L", null, null, "Tamang, Eastern Gorkha", null));
    out.add(new Language("tgf", "Chalikha", "I", "L", null, null, null, null));
    out.add(new Language("tgh", "Tobagonian Creole English", "I", "L", null, null, "Creole English, Tobagonian", null));
    out.add(new Language("tgi", "Lawunuia", "I", "L", null, null, null, null));
    out.add(new Language("tgj", "Tagin", "I", "L", null, null, null, null));
    out.add(new Language("tgk", "Tajik", "I", "L", "tg", null, null, null));
    out.add(new Language("tgl", "Tagalog", "I", "L", "tl", null, null, null));
    out.add(new Language("tgn", "Tandaganon", "I", "L", null, null, null, null));
    out.add(new Language("tgo", "Sudest", "I", "L", null, null, null, null));
    out.add(new Language("tgp", "Tangoa", "I", "L", null, null, null, null));
    out.add(new Language("tgq", "Tring", "I", "L", null, null, null, null));
    out.add(new Language("tgr", "Tareng", "I", "L", null, null, null, null));
    out.add(new Language("tgs", "Nume", "I", "L", null, null, null, null));
    out.add(new Language("tgt", "Central Tagbanwa", "I", "L", null, null, "Tagbanwa, Central", null));
    out.add(new Language("tgu", "Tanggu", "I", "L", null, null, null, null));
    out.add(new Language("tgv", "Tingui-Boto", "I", "E", null, null, null, null));
    out.add(new Language("tgw", "Tagwana Senoufo", "I", "L", null, null, "Senoufo, Tagwana", null));
    out.add(new Language("tgx", "Tagish", "I", "L", null, null, null, null));
    out.add(new Language("tgy", "Togoyo", "I", "E", null, null, null, null));
    out.add(new Language("tgz", "Tagalaka", "I", "E", null, null, null, null));
    out.add(new Language("tha", "Thai", "I", "L", "th", null, null, null));
    out.add(new Language("thd", "Kuuk Thaayorre", "I", "L", null, null, null, null));
    out.add(new Language("the", "Chitwania Tharu", "I", "L", null, null, "Tharu, Chitwania", null));
    out.add(new Language("thf", "Thangmi", "I", "L", null, null, null, null));
    out.add(new Language("thh", "Northern Tarahumara", "I", "L", null, null, "Tarahumara, Northern", null));
    out.add(new Language("thi", "Tai Long", "I", "L", null, null, null, null));
    out.add(new Language("thk", "Tharaka", "I", "L", null, null, null, null));
    out.add(new Language("thl", "Dangaura Tharu", "I", "L", null, null, "Tharu, Dangaura", null));
    out.add(new Language("thm", "Aheu", "I", "L", null, null, null, null));
    out.add(new Language("thn", "Thachanadan", "I", "L", null, null, null, null));
    out.add(new Language("thp", "Thompson", "I", "L", null, null, null, null));
    out.add(new Language("thq", "Kochila Tharu", "I", "L", null, null, "Tharu, Kochila", null));
    out.add(new Language("thr", "Rana Tharu", "I", "L", null, null, "Tharu, Rana", null));
    out.add(new Language("ths", "Thakali", "I", "L", null, null, null, null));
    out.add(new Language("tht", "Tahltan", "I", "L", null, null, null, null));
    out.add(new Language("thu", "Thuri", "I", "L", null, null, null, null));
    out.add(new Language("thv", "Tahaggart Tamahaq", "I", "L", null, null, "Tamahaq, Tahaggart", null));
    out.add(new Language("thy", "Tha", "I", "L", null, null, null, null));
    out.add(new Language("thz", "Tayart Tamajeq", "I", "L", null, null, "Tamajeq, Tayart", null));
    out.add(new Language("tia", "Tidikelt Tamazight", "I", "L", null, null, "Tamazight, Tidikelt", null));
    out.add(new Language("tic", "Tira", "I", "L", null, null, null, null));
    out.add(new Language("tif", "Tifal", "I", "L", null, null, null, null));
    out.add(new Language("tig", "Tigre", "I", "L", null, null, null, null));
    out.add(new Language("tih", "Timugon Murut", "I", "L", null, null, "Murut, Timugon", null));
    out.add(new Language("tii", "Tiene", "I", "L", null, null, null, null));
    out.add(new Language("tij", "Tilung", "I", "L", null, null, null, null));
    out.add(new Language("tik", "Tikar", "I", "L", null, null, null, null));
    out.add(new Language("til", "Tillamook", "I", "E", null, null, null, null));
    out.add(new Language("tim", "Timbe", "I", "L", null, null, null, null));
    out.add(new Language("tin", "Tindi", "I", "L", null, null, null, null));
    out.add(new Language("tio", "Teop", "I", "L", null, null, null, null));
    out.add(new Language("tip", "Trimuris", "I", "L", null, null, null, null));
    out.add(new Language("tiq", "Tiéfo", "I", "L", null, null, null, null));
    out.add(new Language("tir", "Tigrinya", "I", "L", "ti", null, null, null));
    out.add(new Language("tis", "Masadiit Itneg", "I", "L", null, null, "Itneg, Masadiit", null));
    out.add(new Language("tit", "Tinigua", "I", "L", null, null, null, null));
    out.add(new Language("tiu", "Adasen", "I", "L", null, null, null, null));
    out.add(new Language("tiv", "Tiv", "I", "L", null, null, null, null));
    out.add(new Language("tiw", "Tiwi", "I", "L", null, null, null, null));
    out.add(new Language("tix", "Southern Tiwa", "I", "L", null, null, "Tiwa, Southern", null));
    out.add(new Language("tiy", "Tiruray", "I", "L", null, null, null, null));
    out.add(new Language("tiz", "Tai Hongjin", "I", "L", null, null, null, null));
    out.add(new Language("tja", "Tajuasohn", "I", "L", null, null, null, null));
    out.add(new Language("tjg", "Tunjung", "I", "L", null, null, null, null));
    out.add(new Language("tji", "Northern Tujia", "I", "L", null, null, "Tujia, Northern", null));
    out.add(new Language("tjj", "Tjungundji", "I", "L", null, null, null, null));
    out.add(new Language("tjl", "Tai Laing", "I", "L", null, null, null, null));
    out.add(new Language("tjm", "Timucua", "I", "E", null, null, null, null));
    out.add(new Language("tjn", "Tonjon", "I", "E", null, null, null, null));
    out.add(new Language("tjo", "Temacine Tamazight", "I", "L", null, null, "Tamazight, Temacine", null));
    out.add(new Language("tjp", "Tjupany", "I", "L", null, null, null, null));
    out.add(new Language("tjs", "Southern Tujia", "I", "L", null, null, "Tujia, Southern", null));
    out.add(new Language("tju", "Tjurruru", "I", "E", null, null, null, null));
    out.add(new Language("tjw", "Djabwurrung", "I", "L", null, null, null, null));
    out.add(new Language("tka", "Truká", "I", "E", null, null, null, null));
    out.add(new Language("tkb", "Buksa", "I", "L", null, null, null, null));
    out.add(new Language("tkd", "Tukudede", "I", "L", null, null, null, null));
    out.add(new Language("tke", "Takwane", "I", "L", null, null, null, null));
    out.add(new Language("tkf", "Tukumanféd", "I", "E", null, null, null, null));
    out.add(new Language("tkg", "Tesaka Malagasy", "I", "L", null, null, "Malagasy, Tesaka", null));
    out.add(new Language("tkl", "Tokelau", "I", "L", null, null, null, null));
    out.add(new Language("tkm", "Takelma", "I", "E", null, null, null, null));
    out.add(new Language("tkn", "Toku-No-Shima", "I", "L", null, null, null, null));
    out.add(new Language("tkp", "Tikopia", "I", "L", null, null, null, null));
    out.add(new Language("tkq", "Tee", "I", "L", null, null, null, null));
    out.add(new Language("tkr", "Tsakhur", "I", "L", null, null, null, null));
    out.add(new Language("tks", "Takestani", "I", "L", null, null, null, null));
    out.add(new Language("tkt", "Kathoriya Tharu", "I", "L", null, null, "Tharu, Kathoriya", null));
    out.add(new Language("tku", "Upper Necaxa Totonac", "I", "L", null, null, "Totonac, Upper Necaxa", null));
    out.add(new Language("tkv", "Mur Pano", "I", "L", null, null, null, null));
    out.add(new Language("tkw", "Teanu", "I", "L", null, null, null, null));
    out.add(new Language("tkx", "Tangko", "I", "L", null, null, null, null));
    out.add(new Language("tkz", "Takua", "I", "L", null, null, null, null));
    out.add(new Language("tla", "Southwestern Tepehuan", "I", "L", null, null, "Tepehuan, Southwestern", null));
    out.add(new Language("tlb", "Tobelo", "I", "L", null, null, null, null));
    out.add(new Language("tlc", "Yecuatla Totonac", "I", "L", null, null, "Totonac, Yecuatla", null));
    out.add(new Language("tld", "Talaud", "I", "L", null, null, null, null));
    out.add(new Language("tlf", "Telefol", "I", "L", null, null, null, null));
    out.add(new Language("tlg", "Tofanma", "I", "L", null, null, null, null));
    out.add(new Language("tlh", "Klingon", "I", "C", null, null, null, null));
    out.add(new Language("tli", "Tlingit", "I", "L", null, null, null, null));
    out.add(new Language("tlj", "Talinga-Bwisi", "I", "L", null, null, null, null));
    out.add(new Language("tlk", "Taloki", "I", "L", null, null, null, null));
    out.add(new Language("tll", "Tetela", "I", "L", null, null, null, null));
    out.add(new Language("tlm", "Tolomako", "I", "L", null, null, null, null));
    out.add(new Language("tln", "Talondo'", "I", "L", null, null, null, null));
    out.add(new Language("tlo", "Talodi", "I", "L", null, null, null, null));
    out.add(new Language("tlp", "Filomena Mata-Coahuitlán Totonac", "I", "L", null, null, "Totonac, Filomena Mata-Coahuitlán", null));
    out.add(new Language("tlq", "Tai Loi", "I", "L", null, null, null, null));
    out.add(new Language("tlr", "Talise", "I", "L", null, null, null, null));
    out.add(new Language("tls", "Tambotalo", "I", "L", null, null, null, null));
    out.add(new Language("tlt", "Sou Nama", "I", "L", null, null, null, null));
    out.add(new Language("tlu", "Tulehu", "I", "L", null, null, null, null));
    out.add(new Language("tlv", "Taliabu", "I", "L", null, null, null, null));
    out.add(new Language("tlx", "Khehek", "I", "L", null, null, null, null));
    out.add(new Language("tly", "Talysh", "I", "L", null, null, null, null));
    out.add(new Language("tma", "Tama (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("tmb", "Katbol", "I", "L", null, null, null, null));
    out.add(new Language("tmc", "Tumak", "I", "L", null, null, null, null));
    out.add(new Language("tmd", "Haruai", "I", "L", null, null, null, null));
    out.add(new Language("tme", "Tremembé", "I", "E", null, null, null, null));
    out.add(new Language("tmf", "Toba-Maskoy", "I", "L", null, null, null, null));
    out.add(new Language("tmg", "Ternateño", "I", "E", null, null, null, null));
    out.add(new Language("tmh", "Tamashek", "M", "L", null, null, null, null));
    out.add(new Language("tmi", "Tutuba", "I", "L", null, null, null, null));
    out.add(new Language("tmj", "Samarokena", "I", "L", null, null, null, null));
    out.add(new Language("tml", "Tamnim Citak", "I", "L", null, null, "Citak, Tamnim", null));
    out.add(new Language("tmm", "Tai Thanh", "I", "L", null, null, null, null));
    out.add(new Language("tmn", "Taman (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("tmo", "Temoq", "I", "L", null, null, null, null));
    out.add(new Language("tmq", "Tumleo", "I", "L", null, null, null, null));
    out.add(new Language("tmr", "Jewish Babylonian Aramaic (ca. 200-1200 CE)", "I", "E", null, null, "Aramaic, Jewish Babylonian (ca. 200-1200 CE)", null));
    out.add(new Language("tms", "Tima", "I", "L", null, null, null, null));
    out.add(new Language("tmt", "Tasmate", "I", "L", null, null, null, null));
    out.add(new Language("tmu", "Iau", "I", "L", null, null, null, null));
    out.add(new Language("tmv", "Tembo (Motembo)", "I", "L", null, null, null, null));
    out.add(new Language("tmw", "Temuan", "I", "L", null, null, null, null));
    out.add(new Language("tmy", "Tami", "I", "L", null, null, null, null));
    out.add(new Language("tmz", "Tamanaku", "I", "E", null, null, null, null));
    out.add(new Language("tna", "Tacana", "I", "L", null, null, null, null));
    out.add(new Language("tnb", "Western Tunebo", "I", "L", null, null, "Tunebo, Western", null));
    out.add(new Language("tnc", "Tanimuca-Retuarã", "I", "L", null, null, null, null));
    out.add(new Language("tnd", "Angosturas Tunebo", "I", "L", null, null, "Tunebo, Angosturas", null));
    out.add(new Language("tng", "Tobanga", "I", "L", null, null, null, null));
    out.add(new Language("tnh", "Maiani", "I", "L", null, null, null, null));
    out.add(new Language("tni", "Tandia", "I", "L", null, null, null, null));
    out.add(new Language("tnk", "Kwamera", "I", "L", null, null, null, null));
    out.add(new Language("tnl", "Lenakel", "I", "L", null, null, null, null));
    out.add(new Language("tnm", "Tabla", "I", "L", null, null, null, null));
    out.add(new Language("tnn", "North Tanna", "I", "L", null, null, "Tanna, North", null));
    out.add(new Language("tno", "Toromono", "I", "L", null, null, null, null));
    out.add(new Language("tnp", "Whitesands", "I", "L", null, null, null, null));
    out.add(new Language("tnq", "Taino", "I", "E", null, null, null, null));
    out.add(new Language("tnr", "Ménik", "I", "L", null, null, null, null));
    out.add(new Language("tns", "Tenis", "I", "L", null, null, null, null));
    out.add(new Language("tnt", "Tontemboan", "I", "L", null, null, null, null));
    out.add(new Language("tnu", "Tay Khang", "I", "L", null, null, null, null));
    out.add(new Language("tnv", "Tangchangya", "I", "L", null, null, null, null));
    out.add(new Language("tnw", "Tonsawang", "I", "L", null, null, null, null));
    out.add(new Language("tnx", "Tanema", "I", "L", null, null, null, null));
    out.add(new Language("tny", "Tongwe", "I", "L", null, null, null, null));
    out.add(new Language("tnz", "Ten'edn", "I", "L", null, null, null, null));
    out.add(new Language("tob", "Toba", "I", "L", null, null, null, null));
    out.add(new Language("toc", "Coyutla Totonac", "I", "L", null, null, "Totonac, Coyutla", null));
  }
}
