// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 5500 to 5999 of {@link Language}.
 */
final class LanguageData11 {
  private LanguageData11() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("qvn", "North Junín Quechua", "I", "L", null, null, "Quechua, North Junín", null));
    out.add(new Language("qvo", "Napo Lowland Quechua", "I", "L", null, null, "Quechua, Napo Lowland", null));
    out.add(new Language("qvp", "Pacaraos Quechua", "I", "L", null, null, "Quechua, Pacaraos", null));
    out.add(new Language("qvs", "San Martín Quechua", "I", "L", null, null, "Quechua, San Martín", null));
    out.add(new Language("qvw", "Huaylla Wanca Quechua", "I", "L", null, null, "Quechua, Huaylla Wanca", null));
    out.add(new Language("qvy", "Queyu", "I", "L", null, null, null, null));
    out.add(new Language("qvz", "Northern Pastaza Quichua", "I", "L", null, null, "Quichua, Northern Pastaza", null));
    out.add(new Language("qwa", "Corongo Ancash Quechua", "I", "L", null, null, "Quechua, Corongo Ancash", null));
    out.add(new Language("qwc", "Classical Quechua", "I", "H", null, null, "Quechua, Classical", null));
    out.add(new Language("qwh", "Huaylas Ancash Quechua", "I", "L", null, null, "Quechua, Huaylas Ancash", null));
    out.add(new Language("qwm", "Kuman (Russia)", "I", "E", null, null, null, null));
    out.add(new Language("qws", "Sihuas Ancash Quechua", "I", "L", null, null, "Quechua, Sihuas Ancash", null));
    out.add(new Language("qwt", "Kwalhioqua-Tlatskanai", "I", "E", null, null, null, null));
    out.add(new Language("qxa", "Chiquián Ancash Quechua", "I", "L", null, null, "Quechua, Chiquián Ancash", null));
    out.add(new Language("qxc", "Chincha Quechua", "I", "L", null, null, "Quechua, Chincha", null));
    out.add(new Language("qxh", "Panao Huánuco Quechua", "I", "L", null, null, "Quechua, Panao Huánuco", null));
    out.add(new Language("qxl", "Salasaca Highland Quichua", "I", "L", null, null, "Quichua, Salasaca Highland", null));
    out.add(new Language("qxn", "Northern Conchucos Ancash Quechua", "I", "L", null, null, "Quechua, Northern Conchucos Ancash", null));
    out.add(new Language("qxo", "Southern Conchucos Ancash Quechua", "I", "L", null, null, "Quechua, Southern Conchucos Ancash", null));
    out.add(new Language("qxp", "Puno Quechua", "I", "L", null, null, "Quechua, Puno", null));
    out.add(new Language("qxq", "Qashqa'i", "I", "L", null, null, null, null));
    out.add(new Language("qxr", "Cañar Highland Quichua", "I", "L", null, null, "Quichua, Cañar Highland", null));
    out.add(new Language("qxs", "Southern Qiang", "I", "L", null, null, "Qiang, Southern", null));
    out.add(new Language("qxt", "Santa Ana de Tusi Pasco Quechua", "I", "L", null, null, "Quechua, Santa Ana de Tusi Pasco", null));
    out.add(new Language("qxu", "Arequipa-La Unión Quechua", "I", "L", null, null, "Quechua, Arequipa-La Unión", null));
    out.add(new Language("qxw", "Jauja Wanca Quechua", "I", "L", null, null, "Quechua, Jauja Wanca", null));
    out.add(new Language("qya", "Quenya", "I", "C", null, null, null, null));
    out.add(new Language("qyp", "Quiripi", "I", "E", null, null, null, null));
    out.add(new Language("raa", "Dungmali", "I", "L", null, null, null, null));
    out.add(new Language("rab", "Camling", "I", "L", null, null, null, null));
    out.add(new Language("rac", "Rasawa", "I", "L", null, null, null, null));
    out.add(new Language("rad", "Rade", "I", "L", null, null, null, null));
    out.add(new Language("raf", "Western Meohang", "I", "L", null, null, "Meohang, Western", null));
    out.add(new Language("rag", "Logooli", "I", "L", null, null, null, null));
    out.add(new Language("rah", "Rabha", "I", "L", null, null, null, null));
    out.add(new Language("rai", "Ramoaaina", "I", "L", null, null, null, null));
    out.add(new Language("raj", "Rajasthani", "M", "L", null, null, null, null));
    out.add(new Language("rak", "Tulu-Bohuai", "I", "L", null, null, null, null));
    out.add(new Language("ral", "Ralte", "I", "L", null, null, null, null));
    out.add(new Language("ram", "Canela", "I", "L", null, null, null, null));
    out.add(new Language("ran", "Riantana", "I", "L", null, null, null, null));
    out.add(new Language("rao", "Rao", "I", "L", null, null, null, null));
    out.add(new Language("rap", "Rapanui", "I", "L", null, null, null, null));
    out.add(new Language("raq", "Saam", "I", "L", null, null, null, null));
    out.add(new Language("rar", "Rarotongan", "I", "L", null, null, null, null));
    out.add(new Language("ras", "Tegali", "I", "L", null, null, null, null));
    out.add(new Language("rat", "Razajerdi", "I", "L", null, null, null, null));
    out.add(new Language("rau", "Raute", "I", "L", null, null, null, null));
    out.add(new Language("rav", "Sampang", "I", "L", null, null, null, null));
    out.add(new Language("raw", "Rawang", "I", "L", null, null, null, null));
    out.add(new Language("rax", "Rang", "I", "L", null, null, null, null));
    out.add(new Language("ray", "Rapa", "I", "L", null, null, null, null));
    out.add(new Language("raz", "Rahambuu", "I", "L", null, null, null, null));
    out.add(new Language("rbb", "Rumai Palaung", "I", "L", null, null, "Palaung, Rumai", null));
    out.add(new Language("rbk", "Northern Bontok", "I", "L", null, null, "Bontok, Northern", null));
    out.add(new Language("rbl", "Miraya Bikol", "I", "L", null, null, "Bikol, Miraya", null));
    out.add(new Language("rbp", "Barababaraba", "I", "E", null, null, null, null));
    out.add(new Language("rcf", "Réunion Creole French", "I", "L", null, null, "Creole French, Réunion", null));
    out.add(new Language("rdb", "Rudbari", "I", "L", null, null, null, null));
    out.add(new Language("rea", "Rerau", "I", "L", null, null, null, null));
    out.add(new Language("reb", "Rembong", "I", "L", null, null, null, null));
    out.add(new Language("ree", "Rejang Kayan", "I", "L", null, null, "Kayan, Rejang", null));
    out.add(new Language("reg", "Kara (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("rei", "Reli", "I", "L", null, null, null, null));
    out.add(new Language("rej", "Rejang", "I", "L", null, null, null, null));
    out.add(new Language("rel", "Rendille", "I", "L", null, null, null, null));
    out.add(new Language("rem", "Remo", "I", "E", null, null, null, null));
    out.add(new Language("ren", "Rengao", "I", "L", null, null, null, null));
    out.add(new Language("rer", "Rer Bare", "I", "E", null, null, null, null));
    out.add(new Language("res", "Reshe", "I", "L", null, null, null, null));
    out.add(new Language("ret", "Retta", "I", "L", null, null, null, null));
    out.add(new Language("rey", "Reyesano", "I", "L", null, null, null, null));
    out.add(new Language("rga", "Roria", "I", "L", null, null, null, null));
    out.add(new Language("rge", "Romano-Greek", "I", "L", null, null, null, null));
    out.add(new Language("rgk", "Rangkas", "I", "E", null, null, null, null));
    out.add(new Language("rgn", "Romagnol", "I", "L", null, null, null, null));
    out.add(new Language("rgr", "Resígaro", "I", "L", null, null, null, null));
    out.add(new Language("rgs", "Southern Roglai", "I", "L", null, null, "Roglai, Southern", null));
    out.add(new Language("rgu", "Ringgou", "I", "L", null, null, null, null));
    out.add(new Language("rhg", "Rohingya", "I", "L", null, null, null, null));
    out.add(new Language("rhp", "Yahang", "I", "L", null, null, null, null));
    out.add(new Language("ria", "Riang (India)", "I", "L", null, null, null, null));
    out.add(new Language("rib", "Bribri Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rif", "Tarifit", "I", "L", null, null, null, null));
    out.add(new Language("ril", "Riang Lang", "I", "L", null, null, null, null));
    out.add(new Language("rim", "Nyaturu", "I", "L", null, null, null, null));
    out.add(new Language("rin", "Nungu", "I", "L", null, null, null, null));
    out.add(new Language("rir", "Ribun", "I", "L", null, null, null, null));
    out.add(new Language("rit", "Ritharrngu", "I", "L", null, null, null, null));
    out.add(new Language("riu", "Riung", "I", "L", null, null, null, null));
    out.add(new Language("rjg", "Rajong", "I", "L", null, null, null, null));
    out.add(new Language("rji", "Raji", "I", "L", null, null, null, null));
    out.add(new Language("rjs", "Rajbanshi", "I", "L", null, null, null, null));
    out.add(new Language("rka", "Kraol", "I", "L", null, null, null, null));
    out.add(new Language("rkb", "Rikbaktsa", "I", "L", null, null, null, null));
    out.add(new Language("rkh", "Rakahanga-Manihiki", "I", "L", null, null, null, null));
    out.add(new Language("rki", "Rakhine", "I", "L", null, null, null, null));
    out.add(new Language("rkm", "Marka", "I", "L", null, null, null, null));
    out.add(new Language("rkt", "Rangpuri", "I", "L", null, null, null, null));
    out.add(new Language("rkw", "Arakwal", "I", "E", null, null, null, null));
    out.add(new Language("rma", "Rama", "I", "L", null, null, null, null));
    out.add(new Language("rmb", "Rembarrnga", "I", "L", null, null, null, null));
    out.add(new Language("rmc", "Carpathian Romani", "I", "L", null, null, "Romani, Carpathian", null));
    out.add(new Language("rmd", "Traveller Danish", "I", "E", null, null, "Danish, Traveller", null));
    out.add(new Language("rme", "Angloromani", "I", "L", null, null, null, null));
    out.add(new Language("rmf", "Kalo Finnish Romani", "I", "L", null, null, "Romani, Kalo Finnish", null));
    out.add(new Language("rmg", "Traveller Norwegian", "I", "L", null, null, "Norwegian, Traveller", null));
    out.add(new Language("rmh", "Murkim", "I", "L", null, null, null, null));
    out.add(new Language("rmi", "Lomavren", "I", "L", null, null, null, null));
    out.add(new Language("rmk", "Romkun", "I", "L", null, null, null, null));
    out.add(new Language("rml", "Baltic Romani", "I", "L", null, null, "Romani, Baltic", null));
    out.add(new Language("rmm", "Roma", "I", "L", null, null, null, null));
    out.add(new Language("rmn", "Balkan Romani", "I", "L", null, null, "Romani, Balkan", null));
    out.add(new Language("rmo", "Sinte Romani", "I", "L", null, null, "Romani, Sinte", null));
    out.add(new Language("rmp", "Rempi", "I", "L", null, null, null, null));
    out.add(new Language("rmq", "Caló", "I", "L", null, null, null, null));
    out.add(new Language("rms", "Romanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rmt", "Domari", "I", "L", null, null, null, null));
    out.add(new Language("rmu", "Tavringer Romani", "I", "L", null, null, "Romani, Tavringer", null));
    out.add(new Language("rmv", "Romanova", "I", "C", null, null, null, null));
    out.add(new Language("rmw", "Welsh Romani", "I", "L", null, null, "Romani, Welsh", null));
    out.add(new Language("rmx", "Romam", "I", "L", null, null, null, null));
    out.add(new Language("rmy", "Vlax Romani", "I", "L", null, null, "Romani, Vlax", null));
    out.add(new Language("rmz", "Marma", "I", "L", null, null, null, null));
    out.add(new Language("rnb", "Brunca Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rnd", "Ruund", "I", "L", null, null, null, null));
    out.add(new Language("rng", "Ronga", "I", "L", null, null, null, null));
    out.add(new Language("rnl", "Ranglong", "I", "L", null, null, null, null));
    out.add(new Language("rnn", "Roon", "I", "L", null, null, null, null));
    out.add(new Language("rnp", "Rongpo", "I", "L", null, null, null, null));
    out.add(new Language("rnr", "Nari Nari", "I", "E", null, null, null, null));
    out.add(new Language("rnw", "Rungwa", "I", "L", null, null, null, null));
    out.add(new Language("rob", "Tae'", "I", "L", null, null, null, null));
    out.add(new Language("roc", "Cacgia Roglai", "I", "L", null, null, "Roglai, Cacgia", null));
    out.add(new Language("rod", "Rogo", "I", "L", null, null, null, null));
    out.add(new Language("roe", "Ronji", "I", "L", null, null, null, null));
    out.add(new Language("rof", "Rombo", "I", "L", null, null, null, null));
    out.add(new Language("rog", "Northern Roglai", "I", "L", null, null, "Roglai, Northern", null));
    out.add(new Language("roh", "Romansh", "I", "L", "rm", null, null, null));
    out.add(new Language("rol", "Romblomanon", "I", "L", null, null, null, null));
    out.add(new Language("rom", "Romany", "M", "L", null, null, null, null));
    out.add(new Language("ron", "Romanian", "I", "L", "ro", null, null, "rum"));
    out.add(new Language("roo", "Rotokas", "I", "L", null, null, null, null));
    out.add(new Language("rop", "Kriol", "I", "L", null, null, null, null));
    out.add(new Language("ror", "Rongga", "I", "L", null, null, null, null));
    out.add(new Language("rou", "Runga", "I", "L", null, null, null, null));
    out.add(new Language("row", "Dela-Oenale", "I", "L", null, null, null, null));
    out.add(new Language("rpn", "Repanbitip", "I", "L", null, null, null, null));
    out.add(new Language("rpt", "Rapting", "I", "L", null, null, null, null));
    out.add(new Language("rri", "Ririo", "I", "L", null, null, null, null));
    out.add(new Language("rrm", "Moriori", "I", "E", null, null, null, null));
    out.add(new Language("rro", "Waima", "I", "L", null, null, null, null));
    out.add(new Language("rrt", "Arritinngithigh", "I", "E", null, null, null, null));
    out.add(new Language("rsb", "Romano-Serbian", "I", "L", null, null, null, null));
    out.add(new Language("rsk", "Ruthenian", "I", "L", null, null, null, null));
    out.add(new Language("rsl", "Russian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rsm", "Miriwoong Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rsn", "Rwandan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("rsw", "Rishiwa", "I", "L", null, null, null, null));
    out.add(new Language("rtc", "Rungtu Chin", "I", "L", null, null, "Chin, Rungtu", null));
    out.add(new Language("rth", "Ratahan", "I", "L", null, null, null, null));
    out.add(new Language("rtm", "Rotuman", "I", "L", null, null, null, null));
    out.add(new Language("rts", "Yurats", "I", "E", null, null, null, null));
    out.add(new Language("rtw", "Rathawi", "I", "L", null, null, null, null));
    out.add(new Language("rub", "Gungu", "I", "L", null, null, null, null));
    out.add(new Language("ruc", "Ruuli", "I", "L", null, null, null, null));
    out.add(new Language("rue", "Rusyn", "I", "L", null, null, null, null));
    out.add(new Language("ruf", "Luguru", "I", "L", null, null, null, null));
    out.add(new Language("rug", "Roviana", "I", "L", null, null, null, null));
    out.add(new Language("ruh", "Ruga", "I", "L", null, null, null, null));
    out.add(new Language("rui", "Rufiji", "I", "L", null, null, null, null));
    out.add(new Language("ruk", "Che", "I", "L", null, null, null, null));
    out.add(new Language("run", "Rundi", "I", "L", "rn", null, null, null));
    out.add(new Language("ruo", "Istro Romanian", "I", "L", null, null, "Romanian, Istro", null));
    out.add(new Language("rup", "Macedo-Romanian", "I", "L", null, null, "Romanian, Macedo-", null));
    out.add(new Language("ruq", "Megleno Romanian", "I", "L", null, null, "Romanian, Megleno", null));
    out.add(new Language("rus", "Russian", "I", "L", "ru", null, null, null));
    out.add(new Language("rut", "Rutul", "I", "L", null, null, null, null));
    out.add(new Language("ruu", "Lanas Lobu", "I", "L", null, null, "Lobu, Lanas", null));
    out.add(new Language("ruy", "Mala (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("ruz", "Ruma", "I", "L", null, null, null, null));
    out.add(new Language("rwa", "Rawo", "I", "L", null, null, null, null));
    out.add(new Language("rwk", "Rwa", "I", "L", null, null, null, null));
    out.add(new Language("rwl", "Ruwila", "I", "L", null, null, null, null));
    out.add(new Language("rwm", "Amba (Uganda)", "I", "L", null, null, null, null));
    out.add(new Language("rwo", "Rawa", "I", "L", null, null, null, null));
    out.add(new Language("rwr", "Marwari (India)", "I", "L", null, null, null, null));
    out.add(new Language("rxd", "Ngardi", "I", "L", null, null, null, null));
    out.add(new Language("rxw", "Karuwali", "I", "E", null, null, null, null));
    out.add(new Language("ryn", "Northern Amami-Oshima", "I", "L", null, null, "Amami-Oshima, Northern", null));
    out.add(new Language("rys", "Yaeyama", "I", "L", null, null, null, null));
    out.add(new Language("ryu", "Central Okinawan", "I", "L", null, null, "Okinawan, Central", null));
    out.add(new Language("rzh", "Rāziḥī", "I", "L", null, null, null, null));
    out.add(new Language("saa", "Saba", "I", "L", null, null, null, null));
    out.add(new Language("sab", "Buglere", "I", "L", null, null, null, null));
    out.add(new Language("sac", "Meskwaki", "I", "L", null, null, null, null));
    out.add(new Language("sad", "Sandawe", "I", "L", null, null, null, null));
    out.add(new Language("sae", "Sabanê", "I", "L", null, null, null, null));
    out.add(new Language("saf", "Safaliba", "I", "L", null, null, null, null));
    out.add(new Language("sag", "Sango", "I", "L", "sg", null, null, null));
    out.add(new Language("sah", "Yakut", "I", "L", null, null, null, null));
    out.add(new Language("saj", "Sahu", "I", "L", null, null, null, null));
    out.add(new Language("sak", "Sake", "I", "L", null, null, null, null));
    out.add(new Language("sam", "Samaritan Aramaic", "I", "E", null, null, "Aramaic, Samaritan", null));
    out.add(new Language("san", "Sanskrit", "M", "H", "sa", null, null, null));
    out.add(new Language("sao", "Sause", "I", "L", null, null, null, null));
    out.add(new Language("saq", "Samburu", "I", "L", null, null, null, null));
    out.add(new Language("sar", "Saraveca", "I", "E", null, null, null, null));
    out.add(new Language("sas", "Sasak", "I", "L", null, null, null, null));
    out.add(new Language("sat", "Santali", "I", "L", null, null, null, null));
    out.add(new Language("sau", "Saleman", "I", "L", null, null, null, null));
    out.add(new Language("sav", "Saafi-Saafi", "I", "L", null, null, null, null));
    out.add(new Language("saw", "Sawi", "I", "L", null, null, null, null));
    out.add(new Language("sax", "Sa", "I", "L", null, null, null, null));
    out.add(new Language("say", "Saya", "I", "L", null, null, null, null));
    out.add(new Language("saz", "Saurashtra", "I", "L", null, null, null, null));
    out.add(new Language("sba", "Ngambay", "I", "L", null, null, null, null));
    out.add(new Language("sbb", "Simbo", "I", "L", null, null, null, null));
    out.add(new Language("sbc", "Kele (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("sbd", "Southern Samo", "I", "L", null, null, "Samo, Southern", null));
    out.add(new Language("sbe", "Saliba", "I", "L", null, null, null, null));
    out.add(new Language("sbf", "Chabu", "I", "L", null, null, null, null));
    out.add(new Language("sbg", "Seget", "I", "L", null, null, null, null));
    out.add(new Language("sbh", "Sori-Harengan", "I", "L", null, null, null, null));
    out.add(new Language("sbi", "Seti", "I", "L", null, null, null, null));
    out.add(new Language("sbj", "Surbakhal", "I", "L", null, null, null, null));
    out.add(new Language("sbk", "Safwa", "I", "L", null, null, null, null));
    out.add(new Language("sbl", "Botolan Sambal", "I", "L", null, null, "Sambal, Botolan", null));
    out.add(new Language("sbm", "Sagala", "I", "L", null, null, null, null));
    out.add(new Language("sbn", "Sindhi Bhil", "I", "L", null, null, "Bhil, Sindhi", null));
    out.add(new Language("sbo", "Sabüm", "I", "L", null, null, null, null));
    out.add(new Language("sbp", "Sangu (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("sbq", "Sileibi", "I", "L", null, null, null, null));
    out.add(new Language("sbr", "Sembakung Murut", "I", "L", null, null, null, null));
    out.add(new Language("sbs", "Subiya", "I", "L", null, null, null, null));
    out.add(new Language("sbt", "Kimki", "I", "L", null, null, null, null));
    out.add(new Language("sbu", "Stod Bhoti", "I", "L", null, null, "Bhoti, Stod", null));
    out.add(new Language("sbv", "Sabine", "I", "H", null, null, null, null));
    out.add(new Language("sbw", "Simba", "I", "L", null, null, null, null));
    out.add(new Language("sbx", "Seberuang", "I", "L", null, null, null, null));
    out.add(new Language("sby", "Soli", "I", "L", null, null, null, null));
    out.add(new Language("sbz", "Sara Kaba", "I", "L", null, null, null, null));
    out.add(new Language("scb", "Chut", "I", "L", null, null, null, null));
    out.add(new Language("sce", "Dongxiang", "I", "L", null, null, null, null));
    out.add(new Language("scf", "San Miguel Creole French", "I", "L", null, null, "Creole French, San Miguel", null));
    out.add(new Language("scg", "Sanggau", "I", "L", null, null, null, null));
    out.add(new Language("sch", "Sakachep", "I", "L", null, null, null, null));
    out.add(new Language("sci", "Sri Lankan Creole Malay", "I", "L", null, null, "Creole Malay, Sri Lankan", null));
    out.add(new Language("sck", "Sadri", "I", "L", null, null, null, null));
    out.add(new Language("scl", "Shina", "I", "L", null, null, null, null));
    out.add(new Language("scn", "Sicilian", "I", "L", null, null, null, null));
    out.add(new Language("sco", "Scots", "I", "L", null, null, null, null));
    out.add(new Language("scp", "Hyolmo", "I", "L", null, null, null, null));
    out.add(new Language("scq", "Sa'och", "I", "L", null, null, null, null));
    out.add(new Language("scs", "North Slavey", "I", "L", null, null, "Slavey, North", null));
    out.add(new Language("sct", "Southern Katang", "I", "L", null, null, "Katang, Southern", null));
    out.add(new Language("scu", "Shumcho", "I", "L", null, null, null, null));
    out.add(new Language("scv", "Sheni", "I", "L", null, null, null, null));
    out.add(new Language("scw", "Sha", "I", "L", null, null, null, null));
    out.add(new Language("scx", "Sicel", "I", "H", null, null, null, null));
    out.add(new Language("sda", "Toraja-Sa'dan", "I", "L", null, null, null, null));
    out.add(new Language("sdb", "Shabak", "I", "L", null, null, null, null));
    out.add(new Language("sdc", "Sassarese Sardinian", "I", "L", null, null, "Sardinian, Sassarese", null));
    out.add(new Language("sde", "Surubu", "I", "L", null, null, null, null));
    out.add(new Language("sdf", "Sarli", "I", "L", null, null, null, null));
    out.add(new Language("sdg", "Savi", "I", "L", null, null, null, null));
    out.add(new Language("sdh", "Southern Kurdish", "I", "L", null, null, "Kurdish, Southern", null));
    out.add(new Language("sdj", "Suundi", "I", "L", null, null, null, null));
    out.add(new Language("sdk", "Sos Kundi", "I", "L", null, null, null, null));
    out.add(new Language("sdl", "Saudi Arabian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sdn", "Gallurese Sardinian", "I", "L", null, null, "Sardinian, Gallurese", null));
    out.add(new Language("sdo", "Bukar-Sadung Bidayuh", "I", "L", null, null, "Bidayuh, Bukar-Sadung", null));
    out.add(new Language("sdp", "Sherdukpen", "I", "L", null, null, null, null));
    out.add(new Language("sdq", "Semandang", "I", "L", null, null, null, null));
    out.add(new Language("sdr", "Oraon Sadri", "I", "L", null, null, "Sadri, Oraon", null));
    out.add(new Language("sds", "Sened", "I", "E", null, null, null, null));
    out.add(new Language("sdt", "Shuadit", "I", "E", null, null, null, null));
    out.add(new Language("sdu", "Sarudu", "I", "L", null, null, null, null));
    out.add(new Language("sdx", "Sibu Melanau", "I", "L", null, null, "Melanau, Sibu", null));
    out.add(new Language("sdz", "Sallands", "I", "L", null, null, null, null));
    out.add(new Language("sea", "Semai", "I", "L", null, null, null, null));
    out.add(new Language("seb", "Shempire Senoufo", "I", "L", null, null, "Senoufo, Shempire", null));
    out.add(new Language("sec", "Sechelt", "I", "L", null, null, null, null));
    out.add(new Language("sed", "Sedang", "I", "L", null, null, null, null));
    out.add(new Language("see", "Seneca", "I", "L", null, null, null, null));
    out.add(new Language("sef", "Cebaara Senoufo", "I", "L", null, null, "Senoufo, Cebaara", null));
    out.add(new Language("seg", "Segeju", "I", "L", null, null, null, null));
    out.add(new Language("seh", "Sena", "I", "L", null, null, null, null));
    out.add(new Language("sei", "Seri", "I", "L", null, null, null, null));
    out.add(new Language("sej", "Sene", "I", "L", null, null, null, null));
    out.add(new Language("sek", "Sekani", "I", "L", null, null, null, null));
    out.add(new Language("sel", "Selkup", "I", "L", null, null, null, null));
    out.add(new Language("sen", "Nanerigé Sénoufo", "I", "L", null, null, "Sénoufo, Nanerigé", null));
    out.add(new Language("seo", "Suarmin", "I", "L", null, null, null, null));
    out.add(new Language("sep", "Sìcìté Sénoufo", "I", "L", null, null, "Sénoufo, Sìcìté", null));
    out.add(new Language("seq", "Senara Sénoufo", "I", "L", null, null, "Sénoufo, Senara", null));
    out.add(new Language("ser", "Serrano", "I", "L", null, null, null, null));
    out.add(new Language("ses", "Koyraboro Senni Songhai", "I", "L", null, null, "Songhai, Koyraboro Senni", null));
    out.add(new Language("set", "Sentani", "I", "L", null, null, null, null));
    out.add(new Language("seu", "Serui-Laut", "I", "L", null, null, null, null));
    out.add(new Language("sev", "Nyarafolo Senoufo", "I", "L", null, null, "Senoufo, Nyarafolo", null));
    out.add(new Language("sew", "Sewa Bay", "I", "L", null, null, null, null));
    out.add(new Language("sey", "Secoya", "I", "L", null, null, null, null));
    out.add(new Language("sez", "Senthang Chin", "I", "L", null, null, "Chin, Senthang", null));
    out.add(new Language("sfb", "Langue des signes de Belgique Francophone", "I", "L", null, null, null, null));
    out.add(new Language("sfe", "Eastern Subanen", "I", "L", null, null, "Subanen, Eastern", null));
    out.add(new Language("sfm", "Small Flowery Miao", "I", "L", null, null, "Miao, Small Flowery", null));
    out.add(new Language("sfs", "South African Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sfw", "Sehwi", "I", "L", null, null, null, null));
    out.add(new Language("sga", "Old Irish (to 900)", "I", "H", null, null, "Irish, Old (to 900)", null));
    out.add(new Language("sgb", "Mag-antsi Ayta", "I", "L", null, null, "Ayta, Mag-antsi", null));
    out.add(new Language("sgc", "Kipsigis", "I", "L", null, null, null, null));
    out.add(new Language("sgd", "Surigaonon", "I", "L", null, null, null, null));
    out.add(new Language("sge", "Segai", "I", "L", null, null, null, null));
    out.add(new Language("sgg", "Swiss-German Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sgh", "Shughni", "I", "L", null, null, null, null));
    out.add(new Language("sgi", "Suga", "I", "L", null, null, null, null));
    out.add(new Language("sgj", "Surgujia", "I", "L", null, null, null, null));
    out.add(new Language("sgk", "Sangkong", "I", "L", null, null, null, null));
    out.add(new Language("sgm", "Singa", "I", "E", null, null, null, null));
    out.add(new Language("sgp", "Singpho", "I", "L", null, null, null, null));
    out.add(new Language("sgr", "Sangisari", "I", "L", null, null, null, null));
    out.add(new Language("sgs", "Samogitian", "I", "L", null, null, null, null));
    out.add(new Language("sgt", "Brokpake", "I", "L", null, null, null, null));
    out.add(new Language("sgu", "Salas", "I", "L", null, null, null, null));
    out.add(new Language("sgw", "Sebat Bet Gurage", "I", "L", null, null, null, null));
    out.add(new Language("sgx", "Sierra Leone Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("sgy", "Sanglechi", "I", "L", null, null, null, null));
    out.add(new Language("sgz", "Sursurunga", "I", "L", null, null, null, null));
    out.add(new Language("sha", "Shall-Zwall", "I", "L", null, null, null, null));
    out.add(new Language("shb", "Ninam", "I", "L", null, null, null, null));
    out.add(new Language("shc", "Sonde", "I", "L", null, null, null, null));
    out.add(new Language("shd", "Kundal Shahi", "I", "L", null, null, null, null));
    out.add(new Language("she", "Sheko", "I", "L", null, null, null, null));
    out.add(new Language("shg", "Shua", "I", "L", null, null, null, null));
    out.add(new Language("shh", "Shoshoni", "I", "L", null, null, null, null));
    out.add(new Language("shi", "Tachelhit", "I", "L", null, null, null, null));
    out.add(new Language("shj", "Shatt", "I", "L", null, null, null, null));
    out.add(new Language("shk", "Shilluk", "I", "L", null, null, null, null));
    out.add(new Language("shl", "Shendu", "I", "L", null, null, null, null));
    out.add(new Language("shm", "Shahrudi", "I", "L", null, null, null, null));
    out.add(new Language("shn", "Shan", "I", "L", null, null, null, null));
    out.add(new Language("sho", "Shanga", "I", "L", null, null, null, null));
    out.add(new Language("shp", "Shipibo-Conibo", "I", "L", null, null, null, null));
    out.add(new Language("shq", "Sala", "I", "L", null, null, null, null));
    out.add(new Language("shr", "Shi", "I", "L", null, null, null, null));
    out.add(new Language("shs", "Shuswap", "I", "L", null, null, null, null));
    out.add(new Language("sht", "Shasta", "I", "E", null, null, null, null));
    out.add(new Language("shu", "Chadian Arabic", "I", "L", null, null, "Arabic, Chadian", null));
    out.add(new Language("shv", "Shehri", "I", "L", null, null, null, null));
    out.add(new Language("shw", "Shwai", "I", "L", null, null, null, null));
    out.add(new Language("shx", "She", "I", "L", null, null, null, null));
    out.add(new Language("shy", "Tachawit", "I", "L", null, null, null, null));
    out.add(new Language("shz", "Syenara Senoufo", "I", "L", null, null, "Senoufo, Syenara", null));
    out.add(new Language("sia", "Akkala Sami", "I", "E", null, null, "Sami, Akkala", null));
    out.add(new Language("sib", "Sebop", "I", "L", null, null, null, null));
    out.add(new Language("sid", "Sidamo", "I", "L", null, null, null, null));
    out.add(new Language("sie", "Simaa", "I", "L", null, null, null, null));
    out.add(new Language("sif", "Siamou", "I", "L", null, null, null, null));
    out.add(new Language("sig", "Paasaal", "I", "L", null, null, null, null));
    out.add(new Language("sih", "Zire", "I", "L", null, null, null, null));
    out.add(new Language("sii", "Shom Peng", "I", "L", null, null, null, null));
    out.add(new Language("sij", "Numbami", "I", "L", null, null, null, null));
    out.add(new Language("sik", "Sikiana", "I", "L", null, null, null, null));
    out.add(new Language("sil", "Tumulung Sisaala", "I", "L", null, null, "Sisaala, Tumulung", null));
    out.add(new Language("sim", "Mende (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("sin", "Sinhala", "I", "L", "si", null, null, null));
    out.add(new Language("sip", "Sikkimese", "I", "L", null, null, null, null));
    out.add(new Language("siq", "Sonia", "I", "L", null, null, null, null));
    out.add(new Language("sir", "Siri", "I", "L", null, null, null, null));
    out.add(new Language("sis", "Siuslaw", "I", "E", null, null, null, null));
    out.add(new Language("siu", "Sinagen", "I", "L", null, null, null, null));
    out.add(new Language("siv", "Sumariup", "I", "L", null, null, null, null));
    out.add(new Language("siw", "Siwai", "I", "L", null, null, null, null));
    out.add(new Language("six", "Sumau", "I", "L", null, null, null, null));
    out.add(new Language("siy", "Sivandi", "I", "L", null, null, null, null));
    out.add(new Language("siz", "Siwi", "I", "L", null, null, null, null));
    out.add(new Language("sja", "Epena", "I", "L", null, null, null, null));
    out.add(new Language("sjb", "Sajau Basap", "I", "L", null, null, null, null));
    out.add(new Language("sjc", "Shaojiang Chinese", "I", "L", null, null, "Chinese, Shaojiang", null));
    out.add(new Language("sjd", "Kildin Sami", "I", "L", null, null, "Sami, Kildin", null));
    out.add(new Language("sje", "Pite Sami", "I", "L", null, null, "Sami, Pite", null));
    out.add(new Language("sjg", "Assangori", "I", "L", null, null, null, null));
    out.add(new Language("sjk", "Kemi Sami", "I", "E", null, null, "Sami, Kemi", null));
    out.add(new Language("sjl", "Sajalong", "I", "L", null, null, null, null));
    out.add(new Language("sjm", "Mapun", "I", "L", null, null, null, null));
    out.add(new Language("sjn", "Sindarin", "I", "C", null, null, null, null));
    out.add(new Language("sjo", "Xibe", "I", "L", null, null, null, null));
    out.add(new Language("sjp", "Surjapuri", "I", "L", null, null, null, null));
    out.add(new Language("sjr", "Siar-Lak", "I", "L", null, null, null, null));
    out.add(new Language("sjs", "Senhaja De Srair", "I", "E", null, null, null, null));
    out.add(new Language("sjt", "Ter Sami", "I", "L", null, null, "Sami, Ter", null));
    out.add(new Language("sju", "Ume Sami", "I", "L", null, null, "Sami, Ume", null));
    out.add(new Language("sjw", "Shawnee", "I", "L", null, null, null, null));
    out.add(new Language("ska", "Skagit", "I", "L", null, null, null, null));
    out.add(new Language("skb", "Saek", "I", "L", null, null, null, null));
    out.add(new Language("skc", "Ma Manda", "I", "L", null, null, null, null));
    out.add(new Language("skd", "Southern Sierra Miwok", "I", "L", null, null, "Miwok, Southern Sierra", null));
    out.add(new Language("ske", "Seke (Vanuatu)", "I", "L", null, null, null, null));
    out.add(new Language("skf", "Sakirabiá", "I", "L", null, null, null, null));
    out.add(new Language("skg", "Sakalava Malagasy", "I", "L", null, null, "Malagasy, Sakalava", null));
    out.add(new Language("skh", "Sikule", "I", "L", null, null, null, null));
    out.add(new Language("ski", "Sika", "I", "L", null, null, null, null));
    out.add(new Language("skj", "Seke (Nepal)", "I", "L", null, null, null, null));
    out.add(new Language("skm", "Kutong", "I", "L", null, null, null, null));
    out.add(new Language("skn", "Kolibugan Subanon", "I", "L", null, null, "Subanon, Kolibugan", null));
    out.add(new Language("sko", "Seko Tengah", "I", "L", null, null, null, null));
    out.add(new Language("skp", "Sekapan", "I", "L", null, null, null, null));
    out.add(new Language("skq", "Sininkere", "I", "L", null, null, null, null));
    out.add(new Language("skr", "Saraiki", "I", "L", null, null, null, null));
    out.add(new Language("sks", "Maia", "I", "L", null, null, null, null));
    out.add(new Language("skt", "Sakata", "I", "L", null, null, null, null));
    out.add(new Language("sku", "Sakao", "I", "L", null, null, null, null));
    out.add(new Language("skv", "Skou", "I", "L", null, null, null, null));
    out.add(new Language("skw", "Skepi Creole Dutch", "I", "E", null, null, "Creole Dutch, Skepi", null));
    out.add(new Language("skx", "Seko Padang", "I", "L", null, null, null, null));
    out.add(new Language("sky", "Sikaiana", "I", "L", null, null, null, null));
    out.add(new Language("skz", "Sekar", "I", "L", null, null, null, null));
    out.add(new Language("slc", "Sáliba", "I", "L", null, null, null, null));
    out.add(new Language("sld", "Sissala", "I", "L", null, null, null, null));
    out.add(new Language("sle", "Sholaga", "I", "L", null, null, null, null));
    out.add(new Language("slf", "Swiss-Italian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("slg", "Selungai Murut", "I", "L", null, null, null, null));
    out.add(new Language("slh", "Southern Puget Sound Salish", "I", "L", null, null, "Salish, Southern Puget Sound", null));
    out.add(new Language("sli", "Lower Silesian", "I", "L", null, null, "Silesian, Lower", null));
    out.add(new Language("slj", "Salumá", "I", "L", null, null, null, null));
    out.add(new Language("slk", "Slovak", "I", "L", "sk", null, null, "slo"));
    out.add(new Language("sll", "Salt-Yui", "I", "L", null, null, null, null));
    out.add(new Language("slm", "Pangutaran Sama", "I", "L", null, null, "Sama, Pangutaran", null));
    out.add(new Language("sln", "Salinan", "I", "E", null, null, null, null));
    out.add(new Language("slp", "Lamaholot", "I", "L", null, null, null, null));
    out.add(new Language("slr", "Salar", "I", "L", null, null, null, null));
    out.add(new Language("sls", "Singapore Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("slt", "Sila", "I", "L", null, null, null, null));
    out.add(new Language("slu", "Selaru", "I", "L", null, null, null, null));
    out.add(new Language("slv", "Slovenian", "I", "L", "sl", null, null, null));
    out.add(new Language("slw", "Sialum", "I", "L", null, null, null, null));
    out.add(new Language("slx", "Salampasu", "I", "L", null, null, null, null));
    out.add(new Language("sly", "Selayar", "I", "L", null, null, null, null));
    out.add(new Language("slz", "Ma'ya", "I", "L", null, null, null, null));
    out.add(new Language("sma", "Southern Sami", "I", "L", null, null, "Sami, Southern", null));
    out.add(new Language("smb", "Simbari", "I", "L", null, null, null, null));
    out.add(new Language("smc", "Som", "I", "E", null, null, null, null));
    out.add(new Language("sme", "Northern Sami", "I", "L", "se", null, "Sami, Northern", null));
    out.add(new Language("smf", "Auwe", "I", "L", null, null, null, null));
    out.add(new Language("smg", "Simbali", "I", "L", null, null, null, null));
    out.add(new Language("smh", "Samei", "I", "L", null, null, null, null));
    out.add(new Language("smj", "Lule Sami", "I", "L", null, null, null, null));
    out.add(new Language("smk", "Bolinao", "I", "L", null, null, null, null));
    out.add(new Language("sml", "Central Sama", "I", "L", null, null, "Sama, Central", null));
    out.add(new Language("smm", "Musasa", "I", "L", null, null, null, null));
    out.add(new Language("smn", "Inari Sami", "I", "L", null, null, "Sami, Inari", null));
    out.add(new Language("smo", "Samoan", "I", "L", "sm", null, null, null));
    out.add(new Language("smp", "Samaritan", "I", "E", null, null, null, null));
    out.add(new Language("smq", "Samo", "I", "L", null, null, null, null));
    out.add(new Language("smr", "Simeulue", "I", "L", null, null, null, null));
    out.add(new Language("sms", "Skolt Sami", "I", "L", null, null, "Sami, Skolt", null));
    out.add(new Language("smt", "Simte", "I", "L", null, null, null, null));
    out.add(new Language("smu", "Somray", "I", "E", null, null, null, null));
    out.add(new Language("smv", "Samvedi", "I", "L", null, null, null, null));
    out.add(new Language("smw", "Sumbawa", "I", "L", null, null, null, null));
    out.add(new Language("smx", "Samba", "I", "L", null, null, null, null));
    out.add(new Language("smy", "Semnani", "I", "L", null, null, null, null));
    out.add(new Language("smz", "Simeku", "I", "L", null, null, null, null));
    out.add(new Language("sna", "Shona", "I", "L", "sn", null, null, null));
    out.add(new Language("snc", "Sinaugoro", "I", "L", null, null, null, null));
    out.add(new Language("snd", "Sindhi", "I", "L", "sd", null, null, null));
    out.add(new Language("sne", "Bau Bidayuh", "I", "L", null, null, "Bidayuh, Bau", null));
    out.add(new Language("snf", "Noon", "I", "L", null, null, null, null));
    out.add(new Language("sng", "Sanga (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("sni", "Sensi", "I", "E", null, null, null, null));
    out.add(new Language("snj", "Riverain Sango", "I", "L", null, null, "Sango, Riverain", null));
    out.add(new Language("snk", "Soninke", "I", "L", null, null, null, null));
    out.add(new Language("snl", "Sangil", "I", "L", null, null, null, null));
    out.add(new Language("snm", "Southern Ma'di", "I", "L", null, null, "Ma'di, Southern", null));
    out.add(new Language("snn", "Siona", "I", "L", null, null, null, null));
    out.add(new Language("sno", "Snohomish", "I", "L", null, null, null, null));
    out.add(new Language("snp", "Siane", "I", "L", null, null, null, null));
    out.add(new Language("snq", "Sangu (Gabon)", "I", "L", null, null, null, null));
    out.add(new Language("snr", "Sihan", "I", "L", null, null, null, null));
    out.add(new Language("sns", "South West Bay", "I", "L", null, null, null, null));
    out.add(new Language("snu", "Senggi", "I", "L", null, null, null, null));
    out.add(new Language("snv", "Sa'ban", "I", "L", null, null, null, null));
    out.add(new Language("snw", "Selee", "I", "L", null, null, null, null));
    out.add(new Language("snx", "Sam", "I", "L", null, null, null, null));
    out.add(new Language("sny", "Saniyo-Hiyewe", "I", "L", null, null, null, null));
    out.add(new Language("snz", "Kou", "I", "L", null, null, null, null));
    out.add(new Language("soa", "Thai Song", "I", "L", null, null, null, null));
    out.add(new Language("sob", "Sobei", "I", "L", null, null, null, null));
    out.add(new Language("soc", "So (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("sod", "Songoora", "I", "L", null, null, null, null));
    out.add(new Language("soe", "Songomeno", "I", "L", null, null, null, null));
    out.add(new Language("sog", "Sogdian", "I", "H", null, null, null, null));
    out.add(new Language("soh", "Aka", "I", "L", null, null, null, null));
    out.add(new Language("soi", "Sonha", "I", "L", null, null, null, null));
    out.add(new Language("soj", "Soi", "I", "L", null, null, null, null));
    out.add(new Language("sok", "Sokoro", "I", "L", null, null, null, null));
    out.add(new Language("sol", "Solos", "I", "L", null, null, null, null));
    out.add(new Language("som", "Somali", "I", "L", "so", null, null, null));
    out.add(new Language("soo", "Songo", "I", "L", null, null, null, null));
  }
}
