// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 1500 to 1999 of {@link Language}.
 */
final class LanguageData3 {
  private LanguageData3() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("dbm", "Duguri", "I", "L", null, null, null, null));
    out.add(new Language("dbn", "Duriankere", "I", "L", null, null, null, null));
    out.add(new Language("dbo", "Dulbu", "I", "L", null, null, null, null));
    out.add(new Language("dbp", "Duwai", "I", "L", null, null, null, null));
    out.add(new Language("dbq", "Daba", "I", "L", null, null, null, null));
    out.add(new Language("dbr", "Dabarre", "I", "L", null, null, null, null));
    out.add(new Language("dbt", "Ben Tey Dogon", "I", "L", null, null, "Dogon, Ben Tey", null));
    out.add(new Language("dbu", "Bondum Dom Dogon", "I", "L", null, null, "Dogon, Bondum Dom", null));
    out.add(new Language("dbv", "Dungu", "I", "L", null, null, null, null));
    out.add(new Language("dbw", "Bankan Tey Dogon", "I", "L", null, null, "Dogon, Bankan Tey", null));
    out.add(new Language("dby", "Dibiyaso", "I", "L", null, null, null, null));
    out.add(new Language("dcc", "Deccan", "I", "L", null, null, null, null));
    out.add(new Language("dcr", "Negerhollands", "I", "E", null, null, null, null));
    out.add(new Language("dda", "Dadi Dadi", "I", "E", null, null, null, null));
    out.add(new Language("ddd", "Dongotono", "I", "L", null, null, null, null));
    out.add(new Language("dde", "Doondo", "I", "L", null, null, null, null));
    out.add(new Language("ddg", "Fataluku", "I", "L", null, null, null, null));
    out.add(new Language("ddi", "West Goodenough", "I", "L", null, null, "Goodenough, West", null));
    out.add(new Language("ddj", "Jaru", "I", "L", null, null, null, null));
    out.add(new Language("ddn", "Dendi (Benin)", "I", "L", null, null, null, null));
    out.add(new Language("ddo", "Dido", "I", "L", null, null, null, null));
    out.add(new Language("ddr", "Dhudhuroa", "I", "E", null, null, null, null));
    out.add(new Language("dds", "Donno So Dogon", "I", "L", null, null, "Dogon, Donno So", null));
    out.add(new Language("ddw", "Dawera-Daweloor", "I", "L", null, null, null, null));
    out.add(new Language("dec", "Dagik", "I", "L", null, null, null, null));
    out.add(new Language("ded", "Dedua", "I", "L", null, null, null, null));
    out.add(new Language("dee", "Dewoin", "I", "L", null, null, null, null));
    out.add(new Language("def", "Dezfuli", "I", "L", null, null, null, null));
    out.add(new Language("deg", "Degema", "I", "L", null, null, null, null));
    out.add(new Language("deh", "Dehwari", "I", "L", null, null, null, null));
    out.add(new Language("dei", "Demisa", "I", "L", null, null, null, null));
    out.add(new Language("del", "Delaware", "M", "L", null, null, null, null));
    out.add(new Language("dem", "Dem", "I", "L", null, null, null, null));
    out.add(new Language("den", "Slave (Athapascan)", "M", "L", null, null, null, null));
    out.add(new Language("dep", "Pidgin Delaware", "I", "E", null, null, "Delaware, Pidgin", null));
    out.add(new Language("deq", "Dendi (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("der", "Deori", "I", "L", null, null, null, null));
    out.add(new Language("des", "Desano", "I", "L", null, null, null, null));
    out.add(new Language("deu", "German", "I", "L", "de", null, null, "ger"));
    out.add(new Language("dev", "Domung", "I", "L", null, null, null, null));
    out.add(new Language("dez", "Dengese", "I", "L", null, null, null, null));
    out.add(new Language("dga", "Southern Dagaare", "I", "L", null, null, "Dagaare, Southern", null));
    out.add(new Language("dgb", "Bunoge Dogon", "I", "L", null, null, "Dogon, Bunoge", null));
    out.add(new Language("dgc", "Casiguran Dumagat Agta", "I", "L", null, null, "Agta, Casiguran Dumagat", null));
    out.add(new Language("dgd", "Dagaari Dioula", "I", "L", null, null, null, null));
    out.add(new Language("dge", "Degenan", "I", "L", null, null, null, null));
    out.add(new Language("dgg", "Doga", "I", "L", null, null, null, null));
    out.add(new Language("dgh", "Dghwede", "I", "L", null, null, null, null));
    out.add(new Language("dgi", "Northern Dagara", "I", "L", null, null, "Dagara, Northern", null));
    out.add(new Language("dgk", "Dagba", "I", "L", null, null, null, null));
    out.add(new Language("dgl", "Andaandi", "I", "L", null, null, null, null));
    out.add(new Language("dgn", "Dagoman", "I", "E", null, null, null, null));
    out.add(new Language("dgo", "Dogri (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("dgr", "Tlicho", "I", "L", null, null, null, null));
    out.add(new Language("dgs", "Dogoso", "I", "L", null, null, null, null));
    out.add(new Language("dgt", "Ndra'ngith", "I", "E", null, null, null, null));
    out.add(new Language("dgw", "Daungwurrung", "I", "E", null, null, null, null));
    out.add(new Language("dgx", "Doghoro", "I", "L", null, null, null, null));
    out.add(new Language("dgz", "Daga", "I", "L", null, null, null, null));
    out.add(new Language("dhd", "Dhundari", "I", "L", null, null, null, null));
    out.add(new Language("dhg", "Dhangu-Djangu", "I", "L", null, null, null, null));
    out.add(new Language("dhi", "Dhimal", "I", "L", null, null, null, null));
    out.add(new Language("dhl", "Dhalandji", "I", "L", null, null, null, null));
    out.add(new Language("dhm", "Zemba", "I", "L", null, null, null, null));
    out.add(new Language("dhn", "Dhanki", "I", "L", null, null, null, null));
    out.add(new Language("dho", "Dhodia", "I", "L", null, null, null, null));
    out.add(new Language("dhr", "Dhargari", "I", "L", null, null, null, null));
    out.add(new Language("dhs", "Dhaiso", "I", "L", null, null, null, null));
    out.add(new Language("dhu", "Dhurga", "I", "E", null, null, null, null));
    out.add(new Language("dhv", "Dehu", "I", "L", null, null, null, null));
    out.add(new Language("dhw", "Dhanwar (Nepal)", "I", "L", null, null, null, null));
    out.add(new Language("dhx", "Dhungaloo", "I", "L", null, null, null, null));
    out.add(new Language("dia", "Dia", "I", "L", null, null, null, null));
    out.add(new Language("dib", "South Central Dinka", "I", "L", null, null, "Dinka, South Central", null));
    out.add(new Language("dic", "Lakota Dida", "I", "L", null, null, "Dida, Lakota", null));
    out.add(new Language("did", "Didinga", "I", "L", null, null, null, null));
    out.add(new Language("dif", "Dieri", "I", "E", null, null, null, null));
    out.add(new Language("dig", "Digo", "I", "L", null, null, null, null));
    out.add(new Language("dih", "Kumiai", "I", "L", null, null, null, null));
    out.add(new Language("dii", "Dimbong", "I", "L", null, null, null, null));
    out.add(new Language("dij", "Dai", "I", "L", null, null, null, null));
    out.add(new Language("dik", "Southwestern Dinka", "I", "L", null, null, "Dinka, Southwestern", null));
    out.add(new Language("dil", "Dilling", "I", "L", null, null, null, null));
    out.add(new Language("dim", "Dime", "I", "L", null, null, null, null));
    out.add(new Language("din", "Dinka", "M", "L", null, null, null, null));
    out.add(new Language("dio", "Dibo", "I", "L", null, null, null, null));
    out.add(new Language("dip", "Northeastern Dinka", "I", "L", null, null, "Dinka, Northeastern", null));
    out.add(new Language("diq", "Dimli (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("dir", "Dirim", "I", "L", null, null, null, null));
    out.add(new Language("dis", "Dimasa", "I", "L", null, null, null, null));
    out.add(new Language("diu", "Diriku", "I", "L", null, null, null, null));
    out.add(new Language("div", "Divehi", "I", "L", "dv", null, null, null));
    out.add(new Language("diw", "Northwestern Dinka", "I", "L", null, null, "Dinka, Northwestern", null));
    out.add(new Language("dix", "Dixon Reef", "I", "L", null, null, null, null));
    out.add(new Language("diy", "Diuwe", "I", "L", null, null, null, null));
    out.add(new Language("diz", "Ding", "I", "L", null, null, null, null));
    out.add(new Language("dja", "Djadjawurrung", "I", "E", null, null, null, null));
    out.add(new Language("djb", "Djinba", "I", "L", null, null, null, null));
    out.add(new Language("djc", "Dar Daju Daju", "I", "L", null, null, "Daju, Dar Daju", null));
    out.add(new Language("djd", "Djamindjung", "I", "L", null, null, null, null));
    out.add(new Language("dje", "Zarma", "I", "L", null, null, null, null));
    out.add(new Language("djf", "Djangun", "I", "E", null, null, null, null));
    out.add(new Language("dji", "Djinang", "I", "L", null, null, null, null));
    out.add(new Language("djj", "Djeebbana", "I", "L", null, null, null, null));
    out.add(new Language("djk", "Eastern Maroon Creole", "I", "L", null, null, null, null));
    out.add(new Language("djm", "Jamsay Dogon", "I", "L", null, null, "Dogon, Jamsay", null));
    out.add(new Language("djn", "Jawoyn", "I", "L", null, null, null, null));
    out.add(new Language("djo", "Jangkang", "I", "L", null, null, null, null));
    out.add(new Language("djr", "Djambarrpuyngu", "I", "L", null, null, null, null));
    out.add(new Language("dju", "Kapriman", "I", "L", null, null, null, null));
    out.add(new Language("djw", "Djawi", "I", "E", null, null, null, null));
    out.add(new Language("dka", "Dakpakha", "I", "L", null, null, null, null));
    out.add(new Language("dkg", "Kadung", "I", "L", null, null, null, null));
    out.add(new Language("dkk", "Dakka", "I", "L", null, null, null, null));
    out.add(new Language("dkr", "Kuijau", "I", "L", null, null, null, null));
    out.add(new Language("dks", "Southeastern Dinka", "I", "L", null, null, "Dinka, Southeastern", null));
    out.add(new Language("dkx", "Mazagway", "I", "L", null, null, null, null));
    out.add(new Language("dlg", "Dolgan", "I", "L", null, null, null, null));
    out.add(new Language("dlk", "Dahalik", "I", "L", null, null, null, null));
    out.add(new Language("dlm", "Dalmatian", "I", "E", null, null, null, null));
    out.add(new Language("dln", "Darlong", "I", "L", null, null, null, null));
    out.add(new Language("dma", "Duma", "I", "L", null, null, null, null));
    out.add(new Language("dmb", "Mombo Dogon", "I", "L", null, null, "Dogon, Mombo", null));
    out.add(new Language("dmc", "Gavak", "I", "L", null, null, null, null));
    out.add(new Language("dmd", "Madhi Madhi", "I", "E", null, null, null, null));
    out.add(new Language("dme", "Dugwor", "I", "L", null, null, null, null));
    out.add(new Language("dmf", "Medefaidrin", "I", "E", null, null, null, null));
    out.add(new Language("dmg", "Upper Kinabatangan", "I", "L", null, null, "Kinabatangan, Upper", null));
    out.add(new Language("dmk", "Domaaki", "I", "L", null, null, null, null));
    out.add(new Language("dml", "Dameli", "I", "L", null, null, null, null));
    out.add(new Language("dmm", "Dama", "I", "L", null, null, null, null));
    out.add(new Language("dmo", "Kemedzung", "I", "L", null, null, null, null));
    out.add(new Language("dmr", "East Damar", "I", "L", null, null, "Damar, East", null));
    out.add(new Language("dms", "Dampelas", "I", "L", null, null, null, null));
    out.add(new Language("dmu", "Dubu", "I", "L", null, null, null, null));
    out.add(new Language("dmv", "Dumpas", "I", "L", null, null, null, null));
    out.add(new Language("dmw", "Mudburra", "I", "L", null, null, null, null));
    out.add(new Language("dmx", "Dema", "I", "L", null, null, null, null));
    out.add(new Language("dmy", "Demta", "I", "L", null, null, null, null));
    out.add(new Language("dna", "Upper Grand Valley Dani", "I", "L", null, null, "Dani, Upper Grand Valley", null));
    out.add(new Language("dnd", "Daonda", "I", "L", null, null, null, null));
    out.add(new Language("dne", "Ndendeule", "I", "L", null, null, null, null));
    out.add(new Language("dng", "Dungan", "I", "L", null, null, null, null));
    out.add(new Language("dni", "Lower Grand Valley Dani", "I", "L", null, null, "Dani, Lower Grand Valley", null));
    out.add(new Language("dnj", "Dan", "I", "L", null, null, null, null));
    out.add(new Language("dnk", "Dengka", "I", "L", null, null, null, null));
    out.add(new Language("dnn", "Dzùùngoo", "I", "L", null, null, null, null));
    out.add(new Language("dno", "Ndrulo", "I", "L", null, null, null, null));
    out.add(new Language("dnr", "Danaru", "I", "L", null, null, null, null));
    out.add(new Language("dnt", "Mid Grand Valley Dani", "I", "L", null, null, "Dani, Mid Grand Valley", null));
    out.add(new Language("dnu", "Danau", "I", "L", null, null, null, null));
    out.add(new Language("dnv", "Danu", "I", "L", null, null, null, null));
    out.add(new Language("dnw", "Western Dani", "I", "L", null, null, "Dani, Western", null));
    out.add(new Language("dny", "Dení", "I", "L", null, null, null, null));
    out.add(new Language("doa", "Dom", "I", "L", null, null, null, null));
    out.add(new Language("dob", "Dobu", "I", "L", null, null, null, null));
    out.add(new Language("doc", "Northern Dong", "I", "L", null, null, "Dong, Northern", null));
    out.add(new Language("doe", "Doe", "I", "L", null, null, null, null));
    out.add(new Language("dof", "Domu", "I", "L", null, null, null, null));
    out.add(new Language("doh", "Dong", "I", "L", null, null, null, null));
    out.add(new Language("doi", "Dogri (macrolanguage)", "M", "L", null, null, null, null));
    out.add(new Language("dok", "Dondo", "I", "L", null, null, null, null));
    out.add(new Language("dol", "Doso", "I", "L", null, null, null, null));
    out.add(new Language("don", "Toura (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("doo", "Dongo", "I", "L", null, null, null, null));
    out.add(new Language("dop", "Lukpa", "I", "L", null, null, null, null));
    out.add(new Language("doq", "Dominican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("dor", "Dori'o", "I", "L", null, null, null, null));
    out.add(new Language("dos", "Dogosé", "I", "L", null, null, null, null));
    out.add(new Language("dot", "Dass", "I", "L", null, null, null, null));
    out.add(new Language("dov", "Dombe", "I", "L", null, null, null, null));
    out.add(new Language("dow", "Doyayo", "I", "L", null, null, null, null));
    out.add(new Language("dox", "Bussa", "I", "L", null, null, null, null));
    out.add(new Language("doy", "Dompo", "I", "L", null, null, null, null));
    out.add(new Language("doz", "Dorze", "I", "L", null, null, null, null));
    out.add(new Language("dpp", "Papar", "I", "L", null, null, null, null));
    out.add(new Language("drb", "Dair", "I", "L", null, null, null, null));
    out.add(new Language("drc", "Minderico", "I", "L", null, null, null, null));
    out.add(new Language("drd", "Darmiya", "I", "L", null, null, null, null));
    out.add(new Language("dre", "Dolpo", "I", "L", null, null, null, null));
    out.add(new Language("drg", "Rungus", "I", "L", null, null, null, null));
    out.add(new Language("dri", "C'Lela", "I", "L", null, null, null, null));
    out.add(new Language("drl", "Paakantyi", "I", "L", null, null, null, null));
    out.add(new Language("drn", "West Damar", "I", "L", null, null, "Damar, West", null));
    out.add(new Language("dro", "Daro-Matu Melanau", "I", "L", null, null, "Melanau, Daro-Matu", null));
    out.add(new Language("drq", "Dura", "I", "E", null, null, null, null));
    out.add(new Language("drs", "Gedeo", "I", "L", null, null, null, null));
    out.add(new Language("drt", "Drents", "I", "L", null, null, null, null));
    out.add(new Language("dru", "Rukai", "I", "L", null, null, null, null));
    out.add(new Language("dry", "Darai", "I", "L", null, null, null, null));
    out.add(new Language("dsb", "Lower Sorbian", "I", "L", null, null, "Sorbian, Lower", null));
    out.add(new Language("dse", "Dutch Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("dsh", "Daasanach", "I", "L", null, null, null, null));
    out.add(new Language("dsi", "Disa", "I", "L", null, null, null, null));
    out.add(new Language("dsk", "Dokshi", "I", "L", null, null, null, null));
    out.add(new Language("dsl", "Danish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("dsn", "Dusner", "I", "E", null, null, null, null));
    out.add(new Language("dso", "Desiya", "I", "L", null, null, null, null));
    out.add(new Language("dsq", "Tadaksahak", "I", "L", null, null, null, null));
    out.add(new Language("dsz", "Mardin Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("dta", "Daur", "I", "L", null, null, null, null));
    out.add(new Language("dtb", "Labuk-Kinabatangan Kadazan", "I", "L", null, null, "Kadazan, Labuk-Kinabatangan", null));
    out.add(new Language("dtd", "Ditidaht", "I", "L", null, null, null, null));
    out.add(new Language("dth", "Adithinngithigh", "I", "E", null, null, null, null));
    out.add(new Language("dti", "Ana Tinga Dogon", "I", "L", null, null, "Dogon, Ana Tinga", null));
    out.add(new Language("dtk", "Tene Kan Dogon", "I", "L", null, null, "Dogon, Tene Kan", null));
    out.add(new Language("dtm", "Tomo Kan Dogon", "I", "L", null, null, "Dogon, Tomo Kan", null));
    out.add(new Language("dtn", "Daatsʼíin", "I", "L", null, null, null, null));
    out.add(new Language("dto", "Tommo So Dogon", "I", "L", null, null, "Dogon, Tommo So", null));
    out.add(new Language("dtp", "Kadazan Dusun", "I", "L", null, null, "Dusun, Kadazan", null));
    out.add(new Language("dtr", "Lotud", "I", "L", null, null, null, null));
    out.add(new Language("dts", "Toro So Dogon", "I", "L", null, null, "Dogon, Toro So", null));
    out.add(new Language("dtt", "Toro Tegu Dogon", "I", "L", null, null, "Dogon, Toro Tegu", null));
    out.add(new Language("dtu", "Tebul Ure Dogon", "I", "L", null, null, "Dogon, Tebul Ure", null));
    out.add(new Language("dty", "Dotyali", "I", "L", null, null, null, null));
    out.add(new Language("dua", "Duala", "I", "L", null, null, null, null));
    out.add(new Language("dub", "Dubli", "I", "L", null, null, null, null));
    out.add(new Language("duc", "Duna", "I", "L", null, null, null, null));
    out.add(new Language("due", "Umiray Dumaget Agta", "I", "L", null, null, "Agta, Umiray Dumaget", null));
    out.add(new Language("duf", "Dumbea", "I", "L", null, null, null, null));
    out.add(new Language("dug", "Duruma", "I", "L", null, null, null, null));
    out.add(new Language("duh", "Dungra Bhil", "I", "L", null, null, null, null));
    out.add(new Language("dui", "Dumun", "I", "L", null, null, null, null));
    out.add(new Language("duk", "Uyajitaya", "I", "L", null, null, null, null));
    out.add(new Language("dul", "Alabat Island Agta", "I", "L", null, null, "Agta, Alabat Island", null));
    out.add(new Language("dum", "Middle Dutch (ca. 1050-1350)", "I", "H", null, null, "Dutch, Middle (ca. 1050-1350)", null));
    out.add(new Language("dun", "Dusun Deyah", "I", "L", null, null, null, null));
    out.add(new Language("duo", "Dupaninan Agta", "I", "L", null, null, "Agta, Dupaninan", null));
    out.add(new Language("dup", "Duano", "I", "L", null, null, null, null));
    out.add(new Language("duq", "Dusun Malang", "I", "L", null, null, null, null));
    out.add(new Language("dur", "Dii", "I", "L", null, null, null, null));
    out.add(new Language("dus", "Dumi", "I", "L", null, null, null, null));
    out.add(new Language("duu", "Drung", "I", "L", null, null, null, null));
    out.add(new Language("duv", "Duvle", "I", "L", null, null, null, null));
    out.add(new Language("duw", "Dusun Witu", "I", "L", null, null, null, null));
    out.add(new Language("dux", "Duungooma", "I", "L", null, null, null, null));
    out.add(new Language("duy", "Dicamay Agta", "I", "E", null, null, "Agta, Dicamay", null));
    out.add(new Language("duz", "Duli-Gey", "I", "E", null, null, null, null));
    out.add(new Language("dva", "Duau", "I", "L", null, null, null, null));
    out.add(new Language("dwa", "Diri", "I", "L", null, null, null, null));
    out.add(new Language("dwk", "Dawik Kui", "I", "L", null, null, "Kui, Dawik", null));
    out.add(new Language("dwr", "Dawro", "I", "L", null, null, null, null));
    out.add(new Language("dws", "Dutton World Speedwords", "I", "C", null, null, null, null));
    out.add(new Language("dwu", "Dhuwal", "I", "L", null, null, null, null));
    out.add(new Language("dww", "Dawawa", "I", "L", null, null, null, null));
    out.add(new Language("dwy", "Dhuwaya", "I", "L", null, null, null, null));
    out.add(new Language("dwz", "Dewas Rai", "I", "L", null, null, "Rai, Dewas", null));
    out.add(new Language("dya", "Dyan", "I", "L", null, null, null, null));
    out.add(new Language("dyb", "Dyaberdyaber", "I", "E", null, null, null, null));
    out.add(new Language("dyd", "Dyugun", "I", "E", null, null, null, null));
    out.add(new Language("dyg", "Villa Viciosa Agta", "I", "E", null, null, "Agta, Villa Viciosa", null));
    out.add(new Language("dyi", "Djimini Senoufo", "I", "L", null, null, "Senoufo, Djimini", null));
    out.add(new Language("dym", "Yanda Dom Dogon", "I", "L", null, null, "Dogon, Yanda Dom", null));
    out.add(new Language("dyn", "Dyangadi", "I", "L", null, null, null, null));
    out.add(new Language("dyo", "Jola-Fonyi", "I", "L", null, null, null, null));
    out.add(new Language("dyr", "Dyarim", "I", "L", null, null, null, null));
    out.add(new Language("dyu", "Dyula", "I", "L", null, null, null, null));
    out.add(new Language("dyy", "Djabugay", "I", "L", null, null, null, null));
    out.add(new Language("dza", "Tunzu", "I", "L", null, null, null, null));
    out.add(new Language("dzd", "Daza", "I", "L", null, null, null, null));
    out.add(new Language("dze", "Djiwarli", "I", "E", null, null, null, null));
    out.add(new Language("dzg", "Dazaga", "I", "L", null, null, null, null));
    out.add(new Language("dzl", "Dzalakha", "I", "L", null, null, null, null));
    out.add(new Language("dzn", "Dzando", "I", "L", null, null, null, null));
    out.add(new Language("dzo", "Dzongkha", "I", "L", "dz", null, null, null));
    out.add(new Language("eaa", "Karenggapa", "I", "E", null, null, null, null));
    out.add(new Language("ebc", "Beginci", "I", "L", null, null, null, null));
    out.add(new Language("ebg", "Ebughu", "I", "L", null, null, null, null));
    out.add(new Language("ebk", "Eastern Bontok", "I", "L", null, null, "Bontok, Eastern", null));
    out.add(new Language("ebo", "Teke-Ebo", "I", "L", null, null, null, null));
    out.add(new Language("ebr", "Ebrié", "I", "L", null, null, null, null));
    out.add(new Language("ebu", "Embu", "I", "L", null, null, null, null));
    out.add(new Language("ecr", "Eteocretan", "I", "H", null, null, null, null));
    out.add(new Language("ecs", "Ecuadorian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ecy", "Eteocypriot", "I", "H", null, null, null, null));
    out.add(new Language("eee", "E", "I", "L", null, null, null, null));
    out.add(new Language("efa", "Efai", "I", "L", null, null, null, null));
    out.add(new Language("efe", "Efe", "I", "L", null, null, null, null));
    out.add(new Language("efi", "Efik", "I", "L", null, null, null, null));
    out.add(new Language("ega", "Ega", "I", "L", null, null, null, null));
    out.add(new Language("egl", "Emilian", "I", "L", null, null, null, null));
    out.add(new Language("egm", "Benamanga", "I", "L", null, null, null, null));
    out.add(new Language("ego", "Eggon", "I", "L", null, null, null, null));
    out.add(new Language("egy", "Egyptian (Ancient)", "I", "H", null, null, null, null));
    out.add(new Language("ehs", "Miyakubo Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ehu", "Ehueun", "I", "L", null, null, null, null));
    out.add(new Language("eip", "Eipomek", "I", "L", null, null, null, null));
    out.add(new Language("eit", "Eitiep", "I", "L", null, null, null, null));
    out.add(new Language("eiv", "Askopan", "I", "L", null, null, null, null));
    out.add(new Language("eja", "Ejamat", "I", "L", null, null, null, null));
    out.add(new Language("eka", "Ekajuk", "I", "L", null, null, null, null));
    out.add(new Language("eke", "Ekit", "I", "L", null, null, null, null));
    out.add(new Language("ekg", "Ekari", "I", "L", null, null, null, null));
    out.add(new Language("eki", "Eki", "I", "L", null, null, null, null));
    out.add(new Language("ekk", "Standard Estonian", "I", "L", null, null, "Estonian, Standard", null));
    out.add(new Language("ekl", "Kol (Bangladesh)", "I", "L", null, null, null, null));
    out.add(new Language("ekm", "Elip", "I", "L", null, null, null, null));
    out.add(new Language("eko", "Koti", "I", "L", null, null, null, null));
    out.add(new Language("ekp", "Ekpeye", "I", "L", null, null, null, null));
    out.add(new Language("ekr", "Yace", "I", "L", null, null, null, null));
    out.add(new Language("eky", "Eastern Kayah", "I", "L", null, null, "Kayah, Eastern", null));
    out.add(new Language("ele", "Elepi", "I", "L", null, null, null, null));
    out.add(new Language("elh", "El Hugeirat", "I", "L", null, null, null, null));
    out.add(new Language("eli", "Nding", "I", "E", null, null, null, null));
    out.add(new Language("elk", "Elkei", "I", "L", null, null, null, null));
    out.add(new Language("ell", "Modern Greek (1453-)", "I", "L", "el", null, "Greek, Modern (1453-)", "gre"));
    out.add(new Language("elm", "Eleme", "I", "L", null, null, null, null));
    out.add(new Language("elo", "El Molo", "I", "L", null, null, null, null));
    out.add(new Language("elu", "Elu", "I", "L", null, null, null, null));
    out.add(new Language("elx", "Elamite", "I", "H", null, null, null, null));
    out.add(new Language("ema", "Emai-Iuleha-Ora", "I", "L", null, null, null, null));
    out.add(new Language("emb", "Embaloh", "I", "L", null, null, null, null));
    out.add(new Language("eme", "Emerillon", "I", "L", null, null, null, null));
    out.add(new Language("emg", "Eastern Meohang", "I", "L", null, null, "Meohang, Eastern", null));
    out.add(new Language("emi", "Mussau-Emira", "I", "L", null, null, null, null));
    out.add(new Language("emk", "Eastern Maninkakan", "I", "L", null, null, "Maninkakan, Eastern", null));
    out.add(new Language("emm", "Mamulique", "I", "E", null, null, null, null));
    out.add(new Language("emn", "Eman", "I", "L", null, null, null, null));
    out.add(new Language("emp", "Northern Emberá", "I", "L", null, null, "Emberá, Northern", null));
    out.add(new Language("emq", "Eastern Minyag", "I", "L", null, null, "Minyag, Eastern", null));
    out.add(new Language("ems", "Pacific Gulf Yupik", "I", "L", null, null, "Yupik, Pacific Gulf", null));
    out.add(new Language("emu", "Eastern Muria", "I", "L", null, null, "Muria, Eastern", null));
    out.add(new Language("emw", "Emplawas", "I", "L", null, null, null, null));
    out.add(new Language("emx", "Erromintxela", "I", "L", null, null, null, null));
    out.add(new Language("emy", "Epigraphic Mayan", "I", "H", null, null, "Mayan, Epigraphic", null));
    out.add(new Language("emz", "Mbessa", "I", "L", null, null, null, null));
    out.add(new Language("ena", "Apali", "I", "L", null, null, null, null));
    out.add(new Language("enb", "Markweeta", "I", "L", null, null, null, null));
    out.add(new Language("enc", "En", "I", "L", null, null, null, null));
    out.add(new Language("end", "Ende", "I", "L", null, null, null, null));
    out.add(new Language("enf", "Forest Enets", "I", "L", null, null, "Enets, Forest", null));
    out.add(new Language("eng", "English", "I", "L", "en", null, null, null));
    out.add(new Language("enh", "Tundra Enets", "I", "L", null, null, "Enets, Tundra", null));
    out.add(new Language("enl", "Enlhet", "I", "L", null, null, null, null));
    out.add(new Language("enm", "Middle English (1100-1500)", "I", "H", null, null, "English, Middle (1100-1500)", null));
    out.add(new Language("enn", "Engenni", "I", "L", null, null, null, null));
    out.add(new Language("eno", "Enggano", "I", "L", null, null, null, null));
    out.add(new Language("enq", "Enga", "I", "L", null, null, null, null));
    out.add(new Language("enr", "Emumu", "I", "L", null, null, null, null));
    out.add(new Language("enu", "Enu", "I", "L", null, null, null, null));
    out.add(new Language("env", "Enwan (Edo State)", "I", "L", null, null, null, null));
    out.add(new Language("enw", "Enwan (Akwa Ibom State)", "I", "L", null, null, null, null));
    out.add(new Language("enx", "Enxet", "I", "L", null, null, null, null));
    out.add(new Language("eot", "Beti (Côte d'Ivoire)", "I", "L", null, null, null, null));
    out.add(new Language("epi", "Epie", "I", "L", null, null, null, null));
    out.add(new Language("epo", "Esperanto", "I", "C", "eo", null, null, null));
    out.add(new Language("era", "Eravallan", "I", "L", null, null, null, null));
    out.add(new Language("erg", "Sie", "I", "L", null, null, null, null));
    out.add(new Language("erh", "Eruwa", "I", "L", null, null, null, null));
    out.add(new Language("eri", "Ogea", "I", "L", null, null, null, null));
    out.add(new Language("erk", "South Efate", "I", "L", null, null, "Efate, South", null));
    out.add(new Language("ero", "Horpa", "I", "L", null, null, null, null));
    out.add(new Language("err", "Erre", "I", "E", null, null, null, null));
    out.add(new Language("ers", "Ersu", "I", "L", null, null, null, null));
    out.add(new Language("ert", "Eritai", "I", "L", null, null, null, null));
    out.add(new Language("erw", "Erokwanas", "I", "L", null, null, null, null));
    out.add(new Language("ese", "Ese Ejja", "I", "L", null, null, null, null));
    out.add(new Language("esg", "Aheri Gondi", "I", "L", null, null, "Gondi, Aheri", null));
    out.add(new Language("esh", "Eshtehardi", "I", "L", null, null, null, null));
    out.add(new Language("esi", "North Alaskan Inupiatun", "I", "L", null, null, "Inupiatun, North Alaskan", null));
    out.add(new Language("esk", "Northwest Alaska Inupiatun", "I", "L", null, null, "Inupiatun, Northwest Alaska", null));
    out.add(new Language("esl", "Egypt Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("esm", "Esuma", "I", "E", null, null, null, null));
    out.add(new Language("esn", "Salvadoran Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("eso", "Estonian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("esq", "Esselen", "I", "E", null, null, null, null));
    out.add(new Language("ess", "Central Siberian Yupik", "I", "L", null, null, "Yupik, Central Siberian", null));
    out.add(new Language("est", "Estonian", "M", "L", "et", null, null, null));
    out.add(new Language("esu", "Central Yupik", "I", "L", null, null, "Yupik, Central", null));
    out.add(new Language("esy", "Eskayan", "I", "L", null, null, null, null));
    out.add(new Language("etb", "Etebi", "I", "L", null, null, null, null));
    out.add(new Language("etc", "Etchemin", "I", "E", null, null, null, null));
    out.add(new Language("eth", "Ethiopian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("etn", "Eton (Vanuatu)", "I", "L", null, null, null, null));
    out.add(new Language("eto", "Eton (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("etr", "Edolo", "I", "L", null, null, null, null));
    out.add(new Language("ets", "Yekhee", "I", "L", null, null, null, null));
    out.add(new Language("ett", "Etruscan", "I", "H", null, null, null, null));
    out.add(new Language("etu", "Ejagham", "I", "L", null, null, null, null));
    out.add(new Language("etx", "Eten", "I", "L", null, null, null, null));
    out.add(new Language("etz", "Semimi", "I", "L", null, null, null, null));
    out.add(new Language("eud", "Eudeve", "I", "E", null, null, null, null));
    out.add(new Language("eus", "Basque", "I", "L", "eu", null, null, "baq"));
    out.add(new Language("eve", "Even", "I", "L", null, null, null, null));
    out.add(new Language("evh", "Uvbie", "I", "L", null, null, null, null));
    out.add(new Language("evn", "Evenki", "I", "L", null, null, null, null));
    out.add(new Language("ewe", "Ewe", "I", "L", "ee", null, null, null));
    out.add(new Language("ewo", "Ewondo", "I", "L", null, null, null, null));
    out.add(new Language("ext", "Extremaduran", "I", "L", null, null, null, null));
    out.add(new Language("eya", "Eyak", "I", "E", null, null, null, null));
    out.add(new Language("eyo", "Keiyo", "I", "L", null, null, null, null));
    out.add(new Language("eza", "Ezaa", "I", "L", null, null, null, null));
    out.add(new Language("eze", "Uzekwe", "I", "L", null, null, null, null));
    out.add(new Language("faa", "Fasu", "I", "L", null, null, null, null));
    out.add(new Language("fab", "Fa d'Ambu", "I", "L", null, null, null, null));
    out.add(new Language("fad", "Wagi", "I", "L", null, null, null, null));
    out.add(new Language("faf", "Fagani", "I", "L", null, null, null, null));
    out.add(new Language("fag", "Finongan", "I", "L", null, null, null, null));
    out.add(new Language("fah", "Baissa Fali", "I", "L", null, null, "Fali, Baissa", null));
    out.add(new Language("fai", "Faiwol", "I", "L", null, null, null, null));
    out.add(new Language("faj", "Faita", "I", "L", null, null, null, null));
    out.add(new Language("fak", "Fang (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("fal", "South Fali", "I", "L", null, null, "Fali, South", null));
    out.add(new Language("fam", "Fam", "I", "L", null, null, null, null));
    out.add(new Language("fan", "Fang (Equatorial Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("fao", "Faroese", "I", "L", "fo", null, null, null));
    out.add(new Language("fap", "Paloor", "I", "L", null, null, null, null));
    out.add(new Language("far", "Fataleka", "I", "L", null, null, null, null));
    out.add(new Language("fas", "Persian", "M", "L", "fa", null, null, "per"));
    out.add(new Language("fat", "Fanti", "I", "L", null, null, null, null));
    out.add(new Language("fau", "Fayu", "I", "L", null, null, null, null));
    out.add(new Language("fax", "Fala", "I", "L", null, null, null, null));
    out.add(new Language("fay", "Southwestern Fars", "I", "L", null, null, "Fars, Southwestern", null));
    out.add(new Language("faz", "Northwestern Fars", "I", "L", null, null, "Fars, Northwestern", null));
    out.add(new Language("fbl", "West Albay Bikol", "I", "L", null, null, "Bikol, West Albay", null));
    out.add(new Language("fcs", "Quebec Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("fer", "Feroge", "I", "L", null, null, null, null));
    out.add(new Language("ffi", "Foia Foia", "I", "L", null, null, null, null));
    out.add(new Language("ffm", "Maasina Fulfulde", "I", "L", null, null, "Fulfulde, Maasina", null));
    out.add(new Language("fgr", "Fongoro", "I", "L", null, null, null, null));
    out.add(new Language("fia", "Nobiin", "I", "L", null, null, null, null));
    out.add(new Language("fie", "Fyer", "I", "L", null, null, null, null));
    out.add(new Language("fif", "Faifi", "I", "L", null, null, null, null));
    out.add(new Language("fij", "Fijian", "I", "L", "fj", null, null, null));
    out.add(new Language("fil", "Filipino", "I", "L", null, null, null, null));
    out.add(new Language("fin", "Finnish", "I", "L", "fi", null, null, null));
    out.add(new Language("fip", "Fipa", "I", "L", null, null, null, null));
    out.add(new Language("fir", "Firan", "I", "L", null, null, null, null));
    out.add(new Language("fit", "Tornedalen Finnish", "I", "L", null, null, "Finnish, Tornedalen", null));
    out.add(new Language("fiw", "Fiwaga", "I", "L", null, null, null, null));
    out.add(new Language("fkk", "Kirya-Konzəl", "I", "L", null, null, null, null));
    out.add(new Language("fkv", "Kven Finnish", "I", "L", null, null, "Finnish, Kven", null));
    out.add(new Language("fla", "Kalispel-Pend d'Oreille", "I", "L", null, null, null, null));
    out.add(new Language("flh", "Foau", "I", "L", null, null, null, null));
    out.add(new Language("fli", "Fali", "I", "L", null, null, null, null));
    out.add(new Language("fll", "North Fali", "I", "L", null, null, "Fali, North", null));
    out.add(new Language("fln", "Flinders Island", "I", "E", null, null, null, null));
    out.add(new Language("flr", "Fuliiru", "I", "L", null, null, null, null));
    out.add(new Language("fly", "Flaaitaal", "I", "L", null, null, null, null));
    out.add(new Language("fmp", "Fe'fe'", "I", "L", null, null, null, null));
    out.add(new Language("fmu", "Far Western Muria", "I", "L", null, null, "Muria, Far Western", null));
    out.add(new Language("fnb", "Fanbak", "I", "L", null, null, null, null));
    out.add(new Language("fng", "Fanagalo", "I", "L", null, null, null, null));
    out.add(new Language("fni", "Fania", "I", "L", null, null, null, null));
    out.add(new Language("fod", "Foodo", "I", "L", null, null, null, null));
    out.add(new Language("foi", "Foi", "I", "L", null, null, null, null));
    out.add(new Language("fom", "Foma", "I", "L", null, null, null, null));
    out.add(new Language("fon", "Fon", "I", "L", null, null, null, null));
    out.add(new Language("for", "Fore", "I", "L", null, null, null, null));
    out.add(new Language("fos", "Siraya", "I", "E", null, null, null, null));
    out.add(new Language("fpe", "Fernando Po Creole English", "I", "L", null, null, "Creole English, Fernando Po", null));
    out.add(new Language("fqs", "Fas", "I", "L", null, null, null, null));
    out.add(new Language("fra", "French", "I", "L", "fr", null, null, "fre"));
    out.add(new Language("frc", "Cajun French", "I", "L", null, null, "French, Cajun", null));
    out.add(new Language("frd", "Fordata", "I", "L", null, null, null, null));
    out.add(new Language("frk", "Frankish", "I", "H", null, null, null, null));
    out.add(new Language("frm", "Middle French (ca. 1400-1600)", "I", "H", null, null, "French, Middle (ca. 1400-1600)", null));
    out.add(new Language("fro", "Old French (842-ca. 1400)", "I", "H", null, null, "French, Old (842-ca. 1400)", null));
    out.add(new Language("frp", "Arpitan", "I", "L", null, null, null, null));
    out.add(new Language("frq", "Forak", "I", "L", null, null, null, null));
    out.add(new Language("frr", "Northern Frisian", "I", "L", null, null, "Frisian, Northern", null));
    out.add(new Language("frs", "Eastern Frisian", "I", "L", null, null, "Frisian, Eastern", null));
    out.add(new Language("frt", "Fortsenal", "I", "L", null, null, null, null));
    out.add(new Language("fry", "Western Frisian", "I", "L", "fy", null, "Frisian, Western", null));
    out.add(new Language("fse", "Finnish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("fsl", "French Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("fss", "Finland-Swedish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("fub", "Adamawa Fulfulde", "I", "L", null, null, "Fulfulde, Adamawa", null));
    out.add(new Language("fuc", "Pulaar", "I", "L", null, null, null, null));
    out.add(new Language("fud", "East Futuna", "I", "L", null, null, "Futuna, East", null));
    out.add(new Language("fue", "Borgu Fulfulde", "I", "L", null, null, "Fulfulde, Borgu", null));
    out.add(new Language("fuf", "Pular", "I", "L", null, null, null, null));
    out.add(new Language("fuh", "Western Niger Fulfulde", "I", "L", null, null, "Fulfulde, Western Niger", null));
    out.add(new Language("fui", "Bagirmi Fulfulde", "I", "L", null, null, "Fulfulde, Bagirmi", null));
    out.add(new Language("fuj", "Ko", "I", "L", null, null, null, null));
    out.add(new Language("ful", "Fulah", "M", "L", "ff", null, null, null));
    out.add(new Language("fum", "Fum", "I", "L", null, null, null, null));
    out.add(new Language("fun", "Fulniô", "I", "L", null, null, null, null));
    out.add(new Language("fuq", "Central-Eastern Niger Fulfulde", "I", "L", null, null, "Fulfulde, Central-Eastern Niger", null));
    out.add(new Language("fur", "Friulian", "I", "L", null, null, null, null));
    out.add(new Language("fut", "Futuna-Aniwa", "I", "L", null, null, null, null));
    out.add(new Language("fuu", "Furu", "I", "L", null, null, null, null));
    out.add(new Language("fuv", "Nigerian Fulfulde", "I", "L", null, null, "Fulfulde, Nigerian", null));
    out.add(new Language("fuy", "Fuyug", "I", "L", null, null, null, null));
    out.add(new Language("fvr", "Fur", "I", "L", null, null, null, null));
    out.add(new Language("fwa", "Fwâi", "I", "L", null, null, null, null));
    out.add(new Language("fwe", "Fwe", "I", "L", null, null, null, null));
    out.add(new Language("gaa", "Ga", "I", "L", null, null, null, null));
    out.add(new Language("gab", "Gabri", "I", "L", null, null, null, null));
    out.add(new Language("gac", "Mixed Great Andamanese", "I", "L", null, null, "Great Andamanese, Mixed", null));
    out.add(new Language("gad", "Gaddang", "I", "L", null, null, null, null));
    out.add(new Language("gae", "Guarequena", "I", "L", null, null, null, null));
    out.add(new Language("gaf", "Gende", "I", "L", null, null, null, null));
    out.add(new Language("gag", "Gagauz", "I", "L", null, null, null, null));
    out.add(new Language("gah", "Alekano", "I", "L", null, null, null, null));
    out.add(new Language("gai", "Borei", "I", "L", null, null, null, null));
    out.add(new Language("gaj", "Gadsup", "I", "L", null, null, null, null));
    out.add(new Language("gak", "Gamkonora", "I", "L", null, null, null, null));
    out.add(new Language("gal", "Galolen", "I", "L", null, null, null, null));
    out.add(new Language("gam", "Kandawo", "I", "L", null, null, null, null));
  }
}
