// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 2500 to 2999 of {@link Language}.
 */
final class LanguageData5 {
  private LanguageData5() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("hup", "Hupa", "I", "L", null, null, null, null));
    out.add(new Language("huq", "Tsat", "I", "L", null, null, null, null));
    out.add(new Language("hur", "Halkomelem", "I", "L", null, null, null, null));
    out.add(new Language("hus", "Huastec", "I", "L", null, null, null, null));
    out.add(new Language("hut", "Humla", "I", "L", null, null, null, null));
    out.add(new Language("huu", "Murui Huitoto", "I", "L", null, null, "Huitoto, Murui", null));
    out.add(new Language("huv", "San Mateo Del Mar Huave", "I", "L", null, null, "Huave, San Mateo Del Mar", null));
    out.add(new Language("huw", "Hukumina", "I", "E", null, null, null, null));
    out.add(new Language("hux", "Nüpode Huitoto", "I", "L", null, null, "Huitoto, Nüpode", null));
    out.add(new Language("huy", "Hulaulá", "I", "L", null, null, null, null));
    out.add(new Language("huz", "Hunzib", "I", "L", null, null, null, null));
    out.add(new Language("hvc", "Haitian Vodoun Culture Language", "I", "L", null, null, null, null));
    out.add(new Language("hve", "San Dionisio Del Mar Huave", "I", "L", null, null, "Huave, San Dionisio Del Mar", null));
    out.add(new Language("hvk", "Haveke", "I", "L", null, null, null, null));
    out.add(new Language("hvn", "Sabu", "I", "L", null, null, null, null));
    out.add(new Language("hvv", "Santa María Del Mar Huave", "I", "L", null, null, "Huave, Santa María Del Mar", null));
    out.add(new Language("hwa", "Wané", "I", "L", null, null, null, null));
    out.add(new Language("hwc", "Hawai'i Creole English", "I", "L", null, null, "Creole English, Hawai'i", null));
    out.add(new Language("hwo", "Hwana", "I", "L", null, null, null, null));
    out.add(new Language("hya", "Hya", "I", "L", null, null, null, null));
    out.add(new Language("hye", "Armenian", "I", "L", "hy", null, null, "arm"));
    out.add(new Language("hyw", "Western Armenian", "I", "L", null, null, "Armenian, Western", null));
    out.add(new Language("iai", "Iaai", "I", "L", null, null, null, null));
    out.add(new Language("ian", "Iatmul", "I", "L", null, null, null, null));
    out.add(new Language("iar", "Purari", "I", "L", null, null, null, null));
    out.add(new Language("iba", "Iban", "I", "L", null, null, null, null));
    out.add(new Language("ibb", "Ibibio", "I", "L", null, null, null, null));
    out.add(new Language("ibd", "Iwaidja", "I", "L", null, null, null, null));
    out.add(new Language("ibe", "Akpes", "I", "L", null, null, null, null));
    out.add(new Language("ibg", "Ibanag", "I", "L", null, null, null, null));
    out.add(new Language("ibh", "Bih", "I", "L", null, null, null, null));
    out.add(new Language("ibl", "Ibaloi", "I", "L", null, null, null, null));
    out.add(new Language("ibm", "Agoi", "I", "L", null, null, null, null));
    out.add(new Language("ibn", "Ibino", "I", "L", null, null, null, null));
    out.add(new Language("ibo", "Igbo", "I", "L", "ig", null, null, null));
    out.add(new Language("ibr", "Ibuoro", "I", "L", null, null, null, null));
    out.add(new Language("ibu", "Ibu", "I", "L", null, null, null, null));
    out.add(new Language("iby", "Ibani", "I", "L", null, null, null, null));
    out.add(new Language("ica", "Ede Ica", "I", "L", null, null, null, null));
    out.add(new Language("ich", "Etkywan", "I", "L", null, null, null, null));
    out.add(new Language("icl", "Icelandic Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("icr", "Islander Creole English", "I", "L", null, null, "Creole English, Islander", null));
    out.add(new Language("ida", "Idakho-Isukha-Tiriki", "I", "L", null, null, null, null));
    out.add(new Language("idb", "Indo-Portuguese", "I", "L", null, null, null, null));
    out.add(new Language("idc", "Idon", "I", "L", null, null, null, null));
    out.add(new Language("idd", "Ede Idaca", "I", "L", null, null, null, null));
    out.add(new Language("ide", "Idere", "I", "L", null, null, null, null));
    out.add(new Language("idi", "Idi", "I", "L", null, null, null, null));
    out.add(new Language("ido", "Ido", "I", "C", "io", null, null, null));
    out.add(new Language("idr", "Indri", "I", "L", null, null, null, null));
    out.add(new Language("ids", "Idesa", "I", "L", null, null, null, null));
    out.add(new Language("idt", "Idaté", "I", "L", null, null, null, null));
    out.add(new Language("idu", "Idoma", "I", "L", null, null, null, null));
    out.add(new Language("ifa", "Amganad Ifugao", "I", "L", null, null, "Ifugao, Amganad", null));
    out.add(new Language("ifb", "Batad Ifugao", "I", "L", null, null, "Ifugao, Batad", null));
    out.add(new Language("ife", "Ifè", "I", "L", null, null, null, null));
    out.add(new Language("iff", "Ifo", "I", "E", null, null, null, null));
    out.add(new Language("ifk", "Tuwali Ifugao", "I", "L", null, null, "Ifugao, Tuwali", null));
    out.add(new Language("ifm", "Teke-Fuumu", "I", "L", null, null, null, null));
    out.add(new Language("ifu", "Mayoyao Ifugao", "I", "L", null, null, "Ifugao, Mayoyao", null));
    out.add(new Language("ify", "Keley-I Kallahan", "I", "L", null, null, "Kallahan, Keley-I", null));
    out.add(new Language("igb", "Ebira", "I", "L", null, null, null, null));
    out.add(new Language("ige", "Igede", "I", "L", null, null, null, null));
    out.add(new Language("igg", "Igana", "I", "L", null, null, null, null));
    out.add(new Language("igl", "Igala", "I", "L", null, null, null, null));
    out.add(new Language("igm", "Kanggape", "I", "L", null, null, null, null));
    out.add(new Language("ign", "Ignaciano", "I", "L", null, null, null, null));
    out.add(new Language("igo", "Isebe", "I", "L", null, null, null, null));
    out.add(new Language("igs", "Interglossa", "I", "C", null, null, null, null));
    out.add(new Language("igw", "Igwe", "I", "L", null, null, null, null));
    out.add(new Language("ihb", "Iha Based Pidgin", "I", "L", null, null, null, null));
    out.add(new Language("ihi", "Ihievbe", "I", "L", null, null, null, null));
    out.add(new Language("ihp", "Iha", "I", "L", null, null, null, null));
    out.add(new Language("ihw", "Bidhawal", "I", "E", null, null, null, null));
    out.add(new Language("iii", "Sichuan Yi", "I", "L", "ii", null, "Yi, Sichuan", null));
    out.add(new Language("iin", "Thiin", "I", "E", null, null, null, null));
    out.add(new Language("ijc", "Izon", "I", "L", null, null, null, null));
    out.add(new Language("ije", "Biseni", "I", "L", null, null, null, null));
    out.add(new Language("ijj", "Ede Ije", "I", "L", null, null, null, null));
    out.add(new Language("ijn", "Kalabari", "I", "L", null, null, null, null));
    out.add(new Language("ijs", "Southeast Ijo", "I", "L", null, null, "Ijo, Southeast", null));
    out.add(new Language("ike", "Eastern Canadian Inuktitut", "I", "L", null, null, "Inuktitut, Eastern Canadian", null));
    out.add(new Language("ikh", "Ikhin-Arokho", "I", "L", null, null, null, null));
    out.add(new Language("iki", "Iko", "I", "L", null, null, null, null));
    out.add(new Language("ikk", "Ika", "I", "L", null, null, null, null));
    out.add(new Language("ikl", "Ikulu", "I", "L", null, null, null, null));
    out.add(new Language("iko", "Olulumo-Ikom", "I", "L", null, null, null, null));
    out.add(new Language("ikp", "Ikpeshi", "I", "L", null, null, null, null));
    out.add(new Language("ikr", "Ikaranggal", "I", "E", null, null, null, null));
    out.add(new Language("iks", "Inuit Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ikt", "Inuinnaqtun", "I", "L", null, null, null, null));
    out.add(new Language("iku", "Inuktitut", "M", "L", "iu", null, null, null));
    out.add(new Language("ikv", "Iku-Gora-Ankwa", "I", "L", null, null, null, null));
    out.add(new Language("ikw", "Ikwere", "I", "L", null, null, null, null));
    out.add(new Language("ikx", "Ik", "I", "L", null, null, null, null));
    out.add(new Language("ikz", "Ikizu", "I", "L", null, null, null, null));
    out.add(new Language("ila", "Ile Ape", "I", "L", null, null, null, null));
    out.add(new Language("ilb", "Ila", "I", "L", null, null, null, null));
    out.add(new Language("ile", "Interlingue", "I", "C", "ie", null, null, null));
    out.add(new Language("ilg", "Garig-Ilgar", "I", "E", null, null, null, null));
    out.add(new Language("ili", "Ili Turki", "I", "L", null, null, null, null));
    out.add(new Language("ilk", "Ilongot", "I", "L", null, null, null, null));
    out.add(new Language("ilm", "Iranun (Malaysia)", "I", "L", null, null, null, null));
    out.add(new Language("ilo", "Iloko", "I", "L", null, null, null, null));
    out.add(new Language("ilp", "Iranun (Philippines)", "I", "L", null, null, null, null));
    out.add(new Language("ils", "International Sign", "I", "L", null, null, null, null));
    out.add(new Language("ilu", "Ili'uun", "I", "L", null, null, null, null));
    out.add(new Language("ilv", "Ilue", "I", "L", null, null, null, null));
    out.add(new Language("ima", "Mala Malasar", "I", "L", null, null, "Malasar, Mala", null));
    out.add(new Language("imi", "Anamgura", "I", "L", null, null, null, null));
    out.add(new Language("iml", "Miluk", "I", "E", null, null, null, null));
    out.add(new Language("imn", "Imonda", "I", "L", null, null, null, null));
    out.add(new Language("imo", "Imbongu", "I", "L", null, null, null, null));
    out.add(new Language("imr", "Imroing", "I", "L", null, null, null, null));
    out.add(new Language("ims", "Marsian", "I", "H", null, null, null, null));
    out.add(new Language("imt", "Imotong", "I", "L", null, null, null, null));
    out.add(new Language("imy", "Milyan", "I", "H", null, null, null, null));
    out.add(new Language("ina", "Interlingua (International Auxiliary Language Association)", "I", "C", "ia", null, null, null));
    out.add(new Language("inb", "Inga", "I", "L", null, null, null, null));
    out.add(new Language("ind", "Indonesian", "I", "L", "id", null, null, null));
    out.add(new Language("ing", "Degexit'an", "I", "L", null, null, null, null));
    out.add(new Language("inh", "Ingush", "I", "L", null, null, null, null));
    out.add(new Language("inj", "Jungle Inga", "I", "L", null, null, "Inga, Jungle", null));
    out.add(new Language("inl", "Indonesian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("inm", "Minaean", "I", "H", null, null, null, null));
    out.add(new Language("inn", "Isinai", "I", "L", null, null, null, null));
    out.add(new Language("ino", "Inoke-Yate", "I", "L", null, null, null, null));
    out.add(new Language("inp", "Iñapari", "I", "L", null, null, null, null));
    out.add(new Language("ins", "Indian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("int", "Intha", "I", "L", null, null, null, null));
    out.add(new Language("inz", "Ineseño", "I", "E", null, null, null, null));
    out.add(new Language("ior", "Inor", "I", "L", null, null, null, null));
    out.add(new Language("iou", "Tuma-Irumu", "I", "L", null, null, null, null));
    out.add(new Language("iow", "Iowa-Oto", "I", "E", null, null, null, null));
    out.add(new Language("ipi", "Ipili", "I", "L", null, null, null, null));
    out.add(new Language("ipk", "Inupiaq", "M", "L", "ik", null, null, null));
    out.add(new Language("ipo", "Ipiko", "I", "L", null, null, null, null));
    out.add(new Language("iqu", "Iquito", "I", "L", null, null, null, null));
    out.add(new Language("iqw", "Ikwo", "I", "L", null, null, null, null));
    out.add(new Language("ire", "Iresim", "I", "L", null, null, null, null));
    out.add(new Language("irh", "Irarutu", "I", "L", null, null, null, null));
    out.add(new Language("iri", "Rigwe", "I", "L", null, null, null, null));
    out.add(new Language("irk", "Iraqw", "I", "L", null, null, null, null));
    out.add(new Language("irn", "Irántxe", "I", "L", null, null, null, null));
    out.add(new Language("irr", "Ir", "I", "L", null, null, null, null));
    out.add(new Language("iru", "Irula", "I", "L", null, null, null, null));
    out.add(new Language("irx", "Kamberau", "I", "L", null, null, null, null));
    out.add(new Language("iry", "Iraya", "I", "L", null, null, null, null));
    out.add(new Language("isa", "Isabi", "I", "L", null, null, null, null));
    out.add(new Language("isc", "Isconahua", "I", "L", null, null, null, null));
    out.add(new Language("isd", "Isnag", "I", "L", null, null, null, null));
    out.add(new Language("ise", "Italian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("isg", "Irish Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ish", "Esan", "I", "L", null, null, null, null));
    out.add(new Language("isi", "Nkem-Nkum", "I", "L", null, null, null, null));
    out.add(new Language("isk", "Ishkashimi", "I", "L", null, null, null, null));
    out.add(new Language("isl", "Icelandic", "I", "L", "is", null, null, "ice"));
    out.add(new Language("ism", "Masimasi", "I", "L", null, null, null, null));
    out.add(new Language("isn", "Isanzu", "I", "L", null, null, null, null));
    out.add(new Language("iso", "Isoko", "I", "L", null, null, null, null));
    out.add(new Language("isr", "Israeli Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ist", "Istriot", "I", "L", null, null, null, null));
    out.add(new Language("isu", "Isu (Menchum Division)", "I", "L", null, null, null, null));
    out.add(new Language("isv", "Interslavic", "I", "C", null, null, null, null));
    out.add(new Language("ita", "Italian", "I", "L", "it", null, null, null));
    out.add(new Language("itb", "Binongan Itneg", "I", "L", null, null, "Itneg, Binongan", null));
    out.add(new Language("itd", "Southern Tidung", "I", "L", null, null, "Tidung, Southern", null));
    out.add(new Language("ite", "Itene", "I", "E", null, null, null, null));
    out.add(new Language("iti", "Inlaod Itneg", "I", "L", null, null, "Itneg, Inlaod", null));
    out.add(new Language("itk", "Judeo-Italian", "I", "L", null, null, null, null));
    out.add(new Language("itl", "Itelmen", "I", "L", null, null, null, null));
    out.add(new Language("itm", "Itu Mbon Uzo", "I", "L", null, null, null, null));
    out.add(new Language("ito", "Itonama", "I", "L", null, null, null, null));
    out.add(new Language("itr", "Iteri", "I", "L", null, null, null, null));
    out.add(new Language("its", "Isekiri", "I", "L", null, null, null, null));
    out.add(new Language("itt", "Maeng Itneg", "I", "L", null, null, "Itneg, Maeng", null));
    out.add(new Language("itv", "Itawit", "I", "L", null, null, null, null));
    out.add(new Language("itw", "Ito", "I", "L", null, null, null, null));
    out.add(new Language("itx", "Itik", "I", "L", null, null, null, null));
    out.add(new Language("ity", "Moyadan Itneg", "I", "L", null, null, "Itneg, Moyadan", null));
    out.add(new Language("itz", "Itzá", "I", "L", null, null, null, null));
    out.add(new Language("ium", "Iu Mien", "I", "L", null, null, "Mien, Iu", null));
    out.add(new Language("ivb", "Ibatan", "I", "L", null, null, null, null));
    out.add(new Language("ivv", "Ivatan", "I", "L", null, null, null, null));
    out.add(new Language("iwk", "I-Wak", "I", "L", null, null, null, null));
    out.add(new Language("iwm", "Iwam", "I", "L", null, null, null, null));
    out.add(new Language("iwo", "Iwur", "I", "L", null, null, null, null));
    out.add(new Language("iws", "Sepik Iwam", "I", "L", null, null, "Iwam, Sepik", null));
    out.add(new Language("ixc", "Ixcatec", "I", "L", null, null, null, null));
    out.add(new Language("ixl", "Ixil", "I", "L", null, null, null, null));
    out.add(new Language("iya", "Iyayu", "I", "L", null, null, null, null));
    out.add(new Language("iyo", "Mesaka", "I", "L", null, null, null, null));
    out.add(new Language("iyx", "Yaka (Congo)", "I", "L", null, null, null, null));
    out.add(new Language("izh", "Ingrian", "I", "L", null, null, null, null));
    out.add(new Language("izm", "Kizamani", "I", "L", null, null, null, null));
    out.add(new Language("izr", "Izere", "I", "L", null, null, null, null));
    out.add(new Language("izz", "Izii", "I", "L", null, null, null, null));
    out.add(new Language("jaa", "Jamamadí", "I", "L", null, null, null, null));
    out.add(new Language("jab", "Hyam", "I", "L", null, null, null, null));
    out.add(new Language("jac", "Popti'", "I", "L", null, null, null, null));
    out.add(new Language("jad", "Jahanka", "I", "L", null, null, null, null));
    out.add(new Language("jae", "Yabem", "I", "L", null, null, null, null));
    out.add(new Language("jaf", "Jara", "I", "L", null, null, null, null));
    out.add(new Language("jah", "Jah Hut", "I", "L", null, null, null, null));
    out.add(new Language("jaj", "Zazao", "I", "L", null, null, null, null));
    out.add(new Language("jak", "Jakun", "I", "L", null, null, null, null));
    out.add(new Language("jal", "Yalahatan", "I", "L", null, null, null, null));
    out.add(new Language("jam", "Jamaican Creole English", "I", "L", null, null, "Creole English, Jamaican", null));
    out.add(new Language("jan", "Jandai", "I", "E", null, null, null, null));
    out.add(new Language("jao", "Yanyuwa", "I", "L", null, null, null, null));
    out.add(new Language("jaq", "Yaqay", "I", "L", null, null, null, null));
    out.add(new Language("jas", "New Caledonian Javanese", "I", "L", null, null, "Javanese, New Caledonian", null));
    out.add(new Language("jat", "Jakati", "I", "L", null, null, null, null));
    out.add(new Language("jau", "Yaur", "I", "L", null, null, null, null));
    out.add(new Language("jav", "Javanese", "I", "L", "jv", null, null, null));
    out.add(new Language("jax", "Jambi Malay", "I", "L", null, null, "Malay, Jambi", null));
    out.add(new Language("jay", "Yan-nhangu", "I", "L", null, null, null, null));
    out.add(new Language("jaz", "Jawe", "I", "L", null, null, null, null));
    out.add(new Language("jbe", "Judeo-Berber", "I", "L", null, null, null, null));
    out.add(new Language("jbi", "Badjiri", "I", "E", null, null, null, null));
    out.add(new Language("jbj", "Arandai", "I", "L", null, null, null, null));
    out.add(new Language("jbk", "Barikewa", "I", "L", null, null, null, null));
    out.add(new Language("jbm", "Bijim", "I", "L", null, null, null, null));
    out.add(new Language("jbn", "Nafusi", "I", "L", null, null, null, null));
    out.add(new Language("jbo", "Lojban", "I", "C", null, null, null, null));
    out.add(new Language("jbr", "Jofotek-Bromnya", "I", "L", null, null, null, null));
    out.add(new Language("jbt", "Jabutí", "I", "L", null, null, null, null));
    out.add(new Language("jbu", "Jukun Takum", "I", "L", null, null, null, null));
    out.add(new Language("jbw", "Yawijibaya", "I", "E", null, null, null, null));
    out.add(new Language("jcs", "Jamaican Country Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jct", "Krymchak", "I", "L", null, null, null, null));
    out.add(new Language("jda", "Jad", "I", "L", null, null, null, null));
    out.add(new Language("jdg", "Jadgali", "I", "L", null, null, null, null));
    out.add(new Language("jdt", "Judeo-Tat", "I", "L", null, null, null, null));
    out.add(new Language("jeb", "Jebero", "I", "L", null, null, null, null));
    out.add(new Language("jee", "Jerung", "I", "L", null, null, null, null));
    out.add(new Language("jeh", "Jeh", "I", "L", null, null, null, null));
    out.add(new Language("jei", "Yei", "I", "L", null, null, null, null));
    out.add(new Language("jek", "Jeri Kuo", "I", "L", null, null, null, null));
    out.add(new Language("jel", "Yelmek", "I", "L", null, null, null, null));
    out.add(new Language("jen", "Dza", "I", "L", null, null, null, null));
    out.add(new Language("jer", "Jere", "I", "L", null, null, null, null));
    out.add(new Language("jet", "Manem", "I", "L", null, null, null, null));
    out.add(new Language("jeu", "Jonkor Bourmataguil", "I", "L", null, null, null, null));
    out.add(new Language("jgb", "Ngbee", "I", "E", null, null, null, null));
    out.add(new Language("jge", "Judeo-Georgian", "I", "L", null, null, null, null));
    out.add(new Language("jgk", "Gwak", "I", "L", null, null, null, null));
    out.add(new Language("jgo", "Ngomba", "I", "L", null, null, null, null));
    out.add(new Language("jhi", "Jehai", "I", "L", null, null, null, null));
    out.add(new Language("jhs", "Jhankot Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jia", "Jina", "I", "L", null, null, null, null));
    out.add(new Language("jib", "Jibu", "I", "L", null, null, null, null));
    out.add(new Language("jic", "Tol", "I", "L", null, null, null, null));
    out.add(new Language("jid", "Bu (Kaduna State)", "I", "L", null, null, null, null));
    out.add(new Language("jie", "Jilbe", "I", "L", null, null, null, null));
    out.add(new Language("jig", "Jingulu", "I", "L", null, null, null, null));
    out.add(new Language("jih", "sTodsde", "I", "L", null, null, null, null));
    out.add(new Language("jii", "Jiiddu", "I", "L", null, null, null, null));
    out.add(new Language("jil", "Jilim", "I", "L", null, null, null, null));
    out.add(new Language("jim", "Jimi (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("jio", "Jiamao", "I", "L", null, null, null, null));
    out.add(new Language("jiq", "Guanyinqiao", "I", "L", null, null, null, null));
    out.add(new Language("jit", "Jita", "I", "L", null, null, null, null));
    out.add(new Language("jiu", "Youle Jinuo", "I", "L", null, null, "Jinuo, Youle", null));
    out.add(new Language("jiv", "Shuar", "I", "L", null, null, null, null));
    out.add(new Language("jiy", "Buyuan Jinuo", "I", "L", null, null, "Jinuo, Buyuan", null));
    out.add(new Language("jje", "Jejueo", "I", "L", null, null, null, null));
    out.add(new Language("jjr", "Bankal", "I", "L", null, null, null, null));
    out.add(new Language("jka", "Kaera", "I", "L", null, null, null, null));
    out.add(new Language("jkm", "Mobwa Karen", "I", "L", null, null, "Karen, Mobwa", null));
    out.add(new Language("jko", "Kubo", "I", "L", null, null, null, null));
    out.add(new Language("jkp", "Paku Karen", "I", "L", null, null, "Karen, Paku", null));
    out.add(new Language("jkr", "Koro (India)", "I", "L", null, null, null, null));
    out.add(new Language("jks", "Amami Koniya Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jku", "Labir", "I", "L", null, null, null, null));
    out.add(new Language("jle", "Ngile", "I", "L", null, null, null, null));
    out.add(new Language("jls", "Jamaican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jma", "Dima", "I", "L", null, null, null, null));
    out.add(new Language("jmb", "Zumbun", "I", "L", null, null, null, null));
    out.add(new Language("jmc", "Machame", "I", "L", null, null, null, null));
    out.add(new Language("jmd", "Yamdena", "I", "L", null, null, null, null));
    out.add(new Language("jmi", "Jimi (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("jml", "Jumli", "I", "L", null, null, null, null));
    out.add(new Language("jmn", "Makuri Naga", "I", "L", null, null, "Naga, Makuri", null));
    out.add(new Language("jmr", "Kamara", "I", "L", null, null, null, null));
    out.add(new Language("jms", "Mashi (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("jmw", "Mouwase", "I", "L", null, null, null, null));
    out.add(new Language("jmx", "Western Juxtlahuaca Mixtec", "I", "L", null, null, "Mixtec, Western Juxtlahuaca", null));
    out.add(new Language("jna", "Jangshung", "I", "L", null, null, null, null));
    out.add(new Language("jnd", "Jandavra", "I", "L", null, null, null, null));
    out.add(new Language("jng", "Yangman", "I", "E", null, null, null, null));
    out.add(new Language("jni", "Janji", "I", "L", null, null, null, null));
    out.add(new Language("jnj", "Yemsa", "I", "L", null, null, null, null));
    out.add(new Language("jnl", "Rawat", "I", "L", null, null, null, null));
    out.add(new Language("jns", "Jaunsari", "I", "L", null, null, null, null));
    out.add(new Language("job", "Joba", "I", "L", null, null, null, null));
    out.add(new Language("jod", "Wojenaka", "I", "L", null, null, null, null));
    out.add(new Language("jog", "Jogi", "I", "L", null, null, null, null));
    out.add(new Language("jor", "Jorá", "I", "E", null, null, null, null));
    out.add(new Language("jos", "Jordanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jow", "Jowulu", "I", "L", null, null, null, null));
    out.add(new Language("jpa", "Jewish Palestinian Aramaic", "I", "H", null, null, "Aramaic, Jewish Palestinian", null));
    out.add(new Language("jpn", "Japanese", "I", "L", "ja", null, null, null));
    out.add(new Language("jpr", "Judeo-Persian", "I", "L", null, null, null, null));
    out.add(new Language("jqr", "Jaqaru", "I", "L", null, null, null, null));
    out.add(new Language("jra", "Jarai", "I", "L", null, null, null, null));
    out.add(new Language("jrb", "Judeo-Arabic", "M", "L", null, null, null, null));
    out.add(new Language("jrr", "Jiru", "I", "L", null, null, null, null));
    out.add(new Language("jrt", "Jakattoe", "I", "L", null, null, null, null));
    out.add(new Language("jru", "Japrería", "I", "L", null, null, null, null));
    out.add(new Language("jsl", "Japanese Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jua", "Júma", "I", "L", null, null, null, null));
    out.add(new Language("jub", "Wannu", "I", "L", null, null, null, null));
    out.add(new Language("juc", "Jurchen", "I", "H", null, null, null, null));
    out.add(new Language("jud", "Worodougou", "I", "L", null, null, null, null));
    out.add(new Language("juh", "Hõne", "I", "L", null, null, null, null));
    out.add(new Language("jui", "Ngadjuri", "I", "E", null, null, null, null));
    out.add(new Language("juk", "Wapan", "I", "L", null, null, null, null));
    out.add(new Language("jul", "Jirel", "I", "L", null, null, null, null));
    out.add(new Language("jum", "Jumjum", "I", "L", null, null, null, null));
    out.add(new Language("jun", "Juang", "I", "L", null, null, null, null));
    out.add(new Language("juo", "Jiba", "I", "L", null, null, null, null));
    out.add(new Language("jup", "Hupdë", "I", "L", null, null, null, null));
    out.add(new Language("jur", "Jurúna", "I", "L", null, null, null, null));
    out.add(new Language("jus", "Jumla Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("jut", "Jutish", "I", "H", null, null, null, null));
    out.add(new Language("juu", "Ju", "I", "L", null, null, null, null));
    out.add(new Language("juw", "Wãpha", "I", "L", null, null, null, null));
    out.add(new Language("juy", "Juray", "I", "L", null, null, null, null));
    out.add(new Language("jvd", "Javindo", "I", "L", null, null, null, null));
    out.add(new Language("jvn", "Caribbean Javanese", "I", "L", null, null, "Javanese, Caribbean", null));
    out.add(new Language("jwi", "Jwira-Pepesa", "I", "L", null, null, null, null));
    out.add(new Language("jya", "Jiarong", "I", "L", null, null, null, null));
    out.add(new Language("jye", "Judeo-Yemeni Arabic", "I", "L", null, null, "Arabic, Judeo-Yemeni", null));
    out.add(new Language("jyy", "Jaya", "I", "L", null, null, null, null));
    out.add(new Language("kaa", "Kara-Kalpak", "I", "L", null, null, null, null));
    out.add(new Language("kab", "Kabyle", "I", "L", null, null, null, null));
    out.add(new Language("kac", "Kachin", "I", "L", null, null, null, null));
    out.add(new Language("kad", "Adara", "I", "L", null, null, null, null));
    out.add(new Language("kae", "Ketangalan", "I", "E", null, null, null, null));
    out.add(new Language("kaf", "Katso", "I", "L", null, null, null, null));
    out.add(new Language("kag", "Kajaman", "I", "L", null, null, null, null));
    out.add(new Language("kah", "Kara (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("kai", "Karekare", "I", "L", null, null, null, null));
    out.add(new Language("kaj", "Jju", "I", "L", null, null, null, null));
    out.add(new Language("kak", "Kalanguya", "I", "L", null, null, null, null));
    out.add(new Language("kal", "Kalaallisut", "I", "L", "kl", null, null, null));
    out.add(new Language("kam", "Kamba (Kenya)", "I", "L", null, null, null, null));
    out.add(new Language("kan", "Kannada", "I", "L", "kn", null, null, null));
    out.add(new Language("kao", "Xaasongaxango", "I", "L", null, null, null, null));
    out.add(new Language("kap", "Bezhta", "I", "L", null, null, null, null));
    out.add(new Language("kaq", "Capanahua", "I", "L", null, null, null, null));
    out.add(new Language("kas", "Kashmiri", "I", "L", "ks", null, null, null));
    out.add(new Language("kat", "Georgian", "I", "L", "ka", null, null, "geo"));
    out.add(new Language("kau", "Kanuri", "M", "L", "kr", null, null, null));
    out.add(new Language("kav", "Katukína", "I", "L", null, null, null, null));
    out.add(new Language("kaw", "Kawi", "I", "H", null, null, null, null));
    out.add(new Language("kax", "Kao", "I", "L", null, null, null, null));
    out.add(new Language("kay", "Kamayurá", "I", "L", null, null, null, null));
    out.add(new Language("kaz", "Kazakh", "I", "L", "kk", null, null, null));
    out.add(new Language("kba", "Kalarko", "I", "E", null, null, null, null));
    out.add(new Language("kbb", "Kaxuiâna", "I", "E", null, null, null, null));
    out.add(new Language("kbc", "Kadiwéu", "I", "L", null, null, null, null));
    out.add(new Language("kbd", "Kabardian", "I", "L", null, null, null, null));
    out.add(new Language("kbe", "Kanju", "I", "L", null, null, null, null));
    out.add(new Language("kbg", "Khamba", "I", "L", null, null, null, null));
    out.add(new Language("kbh", "Camsá", "I", "L", null, null, null, null));
    out.add(new Language("kbi", "Kaptiau", "I", "L", null, null, null, null));
    out.add(new Language("kbj", "Kari", "I", "L", null, null, null, null));
    out.add(new Language("kbk", "Grass Koiari", "I", "L", null, null, "Koiari, Grass", null));
    out.add(new Language("kbl", "Kanembu", "I", "L", null, null, null, null));
    out.add(new Language("kbm", "Iwal", "I", "L", null, null, null, null));
    out.add(new Language("kbn", "Kare (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("kbo", "Keliko", "I", "L", null, null, null, null));
    out.add(new Language("kbp", "Kabiyè", "I", "L", null, null, null, null));
    out.add(new Language("kbq", "Kamano", "I", "L", null, null, null, null));
    out.add(new Language("kbr", "Kafa", "I", "L", null, null, null, null));
    out.add(new Language("kbs", "Kande", "I", "L", null, null, null, null));
    out.add(new Language("kbt", "Abadi", "I", "L", null, null, null, null));
    out.add(new Language("kbu", "Kabutra", "I", "L", null, null, null, null));
    out.add(new Language("kbv", "Dera (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("kbw", "Kaiep", "I", "L", null, null, null, null));
    out.add(new Language("kbx", "Ap Ma", "I", "L", null, null, null, null));
    out.add(new Language("kby", "Manga Kanuri", "I", "L", null, null, "Kanuri, Manga", null));
    out.add(new Language("kbz", "Duhwa", "I", "L", null, null, null, null));
    out.add(new Language("kca", "Khanty", "I", "L", null, null, null, null));
    out.add(new Language("kcb", "Kawacha", "I", "L", null, null, null, null));
    out.add(new Language("kcc", "Lubila", "I", "L", null, null, null, null));
    out.add(new Language("kcd", "Ngkâlmpw Kanum", "I", "L", null, null, "Kanum, Ngkâlmpw", null));
    out.add(new Language("kce", "Kaivi", "I", "L", null, null, null, null));
    out.add(new Language("kcf", "Ukaan", "I", "L", null, null, null, null));
    out.add(new Language("kcg", "Tyap", "I", "L", null, null, null, null));
    out.add(new Language("kch", "Vono", "I", "L", null, null, null, null));
    out.add(new Language("kci", "Ngyian", "I", "L", null, null, null, null));
    out.add(new Language("kcj", "Kobiana", "I", "L", null, null, null, null));
    out.add(new Language("kck", "Kalanga", "I", "L", null, null, null, null));
    out.add(new Language("kcl", "Kela (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("kcm", "Gula (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("kcn", "Nubi", "I", "L", null, null, null, null));
    out.add(new Language("kco", "Kinalakna", "I", "L", null, null, null, null));
    out.add(new Language("kcp", "Kanga", "I", "L", null, null, null, null));
    out.add(new Language("kcq", "Kamo", "I", "L", null, null, null, null));
    out.add(new Language("kcr", "Katla", "I", "L", null, null, null, null));
    out.add(new Language("kcs", "Koenoem", "I", "L", null, null, null, null));
    out.add(new Language("kct", "Kaian", "I", "L", null, null, null, null));
    out.add(new Language("kcu", "Kami (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("kcv", "Kete", "I", "L", null, null, null, null));
    out.add(new Language("kcw", "Kabwari", "I", "L", null, null, null, null));
    out.add(new Language("kcx", "Kachama-Ganjule", "I", "L", null, null, null, null));
    out.add(new Language("kcy", "Korandje", "I", "L", null, null, null, null));
    out.add(new Language("kcz", "Konongo", "I", "L", null, null, null, null));
    out.add(new Language("kda", "Worimi", "I", "E", null, null, null, null));
    out.add(new Language("kdc", "Kutu", "I", "L", null, null, null, null));
    out.add(new Language("kdd", "Yankunytjatjara", "I", "L", null, null, null, null));
    out.add(new Language("kde", "Makonde", "I", "L", null, null, null, null));
    out.add(new Language("kdf", "Mamusi", "I", "L", null, null, null, null));
    out.add(new Language("kdg", "Seba", "I", "L", null, null, null, null));
    out.add(new Language("kdh", "Tem", "I", "L", null, null, null, null));
    out.add(new Language("kdi", "Kumam", "I", "L", null, null, null, null));
    out.add(new Language("kdj", "Karamojong", "I", "L", null, null, null, null));
    out.add(new Language("kdk", "Numèè", "I", "L", null, null, null, null));
    out.add(new Language("kdl", "Tsikimba", "I", "L", null, null, null, null));
    out.add(new Language("kdm", "Kagoma", "I", "L", null, null, null, null));
    out.add(new Language("kdn", "Kunda", "I", "L", null, null, null, null));
    out.add(new Language("kdp", "Kaningdon-Nindem", "I", "L", null, null, null, null));
    out.add(new Language("kdq", "Koch", "I", "L", null, null, null, null));
    out.add(new Language("kdr", "Karaim", "I", "L", null, null, null, null));
    out.add(new Language("kdt", "Kuy", "I", "L", null, null, null, null));
    out.add(new Language("kdu", "Kadaru", "I", "L", null, null, null, null));
    out.add(new Language("kdw", "Koneraw", "I", "L", null, null, null, null));
    out.add(new Language("kdx", "Kam", "I", "L", null, null, null, null));
    out.add(new Language("kdy", "Keder", "I", "L", null, null, null, null));
    out.add(new Language("kdz", "Kwaja", "I", "L", null, null, null, null));
    out.add(new Language("kea", "Kabuverdianu", "I", "L", null, null, null, null));
    out.add(new Language("keb", "Kélé", "I", "L", null, null, null, null));
    out.add(new Language("kec", "Keiga", "I", "L", null, null, null, null));
    out.add(new Language("ked", "Kerewe", "I", "L", null, null, null, null));
    out.add(new Language("kee", "Eastern Keres", "I", "L", null, null, "Keres, Eastern", null));
    out.add(new Language("kef", "Kpessi", "I", "L", null, null, null, null));
    out.add(new Language("keg", "Tese", "I", "L", null, null, null, null));
    out.add(new Language("keh", "Keak", "I", "L", null, null, null, null));
    out.add(new Language("kei", "Kei", "I", "L", null, null, null, null));
    out.add(new Language("kej", "Kadar", "I", "L", null, null, null, null));
    out.add(new Language("kek", "Kekchí", "I", "L", null, null, null, null));
    out.add(new Language("kel", "Kela (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("kem", "Kemak", "I", "L", null, null, null, null));
    out.add(new Language("ken", "Kenyang", "I", "L", null, null, null, null));
    out.add(new Language("keo", "Kakwa", "I", "L", null, null, null, null));
    out.add(new Language("kep", "Kaikadi", "I", "L", null, null, null, null));
    out.add(new Language("keq", "Kamar", "I", "L", null, null, null, null));
    out.add(new Language("ker", "Kera", "I", "L", null, null, null, null));
    out.add(new Language("kes", "Kugbo", "I", "L", null, null, null, null));
    out.add(new Language("ket", "Ket", "I", "L", null, null, null, null));
    out.add(new Language("keu", "Akebu", "I", "L", null, null, null, null));
    out.add(new Language("kev", "Kanikkaran", "I", "L", null, null, null, null));
    out.add(new Language("kew", "West Kewa", "I", "L", null, null, "Kewa, West", null));
    out.add(new Language("kex", "Kukna", "I", "L", null, null, null, null));
    out.add(new Language("key", "Kupia", "I", "L", null, null, null, null));
    out.add(new Language("kez", "Kukele", "I", "L", null, null, null, null));
    out.add(new Language("kfa", "Kodava", "I", "L", null, null, null, null));
    out.add(new Language("kfb", "Northwestern Kolami", "I", "L", null, null, "Kolami, Northwestern", null));
    out.add(new Language("kfc", "Konda-Dora", "I", "L", null, null, null, null));
    out.add(new Language("kfd", "Korra Koraga", "I", "L", null, null, "Koraga, Korra", null));
    out.add(new Language("kfe", "Kota (India)", "I", "L", null, null, null, null));
    out.add(new Language("kff", "Koya", "I", "L", null, null, null, null));
    out.add(new Language("kfg", "Kudiya", "I", "L", null, null, null, null));
    out.add(new Language("kfh", "Kurichiya", "I", "L", null, null, null, null));
    out.add(new Language("kfi", "Kannada Kurumba", "I", "L", null, null, "Kurumba, Kannada", null));
    out.add(new Language("kfj", "Kemiehua", "I", "L", null, null, null, null));
    out.add(new Language("kfk", "Kinnauri", "I", "L", null, null, null, null));
    out.add(new Language("kfl", "Kung", "I", "L", null, null, null, null));
    out.add(new Language("kfm", "Khunsari", "I", "L", null, null, null, null));
    out.add(new Language("kfn", "Kuk", "I", "L", null, null, null, null));
    out.add(new Language("kfo", "Koro (Côte d'Ivoire)", "I", "L", null, null, null, null));
    out.add(new Language("kfp", "Korwa", "I", "L", null, null, null, null));
    out.add(new Language("kfq", "Korku", "I", "L", null, null, null, null));
    out.add(new Language("kfr", "Kachhi", "I", "L", null, null, null, null));
    out.add(new Language("kfs", "Bilaspuri", "I", "L", null, null, null, null));
    out.add(new Language("kft", "Kanjari", "I", "L", null, null, null, null));
    out.add(new Language("kfu", "Katkari", "I", "L", null, null, null, null));
    out.add(new Language("kfv", "Kurmukar", "I", "L", null, null, null, null));
    out.add(new Language("kfw", "Kharam Naga", "I", "L", null, null, "Naga, Kharam", null));
    out.add(new Language("kfx", "Kullu Pahari", "I", "L", null, null, "Pahari, Kullu", null));
    out.add(new Language("kfy", "Kumaoni", "I", "L", null, null, null, null));
    out.add(new Language("kfz", "Koromfé", "I", "L", null, null, null, null));
    out.add(new Language("kga", "Koyaga", "I", "L", null, null, null, null));
    out.add(new Language("kgb", "Kawe", "I", "L", null, null, null, null));
    out.add(new Language("kge", "Komering", "I", "L", null, null, null, null));
    out.add(new Language("kgf", "Kube", "I", "L", null, null, null, null));
    out.add(new Language("kgg", "Kusunda", "I", "L", null, null, null, null));
    out.add(new Language("kgi", "Selangor Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("kgj", "Gamale Kham", "I", "L", null, null, "Kham, Gamale", null));
    out.add(new Language("kgk", "Kaiwá", "I", "L", null, null, null, null));
    out.add(new Language("kgl", "Kunggari", "I", "E", null, null, null, null));
    out.add(new Language("kgn", "Karingani", "I", "L", null, null, null, null));
    out.add(new Language("kgo", "Krongo", "I", "L", null, null, null, null));
    out.add(new Language("kgp", "Kaingang", "I", "L", null, null, null, null));
    out.add(new Language("kgq", "Kamoro", "I", "L", null, null, null, null));
    out.add(new Language("kgr", "Abun", "I", "L", null, null, null, null));
    out.add(new Language("kgs", "Kumbainggar", "I", "L", null, null, null, null));
  }
}
