// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 500 to 999 of {@link Language}.
 */
final class LanguageData1 {
  private LanguageData1() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("azd", "Eastern Durango Nahuatl", "I", "L", null, null, "Nahuatl, Eastern Durango", null));
    out.add(new Language("aze", "Azerbaijani", "M", "L", "az", null, null, null));
    out.add(new Language("azg", "San Pedro Amuzgos Amuzgo", "I", "L", null, null, "Amuzgo, San Pedro Amuzgos", null));
    out.add(new Language("azj", "North Azerbaijani", "I", "L", null, null, "Azerbaijani, North", null));
    out.add(new Language("azm", "Ipalapa Amuzgo", "I", "L", null, null, "Amuzgo, Ipalapa", null));
    out.add(new Language("azn", "Western Durango Nahuatl", "I", "L", null, null, "Nahuatl, Western Durango", null));
    out.add(new Language("azo", "Awing", "I", "L", null, null, null, null));
    out.add(new Language("azt", "Faire Atta", "I", "L", null, null, "Atta, Faire", null));
    out.add(new Language("azz", "Highland Puebla Nahuatl", "I", "L", null, null, "Nahuatl, Highland Puebla", null));
    out.add(new Language("baa", "Babatana", "I", "L", null, null, null, null));
    out.add(new Language("bab", "Bainouk-Gunyuño", "I", "L", null, null, null, null));
    out.add(new Language("bac", "Badui", "I", "L", null, null, null, null));
    out.add(new Language("bae", "Baré", "I", "E", null, null, null, null));
    out.add(new Language("baf", "Nubaca", "I", "L", null, null, null, null));
    out.add(new Language("bag", "Tuki", "I", "L", null, null, null, null));
    out.add(new Language("bah", "Bahamas Creole English", "I", "L", null, null, "Creole English, Bahamas", null));
    out.add(new Language("baj", "Barakai", "I", "L", null, null, null, null));
    out.add(new Language("bak", "Bashkir", "I", "L", "ba", null, null, null));
    out.add(new Language("bal", "Baluchi", "M", "L", null, null, null, null));
    out.add(new Language("bam", "Bambara", "I", "L", "bm", null, null, null));
    out.add(new Language("ban", "Balinese", "I", "L", null, null, null, null));
    out.add(new Language("bao", "Waimaha", "I", "L", null, null, null, null));
    out.add(new Language("bap", "Bantawa", "I", "L", null, null, null, null));
    out.add(new Language("bar", "Bavarian", "I", "L", null, null, null, null));
    out.add(new Language("bas", "Basa (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("bau", "Bada (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("bav", "Vengo", "I", "L", null, null, null, null));
    out.add(new Language("baw", "Bambili-Bambui", "I", "L", null, null, null, null));
    out.add(new Language("bax", "Bamun", "I", "L", null, null, null, null));
    out.add(new Language("bay", "Batuley", "I", "L", null, null, null, null));
    out.add(new Language("bba", "Baatonum", "I", "L", null, null, null, null));
    out.add(new Language("bbb", "Barai", "I", "L", null, null, null, null));
    out.add(new Language("bbc", "Batak Toba", "I", "L", null, null, null, null));
    out.add(new Language("bbd", "Bau", "I", "L", null, null, null, null));
    out.add(new Language("bbe", "Bangba", "I", "L", null, null, null, null));
    out.add(new Language("bbf", "Baibai", "I", "L", null, null, null, null));
    out.add(new Language("bbg", "Barama", "I", "L", null, null, null, null));
    out.add(new Language("bbh", "Bugan", "I", "L", null, null, null, null));
    out.add(new Language("bbi", "Barombi", "I", "L", null, null, null, null));
    out.add(new Language("bbj", "Ghomálá'", "I", "L", null, null, null, null));
    out.add(new Language("bbk", "Babanki", "I", "L", null, null, null, null));
    out.add(new Language("bbl", "Bats", "I", "L", null, null, null, null));
    out.add(new Language("bbm", "Babango", "I", "L", null, null, null, null));
    out.add(new Language("bbn", "Uneapa", "I", "L", null, null, null, null));
    out.add(new Language("bbo", "Northern Bobo Madaré", "I", "L", null, null, "Bobo Madaré, Northern", null));
    out.add(new Language("bbp", "West Central Banda", "I", "L", null, null, "Banda, West Central", null));
    out.add(new Language("bbq", "Bamali", "I", "L", null, null, null, null));
    out.add(new Language("bbr", "Girawa", "I", "L", null, null, null, null));
    out.add(new Language("bbs", "Bakpinka", "I", "L", null, null, null, null));
    out.add(new Language("bbt", "Mburku", "I", "L", null, null, null, null));
    out.add(new Language("bbu", "Kulung (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("bbv", "Karnai", "I", "L", null, null, null, null));
    out.add(new Language("bbw", "Baba", "I", "L", null, null, null, null));
    out.add(new Language("bbx", "Bubia", "I", "L", null, null, null, null));
    out.add(new Language("bby", "Befang", "I", "L", null, null, null, null));
    out.add(new Language("bca", "Central Bai", "I", "L", null, null, "Bai, Central", null));
    out.add(new Language("bcb", "Bainouk-Samik", "I", "L", null, null, null, null));
    out.add(new Language("bcc", "Southern Balochi", "I", "L", null, null, "Balochi, Southern", null));
    out.add(new Language("bcd", "North Babar", "I", "L", null, null, "Babar, North", null));
    out.add(new Language("bce", "Bamenyam", "I", "L", null, null, null, null));
    out.add(new Language("bcf", "Bamu", "I", "L", null, null, null, null));
    out.add(new Language("bcg", "Baga Pokur", "I", "L", null, null, null, null));
    out.add(new Language("bch", "Bariai", "I", "L", null, null, null, null));
    out.add(new Language("bci", "Baoulé", "I", "L", null, null, null, null));
    out.add(new Language("bcj", "Bardi", "I", "L", null, null, null, null));
    out.add(new Language("bck", "Bunuba", "I", "L", null, null, null, null));
    out.add(new Language("bcl", "Central Bikol", "I", "L", null, null, "Bikol, Central", null));
    out.add(new Language("bcm", "Bannoni", "I", "L", null, null, null, null));
    out.add(new Language("bcn", "Bali (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("bco", "Kaluli", "I", "L", null, null, null, null));
    out.add(new Language("bcp", "Bali (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("bcq", "Bench", "I", "L", null, null, null, null));
    out.add(new Language("bcr", "Babine", "I", "L", null, null, null, null));
    out.add(new Language("bcs", "Kohumono", "I", "L", null, null, null, null));
    out.add(new Language("bct", "Bendi", "I", "L", null, null, null, null));
    out.add(new Language("bcu", "Awad Bing", "I", "L", null, null, null, null));
    out.add(new Language("bcv", "Shoo-Minda-Nye", "I", "L", null, null, null, null));
    out.add(new Language("bcw", "Bana", "I", "L", null, null, null, null));
    out.add(new Language("bcy", "Bacama", "I", "L", null, null, null, null));
    out.add(new Language("bcz", "Bainouk-Gunyaamolo", "I", "L", null, null, null, null));
    out.add(new Language("bda", "Bayot", "I", "L", null, null, null, null));
    out.add(new Language("bdb", "Basap", "I", "L", null, null, null, null));
    out.add(new Language("bdc", "Emberá-Baudó", "I", "L", null, null, null, null));
    out.add(new Language("bdd", "Bunama", "I", "L", null, null, null, null));
    out.add(new Language("bde", "Bade", "I", "L", null, null, null, null));
    out.add(new Language("bdf", "Biage", "I", "L", null, null, null, null));
    out.add(new Language("bdg", "Bonggi", "I", "L", null, null, null, null));
    out.add(new Language("bdh", "Baka (South Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("bdi", "Burun", "I", "L", null, null, null, null));
    out.add(new Language("bdj", "Bai (South Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("bdk", "Budukh", "I", "L", null, null, null, null));
    out.add(new Language("bdl", "Indonesian Bajau", "I", "L", null, null, "Bajau, Indonesian", null));
    out.add(new Language("bdm", "Buduma", "I", "L", null, null, null, null));
    out.add(new Language("bdn", "Baldemu", "I", "L", null, null, null, null));
    out.add(new Language("bdo", "Morom", "I", "L", null, null, null, null));
    out.add(new Language("bdp", "Bende", "I", "L", null, null, null, null));
    out.add(new Language("bdq", "Bahnar", "I", "L", null, null, null, null));
    out.add(new Language("bdr", "West Coast Bajau", "I", "L", null, null, "Bajau, West Coast", null));
    out.add(new Language("bds", "Burunge", "I", "L", null, null, null, null));
    out.add(new Language("bdt", "Bokoto", "I", "L", null, null, null, null));
    out.add(new Language("bdu", "Oroko", "I", "L", null, null, null, null));
    out.add(new Language("bdv", "Bodo Parja", "I", "L", null, null, null, null));
    out.add(new Language("bdw", "Baham", "I", "L", null, null, null, null));
    out.add(new Language("bdx", "Budong-Budong", "I", "L", null, null, null, null));
    out.add(new Language("bdy", "Bandjalang", "I", "L", null, null, null, null));
    out.add(new Language("bdz", "Badeshi", "I", "L", null, null, null, null));
    out.add(new Language("bea", "Beaver", "I", "L", null, null, null, null));
    out.add(new Language("beb", "Bebele", "I", "L", null, null, null, null));
    out.add(new Language("bec", "Iceve-Maci", "I", "L", null, null, null, null));
    out.add(new Language("bed", "Bedoanas", "I", "L", null, null, null, null));
    out.add(new Language("bee", "Byangsi", "I", "L", null, null, null, null));
    out.add(new Language("bef", "Benabena", "I", "L", null, null, null, null));
    out.add(new Language("beg", "Belait", "I", "L", null, null, null, null));
    out.add(new Language("beh", "Biali", "I", "L", null, null, null, null));
    out.add(new Language("bei", "Bekati'", "I", "L", null, null, null, null));
    out.add(new Language("bej", "Beja", "I", "L", null, null, null, null));
    out.add(new Language("bek", "Bebeli", "I", "L", null, null, null, null));
    out.add(new Language("bel", "Belarusian", "I", "L", "be", null, null, null));
    out.add(new Language("bem", "Bemba (Zambia)", "I", "L", null, null, null, null));
    out.add(new Language("ben", "Bengali", "I", "L", "bn", "Bangla", null, null));
    out.add(new Language("beo", "Beami", "I", "L", null, null, null, null));
    out.add(new Language("bep", "Besoa", "I", "L", null, null, null, null));
    out.add(new Language("beq", "Beembe", "I", "L", null, null, null, null));
    out.add(new Language("bes", "Besme", "I", "L", null, null, null, null));
    out.add(new Language("bet", "Guiberoua Béte", "I", "L", null, null, "Béte, Guiberoua", null));
    out.add(new Language("beu", "Blagar", "I", "L", null, null, null, null));
    out.add(new Language("bev", "Daloa Bété", "I", "L", null, null, "Bété, Daloa", null));
    out.add(new Language("bew", "Betawi", "I", "L", null, null, null, null));
    out.add(new Language("bex", "Jur Modo", "I", "L", null, null, null, null));
    out.add(new Language("bey", "Beli (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("bez", "Bena (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("bfa", "Bari", "I", "L", null, null, null, null));
    out.add(new Language("bfb", "Pauri Bareli", "I", "L", null, null, "Bareli, Pauri", null));
    out.add(new Language("bfc", "Panyi Bai", "I", "L", null, null, "Bai, Panyi", null));
    out.add(new Language("bfd", "Bafut", "I", "L", null, null, null, null));
    out.add(new Language("bfe", "Betaf", "I", "L", null, null, null, null));
    out.add(new Language("bff", "Bofi", "I", "L", null, null, null, null));
    out.add(new Language("bfg", "Busang Kayan", "I", "L", null, null, "Kayan, Busang", null));
    out.add(new Language("bfh", "Blafe", "I", "L", null, null, null, null));
    out.add(new Language("bfi", "British Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bfj", "Bafanji", "I", "L", null, null, null, null));
    out.add(new Language("bfk", "Ban Khor Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bfl", "Banda-Ndélé", "I", "L", null, null, null, null));
    out.add(new Language("bfm", "Mmen", "I", "L", null, null, null, null));
    out.add(new Language("bfn", "Bunak", "I", "L", null, null, null, null));
    out.add(new Language("bfo", "Malba Birifor", "I", "L", null, null, "Birifor, Malba", null));
    out.add(new Language("bfp", "Beba", "I", "L", null, null, null, null));
    out.add(new Language("bfq", "Badaga", "I", "L", null, null, null, null));
    out.add(new Language("bfr", "Bazigar", "I", "L", null, null, null, null));
    out.add(new Language("bfs", "Southern Bai", "I", "L", null, null, "Bai, Southern", null));
    out.add(new Language("bft", "Balti", "I", "L", null, null, null, null));
    out.add(new Language("bfu", "Gahri", "I", "L", null, null, null, null));
    out.add(new Language("bfw", "Bondo", "I", "L", null, null, null, null));
    out.add(new Language("bfx", "Bantayanon", "I", "L", null, null, null, null));
    out.add(new Language("bfy", "Bagheli", "I", "L", null, null, null, null));
    out.add(new Language("bfz", "Mahasu Pahari", "I", "L", null, null, "Pahari, Mahasu", null));
    out.add(new Language("bga", "Gwamhi-Wuri", "I", "L", null, null, null, null));
    out.add(new Language("bgb", "Bobongko", "I", "L", null, null, null, null));
    out.add(new Language("bgc", "Haryanvi", "I", "L", null, null, null, null));
    out.add(new Language("bgd", "Rathwi Bareli", "I", "L", null, null, "Bareli, Rathwi", null));
    out.add(new Language("bge", "Bauria", "I", "L", null, null, null, null));
    out.add(new Language("bgf", "Bangandu", "I", "L", null, null, null, null));
    out.add(new Language("bgg", "Bugun", "I", "L", null, null, null, null));
    out.add(new Language("bgi", "Giangan", "I", "L", null, null, null, null));
    out.add(new Language("bgj", "Bangolan", "I", "L", null, null, null, null));
    out.add(new Language("bgk", "Bit", "I", "L", null, null, null, null));
    out.add(new Language("bgl", "Bo (Laos)", "I", "L", null, null, null, null));
    out.add(new Language("bgn", "Western Balochi", "I", "L", null, null, "Balochi, Western", null));
    out.add(new Language("bgo", "Baga Koga", "I", "L", null, null, null, null));
    out.add(new Language("bgp", "Eastern Balochi", "I", "L", null, null, "Balochi, Eastern", null));
    out.add(new Language("bgq", "Bagri", "I", "L", null, null, null, null));
    out.add(new Language("bgr", "Bawm Chin", "I", "L", null, null, "Chin, Bawm", null));
    out.add(new Language("bgs", "Tagabawa", "I", "L", null, null, null, null));
    out.add(new Language("bgt", "Bughotu", "I", "L", null, null, null, null));
    out.add(new Language("bgu", "Mbongno", "I", "L", null, null, null, null));
    out.add(new Language("bgv", "Warkay-Bipim", "I", "L", null, null, null, null));
    out.add(new Language("bgw", "Bhatri", "I", "L", null, null, null, null));
    out.add(new Language("bgx", "Balkan Gagauz Turkish", "I", "L", null, null, "Turkish, Balkan Gagauz", null));
    out.add(new Language("bgy", "Benggoi", "I", "L", null, null, null, null));
    out.add(new Language("bgz", "Banggai", "I", "L", null, null, null, null));
    out.add(new Language("bha", "Bharia", "I", "L", null, null, null, null));
    out.add(new Language("bhb", "Bhili", "I", "L", null, null, null, null));
    out.add(new Language("bhc", "Biga", "I", "L", null, null, null, null));
    out.add(new Language("bhd", "Bhadrawahi", "I", "L", null, null, null, null));
    out.add(new Language("bhe", "Bhaya", "I", "L", null, null, null, null));
    out.add(new Language("bhf", "Odiai", "I", "L", null, null, null, null));
    out.add(new Language("bhg", "Binandere", "I", "L", null, null, null, null));
    out.add(new Language("bhh", "Bukharic", "I", "L", null, null, null, null));
    out.add(new Language("bhi", "Bhilali", "I", "L", null, null, null, null));
    out.add(new Language("bhj", "Bahing", "I", "L", null, null, null, null));
    out.add(new Language("bhl", "Bimin", "I", "L", null, null, null, null));
    out.add(new Language("bhm", "Bathari", "I", "L", null, null, null, null));
    out.add(new Language("bhn", "Bohtan Neo-Aramaic", "I", "L", null, null, "Neo-Aramaic, Bohtan", null));
    out.add(new Language("bho", "Bhojpuri", "I", "L", null, null, null, null));
    out.add(new Language("bhp", "Bima", "I", "L", null, null, null, null));
    out.add(new Language("bhq", "Tukang Besi South", "I", "L", null, null, null, null));
    out.add(new Language("bhr", "Bara Malagasy", "I", "L", null, null, "Malagasy, Bara", null));
    out.add(new Language("bhs", "Buwal", "I", "L", null, null, null, null));
    out.add(new Language("bht", "Bhattiyali", "I", "L", null, null, null, null));
    out.add(new Language("bhu", "Bhunjia", "I", "L", null, null, null, null));
    out.add(new Language("bhv", "Bahau", "I", "L", null, null, null, null));
    out.add(new Language("bhw", "Biak", "I", "L", null, null, null, null));
    out.add(new Language("bhx", "Bhalay", "I", "L", null, null, null, null));
    out.add(new Language("bhy", "Bhele", "I", "L", null, null, null, null));
    out.add(new Language("bhz", "Bada (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("bia", "Badimaya", "I", "L", null, null, null, null));
    out.add(new Language("bib", "Bissa", "I", "L", null, null, null, null));
    out.add(new Language("bid", "Bidiyo", "I", "L", null, null, null, null));
    out.add(new Language("bie", "Bepour", "I", "L", null, null, null, null));
    out.add(new Language("bif", "Biafada", "I", "L", null, null, null, null));
    out.add(new Language("big", "Biangai", "I", "L", null, null, null, null));
    out.add(new Language("bik", "Bikol", "M", "L", null, null, null, null));
    out.add(new Language("bil", "Bile", "I", "L", null, null, null, null));
    out.add(new Language("bim", "Bimoba", "I", "L", null, null, null, null));
    out.add(new Language("bin", "Bini", "I", "L", null, null, null, null));
    out.add(new Language("bio", "Nai", "I", "L", null, null, null, null));
    out.add(new Language("bip", "Bila", "I", "L", null, null, null, null));
    out.add(new Language("biq", "Bipi", "I", "L", null, null, null, null));
    out.add(new Language("bir", "Bisorio", "I", "L", null, null, null, null));
    out.add(new Language("bis", "Bislama", "I", "L", "bi", null, null, null));
    out.add(new Language("bit", "Berinomo", "I", "L", null, null, null, null));
    out.add(new Language("biu", "Biete", "I", "L", null, null, null, null));
    out.add(new Language("biv", "Southern Birifor", "I", "L", null, null, "Birifor, Southern", null));
    out.add(new Language("biw", "Kol (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("bix", "Bijori", "I", "L", null, null, null, null));
    out.add(new Language("biy", "Birhor", "I", "L", null, null, null, null));
    out.add(new Language("biz", "Baloi", "I", "L", null, null, null, null));
    out.add(new Language("bja", "Budza", "I", "L", null, null, null, null));
    out.add(new Language("bjb", "Banggarla", "I", "E", null, null, null, null));
    out.add(new Language("bjc", "Bariji", "I", "L", null, null, null, null));
    out.add(new Language("bje", "Biao-Jiao Mien", "I", "L", null, null, "Mien, Biao-Jiao", null));
    out.add(new Language("bjf", "Barzani Jewish Neo-Aramaic", "I", "L", null, null, "Neo-Aramaic, Barzani Jewish", null));
    out.add(new Language("bjg", "Bidyogo", "I", "L", null, null, null, null));
    out.add(new Language("bjh", "Bahinemo", "I", "L", null, null, null, null));
    out.add(new Language("bji", "Burji", "I", "L", null, null, null, null));
    out.add(new Language("bjj", "Kanauji", "I", "L", null, null, null, null));
    out.add(new Language("bjk", "Barok", "I", "L", null, null, null, null));
    out.add(new Language("bjl", "Bulu (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("bjm", "Bajelani", "I", "L", null, null, null, null));
    out.add(new Language("bjn", "Banjar", "I", "L", null, null, null, null));
    out.add(new Language("bjo", "Mid-Southern Banda", "I", "L", null, null, "Banda, Mid-Southern", null));
    out.add(new Language("bjp", "Fanamaket", "I", "L", null, null, null, null));
    out.add(new Language("bjr", "Binumarien", "I", "L", null, null, null, null));
    out.add(new Language("bjs", "Bajan", "I", "L", null, null, null, null));
    out.add(new Language("bjt", "Balanta-Ganja", "I", "L", null, null, null, null));
    out.add(new Language("bju", "Busuu", "I", "L", null, null, null, null));
    out.add(new Language("bjv", "Bedjond", "I", "L", null, null, null, null));
    out.add(new Language("bjw", "Bakwé", "I", "L", null, null, null, null));
    out.add(new Language("bjx", "Banao Itneg", "I", "L", null, null, "Itneg, Banao", null));
    out.add(new Language("bjy", "Bayali", "I", "E", null, null, null, null));
    out.add(new Language("bjz", "Baruga", "I", "L", null, null, null, null));
    out.add(new Language("bka", "Kyak", "I", "L", null, null, null, null));
    out.add(new Language("bkc", "Baka (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("bkd", "Binukid", "I", "L", null, null, null, null));
    out.add(new Language("bkf", "Beeke", "I", "L", null, null, null, null));
    out.add(new Language("bkg", "Buraka", "I", "L", null, null, null, null));
    out.add(new Language("bkh", "Bakoko", "I", "L", null, null, null, null));
    out.add(new Language("bki", "Baki", "I", "L", null, null, null, null));
    out.add(new Language("bkj", "Pande", "I", "L", null, null, null, null));
    out.add(new Language("bkk", "Brokskat", "I", "L", null, null, null, null));
    out.add(new Language("bkl", "Berik", "I", "L", null, null, null, null));
    out.add(new Language("bkm", "Kom (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("bkn", "Bukitan", "I", "L", null, null, null, null));
    out.add(new Language("bko", "Kwa'", "I", "L", null, null, null, null));
    out.add(new Language("bkp", "Boko (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("bkq", "Bakairí", "I", "L", null, null, null, null));
    out.add(new Language("bkr", "Bakumpai", "I", "L", null, null, null, null));
    out.add(new Language("bks", "Northern Sorsoganon", "I", "L", null, null, "Sorsoganon, Northern", null));
    out.add(new Language("bkt", "Boloki", "I", "L", null, null, null, null));
    out.add(new Language("bku", "Buhid", "I", "L", null, null, null, null));
    out.add(new Language("bkv", "Bekwarra", "I", "L", null, null, null, null));
    out.add(new Language("bkw", "Bekwel", "I", "L", null, null, null, null));
    out.add(new Language("bkx", "Baikeno", "I", "L", null, null, null, null));
    out.add(new Language("bky", "Bokyi", "I", "L", null, null, null, null));
    out.add(new Language("bkz", "Bungku", "I", "L", null, null, null, null));
    out.add(new Language("bla", "Siksika", "I", "L", null, null, null, null));
    out.add(new Language("blb", "Bilua", "I", "L", null, null, null, null));
    out.add(new Language("blc", "Bella Coola", "I", "L", null, null, null, null));
    out.add(new Language("bld", "Bolango", "I", "L", null, null, null, null));
    out.add(new Language("ble", "Balanta-Kentohe", "I", "L", null, null, null, null));
    out.add(new Language("blf", "Buol", "I", "L", null, null, null, null));
    out.add(new Language("blh", "Kuwaa", "I", "L", null, null, null, null));
    out.add(new Language("bli", "Bolia", "I", "L", null, null, null, null));
    out.add(new Language("blj", "Bolongan", "I", "L", null, null, null, null));
    out.add(new Language("blk", "Pa'o Karen", "I", "L", null, null, "Karen, Pa'o", null));
    out.add(new Language("bll", "Biloxi", "I", "E", null, null, null, null));
    out.add(new Language("blm", "Beli (South Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("bln", "Southern Catanduanes Bikol", "I", "L", null, null, "Bikol, Southern Catanduanes", null));
    out.add(new Language("blo", "Anii", "I", "L", null, null, null, null));
    out.add(new Language("blp", "Blablanga", "I", "L", null, null, null, null));
    out.add(new Language("blq", "Baluan-Pam", "I", "L", null, null, null, null));
    out.add(new Language("blr", "Blang", "I", "L", null, null, null, null));
    out.add(new Language("bls", "Balaesang", "I", "L", null, null, null, null));
    out.add(new Language("blt", "Tai Dam", "I", "L", null, null, null, null));
    out.add(new Language("blv", "Kibala", "I", "L", null, null, null, null));
    out.add(new Language("blw", "Balangao", "I", "L", null, null, null, null));
    out.add(new Language("blx", "Mag-Indi Ayta", "I", "L", null, null, "Ayta, Mag-Indi", null));
    out.add(new Language("bly", "Notre", "I", "L", null, null, null, null));
    out.add(new Language("blz", "Balantak", "I", "L", null, null, null, null));
    out.add(new Language("bma", "Lame", "I", "L", null, null, null, null));
    out.add(new Language("bmb", "Bembe", "I", "L", null, null, null, null));
    out.add(new Language("bmc", "Biem", "I", "L", null, null, null, null));
    out.add(new Language("bmd", "Baga Manduri", "I", "L", null, null, "Manduri, Baga", null));
    out.add(new Language("bme", "Limassa", "I", "L", null, null, null, null));
    out.add(new Language("bmf", "Bom-Kim", "I", "L", null, null, null, null));
    out.add(new Language("bmg", "Bamwe", "I", "L", null, null, null, null));
    out.add(new Language("bmh", "Kein", "I", "L", null, null, null, null));
    out.add(new Language("bmi", "Bagirmi", "I", "L", null, null, null, null));
    out.add(new Language("bmj", "Bote-Majhi", "I", "L", null, null, null, null));
    out.add(new Language("bmk", "Ghayavi", "I", "L", null, null, null, null));
    out.add(new Language("bml", "Bomboli", "I", "L", null, null, null, null));
    out.add(new Language("bmm", "Northern Betsimisaraka Malagasy", "I", "L", null, null, "Malagasy, Northern Betsimisaraka", null));
    out.add(new Language("bmn", "Bina (Papua New Guinea)", "I", "E", null, null, null, null));
    out.add(new Language("bmo", "Bambalang", "I", "L", null, null, null, null));
    out.add(new Language("bmp", "Bulgebi", "I", "L", null, null, null, null));
    out.add(new Language("bmq", "Bomu", "I", "L", null, null, null, null));
    out.add(new Language("bmr", "Muinane", "I", "L", null, null, null, null));
    out.add(new Language("bms", "Bilma Kanuri", "I", "L", null, null, "Kanuri, Bilma", null));
    out.add(new Language("bmt", "Biao Mon", "I", "L", null, null, null, null));
    out.add(new Language("bmu", "Somba-Siawari", "I", "L", null, null, null, null));
    out.add(new Language("bmv", "Bum", "I", "L", null, null, null, null));
    out.add(new Language("bmw", "Bomwali", "I", "L", null, null, null, null));
    out.add(new Language("bmx", "Baimak", "I", "L", null, null, null, null));
    out.add(new Language("bmz", "Baramu", "I", "L", null, null, null, null));
    out.add(new Language("bna", "Bonerate", "I", "L", null, null, null, null));
    out.add(new Language("bnb", "Bookan", "I", "L", null, null, null, null));
    out.add(new Language("bnc", "Bontok", "M", "L", null, null, null, null));
    out.add(new Language("bnd", "Banda (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("bne", "Bintauna", "I", "L", null, null, null, null));
    out.add(new Language("bnf", "Masiwang", "I", "L", null, null, null, null));
    out.add(new Language("bng", "Benga", "I", "L", null, null, null, null));
    out.add(new Language("bni", "Bangi", "I", "L", null, null, null, null));
    out.add(new Language("bnj", "Eastern Tawbuid", "I", "L", null, null, "Tawbuid, Eastern", null));
    out.add(new Language("bnk", "Bierebo", "I", "L", null, null, null, null));
    out.add(new Language("bnl", "Boon", "I", "L", null, null, null, null));
    out.add(new Language("bnm", "Batanga", "I", "L", null, null, null, null));
    out.add(new Language("bnn", "Bunun", "I", "L", null, null, null, null));
    out.add(new Language("bno", "Bantoanon", "I", "L", null, null, null, null));
    out.add(new Language("bnp", "Bola", "I", "L", null, null, null, null));
    out.add(new Language("bnq", "Bantik", "I", "L", null, null, null, null));
    out.add(new Language("bnr", "Butmas-Tur", "I", "L", null, null, null, null));
    out.add(new Language("bns", "Bundeli", "I", "L", null, null, null, null));
    out.add(new Language("bnu", "Bentong", "I", "L", null, null, null, null));
    out.add(new Language("bnv", "Bonerif", "I", "L", null, null, null, null));
    out.add(new Language("bnw", "Bisis", "I", "L", null, null, null, null));
    out.add(new Language("bnx", "Bangubangu", "I", "L", null, null, null, null));
    out.add(new Language("bny", "Bintulu", "I", "L", null, null, null, null));
    out.add(new Language("bnz", "Beezen", "I", "L", null, null, null, null));
    out.add(new Language("boa", "Bora", "I", "L", null, null, null, null));
    out.add(new Language("bob", "Aweer", "I", "L", null, null, null, null));
    out.add(new Language("bod", "Tibetan", "I", "L", "bo", null, null, "tib"));
    out.add(new Language("boe", "Mundabli", "I", "L", null, null, null, null));
    out.add(new Language("bof", "Bolon", "I", "L", null, null, null, null));
    out.add(new Language("bog", "Bamako Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("boh", "Boma", "I", "L", null, null, null, null));
    out.add(new Language("boi", "Barbareño", "I", "E", null, null, null, null));
    out.add(new Language("boj", "Anjam", "I", "L", null, null, null, null));
    out.add(new Language("bok", "Bonjo", "I", "L", null, null, null, null));
    out.add(new Language("bol", "Bole", "I", "L", null, null, null, null));
    out.add(new Language("bom", "Berom", "I", "L", null, null, null, null));
    out.add(new Language("bon", "Bine", "I", "L", null, null, null, null));
    out.add(new Language("boo", "Tiemacèwè Bozo", "I", "L", null, null, "Bozo, Tiemacèwè", null));
    out.add(new Language("bop", "Bonkiman", "I", "L", null, null, null, null));
    out.add(new Language("boq", "Bogaya", "I", "L", null, null, null, null));
    out.add(new Language("bor", "Borôro", "I", "L", null, null, null, null));
    out.add(new Language("bos", "Bosnian", "I", "L", "bs", null, null, null));
    out.add(new Language("bot", "Bongo", "I", "L", null, null, null, null));
    out.add(new Language("bou", "Bondei", "I", "L", null, null, null, null));
    out.add(new Language("bov", "Tuwuli", "I", "L", null, null, null, null));
    out.add(new Language("bow", "Rema", "I", "E", null, null, null, null));
    out.add(new Language("box", "Buamu", "I", "L", null, null, null, null));
    out.add(new Language("boy", "Bodo (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("boz", "Tiéyaxo Bozo", "I", "L", null, null, "Bozo, Tiéyaxo", null));
    out.add(new Language("bpa", "Daakaka", "I", "L", null, null, null, null));
    out.add(new Language("bpc", "Mbuk", "I", "L", null, null, null, null));
    out.add(new Language("bpd", "Banda-Banda", "I", "L", null, null, null, null));
    out.add(new Language("bpe", "Bauni", "I", "L", null, null, null, null));
    out.add(new Language("bpg", "Bonggo", "I", "L", null, null, null, null));
    out.add(new Language("bph", "Botlikh", "I", "L", null, null, null, null));
    out.add(new Language("bpi", "Bagupi", "I", "L", null, null, null, null));
    out.add(new Language("bpj", "Binji", "I", "L", null, null, null, null));
    out.add(new Language("bpk", "Orowe", "I", "L", null, null, null, null));
    out.add(new Language("bpl", "Broome Pearling Lugger Pidgin", "I", "L", null, null, null, null));
    out.add(new Language("bpm", "Biyom", "I", "L", null, null, null, null));
    out.add(new Language("bpn", "Dzao Min", "I", "L", null, null, null, null));
    out.add(new Language("bpo", "Anasi", "I", "L", null, null, null, null));
    out.add(new Language("bpp", "Kaure", "I", "L", null, null, null, null));
    out.add(new Language("bpq", "Banda Malay", "I", "L", null, null, "Malay, Banda", null));
    out.add(new Language("bpr", "Koronadal Blaan", "I", "L", null, null, "Blaan, Koronadal", null));
    out.add(new Language("bps", "Sarangani Blaan", "I", "L", null, null, "Blaan, Sarangani", null));
    out.add(new Language("bpt", "Barrow Point", "I", "E", null, null, null, null));
    out.add(new Language("bpu", "Bongu", "I", "L", null, null, null, null));
    out.add(new Language("bpv", "Bian Marind", "I", "L", null, null, "Marind, Bian", null));
    out.add(new Language("bpw", "Bo (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("bpx", "Palya Bareli", "I", "L", null, null, "Bareli, Palya", null));
    out.add(new Language("bpy", "Bishnupriya", "I", "L", null, null, null, null));
    out.add(new Language("bpz", "Bilba", "I", "L", null, null, null, null));
    out.add(new Language("bqa", "Tchumbuli", "I", "L", null, null, null, null));
    out.add(new Language("bqb", "Bagusa", "I", "L", null, null, null, null));
    out.add(new Language("bqc", "Boko (Benin)", "I", "L", null, null, null, null));
    out.add(new Language("bqd", "Bung", "I", "L", null, null, null, null));
    out.add(new Language("bqf", "Baga Kaloum", "I", "E", null, null, null, null));
    out.add(new Language("bqg", "Bago-Kusuntu", "I", "L", null, null, null, null));
    out.add(new Language("bqh", "Baima", "I", "L", null, null, null, null));
    out.add(new Language("bqi", "Bakhtiari", "I", "L", null, null, null, null));
    out.add(new Language("bqj", "Bandial", "I", "L", null, null, null, null));
    out.add(new Language("bqk", "Banda-Mbrès", "I", "L", null, null, null, null));
    out.add(new Language("bql", "Karian", "I", "L", null, null, null, null));
    out.add(new Language("bqm", "Wumboko", "I", "L", null, null, null, null));
    out.add(new Language("bqn", "Bulgarian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bqo", "Balo", "I", "L", null, null, null, null));
    out.add(new Language("bqp", "Busa", "I", "L", null, null, null, null));
    out.add(new Language("bqq", "Biritai", "I", "L", null, null, null, null));
    out.add(new Language("bqr", "Burusu", "I", "L", null, null, null, null));
    out.add(new Language("bqs", "Bosngun", "I", "L", null, null, null, null));
    out.add(new Language("bqt", "Bamukumbit", "I", "L", null, null, null, null));
    out.add(new Language("bqu", "Boguru", "I", "L", null, null, null, null));
    out.add(new Language("bqv", "Koro Wachi", "I", "L", null, null, null, null));
    out.add(new Language("bqw", "Buru (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("bqx", "Baangi", "I", "L", null, null, null, null));
    out.add(new Language("bqy", "Bengkala Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bqz", "Bakaka", "I", "L", null, null, null, null));
    out.add(new Language("bra", "Braj", "I", "L", null, null, null, null));
    out.add(new Language("brb", "Brao", "I", "L", null, null, null, null));
    out.add(new Language("brc", "Berbice Creole Dutch", "I", "E", null, null, "Creole Dutch, Berbice", null));
    out.add(new Language("brd", "Baraamu", "I", "L", null, null, null, null));
    out.add(new Language("bre", "Breton", "I", "L", "br", null, null, null));
    out.add(new Language("brf", "Bira", "I", "L", null, null, null, null));
    out.add(new Language("brg", "Baure", "I", "L", null, null, null, null));
    out.add(new Language("brh", "Brahui", "I", "L", null, null, null, null));
    out.add(new Language("bri", "Mokpwe", "I", "L", null, null, null, null));
    out.add(new Language("brj", "Bieria", "I", "L", null, null, null, null));
    out.add(new Language("brk", "Birked", "I", "E", null, null, null, null));
    out.add(new Language("brl", "Birwa", "I", "L", null, null, null, null));
    out.add(new Language("brm", "Barambu", "I", "L", null, null, null, null));
    out.add(new Language("brn", "Boruca", "I", "L", null, null, null, null));
    out.add(new Language("bro", "Brokkat", "I", "L", null, null, null, null));
    out.add(new Language("brp", "Barapasi", "I", "L", null, null, null, null));
    out.add(new Language("brq", "Breri", "I", "L", null, null, null, null));
    out.add(new Language("brr", "Birao", "I", "L", null, null, null, null));
    out.add(new Language("brs", "Baras", "I", "L", null, null, null, null));
    out.add(new Language("brt", "Bitare", "I", "L", null, null, null, null));
    out.add(new Language("bru", "Eastern Bru", "I", "L", null, null, "Bru, Eastern", null));
    out.add(new Language("brv", "Western Bru", "I", "L", null, null, "Bru, Western", null));
    out.add(new Language("brw", "Bellari", "I", "L", null, null, null, null));
    out.add(new Language("brx", "Bodo (India)", "I", "L", null, null, null, null));
    out.add(new Language("bry", "Burui", "I", "L", null, null, null, null));
    out.add(new Language("brz", "Bilbil", "I", "L", null, null, null, null));
    out.add(new Language("bsa", "Abinomn", "I", "L", null, null, null, null));
    out.add(new Language("bsb", "Brunei Bisaya", "I", "L", null, null, "Bisaya, Brunei", null));
    out.add(new Language("bsc", "Bassari", "I", "L", null, null, null, null));
    out.add(new Language("bse", "Wushi", "I", "L", null, null, null, null));
    out.add(new Language("bsf", "Bauchi", "I", "L", null, null, null, null));
    out.add(new Language("bsg", "Bashkardi", "I", "L", null, null, null, null));
    out.add(new Language("bsh", "Kati", "I", "L", null, null, null, null));
    out.add(new Language("bsi", "Bassossi", "I", "L", null, null, null, null));
    out.add(new Language("bsj", "Bangwinji", "I", "L", null, null, null, null));
    out.add(new Language("bsk", "Burushaski", "I", "L", null, null, null, null));
    out.add(new Language("bsl", "Basa-Gumna", "I", "E", null, null, null, null));
    out.add(new Language("bsm", "Busami", "I", "L", null, null, null, null));
    out.add(new Language("bsn", "Barasana-Eduria", "I", "L", null, null, null, null));
    out.add(new Language("bso", "Buso", "I", "L", null, null, null, null));
    out.add(new Language("bsp", "Baga Sitemu", "I", "L", null, null, null, null));
    out.add(new Language("bsq", "Bassa", "I", "L", null, null, null, null));
    out.add(new Language("bsr", "Bassa-Kontagora", "I", "L", null, null, null, null));
    out.add(new Language("bss", "Akoose", "I", "L", null, null, null, null));
    out.add(new Language("bst", "Basketo", "I", "L", null, null, null, null));
    out.add(new Language("bsu", "Bahonsuai", "I", "L", null, null, null, null));
    out.add(new Language("bsv", "Baga Sobané", "I", "E", null, null, null, null));
    out.add(new Language("bsw", "Baiso", "I", "L", null, null, null, null));
    out.add(new Language("bsx", "Yangkam", "I", "L", null, null, null, null));
    out.add(new Language("bsy", "Sabah Bisaya", "I", "L", null, null, "Bisaya, Sabah", null));
    out.add(new Language("bta", "Bata", "I", "L", null, null, null, null));
    out.add(new Language("btc", "Bati (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("btd", "Batak Dairi", "I", "L", null, null, null, null));
    out.add(new Language("bte", "Gamo-Ningi", "I", "E", null, null, null, null));
    out.add(new Language("btf", "Birgit", "I", "L", null, null, null, null));
    out.add(new Language("btg", "Gagnoa Bété", "I", "L", null, null, "Bété, Gagnoa", null));
    out.add(new Language("bth", "Biatah Bidayuh", "I", "L", null, null, "Bidayuh, Biatah", null));
    out.add(new Language("bti", "Burate", "I", "L", null, null, null, null));
    out.add(new Language("btj", "Bacanese Malay", "I", "L", null, null, "Malay, Bacanese", null));
    out.add(new Language("btm", "Batak Mandailing", "I", "L", null, null, null, null));
    out.add(new Language("btn", "Ratagnon", "I", "L", null, null, null, null));
    out.add(new Language("bto", "Rinconada Bikol", "I", "L", null, null, "Bikol, Rinconada", null));
    out.add(new Language("btp", "Budibud", "I", "L", null, null, null, null));
    out.add(new Language("btq", "Batek", "I", "L", null, null, null, null));
    out.add(new Language("btr", "Baetora", "I", "L", null, null, null, null));
    out.add(new Language("bts", "Batak Simalungun", "I", "L", null, null, null, null));
    out.add(new Language("btt", "Bete-Bendi", "I", "L", null, null, null, null));
    out.add(new Language("btu", "Batu", "I", "L", null, null, null, null));
    out.add(new Language("btv", "Bateri", "I", "L", null, null, null, null));
    out.add(new Language("btw", "Butuanon", "I", "L", null, null, null, null));
    out.add(new Language("btx", "Batak Karo", "I", "L", null, null, null, null));
    out.add(new Language("bty", "Bobot", "I", "L", null, null, null, null));
    out.add(new Language("btz", "Batak Alas-Kluet", "I", "L", null, null, null, null));
    out.add(new Language("bua", "Buriat", "M", "L", null, null, null, null));
    out.add(new Language("bub", "Bua", "I", "L", null, null, null, null));
    out.add(new Language("buc", "Bushi", "I", "L", null, null, null, null));
    out.add(new Language("bud", "Ntcham", "I", "L", null, null, null, null));
    out.add(new Language("bue", "Beothuk", "I", "E", null, null, null, null));
  }
}
