// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 3500 to 3999 of {@link Language}.
 */
final class LanguageData7 {
  private LanguageData7() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("lay", "Lama Bai", "I", "L", null, null, "Bai, Lama", null));
    out.add(new Language("laz", "Aribwatsa", "I", "E", null, null, null, null));
    out.add(new Language("lbb", "Label", "I", "L", null, null, null, null));
    out.add(new Language("lbc", "Lakkia", "I", "L", null, null, null, null));
    out.add(new Language("lbe", "Lak", "I", "L", null, null, null, null));
    out.add(new Language("lbf", "Tinani", "I", "L", null, null, null, null));
    out.add(new Language("lbg", "Laopang", "I", "L", null, null, null, null));
    out.add(new Language("lbi", "La'bi", "I", "L", null, null, null, null));
    out.add(new Language("lbj", "Ladakhi", "I", "L", null, null, null, null));
    out.add(new Language("lbk", "Central Bontok", "I", "L", null, null, "Bontok, Central", null));
    out.add(new Language("lbl", "Libon Bikol", "I", "L", null, null, "Bikol, Libon", null));
    out.add(new Language("lbm", "Lodhi", "I", "L", null, null, null, null));
    out.add(new Language("lbn", "Rmeet", "I", "L", null, null, null, null));
    out.add(new Language("lbo", "Laven", "I", "L", null, null, null, null));
    out.add(new Language("lbq", "Wampar", "I", "L", null, null, null, null));
    out.add(new Language("lbr", "Lohorung", "I", "L", null, null, null, null));
    out.add(new Language("lbs", "Libyan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lbt", "Lachi", "I", "L", null, null, null, null));
    out.add(new Language("lbu", "Labu", "I", "L", null, null, null, null));
    out.add(new Language("lbv", "Lavatbura-Lamusong", "I", "L", null, null, null, null));
    out.add(new Language("lbw", "Tolaki", "I", "L", null, null, null, null));
    out.add(new Language("lbx", "Lawangan", "I", "L", null, null, null, null));
    out.add(new Language("lby", "Lamalama", "I", "E", null, null, null, null));
    out.add(new Language("lbz", "Lardil", "I", "L", null, null, null, null));
    out.add(new Language("lcc", "Legenyem", "I", "L", null, null, null, null));
    out.add(new Language("lcd", "Lola", "I", "L", null, null, null, null));
    out.add(new Language("lce", "Loncong", "I", "L", null, null, null, null));
    out.add(new Language("lcf", "Lubu", "I", "L", null, null, null, null));
    out.add(new Language("lch", "Luchazi", "I", "L", null, null, null, null));
    out.add(new Language("lcl", "Lisela", "I", "L", null, null, null, null));
    out.add(new Language("lcm", "Tungag", "I", "L", null, null, null, null));
    out.add(new Language("lcp", "Western Lawa", "I", "L", null, null, "Lawa, Western", null));
    out.add(new Language("lcq", "Luhu", "I", "L", null, null, null, null));
    out.add(new Language("lcs", "Lisabata-Nuniali", "I", "L", null, null, null, null));
    out.add(new Language("lda", "Kla-Dan", "I", "L", null, null, null, null));
    out.add(new Language("ldb", "Dũya", "I", "L", null, null, null, null));
    out.add(new Language("ldd", "Luri", "I", "L", null, null, null, null));
    out.add(new Language("ldg", "Lenyima", "I", "L", null, null, null, null));
    out.add(new Language("ldh", "Lamja-Dengsa-Tola", "I", "L", null, null, null, null));
    out.add(new Language("ldi", "Laari", "I", "L", null, null, null, null));
    out.add(new Language("ldj", "Lemoro", "I", "L", null, null, null, null));
    out.add(new Language("ldk", "Leelau", "I", "L", null, null, null, null));
    out.add(new Language("ldl", "Kaan", "I", "L", null, null, null, null));
    out.add(new Language("ldm", "Landoma", "I", "L", null, null, null, null));
    out.add(new Language("ldn", "Láadan", "I", "C", null, null, null, null));
    out.add(new Language("ldo", "Loo", "I", "L", null, null, null, null));
    out.add(new Language("ldp", "Tso", "I", "L", null, null, null, null));
    out.add(new Language("ldq", "Lufu", "I", "L", null, null, null, null));
    out.add(new Language("lea", "Lega-Shabunda", "I", "L", null, null, null, null));
    out.add(new Language("leb", "Lala-Bisa", "I", "L", null, null, null, null));
    out.add(new Language("lec", "Leco", "I", "L", null, null, null, null));
    out.add(new Language("led", "Lendu", "I", "L", null, null, null, null));
    out.add(new Language("lee", "Lyélé", "I", "L", null, null, null, null));
    out.add(new Language("lef", "Lelemi", "I", "L", null, null, null, null));
    out.add(new Language("leh", "Lenje", "I", "L", null, null, null, null));
    out.add(new Language("lei", "Lemio", "I", "L", null, null, null, null));
    out.add(new Language("lej", "Lengola", "I", "L", null, null, null, null));
    out.add(new Language("lek", "Leipon", "I", "L", null, null, null, null));
    out.add(new Language("lel", "Lele (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("lem", "Nomaande", "I", "L", null, null, null, null));
    out.add(new Language("len", "Lenca", "I", "E", null, null, null, null));
    out.add(new Language("leo", "Leti (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("lep", "Lepcha", "I", "L", null, null, null, null));
    out.add(new Language("leq", "Lembena", "I", "L", null, null, null, null));
    out.add(new Language("ler", "Lenkau", "I", "L", null, null, null, null));
    out.add(new Language("les", "Lese", "I", "L", null, null, null, null));
    out.add(new Language("let", "Lesing-Gelimi", "I", "L", null, null, null, null));
    out.add(new Language("leu", "Kara (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("lev", "Lamma", "I", "L", null, null, null, null));
    out.add(new Language("lew", "Ledo Kaili", "I", "L", null, null, "Kaili, Ledo", null));
    out.add(new Language("lex", "Luang", "I", "L", null, null, null, null));
    out.add(new Language("ley", "Lemolang", "I", "L", null, null, null, null));
    out.add(new Language("lez", "Lezghian", "I", "L", null, null, null, null));
    out.add(new Language("lfa", "Lefa", "I", "L", null, null, null, null));
    out.add(new Language("lfn", "Lingua Franca Nova", "I", "C", null, null, null, null));
    out.add(new Language("lga", "Lungga", "I", "L", null, null, null, null));
    out.add(new Language("lgb", "Laghu", "I", "L", null, null, null, null));
    out.add(new Language("lgg", "Lugbara", "I", "L", null, null, null, null));
    out.add(new Language("lgh", "Laghuu", "I", "L", null, null, null, null));
    out.add(new Language("lgi", "Lengilu", "I", "L", null, null, null, null));
    out.add(new Language("lgk", "Lingarak", "I", "L", null, null, null, null));
    out.add(new Language("lgl", "Wala", "I", "L", null, null, null, null));
    out.add(new Language("lgm", "Lega-Mwenga", "I", "L", null, null, null, null));
    out.add(new Language("lgn", "T'apo", "I", "L", null, null, null, null));
    out.add(new Language("lgo", "Lango (South Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("lgq", "Logba", "I", "L", null, null, null, null));
    out.add(new Language("lgr", "Lengo", "I", "L", null, null, null, null));
    out.add(new Language("lgs", "Guinea-Bissau Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lgt", "Pahi", "I", "L", null, null, null, null));
    out.add(new Language("lgu", "Longgu", "I", "L", null, null, null, null));
    out.add(new Language("lgz", "Ligenza", "I", "L", null, null, null, null));
    out.add(new Language("lha", "Laha (Viet Nam)", "I", "L", null, null, null, null));
    out.add(new Language("lhh", "Laha (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("lhi", "Lahu Shi", "I", "L", null, null, null, null));
    out.add(new Language("lhl", "Lahul Lohar", "I", "L", null, null, "Lohar, Lahul", null));
    out.add(new Language("lhm", "Lhomi", "I", "L", null, null, null, null));
    out.add(new Language("lhn", "Lahanan", "I", "L", null, null, null, null));
    out.add(new Language("lhp", "Lhokpu", "I", "L", null, null, null, null));
    out.add(new Language("lhs", "Mlahsö", "I", "E", null, null, null, null));
    out.add(new Language("lht", "Lo-Toga", "I", "L", null, null, null, null));
    out.add(new Language("lhu", "Lahu", "I", "L", null, null, null, null));
    out.add(new Language("lia", "West-Central Limba", "I", "L", null, null, "Limba, West-Central", null));
    out.add(new Language("lib", "Likum", "I", "L", null, null, null, null));
    out.add(new Language("lic", "Hlai", "I", "L", null, null, null, null));
    out.add(new Language("lid", "Nyindrou", "I", "L", null, null, null, null));
    out.add(new Language("lie", "Likila", "I", "L", null, null, null, null));
    out.add(new Language("lif", "Limbu", "I", "L", null, null, null, null));
    out.add(new Language("lig", "Ligbi", "I", "L", null, null, null, null));
    out.add(new Language("lih", "Lihir", "I", "L", null, null, null, null));
    out.add(new Language("lij", "Ligurian", "I", "L", null, null, null, null));
    out.add(new Language("lik", "Lika", "I", "L", null, null, null, null));
    out.add(new Language("lil", "Lillooet", "I", "L", null, null, null, null));
    out.add(new Language("lim", "Limburgan", "I", "L", "li", null, null, null));
    out.add(new Language("lin", "Lingala", "I", "L", "ln", null, null, null));
    out.add(new Language("lio", "Liki", "I", "L", null, null, null, null));
    out.add(new Language("lip", "Sekpele", "I", "L", null, null, null, null));
    out.add(new Language("liq", "Libido", "I", "L", null, null, null, null));
    out.add(new Language("lir", "Liberian English", "I", "L", null, null, "English, Liberian", null));
    out.add(new Language("lis", "Lisu", "I", "L", null, null, null, null));
    out.add(new Language("lit", "Lithuanian", "I", "L", "lt", null, null, null));
    out.add(new Language("liu", "Logorik", "I", "L", null, null, null, null));
    out.add(new Language("liv", "Liv", "I", "L", null, null, null, null));
    out.add(new Language("liw", "Col", "I", "L", null, null, null, null));
    out.add(new Language("lix", "Liabuku", "I", "L", null, null, null, null));
    out.add(new Language("liy", "Banda-Bambari", "I", "L", null, null, null, null));
    out.add(new Language("liz", "Libinza", "I", "L", null, null, null, null));
    out.add(new Language("lja", "Golpa", "I", "E", null, null, null, null));
    out.add(new Language("lje", "Rampi", "I", "L", null, null, null, null));
    out.add(new Language("lji", "Laiyolo", "I", "L", null, null, null, null));
    out.add(new Language("ljl", "Li'o", "I", "L", null, null, null, null));
    out.add(new Language("ljp", "Lampung Api", "I", "L", null, null, null, null));
    out.add(new Language("ljw", "Yirandali", "I", "L", null, null, null, null));
    out.add(new Language("ljx", "Yuru", "I", "E", null, null, null, null));
    out.add(new Language("lka", "Lakalei", "I", "L", null, null, null, null));
    out.add(new Language("lkb", "Kabras", "I", "L", null, null, null, null));
    out.add(new Language("lkc", "Kucong", "I", "L", null, null, null, null));
    out.add(new Language("lkd", "Lakondê", "I", "L", null, null, null, null));
    out.add(new Language("lke", "Kenyi", "I", "L", null, null, null, null));
    out.add(new Language("lkh", "Lakha", "I", "L", null, null, null, null));
    out.add(new Language("lki", "Laki", "I", "L", null, null, null, null));
    out.add(new Language("lkj", "Remun", "I", "L", null, null, null, null));
    out.add(new Language("lkl", "Laeko-Libuat", "I", "L", null, null, null, null));
    out.add(new Language("lkm", "Kalaamaya", "I", "E", null, null, null, null));
    out.add(new Language("lkn", "Lakon", "I", "L", null, null, null, null));
    out.add(new Language("lko", "Khayo", "I", "L", null, null, null, null));
    out.add(new Language("lkr", "Päri", "I", "L", null, null, null, null));
    out.add(new Language("lks", "Kisa", "I", "L", null, null, null, null));
    out.add(new Language("lkt", "Lakota", "I", "L", null, null, null, null));
    out.add(new Language("lku", "Kungkari", "I", "E", null, null, null, null));
    out.add(new Language("lky", "Lokoya", "I", "L", null, null, null, null));
    out.add(new Language("lla", "Lala-Roba", "I", "L", null, null, null, null));
    out.add(new Language("llb", "Lolo", "I", "L", null, null, null, null));
    out.add(new Language("llc", "Lele (Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("lld", "Ladin", "I", "L", null, null, null, null));
    out.add(new Language("lle", "Lele (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("llf", "Hermit", "I", "E", null, null, null, null));
    out.add(new Language("llg", "Lole", "I", "L", null, null, null, null));
    out.add(new Language("llh", "Lamu", "I", "L", null, null, null, null));
    out.add(new Language("lli", "Teke-Laali", "I", "L", null, null, null, null));
    out.add(new Language("llj", "Ladji Ladji", "I", "E", null, null, null, null));
    out.add(new Language("llk", "Lelak", "I", "E", null, null, null, null));
    out.add(new Language("lll", "Lilau", "I", "L", null, null, null, null));
    out.add(new Language("llm", "Lasalimu", "I", "L", null, null, null, null));
    out.add(new Language("lln", "Lele (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("llp", "North Efate", "I", "L", null, null, "Efate, North", null));
    out.add(new Language("llq", "Lolak", "I", "L", null, null, null, null));
    out.add(new Language("lls", "Lithuanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("llu", "Lau", "I", "L", null, null, null, null));
    out.add(new Language("llx", "Lauan", "I", "L", null, null, null, null));
    out.add(new Language("lma", "East Limba", "I", "L", null, null, "Limba, East", null));
    out.add(new Language("lmb", "Merei", "I", "L", null, null, null, null));
    out.add(new Language("lmc", "Limilngan", "I", "E", null, null, null, null));
    out.add(new Language("lmd", "Lumun", "I", "L", null, null, null, null));
    out.add(new Language("lme", "Pévé", "I", "L", null, null, null, null));
    out.add(new Language("lmf", "South Lembata", "I", "L", null, null, "Lembata, South", null));
    out.add(new Language("lmg", "Lamogai", "I", "L", null, null, null, null));
    out.add(new Language("lmh", "Lambichhong", "I", "L", null, null, null, null));
    out.add(new Language("lmi", "Lombi", "I", "L", null, null, null, null));
    out.add(new Language("lmj", "West Lembata", "I", "L", null, null, "Lembata, West", null));
    out.add(new Language("lmk", "Lamkang", "I", "L", null, null, null, null));
    out.add(new Language("lml", "Hano", "I", "L", null, null, null, null));
    out.add(new Language("lmn", "Lambadi", "I", "L", null, null, null, null));
    out.add(new Language("lmo", "Lombard", "I", "L", null, null, null, null));
    out.add(new Language("lmp", "Limbum", "I", "L", null, null, null, null));
    out.add(new Language("lmq", "Lamatuka", "I", "L", null, null, null, null));
    out.add(new Language("lmr", "Lamalera", "I", "L", null, null, null, null));
    out.add(new Language("lmu", "Lamenu", "I", "L", null, null, null, null));
    out.add(new Language("lmv", "Lomaiviti", "I", "L", null, null, null, null));
    out.add(new Language("lmw", "Lake Miwok", "I", "L", null, null, "Miwok, Lake", null));
    out.add(new Language("lmx", "Laimbue", "I", "L", null, null, null, null));
    out.add(new Language("lmy", "Lamboya", "I", "L", null, null, null, null));
    out.add(new Language("lna", "Langbashe", "I", "L", null, null, null, null));
    out.add(new Language("lnb", "Mbalanhu", "I", "L", null, null, null, null));
    out.add(new Language("lnd", "Lundayeh", "I", "L", null, null, null, null));
    out.add(new Language("lng", "Langobardic", "I", "H", null, null, null, null));
    out.add(new Language("lnh", "Lanoh", "I", "L", null, null, null, null));
    out.add(new Language("lni", "Daantanai'", "I", "L", null, null, null, null));
    out.add(new Language("lnj", "Leningitij", "I", "E", null, null, null, null));
    out.add(new Language("lnl", "South Central Banda", "I", "L", null, null, "Banda, South Central", null));
    out.add(new Language("lnm", "Langam", "I", "L", null, null, null, null));
    out.add(new Language("lnn", "Lorediakarkar", "I", "L", null, null, null, null));
    out.add(new Language("lns", "Lamnso'", "I", "L", null, null, null, null));
    out.add(new Language("lnu", "Longuda", "I", "L", null, null, null, null));
    out.add(new Language("lnw", "Lanima", "I", "E", null, null, null, null));
    out.add(new Language("lnz", "Lonzo", "I", "L", null, null, null, null));
    out.add(new Language("loa", "Loloda", "I", "L", null, null, null, null));
    out.add(new Language("lob", "Lobi", "I", "L", null, null, null, null));
    out.add(new Language("loc", "Inonhan", "I", "L", null, null, null, null));
    out.add(new Language("loe", "Saluan", "I", "L", null, null, null, null));
    out.add(new Language("lof", "Logol", "I", "L", null, null, null, null));
    out.add(new Language("log", "Logo", "I", "L", null, null, null, null));
    out.add(new Language("loh", "Laarim", "I", "L", null, null, null, null));
    out.add(new Language("loi", "Loma (Côte d'Ivoire)", "I", "L", null, null, null, null));
    out.add(new Language("loj", "Lou", "I", "L", null, null, null, null));
    out.add(new Language("lok", "Loko", "I", "L", null, null, null, null));
    out.add(new Language("lol", "Mongo", "I", "L", null, null, null, null));
    out.add(new Language("lom", "Loma (Liberia)", "I", "L", null, null, null, null));
    out.add(new Language("lon", "Malawi Lomwe", "I", "L", null, null, "Lomwe, Malawi", null));
    out.add(new Language("loo", "Lombo", "I", "L", null, null, null, null));
    out.add(new Language("lop", "Lopa", "I", "L", null, null, null, null));
    out.add(new Language("loq", "Lobala", "I", "L", null, null, null, null));
    out.add(new Language("lor", "Téén", "I", "L", null, null, null, null));
    out.add(new Language("los", "Loniu", "I", "L", null, null, null, null));
    out.add(new Language("lot", "Otuho", "I", "L", null, null, null, null));
    out.add(new Language("lou", "Louisiana Creole", "I", "L", null, null, "Creole, Louisiana", null));
    out.add(new Language("lov", "Lopi", "I", "L", null, null, null, null));
    out.add(new Language("low", "Tampias Lobu", "I", "L", null, null, "Lobu, Tampias", null));
    out.add(new Language("lox", "Loun", "I", "L", null, null, null, null));
    out.add(new Language("loy", "Loke", "I", "L", null, null, null, null));
    out.add(new Language("loz", "Lozi", "I", "L", null, null, null, null));
    out.add(new Language("lpa", "Lelepa", "I", "L", null, null, null, null));
    out.add(new Language("lpe", "Lepki", "I", "L", null, null, null, null));
    out.add(new Language("lpn", "Long Phuri Naga", "I", "L", null, null, "Naga, Long Phuri", null));
    out.add(new Language("lpo", "Lipo", "I", "L", null, null, null, null));
    out.add(new Language("lpx", "Lopit", "I", "L", null, null, null, null));
    out.add(new Language("lqr", "Logir", "I", "L", null, null, null, null));
    out.add(new Language("lra", "Rara Bakati'", "I", "L", null, null, null, null));
    out.add(new Language("lrc", "Northern Luri", "I", "L", null, null, "Luri, Northern", null));
    out.add(new Language("lre", "Laurentian", "I", "E", null, null, null, null));
    out.add(new Language("lrg", "Laragia", "I", "E", null, null, null, null));
    out.add(new Language("lri", "Marachi", "I", "L", null, null, null, null));
    out.add(new Language("lrk", "Loarki", "I", "L", null, null, null, null));
    out.add(new Language("lrl", "Lari", "I", "L", null, null, null, null));
    out.add(new Language("lrm", "Marama", "I", "L", null, null, null, null));
    out.add(new Language("lrn", "Lorang", "I", "L", null, null, null, null));
    out.add(new Language("lro", "Laro", "I", "L", null, null, null, null));
    out.add(new Language("lrr", "Southern Yamphu", "I", "L", null, null, "Yamphu, Southern", null));
    out.add(new Language("lrt", "Larantuka Malay", "I", "L", null, null, "Malay, Larantuka", null));
    out.add(new Language("lrv", "Larevat", "I", "L", null, null, null, null));
    out.add(new Language("lrz", "Lemerig", "I", "L", null, null, null, null));
    out.add(new Language("lsa", "Lasgerdi", "I", "L", null, null, null, null));
    out.add(new Language("lsb", "Burundian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsc", "Albarradas Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsd", "Lishana Deni", "I", "L", null, null, null, null));
    out.add(new Language("lse", "Lusengo", "I", "L", null, null, null, null));
    out.add(new Language("lsh", "Lish", "I", "L", null, null, null, null));
    out.add(new Language("lsi", "Lashi", "I", "L", null, null, null, null));
    out.add(new Language("lsl", "Latvian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsm", "Saamia", "I", "L", null, null, null, null));
    out.add(new Language("lsn", "Tibetan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lso", "Laos Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsp", "Panamanian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsr", "Aruop", "I", "L", null, null, null, null));
    out.add(new Language("lss", "Lasi", "I", "L", null, null, null, null));
    out.add(new Language("lst", "Trinidad and Tobago Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsv", "Sivia Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsw", "Seychelles Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lsy", "Mauritian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("ltc", "Late Middle Chinese", "I", "H", null, null, "Chinese, Late Middle", null));
    out.add(new Language("ltg", "Latgalian", "I", "L", null, null, null, null));
    out.add(new Language("lth", "Thur", "I", "L", null, null, null, null));
    out.add(new Language("lti", "Leti (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("ltn", "Latundê", "I", "L", null, null, null, null));
    out.add(new Language("lto", "Tsotso", "I", "L", null, null, null, null));
    out.add(new Language("lts", "Tachoni", "I", "L", null, null, null, null));
    out.add(new Language("ltu", "Latu", "I", "L", null, null, null, null));
    out.add(new Language("ltz", "Luxembourgish", "I", "L", "lb", null, null, null));
    out.add(new Language("lua", "Luba-Lulua", "I", "L", null, null, null, null));
    out.add(new Language("lub", "Luba-Katanga", "I", "L", "lu", null, null, null));
    out.add(new Language("luc", "Aringa", "I", "L", null, null, null, null));
    out.add(new Language("lud", "Ludian", "I", "L", null, null, null, null));
    out.add(new Language("lue", "Luvale", "I", "L", null, null, null, null));
    out.add(new Language("luf", "Laua", "I", "L", null, null, null, null));
    out.add(new Language("lug", "Ganda", "I", "L", "lg", null, null, null));
    out.add(new Language("luh", "Leizhou Chinese", "I", "L", null, null, "Chinese, Leizhou", null));
    out.add(new Language("lui", "Luiseno", "I", "E", null, null, null, null));
    out.add(new Language("luj", "Luna", "I", "L", null, null, null, null));
    out.add(new Language("luk", "Lunanakha", "I", "L", null, null, null, null));
    out.add(new Language("lul", "Olu'bo", "I", "L", null, null, null, null));
    out.add(new Language("lum", "Luimbi", "I", "L", null, null, null, null));
    out.add(new Language("lun", "Lunda", "I", "L", null, null, null, null));
    out.add(new Language("luo", "Luo (Kenya and Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("lup", "Lumbu", "I", "L", null, null, null, null));
    out.add(new Language("luq", "Lucumi", "I", "L", null, null, null, null));
    out.add(new Language("lur", "Laura", "I", "L", null, null, null, null));
    out.add(new Language("lus", "Lushai", "I", "L", null, null, null, null));
    out.add(new Language("lut", "Lushootseed", "I", "E", null, null, null, null));
    out.add(new Language("luu", "Lumba-Yakkha", "I", "L", null, null, null, null));
    out.add(new Language("luv", "Luwati", "I", "L", null, null, null, null));
    out.add(new Language("luw", "Luo (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("luy", "Luyia", "M", "L", null, null, null, null));
    out.add(new Language("luz", "Southern Luri", "I", "L", null, null, "Luri, Southern", null));
    out.add(new Language("lva", "Maku'a", "I", "L", null, null, null, null));
    out.add(new Language("lvi", "Lavi", "I", "L", null, null, null, null));
    out.add(new Language("lvk", "Lavukaleve", "I", "L", null, null, null, null));
    out.add(new Language("lvl", "Lwel", "I", "L", null, null, null, null));
    out.add(new Language("lvs", "Standard Latvian", "I", "L", null, null, "Latvian, Standard", null));
    out.add(new Language("lvu", "Levuka", "I", "L", null, null, null, null));
    out.add(new Language("lwa", "Lwalu", "I", "L", null, null, null, null));
    out.add(new Language("lwe", "Lewo Eleng", "I", "L", null, null, null, null));
    out.add(new Language("lwg", "Wanga", "I", "L", null, null, null, null));
    out.add(new Language("lwh", "White Lachi", "I", "L", null, null, "Lachi, White", null));
    out.add(new Language("lwl", "Eastern Lawa", "I", "L", null, null, "Lawa, Eastern", null));
    out.add(new Language("lwm", "Laomian", "I", "L", null, null, null, null));
    out.add(new Language("lwo", "Luwo", "I", "L", null, null, null, null));
    out.add(new Language("lws", "Malawian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("lwt", "Lewotobi", "I", "L", null, null, null, null));
    out.add(new Language("lwu", "Lawu", "I", "L", null, null, null, null));
    out.add(new Language("lww", "Lewo", "I", "L", null, null, null, null));
    out.add(new Language("lxm", "Lakurumau", "I", "L", null, null, null, null));
    out.add(new Language("lya", "Layakha", "I", "L", null, null, null, null));
    out.add(new Language("lyg", "Lyngngam", "I", "L", null, null, null, null));
    out.add(new Language("lyn", "Luyana", "I", "L", null, null, null, null));
    out.add(new Language("lzh", "Literary Chinese", "I", "H", null, null, "Chinese, Literary", null));
    out.add(new Language("lzl", "Litzlitz", "I", "L", null, null, null, null));
    out.add(new Language("lzn", "Leinong Naga", "I", "L", null, null, "Naga, Leinong", null));
    out.add(new Language("lzz", "Laz", "I", "L", null, null, null, null));
    out.add(new Language("maa", "San Jerónimo Tecóatl Mazatec", "I", "L", null, null, "Mazatec, San Jerónimo Tecóatl", null));
    out.add(new Language("mab", "Yutanduchi Mixtec", "I", "L", null, null, "Mixtec, Yutanduchi", null));
    out.add(new Language("mad", "Madurese", "I", "L", null, null, null, null));
    out.add(new Language("mae", "Bo-Rukul", "I", "L", null, null, null, null));
    out.add(new Language("maf", "Mafa", "I", "L", null, null, null, null));
    out.add(new Language("mag", "Magahi", "I", "L", null, null, null, null));
    out.add(new Language("mah", "Marshallese", "I", "L", "mh", null, null, null));
    out.add(new Language("mai", "Maithili", "I", "L", null, null, null, null));
    out.add(new Language("maj", "Jalapa De Díaz Mazatec", "I", "L", null, null, "Mazatec, Jalapa De Díaz", null));
    out.add(new Language("mak", "Makasar", "I", "L", null, null, null, null));
    out.add(new Language("mal", "Malayalam", "I", "L", "ml", null, null, null));
    out.add(new Language("mam", "Mam", "I", "L", null, null, null, null));
    out.add(new Language("man", "Mandingo", "M", "L", null, null, null, null));
    out.add(new Language("maq", "Chiquihuitlán Mazatec", "I", "L", null, null, "Mazatec, Chiquihuitlán", null));
    out.add(new Language("mar", "Marathi", "I", "L", "mr", null, null, null));
    out.add(new Language("mas", "Masai", "I", "L", null, null, null, null));
    out.add(new Language("mat", "San Francisco Matlatzinca", "I", "L", null, null, "Matlatzinca, San Francisco", null));
    out.add(new Language("mau", "Huautla Mazatec", "I", "L", null, null, "Mazatec, Huautla", null));
    out.add(new Language("mav", "Sateré-Mawé", "I", "L", null, null, null, null));
    out.add(new Language("maw", "Mampruli", "I", "L", null, null, null, null));
    out.add(new Language("max", "North Moluccan Malay", "I", "L", null, null, "Malay, North Moluccan", null));
    out.add(new Language("maz", "Central Mazahua", "I", "L", null, null, "Mazahua, Central", null));
    out.add(new Language("mba", "Higaonon", "I", "L", null, null, null, null));
    out.add(new Language("mbb", "Western Bukidnon Manobo", "I", "L", null, null, "Manobo, Western Bukidnon", null));
    out.add(new Language("mbc", "Macushi", "I", "L", null, null, null, null));
    out.add(new Language("mbd", "Dibabawon Manobo", "I", "L", null, null, "Manobo, Dibabawon", null));
    out.add(new Language("mbe", "Molale", "I", "E", null, null, null, null));
    out.add(new Language("mbf", "Baba Malay", "I", "L", null, null, "Malay, Baba", null));
    out.add(new Language("mbh", "Mangseng", "I", "L", null, null, null, null));
    out.add(new Language("mbi", "Ilianen Manobo", "I", "L", null, null, "Manobo, Ilianen", null));
    out.add(new Language("mbj", "Nadëb", "I", "L", null, null, null, null));
    out.add(new Language("mbk", "Malol", "I", "L", null, null, null, null));
    out.add(new Language("mbl", "Maxakalí", "I", "L", null, null, null, null));
    out.add(new Language("mbm", "Ombamba", "I", "L", null, null, null, null));
    out.add(new Language("mbn", "Macaguán", "I", "L", null, null, null, null));
    out.add(new Language("mbo", "Mbo (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("mbp", "Malayo", "I", "L", null, null, null, null));
    out.add(new Language("mbq", "Maisin", "I", "L", null, null, null, null));
    out.add(new Language("mbr", "Nukak Makú", "I", "L", null, null, null, null));
    out.add(new Language("mbs", "Sarangani Manobo", "I", "L", null, null, "Manobo, Sarangani", null));
    out.add(new Language("mbt", "Matigsalug Manobo", "I", "L", null, null, "Manobo, Matigsalug", null));
    out.add(new Language("mbu", "Mbula-Bwazza", "I", "L", null, null, null, null));
    out.add(new Language("mbv", "Mbulungish", "I", "L", null, null, null, null));
    out.add(new Language("mbw", "Maring", "I", "L", null, null, null, null));
    out.add(new Language("mbx", "Mari (East Sepik Province)", "I", "L", null, null, null, null));
    out.add(new Language("mby", "Memoni", "I", "L", null, null, null, null));
    out.add(new Language("mbz", "Amoltepec Mixtec", "I", "L", null, null, "Mixtec, Amoltepec", null));
    out.add(new Language("mca", "Maca", "I", "L", null, null, null, null));
    out.add(new Language("mcb", "Machiguenga", "I", "L", null, null, null, null));
    out.add(new Language("mcc", "Bitur", "I", "L", null, null, null, null));
    out.add(new Language("mcd", "Sharanahua", "I", "L", null, null, null, null));
    out.add(new Language("mce", "Itundujia Mixtec", "I", "L", null, null, "Mixtec, Itundujia", null));
    out.add(new Language("mcf", "Matsés", "I", "L", null, null, null, null));
    out.add(new Language("mcg", "Mapoyo", "I", "L", null, null, null, null));
    out.add(new Language("mch", "Maquiritari", "I", "L", null, null, null, null));
    out.add(new Language("mci", "Mese", "I", "L", null, null, null, null));
    out.add(new Language("mcj", "Mvanip", "I", "L", null, null, null, null));
    out.add(new Language("mck", "Mbunda", "I", "L", null, null, null, null));
    out.add(new Language("mcl", "Macaguaje", "I", "E", null, null, null, null));
    out.add(new Language("mcm", "Malaccan Creole Portuguese", "I", "L", null, null, "Creole Portuguese, Malaccan", null));
    out.add(new Language("mcn", "Masana", "I", "L", null, null, null, null));
    out.add(new Language("mco", "Coatlán Mixe", "I", "L", null, null, "Mixe, Coatlán", null));
    out.add(new Language("mcp", "Makaa", "I", "L", null, null, null, null));
    out.add(new Language("mcq", "Ese", "I", "L", null, null, null, null));
    out.add(new Language("mcr", "Menya", "I", "L", null, null, null, null));
    out.add(new Language("mcs", "Mambai", "I", "L", null, null, null, null));
    out.add(new Language("mct", "Mengisa", "I", "L", null, null, null, null));
    out.add(new Language("mcu", "Cameroon Mambila", "I", "L", null, null, "Mambila, Cameroon", null));
    out.add(new Language("mcv", "Minanibai", "I", "L", null, null, null, null));
    out.add(new Language("mcw", "Mawa (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("mcx", "Mpiemo", "I", "L", null, null, null, null));
    out.add(new Language("mcy", "South Watut", "I", "L", null, null, "Watut, South", null));
    out.add(new Language("mcz", "Mawan", "I", "L", null, null, null, null));
    out.add(new Language("mda", "Mada (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("mdb", "Morigi", "I", "L", null, null, null, null));
    out.add(new Language("mdc", "Male (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("mdd", "Mbum", "I", "L", null, null, null, null));
    out.add(new Language("mde", "Maba (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("mdf", "Moksha", "I", "L", null, null, null, null));
    out.add(new Language("mdg", "Massalat", "I", "L", null, null, null, null));
    out.add(new Language("mdh", "Maguindanaon", "I", "L", null, null, null, null));
    out.add(new Language("mdi", "Mamvu", "I", "L", null, null, null, null));
    out.add(new Language("mdj", "Mangbetu", "I", "L", null, null, null, null));
    out.add(new Language("mdk", "Mangbutu", "I", "L", null, null, null, null));
    out.add(new Language("mdl", "Maltese Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mdm", "Mayogo", "I", "L", null, null, null, null));
    out.add(new Language("mdn", "Mbati", "I", "L", null, null, null, null));
    out.add(new Language("mdp", "Mbala", "I", "L", null, null, null, null));
    out.add(new Language("mdq", "Mbole", "I", "L", null, null, null, null));
    out.add(new Language("mdr", "Mandar", "I", "L", null, null, null, null));
    out.add(new Language("mds", "Maria (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("mdt", "Mbere", "I", "L", null, null, null, null));
    out.add(new Language("mdu", "Mboko", "I", "L", null, null, null, null));
    out.add(new Language("mdv", "Santa Lucía Monteverde Mixtec", "I", "L", null, null, "Mixtec, Santa Lucía Monteverde", null));
    out.add(new Language("mdw", "Mbosi", "I", "L", null, null, null, null));
    out.add(new Language("mdx", "Dizin", "I", "L", null, null, null, null));
    out.add(new Language("mdy", "Male (Ethiopia)", "I", "L", null, null, null, null));
    out.add(new Language("mdz", "Suruí Do Pará", "I", "L", null, null, null, null));
    out.add(new Language("mea", "Menka", "I", "L", null, null, null, null));
    out.add(new Language("meb", "Ikobi", "I", "L", null, null, null, null));
    out.add(new Language("mec", "Marra", "I", "L", null, null, null, null));
    out.add(new Language("med", "Melpa", "I", "L", null, null, null, null));
    out.add(new Language("mee", "Mengen", "I", "L", null, null, null, null));
    out.add(new Language("mef", "Megam", "I", "L", null, null, null, null));
    out.add(new Language("meh", "Southwestern Tlaxiaco Mixtec", "I", "L", null, null, "Mixtec, Southwestern Tlaxiaco", null));
    out.add(new Language("mei", "Midob", "I", "L", null, null, null, null));
    out.add(new Language("mej", "Meyah", "I", "L", null, null, null, null));
    out.add(new Language("mek", "Mekeo", "I", "L", null, null, null, null));
    out.add(new Language("mel", "Central Melanau", "I", "L", null, null, "Melanau, Central", null));
    out.add(new Language("mem", "Mangala", "I", "E", null, null, null, null));
    out.add(new Language("men", "Mende (Sierra Leone)", "I", "L", null, null, null, null));
    out.add(new Language("meo", "Kedah Malay", "I", "L", null, null, "Malay, Kedah", null));
    out.add(new Language("mep", "Miriwoong", "I", "L", null, null, null, null));
    out.add(new Language("meq", "Merey", "I", "L", null, null, null, null));
    out.add(new Language("mer", "Meru", "I", "L", null, null, null, null));
    out.add(new Language("mes", "Masmaje", "I", "L", null, null, null, null));
    out.add(new Language("met", "Mato", "I", "L", null, null, null, null));
    out.add(new Language("meu", "Motu", "I", "L", null, null, null, null));
    out.add(new Language("mev", "Mano", "I", "L", null, null, null, null));
    out.add(new Language("mew", "Maaka", "I", "L", null, null, null, null));
    out.add(new Language("mey", "Hassaniyya", "I", "L", null, null, null, null));
    out.add(new Language("mez", "Menominee", "I", "L", null, null, null, null));
    out.add(new Language("mfa", "Pattani Malay", "I", "L", null, null, "Malay, Pattani", null));
    out.add(new Language("mfb", "Bangka", "I", "L", null, null, null, null));
    out.add(new Language("mfc", "Mba", "I", "L", null, null, null, null));
    out.add(new Language("mfd", "Mendankwe-Nkwen", "I", "L", null, null, null, null));
    out.add(new Language("mfe", "Morisyen", "I", "L", null, null, null, null));
    out.add(new Language("mff", "Naki", "I", "L", null, null, null, null));
    out.add(new Language("mfg", "Mogofin", "I", "L", null, null, null, null));
    out.add(new Language("mfh", "Matal", "I", "L", null, null, null, null));
    out.add(new Language("mfi", "Wandala", "I", "L", null, null, null, null));
    out.add(new Language("mfj", "Mefele", "I", "L", null, null, null, null));
    out.add(new Language("mfk", "North Mofu", "I", "L", null, null, "Mofu, North", null));
    out.add(new Language("mfl", "Putai", "I", "L", null, null, null, null));
    out.add(new Language("mfm", "Marghi South", "I", "L", null, null, null, null));
    out.add(new Language("mfn", "Cross River Mbembe", "I", "L", null, null, "Mbembe, Cross River", null));
    out.add(new Language("mfo", "Mbe", "I", "L", null, null, null, null));
    out.add(new Language("mfp", "Makassar Malay", "I", "L", null, null, "Malay, Makassar", null));
    out.add(new Language("mfq", "Moba", "I", "L", null, null, null, null));
    out.add(new Language("mfr", "Marrithiyel", "I", "L", null, null, null, null));
    out.add(new Language("mfs", "Mexican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mft", "Mokerang", "I", "L", null, null, null, null));
    out.add(new Language("mfu", "Mbwela", "I", "L", null, null, null, null));
    out.add(new Language("mfv", "Mandjak", "I", "L", null, null, null, null));
    out.add(new Language("mfw", "Mulaha", "I", "E", null, null, null, null));
    out.add(new Language("mfx", "Melo", "I", "L", null, null, null, null));
    out.add(new Language("mfy", "Mayo", "I", "L", null, null, null, null));
    out.add(new Language("mfz", "Mabaan", "I", "L", null, null, null, null));
    out.add(new Language("mga", "Middle Irish (900-1200)", "I", "H", null, null, "Irish, Middle (900-1200)", null));
    out.add(new Language("mgb", "Mararit", "I", "L", null, null, null, null));
    out.add(new Language("mgc", "Morokodo", "I", "L", null, null, null, null));
    out.add(new Language("mgd", "Moru", "I", "L", null, null, null, null));
    out.add(new Language("mge", "Mango", "I", "L", null, null, null, null));
    out.add(new Language("mgf", "Maklew", "I", "L", null, null, null, null));
    out.add(new Language("mgg", "Mpumpong", "I", "L", null, null, null, null));
    out.add(new Language("mgh", "Makhuwa-Meetto", "I", "L", null, null, null, null));
    out.add(new Language("mgi", "Lijili", "I", "L", null, null, null, null));
    out.add(new Language("mgj", "Abureni", "I", "L", null, null, null, null));
    out.add(new Language("mgk", "Mawes", "I", "L", null, null, null, null));
    out.add(new Language("mgl", "Maleu-Kilenge", "I", "L", null, null, null, null));
    out.add(new Language("mgm", "Mambae", "I", "L", null, null, null, null));
    out.add(new Language("mgn", "Mbangi", "I", "L", null, null, null, null));
    out.add(new Language("mgo", "Meta'", "I", "L", null, null, null, null));
    out.add(new Language("mgp", "Eastern Magar", "I", "L", null, null, "Magar, Eastern", null));
    out.add(new Language("mgq", "Malila", "I", "L", null, null, null, null));
    out.add(new Language("mgr", "Mambwe-Lungu", "I", "L", null, null, null, null));
    out.add(new Language("mgs", "Manda (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("mgt", "Mongol", "I", "L", null, null, null, null));
    out.add(new Language("mgu", "Mailu", "I", "L", null, null, null, null));
    out.add(new Language("mgv", "Matengo", "I", "L", null, null, null, null));
    out.add(new Language("mgw", "Matumbi", "I", "L", null, null, null, null));
    out.add(new Language("mgy", "Mbunga", "I", "L", null, null, null, null));
    out.add(new Language("mgz", "Mbugwe", "I", "L", null, null, null, null));
  }
}
