// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 1000 to 1499 of {@link Language}.
 */
final class LanguageData2 {
  private LanguageData2() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("buf", "Bushoong", "I", "L", null, null, null, null));
    out.add(new Language("bug", "Buginese", "I", "L", null, null, null, null));
    out.add(new Language("buh", "Younuo Bunu", "I", "L", null, null, "Bunu, Younuo", null));
    out.add(new Language("bui", "Bongili", "I", "L", null, null, null, null));
    out.add(new Language("buj", "Basa-Gurmana", "I", "L", null, null, null, null));
    out.add(new Language("buk", "Bugawac", "I", "L", null, null, null, null));
    out.add(new Language("bul", "Bulgarian", "I", "L", "bg", null, null, null));
    out.add(new Language("bum", "Bulu (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("bun", "Sherbro", "I", "L", null, null, null, null));
    out.add(new Language("buo", "Terei", "I", "L", null, null, null, null));
    out.add(new Language("bup", "Busoa", "I", "L", null, null, null, null));
    out.add(new Language("buq", "Brem", "I", "L", null, null, null, null));
    out.add(new Language("bus", "Bokobaru", "I", "L", null, null, null, null));
    out.add(new Language("but", "Bungain", "I", "L", null, null, null, null));
    out.add(new Language("buu", "Budu", "I", "L", null, null, null, null));
    out.add(new Language("buv", "Bun", "I", "L", null, null, null, null));
    out.add(new Language("buw", "Bubi", "I", "L", null, null, null, null));
    out.add(new Language("bux", "Boghom", "I", "L", null, null, null, null));
    out.add(new Language("buy", "Bullom So", "I", "L", null, null, null, null));
    out.add(new Language("buz", "Bukwen", "I", "L", null, null, null, null));
    out.add(new Language("bva", "Barein", "I", "L", null, null, null, null));
    out.add(new Language("bvb", "Bube", "I", "L", null, null, null, null));
    out.add(new Language("bvc", "Baelelea", "I", "L", null, null, null, null));
    out.add(new Language("bvd", "Baeggu", "I", "L", null, null, null, null));
    out.add(new Language("bve", "Berau Malay", "I", "L", null, null, "Malay, Berau", null));
    out.add(new Language("bvf", "Boor", "I", "L", null, null, null, null));
    out.add(new Language("bvg", "Bonkeng", "I", "L", null, null, null, null));
    out.add(new Language("bvh", "Bure", "I", "L", null, null, null, null));
    out.add(new Language("bvi", "Belanda Viri", "I", "L", null, null, null, null));
    out.add(new Language("bvj", "Baan", "I", "L", null, null, null, null));
    out.add(new Language("bvk", "Bukat", "I", "L", null, null, null, null));
    out.add(new Language("bvl", "Bolivian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bvm", "Bamunka", "I", "L", null, null, null, null));
    out.add(new Language("bvn", "Buna", "I", "L", null, null, null, null));
    out.add(new Language("bvo", "Bolgo", "I", "L", null, null, null, null));
    out.add(new Language("bvp", "Bumang", "I", "L", null, null, null, null));
    out.add(new Language("bvq", "Birri", "I", "L", null, null, null, null));
    out.add(new Language("bvr", "Burarra", "I", "L", null, null, null, null));
    out.add(new Language("bvt", "Bati (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("bvu", "Bukit Malay", "I", "L", null, null, "Malay, Bukit", null));
    out.add(new Language("bvv", "Baniva", "I", "E", null, null, null, null));
    out.add(new Language("bvw", "Boga", "I", "L", null, null, null, null));
    out.add(new Language("bvx", "Dibole", "I", "L", null, null, null, null));
    out.add(new Language("bvy", "Baybayanon", "I", "L", null, null, null, null));
    out.add(new Language("bvz", "Bauzi", "I", "L", null, null, null, null));
    out.add(new Language("bwa", "Bwatoo", "I", "L", null, null, null, null));
    out.add(new Language("bwb", "Namosi-Naitasiri-Serua", "I", "L", null, null, null, null));
    out.add(new Language("bwc", "Bwile", "I", "L", null, null, null, null));
    out.add(new Language("bwd", "Bwaidoka", "I", "L", null, null, null, null));
    out.add(new Language("bwe", "Bwe Karen", "I", "L", null, null, "Karen, Bwe", null));
    out.add(new Language("bwf", "Boselewa", "I", "L", null, null, null, null));
    out.add(new Language("bwg", "Barwe", "I", "L", null, null, null, null));
    out.add(new Language("bwh", "Bishuo", "I", "L", null, null, null, null));
    out.add(new Language("bwi", "Baniwa", "I", "L", null, null, null, null));
    out.add(new Language("bwj", "Láá Láá Bwamu", "I", "L", null, null, "Bwamu, Láá Láá", null));
    out.add(new Language("bwk", "Bauwaki", "I", "L", null, null, null, null));
    out.add(new Language("bwl", "Bwela", "I", "L", null, null, null, null));
    out.add(new Language("bwm", "Biwat", "I", "L", null, null, null, null));
    out.add(new Language("bwn", "Wunai Bunu", "I", "L", null, null, "Bunu, Wunai", null));
    out.add(new Language("bwo", "Boro (Ethiopia)", "I", "L", null, null, null, null));
    out.add(new Language("bwp", "Mandobo Bawah", "I", "L", null, null, null, null));
    out.add(new Language("bwq", "Southern Bobo Madaré", "I", "L", null, null, "Bobo Madaré, Southern", null));
    out.add(new Language("bwr", "Bura-Pabir", "I", "L", null, null, null, null));
    out.add(new Language("bws", "Bomboma", "I", "L", null, null, null, null));
    out.add(new Language("bwt", "Bafaw-Balong", "I", "L", null, null, null, null));
    out.add(new Language("bwu", "Buli (Ghana)", "I", "L", null, null, null, null));
    out.add(new Language("bww", "Bwa", "I", "L", null, null, null, null));
    out.add(new Language("bwx", "Bu-Nao Bunu", "I", "L", null, null, "Bunu, Bu-Nao", null));
    out.add(new Language("bwy", "Cwi Bwamu", "I", "L", null, null, "Bwamu, Cwi", null));
    out.add(new Language("bwz", "Bwisi", "I", "L", null, null, null, null));
    out.add(new Language("bxa", "Tairaha", "I", "L", null, null, null, null));
    out.add(new Language("bxb", "Belanda Bor", "I", "L", null, null, "Bor, Belanda", null));
    out.add(new Language("bxc", "Molengue", "I", "L", null, null, null, null));
    out.add(new Language("bxd", "Pela", "I", "L", null, null, null, null));
    out.add(new Language("bxe", "Birale", "I", "L", null, null, null, null));
    out.add(new Language("bxf", "Bilur", "I", "L", null, null, null, null));
    out.add(new Language("bxg", "Bangala", "I", "L", null, null, null, null));
    out.add(new Language("bxh", "Buhutu", "I", "L", null, null, null, null));
    out.add(new Language("bxi", "Pirlatapa", "I", "E", null, null, null, null));
    out.add(new Language("bxj", "Bayungu", "I", "L", null, null, null, null));
    out.add(new Language("bxk", "Bukusu", "I", "L", null, null, null, null));
    out.add(new Language("bxl", "Jalkunan", "I", "L", null, null, null, null));
    out.add(new Language("bxm", "Mongolia Buriat", "I", "L", null, null, "Buriat, Mongolia", null));
    out.add(new Language("bxn", "Burduna", "I", "L", null, null, null, null));
    out.add(new Language("bxo", "Barikanchi", "I", "L", null, null, null, null));
    out.add(new Language("bxp", "Bebil", "I", "L", null, null, null, null));
    out.add(new Language("bxq", "Beele", "I", "L", null, null, null, null));
    out.add(new Language("bxr", "Russia Buriat", "I", "L", null, null, "Buriat, Russia", null));
    out.add(new Language("bxs", "Busam", "I", "L", null, null, null, null));
    out.add(new Language("bxu", "China Buriat", "I", "L", null, null, "Buriat, China", null));
    out.add(new Language("bxv", "Berakou", "I", "L", null, null, null, null));
    out.add(new Language("bxw", "Bankagooma", "I", "L", null, null, null, null));
    out.add(new Language("bxz", "Binahari", "I", "L", null, null, null, null));
    out.add(new Language("bya", "Batak", "I", "L", null, null, null, null));
    out.add(new Language("byb", "Bikya", "I", "L", null, null, null, null));
    out.add(new Language("byc", "Ubaghara", "I", "L", null, null, null, null));
    out.add(new Language("byd", "Benyadu'", "I", "L", null, null, null, null));
    out.add(new Language("bye", "Pouye", "I", "L", null, null, null, null));
    out.add(new Language("byf", "Bete", "I", "L", null, null, null, null));
    out.add(new Language("byg", "Baygo", "I", "E", null, null, null, null));
    out.add(new Language("byh", "Bhujel", "I", "L", null, null, null, null));
    out.add(new Language("byi", "Buyu", "I", "L", null, null, null, null));
    out.add(new Language("byj", "Bina (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("byk", "Biao", "I", "L", null, null, null, null));
    out.add(new Language("byl", "Bayono", "I", "L", null, null, null, null));
    out.add(new Language("bym", "Bidjara", "I", "L", null, null, null, null));
    out.add(new Language("byn", "Bilin", "I", "L", null, null, null, null));
    out.add(new Language("byo", "Biyo", "I", "L", null, null, null, null));
    out.add(new Language("byp", "Bumaji", "I", "L", null, null, null, null));
    out.add(new Language("byq", "Basay", "I", "E", null, null, null, null));
    out.add(new Language("byr", "Baruya", "I", "L", null, null, null, null));
    out.add(new Language("bys", "Burak", "I", "L", null, null, null, null));
    out.add(new Language("byt", "Berti", "I", "E", null, null, null, null));
    out.add(new Language("byv", "Medumba", "I", "L", null, null, null, null));
    out.add(new Language("byw", "Belhariya", "I", "L", null, null, null, null));
    out.add(new Language("byx", "Qaqet", "I", "L", null, null, null, null));
    out.add(new Language("byz", "Banaro", "I", "L", null, null, null, null));
    out.add(new Language("bza", "Bandi", "I", "L", null, null, null, null));
    out.add(new Language("bzb", "Andio", "I", "L", null, null, null, null));
    out.add(new Language("bzc", "Southern Betsimisaraka Malagasy", "I", "L", null, null, "Malagasy, Southern Betsimisaraka", null));
    out.add(new Language("bzd", "Bribri", "I", "L", null, null, null, null));
    out.add(new Language("bze", "Jenaama Bozo", "I", "L", null, null, "Bozo, Jenaama", null));
    out.add(new Language("bzf", "Boikin", "I", "L", null, null, null, null));
    out.add(new Language("bzg", "Babuza", "I", "L", null, null, null, null));
    out.add(new Language("bzh", "Mapos Buang", "I", "L", null, null, "Buang, Mapos", null));
    out.add(new Language("bzi", "Bisu", "I", "L", null, null, null, null));
    out.add(new Language("bzj", "Belize Kriol English", "I", "L", null, null, "Kriol English, Belize", null));
    out.add(new Language("bzk", "Nicaragua Creole English", "I", "L", null, null, "Creole English, Nicaragua", null));
    out.add(new Language("bzl", "Boano (Sulawesi)", "I", "L", null, null, null, null));
    out.add(new Language("bzm", "Bolondo", "I", "L", null, null, null, null));
    out.add(new Language("bzn", "Boano (Maluku)", "I", "L", null, null, null, null));
    out.add(new Language("bzo", "Bozaba", "I", "L", null, null, null, null));
    out.add(new Language("bzp", "Kemberano", "I", "L", null, null, null, null));
    out.add(new Language("bzq", "Buli (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("bzr", "Biri", "I", "E", null, null, null, null));
    out.add(new Language("bzs", "Brazilian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("bzt", "Brithenig", "I", "C", null, null, null, null));
    out.add(new Language("bzu", "Burmeso", "I", "L", null, null, null, null));
    out.add(new Language("bzv", "Naami", "I", "L", null, null, null, null));
    out.add(new Language("bzw", "Basa (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("bzx", "Kɛlɛngaxo Bozo", "I", "L", null, null, "Bozo, Kɛlɛngaxo", null));
    out.add(new Language("bzy", "Obanliku", "I", "L", null, null, null, null));
    out.add(new Language("bzz", "Evant", "I", "L", null, null, null, null));
    out.add(new Language("caa", "Chortí", "I", "L", null, null, null, null));
    out.add(new Language("cab", "Garifuna", "I", "L", null, null, null, null));
    out.add(new Language("cac", "Chuj", "I", "L", null, null, null, null));
    out.add(new Language("cad", "Caddo", "I", "L", null, null, null, null));
    out.add(new Language("cae", "Lehar", "I", "L", null, null, null, null));
    out.add(new Language("caf", "Southern Carrier", "I", "L", null, null, "Carrier, Southern", null));
    out.add(new Language("cag", "Nivaclé", "I", "L", null, null, null, null));
    out.add(new Language("cah", "Cahuarano", "I", "L", null, null, null, null));
    out.add(new Language("caj", "Chané", "I", "E", null, null, null, null));
    out.add(new Language("cak", "Kaqchikel", "I", "L", null, null, null, null));
    out.add(new Language("cal", "Carolinian", "I", "L", null, null, null, null));
    out.add(new Language("cam", "Cemuhî", "I", "L", null, null, null, null));
    out.add(new Language("can", "Chambri", "I", "L", null, null, null, null));
    out.add(new Language("cao", "Chácobo", "I", "L", null, null, null, null));
    out.add(new Language("cap", "Chipaya", "I", "L", null, null, null, null));
    out.add(new Language("caq", "Car Nicobarese", "I", "L", null, null, "Nicobarese, Car", null));
    out.add(new Language("car", "Galibi Carib", "I", "L", null, null, "Carib, Galibi", null));
    out.add(new Language("cas", "Tsimané", "I", "L", null, null, null, null));
    out.add(new Language("cat", "Catalan", "I", "L", "ca", null, null, null));
    out.add(new Language("cav", "Cavineña", "I", "L", null, null, null, null));
    out.add(new Language("caw", "Callawalla", "I", "L", null, null, null, null));
    out.add(new Language("cax", "Chiquitano", "I", "L", null, null, null, null));
    out.add(new Language("cay", "Cayuga", "I", "L", null, null, null, null));
    out.add(new Language("caz", "Canichana", "I", "E", null, null, null, null));
    out.add(new Language("cbb", "Cabiyarí", "I", "L", null, null, null, null));
    out.add(new Language("cbc", "Carapana", "I", "L", null, null, null, null));
    out.add(new Language("cbd", "Carijona", "I", "L", null, null, null, null));
    out.add(new Language("cbg", "Chimila", "I", "L", null, null, null, null));
    out.add(new Language("cbi", "Chachi", "I", "L", null, null, null, null));
    out.add(new Language("cbj", "Ede Cabe", "I", "L", null, null, null, null));
    out.add(new Language("cbk", "Chavacano", "I", "L", null, null, null, null));
    out.add(new Language("cbl", "Bualkhaw Chin", "I", "L", null, null, "Chin, Bualkhaw", null));
    out.add(new Language("cbn", "Nyahkur", "I", "L", null, null, null, null));
    out.add(new Language("cbo", "Izora", "I", "L", null, null, null, null));
    out.add(new Language("cbq", "Tsucuba", "I", "L", null, null, null, null));
    out.add(new Language("cbr", "Cashibo-Cacataibo", "I", "L", null, null, null, null));
    out.add(new Language("cbs", "Cashinahua", "I", "L", null, null, null, null));
    out.add(new Language("cbt", "Chayahuita", "I", "L", null, null, null, null));
    out.add(new Language("cbu", "Candoshi-Shapra", "I", "L", null, null, null, null));
    out.add(new Language("cbv", "Cacua", "I", "L", null, null, null, null));
    out.add(new Language("cbw", "Kinabalian", "I", "L", null, null, null, null));
    out.add(new Language("cby", "Carabayo", "I", "L", null, null, null, null));
    out.add(new Language("ccc", "Chamicuro", "I", "L", null, null, null, null));
    out.add(new Language("ccd", "Cafundo Creole", "I", "L", null, null, "Creole, Cafundo", null));
    out.add(new Language("cce", "Chopi", "I", "L", null, null, null, null));
    out.add(new Language("ccg", "Samba Daka", "I", "L", null, null, "Daka, Samba", null));
    out.add(new Language("cch", "Atsam", "I", "L", null, null, null, null));
    out.add(new Language("ccj", "Kasanga", "I", "L", null, null, null, null));
    out.add(new Language("ccl", "Cutchi-Swahili", "I", "L", null, null, null, null));
    out.add(new Language("ccm", "Malaccan Creole Malay", "I", "L", null, null, "Creole Malay, Malaccan", null));
    out.add(new Language("cco", "Comaltepec Chinantec", "I", "L", null, null, "Chinantec, Comaltepec", null));
    out.add(new Language("ccp", "Chakma", "I", "L", null, null, null, null));
    out.add(new Language("ccr", "Cacaopera", "I", "E", null, null, null, null));
    out.add(new Language("cda", "Choni", "I", "L", null, null, null, null));
    out.add(new Language("cde", "Chenchu", "I", "L", null, null, null, null));
    out.add(new Language("cdf", "Chiru", "I", "L", null, null, null, null));
    out.add(new Language("cdh", "Chambeali", "I", "L", null, null, null, null));
    out.add(new Language("cdi", "Chodri", "I", "L", null, null, null, null));
    out.add(new Language("cdj", "Churahi", "I", "L", null, null, null, null));
    out.add(new Language("cdm", "Chepang", "I", "L", null, null, null, null));
    out.add(new Language("cdn", "Chaudangsi", "I", "L", null, null, null, null));
    out.add(new Language("cdo", "Min Dong Chinese", "I", "L", null, null, "Chinese, Min Dong", null));
    out.add(new Language("cdr", "Cinda-Regi-Tiyal", "I", "L", null, null, null, null));
    out.add(new Language("cds", "Chadian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("cdy", "Chadong", "I", "L", null, null, null, null));
    out.add(new Language("cdz", "Koda", "I", "L", null, null, null, null));
    out.add(new Language("cea", "Lower Chehalis", "I", "E", null, null, "Chehalis, Lower", null));
    out.add(new Language("ceb", "Cebuano", "I", "L", null, null, null, null));
    out.add(new Language("ceg", "Chamacoco", "I", "L", null, null, null, null));
    out.add(new Language("cek", "Eastern Khumi Chin", "I", "L", null, null, "Chin, Eastern Khumi", null));
    out.add(new Language("cen", "Cen", "I", "L", null, null, null, null));
    out.add(new Language("ces", "Czech", "I", "L", "cs", null, null, "cze"));
    out.add(new Language("cet", "Centúúm", "I", "L", null, null, null, null));
    out.add(new Language("cey", "Ekai Chin", "I", "L", null, null, "Chin, Ekai", null));
    out.add(new Language("cfa", "Dijim-Bwilim", "I", "L", null, null, null, null));
    out.add(new Language("cfd", "Cara", "I", "L", null, null, null, null));
    out.add(new Language("cfg", "Como Karim", "I", "L", null, null, null, null));
    out.add(new Language("cfm", "Falam Chin", "I", "L", null, null, "Chin, Falam", null));
    out.add(new Language("cga", "Changriwa", "I", "L", null, null, null, null));
    out.add(new Language("cgc", "Kagayanen", "I", "L", null, null, null, null));
    out.add(new Language("cgg", "Chiga", "I", "L", null, null, null, null));
    out.add(new Language("cgk", "Chocangacakha", "I", "L", null, null, null, null));
    out.add(new Language("cha", "Chamorro", "I", "L", "ch", null, null, null));
    out.add(new Language("chb", "Chibcha", "I", "E", null, null, null, null));
    out.add(new Language("chc", "Catawba", "I", "E", null, null, null, null));
    out.add(new Language("chd", "Highland Oaxaca Chontal", "I", "L", null, null, "Chontal, Highland Oaxaca", null));
    out.add(new Language("che", "Chechen", "I", "L", "ce", null, null, null));
    out.add(new Language("chf", "Tabasco Chontal", "I", "L", null, null, "Chontal, Tabasco", null));
    out.add(new Language("chg", "Chagatai", "I", "E", null, null, null, null));
    out.add(new Language("chh", "Chinook", "I", "E", null, null, null, null));
    out.add(new Language("chj", "Ojitlán Chinantec", "I", "L", null, null, "Chinantec, Ojitlán", null));
    out.add(new Language("chk", "Chuukese", "I", "L", null, null, null, null));
    out.add(new Language("chl", "Cahuilla", "I", "L", null, null, null, null));
    out.add(new Language("chm", "Mari (Russia)", "M", "L", null, null, null, null));
    out.add(new Language("chn", "Chinook jargon", "I", "L", null, null, null, null));
    out.add(new Language("cho", "Choctaw", "I", "L", null, null, null, null));
    out.add(new Language("chp", "Chipewyan", "I", "L", null, null, null, null));
    out.add(new Language("chq", "Quiotepec Chinantec", "I", "L", null, null, "Chinantec, Quiotepec", null));
    out.add(new Language("chr", "Cherokee", "I", "L", null, null, null, null));
    out.add(new Language("cht", "Cholón", "I", "E", null, null, null, null));
    out.add(new Language("chu", "Church Slavic", "I", "H", "cu", null, "Slavic, Church", null));
    out.add(new Language("chv", "Chuvash", "I", "L", "cv", null, null, null));
    out.add(new Language("chw", "Chuwabu", "I", "L", null, null, null, null));
    out.add(new Language("chx", "Chantyal", "I", "L", null, null, null, null));
    out.add(new Language("chy", "Cheyenne", "I", "L", null, null, null, null));
    out.add(new Language("chz", "Ozumacín Chinantec", "I", "L", null, null, "Chinantec, Ozumacín", null));
    out.add(new Language("cia", "Cia-Cia", "I", "L", null, null, null, null));
    out.add(new Language("cib", "Ci Gbe", "I", "L", null, null, "Gbe, Ci", null));
    out.add(new Language("cic", "Chickasaw", "I", "L", null, null, null, null));
    out.add(new Language("cid", "Chimariko", "I", "E", null, null, null, null));
    out.add(new Language("cie", "Cineni", "I", "L", null, null, null, null));
    out.add(new Language("cih", "Chinali", "I", "L", null, null, null, null));
    out.add(new Language("cik", "Chitkuli Kinnauri", "I", "L", null, null, "Kinnauri, Chitkuli", null));
    out.add(new Language("cim", "Cimbrian", "I", "L", null, null, null, null));
    out.add(new Language("cin", "Cinta Larga", "I", "L", null, null, null, null));
    out.add(new Language("cip", "Chiapanec", "I", "L", null, null, null, null));
    out.add(new Language("cir", "Tiri", "I", "L", null, null, null, null));
    out.add(new Language("ciw", "Chippewa", "I", "L", null, null, null, null));
    out.add(new Language("ciy", "Chaima", "I", "L", null, null, null, null));
    out.add(new Language("cja", "Western Cham", "I", "L", null, null, "Cham, Western", null));
    out.add(new Language("cje", "Chru", "I", "L", null, null, null, null));
    out.add(new Language("cjh", "Upper Chehalis", "I", "E", null, null, "Chehalis, Upper", null));
    out.add(new Language("cji", "Chamalal", "I", "L", null, null, null, null));
    out.add(new Language("cjk", "Chokwe", "I", "L", null, null, null, null));
    out.add(new Language("cjm", "Eastern Cham", "I", "L", null, null, "Cham, Eastern", null));
    out.add(new Language("cjn", "Chenapian", "I", "L", null, null, null, null));
    out.add(new Language("cjo", "Ashéninka Pajonal", "I", "L", null, null, null, null));
    out.add(new Language("cjp", "Cabécar", "I", "L", null, null, null, null));
    out.add(new Language("cjs", "Shor", "I", "L", null, null, null, null));
    out.add(new Language("cjv", "Chuave", "I", "L", null, null, null, null));
    out.add(new Language("cjy", "Jinyu Chinese", "I", "L", null, null, "Chinese, Jinyu", null));
    out.add(new Language("ckb", "Central Kurdish", "I", "L", null, null, "Kurdish, Central", null));
    out.add(new Language("ckh", "Chak", "I", "L", null, null, null, null));
    out.add(new Language("ckl", "Cibak", "I", "L", null, null, null, null));
    out.add(new Language("ckm", "Chakavian", "I", "L", null, null, null, null));
    out.add(new Language("ckn", "Kaang Chin", "I", "L", null, null, "Chin, Kaang", null));
    out.add(new Language("cko", "Anufo", "I", "L", null, null, null, null));
    out.add(new Language("ckq", "Kajakse", "I", "L", null, null, null, null));
    out.add(new Language("ckr", "Kairak", "I", "L", null, null, null, null));
    out.add(new Language("cks", "Tayo", "I", "L", null, null, null, null));
    out.add(new Language("ckt", "Chukot", "I", "L", null, null, null, null));
    out.add(new Language("cku", "Koasati", "I", "L", null, null, null, null));
    out.add(new Language("ckv", "Kavalan", "I", "L", null, null, null, null));
    out.add(new Language("ckx", "Caka", "I", "L", null, null, null, null));
    out.add(new Language("cky", "Cakfem-Mushere", "I", "L", null, null, null, null));
    out.add(new Language("ckz", "Cakchiquel-Quiché Mixed Language", "I", "L", null, null, null, null));
    out.add(new Language("cla", "Ron", "I", "L", null, null, null, null));
    out.add(new Language("clc", "Chilcotin", "I", "L", null, null, null, null));
    out.add(new Language("cld", "Chaldean Neo-Aramaic", "I", "L", null, null, "Neo-Aramaic, Chaldean", null));
    out.add(new Language("cle", "Lealao Chinantec", "I", "L", null, null, "Chinantec, Lealao", null));
    out.add(new Language("clh", "Chilisso", "I", "L", null, null, null, null));
    out.add(new Language("cli", "Chakali", "I", "L", null, null, null, null));
    out.add(new Language("clj", "Laitu Chin", "I", "L", null, null, "Chin, Laitu", null));
    out.add(new Language("clk", "Idu-Mishmi", "I", "L", null, null, null, null));
    out.add(new Language("cll", "Chala", "I", "L", null, null, null, null));
    out.add(new Language("clm", "Klallam", "I", "L", null, null, null, null));
    out.add(new Language("clo", "Lowland Oaxaca Chontal", "I", "L", null, null, "Chontal, Lowland Oaxaca", null));
    out.add(new Language("cls", "Classical Sanskrit", "I", "H", null, null, null, null));
    out.add(new Language("clt", "Lautu Chin", "I", "L", null, null, "Chin, Lautu", null));
    out.add(new Language("clu", "Caluyanun", "I", "L", null, null, null, null));
    out.add(new Language("clw", "Chulym", "I", "L", null, null, null, null));
    out.add(new Language("cly", "Eastern Highland Chatino", "I", "L", null, null, "Chatino, Eastern Highland", null));
    out.add(new Language("cma", "Maa", "I", "L", null, null, null, null));
    out.add(new Language("cme", "Cerma", "I", "L", null, null, null, null));
    out.add(new Language("cmg", "Classical Mongolian", "I", "H", null, null, "Mongolian, Classical", null));
    out.add(new Language("cmi", "Emberá-Chamí", "I", "L", null, null, null, null));
    out.add(new Language("cml", "Campalagian", "I", "L", null, null, null, null));
    out.add(new Language("cmm", "Michigamea", "I", "E", null, null, null, null));
    out.add(new Language("cmn", "Mandarin Chinese", "I", "L", null, null, "Chinese, Mandarin", null));
    out.add(new Language("cmo", "Central Mnong", "I", "L", null, null, "Mnong, Central", null));
    out.add(new Language("cmr", "Mro-Khimi Chin", "I", "L", null, null, "Chin, Mro-Khimi", null));
    out.add(new Language("cms", "Messapic", "I", "H", null, null, null, null));
    out.add(new Language("cmt", "Camtho", "I", "L", null, null, null, null));
    out.add(new Language("cna", "Changthang", "I", "L", null, null, null, null));
    out.add(new Language("cnb", "Chinbon Chin", "I", "L", null, null, "Chin, Chinbon", null));
    out.add(new Language("cnc", "Côông", "I", "L", null, null, null, null));
    out.add(new Language("cng", "Northern Qiang", "I", "L", null, null, "Qiang, Northern", null));
    out.add(new Language("cnh", "Hakha Chin", "I", "L", null, null, "Chin, Hakha", null));
    out.add(new Language("cni", "Asháninka", "I", "L", null, null, null, null));
    out.add(new Language("cnk", "Khumi Chin", "I", "L", null, null, "Chin, Khumi", null));
    out.add(new Language("cnl", "Lalana Chinantec", "I", "L", null, null, "Chinantec, Lalana", null));
    out.add(new Language("cno", "Con", "I", "L", null, null, null, null));
    out.add(new Language("cnp", "Northern Ping Chinese", "I", "L", null, null, "Chinese, Northern Ping", null));
    out.add(new Language("cnq", "Chung", "I", "L", null, null, null, null));
    out.add(new Language("cnr", "Montenegrin", "I", "L", null, null, null, null));
    out.add(new Language("cns", "Central Asmat", "I", "L", null, null, "Asmat, Central", null));
    out.add(new Language("cnt", "Tepetotutla Chinantec", "I", "L", null, null, "Chinantec, Tepetotutla", null));
    out.add(new Language("cnu", "Chenoua", "I", "L", null, null, null, null));
    out.add(new Language("cnw", "Ngawn Chin", "I", "L", null, null, "Chin, Ngawn", null));
    out.add(new Language("cnx", "Middle Cornish", "I", "H", null, null, "Cornish, Middle", null));
    out.add(new Language("coa", "Cocos Islands Malay", "I", "L", null, null, "Malay, Cocos Islands", null));
    out.add(new Language("cob", "Chicomuceltec", "I", "E", null, null, null, null));
    out.add(new Language("coc", "Cocopa", "I", "L", null, null, null, null));
    out.add(new Language("cod", "Cocama-Cocamilla", "I", "L", null, null, null, null));
    out.add(new Language("coe", "Koreguaje", "I", "L", null, null, null, null));
    out.add(new Language("cof", "Colorado", "I", "L", null, null, null, null));
    out.add(new Language("cog", "Chong", "I", "L", null, null, null, null));
    out.add(new Language("coh", "Chonyi-Dzihana-Kauma", "I", "L", null, null, null, null));
    out.add(new Language("coj", "Cochimi", "I", "E", null, null, null, null));
    out.add(new Language("cok", "Santa Teresa Cora", "I", "L", null, null, "Cora, Santa Teresa", null));
    out.add(new Language("col", "Columbia-Wenatchi", "I", "L", null, null, null, null));
    out.add(new Language("com", "Comanche", "I", "L", null, null, null, null));
    out.add(new Language("con", "Cofán", "I", "L", null, null, null, null));
    out.add(new Language("coo", "Comox", "I", "L", null, null, null, null));
    out.add(new Language("cop", "Coptic", "I", "E", null, null, null, null));
    out.add(new Language("coq", "Coquille", "I", "E", null, null, null, null));
    out.add(new Language("cor", "Cornish", "I", "L", "kw", null, null, null));
    out.add(new Language("cos", "Corsican", "I", "L", "co", null, null, null));
    out.add(new Language("cot", "Caquinte", "I", "L", null, null, null, null));
    out.add(new Language("cou", "Wamey", "I", "L", null, null, null, null));
    out.add(new Language("cov", "Cao Miao", "I", "L", null, null, null, null));
    out.add(new Language("cow", "Cowlitz", "I", "E", null, null, null, null));
    out.add(new Language("cox", "Nanti", "I", "L", null, null, null, null));
    out.add(new Language("coz", "Chochotec", "I", "L", null, null, null, null));
    out.add(new Language("cpa", "Palantla Chinantec", "I", "L", null, null, "Chinantec, Palantla", null));
    out.add(new Language("cpb", "Ucayali-Yurúa Ashéninka", "I", "L", null, null, "Ashéninka, Ucayali-Yurúa", null));
    out.add(new Language("cpc", "Ajyíninka Apurucayali", "I", "L", null, null, null, null));
    out.add(new Language("cpg", "Cappadocian Greek", "I", "E", null, null, "Greek, Cappadocian", null));
    out.add(new Language("cpi", "Chinese Pidgin English", "I", "L", null, null, "Pidgin English, Chinese", null));
    out.add(new Language("cpn", "Cherepon", "I", "L", null, null, null, null));
    out.add(new Language("cpo", "Kpeego", "I", "L", null, null, null, null));
    out.add(new Language("cps", "Capiznon", "I", "L", null, null, null, null));
    out.add(new Language("cpu", "Pichis Ashéninka", "I", "L", null, null, "Ashéninka, Pichis", null));
    out.add(new Language("cpx", "Pu-Xian Chinese", "I", "L", null, null, "Chinese, Pu-Xian", null));
    out.add(new Language("cpy", "South Ucayali Ashéninka", "I", "L", null, null, "Ashéninka, South Ucayali", null));
    out.add(new Language("cqd", "Chuanqiandian Cluster Miao", "I", "L", null, null, "Miao, Chuanqiandian Cluster", null));
    out.add(new Language("cra", "Chara", "I", "L", null, null, null, null));
    out.add(new Language("crb", "Island Carib", "I", "E", null, null, "Carib, Island", null));
    out.add(new Language("crc", "Lonwolwol", "I", "L", null, null, null, null));
    out.add(new Language("crd", "Coeur d'Alene", "I", "L", null, null, null, null));
    out.add(new Language("cre", "Cree", "M", "L", "cr", null, null, null));
    out.add(new Language("crf", "Caramanta", "I", "E", null, null, null, null));
    out.add(new Language("crg", "Michif", "I", "L", null, null, null, null));
    out.add(new Language("crh", "Crimean Tatar", "I", "L", null, null, "Tatar, Crimean", null));
    out.add(new Language("cri", "Sãotomense", "I", "L", null, null, null, null));
    out.add(new Language("crj", "Southern East Cree", "I", "L", null, null, "Cree, Southern East", null));
    out.add(new Language("crk", "Plains Cree", "I", "L", null, null, "Cree, Plains", null));
    out.add(new Language("crl", "Northern East Cree", "I", "L", null, null, "Cree, Northern East", null));
    out.add(new Language("crm", "Moose Cree", "I", "L", null, null, "Cree, Moose", null));
    out.add(new Language("crn", "El Nayar Cora", "I", "L", null, null, "Cora, El Nayar", null));
    out.add(new Language("cro", "Crow", "I", "L", null, null, null, null));
    out.add(new Language("crq", "Iyo'wujwa Chorote", "I", "L", null, null, "Chorote, Iyo'wujwa", null));
    out.add(new Language("crr", "Carolina Algonquian", "I", "E", null, null, "Algonquian, Carolina", null));
    out.add(new Language("crs", "Seselwa Creole French", "I", "L", null, null, "Creole French, Seselwa", null));
    out.add(new Language("crt", "Iyojwa'ja Chorote", "I", "L", null, null, "Chorote, Iyojwa'ja", null));
    out.add(new Language("crv", "Chaura", "I", "L", null, null, null, null));
    out.add(new Language("crw", "Chrau", "I", "L", null, null, null, null));
    out.add(new Language("crx", "Carrier", "I", "L", null, null, null, null));
    out.add(new Language("cry", "Cori", "I", "L", null, null, null, null));
    out.add(new Language("crz", "Cruzeño", "I", "E", null, null, null, null));
    out.add(new Language("csa", "Chiltepec Chinantec", "I", "L", null, null, "Chinantec, Chiltepec", null));
    out.add(new Language("csb", "Kashubian", "I", "L", null, null, null, null));
    out.add(new Language("csc", "Catalan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csd", "Chiangmai Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("cse", "Czech Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csf", "Cuba Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csg", "Chilean Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csh", "Asho Chin", "I", "L", null, null, "Chin, Asho", null));
    out.add(new Language("csi", "Coast Miwok", "I", "E", null, null, "Miwok, Coast", null));
    out.add(new Language("csj", "Songlai Chin", "I", "L", null, null, "Chin, Songlai", null));
    out.add(new Language("csk", "Jola-Kasa", "I", "L", null, null, null, null));
    out.add(new Language("csl", "Chinese Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csm", "Central Sierra Miwok", "I", "L", null, null, "Miwok, Central Sierra", null));
    out.add(new Language("csn", "Colombian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("cso", "Sochiapam Chinantec", "I", "L", null, null, "Chinantec, Sochiapam", null));
    out.add(new Language("csp", "Southern Ping Chinese", "I", "L", null, null, "Chinese, Southern Ping", null));
    out.add(new Language("csq", "Croatia Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csr", "Costa Rican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("css", "Southern Ohlone", "I", "E", null, null, "Ohlone, Southern", null));
    out.add(new Language("cst", "Northern Ohlone", "I", "L", null, null, "Ohlone, Northern", null));
    out.add(new Language("csv", "Sumtu Chin", "I", "L", null, null, "Chin, Sumtu", null));
    out.add(new Language("csw", "Swampy Cree", "I", "L", null, null, "Cree, Swampy", null));
    out.add(new Language("csx", "Cambodian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("csy", "Siyin Chin", "I", "L", null, null, "Chin, Siyin", null));
    out.add(new Language("csz", "Coos", "I", "L", null, null, null, null));
    out.add(new Language("cta", "Tataltepec Chatino", "I", "L", null, null, "Chatino, Tataltepec", null));
    out.add(new Language("ctc", "Chetco", "I", "E", null, null, null, null));
    out.add(new Language("ctd", "Tedim Chin", "I", "L", null, null, "Chin, Tedim", null));
    out.add(new Language("cte", "Tepinapa Chinantec", "I", "L", null, null, "Chinantec, Tepinapa", null));
    out.add(new Language("ctg", "Chittagonian", "I", "L", null, null, null, null));
    out.add(new Language("cth", "Thaiphum Chin", "I", "L", null, null, "Chin, Thaiphum", null));
    out.add(new Language("ctl", "Tlacoatzintepec Chinantec", "I", "L", null, null, "Chinantec, Tlacoatzintepec", null));
    out.add(new Language("ctm", "Chitimacha", "I", "E", null, null, null, null));
    out.add(new Language("ctn", "Chhintange", "I", "L", null, null, null, null));
    out.add(new Language("cto", "Emberá-Catío", "I", "L", null, null, null, null));
    out.add(new Language("ctp", "Western Highland Chatino", "I", "L", null, null, "Chatino, Western Highland", null));
    out.add(new Language("cts", "Northern Catanduanes Bikol", "I", "L", null, null, "Bikol, Northern Catanduanes", null));
    out.add(new Language("ctt", "Wayanad Chetti", "I", "L", null, null, "Chetti, Wayanad", null));
    out.add(new Language("ctu", "Chol", "I", "L", null, null, null, null));
    out.add(new Language("cty", "Moundadan Chetty", "I", "L", null, null, null, null));
    out.add(new Language("ctz", "Zacatepec Chatino", "I", "L", null, null, "Chatino, Zacatepec", null));
    out.add(new Language("cua", "Cua", "I", "L", null, null, null, null));
    out.add(new Language("cub", "Cubeo", "I", "L", null, null, null, null));
    out.add(new Language("cuc", "Usila Chinantec", "I", "L", null, null, "Chinantec, Usila", null));
    out.add(new Language("cuh", "Chuka", "I", "L", null, null, null, null));
    out.add(new Language("cui", "Cuiba", "I", "L", null, null, null, null));
    out.add(new Language("cuj", "Mashco Piro", "I", "L", null, null, null, null));
    out.add(new Language("cuk", "San Blas Kuna", "I", "L", null, null, "Kuna, San Blas", null));
    out.add(new Language("cul", "Culina", "I", "L", null, null, null, null));
    out.add(new Language("cuo", "Cumanagoto", "I", "E", null, null, null, null));
    out.add(new Language("cup", "Cupeño", "I", "E", null, null, null, null));
    out.add(new Language("cuq", "Cun", "I", "L", null, null, null, null));
    out.add(new Language("cur", "Chhulung", "I", "L", null, null, null, null));
    out.add(new Language("cut", "Teutila Cuicatec", "I", "L", null, null, "Cuicatec, Teutila", null));
    out.add(new Language("cuu", "Tai Ya", "I", "L", null, null, null, null));
    out.add(new Language("cuv", "Cuvok", "I", "L", null, null, null, null));
    out.add(new Language("cuw", "Chukwa", "I", "L", null, null, null, null));
    out.add(new Language("cux", "Tepeuxila Cuicatec", "I", "L", null, null, "Cuicatec, Tepeuxila", null));
    out.add(new Language("cuy", "Cuitlatec", "I", "L", null, null, null, null));
    out.add(new Language("cvg", "Chug", "I", "L", null, null, null, null));
    out.add(new Language("cvn", "Valle Nacional Chinantec", "I", "L", null, null, "Chinantec, Valle Nacional", null));
    out.add(new Language("cwa", "Kabwa", "I", "L", null, null, null, null));
    out.add(new Language("cwb", "Maindo", "I", "L", null, null, null, null));
    out.add(new Language("cwd", "Woods Cree", "I", "L", null, null, "Cree, Woods", null));
    out.add(new Language("cwe", "Kwere", "I", "L", null, null, null, null));
    out.add(new Language("cwg", "Chewong", "I", "L", null, null, null, null));
    out.add(new Language("cwt", "Kuwaataay", "I", "L", null, null, null, null));
    out.add(new Language("cxh", "Cha'ari", "I", "L", null, null, null, null));
    out.add(new Language("cya", "Nopala Chatino", "I", "L", null, null, "Chatino, Nopala", null));
    out.add(new Language("cyb", "Cayubaba", "I", "E", null, null, null, null));
    out.add(new Language("cym", "Welsh", "I", "L", "cy", null, null, "wel"));
    out.add(new Language("cyo", "Cuyonon", "I", "L", null, null, null, null));
    out.add(new Language("czh", "Huizhou Chinese", "I", "L", null, null, "Chinese, Huizhou", null));
    out.add(new Language("czk", "Knaanic", "I", "E", null, null, null, null));
    out.add(new Language("czn", "Zenzontepec Chatino", "I", "L", null, null, "Chatino, Zenzontepec", null));
    out.add(new Language("czo", "Min Zhong Chinese", "I", "L", null, null, "Chinese, Min Zhong", null));
    out.add(new Language("czt", "Zotung Chin", "I", "L", null, null, "Chin, Zotung", null));
    out.add(new Language("daa", "Dangaléat", "I", "L", null, null, null, null));
    out.add(new Language("dac", "Dambi", "I", "L", null, null, null, null));
    out.add(new Language("dad", "Marik", "I", "L", null, null, null, null));
    out.add(new Language("dae", "Duupa", "I", "L", null, null, null, null));
    out.add(new Language("dag", "Dagbani", "I", "L", null, null, null, null));
    out.add(new Language("dah", "Gwahatike", "I", "L", null, null, null, null));
    out.add(new Language("dai", "Day", "I", "L", null, null, null, null));
    out.add(new Language("daj", "Dar Fur Daju", "I", "L", null, null, "Daju, Dar Fur", null));
    out.add(new Language("dak", "Dakota", "I", "L", null, null, null, null));
    out.add(new Language("dal", "Dahalo", "I", "L", null, null, null, null));
    out.add(new Language("dam", "Damakawa", "I", "L", null, null, null, null));
    out.add(new Language("dan", "Danish", "I", "L", "da", null, null, null));
    out.add(new Language("dao", "Daai Chin", "I", "L", null, null, "Chin, Daai", null));
    out.add(new Language("daq", "Dandami Maria", "I", "L", null, null, "Maria, Dandami", null));
    out.add(new Language("dar", "Dargwa", "I", "L", null, null, null, null));
    out.add(new Language("das", "Daho-Doo", "I", "L", null, null, null, null));
    out.add(new Language("dau", "Dar Sila Daju", "I", "L", null, null, "Daju, Dar Sila", null));
    out.add(new Language("dav", "Taita", "I", "L", null, null, null, null));
    out.add(new Language("daw", "Davawenyo", "I", "L", null, null, null, null));
    out.add(new Language("dax", "Dayi", "I", "L", null, null, null, null));
    out.add(new Language("daz", "Moi-Wadea", "I", "L", null, null, null, null));
    out.add(new Language("dba", "Bangime", "I", "L", null, null, null, null));
    out.add(new Language("dbb", "Deno", "I", "L", null, null, null, null));
    out.add(new Language("dbd", "Dadiya", "I", "L", null, null, null, null));
    out.add(new Language("dbe", "Dabe", "I", "L", null, null, null, null));
    out.add(new Language("dbf", "Edopi", "I", "L", null, null, null, null));
    out.add(new Language("dbg", "Dogul Dom Dogon", "I", "L", null, null, "Dogon, Dogul Dom", null));
    out.add(new Language("dbi", "Doka", "I", "L", null, null, null, null));
    out.add(new Language("dbj", "Ida'an", "I", "L", null, null, null, null));
    out.add(new Language("dbl", "Dyirbal", "I", "L", null, null, null, null));
  }
}
