// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 7000 to 7499 of {@link Language}.
 */
final class LanguageData14 {
  private LanguageData14() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("wca", "Yanomámi", "I", "L", null, null, null, null));
    out.add(new Language("wci", "Waci Gbe", "I", "L", null, null, "Gbe, Waci", null));
    out.add(new Language("wdd", "Wandji", "I", "L", null, null, null, null));
    out.add(new Language("wdg", "Wadaginam", "I", "L", null, null, null, null));
    out.add(new Language("wdj", "Wadjiginy", "I", "L", null, null, null, null));
    out.add(new Language("wdk", "Wadikali", "I", "E", null, null, null, null));
    out.add(new Language("wdt", "Wendat", "I", "L", null, null, null, null));
    out.add(new Language("wdu", "Wadjigu", "I", "E", null, null, null, null));
    out.add(new Language("wdy", "Wadjabangayi", "I", "E", null, null, null, null));
    out.add(new Language("wea", "Wewaw", "I", "E", null, null, null, null));
    out.add(new Language("wec", "Wè Western", "I", "L", null, null, null, null));
    out.add(new Language("wed", "Wedau", "I", "L", null, null, null, null));
    out.add(new Language("weg", "Wergaia", "I", "L", null, null, null, null));
    out.add(new Language("weh", "Weh", "I", "L", null, null, null, null));
    out.add(new Language("wei", "Kiunum", "I", "L", null, null, null, null));
    out.add(new Language("wem", "Weme Gbe", "I", "L", null, null, "Gbe, Weme", null));
    out.add(new Language("weo", "Wemale", "I", "L", null, null, null, null));
    out.add(new Language("wep", "Westphalien", "I", "L", null, null, null, null));
    out.add(new Language("wer", "Weri", "I", "L", null, null, null, null));
    out.add(new Language("wes", "Cameroon Pidgin", "I", "L", null, null, "Pidgin, Cameroon", null));
    out.add(new Language("wet", "Perai", "I", "L", null, null, null, null));
    out.add(new Language("weu", "Rawngtu Chin", "I", "L", null, null, "Chin, Rawngtu", null));
    out.add(new Language("wew", "Wejewa", "I", "L", null, null, null, null));
    out.add(new Language("wfg", "Yafi", "I", "L", null, null, null, null));
    out.add(new Language("wga", "Wagaya", "I", "E", null, null, null, null));
    out.add(new Language("wgb", "Wagawaga", "I", "L", null, null, null, null));
    out.add(new Language("wgg", "Wangkangurru", "I", "E", null, null, null, null));
    out.add(new Language("wgi", "Wahgi", "I", "L", null, null, null, null));
    out.add(new Language("wgo", "Waigeo", "I", "L", null, null, null, null));
    out.add(new Language("wgu", "Wirangu", "I", "E", null, null, null, null));
    out.add(new Language("wgy", "Warrgamay", "I", "L", null, null, null, null));
    out.add(new Language("wha", "Sou Upaa", "I", "L", null, null, null, null));
    out.add(new Language("whg", "North Wahgi", "I", "L", null, null, "Wahgi, North", null));
    out.add(new Language("whk", "Wahau Kenyah", "I", "L", null, null, "Kenyah, Wahau", null));
    out.add(new Language("whu", "Wahau Kayan", "I", "L", null, null, "Kayan, Wahau", null));
    out.add(new Language("wib", "Southern Toussian", "I", "L", null, null, "Toussian, Southern", null));
    out.add(new Language("wic", "Wichita", "I", "E", null, null, null, null));
    out.add(new Language("wie", "Wik-Epa", "I", "E", null, null, null, null));
    out.add(new Language("wif", "Wik-Keyangan", "I", "E", null, null, null, null));
    out.add(new Language("wig", "Wik Ngathan", "I", "L", null, null, null, null));
    out.add(new Language("wih", "Wik-Me'anha", "I", "L", null, null, null, null));
    out.add(new Language("wii", "Minidien", "I", "L", null, null, null, null));
    out.add(new Language("wij", "Wik-Iiyanh", "I", "L", null, null, null, null));
    out.add(new Language("wik", "Wikalkan", "I", "L", null, null, null, null));
    out.add(new Language("wil", "Wilawila", "I", "E", null, null, null, null));
    out.add(new Language("wim", "Wik-Mungkan", "I", "L", null, null, null, null));
    out.add(new Language("win", "Ho-Chunk", "I", "L", null, null, null, null));
    out.add(new Language("wir", "Wiraféd", "I", "E", null, null, null, null));
    out.add(new Language("wiu", "Wiru", "I", "L", null, null, null, null));
    out.add(new Language("wiv", "Vitu", "I", "L", null, null, null, null));
    out.add(new Language("wiy", "Wiyot", "I", "E", null, null, null, null));
    out.add(new Language("wja", "Waja", "I", "L", null, null, null, null));
    out.add(new Language("wji", "Warji", "I", "L", null, null, null, null));
    out.add(new Language("wka", "Kw'adza", "I", "E", null, null, null, null));
    out.add(new Language("wkb", "Kumbaran", "I", "L", null, null, null, null));
    out.add(new Language("wkd", "Wakde", "I", "L", null, null, null, null));
    out.add(new Language("wkl", "Kalanadi", "I", "L", null, null, null, null));
    out.add(new Language("wkr", "Keerray-Woorroong", "I", "L", null, null, null, null));
    out.add(new Language("wku", "Kunduvadi", "I", "L", null, null, null, null));
    out.add(new Language("wkw", "Wakawaka", "I", "E", null, null, null, null));
    out.add(new Language("wky", "Wangkayutyuru", "I", "E", null, null, null, null));
    out.add(new Language("wla", "Walio", "I", "L", null, null, null, null));
    out.add(new Language("wlc", "Mwali Comorian", "I", "L", null, null, "Comorian, Mwali", null));
    out.add(new Language("wle", "Wolane", "I", "L", null, null, null, null));
    out.add(new Language("wlg", "Kunbarlang", "I", "L", null, null, null, null));
    out.add(new Language("wlh", "Welaun", "I", "L", null, null, null, null));
    out.add(new Language("wli", "Waioli", "I", "L", null, null, null, null));
    out.add(new Language("wlk", "Wailaki", "I", "E", null, null, null, null));
    out.add(new Language("wll", "Wali (Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("wlm", "Middle Welsh", "I", "H", null, null, "Welsh, Middle", null));
    out.add(new Language("wln", "Walloon", "I", "L", "wa", null, null, null));
    out.add(new Language("wlo", "Wolio", "I", "L", null, null, null, null));
    out.add(new Language("wlr", "Wailapa", "I", "L", null, null, null, null));
    out.add(new Language("wls", "Wallisian", "I", "L", null, null, null, null));
    out.add(new Language("wlu", "Wuliwuli", "I", "E", null, null, null, null));
    out.add(new Language("wlv", "Wichí Lhamtés Vejoz", "I", "L", null, null, null, null));
    out.add(new Language("wlw", "Walak", "I", "L", null, null, null, null));
    out.add(new Language("wlx", "Wali (Ghana)", "I", "L", null, null, null, null));
    out.add(new Language("wly", "Waling", "I", "E", null, null, null, null));
    out.add(new Language("wma", "Mawa (Nigeria)", "I", "E", null, null, null, null));
    out.add(new Language("wmb", "Wambaya", "I", "L", null, null, null, null));
    out.add(new Language("wmc", "Wamas", "I", "L", null, null, null, null));
    out.add(new Language("wmd", "Mamaindé", "I", "L", null, null, null, null));
    out.add(new Language("wme", "Wambule", "I", "L", null, null, null, null));
    out.add(new Language("wmg", "Western Minyag", "I", "L", null, null, "Minyag, Western", null));
    out.add(new Language("wmh", "Waima'a", "I", "L", null, null, null, null));
    out.add(new Language("wmi", "Wamin", "I", "E", null, null, null, null));
    out.add(new Language("wmm", "Maiwa (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("wmn", "Waamwang", "I", "E", null, null, null, null));
    out.add(new Language("wmo", "Wom (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("wms", "Wambon", "I", "L", null, null, null, null));
    out.add(new Language("wmt", "Walmajarri", "I", "L", null, null, null, null));
    out.add(new Language("wmw", "Mwani", "I", "L", null, null, null, null));
    out.add(new Language("wmx", "Womo", "I", "L", null, null, null, null));
    out.add(new Language("wnb", "Mokati", "I", "L", null, null, null, null));
    out.add(new Language("wnc", "Wantoat", "I", "L", null, null, null, null));
    out.add(new Language("wnd", "Wandarang", "I", "E", null, null, null, null));
    out.add(new Language("wne", "Waneci", "I", "L", null, null, null, null));
    out.add(new Language("wng", "Wanggom", "I", "L", null, null, null, null));
    out.add(new Language("wni", "Ndzwani Comorian", "I", "L", null, null, "Comorian, Ndzwani", null));
    out.add(new Language("wnk", "Wanukaka", "I", "L", null, null, null, null));
    out.add(new Language("wnm", "Wanggamala", "I", "E", null, null, null, null));
    out.add(new Language("wnn", "Wunumara", "I", "E", null, null, null, null));
    out.add(new Language("wno", "Wano", "I", "L", null, null, null, null));
    out.add(new Language("wnp", "Wanap", "I", "L", null, null, null, null));
    out.add(new Language("wnu", "Usan", "I", "L", null, null, null, null));
    out.add(new Language("wnw", "Wintu", "I", "L", null, null, null, null));
    out.add(new Language("wny", "Wanyi", "I", "L", null, null, null, null));
    out.add(new Language("woa", "Kuwema", "I", "L", null, null, null, null));
    out.add(new Language("wob", "Wè Northern", "I", "L", null, null, null, null));
    out.add(new Language("woc", "Wogeo", "I", "L", null, null, null, null));
    out.add(new Language("wod", "Wolani", "I", "L", null, null, null, null));
    out.add(new Language("woe", "Woleaian", "I", "L", null, null, null, null));
    out.add(new Language("wof", "Gambian Wolof", "I", "L", null, null, "Wolof, Gambian", null));
    out.add(new Language("wog", "Wogamusin", "I", "L", null, null, null, null));
    out.add(new Language("woi", "Kamang", "I", "L", null, null, null, null));
    out.add(new Language("wok", "Longto", "I", "L", null, null, null, null));
    out.add(new Language("wol", "Wolof", "I", "L", "wo", null, null, null));
    out.add(new Language("wom", "Wom (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("won", "Wongo", "I", "L", null, null, null, null));
    out.add(new Language("woo", "Manombai", "I", "L", null, null, null, null));
    out.add(new Language("wor", "Woria", "I", "L", null, null, null, null));
    out.add(new Language("wos", "Hanga Hundi", "I", "L", null, null, null, null));
    out.add(new Language("wow", "Wawonii", "I", "L", null, null, null, null));
    out.add(new Language("woy", "Weyto", "I", "E", null, null, null, null));
    out.add(new Language("wpc", "Maco", "I", "L", null, null, null, null));
    out.add(new Language("wrb", "Waluwarra", "I", "E", null, null, null, null));
    out.add(new Language("wrg", "Warungu", "I", "E", null, null, null, null));
    out.add(new Language("wrh", "Wiradjuri", "I", "E", null, null, null, null));
    out.add(new Language("wri", "Wariyangga", "I", "E", null, null, null, null));
    out.add(new Language("wrk", "Garrwa", "I", "L", null, null, null, null));
    out.add(new Language("wrl", "Warlmanpa", "I", "L", null, null, null, null));
    out.add(new Language("wrm", "Warumungu", "I", "L", null, null, null, null));
    out.add(new Language("wrn", "Warnang", "I", "L", null, null, null, null));
    out.add(new Language("wro", "Worrorra", "I", "E", null, null, null, null));
    out.add(new Language("wrp", "Waropen", "I", "L", null, null, null, null));
    out.add(new Language("wrr", "Wardaman", "I", "L", null, null, null, null));
    out.add(new Language("wrs", "Waris", "I", "L", null, null, null, null));
    out.add(new Language("wru", "Waru", "I", "L", null, null, null, null));
    out.add(new Language("wrv", "Waruna", "I", "L", null, null, null, null));
    out.add(new Language("wrw", "Gugu Warra", "I", "E", null, null, null, null));
    out.add(new Language("wrx", "Wae Rana", "I", "L", null, null, null, null));
    out.add(new Language("wry", "Merwari", "I", "L", null, null, null, null));
    out.add(new Language("wrz", "Waray (Australia)", "I", "E", null, null, null, null));
    out.add(new Language("wsa", "Warembori", "I", "L", null, null, null, null));
    out.add(new Language("wsg", "Adilabad Gondi", "I", "L", null, null, "Gondi, Adilabad", null));
    out.add(new Language("wsi", "Wusi", "I", "L", null, null, null, null));
    out.add(new Language("wsk", "Waskia", "I", "L", null, null, null, null));
    out.add(new Language("wsr", "Owenia", "I", "L", null, null, null, null));
    out.add(new Language("wss", "Wasa", "I", "L", null, null, null, null));
    out.add(new Language("wsu", "Wasu", "I", "E", null, null, null, null));
    out.add(new Language("wsv", "Wotapuri-Katarqalai", "I", "E", null, null, null, null));
    out.add(new Language("wtb", "Matambwe", "I", "L", null, null, null, null));
    out.add(new Language("wtf", "Watiwa", "I", "L", null, null, null, null));
    out.add(new Language("wth", "Wathawurrung", "I", "E", null, null, null, null));
    out.add(new Language("wti", "Berta", "I", "L", null, null, null, null));
    out.add(new Language("wtk", "Watakataui", "I", "L", null, null, null, null));
    out.add(new Language("wtm", "Mewati", "I", "L", null, null, null, null));
    out.add(new Language("wtw", "Wotu", "I", "L", null, null, null, null));
    out.add(new Language("wua", "Wikngenchera", "I", "L", null, null, null, null));
    out.add(new Language("wub", "Wunambal", "I", "L", null, null, null, null));
    out.add(new Language("wud", "Wudu", "I", "L", null, null, null, null));
    out.add(new Language("wuh", "Wutunhua", "I", "L", null, null, null, null));
    out.add(new Language("wul", "Silimo", "I", "L", null, null, null, null));
    out.add(new Language("wum", "Wumbvu", "I", "L", null, null, null, null));
    out.add(new Language("wun", "Bungu", "I", "L", null, null, null, null));
    out.add(new Language("wur", "Wurrugu", "I", "E", null, null, null, null));
    out.add(new Language("wut", "Wutung", "I", "L", null, null, null, null));
    out.add(new Language("wuu", "Wu Chinese", "I", "L", null, null, "Chinese, Wu", null));
    out.add(new Language("wuv", "Wuvulu-Aua", "I", "L", null, null, null, null));
    out.add(new Language("wux", "Wulna", "I", "L", null, null, null, null));
    out.add(new Language("wuy", "Wauyai", "I", "L", null, null, null, null));
    out.add(new Language("wwa", "Waama", "I", "L", null, null, null, null));
    out.add(new Language("wwb", "Wakabunga", "I", "E", null, null, null, null));
    out.add(new Language("wwo", "Wetamut", "I", "L", null, null, null, null));
    out.add(new Language("wwr", "Warrwa", "I", "E", null, null, null, null));
    out.add(new Language("www", "Wawa", "I", "L", null, null, null, null));
    out.add(new Language("wxa", "Waxianghua", "I", "L", null, null, null, null));
    out.add(new Language("wxw", "Wardandi", "I", "E", null, null, null, null));
    out.add(new Language("wyb", "Wangaaybuwan-Ngiyambaa", "I", "L", null, null, null, null));
    out.add(new Language("wyi", "Woiwurrung", "I", "E", null, null, null, null));
    out.add(new Language("wym", "Wymysorys", "I", "L", null, null, null, null));
    out.add(new Language("wyn", "Wyandot", "I", "L", null, null, null, null));
    out.add(new Language("wyr", "Wayoró", "I", "L", null, null, null, null));
    out.add(new Language("wyy", "Western Fijian", "I", "L", null, null, "Fijian, Western", null));
    out.add(new Language("xaa", "Andalusian Arabic", "I", "H", null, null, "Arabic, Andalusian", null));
    out.add(new Language("xab", "Sambe", "I", "L", null, null, null, null));
    out.add(new Language("xac", "Kachari", "I", "L", null, null, null, null));
    out.add(new Language("xad", "Adai", "I", "E", null, null, null, null));
    out.add(new Language("xae", "Aequian", "I", "H", null, null, null, null));
    out.add(new Language("xag", "Aghwan", "I", "H", null, null, null, null));
    out.add(new Language("xai", "Kaimbé", "I", "E", null, null, null, null));
    out.add(new Language("xaj", "Ararandewára", "I", "E", null, null, null, null));
    out.add(new Language("xak", "Máku", "I", "E", null, null, null, null));
    out.add(new Language("xal", "Kalmyk", "I", "L", null, null, null, null));
    out.add(new Language("xam", "ǀXam", "I", "E", null, null, null, null));
    out.add(new Language("xan", "Xamtanga", "I", "L", null, null, null, null));
    out.add(new Language("xao", "Khao", "I", "L", null, null, null, null));
    out.add(new Language("xap", "Apalachee", "I", "E", null, null, null, null));
    out.add(new Language("xaq", "Aquitanian", "I", "H", null, null, null, null));
    out.add(new Language("xar", "Karami", "I", "E", null, null, null, null));
    out.add(new Language("xas", "Kamas", "I", "E", null, null, null, null));
    out.add(new Language("xat", "Katawixi", "I", "L", null, null, null, null));
    out.add(new Language("xau", "Kauwera", "I", "L", null, null, null, null));
    out.add(new Language("xav", "Xavánte", "I", "L", null, null, null, null));
    out.add(new Language("xaw", "Kawaiisu", "I", "L", null, null, null, null));
    out.add(new Language("xay", "Kayan Mahakam", "I", "L", null, null, null, null));
    out.add(new Language("xbb", "Lower Burdekin", "I", "E", null, null, "Burdekin, Lower", null));
    out.add(new Language("xbc", "Bactrian", "I", "H", null, null, null, null));
    out.add(new Language("xbd", "Bindal", "I", "E", null, null, null, null));
    out.add(new Language("xbe", "Bigambal", "I", "E", null, null, null, null));
    out.add(new Language("xbg", "Bunganditj", "I", "E", null, null, null, null));
    out.add(new Language("xbi", "Kombio", "I", "L", null, null, null, null));
    out.add(new Language("xbj", "Birrpayi", "I", "E", null, null, null, null));
    out.add(new Language("xbm", "Middle Breton", "I", "H", null, null, "Breton, Middle", null));
    out.add(new Language("xbn", "Kenaboi", "I", "E", null, null, null, null));
    out.add(new Language("xbo", "Bolgarian", "I", "H", null, null, null, null));
    out.add(new Language("xbp", "Bibbulman", "I", "E", null, null, null, null));
    out.add(new Language("xbr", "Kambera", "I", "L", null, null, null, null));
    out.add(new Language("xbw", "Kambiwá", "I", "E", null, null, null, null));
    out.add(new Language("xby", "Batjala", "I", "L", null, null, null, null));
    out.add(new Language("xcb", "Cumbric", "I", "H", null, null, null, null));
    out.add(new Language("xcc", "Camunic", "I", "H", null, null, null, null));
    out.add(new Language("xce", "Celtiberian", "I", "H", null, null, null, null));
    out.add(new Language("xcg", "Cisalpine Gaulish", "I", "H", null, null, "Gaulish, Cisalpine", null));
    out.add(new Language("xch", "Chemakum", "I", "E", null, null, null, null));
    out.add(new Language("xcl", "Classical Armenian", "I", "H", null, null, "Armenian, Classical", null));
    out.add(new Language("xcm", "Comecrudo", "I", "E", null, null, null, null));
    out.add(new Language("xcn", "Cotoname", "I", "E", null, null, null, null));
    out.add(new Language("xco", "Chorasmian", "I", "H", null, null, null, null));
    out.add(new Language("xcr", "Carian", "I", "H", null, null, null, null));
    out.add(new Language("xct", "Classical Tibetan", "I", "H", null, null, "Tibetan, Classical", null));
    out.add(new Language("xcu", "Curonian", "I", "H", null, null, null, null));
    out.add(new Language("xcv", "Chuvantsy", "I", "E", null, null, null, null));
    out.add(new Language("xcw", "Coahuilteco", "I", "E", null, null, null, null));
    out.add(new Language("xcy", "Cayuse", "I", "E", null, null, null, null));
    out.add(new Language("xda", "Darkinyung", "I", "L", null, null, null, null));
    out.add(new Language("xdc", "Dacian", "I", "H", null, null, null, null));
    out.add(new Language("xdk", "Dharuk", "I", "E", null, null, null, null));
    out.add(new Language("xdm", "Edomite", "I", "H", null, null, null, null));
    out.add(new Language("xdo", "Kwandu", "I", "L", null, null, null, null));
    out.add(new Language("xdq", "Kaitag", "I", "L", null, null, null, null));
    out.add(new Language("xdy", "Malayic Dayak", "I", "L", null, null, "Dayak, Malayic", null));
    out.add(new Language("xeb", "Eblan", "I", "H", null, null, null, null));
    out.add(new Language("xed", "Hdi", "I", "L", null, null, null, null));
    out.add(new Language("xeg", "ǁXegwi", "I", "E", null, null, null, null));
    out.add(new Language("xel", "Kelo", "I", "L", null, null, null, null));
    out.add(new Language("xem", "Kembayan", "I", "L", null, null, null, null));
    out.add(new Language("xep", "Epi-Olmec", "I", "H", null, null, null, null));
    out.add(new Language("xer", "Xerénte", "I", "L", null, null, null, null));
    out.add(new Language("xes", "Kesawai", "I", "L", null, null, null, null));
    out.add(new Language("xet", "Xetá", "I", "L", null, null, null, null));
    out.add(new Language("xeu", "Keoru-Ahia", "I", "L", null, null, null, null));
    out.add(new Language("xfa", "Faliscan", "I", "H", null, null, null, null));
    out.add(new Language("xga", "Galatian", "I", "H", null, null, null, null));
    out.add(new Language("xgb", "Gbin", "I", "E", null, null, null, null));
    out.add(new Language("xgd", "Gudang", "I", "E", null, null, null, null));
    out.add(new Language("xgf", "Gabrielino-Fernandeño", "I", "E", null, null, null, null));
    out.add(new Language("xgg", "Goreng", "I", "E", null, null, null, null));
    out.add(new Language("xgi", "Garingbal", "I", "E", null, null, null, null));
    out.add(new Language("xgl", "Galindan", "I", "H", null, null, null, null));
    out.add(new Language("xgm", "Dharumbal", "I", "E", null, null, null, null));
    out.add(new Language("xgr", "Garza", "I", "E", null, null, null, null));
    out.add(new Language("xgu", "Unggumi", "I", "L", null, null, null, null));
    out.add(new Language("xgw", "Guwa", "I", "E", null, null, null, null));
    out.add(new Language("xha", "Harami", "I", "H", null, null, null, null));
    out.add(new Language("xhc", "Hunnic", "I", "H", null, null, null, null));
    out.add(new Language("xhd", "Hadrami", "I", "H", null, null, null, null));
    out.add(new Language("xhe", "Khetrani", "I", "L", null, null, null, null));
    out.add(new Language("xhm", "Middle Khmer (1400 to 1850 CE)", "I", "H", null, null, "Khmer, Middle (1400 to 1850 CE)", null));
    out.add(new Language("xho", "Xhosa", "I", "L", "xh", null, null, null));
    out.add(new Language("xhr", "Hernican", "I", "H", null, null, null, null));
    out.add(new Language("xht", "Hattic", "I", "H", null, null, null, null));
    out.add(new Language("xhu", "Hurrian", "I", "H", null, null, null, null));
    out.add(new Language("xhv", "Khua", "I", "L", null, null, null, null));
    out.add(new Language("xib", "Iberian", "I", "H", null, null, null, null));
    out.add(new Language("xii", "Xiri", "I", "L", null, null, null, null));
    out.add(new Language("xil", "Illyrian", "I", "H", null, null, null, null));
    out.add(new Language("xin", "Xinca", "I", "E", null, null, null, null));
    out.add(new Language("xir", "Xiriâna", "I", "E", null, null, null, null));
    out.add(new Language("xis", "Kisan", "I", "L", null, null, null, null));
    out.add(new Language("xiv", "Indus Valley Language", "I", "H", null, null, null, null));
    out.add(new Language("xiy", "Xipaya", "I", "L", null, null, null, null));
    out.add(new Language("xjb", "Minjungbal", "I", "E", null, null, null, null));
    out.add(new Language("xjt", "Jaitmatang", "I", "E", null, null, null, null));
    out.add(new Language("xka", "Kalkoti", "I", "L", null, null, null, null));
    out.add(new Language("xkb", "Northern Nago", "I", "L", null, null, "Nago, Northern", null));
    out.add(new Language("xkc", "Kho'ini", "I", "L", null, null, null, null));
    out.add(new Language("xkd", "Mendalam Kayan", "I", "L", null, null, "Kayan, Mendalam", null));
    out.add(new Language("xke", "Kereho", "I", "L", null, null, null, null));
    out.add(new Language("xkf", "Khengkha", "I", "L", null, null, null, null));
    out.add(new Language("xkg", "Kagoro", "I", "L", null, null, null, null));
    out.add(new Language("xki", "Kenyan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("xkj", "Kajali", "I", "L", null, null, null, null));
    out.add(new Language("xkk", "Kachok", "I", "L", null, null, null, null));
    out.add(new Language("xkl", "Mainstream Kenyah", "I", "L", null, null, null, null));
    out.add(new Language("xkn", "Kayan River Kayan", "I", "L", null, null, "Kayan, Kayan River", null));
    out.add(new Language("xko", "Kiorr", "I", "L", null, null, null, null));
    out.add(new Language("xkp", "Kabatei", "I", "L", null, null, null, null));
    out.add(new Language("xkq", "Koroni", "I", "L", null, null, null, null));
    out.add(new Language("xkr", "Xakriabá", "I", "E", null, null, null, null));
    out.add(new Language("xks", "Kumbewaha", "I", "L", null, null, null, null));
    out.add(new Language("xkt", "Kantosi", "I", "L", null, null, null, null));
    out.add(new Language("xku", "Kaamba", "I", "L", null, null, null, null));
    out.add(new Language("xkv", "Kgalagadi", "I", "L", null, null, null, null));
    out.add(new Language("xkw", "Kembra", "I", "L", null, null, null, null));
    out.add(new Language("xkx", "Karore", "I", "L", null, null, null, null));
    out.add(new Language("xky", "Uma' Lasan", "I", "L", null, null, null, null));
    out.add(new Language("xkz", "Kurtokha", "I", "L", null, null, null, null));
    out.add(new Language("xla", "Kamula", "I", "L", null, null, null, null));
    out.add(new Language("xlb", "Loup B", "I", "E", null, null, null, null));
    out.add(new Language("xlc", "Lycian", "I", "H", null, null, null, null));
    out.add(new Language("xld", "Lydian", "I", "H", null, null, null, null));
    out.add(new Language("xle", "Lemnian", "I", "H", null, null, null, null));
    out.add(new Language("xlg", "Ligurian (Ancient)", "I", "H", null, null, null, null));
    out.add(new Language("xli", "Liburnian", "I", "H", null, null, null, null));
    out.add(new Language("xln", "Alanic", "I", "H", null, null, null, null));
    out.add(new Language("xlo", "Loup A", "I", "E", null, null, null, null));
    out.add(new Language("xlp", "Lepontic", "I", "H", null, null, null, null));
    out.add(new Language("xls", "Lusitanian", "I", "H", null, null, null, null));
    out.add(new Language("xlu", "Cuneiform Luwian", "I", "H", null, null, "Luwian, Cuneiform", null));
    out.add(new Language("xly", "Elymian", "I", "H", null, null, null, null));
    out.add(new Language("xma", "Mushungulu", "I", "L", null, null, null, null));
    out.add(new Language("xmb", "Mbonga", "I", "L", null, null, null, null));
    out.add(new Language("xmc", "Makhuwa-Marrevone", "I", "L", null, null, null, null));
    out.add(new Language("xmd", "Mbudum", "I", "L", null, null, null, null));
    out.add(new Language("xme", "Median", "I", "H", null, null, null, null));
    out.add(new Language("xmf", "Mingrelian", "I", "L", null, null, null, null));
    out.add(new Language("xmg", "Mengaka", "I", "L", null, null, null, null));
    out.add(new Language("xmh", "Kugu-Muminh", "I", "L", null, null, null, null));
    out.add(new Language("xmj", "Majera", "I", "L", null, null, null, null));
    out.add(new Language("xmk", "Ancient Macedonian", "I", "H", null, null, "Macedonian, Ancient", null));
    out.add(new Language("xml", "Malaysian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("xmm", "Manado Malay", "I", "L", null, null, "Malay, Manado", null));
    out.add(new Language("xmn", "Manichaean Middle Persian", "I", "H", null, null, "Persian, Manichaean Middle", null));
    out.add(new Language("xmo", "Morerebi", "I", "L", null, null, null, null));
    out.add(new Language("xmp", "Kuku-Mu'inh", "I", "E", null, null, null, null));
    out.add(new Language("xmq", "Kuku-Mangk", "I", "E", null, null, null, null));
    out.add(new Language("xmr", "Meroitic", "I", "H", null, null, null, null));
    out.add(new Language("xms", "Moroccan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("xmt", "Matbat", "I", "L", null, null, null, null));
    out.add(new Language("xmu", "Kamu", "I", "E", null, null, null, null));
    out.add(new Language("xmv", "Antankarana Malagasy", "I", "L", null, null, "Malagasy, Antankarana", null));
    out.add(new Language("xmw", "Tsimihety Malagasy", "I", "L", null, null, "Malagasy, Tsimihety", null));
    out.add(new Language("xmx", "Salawati", "I", "L", null, null, null, null));
    out.add(new Language("xmy", "Mayaguduna", "I", "L", null, null, null, null));
    out.add(new Language("xmz", "Mori Bawah", "I", "L", null, null, null, null));
    out.add(new Language("xna", "Ancient North Arabian", "I", "H", null, null, "North Arabian, Ancient", null));
    out.add(new Language("xnb", "Kanakanabu", "I", "L", null, null, null, null));
    out.add(new Language("xng", "Middle Mongolian", "I", "H", null, null, "Mongolian, Middle", null));
    out.add(new Language("xnh", "Kuanhua", "I", "L", null, null, null, null));
    out.add(new Language("xni", "Ngarigu", "I", "E", null, null, null, null));
    out.add(new Language("xnj", "Ngoni (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("xnk", "Nganakarti", "I", "E", null, null, null, null));
    out.add(new Language("xnm", "Ngumbarl", "I", "E", null, null, null, null));
    out.add(new Language("xnn", "Northern Kankanay", "I", "L", null, null, "Kankanay, Northern", null));
    out.add(new Language("xno", "Anglo-Norman", "I", "H", null, null, null, null));
    out.add(new Language("xnq", "Ngoni (Mozambique)", "I", "L", null, null, null, null));
    out.add(new Language("xnr", "Kangri", "I", "L", null, null, null, null));
    out.add(new Language("xns", "Kanashi", "I", "L", null, null, null, null));
    out.add(new Language("xnt", "Narragansett", "I", "E", null, null, null, null));
    out.add(new Language("xnu", "Nukunul", "I", "E", null, null, null, null));
    out.add(new Language("xny", "Nyiyaparli", "I", "L", null, null, null, null));
    out.add(new Language("xnz", "Kenzi", "I", "L", null, null, null, null));
    out.add(new Language("xoc", "O'chi'chi'", "I", "E", null, null, null, null));
    out.add(new Language("xod", "Kokoda", "I", "L", null, null, null, null));
    out.add(new Language("xog", "Soga", "I", "L", null, null, null, null));
    out.add(new Language("xoi", "Kominimung", "I", "L", null, null, null, null));
    out.add(new Language("xok", "Xokleng", "I", "L", null, null, null, null));
    out.add(new Language("xom", "Komo (Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("xon", "Konkomba", "I", "L", null, null, null, null));
    out.add(new Language("xoo", "Xukurú", "I", "E", null, null, null, null));
    out.add(new Language("xop", "Kopar", "I", "L", null, null, null, null));
    out.add(new Language("xor", "Korubo", "I", "L", null, null, null, null));
    out.add(new Language("xow", "Kowaki", "I", "L", null, null, null, null));
    out.add(new Language("xpa", "Pirriya", "I", "E", null, null, null, null));
    out.add(new Language("xpb", "Northeastern Tasmanian", "I", "E", null, null, "Tasmanian, Northeastern", null));
    out.add(new Language("xpc", "Pecheneg", "I", "H", null, null, null, null));
    out.add(new Language("xpd", "Oyster Bay Tasmanian", "I", "E", null, null, "Tasmanian, Oyster Bay", null));
    out.add(new Language("xpe", "Liberia Kpelle", "I", "L", null, null, "Kpelle, Liberia", null));
    out.add(new Language("xpf", "Southeast Tasmanian", "I", "E", null, null, "Tasmanian, Southeast", null));
    out.add(new Language("xpg", "Phrygian", "I", "H", null, null, null, null));
    out.add(new Language("xph", "North Midlands Tasmanian", "I", "E", null, null, "Tasmanian, North Midlands", null));
    out.add(new Language("xpi", "Pictish", "I", "H", null, null, null, null));
    out.add(new Language("xpj", "Mpalitjanh", "I", "E", null, null, null, null));
    out.add(new Language("xpk", "Kulina Pano", "I", "L", null, null, "Pano, Kulina", null));
    out.add(new Language("xpl", "Port Sorell Tasmanian", "I", "E", null, null, "Tasmanian, Port Sorell", null));
    out.add(new Language("xpm", "Pumpokol", "I", "E", null, null, null, null));
    out.add(new Language("xpn", "Kapinawá", "I", "E", null, null, null, null));
    out.add(new Language("xpo", "Pochutec", "I", "E", null, null, null, null));
    out.add(new Language("xpp", "Puyo-Paekche", "I", "H", null, null, null, null));
    out.add(new Language("xpq", "Mohegan-Pequot", "I", "E", null, null, null, null));
    out.add(new Language("xpr", "Parthian", "I", "H", null, null, null, null));
    out.add(new Language("xps", "Pisidian", "I", "H", null, null, null, null));
    out.add(new Language("xpt", "Punthamara", "I", "E", null, null, null, null));
    out.add(new Language("xpu", "Punic", "I", "H", null, null, null, null));
    out.add(new Language("xpv", "Northern Tasmanian", "I", "E", null, null, "Tasmanian, Northern", null));
    out.add(new Language("xpw", "Northwestern Tasmanian", "I", "E", null, null, "Tasmanian, Northwestern", null));
    out.add(new Language("xpx", "Southwestern Tasmanian", "I", "E", null, null, "Tasmanian, Southwestern", null));
    out.add(new Language("xpy", "Puyo", "I", "H", null, null, null, null));
    out.add(new Language("xpz", "Bruny Island Tasmanian", "I", "E", null, null, "Tasmanian, Bruny Island", null));
    out.add(new Language("xqa", "Karakhanid", "I", "H", null, null, null, null));
    out.add(new Language("xqt", "Qatabanian", "I", "H", null, null, null, null));
    out.add(new Language("xra", "Krahô", "I", "L", null, null, null, null));
    out.add(new Language("xrb", "Eastern Karaboro", "I", "L", null, null, "Karaboro, Eastern", null));
    out.add(new Language("xrd", "Gundungurra", "I", "E", null, null, null, null));
    out.add(new Language("xre", "Kreye", "I", "L", null, null, null, null));
    out.add(new Language("xrg", "Minang", "I", "E", null, null, null, null));
    out.add(new Language("xri", "Krikati-Timbira", "I", "L", null, null, null, null));
    out.add(new Language("xrm", "Armazic", "I", "H", null, null, null, null));
    out.add(new Language("xrn", "Arin", "I", "E", null, null, null, null));
    out.add(new Language("xrr", "Raetic", "I", "H", null, null, null, null));
    out.add(new Language("xrt", "Aranama-Tamique", "I", "E", null, null, null, null));
    out.add(new Language("xru", "Marriammu", "I", "L", null, null, null, null));
    out.add(new Language("xrw", "Karawa", "I", "L", null, null, null, null));
    out.add(new Language("xsa", "Sabaean", "I", "H", null, null, null, null));
    out.add(new Language("xsb", "Sambal", "I", "L", null, null, null, null));
    out.add(new Language("xsc", "Scythian", "I", "H", null, null, null, null));
    out.add(new Language("xsd", "Sidetic", "I", "H", null, null, null, null));
    out.add(new Language("xse", "Sempan", "I", "L", null, null, null, null));
    out.add(new Language("xsh", "Shamang", "I", "L", null, null, null, null));
    out.add(new Language("xsi", "Sio", "I", "L", null, null, null, null));
    out.add(new Language("xsj", "Subi", "I", "L", null, null, null, null));
    out.add(new Language("xsl", "South Slavey", "I", "L", null, null, "Slavey, South", null));
    out.add(new Language("xsm", "Kasem", "I", "L", null, null, null, null));
    out.add(new Language("xsn", "Sanga (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("xso", "Solano", "I", "E", null, null, null, null));
    out.add(new Language("xsp", "Silopi", "I", "L", null, null, null, null));
    out.add(new Language("xsq", "Makhuwa-Saka", "I", "L", null, null, null, null));
    out.add(new Language("xsr", "Sherpa", "I", "L", null, null, null, null));
    out.add(new Language("xsu", "Sanumá", "I", "L", null, null, null, null));
    out.add(new Language("xsv", "Sudovian", "I", "E", null, null, null, null));
    out.add(new Language("xsy", "Saisiyat", "I", "L", null, null, null, null));
    out.add(new Language("xta", "Alcozauca Mixtec", "I", "L", null, null, "Mixtec, Alcozauca", null));
    out.add(new Language("xtb", "Chazumba Mixtec", "I", "L", null, null, "Mixtec, Chazumba", null));
    out.add(new Language("xtc", "Katcha-Kadugli-Miri", "I", "L", null, null, null, null));
    out.add(new Language("xtd", "Diuxi-Tilantongo Mixtec", "I", "L", null, null, "Mixtec, Diuxi-Tilantongo", null));
    out.add(new Language("xte", "Ketengban", "I", "L", null, null, null, null));
    out.add(new Language("xtg", "Transalpine Gaulish", "I", "H", null, null, "Gaulish, Transalpine", null));
    out.add(new Language("xth", "Yitha Yitha", "I", "E", null, null, null, null));
    out.add(new Language("xti", "Sinicahua Mixtec", "I", "L", null, null, "Mixtec, Sinicahua", null));
    out.add(new Language("xtj", "San Juan Teita Mixtec", "I", "L", null, null, "Mixtec, San Juan Teita", null));
    out.add(new Language("xtl", "Tijaltepec Mixtec", "I", "L", null, null, "Mixtec, Tijaltepec", null));
    out.add(new Language("xtm", "Magdalena Peñasco Mixtec", "I", "L", null, null, "Mixtec, Magdalena Peñasco", null));
    out.add(new Language("xtn", "Northern Tlaxiaco Mixtec", "I", "L", null, null, "Mixtec, Northern Tlaxiaco", null));
    out.add(new Language("xto", "Tokharian A", "I", "H", null, null, null, null));
    out.add(new Language("xtp", "San Miguel Piedras Mixtec", "I", "L", null, null, "Mixtec, San Miguel Piedras", null));
    out.add(new Language("xtq", "Tumshuqese", "I", "H", null, null, null, null));
    out.add(new Language("xtr", "Early Tripuri", "I", "H", null, null, "Tripuri, Early", null));
    out.add(new Language("xts", "Sindihui Mixtec", "I", "L", null, null, "Mixtec, Sindihui", null));
    out.add(new Language("xtt", "Tacahua Mixtec", "I", "L", null, null, "Mixtec, Tacahua", null));
    out.add(new Language("xtu", "Cuyamecalco Mixtec", "I", "L", null, null, "Mixtec, Cuyamecalco", null));
    out.add(new Language("xtv", "Thawa", "I", "E", null, null, null, null));
    out.add(new Language("xtw", "Tawandê", "I", "L", null, null, null, null));
    out.add(new Language("xty", "Yoloxochitl Mixtec", "I", "L", null, null, "Mixtec, Yoloxochitl", null));
    out.add(new Language("xua", "Alu Kurumba", "I", "L", null, null, "Kurumba, Alu", null));
    out.add(new Language("xub", "Betta Kurumba", "I", "L", null, null, "Kurumba, Betta", null));
    out.add(new Language("xud", "Umiida", "I", "E", null, null, null, null));
    out.add(new Language("xug", "Kunigami", "I", "L", null, null, null, null));
    out.add(new Language("xuj", "Jennu Kurumba", "I", "L", null, null, "Kurumba, Jennu", null));
    out.add(new Language("xul", "Ngunawal", "I", "E", null, null, null, null));
    out.add(new Language("xum", "Umbrian", "I", "H", null, null, null, null));
    out.add(new Language("xun", "Unggaranggu", "I", "E", null, null, null, null));
    out.add(new Language("xuo", "Kuo", "I", "L", null, null, null, null));
    out.add(new Language("xup", "Upper Umpqua", "I", "E", null, null, "Umpqua, Upper", null));
    out.add(new Language("xur", "Urartian", "I", "H", null, null, null, null));
    out.add(new Language("xut", "Kuthant", "I", "E", null, null, null, null));
    out.add(new Language("xuu", "Kxoe", "I", "L", null, null, null, null));
    out.add(new Language("xve", "Venetic", "I", "H", null, null, null, null));
    out.add(new Language("xvi", "Kamviri", "I", "L", null, null, null, null));
    out.add(new Language("xvn", "Vandalic", "I", "H", null, null, null, null));
    out.add(new Language("xvo", "Volscian", "I", "H", null, null, null, null));
    out.add(new Language("xvs", "Vestinian", "I", "H", null, null, null, null));
    out.add(new Language("xwa", "Kwaza", "I", "L", null, null, null, null));
    out.add(new Language("xwc", "Woccon", "I", "E", null, null, null, null));
    out.add(new Language("xwd", "Wadi Wadi", "I", "E", null, null, null, null));
    out.add(new Language("xwe", "Xwela Gbe", "I", "L", null, null, "Gbe, Xwela", null));
    out.add(new Language("xwg", "Kwegu", "I", "L", null, null, null, null));
    out.add(new Language("xwj", "Wajuk", "I", "E", null, null, null, null));
    out.add(new Language("xwk", "Wangkumara", "I", "E", null, null, null, null));
    out.add(new Language("xwl", "Western Xwla Gbe", "I", "L", null, null, "Gbe, Western Xwla", null));
    out.add(new Language("xwo", "Written Oirat", "I", "E", null, null, "Oirat, Written", null));
    out.add(new Language("xwr", "Kwerba Mamberamo", "I", "L", null, null, null, null));
    out.add(new Language("xwt", "Wotjobaluk", "I", "E", null, null, null, null));
    out.add(new Language("xww", "Wemba Wemba", "I", "E", null, null, null, null));
    out.add(new Language("xxb", "Boro (Ghana)", "I", "E", null, null, null, null));
    out.add(new Language("xxk", "Ke'o", "I", "L", null, null, null, null));
    out.add(new Language("xxm", "Minkin", "I", "E", null, null, null, null));
    out.add(new Language("xxr", "Koropó", "I", "E", null, null, null, null));
    out.add(new Language("xxt", "Tambora", "I", "E", null, null, null, null));
    out.add(new Language("xya", "Yaygir", "I", "E", null, null, null, null));
    out.add(new Language("xyb", "Yandjibara", "I", "E", null, null, null, null));
    out.add(new Language("xyj", "Mayi-Yapi", "I", "E", null, null, null, null));
    out.add(new Language("xyk", "Mayi-Kulan", "I", "E", null, null, null, null));
    out.add(new Language("xyl", "Yalakalore", "I", "E", null, null, null, null));
    out.add(new Language("xyt", "Mayi-Thakurti", "I", "E", null, null, null, null));
    out.add(new Language("xyy", "Yorta Yorta", "I", "L", null, null, null, null));
    out.add(new Language("xzh", "Zhang-Zhung", "I", "H", null, null, null, null));
    out.add(new Language("xzm", "Zemgalian", "I", "E", null, null, null, null));
    out.add(new Language("xzp", "Ancient Zapotec", "I", "H", null, null, "Zapotec, Ancient", null));
  }
}
