// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 4000 to 4499 of {@link Language}.
 */
final class LanguageData8 {
  private LanguageData8() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("mha", "Manda (India)", "I", "L", null, null, null, null));
    out.add(new Language("mhb", "Mahongwe", "I", "L", null, null, null, null));
    out.add(new Language("mhc", "Mocho", "I", "L", null, null, null, null));
    out.add(new Language("mhd", "Mbugu", "I", "L", null, null, null, null));
    out.add(new Language("mhe", "Besisi", "I", "L", null, null, null, null));
    out.add(new Language("mhf", "Mamaa", "I", "L", null, null, null, null));
    out.add(new Language("mhg", "Margu", "I", "L", null, null, null, null));
    out.add(new Language("mhi", "Ma'di", "I", "L", null, null, null, null));
    out.add(new Language("mhj", "Mogholi", "I", "L", null, null, null, null));
    out.add(new Language("mhk", "Mungaka", "I", "L", null, null, null, null));
    out.add(new Language("mhl", "Mauwake", "I", "L", null, null, null, null));
    out.add(new Language("mhm", "Makhuwa-Moniga", "I", "L", null, null, null, null));
    out.add(new Language("mhn", "Mòcheno", "I", "L", null, null, null, null));
    out.add(new Language("mho", "Mashi (Zambia)", "I", "L", null, null, null, null));
    out.add(new Language("mhp", "Balinese Malay", "I", "L", null, null, "Malay, Balinese", null));
    out.add(new Language("mhq", "Mandan", "I", "L", null, null, null, null));
    out.add(new Language("mhr", "Eastern Mari", "I", "L", null, null, "Mari, Eastern", null));
    out.add(new Language("mhs", "Buru (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("mht", "Mandahuaca", "I", "L", null, null, null, null));
    out.add(new Language("mhu", "Digaro-Mishmi", "I", "L", null, null, null, null));
    out.add(new Language("mhw", "Mbukushu", "I", "L", null, null, null, null));
    out.add(new Language("mhx", "Maru", "I", "L", null, null, null, null));
    out.add(new Language("mhy", "Ma'anyan", "I", "L", null, null, null, null));
    out.add(new Language("mhz", "Mor (Mor Islands)", "I", "L", null, null, null, null));
    out.add(new Language("mia", "Miami", "I", "L", null, null, null, null));
    out.add(new Language("mib", "Atatláhuca Mixtec", "I", "L", null, null, "Mixtec, Atatláhuca", null));
    out.add(new Language("mic", "Mi'kmaq", "I", "L", null, null, null, null));
    out.add(new Language("mid", "Mandaic", "I", "L", null, null, null, null));
    out.add(new Language("mie", "Ocotepec Mixtec", "I", "L", null, null, "Mixtec, Ocotepec", null));
    out.add(new Language("mif", "Mofu-Gudur", "I", "L", null, null, null, null));
    out.add(new Language("mig", "San Miguel El Grande Mixtec", "I", "L", null, null, "Mixtec, San Miguel El Grande", null));
    out.add(new Language("mih", "Chayuco Mixtec", "I", "L", null, null, "Mixtec, Chayuco", null));
    out.add(new Language("mii", "Chigmecatitlán Mixtec", "I", "L", null, null, "Mixtec, Chigmecatitlán", null));
    out.add(new Language("mij", "Abar", "I", "L", null, null, null, null));
    out.add(new Language("mik", "Mikasuki", "I", "L", null, null, null, null));
    out.add(new Language("mil", "Peñoles Mixtec", "I", "L", null, null, "Mixtec, Peñoles", null));
    out.add(new Language("mim", "Alacatlatzala Mixtec", "I", "L", null, null, "Mixtec, Alacatlatzala", null));
    out.add(new Language("min", "Minangkabau", "I", "L", null, null, null, null));
    out.add(new Language("mio", "Pinotepa Nacional Mixtec", "I", "L", null, null, "Mixtec, Pinotepa Nacional", null));
    out.add(new Language("mip", "Apasco-Apoala Mixtec", "I", "L", null, null, "Mixtec, Apasco-Apoala", null));
    out.add(new Language("miq", "Mískito", "I", "L", null, null, null, null));
    out.add(new Language("mir", "Isthmus Mixe", "I", "L", null, null, "Mixe, Isthmus", null));
    out.add(new Language("mis", "Uncoded languages", "S", "S", null, null, null, null));
    out.add(new Language("mit", "Southern Puebla Mixtec", "I", "L", null, null, "Mixtec, Southern Puebla", null));
    out.add(new Language("miu", "Cacaloxtepec Mixtec", "I", "L", null, null, "Mixtec, Cacaloxtepec", null));
    out.add(new Language("miw", "Akoye", "I", "L", null, null, null, null));
    out.add(new Language("mix", "Mixtepec Mixtec", "I", "L", null, null, "Mixtec, Mixtepec", null));
    out.add(new Language("miy", "Ayutla Mixtec", "I", "L", null, null, "Mixtec, Ayutla", null));
    out.add(new Language("miz", "Coatzospan Mixtec", "I", "L", null, null, "Mixtec, Coatzospan", null));
    out.add(new Language("mjb", "Makalero", "I", "L", null, null, null, null));
    out.add(new Language("mjc", "San Juan Colorado Mixtec", "I", "L", null, null, "Mixtec, San Juan Colorado", null));
    out.add(new Language("mjd", "Northwest Maidu", "I", "L", null, null, "Maidu, Northwest", null));
    out.add(new Language("mje", "Muskum", "I", "E", null, null, null, null));
    out.add(new Language("mjg", "Tu", "I", "L", null, null, null, null));
    out.add(new Language("mjh", "Mwera (Nyasa)", "I", "L", null, null, null, null));
    out.add(new Language("mji", "Kim Mun", "I", "L", null, null, null, null));
    out.add(new Language("mjj", "Mawak", "I", "L", null, null, null, null));
    out.add(new Language("mjk", "Matukar", "I", "L", null, null, null, null));
    out.add(new Language("mjl", "Mandeali", "I", "L", null, null, null, null));
    out.add(new Language("mjm", "Medebur", "I", "L", null, null, null, null));
    out.add(new Language("mjn", "Ma (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("mjo", "Malankuravan", "I", "L", null, null, null, null));
    out.add(new Language("mjp", "Malapandaram", "I", "L", null, null, null, null));
    out.add(new Language("mjq", "Malaryan", "I", "E", null, null, null, null));
    out.add(new Language("mjr", "Malavedan", "I", "L", null, null, null, null));
    out.add(new Language("mjs", "Miship", "I", "L", null, null, null, null));
    out.add(new Language("mjt", "Sauria Paharia", "I", "L", null, null, null, null));
    out.add(new Language("mju", "Manna-Dora", "I", "L", null, null, null, null));
    out.add(new Language("mjv", "Mannan", "I", "L", null, null, null, null));
    out.add(new Language("mjw", "Karbi", "I", "L", null, null, null, null));
    out.add(new Language("mjx", "Mahali", "I", "L", null, null, null, null));
    out.add(new Language("mjy", "Mahican", "I", "E", null, null, null, null));
    out.add(new Language("mjz", "Majhi", "I", "L", null, null, null, null));
    out.add(new Language("mka", "Mbre", "I", "L", null, null, null, null));
    out.add(new Language("mkb", "Mal Paharia", "I", "L", null, null, null, null));
    out.add(new Language("mkc", "Siliput", "I", "L", null, null, null, null));
    out.add(new Language("mkd", "Macedonian", "I", "L", "mk", null, null, "mac"));
    out.add(new Language("mke", "Mawchi", "I", "L", null, null, null, null));
    out.add(new Language("mkf", "Miya", "I", "L", null, null, null, null));
    out.add(new Language("mkg", "Mak (China)", "I", "L", null, null, null, null));
    out.add(new Language("mki", "Dhatki", "I", "L", null, null, null, null));
    out.add(new Language("mkj", "Mokilese", "I", "L", null, null, null, null));
    out.add(new Language("mkk", "Byep", "I", "L", null, null, null, null));
    out.add(new Language("mkl", "Mokole", "I", "L", null, null, null, null));
    out.add(new Language("mkm", "Moklen", "I", "L", null, null, null, null));
    out.add(new Language("mkn", "Kupang Malay", "I", "L", null, null, "Malay, Kupang", null));
    out.add(new Language("mko", "Mingang Doso", "I", "L", null, null, null, null));
    out.add(new Language("mkp", "Moikodi", "I", "L", null, null, null, null));
    out.add(new Language("mkq", "Bay Miwok", "I", "E", null, null, "Miwok, Bay", null));
    out.add(new Language("mkr", "Malas", "I", "L", null, null, null, null));
    out.add(new Language("mks", "Silacayoapan Mixtec", "I", "L", null, null, "Mixtec, Silacayoapan", null));
    out.add(new Language("mkt", "Vamale", "I", "L", null, null, null, null));
    out.add(new Language("mku", "Konyanka Maninka", "I", "L", null, null, "Maninka, Konyanka", null));
    out.add(new Language("mkv", "Mafea", "I", "L", null, null, null, null));
    out.add(new Language("mkw", "Kituba (Congo)", "I", "L", null, null, null, null));
    out.add(new Language("mkx", "Kinamiging Manobo", "I", "L", null, null, "Manobo, Kinamiging", null));
    out.add(new Language("mky", "East Makian", "I", "L", null, null, "Makian, East", null));
    out.add(new Language("mkz", "Makasae", "I", "L", null, null, null, null));
    out.add(new Language("mla", "Malo", "I", "L", null, null, null, null));
    out.add(new Language("mlb", "Mbule", "I", "L", null, null, null, null));
    out.add(new Language("mlc", "Cao Lan", "I", "L", null, null, null, null));
    out.add(new Language("mle", "Manambu", "I", "L", null, null, null, null));
    out.add(new Language("mlf", "Mal", "I", "L", null, null, null, null));
    out.add(new Language("mlg", "Malagasy", "M", "L", "mg", null, null, null));
    out.add(new Language("mlh", "Mape", "I", "L", null, null, null, null));
    out.add(new Language("mli", "Malimpung", "I", "L", null, null, null, null));
    out.add(new Language("mlj", "Miltu", "I", "L", null, null, null, null));
    out.add(new Language("mlk", "Ilwana", "I", "L", null, null, null, null));
    out.add(new Language("mll", "Malua Bay", "I", "L", null, null, null, null));
    out.add(new Language("mlm", "Mulam", "I", "L", null, null, null, null));
    out.add(new Language("mln", "Malango", "I", "L", null, null, null, null));
    out.add(new Language("mlo", "Mlomp", "I", "L", null, null, null, null));
    out.add(new Language("mlp", "Bargam", "I", "L", null, null, null, null));
    out.add(new Language("mlq", "Western Maninkakan", "I", "L", null, null, "Maninkakan, Western", null));
    out.add(new Language("mlr", "Vame", "I", "L", null, null, null, null));
    out.add(new Language("mls", "Masalit", "I", "L", null, null, null, null));
    out.add(new Language("mlt", "Maltese", "I", "L", "mt", null, null, null));
    out.add(new Language("mlu", "To'abaita", "I", "L", null, null, null, null));
    out.add(new Language("mlv", "Motlav", "I", "L", null, null, null, null));
    out.add(new Language("mlw", "Moloko", "I", "L", null, null, null, null));
    out.add(new Language("mlx", "Malfaxal", "I", "L", null, null, null, null));
    out.add(new Language("mlz", "Malaynon", "I", "L", null, null, null, null));
    out.add(new Language("mma", "Mama", "I", "L", null, null, null, null));
    out.add(new Language("mmb", "Momina", "I", "L", null, null, null, null));
    out.add(new Language("mmc", "Michoacán Mazahua", "I", "L", null, null, "Mazahua, Michoacán", null));
    out.add(new Language("mmd", "Maonan", "I", "L", null, null, null, null));
    out.add(new Language("mme", "Mae", "I", "L", null, null, null, null));
    out.add(new Language("mmf", "Mundat", "I", "L", null, null, null, null));
    out.add(new Language("mmg", "North Ambrym", "I", "L", null, null, "Ambrym, North", null));
    out.add(new Language("mmh", "Mehináku", "I", "L", null, null, null, null));
    out.add(new Language("mmi", "Hember Avu", "I", "L", null, null, null, null));
    out.add(new Language("mmj", "Majhwar", "I", "L", null, null, null, null));
    out.add(new Language("mmk", "Mukha-Dora", "I", "L", null, null, null, null));
    out.add(new Language("mml", "Man Met", "I", "L", null, null, null, null));
    out.add(new Language("mmm", "Maii", "I", "L", null, null, null, null));
    out.add(new Language("mmn", "Mamanwa", "I", "L", null, null, null, null));
    out.add(new Language("mmo", "Mangga Buang", "I", "L", null, null, "Buang, Mangga", null));
    out.add(new Language("mmp", "Siawi", "I", "L", null, null, null, null));
    out.add(new Language("mmq", "Musak", "I", "L", null, null, null, null));
    out.add(new Language("mmr", "Western Xiangxi Miao", "I", "L", null, null, "Miao, Western Xiangxi", null));
    out.add(new Language("mmt", "Malalamai", "I", "L", null, null, null, null));
    out.add(new Language("mmu", "Mmaala", "I", "L", null, null, null, null));
    out.add(new Language("mmv", "Miriti", "I", "E", null, null, null, null));
    out.add(new Language("mmw", "Emae", "I", "L", null, null, null, null));
    out.add(new Language("mmx", "Madak", "I", "L", null, null, null, null));
    out.add(new Language("mmy", "Migaama", "I", "L", null, null, null, null));
    out.add(new Language("mmz", "Mabaale", "I", "L", null, null, null, null));
    out.add(new Language("mna", "Mbula", "I", "L", null, null, null, null));
    out.add(new Language("mnb", "Muna", "I", "L", null, null, null, null));
    out.add(new Language("mnc", "Manchu", "I", "L", null, null, null, null));
    out.add(new Language("mnd", "Mondé", "I", "L", null, null, null, null));
    out.add(new Language("mne", "Naba", "I", "L", null, null, null, null));
    out.add(new Language("mnf", "Mundani", "I", "L", null, null, null, null));
    out.add(new Language("mng", "Eastern Mnong", "I", "L", null, null, "Mnong, Eastern", null));
    out.add(new Language("mnh", "Mono (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("mni", "Manipuri", "I", "L", null, null, null, null));
    out.add(new Language("mnj", "Munji", "I", "L", null, null, null, null));
    out.add(new Language("mnk", "Mandinka", "I", "L", null, null, null, null));
    out.add(new Language("mnl", "Tiale", "I", "L", null, null, null, null));
    out.add(new Language("mnm", "Mapena", "I", "L", null, null, null, null));
    out.add(new Language("mnn", "Southern Mnong", "I", "L", null, null, "Mnong, Southern", null));
    out.add(new Language("mnp", "Min Bei Chinese", "I", "L", null, null, "Chinese, Min Bei", null));
    out.add(new Language("mnq", "Minriq", "I", "L", null, null, null, null));
    out.add(new Language("mnr", "Mono (USA)", "I", "L", null, null, null, null));
    out.add(new Language("mns", "Mansi", "I", "L", null, null, null, null));
    out.add(new Language("mnu", "Mer", "I", "L", null, null, null, null));
    out.add(new Language("mnv", "Rennell-Bellona", "I", "L", null, null, null, null));
    out.add(new Language("mnw", "Mon", "I", "L", null, null, null, null));
    out.add(new Language("mnx", "Manikion", "I", "L", null, null, null, null));
    out.add(new Language("mny", "Manyawa", "I", "L", null, null, null, null));
    out.add(new Language("mnz", "Moni", "I", "L", null, null, null, null));
    out.add(new Language("moa", "Mwan", "I", "L", null, null, null, null));
    out.add(new Language("moc", "Mocoví", "I", "L", null, null, null, null));
    out.add(new Language("mod", "Mobilian", "I", "E", null, null, null, null));
    out.add(new Language("moe", "Innu", "I", "L", null, null, null, null));
    out.add(new Language("mog", "Mongondow", "I", "L", null, null, null, null));
    out.add(new Language("moh", "Mohawk", "I", "L", null, null, null, null));
    out.add(new Language("moi", "Mboi", "I", "L", null, null, null, null));
    out.add(new Language("moj", "Monzombo", "I", "L", null, null, null, null));
    out.add(new Language("mok", "Morori", "I", "L", null, null, null, null));
    out.add(new Language("mom", "Mangue", "I", "E", null, null, null, null));
    out.add(new Language("mon", "Mongolian", "M", "L", "mn", null, null, null));
    out.add(new Language("moo", "Monom", "I", "L", null, null, null, null));
    out.add(new Language("mop", "Mopán Maya", "I", "L", null, null, null, null));
    out.add(new Language("moq", "Mor (Bomberai Peninsula)", "I", "L", null, null, null, null));
    out.add(new Language("mor", "Moro", "I", "L", null, null, null, null));
    out.add(new Language("mos", "Mossi", "I", "L", null, null, null, null));
    out.add(new Language("mot", "Barí", "I", "L", null, null, null, null));
    out.add(new Language("mou", "Mogum", "I", "L", null, null, null, null));
    out.add(new Language("mov", "Mohave", "I", "L", null, null, null, null));
    out.add(new Language("mow", "Moi (Congo)", "I", "L", null, null, null, null));
    out.add(new Language("mox", "Molima", "I", "L", null, null, null, null));
    out.add(new Language("moy", "Shekkacho", "I", "L", null, null, null, null));
    out.add(new Language("moz", "Mukulu", "I", "L", null, null, null, null));
    out.add(new Language("mpa", "Mpoto", "I", "L", null, null, null, null));
    out.add(new Language("mpb", "Malak Malak", "I", "L", null, null, null, null));
    out.add(new Language("mpc", "Mangarrayi", "I", "L", null, null, null, null));
    out.add(new Language("mpd", "Machinere", "I", "L", null, null, null, null));
    out.add(new Language("mpe", "Majang", "I", "L", null, null, null, null));
    out.add(new Language("mpg", "Marba", "I", "L", null, null, null, null));
    out.add(new Language("mph", "Maung", "I", "L", null, null, null, null));
    out.add(new Language("mpi", "Mpade", "I", "L", null, null, null, null));
    out.add(new Language("mpj", "Martu Wangka", "I", "L", null, null, null, null));
    out.add(new Language("mpk", "Mbara (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("mpl", "Middle Watut", "I", "L", null, null, "Watut, Middle", null));
    out.add(new Language("mpm", "Yosondúa Mixtec", "I", "L", null, null, "Mixtec, Yosondúa", null));
    out.add(new Language("mpn", "Mindiri", "I", "L", null, null, null, null));
    out.add(new Language("mpo", "Miu", "I", "L", null, null, null, null));
    out.add(new Language("mpp", "Migabac", "I", "L", null, null, null, null));
    out.add(new Language("mpq", "Matís", "I", "L", null, null, null, null));
    out.add(new Language("mpr", "Vangunu", "I", "L", null, null, null, null));
    out.add(new Language("mps", "Dadibi", "I", "L", null, null, null, null));
    out.add(new Language("mpt", "Mian", "I", "L", null, null, null, null));
    out.add(new Language("mpu", "Makuráp", "I", "L", null, null, null, null));
    out.add(new Language("mpv", "Mungkip", "I", "L", null, null, null, null));
    out.add(new Language("mpw", "Mapidian", "I", "L", null, null, null, null));
    out.add(new Language("mpx", "Misima-Panaeati", "I", "L", null, null, null, null));
    out.add(new Language("mpy", "Mapia", "I", "L", null, null, null, null));
    out.add(new Language("mpz", "Mpi", "I", "L", null, null, null, null));
    out.add(new Language("mqa", "Maba (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("mqb", "Mbuko", "I", "L", null, null, null, null));
    out.add(new Language("mqc", "Mangole", "I", "L", null, null, null, null));
    out.add(new Language("mqe", "Matepi", "I", "L", null, null, null, null));
    out.add(new Language("mqf", "Momuna", "I", "L", null, null, null, null));
    out.add(new Language("mqg", "Kota Bangun Kutai Malay", "I", "L", null, null, "Malay, Kota Bangun Kutai", null));
    out.add(new Language("mqh", "Tlazoyaltepec Mixtec", "I", "L", null, null, "Mixtec, Tlazoyaltepec", null));
    out.add(new Language("mqi", "Mariri", "I", "L", null, null, null, null));
    out.add(new Language("mqj", "Mamasa", "I", "L", null, null, null, null));
    out.add(new Language("mqk", "Rajah Kabunsuwan Manobo", "I", "L", null, null, "Manobo, Rajah Kabunsuwan", null));
    out.add(new Language("mql", "Mbelime", "I", "L", null, null, null, null));
    out.add(new Language("mqm", "South Marquesan", "I", "L", null, null, "Marquesan, South", null));
    out.add(new Language("mqn", "Moronene", "I", "L", null, null, null, null));
    out.add(new Language("mqo", "Modole", "I", "L", null, null, null, null));
    out.add(new Language("mqp", "Manipa", "I", "L", null, null, null, null));
    out.add(new Language("mqq", "Minokok", "I", "L", null, null, null, null));
    out.add(new Language("mqr", "Mander", "I", "L", null, null, null, null));
    out.add(new Language("mqs", "West Makian", "I", "L", null, null, "Makian, West", null));
    out.add(new Language("mqt", "Mok", "I", "L", null, null, null, null));
    out.add(new Language("mqu", "Mandari", "I", "L", null, null, null, null));
    out.add(new Language("mqv", "Mosimo", "I", "L", null, null, null, null));
    out.add(new Language("mqw", "Murupi", "I", "L", null, null, null, null));
    out.add(new Language("mqx", "Mamuju", "I", "L", null, null, null, null));
    out.add(new Language("mqy", "Manggarai", "I", "L", null, null, null, null));
    out.add(new Language("mqz", "Pano", "I", "L", null, null, null, null));
    out.add(new Language("mra", "Mlabri", "I", "L", null, null, null, null));
    out.add(new Language("mrb", "Marino", "I", "L", null, null, null, null));
    out.add(new Language("mrc", "Maricopa", "I", "L", null, null, null, null));
    out.add(new Language("mrd", "Western Magar", "I", "L", null, null, "Magar, Western", null));
    out.add(new Language("mre", "Martha's Vineyard Sign Language", "I", "E", null, null, null, null));
    out.add(new Language("mrf", "Elseng", "I", "L", null, null, null, null));
    out.add(new Language("mrg", "Mising", "I", "L", null, null, null, null));
    out.add(new Language("mrh", "Mara Chin", "I", "L", null, null, "Chin, Mara", null));
    out.add(new Language("mri", "Maori", "I", "L", "mi", null, null, "mao"));
    out.add(new Language("mrj", "Western Mari", "I", "L", null, null, "Mari, Western", null));
    out.add(new Language("mrk", "Hmwaveke", "I", "L", null, null, null, null));
    out.add(new Language("mrl", "Mortlockese", "I", "L", null, null, null, null));
    out.add(new Language("mrm", "Merlav", "I", "L", null, null, null, null));
    out.add(new Language("mrn", "Cheke Holo", "I", "L", null, null, null, null));
    out.add(new Language("mro", "Mru", "I", "L", null, null, null, null));
    out.add(new Language("mrp", "Morouas", "I", "L", null, null, null, null));
    out.add(new Language("mrq", "North Marquesan", "I", "L", null, null, "Marquesan, North", null));
    out.add(new Language("mrr", "Maria (India)", "I", "L", null, null, null, null));
    out.add(new Language("mrs", "Maragus", "I", "L", null, null, null, null));
    out.add(new Language("mrt", "Marghi Central", "I", "L", null, null, null, null));
    out.add(new Language("mru", "Mono (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("mrv", "Mangareva", "I", "L", null, null, null, null));
    out.add(new Language("mrw", "Maranao", "I", "L", null, null, null, null));
    out.add(new Language("mrx", "Maremgi", "I", "L", null, null, null, null));
    out.add(new Language("mry", "Mandaya", "I", "L", null, null, null, null));
    out.add(new Language("mrz", "Marind", "I", "L", null, null, null, null));
    out.add(new Language("msa", "Malay (macrolanguage)", "M", "L", "ms", null, null, "may"));
    out.add(new Language("msb", "Masbatenyo", "I", "L", null, null, null, null));
    out.add(new Language("msc", "Sankaran Maninka", "I", "L", null, null, "Maninka, Sankaran", null));
    out.add(new Language("msd", "Yucatec Maya Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mse", "Musey", "I", "L", null, null, null, null));
    out.add(new Language("msf", "Mekwei", "I", "L", null, null, null, null));
    out.add(new Language("msg", "Moraid", "I", "L", null, null, null, null));
    out.add(new Language("msh", "Masikoro Malagasy", "I", "L", null, null, "Malagasy, Masikoro", null));
    out.add(new Language("msi", "Sabah Malay", "I", "L", null, null, "Malay, Sabah", null));
    out.add(new Language("msj", "Ma (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("msk", "Mansaka", "I", "L", null, null, null, null));
    out.add(new Language("msl", "Molof", "I", "L", null, null, null, null));
    out.add(new Language("msm", "Agusan Manobo", "I", "L", null, null, "Manobo, Agusan", null));
    out.add(new Language("msn", "Vurës", "I", "L", null, null, null, null));
    out.add(new Language("mso", "Mombum", "I", "L", null, null, null, null));
    out.add(new Language("msp", "Maritsauá", "I", "E", null, null, null, null));
    out.add(new Language("msq", "Caac", "I", "L", null, null, null, null));
    out.add(new Language("msr", "Mongolian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mss", "West Masela", "I", "L", null, null, "Masela, West", null));
    out.add(new Language("msu", "Musom", "I", "L", null, null, null, null));
    out.add(new Language("msv", "Maslam", "I", "L", null, null, null, null));
    out.add(new Language("msw", "Mansoanka", "I", "L", null, null, null, null));
    out.add(new Language("msx", "Moresada", "I", "L", null, null, null, null));
    out.add(new Language("msy", "Aruamu", "I", "L", null, null, null, null));
    out.add(new Language("msz", "Momare", "I", "L", null, null, null, null));
    out.add(new Language("mta", "Cotabato Manobo", "I", "L", null, null, "Manobo, Cotabato", null));
    out.add(new Language("mtb", "Anyin Morofo", "I", "L", null, null, null, null));
    out.add(new Language("mtc", "Munit", "I", "L", null, null, null, null));
    out.add(new Language("mtd", "Mualang", "I", "L", null, null, null, null));
    out.add(new Language("mte", "Mono (Solomon Islands)", "I", "L", null, null, null, null));
    out.add(new Language("mtf", "Murik (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("mtg", "Una", "I", "L", null, null, null, null));
    out.add(new Language("mth", "Munggui", "I", "L", null, null, null, null));
    out.add(new Language("mti", "Maiwa (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("mtj", "Moskona", "I", "L", null, null, null, null));
    out.add(new Language("mtk", "Mbe'", "I", "L", null, null, null, null));
    out.add(new Language("mtl", "Montol", "I", "L", null, null, null, null));
    out.add(new Language("mtm", "Mator", "I", "E", null, null, null, null));
    out.add(new Language("mtn", "Matagalpa", "I", "E", null, null, null, null));
    out.add(new Language("mto", "Totontepec Mixe", "I", "L", null, null, "Mixe, Totontepec", null));
    out.add(new Language("mtp", "Wichí Lhamtés Nocten", "I", "L", null, null, null, null));
    out.add(new Language("mtq", "Muong", "I", "L", null, null, null, null));
    out.add(new Language("mtr", "Mewari", "I", "L", null, null, null, null));
    out.add(new Language("mts", "Yora", "I", "L", null, null, null, null));
    out.add(new Language("mtt", "Mota", "I", "L", null, null, null, null));
    out.add(new Language("mtu", "Tututepec Mixtec", "I", "L", null, null, "Mixtec, Tututepec", null));
    out.add(new Language("mtv", "Asaro'o", "I", "L", null, null, null, null));
    out.add(new Language("mtw", "Southern Binukidnon", "I", "L", null, null, "Binukidnon, Southern", null));
    out.add(new Language("mtx", "Tidaá Mixtec", "I", "L", null, null, "Mixtec, Tidaá", null));
    out.add(new Language("mty", "Nabi", "I", "L", null, null, null, null));
    out.add(new Language("mua", "Mundang", "I", "L", null, null, null, null));
    out.add(new Language("mub", "Mubi", "I", "L", null, null, null, null));
    out.add(new Language("muc", "Ajumbu", "I", "L", null, null, null, null));
    out.add(new Language("mud", "Mednyj Aleut", "I", "L", null, null, "Aleut, Mednyj", null));
    out.add(new Language("mue", "Media Lengua", "I", "L", null, null, null, null));
    out.add(new Language("mug", "Musgu", "I", "L", null, null, null, null));
    out.add(new Language("muh", "Mündü", "I", "L", null, null, null, null));
    out.add(new Language("mui", "Musi", "I", "L", null, null, null, null));
    out.add(new Language("muj", "Mabire", "I", "L", null, null, null, null));
    out.add(new Language("muk", "Mugom", "I", "L", null, null, null, null));
    out.add(new Language("mul", "Multiple languages", "S", "S", null, null, null, null));
    out.add(new Language("mum", "Maiwala", "I", "L", null, null, null, null));
    out.add(new Language("muo", "Nyong", "I", "L", null, null, null, null));
    out.add(new Language("mup", "Malvi", "I", "L", null, null, null, null));
    out.add(new Language("muq", "Eastern Xiangxi Miao", "I", "L", null, null, "Miao, Eastern Xiangxi", null));
    out.add(new Language("mur", "Murle", "I", "L", null, null, null, null));
    out.add(new Language("mus", "Creek", "I", "L", null, null, null, null));
    out.add(new Language("mut", "Western Muria", "I", "L", null, null, "Muria, Western", null));
    out.add(new Language("muu", "Yaaku", "I", "L", null, null, null, null));
    out.add(new Language("muv", "Muthuvan", "I", "L", null, null, null, null));
    out.add(new Language("mux", "Bo-Ung", "I", "L", null, null, null, null));
    out.add(new Language("muy", "Muyang", "I", "L", null, null, null, null));
    out.add(new Language("muz", "Mursi", "I", "L", null, null, null, null));
    out.add(new Language("mva", "Manam", "I", "L", null, null, null, null));
    out.add(new Language("mvb", "Mattole", "I", "E", null, null, null, null));
    out.add(new Language("mvd", "Mamboru", "I", "L", null, null, null, null));
    out.add(new Language("mve", "Marwari (Pakistan)", "I", "L", null, null, null, null));
    out.add(new Language("mvf", "Peripheral Mongolian", "I", "L", null, null, "Mongolian, Peripheral", null));
    out.add(new Language("mvg", "Yucuañe Mixtec", "I", "L", null, null, "Mixtec, Yucuañe", null));
    out.add(new Language("mvh", "Mulgi", "I", "L", null, null, null, null));
    out.add(new Language("mvi", "Miyako", "I", "L", null, null, null, null));
    out.add(new Language("mvk", "Mekmek", "I", "L", null, null, null, null));
    out.add(new Language("mvl", "Mbara (Australia)", "I", "E", null, null, null, null));
    out.add(new Language("mvn", "Minaveha", "I", "L", null, null, null, null));
    out.add(new Language("mvo", "Marovo", "I", "L", null, null, null, null));
    out.add(new Language("mvp", "Duri", "I", "L", null, null, null, null));
    out.add(new Language("mvq", "Moere", "I", "L", null, null, null, null));
    out.add(new Language("mvr", "Marau", "I", "L", null, null, null, null));
    out.add(new Language("mvs", "Massep", "I", "L", null, null, null, null));
    out.add(new Language("mvt", "Mpotovoro", "I", "L", null, null, null, null));
    out.add(new Language("mvu", "Marfa", "I", "L", null, null, null, null));
    out.add(new Language("mvv", "Tagal Murut", "I", "L", null, null, "Murut, Tagal", null));
    out.add(new Language("mvw", "Machinga", "I", "L", null, null, null, null));
    out.add(new Language("mvx", "Meoswar", "I", "L", null, null, null, null));
    out.add(new Language("mvy", "Indus Kohistani", "I", "L", null, null, "Kohistani, Indus", null));
    out.add(new Language("mvz", "Mesqan", "I", "L", null, null, null, null));
    out.add(new Language("mwa", "Mwatebu", "I", "L", null, null, null, null));
    out.add(new Language("mwb", "Juwal", "I", "L", null, null, null, null));
    out.add(new Language("mwc", "Are", "I", "L", null, null, null, null));
    out.add(new Language("mwe", "Mwera (Chimwera)", "I", "L", null, null, null, null));
    out.add(new Language("mwf", "Murrinh-Patha", "I", "L", null, null, null, null));
    out.add(new Language("mwg", "Aiklep", "I", "L", null, null, null, null));
    out.add(new Language("mwh", "Mouk-Aria", "I", "L", null, null, null, null));
    out.add(new Language("mwi", "Labo", "I", "L", null, null, null, null));
    out.add(new Language("mwk", "Kita Maninkakan", "I", "L", null, null, "Maninkakan, Kita", null));
    out.add(new Language("mwl", "Mirandese", "I", "L", null, null, null, null));
    out.add(new Language("mwm", "Sar", "I", "L", null, null, null, null));
    out.add(new Language("mwn", "Nyamwanga", "I", "L", null, null, null, null));
    out.add(new Language("mwo", "Central Maewo", "I", "L", null, null, "Maewo, Central", null));
    out.add(new Language("mwp", "Kala Lagaw Ya", "I", "L", null, null, null, null));
    out.add(new Language("mwq", "Mün Chin", "I", "L", null, null, "Chin, Mün", null));
    out.add(new Language("mwr", "Marwari", "M", "L", null, null, null, null));
    out.add(new Language("mws", "Mwimbi-Muthambi", "I", "L", null, null, null, null));
    out.add(new Language("mwt", "Moken", "I", "L", null, null, null, null));
    out.add(new Language("mwu", "Mittu", "I", "E", null, null, null, null));
    out.add(new Language("mwv", "Mentawai", "I", "L", null, null, null, null));
    out.add(new Language("mww", "Hmong Daw", "I", "L", null, null, null, null));
    out.add(new Language("mwz", "Moingi", "I", "L", null, null, null, null));
    out.add(new Language("mxa", "Northwest Oaxaca Mixtec", "I", "L", null, null, "Mixtec, Northwest Oaxaca", null));
    out.add(new Language("mxb", "Tezoatlán Mixtec", "I", "L", null, null, "Mixtec, Tezoatlán", null));
    out.add(new Language("mxc", "Manyika", "I", "L", null, null, null, null));
    out.add(new Language("mxd", "Modang", "I", "L", null, null, null, null));
    out.add(new Language("mxe", "Mele-Fila", "I", "L", null, null, null, null));
    out.add(new Language("mxf", "Malgbe", "I", "L", null, null, null, null));
    out.add(new Language("mxg", "Mbangala", "I", "L", null, null, null, null));
    out.add(new Language("mxh", "Mvuba", "I", "L", null, null, null, null));
    out.add(new Language("mxi", "Mozarabic", "I", "H", null, null, null, null));
    out.add(new Language("mxj", "Miju-Mishmi", "I", "L", null, null, null, null));
    out.add(new Language("mxk", "Monumbo", "I", "L", null, null, null, null));
    out.add(new Language("mxl", "Maxi Gbe", "I", "L", null, null, "Gbe, Maxi", null));
    out.add(new Language("mxm", "Meramera", "I", "L", null, null, null, null));
    out.add(new Language("mxn", "Moi (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("mxo", "Mbowe", "I", "L", null, null, null, null));
    out.add(new Language("mxp", "Tlahuitoltepec Mixe", "I", "L", null, null, "Mixe, Tlahuitoltepec", null));
    out.add(new Language("mxq", "Juquila Mixe", "I", "L", null, null, "Mixe, Juquila", null));
    out.add(new Language("mxr", "Murik (Malaysia)", "I", "L", null, null, null, null));
    out.add(new Language("mxs", "Huitepec Mixtec", "I", "L", null, null, "Mixtec, Huitepec", null));
    out.add(new Language("mxt", "Jamiltepec Mixtec", "I", "L", null, null, "Mixtec, Jamiltepec", null));
    out.add(new Language("mxu", "Mada (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("mxv", "Metlatónoc Mixtec", "I", "L", null, null, "Mixtec, Metlatónoc", null));
    out.add(new Language("mxw", "Namo", "I", "L", null, null, null, null));
    out.add(new Language("mxx", "Mahou", "I", "L", null, null, null, null));
    out.add(new Language("mxy", "Southeastern Nochixtlán Mixtec", "I", "L", null, null, "Mixtec, Southeastern Nochixtlán", null));
    out.add(new Language("mxz", "Central Masela", "I", "L", null, null, "Masela, Central", null));
    out.add(new Language("mya", "Burmese", "I", "L", "my", null, null, "bur"));
    out.add(new Language("myb", "Mbay", "I", "L", null, null, null, null));
    out.add(new Language("myc", "Mayeka", "I", "L", null, null, null, null));
    out.add(new Language("mye", "Myene", "I", "L", null, null, null, null));
    out.add(new Language("myf", "Bambassi", "I", "L", null, null, null, null));
    out.add(new Language("myg", "Manta", "I", "L", null, null, null, null));
    out.add(new Language("myh", "Makah", "I", "L", null, null, null, null));
    out.add(new Language("myj", "Mangayat", "I", "L", null, null, null, null));
    out.add(new Language("myk", "Mamara Senoufo", "I", "L", null, null, "Senoufo, Mamara", null));
    out.add(new Language("myl", "Moma", "I", "L", null, null, null, null));
    out.add(new Language("mym", "Me'en", "I", "L", null, null, null, null));
    out.add(new Language("myo", "Anfillo", "I", "L", null, null, null, null));
    out.add(new Language("myp", "Pirahã", "I", "L", null, null, null, null));
    out.add(new Language("myr", "Muniche", "I", "L", null, null, null, null));
    out.add(new Language("mys", "Mesmes", "I", "E", null, null, null, null));
    out.add(new Language("myu", "Mundurukú", "I", "L", null, null, null, null));
    out.add(new Language("myv", "Erzya", "I", "L", null, null, null, null));
    out.add(new Language("myw", "Muyuw", "I", "L", null, null, null, null));
    out.add(new Language("myx", "Masaaba", "I", "L", null, null, null, null));
    out.add(new Language("myy", "Macuna", "I", "L", null, null, null, null));
    out.add(new Language("myz", "Classical Mandaic", "I", "H", null, null, "Mandaic, Classical", null));
    out.add(new Language("mza", "Santa María Zacatepec Mixtec", "I", "L", null, null, "Mixtec, Santa María Zacatepec", null));
    out.add(new Language("mzb", "Tumzabt", "I", "L", null, null, null, null));
    out.add(new Language("mzc", "Madagascar Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mzd", "Malimba", "I", "L", null, null, null, null));
    out.add(new Language("mze", "Morawa", "I", "L", null, null, null, null));
    out.add(new Language("mzg", "Monastic Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mzh", "Wichí Lhamtés Güisnay", "I", "L", null, null, null, null));
    out.add(new Language("mzi", "Ixcatlán Mazatec", "I", "L", null, null, "Mazatec, Ixcatlán", null));
    out.add(new Language("mzj", "Manya", "I", "L", null, null, null, null));
    out.add(new Language("mzk", "Nigeria Mambila", "I", "L", null, null, "Mambila, Nigeria", null));
    out.add(new Language("mzl", "Mazatlán Mixe", "I", "L", null, null, "Mixe, Mazatlán", null));
    out.add(new Language("mzm", "Mumuye", "I", "L", null, null, null, null));
    out.add(new Language("mzn", "Mazanderani", "I", "L", null, null, null, null));
    out.add(new Language("mzo", "Matipuhy", "I", "E", null, null, null, null));
    out.add(new Language("mzp", "Movima", "I", "L", null, null, null, null));
    out.add(new Language("mzq", "Mori Atas", "I", "L", null, null, null, null));
    out.add(new Language("mzr", "Marúbo", "I", "L", null, null, null, null));
    out.add(new Language("mzs", "Macanese", "I", "L", null, null, null, null));
    out.add(new Language("mzt", "Mintil", "I", "L", null, null, null, null));
    out.add(new Language("mzu", "Inapang", "I", "L", null, null, null, null));
    out.add(new Language("mzv", "Manza", "I", "L", null, null, null, null));
    out.add(new Language("mzw", "Deg", "I", "L", null, null, null, null));
    out.add(new Language("mzx", "Mawayana", "I", "L", null, null, null, null));
    out.add(new Language("mzy", "Mozambican Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("mzz", "Maiadomu", "I", "L", null, null, null, null));
    out.add(new Language("naa", "Namla", "I", "L", null, null, null, null));
    out.add(new Language("nab", "Southern Nambikuára", "I", "L", null, null, "Nambikuára, Southern", null));
    out.add(new Language("nac", "Narak", "I", "L", null, null, null, null));
    out.add(new Language("nae", "Naka'ela", "I", "E", null, null, null, null));
    out.add(new Language("naf", "Nabak", "I", "L", null, null, null, null));
    out.add(new Language("nag", "Naga Pidgin", "I", "L", null, null, null, null));
    out.add(new Language("naj", "Nalu", "I", "L", null, null, null, null));
    out.add(new Language("nak", "Nakanai", "I", "L", null, null, null, null));
    out.add(new Language("nal", "Nalik", "I", "L", null, null, null, null));
    out.add(new Language("nam", "Ngan'gityemerri", "I", "L", null, null, null, null));
    out.add(new Language("nan", "Min Nan Chinese", "I", "L", null, null, "Chinese, Min Nan", null));
    out.add(new Language("nao", "Naaba", "I", "L", null, null, null, null));
    out.add(new Language("nap", "Neapolitan", "I", "L", null, null, null, null));
    out.add(new Language("naq", "Khoekhoe", "I", "L", null, null, null, null));
    out.add(new Language("nar", "Iguta", "I", "L", null, null, null, null));
    out.add(new Language("nas", "Naasioi", "I", "L", null, null, null, null));
    out.add(new Language("nat", "Ca̱hungwa̱rya̱", "I", "L", null, null, null, null));
    out.add(new Language("nau", "Nauru", "I", "L", "na", null, null, null));
    out.add(new Language("nav", "Navajo", "I", "L", "nv", null, null, null));
    out.add(new Language("naw", "Nawuri", "I", "L", null, null, null, null));
    out.add(new Language("nax", "Nakwi", "I", "L", null, null, null, null));
    out.add(new Language("nay", "Ngarrindjeri", "I", "E", null, null, null, null));
    out.add(new Language("naz", "Coatepec Nahuatl", "I", "L", null, null, "Nahuatl, Coatepec", null));
    out.add(new Language("nba", "Nyemba", "I", "L", null, null, null, null));
    out.add(new Language("nbb", "Ndoe", "I", "L", null, null, null, null));
    out.add(new Language("nbc", "Chang Naga", "I", "L", null, null, "Naga, Chang", null));
    out.add(new Language("nbd", "Ngbinda", "I", "L", null, null, null, null));
    out.add(new Language("nbe", "Konyak Naga", "I", "L", null, null, "Naga, Konyak", null));
    out.add(new Language("nbg", "Nagarchal", "I", "L", null, null, null, null));
    out.add(new Language("nbh", "Ngamo", "I", "L", null, null, null, null));
    out.add(new Language("nbi", "Mao Naga", "I", "L", null, null, "Naga, Mao", null));
    out.add(new Language("nbj", "Ngarinyman", "I", "L", null, null, null, null));
    out.add(new Language("nbk", "Nake", "I", "L", null, null, null, null));
    out.add(new Language("nbl", "South Ndebele", "I", "L", "nr", null, "Ndebele, South", null));
    out.add(new Language("nbm", "Ngbaka Ma'bo", "I", "L", null, null, null, null));
    out.add(new Language("nbn", "Kuri", "I", "L", null, null, null, null));
    out.add(new Language("nbo", "Nkukoli", "I", "L", null, null, null, null));
    out.add(new Language("nbp", "Nnam", "I", "L", null, null, null, null));
    out.add(new Language("nbq", "Nggem", "I", "L", null, null, null, null));
    out.add(new Language("nbr", "Numana", "I", "L", null, null, null, null));
  }
}
