// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 4500 to 4999 of {@link Language}.
 */
final class LanguageData9 {
  private LanguageData9() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("nbs", "Namibian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nbt", "Na", "I", "L", null, null, null, null));
    out.add(new Language("nbu", "Rongmei Naga", "I", "L", null, null, "Naga, Rongmei", null));
    out.add(new Language("nbv", "Ngamambo", "I", "L", null, null, null, null));
    out.add(new Language("nbw", "Southern Ngbandi", "I", "L", null, null, "Ngbandi, Southern", null));
    out.add(new Language("nby", "Ningera", "I", "L", null, null, null, null));
    out.add(new Language("nca", "Iyo", "I", "L", null, null, null, null));
    out.add(new Language("ncb", "Central Nicobarese", "I", "L", null, null, "Nicobarese, Central", null));
    out.add(new Language("ncc", "Ponam", "I", "L", null, null, null, null));
    out.add(new Language("ncd", "Nachering", "I", "L", null, null, null, null));
    out.add(new Language("nce", "Yale", "I", "L", null, null, null, null));
    out.add(new Language("ncf", "Notsi", "I", "L", null, null, null, null));
    out.add(new Language("ncg", "Nisga'a", "I", "L", null, null, null, null));
    out.add(new Language("nch", "Central Huasteca Nahuatl", "I", "L", null, null, "Nahuatl, Central Huasteca", null));
    out.add(new Language("nci", "Classical Nahuatl", "I", "H", null, null, "Nahuatl, Classical", null));
    out.add(new Language("ncj", "Northern Puebla Nahuatl", "I", "L", null, null, "Nahuatl, Northern Puebla", null));
    out.add(new Language("nck", "Na-kara", "I", "L", null, null, null, null));
    out.add(new Language("ncl", "Michoacán Nahuatl", "I", "L", null, null, "Nahuatl, Michoacán", null));
    out.add(new Language("ncm", "Nambo", "I", "L", null, null, null, null));
    out.add(new Language("ncn", "Nauna", "I", "L", null, null, null, null));
    out.add(new Language("nco", "Sibe", "I", "L", null, null, null, null));
    out.add(new Language("ncq", "Northern Katang", "I", "L", null, null, "Katang, Northern", null));
    out.add(new Language("ncr", "Ncane", "I", "L", null, null, null, null));
    out.add(new Language("ncs", "Nicaraguan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nct", "Chothe Naga", "I", "L", null, null, "Naga, Chothe", null));
    out.add(new Language("ncu", "Chumburung", "I", "L", null, null, null, null));
    out.add(new Language("ncx", "Central Puebla Nahuatl", "I", "L", null, null, "Nahuatl, Central Puebla", null));
    out.add(new Language("ncz", "Natchez", "I", "E", null, null, null, null));
    out.add(new Language("nda", "Ndasa", "I", "L", null, null, null, null));
    out.add(new Language("ndb", "Kenswei Nsei", "I", "L", null, null, null, null));
    out.add(new Language("ndc", "Ndau", "I", "L", null, null, null, null));
    out.add(new Language("ndd", "Nde-Nsele-Nta", "I", "L", null, null, null, null));
    out.add(new Language("nde", "North Ndebele", "I", "L", "nd", null, "Ndebele, North", null));
    out.add(new Language("ndf", "Nadruvian", "I", "H", null, null, null, null));
    out.add(new Language("ndg", "Ndengereko", "I", "L", null, null, null, null));
    out.add(new Language("ndh", "Ndali", "I", "L", null, null, null, null));
    out.add(new Language("ndi", "Samba Leko", "I", "L", null, null, null, null));
    out.add(new Language("ndj", "Ndamba", "I", "L", null, null, null, null));
    out.add(new Language("ndk", "Ndaka", "I", "L", null, null, null, null));
    out.add(new Language("ndl", "Ndolo", "I", "L", null, null, null, null));
    out.add(new Language("ndm", "Ndam", "I", "L", null, null, null, null));
    out.add(new Language("ndn", "Ngundi", "I", "L", null, null, null, null));
    out.add(new Language("ndo", "Ndonga", "I", "L", "ng", null, null, null));
    out.add(new Language("ndp", "Ndo", "I", "L", null, null, null, null));
    out.add(new Language("ndq", "Ndombe", "I", "L", null, null, null, null));
    out.add(new Language("ndr", "Ndoola", "I", "L", null, null, null, null));
    out.add(new Language("nds", "Low German", "I", "L", null, null, "German, Low", null));
    out.add(new Language("ndt", "Ndunga", "I", "L", null, null, null, null));
    out.add(new Language("ndu", "Dugun", "I", "L", null, null, null, null));
    out.add(new Language("ndv", "Ndut", "I", "L", null, null, null, null));
    out.add(new Language("ndw", "Ndobo", "I", "L", null, null, null, null));
    out.add(new Language("ndx", "Nduga", "I", "L", null, null, null, null));
    out.add(new Language("ndy", "Lutos", "I", "L", null, null, null, null));
    out.add(new Language("ndz", "Ndogo", "I", "L", null, null, null, null));
    out.add(new Language("nea", "Eastern Ngad'a", "I", "L", null, null, "Ngad'a, Eastern", null));
    out.add(new Language("neb", "Toura (Côte d'Ivoire)", "I", "L", null, null, null, null));
    out.add(new Language("nec", "Nedebang", "I", "L", null, null, null, null));
    out.add(new Language("ned", "Nde-Gbite", "I", "L", null, null, null, null));
    out.add(new Language("nee", "Nêlêmwa-Nixumwak", "I", "L", null, null, null, null));
    out.add(new Language("nef", "Nefamese", "I", "L", null, null, null, null));
    out.add(new Language("neg", "Negidal", "I", "L", null, null, null, null));
    out.add(new Language("neh", "Nyenkha", "I", "L", null, null, null, null));
    out.add(new Language("nei", "Neo-Hittite", "I", "H", null, null, "Hittite, Neo-", null));
    out.add(new Language("nej", "Neko", "I", "L", null, null, null, null));
    out.add(new Language("nek", "Neku", "I", "L", null, null, null, null));
    out.add(new Language("nem", "Nemi", "I", "L", null, null, null, null));
    out.add(new Language("nen", "Nengone", "I", "L", null, null, null, null));
    out.add(new Language("neo", "Ná-Meo", "I", "L", null, null, null, null));
    out.add(new Language("nep", "Nepali (macrolanguage)", "M", "L", "ne", null, null, null));
    out.add(new Language("neq", "North Central Mixe", "I", "L", null, null, "Mixe, North Central", null));
    out.add(new Language("ner", "Yahadian", "I", "L", null, null, null, null));
    out.add(new Language("nes", "Bhoti Kinnauri", "I", "L", null, null, "Kinnauri, Bhoti", null));
    out.add(new Language("net", "Nete", "I", "L", null, null, null, null));
    out.add(new Language("neu", "Neo", "I", "C", null, null, null, null));
    out.add(new Language("nev", "Nyaheun", "I", "L", null, null, null, null));
    out.add(new Language("new", "Nepal Bhasa", "I", "L", null, null, "Bhasa, Nepal", null));
    out.add(new Language("nex", "Neme", "I", "L", null, null, null, null));
    out.add(new Language("ney", "Neyo", "I", "L", null, null, null, null));
    out.add(new Language("nez", "Nez Perce", "I", "L", null, null, null, null));
    out.add(new Language("nfa", "Dhao", "I", "L", null, null, null, null));
    out.add(new Language("nfd", "Ahwai", "I", "L", null, null, null, null));
    out.add(new Language("nfl", "Ayiwo", "I", "L", null, null, null, null));
    out.add(new Language("nfr", "Nafaanra", "I", "L", null, null, null, null));
    out.add(new Language("nfu", "Mfumte", "I", "L", null, null, null, null));
    out.add(new Language("nga", "Ngbaka", "I", "L", null, null, null, null));
    out.add(new Language("ngb", "Northern Ngbandi", "I", "L", null, null, "Ngbandi, Northern", null));
    out.add(new Language("ngc", "Ngombe (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("ngd", "Ngando (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("nge", "Ngemba", "I", "L", null, null, null, null));
    out.add(new Language("ngg", "Ngbaka Manza", "I", "L", null, null, null, null));
    out.add(new Language("ngh", "Nǁng", "I", "L", null, null, null, null));
    out.add(new Language("ngi", "Ngizim", "I", "L", null, null, null, null));
    out.add(new Language("ngj", "Ngie", "I", "L", null, null, null, null));
    out.add(new Language("ngk", "Dalabon", "I", "L", null, null, null, null));
    out.add(new Language("ngl", "Lomwe", "I", "L", null, null, null, null));
    out.add(new Language("ngm", "Ngatik Men's Creole", "I", "L", null, null, null, null));
    out.add(new Language("ngn", "Ngwo", "I", "L", null, null, null, null));
    out.add(new Language("ngp", "Ngulu", "I", "L", null, null, null, null));
    out.add(new Language("ngq", "Ngurimi", "I", "L", null, null, null, null));
    out.add(new Language("ngr", "Engdewu", "I", "L", null, null, null, null));
    out.add(new Language("ngs", "Gvoko", "I", "L", null, null, null, null));
    out.add(new Language("ngt", "Kriang", "I", "L", null, null, null, null));
    out.add(new Language("ngu", "Guerrero Nahuatl", "I", "L", null, null, "Nahuatl, Guerrero", null));
    out.add(new Language("ngv", "Nagumi", "I", "E", null, null, null, null));
    out.add(new Language("ngw", "Ngwaba", "I", "L", null, null, null, null));
    out.add(new Language("ngx", "Nggwahyi", "I", "L", null, null, null, null));
    out.add(new Language("ngy", "Tibea", "I", "L", null, null, null, null));
    out.add(new Language("ngz", "Ngungwel", "I", "L", null, null, null, null));
    out.add(new Language("nha", "Nhanda", "I", "L", null, null, null, null));
    out.add(new Language("nhb", "Beng", "I", "L", null, null, null, null));
    out.add(new Language("nhc", "Tabasco Nahuatl", "I", "E", null, null, "Nahuatl, Tabasco", null));
    out.add(new Language("nhd", "Chiripá", "I", "L", null, null, null, null));
    out.add(new Language("nhe", "Eastern Huasteca Nahuatl", "I", "L", null, null, "Nahuatl, Eastern Huasteca", null));
    out.add(new Language("nhf", "Nhuwala", "I", "L", null, null, null, null));
    out.add(new Language("nhg", "Tetelcingo Nahuatl", "I", "L", null, null, "Nahuatl, Tetelcingo", null));
    out.add(new Language("nhh", "Nahari", "I", "L", null, null, null, null));
    out.add(new Language("nhi", "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl", "I", "L", null, null, "Nahuatl, Zacatlán-Ahuacatlán-Tepetzintla", null));
    out.add(new Language("nhk", "Isthmus-Cosoleacaque Nahuatl", "I", "L", null, null, "Nahuatl, Isthmus-Cosoleacaque", null));
    out.add(new Language("nhm", "Morelos Nahuatl", "I", "L", null, null, "Nahuatl, Morelos", null));
    out.add(new Language("nhn", "Central Nahuatl", "I", "L", null, null, "Nahuatl, Central", null));
    out.add(new Language("nho", "Takuu", "I", "L", null, null, null, null));
    out.add(new Language("nhp", "Isthmus-Pajapan Nahuatl", "I", "L", null, null, "Nahuatl, Isthmus-Pajapan", null));
    out.add(new Language("nhq", "Huaxcaleca Nahuatl", "I", "L", null, null, "Nahuatl, Huaxcaleca", null));
    out.add(new Language("nhr", "Naro", "I", "L", null, null, null, null));
    out.add(new Language("nht", "Ometepec Nahuatl", "I", "L", null, null, "Nahuatl, Ometepec", null));
    out.add(new Language("nhu", "Noone", "I", "L", null, null, null, null));
    out.add(new Language("nhv", "Temascaltepec Nahuatl", "I", "L", null, null, "Nahuatl, Temascaltepec", null));
    out.add(new Language("nhw", "Western Huasteca Nahuatl", "I", "L", null, null, "Nahuatl, Western Huasteca", null));
    out.add(new Language("nhx", "Isthmus-Mecayapan Nahuatl", "I", "L", null, null, "Nahuatl, Isthmus-Mecayapan", null));
    out.add(new Language("nhy", "Northern Oaxaca Nahuatl", "I", "L", null, null, "Nahuatl, Northern Oaxaca", null));
    out.add(new Language("nhz", "Santa María La Alta Nahuatl", "I", "L", null, null, "Nahuatl, Santa María La Alta", null));
    out.add(new Language("nia", "Nias", "I", "L", null, null, null, null));
    out.add(new Language("nib", "Nakame", "I", "L", null, null, null, null));
    out.add(new Language("nid", "Ngandi", "I", "E", null, null, null, null));
    out.add(new Language("nie", "Niellim", "I", "L", null, null, null, null));
    out.add(new Language("nif", "Nek", "I", "L", null, null, null, null));
    out.add(new Language("nig", "Ngalakgan", "I", "E", null, null, null, null));
    out.add(new Language("nih", "Nyiha (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("nii", "Nii", "I", "L", null, null, null, null));
    out.add(new Language("nij", "Ngaju", "I", "L", null, null, null, null));
    out.add(new Language("nik", "Southern Nicobarese", "I", "L", null, null, "Nicobarese, Southern", null));
    out.add(new Language("nil", "Nila", "I", "L", null, null, null, null));
    out.add(new Language("nim", "Nilamba", "I", "L", null, null, null, null));
    out.add(new Language("nin", "Ninzo", "I", "L", null, null, null, null));
    out.add(new Language("nio", "Nganasan", "I", "L", null, null, null, null));
    out.add(new Language("niq", "Nandi", "I", "L", null, null, null, null));
    out.add(new Language("nir", "Nimboran", "I", "L", null, null, null, null));
    out.add(new Language("nis", "Nimi", "I", "L", null, null, null, null));
    out.add(new Language("nit", "Southeastern Kolami", "I", "L", null, null, "Kolami, Southeastern", null));
    out.add(new Language("niu", "Niuean", "I", "L", null, null, null, null));
    out.add(new Language("niv", "Gilyak", "I", "L", null, null, null, null));
    out.add(new Language("niw", "Nimo", "I", "L", null, null, null, null));
    out.add(new Language("nix", "Hema", "I", "L", null, null, null, null));
    out.add(new Language("niy", "Ngiti", "I", "L", null, null, null, null));
    out.add(new Language("niz", "Ningil", "I", "L", null, null, null, null));
    out.add(new Language("nja", "Nzanyi", "I", "L", null, null, null, null));
    out.add(new Language("njb", "Nocte Naga", "I", "L", null, null, "Naga, Nocte", null));
    out.add(new Language("njd", "Ndonde Hamba", "I", "L", null, null, null, null));
    out.add(new Language("njh", "Lotha Naga", "I", "L", null, null, "Naga, Lotha", null));
    out.add(new Language("nji", "Gudanji", "I", "L", null, null, null, null));
    out.add(new Language("njj", "Njen", "I", "L", null, null, null, null));
    out.add(new Language("njl", "Njalgulgule", "I", "L", null, null, null, null));
    out.add(new Language("njm", "Angami Naga", "I", "L", null, null, "Naga, Angami", null));
    out.add(new Language("njn", "Liangmai Naga", "I", "L", null, null, "Naga, Liangmai", null));
    out.add(new Language("njo", "Ao Naga", "I", "L", null, null, "Naga, Ao", null));
    out.add(new Language("njr", "Njerep", "I", "L", null, null, null, null));
    out.add(new Language("njs", "Nisa", "I", "L", null, null, null, null));
    out.add(new Language("njt", "Ndyuka-Trio Pidgin", "I", "L", null, null, null, null));
    out.add(new Language("nju", "Ngadjunmaya", "I", "L", null, null, null, null));
    out.add(new Language("njx", "Kunyi", "I", "L", null, null, null, null));
    out.add(new Language("njy", "Njyem", "I", "L", null, null, null, null));
    out.add(new Language("njz", "Nyishi", "I", "L", null, null, null, null));
    out.add(new Language("nka", "Nkoya", "I", "L", null, null, null, null));
    out.add(new Language("nkb", "Khoibu Naga", "I", "L", null, null, "Naga, Khoibu", null));
    out.add(new Language("nkc", "Nkongho", "I", "L", null, null, null, null));
    out.add(new Language("nkd", "Koireng", "I", "L", null, null, null, null));
    out.add(new Language("nke", "Duke", "I", "L", null, null, null, null));
    out.add(new Language("nkf", "Inpui Naga", "I", "L", null, null, "Naga, Inpui", null));
    out.add(new Language("nkg", "Nekgini", "I", "L", null, null, null, null));
    out.add(new Language("nkh", "Khezha Naga", "I", "L", null, null, "Naga, Khezha", null));
    out.add(new Language("nki", "Thangal Naga", "I", "L", null, null, "Naga, Thangal", null));
    out.add(new Language("nkj", "Nakai", "I", "L", null, null, null, null));
    out.add(new Language("nkk", "Nokuku", "I", "L", null, null, null, null));
    out.add(new Language("nkm", "Namat", "I", "L", null, null, null, null));
    out.add(new Language("nkn", "Nkangala", "I", "L", null, null, null, null));
    out.add(new Language("nko", "Nkonya", "I", "L", null, null, null, null));
    out.add(new Language("nkp", "Niuatoputapu", "I", "E", null, null, null, null));
    out.add(new Language("nkq", "Nkami", "I", "L", null, null, null, null));
    out.add(new Language("nkr", "Nukuoro", "I", "L", null, null, null, null));
    out.add(new Language("nks", "North Asmat", "I", "L", null, null, "Asmat, North", null));
    out.add(new Language("nkt", "Nyika (Tanzania)", "I", "L", null, null, null, null));
    out.add(new Language("nku", "Bouna Kulango", "I", "L", null, null, "Kulango, Bouna", null));
    out.add(new Language("nkv", "Nyika (Malawi and Zambia)", "I", "L", null, null, null, null));
    out.add(new Language("nkw", "Nkutu", "I", "L", null, null, null, null));
    out.add(new Language("nkx", "Nkoroo", "I", "L", null, null, null, null));
    out.add(new Language("nkz", "Nkari", "I", "L", null, null, null, null));
    out.add(new Language("nla", "Ngombale", "I", "L", null, null, null, null));
    out.add(new Language("nlc", "Nalca", "I", "L", null, null, null, null));
    out.add(new Language("nld", "Dutch", "I", "L", "nl", null, null, "dut"));
    out.add(new Language("nle", "East Nyala", "I", "L", null, null, "Nyala, East", null));
    out.add(new Language("nlg", "Gela", "I", "L", null, null, null, null));
    out.add(new Language("nli", "Grangali", "I", "L", null, null, null, null));
    out.add(new Language("nlj", "Nyali", "I", "L", null, null, null, null));
    out.add(new Language("nlk", "Ninia Yali", "I", "L", null, null, "Yali, Ninia", null));
    out.add(new Language("nll", "Nihali", "I", "L", null, null, null, null));
    out.add(new Language("nlm", "Mankiyali", "I", "L", null, null, null, null));
    out.add(new Language("nlo", "Ngul", "I", "L", null, null, null, null));
    out.add(new Language("nlq", "Lao Naga", "I", "L", null, null, "Naga, Lao", null));
    out.add(new Language("nlu", "Nchumbulu", "I", "L", null, null, null, null));
    out.add(new Language("nlv", "Orizaba Nahuatl", "I", "L", null, null, "Nahuatl, Orizaba", null));
    out.add(new Language("nlw", "Walangama", "I", "E", null, null, null, null));
    out.add(new Language("nlx", "Nahali", "I", "L", null, null, null, null));
    out.add(new Language("nly", "Nyamal", "I", "L", null, null, null, null));
    out.add(new Language("nlz", "Nalögo", "I", "L", null, null, null, null));
    out.add(new Language("nma", "Maram Naga", "I", "L", null, null, "Naga, Maram", null));
    out.add(new Language("nmb", "Big Nambas", "I", "L", null, null, "Nambas, Big", null));
    out.add(new Language("nmc", "Ngam", "I", "L", null, null, null, null));
    out.add(new Language("nmd", "Ndumu", "I", "L", null, null, null, null));
    out.add(new Language("nme", "Mzieme Naga", "I", "L", null, null, "Naga, Mzieme", null));
    out.add(new Language("nmf", "Tangkhul Naga (India)", "I", "L", null, null, "Naga, Tangkhul (India)", null));
    out.add(new Language("nmg", "Kwasio", "I", "L", null, null, null, null));
    out.add(new Language("nmh", "Monsang Naga", "I", "L", null, null, "Naga, Monsang", null));
    out.add(new Language("nmi", "Nyam", "I", "L", null, null, null, null));
    out.add(new Language("nmj", "Ngombe (Central African Republic)", "I", "L", null, null, null, null));
    out.add(new Language("nmk", "Namakura", "I", "L", null, null, null, null));
    out.add(new Language("nml", "Ndemli", "I", "L", null, null, null, null));
    out.add(new Language("nmm", "Manangba", "I", "L", null, null, null, null));
    out.add(new Language("nmn", "ǃXóõ", "I", "L", null, null, null, null));
    out.add(new Language("nmo", "Moyon Naga", "I", "L", null, null, "Naga, Moyon", null));
    out.add(new Language("nmp", "Nimanbur", "I", "E", null, null, null, null));
    out.add(new Language("nmq", "Nambya", "I", "L", null, null, null, null));
    out.add(new Language("nmr", "Nimbari", "I", "E", null, null, null, null));
    out.add(new Language("nms", "Letemboi", "I", "L", null, null, null, null));
    out.add(new Language("nmt", "Namonuito", "I", "L", null, null, null, null));
    out.add(new Language("nmu", "Northeast Maidu", "I", "L", null, null, "Maidu, Northeast", null));
    out.add(new Language("nmv", "Ngamini", "I", "E", null, null, null, null));
    out.add(new Language("nmw", "Nimoa", "I", "L", null, null, null, null));
    out.add(new Language("nmx", "Nama (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("nmy", "Namuyi", "I", "L", null, null, null, null));
    out.add(new Language("nmz", "Nawdm", "I", "L", null, null, null, null));
    out.add(new Language("nna", "Nyangumarta", "I", "L", null, null, null, null));
    out.add(new Language("nnb", "Nande", "I", "L", null, null, null, null));
    out.add(new Language("nnc", "Nancere", "I", "L", null, null, null, null));
    out.add(new Language("nnd", "West Ambae", "I", "L", null, null, "Ambae, West", null));
    out.add(new Language("nne", "Ngandyera", "I", "L", null, null, null, null));
    out.add(new Language("nnf", "Ngaing", "I", "L", null, null, null, null));
    out.add(new Language("nng", "Maring Naga", "I", "L", null, null, "Naga, Maring", null));
    out.add(new Language("nnh", "Ngiemboon", "I", "L", null, null, null, null));
    out.add(new Language("nni", "North Nuaulu", "I", "L", null, null, "Nuaulu, North", null));
    out.add(new Language("nnj", "Nyangatom", "I", "L", null, null, null, null));
    out.add(new Language("nnk", "Nankina", "I", "L", null, null, null, null));
    out.add(new Language("nnl", "Northern Rengma Naga", "I", "L", null, null, "Naga, Northern Rengma", null));
    out.add(new Language("nnm", "Namia", "I", "L", null, null, null, null));
    out.add(new Language("nnn", "Ngete", "I", "L", null, null, null, null));
    out.add(new Language("nno", "Norwegian Nynorsk", "I", "L", "nn", null, null, null));
    out.add(new Language("nnp", "Wancho Naga", "I", "L", null, null, "Naga, Wancho", null));
    out.add(new Language("nnq", "Ngindo", "I", "L", null, null, null, null));
    out.add(new Language("nnr", "Narungga", "I", "E", null, null, null, null));
    out.add(new Language("nnt", "Nanticoke", "I", "E", null, null, null, null));
    out.add(new Language("nnu", "Dwang", "I", "L", null, null, null, null));
    out.add(new Language("nnv", "Nugunu (Australia)", "I", "E", null, null, null, null));
    out.add(new Language("nnw", "Southern Nuni", "I", "L", null, null, "Nuni, Southern", null));
    out.add(new Language("nny", "Nyangga", "I", "E", null, null, null, null));
    out.add(new Language("nnz", "Nda'nda'", "I", "L", null, null, null, null));
    out.add(new Language("noa", "Woun Meu", "I", "L", null, null, null, null));
    out.add(new Language("nob", "Norwegian Bokmål", "I", "L", "nb", null, null, null));
    out.add(new Language("noc", "Nuk", "I", "L", null, null, null, null));
    out.add(new Language("nod", "Northern Thai", "I", "L", null, null, "Thai, Northern", null));
    out.add(new Language("noe", "Nimadi", "I", "L", null, null, null, null));
    out.add(new Language("nof", "Nomane", "I", "L", null, null, null, null));
    out.add(new Language("nog", "Nogai", "I", "L", null, null, null, null));
    out.add(new Language("noh", "Nomu", "I", "L", null, null, null, null));
    out.add(new Language("noi", "Noiri", "I", "L", null, null, null, null));
    out.add(new Language("noj", "Nonuya", "I", "L", null, null, null, null));
    out.add(new Language("nok", "Nooksack", "I", "E", null, null, null, null));
    out.add(new Language("nol", "Nomlaki", "I", "E", null, null, null, null));
    out.add(new Language("non", "Old Norse", "I", "H", null, null, "Norse, Old", null));
    out.add(new Language("nop", "Numanggang", "I", "L", null, null, null, null));
    out.add(new Language("noq", "Ngongo", "I", "L", null, null, null, null));
    out.add(new Language("nor", "Norwegian", "M", "L", "no", null, null, null));
    out.add(new Language("nos", "Eastern Nisu", "I", "L", null, null, "Nisu, Eastern", null));
    out.add(new Language("not", "Nomatsiguenga", "I", "L", null, null, null, null));
    out.add(new Language("nou", "Ewage-Notu", "I", "L", null, null, null, null));
    out.add(new Language("nov", "Novial", "I", "C", null, null, null, null));
    out.add(new Language("now", "Nyambo", "I", "L", null, null, null, null));
    out.add(new Language("noy", "Noy", "I", "L", null, null, null, null));
    out.add(new Language("noz", "Nayi", "I", "L", null, null, null, null));
    out.add(new Language("npa", "Nar Phu", "I", "L", null, null, null, null));
    out.add(new Language("npb", "Nupbikha", "I", "L", null, null, null, null));
    out.add(new Language("npg", "Ponyo-Gongwang Naga", "I", "L", null, null, "Naga, Ponyo-Gongwang", null));
    out.add(new Language("nph", "Phom Naga", "I", "L", null, null, "Naga, Phom", null));
    out.add(new Language("npi", "Nepali (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("npl", "Southeastern Puebla Nahuatl", "I", "L", null, null, "Nahuatl, Southeastern Puebla", null));
    out.add(new Language("npn", "Mondropolon", "I", "L", null, null, null, null));
    out.add(new Language("npo", "Pochuri Naga", "I", "L", null, null, "Naga, Pochuri", null));
    out.add(new Language("nps", "Nipsan", "I", "L", null, null, null, null));
    out.add(new Language("npu", "Puimei Naga", "I", "L", null, null, "Naga, Puimei", null));
    out.add(new Language("npx", "Noipx", "I", "L", null, null, null, null));
    out.add(new Language("npy", "Napu", "I", "L", null, null, null, null));
    out.add(new Language("nqg", "Southern Nago", "I", "L", null, null, "Nago, Southern", null));
    out.add(new Language("nqk", "Kura Ede Nago", "I", "L", null, null, "Ede Nago, Kura", null));
    out.add(new Language("nql", "Ngendelengo", "I", "L", null, null, null, null));
    out.add(new Language("nqm", "Ndom", "I", "L", null, null, null, null));
    out.add(new Language("nqn", "Nen", "I", "L", null, null, null, null));
    out.add(new Language("nqo", "N'Ko", "I", "L", null, null, null, null));
    out.add(new Language("nqq", "Kyan-Karyaw Naga", "I", "L", null, null, "Naga, Kyan-Karyaw", null));
    out.add(new Language("nqt", "Nteng", "I", "L", null, null, null, null));
    out.add(new Language("nqy", "Akyaung Ari Naga", "I", "L", null, null, "Naga, Akyaung Ari", null));
    out.add(new Language("nra", "Ngom", "I", "L", null, null, null, null));
    out.add(new Language("nrb", "Nara", "I", "L", null, null, null, null));
    out.add(new Language("nrc", "Noric", "I", "H", null, null, null, null));
    out.add(new Language("nre", "Southern Rengma Naga", "I", "L", null, null, "Naga, Southern Rengma", null));
    out.add(new Language("nrf", "Jèrriais", "I", "L", null, null, null, null));
    out.add(new Language("nrg", "Narango", "I", "L", null, null, null, null));
    out.add(new Language("nri", "Chokri Naga", "I", "L", null, null, "Naga, Chokri", null));
    out.add(new Language("nrk", "Ngarla", "I", "L", null, null, null, null));
    out.add(new Language("nrl", "Ngarluma", "I", "L", null, null, null, null));
    out.add(new Language("nrm", "Narom", "I", "L", null, null, null, null));
    out.add(new Language("nrn", "Norn", "I", "E", null, null, null, null));
    out.add(new Language("nrp", "North Picene", "I", "H", null, null, "Picene, North", null));
    out.add(new Language("nrr", "Norra", "I", "E", null, null, null, null));
    out.add(new Language("nrt", "Northern Kalapuya", "I", "E", null, null, "Kalapuya, Northern", null));
    out.add(new Language("nru", "Narua", "I", "L", null, null, null, null));
    out.add(new Language("nrx", "Ngurmbur", "I", "E", null, null, null, null));
    out.add(new Language("nrz", "Lala", "I", "L", null, null, null, null));
    out.add(new Language("nsa", "Sangtam Naga", "I", "L", null, null, "Naga, Sangtam", null));
    out.add(new Language("nsb", "Lower Nossob", "I", "E", null, null, null, null));
    out.add(new Language("nsc", "Nshi", "I", "L", null, null, null, null));
    out.add(new Language("nsd", "Southern Nisu", "I", "L", null, null, "Nisu, Southern", null));
    out.add(new Language("nse", "Nsenga", "I", "L", null, null, null, null));
    out.add(new Language("nsf", "Northwestern Nisu", "I", "L", null, null, "Nisu, Northwestern", null));
    out.add(new Language("nsg", "Ngasa", "I", "L", null, null, null, null));
    out.add(new Language("nsh", "Ngoshie", "I", "L", null, null, null, null));
    out.add(new Language("nsi", "Nigerian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nsk", "Naskapi", "I", "L", null, null, null, null));
    out.add(new Language("nsl", "Norwegian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nsm", "Sumi Naga", "I", "L", null, null, "Naga, Sumi", null));
    out.add(new Language("nsn", "Nehan", "I", "L", null, null, null, null));
    out.add(new Language("nso", "Pedi", "I", "L", null, null, null, null));
    out.add(new Language("nsp", "Nepalese Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nsq", "Northern Sierra Miwok", "I", "L", null, null, "Miwok, Northern Sierra", null));
    out.add(new Language("nsr", "Maritime Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nss", "Nali", "I", "L", null, null, null, null));
    out.add(new Language("nst", "Tase Naga", "I", "L", null, null, "Naga, Tase", null));
    out.add(new Language("nsu", "Sierra Negra Nahuatl", "I", "L", null, null, "Nahuatl, Sierra Negra", null));
    out.add(new Language("nsv", "Southwestern Nisu", "I", "L", null, null, "Nisu, Southwestern", null));
    out.add(new Language("nsw", "Navut", "I", "L", null, null, null, null));
    out.add(new Language("nsx", "Nsongo", "I", "L", null, null, null, null));
    out.add(new Language("nsy", "Nasal", "I", "L", null, null, null, null));
    out.add(new Language("nsz", "Nisenan", "I", "L", null, null, null, null));
    out.add(new Language("ntd", "Northern Tidung", "I", "L", null, null, "Tidung, Northern", null));
    out.add(new Language("ntg", "Ngantangarra", "I", "E", null, null, null, null));
    out.add(new Language("nti", "Natioro", "I", "L", null, null, null, null));
    out.add(new Language("ntj", "Ngaanyatjarra", "I", "L", null, null, null, null));
    out.add(new Language("ntk", "Ikoma-Nata-Isenye", "I", "L", null, null, null, null));
    out.add(new Language("ntm", "Nateni", "I", "L", null, null, null, null));
    out.add(new Language("nto", "Ntomba", "I", "L", null, null, null, null));
    out.add(new Language("ntp", "Northern Tepehuan", "I", "L", null, null, "Tepehuan, Northern", null));
    out.add(new Language("ntr", "Delo", "I", "L", null, null, null, null));
    out.add(new Language("ntu", "Natügu", "I", "L", null, null, null, null));
    out.add(new Language("ntw", "Nottoway", "I", "E", null, null, null, null));
    out.add(new Language("ntx", "Tangkhul Naga (Myanmar)", "I", "L", null, null, "Naga, Tangkhul (Myanmar)", null));
    out.add(new Language("nty", "Mantsi", "I", "L", null, null, null, null));
    out.add(new Language("ntz", "Natanzi", "I", "L", null, null, null, null));
    out.add(new Language("nua", "Yuanga", "I", "L", null, null, null, null));
    out.add(new Language("nuc", "Nukuini", "I", "E", null, null, null, null));
    out.add(new Language("nud", "Ngala", "I", "L", null, null, null, null));
    out.add(new Language("nue", "Ngundu", "I", "L", null, null, null, null));
    out.add(new Language("nuf", "Nusu", "I", "L", null, null, null, null));
    out.add(new Language("nug", "Nungali", "I", "E", null, null, null, null));
    out.add(new Language("nuh", "Ndunda", "I", "L", null, null, null, null));
    out.add(new Language("nui", "Ngumbi", "I", "L", null, null, null, null));
    out.add(new Language("nuj", "Nyole", "I", "L", null, null, null, null));
    out.add(new Language("nuk", "Nuu-chah-nulth", "I", "L", null, null, null, null));
    out.add(new Language("nul", "Nusa Laut", "I", "E", null, null, null, null));
    out.add(new Language("num", "Niuafo'ou", "I", "L", null, null, null, null));
    out.add(new Language("nun", "Anong", "I", "L", null, null, null, null));
    out.add(new Language("nuo", "Nguôn", "I", "L", null, null, null, null));
    out.add(new Language("nup", "Nupe-Nupe-Tako", "I", "L", null, null, null, null));
    out.add(new Language("nuq", "Nukumanu", "I", "L", null, null, null, null));
    out.add(new Language("nur", "Nukuria", "I", "L", null, null, null, null));
    out.add(new Language("nus", "Nuer", "I", "L", null, null, null, null));
    out.add(new Language("nut", "Nung (Viet Nam)", "I", "L", null, null, null, null));
    out.add(new Language("nuu", "Ngbundu", "I", "L", null, null, null, null));
    out.add(new Language("nuv", "Northern Nuni", "I", "L", null, null, "Nuni, Northern", null));
    out.add(new Language("nuw", "Nguluwan", "I", "L", null, null, null, null));
    out.add(new Language("nux", "Mehek", "I", "L", null, null, null, null));
    out.add(new Language("nuy", "Nunggubuyu", "I", "L", null, null, null, null));
    out.add(new Language("nuz", "Tlamacazapa Nahuatl", "I", "L", null, null, "Nahuatl, Tlamacazapa", null));
    out.add(new Language("nvh", "Nasarian", "I", "L", null, null, null, null));
    out.add(new Language("nvm", "Namiae", "I", "L", null, null, null, null));
    out.add(new Language("nvo", "Nyokon", "I", "L", null, null, null, null));
    out.add(new Language("nwa", "Nawathinehena", "I", "E", null, null, null, null));
    out.add(new Language("nwb", "Nyabwa", "I", "L", null, null, null, null));
    out.add(new Language("nwc", "Classical Newari", "I", "H", null, null, "Newari, Classical", null));
    out.add(new Language("nwe", "Ngwe", "I", "L", null, null, null, null));
    out.add(new Language("nwg", "Ngayawung", "I", "E", null, null, null, null));
    out.add(new Language("nwi", "Southwest Tanna", "I", "L", null, null, "Tanna, Southwest", null));
    out.add(new Language("nwm", "Nyamusa-Molo", "I", "L", null, null, null, null));
    out.add(new Language("nwo", "Nauo", "I", "E", null, null, null, null));
    out.add(new Language("nwr", "Nawaru", "I", "L", null, null, null, null));
    out.add(new Language("nww", "Ndwewe", "I", "L", null, null, null, null));
    out.add(new Language("nwx", "Middle Newar", "I", "H", null, null, "Newar, Middle", null));
    out.add(new Language("nwy", "Nottoway-Meherrin", "I", "E", null, null, null, null));
    out.add(new Language("nxa", "Nauete", "I", "L", null, null, null, null));
    out.add(new Language("nxd", "Ngando (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("nxe", "Nage", "I", "L", null, null, null, null));
    out.add(new Language("nxg", "Ngad'a", "I", "L", null, null, null, null));
    out.add(new Language("nxi", "Nindi", "I", "L", null, null, null, null));
    out.add(new Language("nxk", "Koki Naga", "I", "L", null, null, "Naga, Koki", null));
    out.add(new Language("nxl", "South Nuaulu", "I", "L", null, null, "Nuaulu, South", null));
    out.add(new Language("nxm", "Numidian", "I", "H", null, null, null, null));
    out.add(new Language("nxn", "Ngawun", "I", "E", null, null, null, null));
    out.add(new Language("nxo", "Ndambomo", "I", "L", null, null, null, null));
    out.add(new Language("nxq", "Naxi", "I", "L", null, null, null, null));
    out.add(new Language("nxr", "Ninggerum", "I", "L", null, null, null, null));
    out.add(new Language("nxx", "Nafri", "I", "L", null, null, null, null));
    out.add(new Language("nya", "Chichewa", "I", "L", "ny", null, null, null));
    out.add(new Language("nyb", "Nyangbo", "I", "L", null, null, null, null));
    out.add(new Language("nyc", "Nyanga-li", "I", "L", null, null, null, null));
    out.add(new Language("nyd", "Nyore", "I", "L", null, null, null, null));
    out.add(new Language("nye", "Nyengo", "I", "L", null, null, null, null));
    out.add(new Language("nyf", "Giryama", "I", "L", null, null, null, null));
    out.add(new Language("nyg", "Nyindu", "I", "L", null, null, null, null));
    out.add(new Language("nyh", "Nyikina", "I", "L", null, null, null, null));
    out.add(new Language("nyi", "Ama (Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("nyj", "Nyanga", "I", "L", null, null, null, null));
    out.add(new Language("nyk", "Nyaneka", "I", "L", null, null, null, null));
    out.add(new Language("nyl", "Nyeu", "I", "L", null, null, null, null));
    out.add(new Language("nym", "Nyamwezi", "I", "L", null, null, null, null));
    out.add(new Language("nyn", "Nyankole", "I", "L", null, null, null, null));
    out.add(new Language("nyo", "Nyoro", "I", "L", null, null, null, null));
    out.add(new Language("nyp", "Nyang'i", "I", "E", null, null, null, null));
    out.add(new Language("nyq", "Nayini", "I", "L", null, null, null, null));
    out.add(new Language("nyr", "Nyiha (Malawi)", "I", "L", null, null, null, null));
    out.add(new Language("nys", "Nyungar", "I", "L", null, null, null, null));
    out.add(new Language("nyt", "Nyawaygi", "I", "E", null, null, null, null));
    out.add(new Language("nyu", "Nyungwe", "I", "L", null, null, null, null));
    out.add(new Language("nyv", "Nyulnyul", "I", "E", null, null, null, null));
    out.add(new Language("nyw", "Nyaw", "I", "L", null, null, null, null));
    out.add(new Language("nyx", "Nganyaywana", "I", "E", null, null, null, null));
    out.add(new Language("nyy", "Nyakyusa-Ngonde", "I", "L", null, null, null, null));
    out.add(new Language("nza", "Tigon Mbembe", "I", "L", null, null, "Mbembe, Tigon", null));
    out.add(new Language("nzb", "Njebi", "I", "L", null, null, null, null));
    out.add(new Language("nzd", "Nzadi", "I", "L", null, null, null, null));
    out.add(new Language("nzi", "Nzima", "I", "L", null, null, null, null));
    out.add(new Language("nzk", "Nzakara", "I", "L", null, null, null, null));
    out.add(new Language("nzm", "Zeme Naga", "I", "L", null, null, "Naga, Zeme", null));
    out.add(new Language("nzr", "Dir-Nyamzak-Mbarimi", "I", "L", null, null, null, null));
    out.add(new Language("nzs", "New Zealand Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("nzu", "Teke-Nzikou", "I", "L", null, null, null, null));
    out.add(new Language("nzy", "Nzakambay", "I", "L", null, null, null, null));
    out.add(new Language("nzz", "Nanga Dama Dogon", "I", "L", null, null, "Dogon, Nanga Dama", null));
    out.add(new Language("oaa", "Orok", "I", "L", null, null, null, null));
    out.add(new Language("oac", "Oroch", "I", "L", null, null, null, null));
    out.add(new Language("oak", "Noakhali", "I", "L", null, null, null, null));
    out.add(new Language("oar", "Old Aramaic (up to 700 BCE)", "I", "H", null, null, "Aramaic, Old (up to 700 BCE)", null));
    out.add(new Language("oav", "Old Avar", "I", "H", null, null, "Avar, Old", null));
    out.add(new Language("obi", "Obispeño", "I", "E", null, null, null, null));
    out.add(new Language("obk", "Southern Bontok", "I", "L", null, null, "Bontok, Southern", null));
    out.add(new Language("obl", "Oblo", "I", "L", null, null, null, null));
    out.add(new Language("obm", "Moabite", "I", "H", null, null, null, null));
    out.add(new Language("obo", "Obo Manobo", "I", "L", null, null, "Manobo, Obo", null));
    out.add(new Language("obr", "Old Burmese", "I", "H", null, null, "Burmese, Old", null));
    out.add(new Language("obt", "Old Breton", "I", "H", null, null, "Breton, Old", null));
    out.add(new Language("obu", "Obulom", "I", "L", null, null, null, null));
    out.add(new Language("oca", "Ocaina", "I", "L", null, null, null, null));
    out.add(new Language("och", "Old Chinese", "I", "H", null, null, "Chinese, Old", null));
    out.add(new Language("oci", "Occitan (post 1500)", "I", "L", "oc", null, null, null));
    out.add(new Language("ocm", "Old Cham", "I", "H", null, null, "Cham, Old", null));
    out.add(new Language("oco", "Old Cornish", "I", "H", null, null, "Cornish, Old", null));
    out.add(new Language("ocu", "Atzingo Matlatzinca", "I", "L", null, null, "Matlatzinca, Atzingo", null));
    out.add(new Language("oda", "Odut", "I", "L", null, null, null, null));
    out.add(new Language("odk", "Od", "I", "L", null, null, null, null));
    out.add(new Language("odt", "Old Dutch", "I", "H", null, null, "Dutch, Old", null));
    out.add(new Language("odu", "Odual", "I", "L", null, null, null, null));
    out.add(new Language("ofo", "Ofo", "I", "E", null, null, null, null));
    out.add(new Language("ofs", "Old Frisian", "I", "H", null, null, "Frisian, Old", null));
    out.add(new Language("ofu", "Efutop", "I", "L", null, null, null, null));
    out.add(new Language("ogb", "Ogbia", "I", "L", null, null, null, null));
    out.add(new Language("ogc", "Ogbah", "I", "L", null, null, null, null));
    out.add(new Language("oge", "Old Georgian", "I", "H", null, null, "Georgian, Old", null));
    out.add(new Language("ogg", "Ogbogolo", "I", "L", null, null, null, null));
    out.add(new Language("ogo", "Khana", "I", "L", null, null, null, null));
    out.add(new Language("ogu", "Ogbronuagum", "I", "L", null, null, null, null));
    out.add(new Language("oht", "Old Hittite", "I", "H", null, null, "Hittite, Old", null));
    out.add(new Language("ohu", "Old Hungarian", "I", "H", null, null, "Hungarian, Old", null));
    out.add(new Language("oia", "Oirata", "I", "L", null, null, null, null));
    out.add(new Language("oie", "Okolie", "I", "L", null, null, null, null));
    out.add(new Language("oin", "Inebu One", "I", "L", null, null, "One, Inebu", null));
    out.add(new Language("ojb", "Northwestern Ojibwa", "I", "L", null, null, "Ojibwa, Northwestern", null));
    out.add(new Language("ojc", "Central Ojibwa", "I", "L", null, null, "Ojibwa, Central", null));
    out.add(new Language("ojg", "Eastern Ojibwa", "I", "L", null, null, "Ojibwa, Eastern", null));
    out.add(new Language("oji", "Ojibwa", "M", "L", "oj", null, null, null));
    out.add(new Language("ojp", "Old Japanese", "I", "H", null, null, "Japanese, Old", null));
    out.add(new Language("ojs", "Severn Ojibwa", "I", "L", null, null, "Ojibwa, Severn", null));
    out.add(new Language("ojv", "Ontong Java", "I", "L", null, null, null, null));
    out.add(new Language("ojw", "Western Ojibwa", "I", "L", null, null, "Ojibwa, Western", null));
    out.add(new Language("oka", "Okanagan", "I", "L", null, null, null, null));
    out.add(new Language("okb", "Okobo", "I", "L", null, null, null, null));
  }
}
