// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 3000 to 3499 of {@link Language}.
 */
final class LanguageData6 {
  private LanguageData6() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("kgt", "Somyev", "I", "L", null, null, null, null));
    out.add(new Language("kgu", "Kobol", "I", "L", null, null, null, null));
    out.add(new Language("kgv", "Karas", "I", "L", null, null, null, null));
    out.add(new Language("kgw", "Karon Dori", "I", "L", null, null, null, null));
    out.add(new Language("kgx", "Kamaru", "I", "L", null, null, null, null));
    out.add(new Language("kgy", "Kyerung", "I", "L", null, null, null, null));
    out.add(new Language("kha", "Khasi", "I", "L", null, null, null, null));
    out.add(new Language("khb", "Lü", "I", "L", null, null, null, null));
    out.add(new Language("khc", "Tukang Besi North", "I", "L", null, null, null, null));
    out.add(new Language("khd", "Bädi Kanum", "I", "L", null, null, "Kanum, Bädi", null));
    out.add(new Language("khe", "Korowai", "I", "L", null, null, null, null));
    out.add(new Language("khf", "Khuen", "I", "L", null, null, null, null));
    out.add(new Language("khg", "Khams Tibetan", "I", "L", null, null, "Tibetan, Khams", null));
    out.add(new Language("khh", "Kehu", "I", "L", null, null, null, null));
    out.add(new Language("khj", "Kuturmi", "I", "L", null, null, null, null));
    out.add(new Language("khk", "Halh Mongolian", "I", "L", null, null, "Mongolian, Halh", null));
    out.add(new Language("khl", "Lusi", "I", "L", null, null, null, null));
    out.add(new Language("khm", "Khmer", "I", "L", "km", null, null, null));
    out.add(new Language("khn", "Khandesi", "I", "L", null, null, null, null));
    out.add(new Language("kho", "Khotanese", "I", "H", null, null, null, null));
    out.add(new Language("khp", "Kapori", "I", "L", null, null, null, null));
    out.add(new Language("khq", "Koyra Chiini Songhay", "I", "L", null, null, "Songhay, Koyra Chiini", null));
    out.add(new Language("khr", "Kharia", "I", "L", null, null, null, null));
    out.add(new Language("khs", "Kasua", "I", "L", null, null, null, null));
    out.add(new Language("kht", "Khamti", "I", "L", null, null, null, null));
    out.add(new Language("khu", "Nkhumbi", "I", "L", null, null, null, null));
    out.add(new Language("khv", "Khvarshi", "I", "L", null, null, null, null));
    out.add(new Language("khw", "Khowar", "I", "L", null, null, null, null));
    out.add(new Language("khx", "Kanu", "I", "L", null, null, null, null));
    out.add(new Language("khy", "Kele (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("khz", "Keapara", "I", "L", null, null, null, null));
    out.add(new Language("kia", "Kim", "I", "L", null, null, null, null));
    out.add(new Language("kib", "Koalib", "I", "L", null, null, null, null));
    out.add(new Language("kic", "Kickapoo", "I", "L", null, null, null, null));
    out.add(new Language("kid", "Koshin", "I", "L", null, null, null, null));
    out.add(new Language("kie", "Kibet", "I", "L", null, null, null, null));
    out.add(new Language("kif", "Eastern Parbate Kham", "I", "L", null, null, "Kham, Eastern Parbate", null));
    out.add(new Language("kig", "Kimaama", "I", "L", null, null, null, null));
    out.add(new Language("kih", "Kilmeri", "I", "L", null, null, null, null));
    out.add(new Language("kii", "Kitsai", "I", "E", null, null, null, null));
    out.add(new Language("kij", "Kilivila", "I", "L", null, null, null, null));
    out.add(new Language("kik", "Kikuyu", "I", "L", "ki", null, null, null));
    out.add(new Language("kil", "Kariya", "I", "L", null, null, null, null));
    out.add(new Language("kim", "Karagas", "I", "L", null, null, null, null));
    out.add(new Language("kin", "Kinyarwanda", "I", "L", "rw", null, null, null));
    out.add(new Language("kio", "Kiowa", "I", "L", null, null, null, null));
    out.add(new Language("kip", "Sheshi Kham", "I", "L", null, null, "Kham, Sheshi", null));
    out.add(new Language("kiq", "Kosadle", "I", "L", null, null, null, null));
    out.add(new Language("kir", "Kirghiz", "I", "L", "ky", null, null, null));
    out.add(new Language("kis", "Kis", "I", "L", null, null, null, null));
    out.add(new Language("kit", "Agob", "I", "L", null, null, null, null));
    out.add(new Language("kiu", "Kirmanjki (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("kiv", "Kimbu", "I", "L", null, null, null, null));
    out.add(new Language("kiw", "Northeast Kiwai", "I", "L", null, null, "Kiwai, Northeast", null));
    out.add(new Language("kix", "Khiamniungan Naga", "I", "L", null, null, "Naga, Khiamniungan", null));
    out.add(new Language("kiy", "Kirikiri", "I", "L", null, null, null, null));
    out.add(new Language("kiz", "Kisi", "I", "L", null, null, null, null));
    out.add(new Language("kja", "Mlap", "I", "L", null, null, null, null));
    out.add(new Language("kjb", "Q'anjob'al", "I", "L", null, null, null, null));
    out.add(new Language("kjc", "Coastal Konjo", "I", "L", null, null, "Konjo, Coastal", null));
    out.add(new Language("kjd", "Southern Kiwai", "I", "L", null, null, "Kiwai, Southern", null));
    out.add(new Language("kje", "Kisar", "I", "L", null, null, null, null));
    out.add(new Language("kjg", "Khmu", "I", "L", null, null, null, null));
    out.add(new Language("kjh", "Khakas", "I", "L", null, null, null, null));
    out.add(new Language("kji", "Zabana", "I", "L", null, null, null, null));
    out.add(new Language("kjj", "Khinalugh", "I", "L", null, null, null, null));
    out.add(new Language("kjk", "Highland Konjo", "I", "L", null, null, "Konjo, Highland", null));
    out.add(new Language("kjl", "Western Parbate Kham", "I", "L", null, null, "Kham, Western Parbate", null));
    out.add(new Language("kjm", "Kháng", "I", "L", null, null, null, null));
    out.add(new Language("kjn", "Kunjen", "I", "L", null, null, null, null));
    out.add(new Language("kjo", "Harijan Kinnauri", "I", "L", null, null, "Kinnauri, Harijan", null));
    out.add(new Language("kjp", "Pwo Eastern Karen", "I", "L", null, null, "Karen, Pwo Eastern", null));
    out.add(new Language("kjq", "Western Keres", "I", "L", null, null, "Keres, Western", null));
    out.add(new Language("kjr", "Kurudu", "I", "L", null, null, null, null));
    out.add(new Language("kjs", "East Kewa", "I", "L", null, null, "Kewa, East", null));
    out.add(new Language("kjt", "Phrae Pwo Karen", "I", "L", null, null, "Karen, Phrae Pwo", null));
    out.add(new Language("kju", "Kashaya", "I", "L", null, null, null, null));
    out.add(new Language("kjv", "Kaikavian Literary Language", "I", "H", null, null, null, null));
    out.add(new Language("kjx", "Ramopa", "I", "L", null, null, null, null));
    out.add(new Language("kjy", "Erave", "I", "L", null, null, null, null));
    out.add(new Language("kjz", "Bumthangkha", "I", "L", null, null, null, null));
    out.add(new Language("kka", "Kakanda", "I", "L", null, null, null, null));
    out.add(new Language("kkb", "Kwerisa", "I", "L", null, null, null, null));
    out.add(new Language("kkc", "Odoodee", "I", "L", null, null, null, null));
    out.add(new Language("kkd", "Kinuku", "I", "L", null, null, null, null));
    out.add(new Language("kke", "Kakabe", "I", "L", null, null, null, null));
    out.add(new Language("kkf", "Kalaktang Monpa", "I", "L", null, null, "Monpa, Kalaktang", null));
    out.add(new Language("kkg", "Mabaka Valley Kalinga", "I", "L", null, null, "Kalinga, Mabaka Valley", null));
    out.add(new Language("kkh", "Khün", "I", "L", null, null, null, null));
    out.add(new Language("kki", "Kagulu", "I", "L", null, null, null, null));
    out.add(new Language("kkj", "Kako", "I", "L", null, null, null, null));
    out.add(new Language("kkk", "Kokota", "I", "L", null, null, null, null));
    out.add(new Language("kkl", "Kosarek Yale", "I", "L", null, null, "Yale, Kosarek", null));
    out.add(new Language("kkm", "Kiong", "I", "L", null, null, null, null));
    out.add(new Language("kkn", "Kon Keu", "I", "L", null, null, null, null));
    out.add(new Language("kko", "Karko", "I", "L", null, null, null, null));
    out.add(new Language("kkp", "Gugubera", "I", "L", null, null, null, null));
    out.add(new Language("kkq", "Kaeku", "I", "L", null, null, null, null));
    out.add(new Language("kkr", "Kir-Balar", "I", "L", null, null, null, null));
    out.add(new Language("kks", "Giiwo", "I", "L", null, null, null, null));
    out.add(new Language("kkt", "Koi", "I", "L", null, null, null, null));
    out.add(new Language("kku", "Tumi", "I", "L", null, null, null, null));
    out.add(new Language("kkv", "Kangean", "I", "L", null, null, null, null));
    out.add(new Language("kkw", "Teke-Kukuya", "I", "L", null, null, null, null));
    out.add(new Language("kkx", "Kohin", "I", "L", null, null, null, null));
    out.add(new Language("kky", "Guugu Yimidhirr", "I", "L", null, null, null, null));
    out.add(new Language("kkz", "Kaska", "I", "L", null, null, null, null));
    out.add(new Language("kla", "Klamath-Modoc", "I", "E", null, null, null, null));
    out.add(new Language("klb", "Kiliwa", "I", "L", null, null, null, null));
    out.add(new Language("klc", "Kolbila", "I", "L", null, null, null, null));
    out.add(new Language("kld", "Gamilaraay", "I", "L", null, null, null, null));
    out.add(new Language("kle", "Kulung (Nepal)", "I", "L", null, null, null, null));
    out.add(new Language("klf", "Kendeje", "I", "L", null, null, null, null));
    out.add(new Language("klg", "Tagakaulo", "I", "L", null, null, null, null));
    out.add(new Language("klh", "Weliki", "I", "L", null, null, null, null));
    out.add(new Language("kli", "Kalumpang", "I", "L", null, null, null, null));
    out.add(new Language("klj", "Khalaj", "I", "L", null, null, null, null));
    out.add(new Language("klk", "Kono (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("kll", "Kagan Kalagan", "I", "L", null, null, "Kalagan, Kagan", null));
    out.add(new Language("klm", "Migum", "I", "L", null, null, null, null));
    out.add(new Language("kln", "Kalenjin", "M", "L", null, null, null, null));
    out.add(new Language("klo", "Kapya", "I", "L", null, null, null, null));
    out.add(new Language("klp", "Kamasa", "I", "L", null, null, null, null));
    out.add(new Language("klq", "Rumu", "I", "L", null, null, null, null));
    out.add(new Language("klr", "Khaling", "I", "L", null, null, null, null));
    out.add(new Language("kls", "Kalasha", "I", "L", null, null, null, null));
    out.add(new Language("klt", "Nukna", "I", "L", null, null, null, null));
    out.add(new Language("klu", "Klao", "I", "L", null, null, null, null));
    out.add(new Language("klv", "Maskelynes", "I", "L", null, null, null, null));
    out.add(new Language("klw", "Tado", "I", "L", null, null, null, null));
    out.add(new Language("klx", "Koluwawa", "I", "L", null, null, null, null));
    out.add(new Language("kly", "Kalao", "I", "L", null, null, null, null));
    out.add(new Language("klz", "Kabola", "I", "L", null, null, null, null));
    out.add(new Language("kma", "Konni", "I", "L", null, null, null, null));
    out.add(new Language("kmb", "Kimbundu", "I", "L", null, null, null, null));
    out.add(new Language("kmc", "Southern Dong", "I", "L", null, null, "Dong, Southern", null));
    out.add(new Language("kmd", "Majukayang Kalinga", "I", "L", null, null, "Kalinga, Majukayang", null));
    out.add(new Language("kme", "Bakole", "I", "L", null, null, null, null));
    out.add(new Language("kmf", "Kare (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("kmg", "Kâte", "I", "L", null, null, null, null));
    out.add(new Language("kmh", "Kalam", "I", "L", null, null, null, null));
    out.add(new Language("kmi", "Kami (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("kmj", "Kumarbhag Paharia", "I", "L", null, null, null, null));
    out.add(new Language("kmk", "Limos Kalinga", "I", "L", null, null, "Kalinga, Limos", null));
    out.add(new Language("kml", "Tanudan Kalinga", "I", "L", null, null, "Kalinga, Tanudan", null));
    out.add(new Language("kmm", "Kom (India)", "I", "L", null, null, null, null));
    out.add(new Language("kmn", "Awtuw", "I", "L", null, null, null, null));
    out.add(new Language("kmo", "Kwoma", "I", "L", null, null, null, null));
    out.add(new Language("kmp", "Gimme", "I", "L", null, null, null, null));
    out.add(new Language("kmq", "Kwama", "I", "L", null, null, null, null));
    out.add(new Language("kmr", "Northern Kurdish", "I", "L", null, null, "Kurdish, Northern", null));
    out.add(new Language("kms", "Kamasau", "I", "L", null, null, null, null));
    out.add(new Language("kmt", "Kemtuik", "I", "L", null, null, null, null));
    out.add(new Language("kmu", "Kanite", "I", "L", null, null, null, null));
    out.add(new Language("kmv", "Karipúna Creole French", "I", "L", null, null, "Creole French, Karipúna", null));
    out.add(new Language("kmw", "Komo (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("kmx", "Waboda", "I", "L", null, null, null, null));
    out.add(new Language("kmy", "Koma", "I", "L", null, null, null, null));
    out.add(new Language("kmz", "Khorasani Turkish", "I", "L", null, null, null, null));
    out.add(new Language("kna", "Dera (Nigeria)", "I", "L", null, null, null, null));
    out.add(new Language("knb", "Lubuagan Kalinga", "I", "L", null, null, "Kalinga, Lubuagan", null));
    out.add(new Language("knc", "Central Kanuri", "I", "L", null, null, "Kanuri, Central", null));
    out.add(new Language("knd", "Konda", "I", "L", null, null, null, null));
    out.add(new Language("kne", "Kankanaey", "I", "L", null, null, null, null));
    out.add(new Language("knf", "Mankanya", "I", "L", null, null, null, null));
    out.add(new Language("kng", "Koongo", "I", "L", null, null, null, null));
    out.add(new Language("kni", "Kanufi", "I", "L", null, null, null, null));
    out.add(new Language("knj", "Western Kanjobal", "I", "L", null, null, "Kanjobal, Western", null));
    out.add(new Language("knk", "Kuranko", "I", "L", null, null, null, null));
    out.add(new Language("knl", "Keninjal", "I", "L", null, null, null, null));
    out.add(new Language("knm", "Kanamarí", "I", "L", null, null, null, null));
    out.add(new Language("knn", "Konkani (individual language)", "I", "L", null, null, null, null));
    out.add(new Language("kno", "Kono (Sierra Leone)", "I", "L", null, null, null, null));
    out.add(new Language("knp", "Kwanja", "I", "L", null, null, null, null));
    out.add(new Language("knq", "Kintaq", "I", "L", null, null, null, null));
    out.add(new Language("knr", "Kaningra", "I", "L", null, null, null, null));
    out.add(new Language("kns", "Kensiu", "I", "L", null, null, null, null));
    out.add(new Language("knt", "Panoan Katukína", "I", "L", null, null, "Katukína, Panoan", null));
    out.add(new Language("knu", "Kono (Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("knv", "Tabo", "I", "L", null, null, null, null));
    out.add(new Language("knw", "Kung-Ekoka", "I", "L", null, null, null, null));
    out.add(new Language("knx", "Kendayan", "I", "L", null, null, null, null));
    out.add(new Language("kny", "Kanyok", "I", "L", null, null, null, null));
    out.add(new Language("knz", "Kalamsé", "I", "L", null, null, null, null));
    out.add(new Language("koa", "Konomala", "I", "L", null, null, null, null));
    out.add(new Language("koc", "Kpati", "I", "E", null, null, null, null));
    out.add(new Language("kod", "Kodi", "I", "L", null, null, null, null));
    out.add(new Language("koe", "Kacipo-Bale Suri", "I", "L", null, null, "Suri, Kacipo-Bale", null));
    out.add(new Language("kof", "Kubi", "I", "E", null, null, null, null));
    out.add(new Language("kog", "Cogui", "I", "L", null, null, null, null));
    out.add(new Language("koh", "Koyo", "I", "L", null, null, null, null));
    out.add(new Language("koi", "Komi-Permyak", "I", "L", null, null, null, null));
    out.add(new Language("kok", "Konkani (macrolanguage)", "M", "L", null, null, null, null));
    out.add(new Language("kol", "Kol (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("kom", "Komi", "M", "L", "kv", null, null, null));
    out.add(new Language("kon", "Kongo", "M", "L", "kg", null, null, null));
    out.add(new Language("koo", "Konzo", "I", "L", null, null, null, null));
    out.add(new Language("kop", "Waube", "I", "L", null, null, null, null));
    out.add(new Language("koq", "Kota (Gabon)", "I", "L", null, null, null, null));
    out.add(new Language("kor", "Korean", "I", "L", "ko", null, null, null));
    out.add(new Language("kos", "Kosraean", "I", "L", null, null, null, null));
    out.add(new Language("kot", "Lagwan", "I", "L", null, null, null, null));
    out.add(new Language("kou", "Koke", "I", "L", null, null, null, null));
    out.add(new Language("kov", "Kudu-Camo", "I", "L", null, null, null, null));
    out.add(new Language("kow", "Kugama", "I", "L", null, null, null, null));
    out.add(new Language("koy", "Koyukon", "I", "L", null, null, null, null));
    out.add(new Language("koz", "Korak", "I", "L", null, null, null, null));
    out.add(new Language("kpa", "Kutto", "I", "L", null, null, null, null));
    out.add(new Language("kpb", "Mullu Kurumba", "I", "L", null, null, "Kurumba, Mullu", null));
    out.add(new Language("kpc", "Curripaco", "I", "L", null, null, null, null));
    out.add(new Language("kpd", "Koba", "I", "L", null, null, null, null));
    out.add(new Language("kpe", "Kpelle", "M", "L", null, null, null, null));
    out.add(new Language("kpf", "Komba", "I", "L", null, null, null, null));
    out.add(new Language("kpg", "Kapingamarangi", "I", "L", null, null, null, null));
    out.add(new Language("kph", "Kplang", "I", "L", null, null, null, null));
    out.add(new Language("kpi", "Kofei", "I", "L", null, null, null, null));
    out.add(new Language("kpj", "Karajá", "I", "L", null, null, null, null));
    out.add(new Language("kpk", "Kpan", "I", "L", null, null, null, null));
    out.add(new Language("kpl", "Kpala", "I", "L", null, null, null, null));
    out.add(new Language("kpm", "Koho", "I", "L", null, null, null, null));
    out.add(new Language("kpn", "Kepkiriwát", "I", "E", null, null, null, null));
    out.add(new Language("kpo", "Ikposo", "I", "L", null, null, null, null));
    out.add(new Language("kpq", "Korupun-Sela", "I", "L", null, null, null, null));
    out.add(new Language("kpr", "Korafe-Yegha", "I", "L", null, null, null, null));
    out.add(new Language("kps", "Tehit", "I", "L", null, null, null, null));
    out.add(new Language("kpt", "Karata", "I", "L", null, null, null, null));
    out.add(new Language("kpu", "Kafoa", "I", "L", null, null, null, null));
    out.add(new Language("kpv", "Komi-Zyrian", "I", "L", null, null, null, null));
    out.add(new Language("kpw", "Kobon", "I", "L", null, null, null, null));
    out.add(new Language("kpx", "Mountain Koiali", "I", "L", null, null, "Koiali, Mountain", null));
    out.add(new Language("kpy", "Koryak", "I", "L", null, null, null, null));
    out.add(new Language("kpz", "Kupsabiny", "I", "L", null, null, null, null));
    out.add(new Language("kqa", "Mum", "I", "L", null, null, null, null));
    out.add(new Language("kqb", "Kovai", "I", "L", null, null, null, null));
    out.add(new Language("kqc", "Doromu-Koki", "I", "L", null, null, null, null));
    out.add(new Language("kqd", "Koy Sanjaq Surat", "I", "L", null, null, null, null));
    out.add(new Language("kqe", "Kalagan", "I", "L", null, null, null, null));
    out.add(new Language("kqf", "Kakabai", "I", "L", null, null, null, null));
    out.add(new Language("kqg", "Khe", "I", "L", null, null, null, null));
    out.add(new Language("kqh", "Kisankasa", "I", "L", null, null, null, null));
    out.add(new Language("kqi", "Koitabu", "I", "L", null, null, null, null));
    out.add(new Language("kqj", "Koromira", "I", "L", null, null, null, null));
    out.add(new Language("kqk", "Kotafon Gbe", "I", "L", null, null, "Gbe, Kotafon", null));
    out.add(new Language("kql", "Kyenele", "I", "L", null, null, null, null));
    out.add(new Language("kqm", "Khisa", "I", "L", null, null, null, null));
    out.add(new Language("kqn", "Kaonde", "I", "L", null, null, null, null));
    out.add(new Language("kqo", "Eastern Krahn", "I", "L", null, null, "Krahn, Eastern", null));
    out.add(new Language("kqp", "Kimré", "I", "L", null, null, null, null));
    out.add(new Language("kqq", "Krenak", "I", "L", null, null, null, null));
    out.add(new Language("kqr", "Kimaragang", "I", "L", null, null, null, null));
    out.add(new Language("kqs", "Northern Kissi", "I", "L", null, null, "Kissi, Northern", null));
    out.add(new Language("kqt", "Klias River Kadazan", "I", "L", null, null, "Kadazan, Klias River", null));
    out.add(new Language("kqu", "Seroa", "I", "E", null, null, null, null));
    out.add(new Language("kqv", "Okolod", "I", "L", null, null, null, null));
    out.add(new Language("kqw", "Kandas", "I", "L", null, null, null, null));
    out.add(new Language("kqx", "Mser", "I", "L", null, null, null, null));
    out.add(new Language("kqy", "Koorete", "I", "L", null, null, null, null));
    out.add(new Language("kqz", "Korana", "I", "E", null, null, null, null));
    out.add(new Language("kra", "Kumhali", "I", "L", null, null, null, null));
    out.add(new Language("krb", "Karkin", "I", "E", null, null, null, null));
    out.add(new Language("krc", "Karachay-Balkar", "I", "L", null, null, null, null));
    out.add(new Language("krd", "Kairui-Midiki", "I", "L", null, null, null, null));
    out.add(new Language("kre", "Panará", "I", "L", null, null, null, null));
    out.add(new Language("krf", "Koro (Vanuatu)", "I", "L", null, null, null, null));
    out.add(new Language("krh", "Kurama", "I", "L", null, null, null, null));
    out.add(new Language("kri", "Krio", "I", "L", null, null, null, null));
    out.add(new Language("krj", "Kinaray-A", "I", "L", null, null, null, null));
    out.add(new Language("krk", "Kerek", "I", "E", null, null, null, null));
    out.add(new Language("krl", "Karelian", "I", "L", null, null, null, null));
    out.add(new Language("krn", "Sapo", "I", "L", null, null, null, null));
    out.add(new Language("krp", "Durop", "I", "L", null, null, null, null));
    out.add(new Language("krr", "Krung", "I", "L", null, null, null, null));
    out.add(new Language("krs", "Gbaya (Sudan)", "I", "L", null, null, null, null));
    out.add(new Language("krt", "Tumari Kanuri", "I", "L", null, null, "Kanuri, Tumari", null));
    out.add(new Language("kru", "Kurukh", "I", "L", null, null, null, null));
    out.add(new Language("krv", "Kavet", "I", "L", null, null, null, null));
    out.add(new Language("krw", "Western Krahn", "I", "L", null, null, "Krahn, Western", null));
    out.add(new Language("krx", "Karon", "I", "L", null, null, null, null));
    out.add(new Language("kry", "Kryts", "I", "L", null, null, null, null));
    out.add(new Language("krz", "Sota Kanum", "I", "L", null, null, "Kanum, Sota", null));
    out.add(new Language("ksb", "Shambala", "I", "L", null, null, null, null));
    out.add(new Language("ksc", "Southern Kalinga", "I", "L", null, null, "Kalinga, Southern", null));
    out.add(new Language("ksd", "Kuanua", "I", "L", null, null, null, null));
    out.add(new Language("kse", "Kuni", "I", "L", null, null, null, null));
    out.add(new Language("ksf", "Bafia", "I", "L", null, null, null, null));
    out.add(new Language("ksg", "Kusaghe", "I", "L", null, null, null, null));
    out.add(new Language("ksh", "Kölsch", "I", "L", null, null, null, null));
    out.add(new Language("ksi", "Krisa", "I", "L", null, null, null, null));
    out.add(new Language("ksj", "Uare", "I", "L", null, null, null, null));
    out.add(new Language("ksk", "Kansa", "I", "L", null, null, null, null));
    out.add(new Language("ksl", "Kumalu", "I", "L", null, null, null, null));
    out.add(new Language("ksm", "Kumba", "I", "L", null, null, null, null));
    out.add(new Language("ksn", "Kasiguranin", "I", "L", null, null, null, null));
    out.add(new Language("kso", "Kofa", "I", "L", null, null, null, null));
    out.add(new Language("ksp", "Kaba", "I", "L", null, null, null, null));
    out.add(new Language("ksq", "Kwaami", "I", "L", null, null, null, null));
    out.add(new Language("ksr", "Borong", "I", "L", null, null, null, null));
    out.add(new Language("kss", "Southern Kisi", "I", "L", null, null, "Kisi, Southern", null));
    out.add(new Language("kst", "Winyé", "I", "L", null, null, null, null));
    out.add(new Language("ksu", "Khamyang", "I", "L", null, null, null, null));
    out.add(new Language("ksv", "Kusu", "I", "L", null, null, null, null));
    out.add(new Language("ksw", "S'gaw Karen", "I", "L", null, null, "Karen, S'gaw", null));
    out.add(new Language("ksx", "Kedang", "I", "L", null, null, null, null));
    out.add(new Language("ksy", "Kharia Thar", "I", "L", null, null, null, null));
    out.add(new Language("ksz", "Kodaku", "I", "L", null, null, null, null));
    out.add(new Language("kta", "Katua", "I", "L", null, null, null, null));
    out.add(new Language("ktb", "Kambaata", "I", "L", null, null, null, null));
    out.add(new Language("ktc", "Kholok", "I", "L", null, null, null, null));
    out.add(new Language("ktd", "Kokata", "I", "L", null, null, null, null));
    out.add(new Language("kte", "Nubri", "I", "L", null, null, null, null));
    out.add(new Language("ktf", "Kwami", "I", "L", null, null, null, null));
    out.add(new Language("ktg", "Kalkutung", "I", "E", null, null, null, null));
    out.add(new Language("kth", "Karanga", "I", "L", null, null, null, null));
    out.add(new Language("kti", "North Muyu", "I", "L", null, null, "Muyu, North", null));
    out.add(new Language("ktj", "Plapo Krumen", "I", "L", null, null, "Krumen, Plapo", null));
    out.add(new Language("ktk", "Kaniet", "I", "E", null, null, null, null));
    out.add(new Language("ktl", "Koroshi", "I", "L", null, null, null, null));
    out.add(new Language("ktm", "Kurti", "I", "L", null, null, null, null));
    out.add(new Language("ktn", "Karitiâna", "I", "L", null, null, null, null));
    out.add(new Language("kto", "Kuot", "I", "L", null, null, null, null));
    out.add(new Language("ktp", "Kaduo", "I", "L", null, null, null, null));
    out.add(new Language("ktq", "Katabaga", "I", "E", null, null, null, null));
    out.add(new Language("kts", "South Muyu", "I", "L", null, null, "Muyu, South", null));
    out.add(new Language("ktt", "Ketum", "I", "L", null, null, null, null));
    out.add(new Language("ktu", "Kituba (Democratic Republic of Congo)", "I", "L", null, null, null, null));
    out.add(new Language("ktv", "Eastern Katu", "I", "L", null, null, "Katu, Eastern", null));
    out.add(new Language("ktw", "Kato", "I", "E", null, null, null, null));
    out.add(new Language("ktx", "Kaxararí", "I", "L", null, null, null, null));
    out.add(new Language("kty", "Kango (Bas-Uélé District)", "I", "L", null, null, null, null));
    out.add(new Language("ktz", "Juǀʼhoan", "I", "L", null, null, null, null));
    out.add(new Language("kua", "Kuanyama", "I", "L", "kj", null, null, null));
    out.add(new Language("kub", "Kutep", "I", "L", null, null, null, null));
    out.add(new Language("kuc", "Kwinsu", "I", "L", null, null, null, null));
    out.add(new Language("kud", "'Auhelawa", "I", "L", null, null, null, null));
    out.add(new Language("kue", "Kuman (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("kuf", "Western Katu", "I", "L", null, null, "Katu, Western", null));
    out.add(new Language("kug", "Kupa", "I", "L", null, null, null, null));
    out.add(new Language("kuh", "Kushi", "I", "L", null, null, null, null));
    out.add(new Language("kui", "Kuikúro-Kalapálo", "I", "L", null, null, null, null));
    out.add(new Language("kuj", "Kuria", "I", "L", null, null, null, null));
    out.add(new Language("kuk", "Kepo'", "I", "L", null, null, null, null));
    out.add(new Language("kul", "Kulere", "I", "L", null, null, null, null));
    out.add(new Language("kum", "Kumyk", "I", "L", null, null, null, null));
    out.add(new Language("kun", "Kunama", "I", "L", null, null, null, null));
    out.add(new Language("kuo", "Kumukio", "I", "L", null, null, null, null));
    out.add(new Language("kup", "Kunimaipa", "I", "L", null, null, null, null));
    out.add(new Language("kuq", "Karipuna", "I", "L", null, null, null, null));
    out.add(new Language("kur", "Kurdish", "M", "L", "ku", null, null, null));
    out.add(new Language("kus", "Kusaal", "I", "L", null, null, null, null));
    out.add(new Language("kut", "Kutenai", "I", "L", null, null, null, null));
    out.add(new Language("kuu", "Upper Kuskokwim", "I", "L", null, null, "Kuskokwim, Upper", null));
    out.add(new Language("kuv", "Kur", "I", "L", null, null, null, null));
    out.add(new Language("kuw", "Kpagua", "I", "L", null, null, null, null));
    out.add(new Language("kux", "Kukatja", "I", "L", null, null, null, null));
    out.add(new Language("kuy", "Kuuku-Ya'u", "I", "L", null, null, null, null));
    out.add(new Language("kuz", "Kunza", "I", "E", null, null, null, null));
    out.add(new Language("kva", "Bagvalal", "I", "L", null, null, null, null));
    out.add(new Language("kvb", "Kubu", "I", "L", null, null, null, null));
    out.add(new Language("kvc", "Kove", "I", "L", null, null, null, null));
    out.add(new Language("kvd", "Kui (Indonesia)", "I", "L", null, null, null, null));
    out.add(new Language("kve", "Kalabakan", "I", "L", null, null, null, null));
    out.add(new Language("kvf", "Kabalai", "I", "L", null, null, null, null));
    out.add(new Language("kvg", "Kuni-Boazi", "I", "L", null, null, null, null));
    out.add(new Language("kvh", "Komodo", "I", "L", null, null, null, null));
    out.add(new Language("kvi", "Kwang", "I", "L", null, null, null, null));
    out.add(new Language("kvj", "Psikye", "I", "L", null, null, null, null));
    out.add(new Language("kvk", "Korean Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("kvl", "Kayaw", "I", "L", null, null, null, null));
    out.add(new Language("kvm", "Kendem", "I", "L", null, null, null, null));
    out.add(new Language("kvn", "Border Kuna", "I", "L", null, null, "Kuna, Border", null));
    out.add(new Language("kvo", "Dobel", "I", "L", null, null, null, null));
    out.add(new Language("kvp", "Kompane", "I", "L", null, null, null, null));
    out.add(new Language("kvq", "Geba Karen", "I", "L", null, null, "Karen, Geba", null));
    out.add(new Language("kvr", "Kerinci", "I", "L", null, null, null, null));
    out.add(new Language("kvt", "Lahta Karen", "I", "L", null, null, "Karen, Lahta", null));
    out.add(new Language("kvu", "Yinbaw Karen", "I", "L", null, null, "Karen, Yinbaw", null));
    out.add(new Language("kvv", "Kola", "I", "L", null, null, null, null));
    out.add(new Language("kvw", "Wersing", "I", "L", null, null, null, null));
    out.add(new Language("kvx", "Parkari Koli", "I", "L", null, null, "Koli, Parkari", null));
    out.add(new Language("kvy", "Yintale Karen", "I", "L", null, null, "Karen, Yintale", null));
    out.add(new Language("kvz", "Tsakwambo", "I", "L", null, null, null, null));
    out.add(new Language("kwa", "Dâw", "I", "L", null, null, null, null));
    out.add(new Language("kwb", "Kwa", "I", "L", null, null, null, null));
    out.add(new Language("kwc", "Likwala", "I", "L", null, null, null, null));
    out.add(new Language("kwd", "Kwaio", "I", "L", null, null, null, null));
    out.add(new Language("kwe", "Kwerba", "I", "L", null, null, null, null));
    out.add(new Language("kwf", "Kwara'ae", "I", "L", null, null, null, null));
    out.add(new Language("kwg", "Sara Kaba Deme", "I", "L", null, null, null, null));
    out.add(new Language("kwh", "Kowiai", "I", "L", null, null, null, null));
    out.add(new Language("kwi", "Awa-Cuaiquer", "I", "L", null, null, null, null));
    out.add(new Language("kwj", "Kwanga", "I", "L", null, null, null, null));
    out.add(new Language("kwk", "Kwak'wala", "I", "L", null, null, null, null));
    out.add(new Language("kwl", "Kofyar", "I", "L", null, null, null, null));
    out.add(new Language("kwm", "Kwambi", "I", "L", null, null, null, null));
    out.add(new Language("kwn", "Kwangali", "I", "L", null, null, null, null));
    out.add(new Language("kwo", "Kwomtari", "I", "L", null, null, null, null));
    out.add(new Language("kwp", "Kodia", "I", "L", null, null, null, null));
    out.add(new Language("kwr", "Kwer", "I", "L", null, null, null, null));
    out.add(new Language("kws", "Kwese", "I", "L", null, null, null, null));
    out.add(new Language("kwt", "Kwesten", "I", "L", null, null, null, null));
    out.add(new Language("kwu", "Kwakum", "I", "L", null, null, null, null));
    out.add(new Language("kwv", "Sara Kaba Náà", "I", "L", null, null, null, null));
    out.add(new Language("kww", "Kwinti", "I", "L", null, null, null, null));
    out.add(new Language("kwx", "Khirwar", "I", "L", null, null, null, null));
    out.add(new Language("kwy", "San Salvador Kongo", "I", "L", null, null, "Kongo, San Salvador", null));
    out.add(new Language("kwz", "Kwadi", "I", "E", null, null, null, null));
    out.add(new Language("kxa", "Kairiru", "I", "L", null, null, null, null));
    out.add(new Language("kxb", "Krobu", "I", "L", null, null, null, null));
    out.add(new Language("kxc", "Konso", "I", "L", null, null, null, null));
    out.add(new Language("kxd", "Brunei", "I", "L", null, null, null, null));
    out.add(new Language("kxf", "Manumanaw Karen", "I", "L", null, null, "Karen, Manumanaw", null));
    out.add(new Language("kxh", "Karo (Ethiopia)", "I", "L", null, null, null, null));
    out.add(new Language("kxi", "Keningau Murut", "I", "L", null, null, "Murut, Keningau", null));
    out.add(new Language("kxj", "Kulfa", "I", "L", null, null, null, null));
    out.add(new Language("kxk", "Zayein Karen", "I", "L", null, null, "Karen, Zayein", null));
    out.add(new Language("kxm", "Northern Khmer", "I", "L", null, null, "Khmer, Northern", null));
    out.add(new Language("kxn", "Kanowit-Tanjong Melanau", "I", "L", null, null, "Melanau, Kanowit-Tanjong", null));
    out.add(new Language("kxo", "Kanoé", "I", "E", null, null, null, null));
    out.add(new Language("kxp", "Wadiyara Koli", "I", "L", null, null, "Koli, Wadiyara", null));
    out.add(new Language("kxq", "Smärky Kanum", "I", "L", null, null, "Kanum, Smärky", null));
    out.add(new Language("kxr", "Koro (Papua New Guinea)", "I", "L", null, null, null, null));
    out.add(new Language("kxs", "Kangjia", "I", "L", null, null, null, null));
    out.add(new Language("kxt", "Koiwat", "I", "L", null, null, null, null));
    out.add(new Language("kxv", "Kuvi", "I", "L", null, null, null, null));
    out.add(new Language("kxw", "Konai", "I", "L", null, null, null, null));
    out.add(new Language("kxx", "Likuba", "I", "L", null, null, null, null));
    out.add(new Language("kxy", "Kayong", "I", "L", null, null, null, null));
    out.add(new Language("kxz", "Kerewo", "I", "L", null, null, null, null));
    out.add(new Language("kya", "Kwaya", "I", "L", null, null, null, null));
    out.add(new Language("kyb", "Butbut Kalinga", "I", "L", null, null, "Kalinga, Butbut", null));
    out.add(new Language("kyc", "Kyaka", "I", "L", null, null, null, null));
    out.add(new Language("kyd", "Karey", "I", "L", null, null, null, null));
    out.add(new Language("kye", "Krache", "I", "L", null, null, null, null));
    out.add(new Language("kyf", "Kouya", "I", "L", null, null, null, null));
    out.add(new Language("kyg", "Keyagana", "I", "L", null, null, null, null));
    out.add(new Language("kyh", "Karok", "I", "L", null, null, null, null));
    out.add(new Language("kyi", "Kiput", "I", "L", null, null, null, null));
    out.add(new Language("kyj", "Karao", "I", "L", null, null, null, null));
    out.add(new Language("kyk", "Kamayo", "I", "L", null, null, null, null));
    out.add(new Language("kyl", "Kalapuya", "I", "L", null, null, null, null));
    out.add(new Language("kym", "Kpatili", "I", "L", null, null, null, null));
    out.add(new Language("kyn", "Northern Binukidnon", "I", "L", null, null, "Binukidnon, Northern", null));
    out.add(new Language("kyo", "Kelon", "I", "L", null, null, null, null));
    out.add(new Language("kyp", "Kang", "I", "L", null, null, null, null));
    out.add(new Language("kyq", "Kenga", "I", "L", null, null, null, null));
    out.add(new Language("kyr", "Kuruáya", "I", "L", null, null, null, null));
    out.add(new Language("kys", "Baram Kayan", "I", "L", null, null, "Kayan, Baram", null));
    out.add(new Language("kyt", "Kayagar", "I", "L", null, null, null, null));
    out.add(new Language("kyu", "Western Kayah", "I", "L", null, null, "Kayah, Western", null));
    out.add(new Language("kyv", "Kayort", "I", "L", null, null, null, null));
    out.add(new Language("kyw", "Kudmali", "I", "L", null, null, null, null));
    out.add(new Language("kyx", "Rapoisi", "I", "L", null, null, null, null));
    out.add(new Language("kyy", "Kambaira", "I", "L", null, null, null, null));
    out.add(new Language("kyz", "Kayabí", "I", "L", null, null, null, null));
    out.add(new Language("kza", "Western Karaboro", "I", "L", null, null, "Karaboro, Western", null));
    out.add(new Language("kzb", "Kaibobo", "I", "L", null, null, null, null));
    out.add(new Language("kzc", "Bondoukou Kulango", "I", "L", null, null, "Kulango, Bondoukou", null));
    out.add(new Language("kzd", "Kadai", "I", "L", null, null, null, null));
    out.add(new Language("kze", "Kosena", "I", "L", null, null, null, null));
    out.add(new Language("kzf", "Da'a Kaili", "I", "L", null, null, "Kaili, Da'a", null));
    out.add(new Language("kzg", "Kikai", "I", "L", null, null, null, null));
    out.add(new Language("kzi", "Kelabit", "I", "L", null, null, null, null));
    out.add(new Language("kzk", "Kazukuru", "I", "E", null, null, null, null));
    out.add(new Language("kzl", "Kayeli", "I", "L", null, null, null, null));
    out.add(new Language("kzm", "Kais", "I", "L", null, null, null, null));
    out.add(new Language("kzn", "Kokola", "I", "L", null, null, null, null));
    out.add(new Language("kzo", "Kaningi", "I", "L", null, null, null, null));
    out.add(new Language("kzp", "Kaidipang", "I", "L", null, null, null, null));
    out.add(new Language("kzq", "Kaike", "I", "L", null, null, null, null));
    out.add(new Language("kzr", "Karang", "I", "L", null, null, null, null));
    out.add(new Language("kzs", "Sugut Dusun", "I", "L", null, null, "Dusun, Sugut", null));
    out.add(new Language("kzu", "Kayupulau", "I", "L", null, null, null, null));
    out.add(new Language("kzv", "Komyandaret", "I", "L", null, null, null, null));
    out.add(new Language("kzw", "Karirí-Xocó", "I", "E", null, null, null, null));
    out.add(new Language("kzx", "Kamarian", "I", "E", null, null, null, null));
    out.add(new Language("kzy", "Kango (Tshopo District)", "I", "L", null, null, null, null));
    out.add(new Language("kzz", "Kalabra", "I", "L", null, null, null, null));
    out.add(new Language("laa", "Southern Subanen", "I", "L", null, null, "Subanen, Southern", null));
    out.add(new Language("lab", "Linear A", "I", "H", null, null, null, null));
    out.add(new Language("lac", "Lacandon", "I", "L", null, null, null, null));
    out.add(new Language("lad", "Ladino", "I", "L", null, null, null, null));
    out.add(new Language("lae", "Pattani", "I", "L", null, null, null, null));
    out.add(new Language("laf", "Lafofa", "I", "L", null, null, null, null));
    out.add(new Language("lag", "Rangi", "I", "L", null, null, null, null));
    out.add(new Language("lah", "Lahnda", "M", "L", null, null, null, null));
    out.add(new Language("lai", "Lambya", "I", "L", null, null, null, null));
    out.add(new Language("laj", "Lango (Uganda)", "I", "L", null, null, null, null));
    out.add(new Language("lal", "Lalia", "I", "L", null, null, null, null));
    out.add(new Language("lam", "Lamba", "I", "L", null, null, null, null));
    out.add(new Language("lan", "Laru", "I", "L", null, null, null, null));
    out.add(new Language("lao", "Lao", "I", "L", "lo", null, null, null));
    out.add(new Language("lap", "Laka (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("laq", "Qabiao", "I", "L", null, null, null, null));
    out.add(new Language("lar", "Larteh", "I", "L", null, null, null, null));
    out.add(new Language("las", "Lama (Togo)", "I", "L", null, null, null, null));
    out.add(new Language("lat", "Latin", "I", "H", "la", null, null, null));
    out.add(new Language("lau", "Laba", "I", "L", null, null, null, null));
    out.add(new Language("lav", "Latvian", "M", "L", "lv", null, null, null));
    out.add(new Language("law", "Lauje", "I", "L", null, null, null, null));
    out.add(new Language("lax", "Tiwa", "I", "L", null, null, null, null));
  }
}
