// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso639;

import java.util.List;

/**
 * Entries 2000 to 2499 of {@link Language}.
 */
final class LanguageData4 {
  private LanguageData4() {
  }

  static void addTo(List<Language> out) {
    out.add(new Language("gan", "Gan Chinese", "I", "L", null, null, "Chinese, Gan", null));
    out.add(new Language("gao", "Gants", "I", "L", null, null, null, null));
    out.add(new Language("gap", "Gal", "I", "L", null, null, null, null));
    out.add(new Language("gaq", "Gata'", "I", "L", null, null, null, null));
    out.add(new Language("gar", "Galeya", "I", "L", null, null, null, null));
    out.add(new Language("gas", "Adiwasi Garasia", "I", "L", null, null, "Garasia, Adiwasi", null));
    out.add(new Language("gat", "Kenati", "I", "L", null, null, null, null));
    out.add(new Language("gau", "Mudhili Gadaba", "I", "L", null, null, "Gadaba, Mudhili", null));
    out.add(new Language("gaw", "Nobonob", "I", "L", null, null, null, null));
    out.add(new Language("gax", "Borana-Arsi-Guji Oromo", "I", "L", null, null, "Oromo, Borana-Arsi-Guji", null));
    out.add(new Language("gay", "Gayo", "I", "L", null, null, null, null));
    out.add(new Language("gaz", "West Central Oromo", "I", "L", null, null, "Oromo, West Central", null));
    out.add(new Language("gba", "Gbaya (Central African Republic)", "M", "L", null, null, null, null));
    out.add(new Language("gbb", "Kaytetye", "I", "L", null, null, null, null));
    out.add(new Language("gbd", "Karajarri", "I", "L", null, null, null, null));
    out.add(new Language("gbe", "Niksek", "I", "L", null, null, null, null));
    out.add(new Language("gbf", "Gaikundi", "I", "L", null, null, null, null));
    out.add(new Language("gbg", "Gbanziri", "I", "L", null, null, null, null));
    out.add(new Language("gbh", "Defi Gbe", "I", "L", null, null, "Gbe, Defi", null));
    out.add(new Language("gbi", "Galela", "I", "L", null, null, null, null));
    out.add(new Language("gbj", "Bodo Gadaba", "I", "L", null, null, "Gadaba, Bodo", null));
    out.add(new Language("gbk", "Gaddi", "I", "L", null, null, null, null));
    out.add(new Language("gbl", "Gamit", "I", "L", null, null, null, null));
    out.add(new Language("gbm", "Garhwali", "I", "L", null, null, null, null));
    out.add(new Language("gbn", "Mo'da", "I", "L", null, null, null, null));
    out.add(new Language("gbo", "Northern Grebo", "I", "L", null, null, "Grebo, Northern", null));
    out.add(new Language("gbp", "Gbaya-Bossangoa", "I", "L", null, null, null, null));
    out.add(new Language("gbq", "Gbaya-Bozoum", "I", "L", null, null, null, null));
    out.add(new Language("gbr", "Gbagyi", "I", "L", null, null, null, null));
    out.add(new Language("gbs", "Gbesi Gbe", "I", "L", null, null, "Gbe, Gbesi", null));
    out.add(new Language("gbu", "Gagadu", "I", "L", null, null, null, null));
    out.add(new Language("gbv", "Gbanu", "I", "L", null, null, null, null));
    out.add(new Language("gbw", "Gabi-Gabi", "I", "L", null, null, null, null));
    out.add(new Language("gbx", "Eastern Xwla Gbe", "I", "L", null, null, "Gbe, Eastern Xwla", null));
    out.add(new Language("gby", "Gbari", "I", "L", null, null, null, null));
    out.add(new Language("gbz", "Zoroastrian Dari", "I", "L", null, null, "Dari, Zoroastrian", null));
    out.add(new Language("gcc", "Mali", "I", "L", null, null, null, null));
    out.add(new Language("gcd", "Ganggalida", "I", "E", null, null, null, null));
    out.add(new Language("gce", "Galice", "I", "E", null, null, null, null));
    out.add(new Language("gcf", "Guadeloupean Creole French", "I", "L", null, null, "Creole French, Guadeloupean", null));
    out.add(new Language("gcl", "Grenadian Creole English", "I", "L", null, null, "Creole English, Grenadian", null));
    out.add(new Language("gcn", "Gaina", "I", "L", null, null, null, null));
    out.add(new Language("gcr", "Guianese Creole French", "I", "L", null, null, "Creole French, Guianese", null));
    out.add(new Language("gct", "Colonia Tovar German", "I", "L", null, null, "German, Colonia Tovar", null));
    out.add(new Language("gda", "Gade Lohar", "I", "L", null, null, "Lohar, Gade", null));
    out.add(new Language("gdb", "Pottangi Ollar Gadaba", "I", "L", null, null, "Gadaba, Pottangi Ollar", null));
    out.add(new Language("gdc", "Gugu Badhun", "I", "E", null, null, null, null));
    out.add(new Language("gdd", "Gedaged", "I", "L", null, null, null, null));
    out.add(new Language("gde", "Gude", "I", "L", null, null, null, null));
    out.add(new Language("gdf", "Guduf-Gava", "I", "L", null, null, null, null));
    out.add(new Language("gdg", "Ga'dang", "I", "L", null, null, null, null));
    out.add(new Language("gdh", "Gadjerawang", "I", "L", null, null, null, null));
    out.add(new Language("gdi", "Gundi", "I", "L", null, null, null, null));
    out.add(new Language("gdj", "Gurdjar", "I", "L", null, null, null, null));
    out.add(new Language("gdk", "Gadang", "I", "L", null, null, null, null));
    out.add(new Language("gdl", "Dirasha", "I", "L", null, null, null, null));
    out.add(new Language("gdm", "Laal", "I", "L", null, null, null, null));
    out.add(new Language("gdn", "Umanakaina", "I", "L", null, null, null, null));
    out.add(new Language("gdo", "Ghodoberi", "I", "L", null, null, null, null));
    out.add(new Language("gdq", "Mehri", "I", "L", null, null, null, null));
    out.add(new Language("gdr", "Wipi", "I", "L", null, null, null, null));
    out.add(new Language("gds", "Ghandruk Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gdt", "Kungardutyi", "I", "E", null, null, null, null));
    out.add(new Language("gdu", "Gudu", "I", "L", null, null, null, null));
    out.add(new Language("gdx", "Godwari", "I", "L", null, null, null, null));
    out.add(new Language("gea", "Geruma", "I", "L", null, null, null, null));
    out.add(new Language("geb", "Kire", "I", "L", null, null, null, null));
    out.add(new Language("gec", "Gboloo Grebo", "I", "L", null, null, "Grebo, Gboloo", null));
    out.add(new Language("ged", "Gade", "I", "L", null, null, null, null));
    out.add(new Language("gef", "Gerai", "I", "L", null, null, null, null));
    out.add(new Language("geg", "Gengle", "I", "L", null, null, null, null));
    out.add(new Language("geh", "Hutterite German", "I", "L", null, null, "German, Hutterite", null));
    out.add(new Language("gei", "Gebe", "I", "L", null, null, null, null));
    out.add(new Language("gej", "Gen", "I", "L", null, null, null, null));
    out.add(new Language("gek", "Ywom", "I", "L", null, null, null, null));
    out.add(new Language("gel", "ut-Ma'in", "I", "L", null, null, null, null));
    out.add(new Language("geq", "Geme", "I", "L", null, null, null, null));
    out.add(new Language("ges", "Geser-Gorom", "I", "L", null, null, null, null));
    out.add(new Language("gev", "Eviya", "I", "L", null, null, null, null));
    out.add(new Language("gew", "Gera", "I", "L", null, null, null, null));
    out.add(new Language("gex", "Garre", "I", "L", null, null, null, null));
    out.add(new Language("gey", "Enya", "I", "L", null, null, null, null));
    out.add(new Language("gez", "Geez", "I", "H", null, null, null, null));
    out.add(new Language("gfk", "Patpatar", "I", "L", null, null, null, null));
    out.add(new Language("gft", "Gafat", "I", "E", null, null, null, null));
    out.add(new Language("gga", "Gao", "I", "L", null, null, null, null));
    out.add(new Language("ggb", "Gbii", "I", "L", null, null, null, null));
    out.add(new Language("ggd", "Gugadj", "I", "E", null, null, null, null));
    out.add(new Language("gge", "Gurr-goni", "I", "L", null, null, null, null));
    out.add(new Language("ggg", "Gurgula", "I", "L", null, null, null, null));
    out.add(new Language("ggk", "Kungarakany", "I", "E", null, null, null, null));
    out.add(new Language("ggl", "Ganglau", "I", "L", null, null, null, null));
    out.add(new Language("ggt", "Gitua", "I", "L", null, null, null, null));
    out.add(new Language("ggu", "Gagu", "I", "L", null, null, null, null));
    out.add(new Language("ggw", "Gogodala", "I", "L", null, null, null, null));
    out.add(new Language("gha", "Ghadamès", "I", "L", null, null, null, null));
    out.add(new Language("ghc", "Hiberno-Scottish Gaelic", "I", "H", null, null, "Gaelic, Hiberno-Scottish", null));
    out.add(new Language("ghe", "Southern Ghale", "I", "L", null, null, "Ghale, Southern", null));
    out.add(new Language("ghh", "Northern Ghale", "I", "L", null, null, "Ghale, Northern", null));
    out.add(new Language("ghk", "Geko Karen", "I", "L", null, null, "Karen, Geko", null));
    out.add(new Language("ghl", "Ghulfan", "I", "L", null, null, null, null));
    out.add(new Language("ghn", "Ghanongga", "I", "L", null, null, null, null));
    out.add(new Language("gho", "Ghomara", "I", "L", null, null, null, null));
    out.add(new Language("ghr", "Ghera", "I", "L", null, null, null, null));
    out.add(new Language("ghs", "Guhu-Samane", "I", "L", null, null, null, null));
    out.add(new Language("ght", "Kuke", "I", "L", null, null, null, null));
    out.add(new Language("gia", "Kija", "I", "L", null, null, null, null));
    out.add(new Language("gib", "Gibanawa", "I", "L", null, null, null, null));
    out.add(new Language("gic", "Gail", "I", "L", null, null, null, null));
    out.add(new Language("gid", "Gidar", "I", "L", null, null, null, null));
    out.add(new Language("gie", "Gaɓogbo", "I", "L", null, null, null, null));
    out.add(new Language("gig", "Goaria", "I", "L", null, null, null, null));
    out.add(new Language("gih", "Githabul", "I", "L", null, null, null, null));
    out.add(new Language("gii", "Girirra", "I", "L", null, null, null, null));
    out.add(new Language("gil", "Gilbertese", "I", "L", null, null, null, null));
    out.add(new Language("gim", "Gimi (Eastern Highlands)", "I", "L", null, null, null, null));
    out.add(new Language("gin", "Hinukh", "I", "L", null, null, null, null));
    out.add(new Language("gip", "Gimi (West New Britain)", "I", "L", null, null, null, null));
    out.add(new Language("giq", "Green Gelao", "I", "L", null, null, "Gelao, Green", null));
    out.add(new Language("gir", "Red Gelao", "I", "L", null, null, "Gelao, Red", null));
    out.add(new Language("gis", "North Giziga", "I", "L", null, null, "Giziga, North", null));
    out.add(new Language("git", "Gitxsan", "I", "L", null, null, null, null));
    out.add(new Language("giu", "Mulao", "I", "L", null, null, null, null));
    out.add(new Language("giw", "White Gelao", "I", "L", null, null, "Gelao, White", null));
    out.add(new Language("gix", "Gilima", "I", "L", null, null, null, null));
    out.add(new Language("giy", "Giyug", "I", "L", null, null, null, null));
    out.add(new Language("giz", "South Giziga", "I", "L", null, null, "Giziga, South", null));
    out.add(new Language("gjk", "Kachi Koli", "I", "L", null, null, "Koli, Kachi", null));
    out.add(new Language("gjm", "Gunditjmara", "I", "E", null, null, null, null));
    out.add(new Language("gjn", "Gonja", "I", "L", null, null, null, null));
    out.add(new Language("gjr", "Gurindji Kriol", "I", "L", null, null, null, null));
    out.add(new Language("gju", "Gujari", "I", "L", null, null, null, null));
    out.add(new Language("gka", "Guya", "I", "L", null, null, null, null));
    out.add(new Language("gkd", "Magɨ (Madang Province)", "I", "L", null, null, null, null));
    out.add(new Language("gke", "Ndai", "I", "L", null, null, null, null));
    out.add(new Language("gkn", "Gokana", "I", "L", null, null, null, null));
    out.add(new Language("gko", "Kok-Nar", "I", "E", null, null, null, null));
    out.add(new Language("gkp", "Guinea Kpelle", "I", "L", null, null, "Kpelle, Guinea", null));
    out.add(new Language("gku", "ǂUngkue", "I", "E", null, null, null, null));
    out.add(new Language("gla", "Scottish Gaelic", "I", "L", "gd", null, "Gaelic, Scottish", null));
    out.add(new Language("glb", "Belning", "I", "L", null, null, null, null));
    out.add(new Language("glc", "Bon Gula", "I", "L", null, null, null, null));
    out.add(new Language("gld", "Nanai", "I", "L", null, null, null, null));
    out.add(new Language("gle", "Irish", "I", "L", "ga", null, null, null));
    out.add(new Language("glg", "Galician", "I", "L", "gl", null, null, null));
    out.add(new Language("glh", "Northwest Pashai", "I", "L", null, null, "Pashai, Northwest", null));
    out.add(new Language("glj", "Gula Iro", "I", "L", null, null, null, null));
    out.add(new Language("glk", "Gilaki", "I", "L", null, null, null, null));
    out.add(new Language("gll", "Garlali", "I", "E", null, null, null, null));
    out.add(new Language("glo", "Galambu", "I", "L", null, null, null, null));
    out.add(new Language("glr", "Glaro-Twabo", "I", "L", null, null, null, null));
    out.add(new Language("glu", "Gula (Chad)", "I", "L", null, null, null, null));
    out.add(new Language("glv", "Manx", "I", "L", "gv", null, null, null));
    out.add(new Language("glw", "Glavda", "I", "L", null, null, null, null));
    out.add(new Language("gly", "Gule", "I", "E", null, null, null, null));
    out.add(new Language("gma", "Gambera", "I", "E", null, null, null, null));
    out.add(new Language("gmb", "Gula'alaa", "I", "L", null, null, null, null));
    out.add(new Language("gmd", "Mághdì", "I", "L", null, null, null, null));
    out.add(new Language("gmg", "Magɨyi", "I", "L", null, null, null, null));
    out.add(new Language("gmh", "Middle High German (ca. 1050-1500)", "I", "H", null, null, "German, Middle High (ca. 1050-1500)", null));
    out.add(new Language("gml", "Middle Low German", "I", "H", null, null, "German, Middle Low", null));
    out.add(new Language("gmm", "Gbaya-Mbodomo", "I", "L", null, null, null, null));
    out.add(new Language("gmn", "Gimnime", "I", "L", null, null, null, null));
    out.add(new Language("gmr", "Mirning", "I", "L", null, null, null, null));
    out.add(new Language("gmu", "Gumalu", "I", "L", null, null, null, null));
    out.add(new Language("gmv", "Gamo", "I", "L", null, null, null, null));
    out.add(new Language("gmx", "Magoma", "I", "L", null, null, null, null));
    out.add(new Language("gmy", "Mycenaean Greek", "I", "H", null, null, "Greek, Mycenaean", null));
    out.add(new Language("gmz", "Mgbolizhia", "I", "L", null, null, null, null));
    out.add(new Language("gna", "Kaansa", "I", "L", null, null, null, null));
    out.add(new Language("gnb", "Gangte", "I", "L", null, null, null, null));
    out.add(new Language("gnc", "Guanche", "I", "E", null, null, null, null));
    out.add(new Language("gnd", "Zulgo-Gemzek", "I", "L", null, null, null, null));
    out.add(new Language("gne", "Ganang", "I", "L", null, null, null, null));
    out.add(new Language("gng", "Ngangam", "I", "L", null, null, null, null));
    out.add(new Language("gnh", "Lere", "I", "L", null, null, null, null));
    out.add(new Language("gni", "Gooniyandi", "I", "L", null, null, null, null));
    out.add(new Language("gnj", "Ngen", "I", "L", null, null, null, null));
    out.add(new Language("gnk", "ǁGana", "I", "L", null, null, null, null));
    out.add(new Language("gnl", "Gangulu", "I", "E", null, null, null, null));
    out.add(new Language("gnm", "Ginuman", "I", "L", null, null, null, null));
    out.add(new Language("gnn", "Gumatj", "I", "L", null, null, null, null));
    out.add(new Language("gno", "Northern Gondi", "I", "L", null, null, "Gondi, Northern", null));
    out.add(new Language("gnq", "Gana", "I", "L", null, null, null, null));
    out.add(new Language("gnr", "Gureng Gureng", "I", "E", null, null, null, null));
    out.add(new Language("gnt", "Guntai", "I", "L", null, null, null, null));
    out.add(new Language("gnu", "Gnau", "I", "L", null, null, null, null));
    out.add(new Language("gnw", "Western Bolivian Guaraní", "I", "L", null, null, "Guaraní, Western Bolivian", null));
    out.add(new Language("gnz", "Ganzi", "I", "L", null, null, null, null));
    out.add(new Language("goa", "Guro", "I", "L", null, null, null, null));
    out.add(new Language("gob", "Playero", "I", "L", null, null, null, null));
    out.add(new Language("goc", "Gorakor", "I", "L", null, null, null, null));
    out.add(new Language("god", "Godié", "I", "L", null, null, null, null));
    out.add(new Language("goe", "Gongduk", "I", "L", null, null, null, null));
    out.add(new Language("gof", "Gofa", "I", "L", null, null, null, null));
    out.add(new Language("gog", "Gogo", "I", "L", null, null, null, null));
    out.add(new Language("goh", "Old High German (ca. 750-1050)", "I", "H", null, null, "German, Old High (ca. 750-1050)", null));
    out.add(new Language("goi", "Gobasi", "I", "L", null, null, null, null));
    out.add(new Language("goj", "Gowlan", "I", "L", null, null, null, null));
    out.add(new Language("gok", "Gowli", "I", "L", null, null, null, null));
    out.add(new Language("gol", "Gola", "I", "L", null, null, null, null));
    out.add(new Language("gom", "Goan Konkani", "I", "L", null, null, "Konkani, Goan", null));
    out.add(new Language("gon", "Gondi", "M", "L", null, null, null, null));
    out.add(new Language("goo", "Gone Dau", "I", "L", null, null, null, null));
    out.add(new Language("gop", "Yeretuar", "I", "L", null, null, null, null));
    out.add(new Language("goq", "Gorap", "I", "L", null, null, null, null));
    out.add(new Language("gor", "Gorontalo", "I", "L", null, null, null, null));
    out.add(new Language("gos", "Gronings", "I", "L", null, null, null, null));
    out.add(new Language("got", "Gothic", "I", "H", null, null, null, null));
    out.add(new Language("gou", "Gavar", "I", "L", null, null, null, null));
    out.add(new Language("gov", "Goo", "I", "L", null, null, null, null));
    out.add(new Language("gow", "Gorowa", "I", "L", null, null, null, null));
    out.add(new Language("gox", "Gobu", "I", "L", null, null, null, null));
    out.add(new Language("goy", "Goundo", "I", "L", null, null, null, null));
    out.add(new Language("goz", "Gozarkhani", "I", "L", null, null, null, null));
    out.add(new Language("gpa", "Gupa-Abawa", "I", "L", null, null, null, null));
    out.add(new Language("gpe", "Ghanaian Pidgin English", "I", "L", null, null, "Pidgin English, Ghanaian", null));
    out.add(new Language("gpn", "Taiap", "I", "L", null, null, null, null));
    out.add(new Language("gqa", "Ga'anda", "I", "L", null, null, null, null));
    out.add(new Language("gqi", "Guiqiong", "I", "L", null, null, null, null));
    out.add(new Language("gqn", "Guana (Brazil)", "I", "E", null, null, null, null));
    out.add(new Language("gqr", "Gor", "I", "L", null, null, null, null));
    out.add(new Language("gqu", "Qau", "I", "L", null, null, null, null));
    out.add(new Language("gra", "Rajput Garasia", "I", "L", null, null, "Garasia, Rajput", null));
    out.add(new Language("grb", "Grebo", "M", "L", null, null, null, null));
    out.add(new Language("grc", "Ancient Greek (to 1453)", "I", "H", null, null, "Greek, Ancient (to 1453)", null));
    out.add(new Language("grd", "Guruntum-Mbaaru", "I", "L", null, null, null, null));
    out.add(new Language("grg", "Madi", "I", "L", null, null, null, null));
    out.add(new Language("grh", "Gbiri-Niragu", "I", "L", null, null, null, null));
    out.add(new Language("gri", "Ghari", "I", "L", null, null, null, null));
    out.add(new Language("grj", "Southern Grebo", "I", "L", null, null, "Grebo, Southern", null));
    out.add(new Language("grm", "Kota Marudu Talantang", "I", "L", null, null, null, null));
    out.add(new Language("grn", "Guarani", "M", "L", "gn", null, null, null));
    out.add(new Language("gro", "Groma", "I", "L", null, null, null, null));
    out.add(new Language("grq", "Gorovu", "I", "L", null, null, null, null));
    out.add(new Language("grr", "Taznatit", "I", "L", null, null, null, null));
    out.add(new Language("grs", "Gresi", "I", "L", null, null, null, null));
    out.add(new Language("grt", "Garo", "I", "L", null, null, null, null));
    out.add(new Language("gru", "Kistane", "I", "L", null, null, null, null));
    out.add(new Language("grv", "Central Grebo", "I", "L", null, null, "Grebo, Central", null));
    out.add(new Language("grw", "Gweda", "I", "L", null, null, null, null));
    out.add(new Language("grx", "Guriaso", "I", "L", null, null, null, null));
    out.add(new Language("gry", "Barclayville Grebo", "I", "L", null, null, "Grebo, Barclayville", null));
    out.add(new Language("grz", "Guramalum", "I", "L", null, null, null, null));
    out.add(new Language("gse", "Ghanaian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gsg", "German Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gsl", "Gusilay", "I", "L", null, null, null, null));
    out.add(new Language("gsm", "Guatemalan Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gsn", "Nema", "I", "L", null, null, null, null));
    out.add(new Language("gso", "Southwest Gbaya", "I", "L", null, null, "Gbaya, Southwest", null));
    out.add(new Language("gsp", "Wasembo", "I", "L", null, null, null, null));
    out.add(new Language("gss", "Greek Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gsw", "Swiss German", "I", "L", null, null, "German, Swiss", null));
    out.add(new Language("gta", "Guató", "I", "L", null, null, null, null));
    out.add(new Language("gtu", "Aghu-Tharnggala", "I", "E", null, null, null, null));
    out.add(new Language("gua", "Shiki", "I", "L", null, null, null, null));
    out.add(new Language("gub", "Guajajára", "I", "L", null, null, null, null));
    out.add(new Language("guc", "Wayuu", "I", "L", null, null, null, null));
    out.add(new Language("gud", "Yocoboué Dida", "I", "L", null, null, "Dida, Yocoboué", null));
    out.add(new Language("gue", "Gurindji", "I", "L", null, null, null, null));
    out.add(new Language("guf", "Gupapuyngu", "I", "L", null, null, null, null));
    out.add(new Language("gug", "Paraguayan Guaraní", "I", "L", null, null, "Guaraní, Paraguayan", null));
    out.add(new Language("guh", "Guahibo", "I", "L", null, null, null, null));
    out.add(new Language("gui", "Eastern Bolivian Guaraní", "I", "L", null, null, "Guaraní, Eastern Bolivian", null));
    out.add(new Language("guj", "Gujarati", "I", "L", "gu", null, null, null));
    out.add(new Language("guk", "Gumuz", "I", "L", null, null, null, null));
    out.add(new Language("gul", "Sea Island Creole English", "I", "L", null, null, "Creole English, Sea Island", null));
    out.add(new Language("gum", "Guambiano", "I", "L", null, null, null, null));
    out.add(new Language("gun", "Mbyá Guaraní", "I", "L", null, null, "Guaraní, Mbyá", null));
    out.add(new Language("guo", "Guayabero", "I", "L", null, null, null, null));
    out.add(new Language("gup", "Gunwinggu", "I", "L", null, null, null, null));
    out.add(new Language("guq", "Aché", "I", "L", null, null, null, null));
    out.add(new Language("gur", "Farefare", "I", "L", null, null, null, null));
    out.add(new Language("gus", "Guinean Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("gut", "Maléku Jaíka", "I", "L", null, null, null, null));
    out.add(new Language("guu", "Yanomamö", "I", "L", null, null, null, null));
    out.add(new Language("guw", "Gun", "I", "L", null, null, null, null));
    out.add(new Language("gux", "Gourmanchéma", "I", "L", null, null, null, null));
    out.add(new Language("guz", "Gusii", "I", "L", null, null, null, null));
    out.add(new Language("gva", "Guana (Paraguay)", "I", "L", null, null, null, null));
    out.add(new Language("gvc", "Guanano", "I", "L", null, null, null, null));
    out.add(new Language("gve", "Duwet", "I", "L", null, null, null, null));
    out.add(new Language("gvf", "Golin", "I", "L", null, null, null, null));
    out.add(new Language("gvj", "Guajá", "I", "L", null, null, null, null));
    out.add(new Language("gvl", "Gulay", "I", "L", null, null, null, null));
    out.add(new Language("gvm", "Gurmana", "I", "L", null, null, null, null));
    out.add(new Language("gvn", "Kuku-Yalanji", "I", "L", null, null, null, null));
    out.add(new Language("gvo", "Gavião Do Jiparaná", "I", "L", null, null, null, null));
    out.add(new Language("gvp", "Pará Gavião", "I", "L", null, null, "Gavião, Pará", null));
    out.add(new Language("gvr", "Gurung", "I", "L", null, null, null, null));
    out.add(new Language("gvs", "Gumawana", "I", "L", null, null, null, null));
    out.add(new Language("gvy", "Guyani", "I", "E", null, null, null, null));
    out.add(new Language("gwa", "Mbato", "I", "L", null, null, null, null));
    out.add(new Language("gwb", "Gwa", "I", "L", null, null, null, null));
    out.add(new Language("gwc", "Gawri", "I", "L", null, null, null, null));
    out.add(new Language("gwd", "Gawwada", "I", "L", null, null, null, null));
    out.add(new Language("gwe", "Gweno", "I", "L", null, null, null, null));
    out.add(new Language("gwf", "Gowro", "I", "L", null, null, null, null));
    out.add(new Language("gwg", "Moo", "I", "L", null, null, null, null));
    out.add(new Language("gwi", "Gwichʼin", "I", "L", null, null, null, null));
    out.add(new Language("gwj", "ǀGwi", "I", "L", null, null, null, null));
    out.add(new Language("gwm", "Awngthim", "I", "E", null, null, null, null));
    out.add(new Language("gwn", "Gwandara", "I", "L", null, null, null, null));
    out.add(new Language("gwr", "Gwere", "I", "L", null, null, null, null));
    out.add(new Language("gwt", "Gawar-Bati", "I", "L", null, null, null, null));
    out.add(new Language("gwu", "Guwamu", "I", "E", null, null, null, null));
    out.add(new Language("gww", "Kwini", "I", "L", null, null, null, null));
    out.add(new Language("gwx", "Gua", "I", "L", null, null, null, null));
    out.add(new Language("gxx", "Wè Southern", "I", "L", null, null, null, null));
    out.add(new Language("gya", "Northwest Gbaya", "I", "L", null, null, "Gbaya, Northwest", null));
    out.add(new Language("gyb", "Garus", "I", "L", null, null, null, null));
    out.add(new Language("gyd", "Kayardild", "I", "L", null, null, null, null));
    out.add(new Language("gye", "Gyem", "I", "L", null, null, null, null));
    out.add(new Language("gyf", "Gungabula", "I", "E", null, null, null, null));
    out.add(new Language("gyg", "Gbayi", "I", "L", null, null, null, null));
    out.add(new Language("gyi", "Gyele", "I", "L", null, null, null, null));
    out.add(new Language("gyl", "Gayil", "I", "L", null, null, null, null));
    out.add(new Language("gym", "Ngäbere", "I", "L", null, null, null, null));
    out.add(new Language("gyn", "Guyanese Creole English", "I", "L", null, null, "Creole English, Guyanese", null));
    out.add(new Language("gyo", "Gyalsumdo", "I", "L", null, null, null, null));
    out.add(new Language("gyr", "Guarayu", "I", "L", null, null, null, null));
    out.add(new Language("gyy", "Gunya", "I", "E", null, null, null, null));
    out.add(new Language("gyz", "Geji", "I", "L", null, null, null, null));
    out.add(new Language("gza", "Ganza", "I", "L", null, null, null, null));
    out.add(new Language("gzi", "Gazi", "I", "L", null, null, null, null));
    out.add(new Language("gzn", "Gane", "I", "L", null, null, null, null));
    out.add(new Language("haa", "Hän", "I", "L", null, null, null, null));
    out.add(new Language("hab", "Hanoi Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hac", "Gurani", "I", "L", null, null, null, null));
    out.add(new Language("had", "Hatam", "I", "L", null, null, null, null));
    out.add(new Language("hae", "Eastern Oromo", "I", "L", null, null, "Oromo, Eastern", null));
    out.add(new Language("haf", "Haiphong Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hag", "Hanga", "I", "L", null, null, null, null));
    out.add(new Language("hah", "Hahon", "I", "L", null, null, null, null));
    out.add(new Language("hai", "Haida", "M", "L", null, null, null, null));
    out.add(new Language("haj", "Hajong", "I", "L", null, null, null, null));
    out.add(new Language("hak", "Hakka Chinese", "I", "L", null, null, "Chinese, Hakka", null));
    out.add(new Language("hal", "Halang", "I", "L", null, null, null, null));
    out.add(new Language("ham", "Hewa", "I", "L", null, null, null, null));
    out.add(new Language("han", "Hangaza", "I", "L", null, null, null, null));
    out.add(new Language("hao", "Hakö", "I", "L", null, null, null, null));
    out.add(new Language("hap", "Hupla", "I", "L", null, null, null, null));
    out.add(new Language("haq", "Ha", "I", "L", null, null, null, null));
    out.add(new Language("har", "Harari", "I", "L", null, null, null, null));
    out.add(new Language("has", "Haisla", "I", "L", null, null, null, null));
    out.add(new Language("hat", "Haitian", "I", "L", "ht", null, null, null));
    out.add(new Language("hau", "Hausa", "I", "L", "ha", null, null, null));
    out.add(new Language("hav", "Havu", "I", "L", null, null, null, null));
    out.add(new Language("haw", "Hawaiian", "I", "L", null, null, null, null));
    out.add(new Language("hax", "Southern Haida", "I", "L", null, null, "Haida, Southern", null));
    out.add(new Language("hay", "Haya", "I", "L", null, null, null, null));
    out.add(new Language("haz", "Hazaragi", "I", "L", null, null, null, null));
    out.add(new Language("hba", "Hamba", "I", "L", null, null, null, null));
    out.add(new Language("hbb", "Huba", "I", "L", null, null, null, null));
    out.add(new Language("hbn", "Heiban", "I", "L", null, null, null, null));
    out.add(new Language("hbo", "Ancient Hebrew", "I", "H", null, null, "Hebrew, Ancient", null));
    out.add(new Language("hbs", "Serbo-Croatian", "M", "L", "sh", null, null, null));
    out.add(new Language("hbu", "Habu", "I", "L", null, null, null, null));
    out.add(new Language("hca", "Andaman Creole Hindi", "I", "L", null, null, "Creole Hindi, Andaman", null));
    out.add(new Language("hch", "Huichol", "I", "L", null, null, null, null));
    out.add(new Language("hdn", "Northern Haida", "I", "L", null, null, "Haida, Northern", null));
    out.add(new Language("hds", "Honduras Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hdy", "Hadiyya", "I", "L", null, null, null, null));
    out.add(new Language("hea", "Northern Qiandong Miao", "I", "L", null, null, "Miao, Northern Qiandong", null));
    out.add(new Language("heb", "Hebrew", "I", "L", "he", null, null, null));
    out.add(new Language("hed", "Herdé", "I", "L", null, null, null, null));
    out.add(new Language("heg", "Helong", "I", "L", null, null, null, null));
    out.add(new Language("heh", "Hehe", "I", "L", null, null, null, null));
    out.add(new Language("hei", "Heiltsuk", "I", "L", null, null, null, null));
    out.add(new Language("hem", "Hemba", "I", "L", null, null, null, null));
    out.add(new Language("her", "Herero", "I", "L", "hz", null, null, null));
    out.add(new Language("hgm", "Haiǁom", "I", "L", null, null, null, null));
    out.add(new Language("hgw", "Haigwai", "I", "L", null, null, null, null));
    out.add(new Language("hhi", "Hoia Hoia", "I", "L", null, null, null, null));
    out.add(new Language("hhr", "Kerak", "I", "L", null, null, null, null));
    out.add(new Language("hhy", "Hoyahoya", "I", "L", null, null, null, null));
    out.add(new Language("hia", "Lamang", "I", "L", null, null, null, null));
    out.add(new Language("hib", "Hibito", "I", "E", null, null, null, null));
    out.add(new Language("hid", "Hidatsa", "I", "L", null, null, null, null));
    out.add(new Language("hif", "Fiji Hindi", "I", "L", null, null, "Hindi, Fiji", null));
    out.add(new Language("hig", "Kamwe", "I", "L", null, null, null, null));
    out.add(new Language("hih", "Pamosu", "I", "L", null, null, null, null));
    out.add(new Language("hii", "Hinduri", "I", "L", null, null, null, null));
    out.add(new Language("hij", "Hijuk", "I", "L", null, null, null, null));
    out.add(new Language("hik", "Seit-Kaitetu", "I", "L", null, null, null, null));
    out.add(new Language("hil", "Hiligaynon", "I", "L", null, null, null, null));
    out.add(new Language("hin", "Hindi", "I", "L", "hi", null, null, null));
    out.add(new Language("hio", "Tsoa", "I", "L", null, null, null, null));
    out.add(new Language("hir", "Himarimã", "I", "L", null, null, null, null));
    out.add(new Language("hit", "Hittite", "I", "H", null, null, null, null));
    out.add(new Language("hiw", "Hiw", "I", "L", null, null, null, null));
    out.add(new Language("hix", "Hixkaryána", "I", "L", null, null, null, null));
    out.add(new Language("hji", "Haji", "I", "L", null, null, null, null));
    out.add(new Language("hka", "Kahe", "I", "L", null, null, null, null));
    out.add(new Language("hke", "Hunde", "I", "L", null, null, null, null));
    out.add(new Language("hkh", "Khah", "I", "L", null, null, null, null));
    out.add(new Language("hkk", "Hunjara-Kaina Ke", "I", "L", null, null, null, null));
    out.add(new Language("hkn", "Mel-Khaonh", "I", "L", null, null, null, null));
    out.add(new Language("hks", "Hong Kong Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hla", "Halia", "I", "L", null, null, null, null));
    out.add(new Language("hlb", "Halbi", "I", "L", null, null, null, null));
    out.add(new Language("hld", "Halang Doan", "I", "L", null, null, null, null));
    out.add(new Language("hle", "Hlersu", "I", "L", null, null, null, null));
    out.add(new Language("hlt", "Matu Chin", "I", "L", null, null, "Chin, Matu", null));
    out.add(new Language("hlu", "Hieroglyphic Luwian", "I", "H", null, null, "Luwian, Hieroglyphic", null));
    out.add(new Language("hma", "Southern Mashan Hmong", "I", "L", null, null, "Hmong, Southern Mashan", null));
    out.add(new Language("hmb", "Humburi Senni Songhay", "I", "L", null, null, "Songhay, Humburi Senni", null));
    out.add(new Language("hmc", "Central Huishui Hmong", "I", "L", null, null, "Hmong, Central Huishui", null));
    out.add(new Language("hmd", "Large Flowery Miao", "I", "L", null, null, "Miao, Large Flowery", null));
    out.add(new Language("hme", "Eastern Huishui Hmong", "I", "L", null, null, "Hmong, Eastern Huishui", null));
    out.add(new Language("hmf", "Hmong Don", "I", "L", null, null, null, null));
    out.add(new Language("hmg", "Southwestern Guiyang Hmong", "I", "L", null, null, "Hmong, Southwestern Guiyang", null));
    out.add(new Language("hmh", "Southwestern Huishui Hmong", "I", "L", null, null, "Hmong, Southwestern Huishui", null));
    out.add(new Language("hmi", "Northern Huishui Hmong", "I", "L", null, null, "Hmong, Northern Huishui", null));
    out.add(new Language("hmj", "Ge", "I", "L", null, null, null, null));
    out.add(new Language("hmk", "Maek", "I", "H", null, null, null, null));
    out.add(new Language("hml", "Luopohe Hmong", "I", "L", null, null, "Hmong, Luopohe", null));
    out.add(new Language("hmm", "Central Mashan Hmong", "I", "L", null, null, "Hmong, Central Mashan", null));
    out.add(new Language("hmn", "Hmong", "M", "L", null, null, null, null));
    out.add(new Language("hmo", "Hiri Motu", "I", "L", "ho", null, null, null));
    out.add(new Language("hmp", "Northern Mashan Hmong", "I", "L", null, null, "Hmong, Northern Mashan", null));
    out.add(new Language("hmq", "Eastern Qiandong Miao", "I", "L", null, null, "Miao, Eastern Qiandong", null));
    out.add(new Language("hmr", "Hmar", "I", "L", null, null, null, null));
    out.add(new Language("hms", "Southern Qiandong Miao", "I", "L", null, null, "Miao, Southern Qiandong", null));
    out.add(new Language("hmt", "Hamtai", "I", "L", null, null, null, null));
    out.add(new Language("hmu", "Hamap", "I", "L", null, null, null, null));
    out.add(new Language("hmv", "Hmong Dô", "I", "L", null, null, null, null));
    out.add(new Language("hmw", "Western Mashan Hmong", "I", "L", null, null, "Hmong, Western Mashan", null));
    out.add(new Language("hmy", "Southern Guiyang Hmong", "I", "L", null, null, "Hmong, Southern Guiyang", null));
    out.add(new Language("hmz", "Hmong Shua", "I", "L", null, null, null, null));
    out.add(new Language("hna", "Mina (Cameroon)", "I", "L", null, null, null, null));
    out.add(new Language("hnd", "Southern Hindko", "I", "L", null, null, "Hindko, Southern", null));
    out.add(new Language("hne", "Chhattisgarhi", "I", "L", null, null, null, null));
    out.add(new Language("hng", "Hungu", "I", "L", null, null, null, null));
    out.add(new Language("hnh", "ǁAni", "I", "L", null, null, null, null));
    out.add(new Language("hni", "Hani", "I", "L", null, null, null, null));
    out.add(new Language("hnj", "Hmong Njua", "I", "L", null, null, null, null));
    out.add(new Language("hnm", "Hainanese", "I", "L", null, null, null, null));
    out.add(new Language("hnn", "Hanunoo", "I", "L", null, null, null, null));
    out.add(new Language("hno", "Northern Hindko", "I", "L", null, null, "Hindko, Northern", null));
    out.add(new Language("hns", "Caribbean Hindustani", "I", "L", null, null, "Hindustani, Caribbean", null));
    out.add(new Language("hnu", "Hung", "I", "L", null, null, null, null));
    out.add(new Language("hoa", "Hoava", "I", "L", null, null, null, null));
    out.add(new Language("hob", "Mari (Madang Province)", "I", "L", null, null, null, null));
    out.add(new Language("hoc", "Ho", "I", "L", null, null, null, null));
    out.add(new Language("hod", "Holma", "I", "E", null, null, null, null));
    out.add(new Language("hoe", "Horom", "I", "L", null, null, null, null));
    out.add(new Language("hoh", "Hobyót", "I", "L", null, null, null, null));
    out.add(new Language("hoi", "Holikachuk", "I", "L", null, null, null, null));
    out.add(new Language("hoj", "Hadothi", "I", "L", null, null, null, null));
    out.add(new Language("hol", "Holu", "I", "L", null, null, null, null));
    out.add(new Language("hom", "Homa", "I", "E", null, null, null, null));
    out.add(new Language("hoo", "Holoholo", "I", "L", null, null, null, null));
    out.add(new Language("hop", "Hopi", "I", "L", null, null, null, null));
    out.add(new Language("hor", "Horo", "I", "E", null, null, null, null));
    out.add(new Language("hos", "Ho Chi Minh City Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hot", "Hote", "I", "L", null, null, null, null));
    out.add(new Language("hov", "Hovongan", "I", "L", null, null, null, null));
    out.add(new Language("how", "Honi", "I", "L", null, null, null, null));
    out.add(new Language("hoy", "Holiya", "I", "L", null, null, null, null));
    out.add(new Language("hoz", "Hozo", "I", "L", null, null, null, null));
    out.add(new Language("hpo", "Hpon", "I", "E", null, null, null, null));
    out.add(new Language("hps", "Hawai'i Sign Language (HSL)", "I", "L", null, null, null, null));
    out.add(new Language("hra", "Hrangkhol", "I", "L", null, null, null, null));
    out.add(new Language("hrc", "Niwer Mil", "I", "L", null, null, null, null));
    out.add(new Language("hre", "Hre", "I", "L", null, null, null, null));
    out.add(new Language("hrk", "Haruku", "I", "L", null, null, null, null));
    out.add(new Language("hrm", "Horned Miao", "I", "L", null, null, "Miao, Horned", null));
    out.add(new Language("hro", "Haroi", "I", "L", null, null, null, null));
    out.add(new Language("hrp", "Nhirrpi", "I", "E", null, null, null, null));
    out.add(new Language("hrt", "Hértevin", "I", "L", null, null, null, null));
    out.add(new Language("hru", "Hruso", "I", "L", null, null, null, null));
    out.add(new Language("hrv", "Croatian", "I", "L", "hr", null, null, null));
    out.add(new Language("hrw", "Warwar Feni", "I", "L", null, null, null, null));
    out.add(new Language("hrx", "Hunsrik", "I", "L", null, null, null, null));
    out.add(new Language("hrz", "Harzani", "I", "L", null, null, null, null));
    out.add(new Language("hsb", "Upper Sorbian", "I", "L", null, null, "Sorbian, Upper", null));
    out.add(new Language("hsh", "Hungarian Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hsl", "Hausa Sign Language", "I", "L", null, null, null, null));
    out.add(new Language("hsn", "Xiang Chinese", "I", "L", null, null, "Chinese, Xiang", null));
    out.add(new Language("hss", "Harsusi", "I", "L", null, null, null, null));
    out.add(new Language("hti", "Hoti", "I", "E", null, null, null, null));
    out.add(new Language("hto", "Minica Huitoto", "I", "L", null, null, "Huitoto, Minica", null));
    out.add(new Language("hts", "Hadza", "I", "L", null, null, null, null));
    out.add(new Language("htu", "Hitu", "I", "L", null, null, null, null));
    out.add(new Language("htx", "Middle Hittite", "I", "H", null, null, "Hittite, Middle", null));
    out.add(new Language("hub", "Huambisa", "I", "L", null, null, null, null));
    out.add(new Language("huc", "ǂHua", "I", "L", null, null, null, null));
    out.add(new Language("hud", "Huaulu", "I", "L", null, null, null, null));
    out.add(new Language("hue", "San Francisco Del Mar Huave", "I", "L", null, null, "Huave, San Francisco Del Mar", null));
    out.add(new Language("huf", "Humene", "I", "L", null, null, null, null));
    out.add(new Language("hug", "Huachipaeri", "I", "L", null, null, null, null));
    out.add(new Language("huh", "Huilliche", "I", "L", null, null, null, null));
    out.add(new Language("hui", "Huli", "I", "L", null, null, null, null));
    out.add(new Language("huj", "Northern Guiyang Hmong", "I", "L", null, null, "Hmong, Northern Guiyang", null));
    out.add(new Language("huk", "Hulung", "I", "E", null, null, null, null));
    out.add(new Language("hul", "Hula", "I", "L", null, null, null, null));
    out.add(new Language("hum", "Hungana", "I", "L", null, null, null, null));
    out.add(new Language("hun", "Hungarian", "I", "L", "hu", null, null, null));
    out.add(new Language("huo", "Hu", "I", "L", null, null, null, null));
  }
}
