// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 500 to 999 of {@link Subdivision}.
 */
final class SubdivisionData1 {
  private SubdivisionData1() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("BS-NP", "New Providence", null, "Island"));
    out.add(new Subdivision("BS-NS", "North Andros", null, "District"));
    out.add(new Subdivision("BS-RC", "Rum Cay", null, "District"));
    out.add(new Subdivision("BS-RI", "Ragged Island", null, "District"));
    out.add(new Subdivision("BS-SA", "South Andros", null, "District"));
    out.add(new Subdivision("BS-SE", "South Eleuthera", null, "District"));
    out.add(new Subdivision("BS-SO", "South Abaco", null, "District"));
    out.add(new Subdivision("BS-SS", "San Salvador", null, "District"));
    out.add(new Subdivision("BS-SW", "Spanish Wells", null, "District"));
    out.add(new Subdivision("BS-WG", "West Grand Bahama", null, "District"));
    out.add(new Subdivision("BT-11", "Paro", null, "District"));
    out.add(new Subdivision("BT-12", "Chhukha", null, "District"));
    out.add(new Subdivision("BT-13", "Haa", null, "District"));
    out.add(new Subdivision("BT-14", "Samtse", null, "District"));
    out.add(new Subdivision("BT-15", "Thimphu", null, "District"));
    out.add(new Subdivision("BT-21", "Tsirang", null, "District"));
    out.add(new Subdivision("BT-22", "Dagana", null, "District"));
    out.add(new Subdivision("BT-23", "Punakha", null, "District"));
    out.add(new Subdivision("BT-24", "Wangdue Phodrang", null, "District"));
    out.add(new Subdivision("BT-31", "Sarpang", null, "District"));
    out.add(new Subdivision("BT-32", "Trongsa", null, "District"));
    out.add(new Subdivision("BT-33", "Bumthang", null, "District"));
    out.add(new Subdivision("BT-34", "Zhemgang", null, "District"));
    out.add(new Subdivision("BT-41", "Trashigang", null, "District"));
    out.add(new Subdivision("BT-42", "Monggar", null, "District"));
    out.add(new Subdivision("BT-43", "Pema Gatshel", null, "District"));
    out.add(new Subdivision("BT-44", "Lhuentse", null, "District"));
    out.add(new Subdivision("BT-45", "Samdrup Jongkhar", null, "District"));
    out.add(new Subdivision("BT-GA", "Gasa", null, "District"));
    out.add(new Subdivision("BT-TY", "Trashi Yangtse", null, "District"));
    out.add(new Subdivision("BW-CE", "Central", null, "District"));
    out.add(new Subdivision("BW-CH", "Chobe", null, "District"));
    out.add(new Subdivision("BW-FR", "Francistown", null, "City"));
    out.add(new Subdivision("BW-GA", "Gaborone", null, "City"));
    out.add(new Subdivision("BW-GH", "Ghanzi", null, "District"));
    out.add(new Subdivision("BW-JW", "Jwaneng", null, "Town"));
    out.add(new Subdivision("BW-KG", "Kgalagadi", null, "District"));
    out.add(new Subdivision("BW-KL", "Kgatleng", null, "District"));
    out.add(new Subdivision("BW-KW", "Kweneng", null, "District"));
    out.add(new Subdivision("BW-LO", "Lobatse", null, "Town"));
    out.add(new Subdivision("BW-NE", "North East", null, "District"));
    out.add(new Subdivision("BW-NW", "North West", null, "District"));
    out.add(new Subdivision("BW-SE", "South East", null, "District"));
    out.add(new Subdivision("BW-SO", "Southern", null, "District"));
    out.add(new Subdivision("BW-SP", "Selibe Phikwe", null, "Town"));
    out.add(new Subdivision("BW-ST", "Sowa Town", null, "Town"));
    out.add(new Subdivision("BY-BR", "Bresckaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BY-HM", "Horad Minsk", null, "City"));
    out.add(new Subdivision("BY-HO", "Homieĺskaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BY-HR", "Hrodzienskaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BY-MA", "Mahilioŭskaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BY-MI", "Minskaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BY-VI", "Viciebskaja voblasć", null, "Oblast"));
    out.add(new Subdivision("BZ-BZ", "Belize", null, "District"));
    out.add(new Subdivision("BZ-CY", "Cayo", null, "District"));
    out.add(new Subdivision("BZ-CZL", "Corozal", null, "District"));
    out.add(new Subdivision("BZ-OW", "Orange Walk", null, "District"));
    out.add(new Subdivision("BZ-SC", "Stann Creek", null, "District"));
    out.add(new Subdivision("BZ-TOL", "Toledo", null, "District"));
    out.add(new Subdivision("CA-AB", "Alberta", null, "Province"));
    out.add(new Subdivision("CA-BC", "British Columbia", null, "Province"));
    out.add(new Subdivision("CA-MB", "Manitoba", null, "Province"));
    out.add(new Subdivision("CA-NB", "New Brunswick", null, "Province"));
    out.add(new Subdivision("CA-NL", "Newfoundland and Labrador", null, "Province"));
    out.add(new Subdivision("CA-NS", "Nova Scotia", null, "Province"));
    out.add(new Subdivision("CA-NT", "Northwest Territories", null, "Territory"));
    out.add(new Subdivision("CA-NU", "Nunavut", null, "Territory"));
    out.add(new Subdivision("CA-ON", "Ontario", null, "Province"));
    out.add(new Subdivision("CA-PE", "Prince Edward Island", null, "Province"));
    out.add(new Subdivision("CA-QC", "Quebec", null, "Province"));
    out.add(new Subdivision("CA-SK", "Saskatchewan", null, "Province"));
    out.add(new Subdivision("CA-YT", "Yukon", null, "Territory"));
    out.add(new Subdivision("CD-BC", "Kongo Central", null, "Province"));
    out.add(new Subdivision("CD-BU", "Bas-Uélé", null, "Province"));
    out.add(new Subdivision("CD-EQ", "Équateur", null, "Province"));
    out.add(new Subdivision("CD-HK", "Haut-Katanga", null, "Province"));
    out.add(new Subdivision("CD-HL", "Haut-Lomami", null, "Province"));
    out.add(new Subdivision("CD-HU", "Haut-Uélé", null, "Province"));
    out.add(new Subdivision("CD-IT", "Ituri", null, "Province"));
    out.add(new Subdivision("CD-KC", "Kasaï Central", null, "Province"));
    out.add(new Subdivision("CD-KE", "Kasaï Oriental", null, "Province"));
    out.add(new Subdivision("CD-KG", "Kwango", null, "Province"));
    out.add(new Subdivision("CD-KL", "Kwilu", null, "Province"));
    out.add(new Subdivision("CD-KN", "Kinshasa", null, "City"));
    out.add(new Subdivision("CD-KS", "Kasaï", null, "Province"));
    out.add(new Subdivision("CD-LO", "Lomami", null, "Province"));
    out.add(new Subdivision("CD-LU", "Lualaba", null, "Province"));
    out.add(new Subdivision("CD-MA", "Maniema", null, "Province"));
    out.add(new Subdivision("CD-MN", "Mai-Ndombe", null, "Province"));
    out.add(new Subdivision("CD-MO", "Mongala", null, "Province"));
    out.add(new Subdivision("CD-NK", "Nord-Kivu", null, "Province"));
    out.add(new Subdivision("CD-NU", "Nord-Ubangi", null, "Province"));
    out.add(new Subdivision("CD-SA", "Sankuru", null, "Province"));
    out.add(new Subdivision("CD-SK", "Sud-Kivu", null, "Province"));
    out.add(new Subdivision("CD-SU", "Sud-Ubangi", null, "Province"));
    out.add(new Subdivision("CD-TA", "Tanganyika", null, "Province"));
    out.add(new Subdivision("CD-TO", "Tshopo", null, "Province"));
    out.add(new Subdivision("CD-TU", "Tshuapa", null, "Province"));
    out.add(new Subdivision("CF-AC", "Ouham", null, "Prefecture"));
    out.add(new Subdivision("CF-BB", "Bamingui-Bangoran", null, "Prefecture"));
    out.add(new Subdivision("CF-BGF", "Bangui", null, "Commune"));
    out.add(new Subdivision("CF-BK", "Basse-Kotto", null, "Prefecture"));
    out.add(new Subdivision("CF-HK", "Haute-Kotto", null, "Prefecture"));
    out.add(new Subdivision("CF-HM", "Haut-Mbomou", null, "Prefecture"));
    out.add(new Subdivision("CF-HS", "Haute-Sangha / Mambéré-Kadéï", null, "Prefecture"));
    out.add(new Subdivision("CF-KB", "Gribingui", null, "Economic prefecture"));
    out.add(new Subdivision("CF-KG", "Kémo-Gribingui", null, "Prefecture"));
    out.add(new Subdivision("CF-LB", "Lobaye", null, "Prefecture"));
    out.add(new Subdivision("CF-MB", "Mbomou", null, "Prefecture"));
    out.add(new Subdivision("CF-MP", "Ombella-Mpoko", null, "Prefecture"));
    out.add(new Subdivision("CF-NM", "Nana-Mambéré", null, "Prefecture"));
    out.add(new Subdivision("CF-OP", "Ouham-Pendé", null, "Prefecture"));
    out.add(new Subdivision("CF-SE", "Sangha", null, "Economic prefecture"));
    out.add(new Subdivision("CF-UK", "Ouaka", null, "Prefecture"));
    out.add(new Subdivision("CF-VK", "Vakaga", null, "Prefecture"));
    out.add(new Subdivision("CG-11", "Bouenza", null, "Department"));
    out.add(new Subdivision("CG-12", "Pool", null, "Department"));
    out.add(new Subdivision("CG-13", "Sangha", null, "Department"));
    out.add(new Subdivision("CG-14", "Plateaux", null, "Department"));
    out.add(new Subdivision("CG-15", "Cuvette-Ouest", null, "Department"));
    out.add(new Subdivision("CG-16", "Pointe-Noire", null, "Department"));
    out.add(new Subdivision("CG-2", "Lékoumou", null, "Department"));
    out.add(new Subdivision("CG-5", "Kouilou", null, "Department"));
    out.add(new Subdivision("CG-7", "Likouala", null, "Department"));
    out.add(new Subdivision("CG-8", "Cuvette", null, "Department"));
    out.add(new Subdivision("CG-9", "Niari", null, "Department"));
    out.add(new Subdivision("CG-BZV", "Brazzaville", null, "Department"));
    out.add(new Subdivision("CH-AG", "Aargau", null, "Canton"));
    out.add(new Subdivision("CH-AI", "Appenzell Innerrhoden", null, "Canton"));
    out.add(new Subdivision("CH-AR", "Appenzell Ausserrhoden", null, "Canton"));
    out.add(new Subdivision("CH-BE", "Berne", null, "Canton"));
    out.add(new Subdivision("CH-BL", "Basel-Landschaft", null, "Canton"));
    out.add(new Subdivision("CH-BS", "Basel-Stadt", null, "Canton"));
    out.add(new Subdivision("CH-FR", "Fribourg", null, "Canton"));
    out.add(new Subdivision("CH-GE", "Genève", null, "Canton"));
    out.add(new Subdivision("CH-GL", "Glarus", null, "Canton"));
    out.add(new Subdivision("CH-GR", "Graubünden", null, "Canton"));
    out.add(new Subdivision("CH-JU", "Jura", null, "Canton"));
    out.add(new Subdivision("CH-LU", "Luzern", null, "Canton"));
    out.add(new Subdivision("CH-NE", "Neuchâtel", null, "Canton"));
    out.add(new Subdivision("CH-NW", "Nidwalden", null, "Canton"));
    out.add(new Subdivision("CH-OW", "Obwalden", null, "Canton"));
    out.add(new Subdivision("CH-SG", "Sankt Gallen", null, "Canton"));
    out.add(new Subdivision("CH-SH", "Schaffhausen", null, "Canton"));
    out.add(new Subdivision("CH-SO", "Solothurn", null, "Canton"));
    out.add(new Subdivision("CH-SZ", "Schwyz", null, "Canton"));
    out.add(new Subdivision("CH-TG", "Thurgau", null, "Canton"));
    out.add(new Subdivision("CH-TI", "Ticino", null, "Canton"));
    out.add(new Subdivision("CH-UR", "Uri", null, "Canton"));
    out.add(new Subdivision("CH-VD", "Vaud", null, "Canton"));
    out.add(new Subdivision("CH-VS", "Valais", null, "Canton"));
    out.add(new Subdivision("CH-ZG", "Zug", null, "Canton"));
    out.add(new Subdivision("CH-ZH", "Zürich", null, "Canton"));
    out.add(new Subdivision("CI-AB", "Abidjan", null, "Autonomous district"));
    out.add(new Subdivision("CI-BS", "Bas-Sassandra", null, "District"));
    out.add(new Subdivision("CI-CM", "Comoé", null, "District"));
    out.add(new Subdivision("CI-DN", "Denguélé", null, "District"));
    out.add(new Subdivision("CI-GD", "Gôh-Djiboua", null, "District"));
    out.add(new Subdivision("CI-LC", "Lacs", null, "District"));
    out.add(new Subdivision("CI-LG", "Lagunes", null, "District"));
    out.add(new Subdivision("CI-MG", "Montagnes", null, "District"));
    out.add(new Subdivision("CI-SM", "Sassandra-Marahoué", null, "District"));
    out.add(new Subdivision("CI-SV", "Savanes", null, "District"));
    out.add(new Subdivision("CI-VB", "Vallée du Bandama", null, "District"));
    out.add(new Subdivision("CI-WR", "Woroba", null, "District"));
    out.add(new Subdivision("CI-YM", "Yamoussoukro", null, "Autonomous district"));
    out.add(new Subdivision("CI-ZZ", "Zanzan", null, "District"));
    out.add(new Subdivision("CL-AI", "Aisén del General Carlos Ibañez del Campo", null, "Region"));
    out.add(new Subdivision("CL-AN", "Antofagasta", null, "Region"));
    out.add(new Subdivision("CL-AP", "Arica y Parinacota", null, "Region"));
    out.add(new Subdivision("CL-AR", "La Araucanía", null, "Region"));
    out.add(new Subdivision("CL-AT", "Atacama", null, "Region"));
    out.add(new Subdivision("CL-BI", "Biobío", null, "Region"));
    out.add(new Subdivision("CL-CO", "Coquimbo", null, "Region"));
    out.add(new Subdivision("CL-LI", "Libertador General Bernardo O'Higgins", null, "Region"));
    out.add(new Subdivision("CL-LL", "Los Lagos", null, "Region"));
    out.add(new Subdivision("CL-LR", "Los Ríos", null, "Region"));
    out.add(new Subdivision("CL-MA", "Magallanes", null, "Region"));
    out.add(new Subdivision("CL-ML", "Maule", null, "Region"));
    out.add(new Subdivision("CL-NB", "Ñuble", null, "Region"));
    out.add(new Subdivision("CL-RM", "Región Metropolitana de Santiago", null, "Region"));
    out.add(new Subdivision("CL-TA", "Tarapacá", null, "Region"));
    out.add(new Subdivision("CL-VS", "Valparaíso", null, "Region"));
    out.add(new Subdivision("CM-AD", "Adamaoua", null, "Region"));
    out.add(new Subdivision("CM-CE", "Centre", null, "Region"));
    out.add(new Subdivision("CM-EN", "Far North", null, "Region"));
    out.add(new Subdivision("CM-ES", "East", null, "Region"));
    out.add(new Subdivision("CM-LT", "Littoral", null, "Region"));
    out.add(new Subdivision("CM-NO", "North", null, "Region"));
    out.add(new Subdivision("CM-NW", "North-West", null, "Region"));
    out.add(new Subdivision("CM-OU", "West", null, "Region"));
    out.add(new Subdivision("CM-SU", "South", null, "Region"));
    out.add(new Subdivision("CM-SW", "South-West", null, "Region"));
    out.add(new Subdivision("CN-AH", "Anhui Sheng", null, "Province"));
    out.add(new Subdivision("CN-BJ", "Beijing Shi", null, "Municipality"));
    out.add(new Subdivision("CN-CQ", "Chongqing Shi", null, "Municipality"));
    out.add(new Subdivision("CN-FJ", "Fujian Sheng", null, "Province"));
    out.add(new Subdivision("CN-GD", "Guangdong Sheng", null, "Province"));
    out.add(new Subdivision("CN-GS", "Gansu Sheng", null, "Province"));
    out.add(new Subdivision("CN-GX", "Guangxi Zhuangzu Zizhiqu", null, "Autonomous region"));
    out.add(new Subdivision("CN-GZ", "Guizhou Sheng", null, "Province"));
    out.add(new Subdivision("CN-HA", "Henan Sheng", null, "Province"));
    out.add(new Subdivision("CN-HB", "Hubei Sheng", null, "Province"));
    out.add(new Subdivision("CN-HE", "Hebei Sheng", null, "Province"));
    out.add(new Subdivision("CN-HI", "Hainan Sheng", null, "Province"));
    out.add(new Subdivision("CN-HK", "Hong Kong SAR", null, "Special administrative region"));
    out.add(new Subdivision("CN-HL", "Heilongjiang Sheng", null, "Province"));
    out.add(new Subdivision("CN-HN", "Hunan Sheng", null, "Province"));
    out.add(new Subdivision("CN-JL", "Jilin Sheng", null, "Province"));
    out.add(new Subdivision("CN-JS", "Jiangsu Sheng", null, "Province"));
    out.add(new Subdivision("CN-JX", "Jiangxi Sheng", null, "Province"));
    out.add(new Subdivision("CN-LN", "Liaoning Sheng", null, "Province"));
    out.add(new Subdivision("CN-MO", "Macao SAR", null, "Special administrative region"));
    out.add(new Subdivision("CN-NM", "Nei Mongol Zizhiqu", null, "Autonomous region"));
    out.add(new Subdivision("CN-NX", "Ningxia Huizu Zizhiqu", null, "Autonomous region"));
    out.add(new Subdivision("CN-QH", "Qinghai Sheng", null, "Province"));
    out.add(new Subdivision("CN-SC", "Sichuan Sheng", null, "Province"));
    out.add(new Subdivision("CN-SD", "Shandong Sheng", null, "Province"));
    out.add(new Subdivision("CN-SH", "Shanghai Shi", null, "Municipality"));
    out.add(new Subdivision("CN-SN", "Shaanxi Sheng", null, "Province"));
    out.add(new Subdivision("CN-SX", "Shanxi Sheng", null, "Province"));
    out.add(new Subdivision("CN-TJ", "Tianjin Shi", null, "Municipality"));
    out.add(new Subdivision("CN-TW", "Taiwan Sheng", null, "Province"));
    out.add(new Subdivision("CN-XJ", "Xinjiang Uygur Zizhiqu", null, "Autonomous region"));
    out.add(new Subdivision("CN-XZ", "Xizang Zizhiqu", null, "Autonomous region"));
    out.add(new Subdivision("CN-YN", "Yunnan Sheng", null, "Province"));
    out.add(new Subdivision("CN-ZJ", "Zhejiang Sheng", null, "Province"));
    out.add(new Subdivision("CO-AMA", "Amazonas", null, "Department"));
    out.add(new Subdivision("CO-ANT", "Antioquia", null, "Department"));
    out.add(new Subdivision("CO-ARA", "Arauca", null, "Department"));
    out.add(new Subdivision("CO-ATL", "Atlántico", null, "Department"));
    out.add(new Subdivision("CO-BOL", "Bolívar", null, "Department"));
    out.add(new Subdivision("CO-BOY", "Boyacá", null, "Department"));
    out.add(new Subdivision("CO-CAL", "Caldas", null, "Department"));
    out.add(new Subdivision("CO-CAQ", "Caquetá", null, "Department"));
    out.add(new Subdivision("CO-CAS", "Casanare", null, "Department"));
    out.add(new Subdivision("CO-CAU", "Cauca", null, "Department"));
    out.add(new Subdivision("CO-CES", "Cesar", null, "Department"));
    out.add(new Subdivision("CO-CHO", "Chocó", null, "Department"));
    out.add(new Subdivision("CO-COR", "Córdoba", null, "Department"));
    out.add(new Subdivision("CO-CUN", "Cundinamarca", null, "Department"));
    out.add(new Subdivision("CO-DC", "Distrito Capital de Bogotá", null, "Capital district"));
    out.add(new Subdivision("CO-GUA", "Guainía", null, "Department"));
    out.add(new Subdivision("CO-GUV", "Guaviare", null, "Department"));
    out.add(new Subdivision("CO-HUI", "Huila", null, "Department"));
    out.add(new Subdivision("CO-LAG", "La Guajira", null, "Department"));
    out.add(new Subdivision("CO-MAG", "Magdalena", null, "Department"));
    out.add(new Subdivision("CO-MET", "Meta", null, "Department"));
    out.add(new Subdivision("CO-NAR", "Nariño", null, "Department"));
    out.add(new Subdivision("CO-NSA", "Norte de Santander", null, "Department"));
    out.add(new Subdivision("CO-PUT", "Putumayo", null, "Department"));
    out.add(new Subdivision("CO-QUI", "Quindío", null, "Department"));
    out.add(new Subdivision("CO-RIS", "Risaralda", null, "Department"));
    out.add(new Subdivision("CO-SAN", "Santander", null, "Department"));
    out.add(new Subdivision("CO-SAP", "San Andrés, Providencia y Santa Catalina", null, "Department"));
    out.add(new Subdivision("CO-SUC", "Sucre", null, "Department"));
    out.add(new Subdivision("CO-TOL", "Tolima", null, "Department"));
    out.add(new Subdivision("CO-VAC", "Valle del Cauca", null, "Department"));
    out.add(new Subdivision("CO-VAU", "Vaupés", null, "Department"));
    out.add(new Subdivision("CO-VID", "Vichada", null, "Department"));
    out.add(new Subdivision("CR-A", "Alajuela", null, "Province"));
    out.add(new Subdivision("CR-C", "Cartago", null, "Province"));
    out.add(new Subdivision("CR-G", "Guanacaste", null, "Province"));
    out.add(new Subdivision("CR-H", "Heredia", null, "Province"));
    out.add(new Subdivision("CR-L", "Limón", null, "Province"));
    out.add(new Subdivision("CR-P", "Puntarenas", null, "Province"));
    out.add(new Subdivision("CR-SJ", "San José", null, "Province"));
    out.add(new Subdivision("CU-01", "Pinar del Río", null, "Province"));
    out.add(new Subdivision("CU-03", "La Habana", null, "Province"));
    out.add(new Subdivision("CU-04", "Matanzas", null, "Province"));
    out.add(new Subdivision("CU-05", "Villa Clara", null, "Province"));
    out.add(new Subdivision("CU-06", "Cienfuegos", null, "Province"));
    out.add(new Subdivision("CU-07", "Sancti Spíritus", null, "Province"));
    out.add(new Subdivision("CU-08", "Ciego de Ávila", null, "Province"));
    out.add(new Subdivision("CU-09", "Camagüey", null, "Province"));
    out.add(new Subdivision("CU-10", "Las Tunas", null, "Province"));
    out.add(new Subdivision("CU-11", "Holguín", null, "Province"));
    out.add(new Subdivision("CU-12", "Granma", null, "Province"));
    out.add(new Subdivision("CU-13", "Santiago de Cuba", null, "Province"));
    out.add(new Subdivision("CU-14", "Guantánamo", null, "Province"));
    out.add(new Subdivision("CU-15", "Artemisa", null, "Province"));
    out.add(new Subdivision("CU-16", "Mayabeque", null, "Province"));
    out.add(new Subdivision("CU-99", "Isla de la Juventud", null, "Special municipality"));
    out.add(new Subdivision("CV-B", "Ilhas de Barlavento", null, "Geographical region"));
    out.add(new Subdivision("CV-BR", "Brava", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-BV", "Boa Vista", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-CA", "Santa Catarina", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-CF", "Santa Catarina do Fogo", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-CR", "Santa Cruz", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-MA", "Maio", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-MO", "Mosteiros", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-PA", "Paul", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-PN", "Porto Novo", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-PR", "Praia", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-RB", "Ribeira Brava", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-RG", "Ribeira Grande", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-RS", "Ribeira Grande de Santiago", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-S", "Ilhas de Sotavento", null, "Geographical region"));
    out.add(new Subdivision("CV-SD", "São Domingos", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-SF", "São Filipe", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-SL", "Sal", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-SM", "São Miguel", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-SO", "São Lourenço dos Órgãos", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-SS", "São Salvador do Mundo", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-SV", "São Vicente", "CV-B", "Municipality"));
    out.add(new Subdivision("CV-TA", "Tarrafal", "CV-S", "Municipality"));
    out.add(new Subdivision("CV-TS", "Tarrafal de São Nicolau", "CV-B", "Municipality"));
    out.add(new Subdivision("CY-01", "Lefkosia", null, "District"));
    out.add(new Subdivision("CY-02", "Lemesos", null, "District"));
    out.add(new Subdivision("CY-03", "Larnaka", null, "District"));
    out.add(new Subdivision("CY-04", "Ammochostos", null, "District"));
    out.add(new Subdivision("CY-05", "Pafos", null, "District"));
    out.add(new Subdivision("CY-06", "Keryneia", null, "District"));
    out.add(new Subdivision("CZ-10", "Praha, Hlavní město", null, "Capital city"));
    out.add(new Subdivision("CZ-20", "Středočeský kraj", null, "Region"));
    out.add(new Subdivision("CZ-201", "Benešov", "CZ-20", "District"));
    out.add(new Subdivision("CZ-202", "Beroun", "CZ-20", "District"));
    out.add(new Subdivision("CZ-203", "Kladno", "CZ-20", "District"));
    out.add(new Subdivision("CZ-204", "Kolín", "CZ-20", "District"));
    out.add(new Subdivision("CZ-205", "Kutná Hora", "CZ-20", "District"));
    out.add(new Subdivision("CZ-206", "Mělník", "CZ-20", "District"));
    out.add(new Subdivision("CZ-207", "Mladá Boleslav", "CZ-20", "District"));
    out.add(new Subdivision("CZ-208", "Nymburk", "CZ-20", "District"));
    out.add(new Subdivision("CZ-209", "Praha-východ", "CZ-20", "District"));
    out.add(new Subdivision("CZ-20A", "Praha-západ", "CZ-20", "District"));
    out.add(new Subdivision("CZ-20B", "Příbram", "CZ-20", "District"));
    out.add(new Subdivision("CZ-20C", "Rakovník", "CZ-20", "District"));
    out.add(new Subdivision("CZ-31", "Jihočeský kraj", null, "Region"));
    out.add(new Subdivision("CZ-311", "České Budějovice", "CZ-31", "District"));
    out.add(new Subdivision("CZ-312", "Český Krumlov", "CZ-31", "District"));
    out.add(new Subdivision("CZ-313", "Jindřichův Hradec", "CZ-31", "District"));
    out.add(new Subdivision("CZ-314", "Písek", "CZ-31", "District"));
    out.add(new Subdivision("CZ-315", "Prachatice", "CZ-31", "District"));
    out.add(new Subdivision("CZ-316", "Strakonice", "CZ-31", "District"));
    out.add(new Subdivision("CZ-317", "Tábor", "CZ-31", "District"));
    out.add(new Subdivision("CZ-32", "Plzeňský kraj", null, "Region"));
    out.add(new Subdivision("CZ-321", "Domažlice", "CZ-32", "District"));
    out.add(new Subdivision("CZ-322", "Klatovy", "CZ-32", "District"));
    out.add(new Subdivision("CZ-323", "Plzeň-město", "CZ-32", "District"));
    out.add(new Subdivision("CZ-324", "Plzeň-jih", "CZ-32", "District"));
    out.add(new Subdivision("CZ-325", "Plzeň-sever", "CZ-32", "District"));
    out.add(new Subdivision("CZ-326", "Rokycany", "CZ-32", "District"));
    out.add(new Subdivision("CZ-327", "Tachov", "CZ-32", "District"));
    out.add(new Subdivision("CZ-41", "Karlovarský kraj", null, "Region"));
    out.add(new Subdivision("CZ-411", "Cheb", "CZ-41", "District"));
    out.add(new Subdivision("CZ-412", "Karlovy Vary", "CZ-41", "District"));
    out.add(new Subdivision("CZ-413", "Sokolov", "CZ-41", "District"));
    out.add(new Subdivision("CZ-42", "Ústecký kraj", null, "Region"));
    out.add(new Subdivision("CZ-421", "Děčín", "CZ-42", "District"));
    out.add(new Subdivision("CZ-422", "Chomutov", "CZ-42", "District"));
    out.add(new Subdivision("CZ-423", "Litoměřice", "CZ-42", "District"));
    out.add(new Subdivision("CZ-424", "Louny", "CZ-42", "District"));
    out.add(new Subdivision("CZ-425", "Most", "CZ-42", "District"));
    out.add(new Subdivision("CZ-426", "Teplice", "CZ-42", "District"));
    out.add(new Subdivision("CZ-427", "Ústí nad Labem", "CZ-42", "District"));
    out.add(new Subdivision("CZ-51", "Liberecký kraj", null, "Region"));
    out.add(new Subdivision("CZ-511", "Česká Lípa", "CZ-51", "District"));
    out.add(new Subdivision("CZ-512", "Jablonec nad Nisou", "CZ-51", "District"));
    out.add(new Subdivision("CZ-513", "Liberec", "CZ-51", "District"));
    out.add(new Subdivision("CZ-514", "Semily", "CZ-51", "District"));
    out.add(new Subdivision("CZ-52", "Královéhradecký kraj", null, "Region"));
    out.add(new Subdivision("CZ-521", "Hradec Králové", "CZ-52", "District"));
    out.add(new Subdivision("CZ-522", "Jičín", "CZ-52", "District"));
    out.add(new Subdivision("CZ-523", "Náchod", "CZ-52", "District"));
    out.add(new Subdivision("CZ-524", "Rychnov nad Kněžnou", "CZ-52", "District"));
    out.add(new Subdivision("CZ-525", "Trutnov", "CZ-52", "District"));
    out.add(new Subdivision("CZ-53", "Pardubický kraj", null, "Region"));
    out.add(new Subdivision("CZ-531", "Chrudim", "CZ-53", "District"));
    out.add(new Subdivision("CZ-532", "Pardubice", "CZ-53", "District"));
    out.add(new Subdivision("CZ-533", "Svitavy", "CZ-53", "District"));
    out.add(new Subdivision("CZ-534", "Ústí nad Orlicí", "CZ-53", "District"));
    out.add(new Subdivision("CZ-63", "Kraj Vysočina", null, "Region"));
    out.add(new Subdivision("CZ-631", "Havlíčkův Brod", "CZ-63", "District"));
    out.add(new Subdivision("CZ-632", "Jihlava", "CZ-63", "District"));
    out.add(new Subdivision("CZ-633", "Pelhřimov", "CZ-63", "District"));
    out.add(new Subdivision("CZ-634", "Třebíč", "CZ-63", "District"));
    out.add(new Subdivision("CZ-635", "Žďár nad Sázavou", "CZ-63", "District"));
    out.add(new Subdivision("CZ-64", "Jihomoravský kraj", null, "Region"));
    out.add(new Subdivision("CZ-641", "Blansko", "CZ-64", "District"));
    out.add(new Subdivision("CZ-642", "Brno-město", "CZ-64", "District"));
    out.add(new Subdivision("CZ-643", "Brno-venkov", "CZ-64", "District"));
    out.add(new Subdivision("CZ-644", "Břeclav", "CZ-64", "District"));
    out.add(new Subdivision("CZ-645", "Hodonín", "CZ-64", "District"));
    out.add(new Subdivision("CZ-646", "Vyškov", "CZ-64", "District"));
    out.add(new Subdivision("CZ-647", "Znojmo", "CZ-64", "District"));
    out.add(new Subdivision("CZ-71", "Olomoucký kraj", null, "Region"));
    out.add(new Subdivision("CZ-711", "Jeseník", "CZ-71", "District"));
    out.add(new Subdivision("CZ-712", "Olomouc", "CZ-71", "District"));
    out.add(new Subdivision("CZ-713", "Prostějov", "CZ-71", "District"));
    out.add(new Subdivision("CZ-714", "Přerov", "CZ-71", "District"));
    out.add(new Subdivision("CZ-715", "Šumperk", "CZ-71", "District"));
    out.add(new Subdivision("CZ-72", "Zlínský kraj", null, "Region"));
    out.add(new Subdivision("CZ-721", "Kroměříž", "CZ-72", "District"));
    out.add(new Subdivision("CZ-722", "Uherské Hradiště", "CZ-72", "District"));
    out.add(new Subdivision("CZ-723", "Vsetín", "CZ-72", "District"));
    out.add(new Subdivision("CZ-724", "Zlín", "CZ-72", "District"));
    out.add(new Subdivision("CZ-80", "Moravskoslezský kraj", null, "Region"));
    out.add(new Subdivision("CZ-801", "Bruntál", "CZ-80", "District"));
    out.add(new Subdivision("CZ-802", "Frýdek-Místek", "CZ-80", "District"));
    out.add(new Subdivision("CZ-803", "Karviná", "CZ-80", "District"));
    out.add(new Subdivision("CZ-804", "Nový Jičín", "CZ-80", "District"));
    out.add(new Subdivision("CZ-805", "Opava", "CZ-80", "District"));
    out.add(new Subdivision("CZ-806", "Ostrava-město", "CZ-80", "District"));
    out.add(new Subdivision("DE-BB", "Brandenburg", null, "Land"));
    out.add(new Subdivision("DE-BE", "Berlin", null, "Land"));
    out.add(new Subdivision("DE-BW", "Baden-Württemberg", null, "Land"));
    out.add(new Subdivision("DE-BY", "Bayern", null, "Land"));
    out.add(new Subdivision("DE-HB", "Bremen", null, "Land"));
    out.add(new Subdivision("DE-HE", "Hessen", null, "Land"));
    out.add(new Subdivision("DE-HH", "Hamburg", null, "Land"));
    out.add(new Subdivision("DE-MV", "Mecklenburg-Vorpommern", null, "Land"));
    out.add(new Subdivision("DE-NI", "Niedersachsen", null, "Land"));
    out.add(new Subdivision("DE-NW", "Nordrhein-Westfalen", null, "Land"));
    out.add(new Subdivision("DE-RP", "Rheinland-Pfalz", null, "Land"));
    out.add(new Subdivision("DE-SH", "Schleswig-Holstein", null, "Land"));
    out.add(new Subdivision("DE-SL", "Saarland", null, "Land"));
    out.add(new Subdivision("DE-SN", "Sachsen", null, "Land"));
    out.add(new Subdivision("DE-ST", "Sachsen-Anhalt", null, "Land"));
    out.add(new Subdivision("DE-TH", "Thüringen", null, "Land"));
    out.add(new Subdivision("DJ-AR", "Arta", null, "Region"));
    out.add(new Subdivision("DJ-AS", "Ali Sabieh", null, "Region"));
    out.add(new Subdivision("DJ-DI", "Dikhil", null, "Region"));
    out.add(new Subdivision("DJ-DJ", "Djibouti", null, "City"));
    out.add(new Subdivision("DJ-OB", "Obock", null, "Region"));
    out.add(new Subdivision("DJ-TA", "Tadjourah", null, "Region"));
    out.add(new Subdivision("DK-81", "Nordjylland", null, "Region"));
    out.add(new Subdivision("DK-82", "Midtjylland", null, "Region"));
    out.add(new Subdivision("DK-83", "Syddanmark", null, "Region"));
    out.add(new Subdivision("DK-84", "Hovedstaden", null, "Region"));
    out.add(new Subdivision("DK-85", "Sjælland", null, "Region"));
    out.add(new Subdivision("DM-02", "Saint Andrew", null, "Parish"));
    out.add(new Subdivision("DM-03", "Saint David", null, "Parish"));
    out.add(new Subdivision("DM-04", "Saint George", null, "Parish"));
    out.add(new Subdivision("DM-05", "Saint John", null, "Parish"));
    out.add(new Subdivision("DM-06", "Saint Joseph", null, "Parish"));
    out.add(new Subdivision("DM-07", "Saint Luke", null, "Parish"));
    out.add(new Subdivision("DM-08", "Saint Mark", null, "Parish"));
    out.add(new Subdivision("DM-09", "Saint Patrick", null, "Parish"));
    out.add(new Subdivision("DM-10", "Saint Paul", null, "Parish"));
    out.add(new Subdivision("DM-11", "Saint Peter", null, "Parish"));
    out.add(new Subdivision("DO-01", "Distrito Nacional (Santo Domingo)", "DO-40", "District"));
    out.add(new Subdivision("DO-02", "Azua", "DO-41", "Province"));
    out.add(new Subdivision("DO-03", "Baoruco", "DO-38", "Province"));
    out.add(new Subdivision("DO-04", "Barahona", "DO-38", "Province"));
    out.add(new Subdivision("DO-05", "Dajabón", "DO-34", "Province"));
    out.add(new Subdivision("DO-06", "Duarte", "DO-33", "Province"));
    out.add(new Subdivision("DO-07", "Elías Piña", "DO-37", "Province"));
    out.add(new Subdivision("DO-08", "El Seibo", "DO-42", "Province"));
    out.add(new Subdivision("DO-09", "Espaillat", "DO-35", "Province"));
    out.add(new Subdivision("DO-10", "Independencia", "DO-38", "Province"));
    out.add(new Subdivision("DO-11", "La Altagracia", "DO-42", "Province"));
    out.add(new Subdivision("DO-12", "La Romana", "DO-42", "Province"));
    out.add(new Subdivision("DO-13", "La Vega", "DO-36", "Province"));
    out.add(new Subdivision("DO-14", "María Trinidad Sánchez", "DO-33", "Province"));
    out.add(new Subdivision("DO-15", "Monte Cristi", "DO-34", "Province"));
    out.add(new Subdivision("DO-16", "Pedernales", "DO-38", "Province"));
    out.add(new Subdivision("DO-17", "Peravia", "DO-41", "Province"));
    out.add(new Subdivision("DO-18", "Puerto Plata", "DO-35", "Province"));
    out.add(new Subdivision("DO-19", "Hermanas Mirabal", "DO-33", "Province"));
    out.add(new Subdivision("DO-20", "Samaná", "DO-33", "Province"));
    out.add(new Subdivision("DO-21", "San Cristóbal", "DO-41", "Province"));
    out.add(new Subdivision("DO-22", "San Juan", "DO-37", "Province"));
    out.add(new Subdivision("DO-23", "San Pedro de Macorís", "DO-39", "Province"));
    out.add(new Subdivision("DO-24", "Sánchez Ramírez", "DO-36", "Province"));
    out.add(new Subdivision("DO-25", "Santiago", "DO-35", "Province"));
    out.add(new Subdivision("DO-26", "Santiago Rodríguez", "DO-34", "Province"));
    out.add(new Subdivision("DO-27", "Valverde", "DO-34", "Province"));
    out.add(new Subdivision("DO-28", "Monseñor Nouel", "DO-36", "Province"));
    out.add(new Subdivision("DO-29", "Monte Plata", "DO-39", "Province"));
    out.add(new Subdivision("DO-30", "Hato Mayor", "DO-39", "Province"));
    out.add(new Subdivision("DO-31", "San José de Ocoa", "DO-41", "Province"));
    out.add(new Subdivision("DO-32", "Santo Domingo", "DO-40", "Province"));
    out.add(new Subdivision("DO-33", "Cibao Nordeste", null, "Region"));
    out.add(new Subdivision("DO-34", "Cibao Noroeste", null, "Region"));
    out.add(new Subdivision("DO-35", "Cibao Norte", null, "Region"));
    out.add(new Subdivision("DO-36", "Cibao Sur", null, "Region"));
    out.add(new Subdivision("DO-37", "El Valle", null, "Region"));
    out.add(new Subdivision("DO-38", "Enriquillo", null, "Region"));
    out.add(new Subdivision("DO-39", "Higuamo", null, "Region"));
    out.add(new Subdivision("DO-40", "Ozama", null, "Region"));
    out.add(new Subdivision("DO-41", "Valdesia", null, "Region"));
    out.add(new Subdivision("DO-42", "Yuma", null, "Region"));
    out.add(new Subdivision("DZ-01", "Adrar", null, "Province"));
    out.add(new Subdivision("DZ-02", "Chlef", null, "Province"));
    out.add(new Subdivision("DZ-03", "Laghouat", null, "Province"));
    out.add(new Subdivision("DZ-04", "Oum el Bouaghi", null, "Province"));
    out.add(new Subdivision("DZ-05", "Batna", null, "Province"));
    out.add(new Subdivision("DZ-06", "Béjaïa", null, "Province"));
    out.add(new Subdivision("DZ-07", "Biskra", null, "Province"));
    out.add(new Subdivision("DZ-08", "Béchar", null, "Province"));
    out.add(new Subdivision("DZ-09", "Blida", null, "Province"));
    out.add(new Subdivision("DZ-10", "Bouira", null, "Province"));
    out.add(new Subdivision("DZ-11", "Tamanrasset", null, "Province"));
    out.add(new Subdivision("DZ-12", "Tébessa", null, "Province"));
    out.add(new Subdivision("DZ-13", "Tlemcen", null, "Province"));
    out.add(new Subdivision("DZ-14", "Tiaret", null, "Province"));
    out.add(new Subdivision("DZ-15", "Tizi Ouzou", null, "Province"));
    out.add(new Subdivision("DZ-16", "Alger", null, "Province"));
    out.add(new Subdivision("DZ-17", "Djelfa", null, "Province"));
    out.add(new Subdivision("DZ-18", "Jijel", null, "Province"));
  }
}
