// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 1000 to 1499 of {@link Subdivision}.
 */
final class SubdivisionData2 {
  private SubdivisionData2() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("DZ-19", "Sétif", null, "Province"));
    out.add(new Subdivision("DZ-20", "Saïda", null, "Province"));
    out.add(new Subdivision("DZ-21", "Skikda", null, "Province"));
    out.add(new Subdivision("DZ-22", "Sidi Bel Abbès", null, "Province"));
    out.add(new Subdivision("DZ-23", "Annaba", null, "Province"));
    out.add(new Subdivision("DZ-24", "Guelma", null, "Province"));
    out.add(new Subdivision("DZ-25", "Constantine", null, "Province"));
    out.add(new Subdivision("DZ-26", "Médéa", null, "Province"));
    out.add(new Subdivision("DZ-27", "Mostaganem", null, "Province"));
    out.add(new Subdivision("DZ-28", "M'sila", null, "Province"));
    out.add(new Subdivision("DZ-29", "Mascara", null, "Province"));
    out.add(new Subdivision("DZ-30", "Ouargla", null, "Province"));
    out.add(new Subdivision("DZ-31", "Oran", null, "Province"));
    out.add(new Subdivision("DZ-32", "El Bayadh", null, "Province"));
    out.add(new Subdivision("DZ-33", "Illizi", null, "Province"));
    out.add(new Subdivision("DZ-34", "Bordj Bou Arréridj", null, "Province"));
    out.add(new Subdivision("DZ-35", "Boumerdès", null, "Province"));
    out.add(new Subdivision("DZ-36", "El Tarf", null, "Province"));
    out.add(new Subdivision("DZ-37", "Tindouf", null, "Province"));
    out.add(new Subdivision("DZ-38", "Tissemsilt", null, "Province"));
    out.add(new Subdivision("DZ-39", "El Oued", null, "Province"));
    out.add(new Subdivision("DZ-40", "Khenchela", null, "Province"));
    out.add(new Subdivision("DZ-41", "Souk Ahras", null, "Province"));
    out.add(new Subdivision("DZ-42", "Tipaza", null, "Province"));
    out.add(new Subdivision("DZ-43", "Mila", null, "Province"));
    out.add(new Subdivision("DZ-44", "Aïn Defla", null, "Province"));
    out.add(new Subdivision("DZ-45", "Naama", null, "Province"));
    out.add(new Subdivision("DZ-46", "Aïn Témouchent", null, "Province"));
    out.add(new Subdivision("DZ-47", "Ghardaïa", null, "Province"));
    out.add(new Subdivision("DZ-48", "Relizane", null, "Province"));
    out.add(new Subdivision("DZ-49", "Timimoun", null, "Province"));
    out.add(new Subdivision("DZ-50", "Bordj Badji Mokhtar", null, "Province"));
    out.add(new Subdivision("DZ-51", "Ouled Djellal", null, "Province"));
    out.add(new Subdivision("DZ-52", "Béni Abbès", null, "Province"));
    out.add(new Subdivision("DZ-53", "In Salah", null, "Province"));
    out.add(new Subdivision("DZ-54", "In Guezzam", null, "Province"));
    out.add(new Subdivision("DZ-55", "Touggourt", null, "Province"));
    out.add(new Subdivision("DZ-56", "Djanet", null, "Province"));
    out.add(new Subdivision("DZ-57", "El Meghaier", null, "Province"));
    out.add(new Subdivision("DZ-58", "El Meniaa", null, "Province"));
    out.add(new Subdivision("EC-A", "Azuay", null, "Province"));
    out.add(new Subdivision("EC-B", "Bolívar", null, "Province"));
    out.add(new Subdivision("EC-C", "Carchi", null, "Province"));
    out.add(new Subdivision("EC-D", "Orellana", null, "Province"));
    out.add(new Subdivision("EC-E", "Esmeraldas", null, "Province"));
    out.add(new Subdivision("EC-F", "Cañar", null, "Province"));
    out.add(new Subdivision("EC-G", "Guayas", null, "Province"));
    out.add(new Subdivision("EC-H", "Chimborazo", null, "Province"));
    out.add(new Subdivision("EC-I", "Imbabura", null, "Province"));
    out.add(new Subdivision("EC-L", "Loja", null, "Province"));
    out.add(new Subdivision("EC-M", "Manabí", null, "Province"));
    out.add(new Subdivision("EC-N", "Napo", null, "Province"));
    out.add(new Subdivision("EC-O", "El Oro", null, "Province"));
    out.add(new Subdivision("EC-P", "Pichincha", null, "Province"));
    out.add(new Subdivision("EC-R", "Los Ríos", null, "Province"));
    out.add(new Subdivision("EC-S", "Morona Santiago", null, "Province"));
    out.add(new Subdivision("EC-SD", "Santo Domingo de los Tsáchilas", null, "Province"));
    out.add(new Subdivision("EC-SE", "Santa Elena", null, "Province"));
    out.add(new Subdivision("EC-T", "Tungurahua", null, "Province"));
    out.add(new Subdivision("EC-U", "Sucumbíos", null, "Province"));
    out.add(new Subdivision("EC-W", "Galápagos", null, "Province"));
    out.add(new Subdivision("EC-X", "Cotopaxi", null, "Province"));
    out.add(new Subdivision("EC-Y", "Pastaza", null, "Province"));
    out.add(new Subdivision("EC-Z", "Zamora Chinchipe", null, "Province"));
    out.add(new Subdivision("EE-130", "Alutaguse", "EE-45", "Rural municipality"));
    out.add(new Subdivision("EE-141", "Anija", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-142", "Antsla", "EE-87", "Rural municipality"));
    out.add(new Subdivision("EE-171", "Elva", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-184", "Haapsalu", "EE-56", "Urban municipality"));
    out.add(new Subdivision("EE-191", "Haljala", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-198", "Harku", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-205", "Hiiumaa", "EE-39", "Rural municipality"));
    out.add(new Subdivision("EE-214", "Häädemeeste", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-245", "Jõelähtme", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-247", "Jõgeva", "EE-50", "Rural municipality"));
    out.add(new Subdivision("EE-251", "Jõhvi", "EE-45", "Rural municipality"));
    out.add(new Subdivision("EE-255", "Järva", "EE-52", "Rural municipality"));
    out.add(new Subdivision("EE-272", "Kadrina", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-283", "Kambja", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-284", "Kanepi", "EE-64", "Rural municipality"));
    out.add(new Subdivision("EE-291", "Kastre", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-293", "Kehtna", "EE-71", "Rural municipality"));
    out.add(new Subdivision("EE-296", "Keila", "EE-37", "Urban municipality"));
    out.add(new Subdivision("EE-303", "Kihnu", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-305", "Kiili", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-317", "Kohila", "EE-71", "Rural municipality"));
    out.add(new Subdivision("EE-321", "Kohtla-Järve", "EE-45", "Urban municipality"));
    out.add(new Subdivision("EE-338", "Kose", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-353", "Kuusalu", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-37", "Harjumaa", null, "County"));
    out.add(new Subdivision("EE-39", "Hiiumaa", null, "County"));
    out.add(new Subdivision("EE-424", "Loksa", "EE-37", "Urban municipality"));
    out.add(new Subdivision("EE-430", "Lääneranna", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-431", "Lääne-Harju", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-432", "Luunja", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-441", "Lääne-Nigula", "EE-56", "Rural municipality"));
    out.add(new Subdivision("EE-442", "Lüganuse", "EE-45", "Rural municipality"));
    out.add(new Subdivision("EE-446", "Maardu", "EE-37", "Urban municipality"));
    out.add(new Subdivision("EE-45", "Ida-Virumaa", null, "County"));
    out.add(new Subdivision("EE-478", "Muhu", "EE-74", "Rural municipality"));
    out.add(new Subdivision("EE-480", "Mulgi", "EE-84", "Rural municipality"));
    out.add(new Subdivision("EE-486", "Mustvee", "EE-50", "Rural municipality"));
    out.add(new Subdivision("EE-50", "Jõgevamaa", null, "County"));
    out.add(new Subdivision("EE-503", "Märjamaa", "EE-71", "Rural municipality"));
    out.add(new Subdivision("EE-511", "Narva", "EE-45", "Urban municipality"));
    out.add(new Subdivision("EE-514", "Narva-Jõesuu", "EE-45", "Urban municipality"));
    out.add(new Subdivision("EE-52", "Järvamaa", null, "County"));
    out.add(new Subdivision("EE-528", "Nõo", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-557", "Otepää", "EE-81", "Rural municipality"));
    out.add(new Subdivision("EE-56", "Läänemaa", null, "County"));
    out.add(new Subdivision("EE-567", "Paide", "EE-52", "Urban municipality"));
    out.add(new Subdivision("EE-586", "Peipsiääre", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-60", "Lääne-Virumaa", null, "County"));
    out.add(new Subdivision("EE-615", "Põhja-Sakala", "EE-84", "Rural municipality"));
    out.add(new Subdivision("EE-618", "Põltsamaa", "EE-50", "Rural municipality"));
    out.add(new Subdivision("EE-622", "Põlva", "EE-64", "Rural municipality"));
    out.add(new Subdivision("EE-624", "Pärnu", "EE-68", "Urban municipality"));
    out.add(new Subdivision("EE-638", "Põhja-Pärnumaa", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-64", "Põlvamaa", null, "County"));
    out.add(new Subdivision("EE-651", "Raasiku", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-653", "Rae", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-661", "Rakvere", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-663", "Rakvere", "EE-60", "Urban municipality"));
    out.add(new Subdivision("EE-668", "Rapla", "EE-71", "Rural municipality"));
    out.add(new Subdivision("EE-68", "Pärnumaa", null, "County"));
    out.add(new Subdivision("EE-689", "Ruhnu", "EE-74", "Rural municipality"));
    out.add(new Subdivision("EE-698", "Rõuge", "EE-87", "Rural municipality"));
    out.add(new Subdivision("EE-708", "Räpina", "EE-64", "Rural municipality"));
    out.add(new Subdivision("EE-71", "Raplamaa", null, "County"));
    out.add(new Subdivision("EE-712", "Saarde", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-714", "Saaremaa", "EE-74", "Rural municipality"));
    out.add(new Subdivision("EE-719", "Saku", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-726", "Saue", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-732", "Setomaa", "EE-87", "Rural municipality"));
    out.add(new Subdivision("EE-735", "Sillamäe", "EE-45", "Urban municipality"));
    out.add(new Subdivision("EE-74", "Saaremaa", null, "County"));
    out.add(new Subdivision("EE-784", "Tallinn", "EE-37", "Urban municipality"));
    out.add(new Subdivision("EE-79", "Tartumaa", null, "County"));
    out.add(new Subdivision("EE-792", "Tapa", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-793", "Tartu", "EE-79", "Urban municipality"));
    out.add(new Subdivision("EE-796", "Tartu", "EE-79", "Rural municipality"));
    out.add(new Subdivision("EE-803", "Toila", "EE-45", "Rural municipality"));
    out.add(new Subdivision("EE-809", "Tori", "EE-68", "Rural municipality"));
    out.add(new Subdivision("EE-81", "Valgamaa", null, "County"));
    out.add(new Subdivision("EE-824", "Tõrva", "EE-81", "Rural municipality"));
    out.add(new Subdivision("EE-834", "Türi", "EE-52", "Rural municipality"));
    out.add(new Subdivision("EE-84", "Viljandimaa", null, "County"));
    out.add(new Subdivision("EE-855", "Valga", "EE-81", "Rural municipality"));
    out.add(new Subdivision("EE-87", "Võrumaa", null, "County"));
    out.add(new Subdivision("EE-890", "Viimsi", "EE-37", "Rural municipality"));
    out.add(new Subdivision("EE-897", "Viljandi", "EE-84", "Urban municipality"));
    out.add(new Subdivision("EE-899", "Viljandi", "EE-84", "Rural municipality"));
    out.add(new Subdivision("EE-901", "Vinni", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-903", "Viru-Nigula", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EE-907", "Vormsi", "EE-56", "Rural municipality"));
    out.add(new Subdivision("EE-917", "Võru", "EE-87", "Rural municipality"));
    out.add(new Subdivision("EE-919", "Võru", "EE-87", "Urban municipality"));
    out.add(new Subdivision("EE-928", "Väike-Maarja", "EE-60", "Rural municipality"));
    out.add(new Subdivision("EG-ALX", "Al Iskandarīyah", null, "Governorate"));
    out.add(new Subdivision("EG-ASN", "Aswān", null, "Governorate"));
    out.add(new Subdivision("EG-AST", "Asyūţ", null, "Governorate"));
    out.add(new Subdivision("EG-BA", "Al Baḩr al Aḩmar", null, "Governorate"));
    out.add(new Subdivision("EG-BH", "Al Buḩayrah", null, "Governorate"));
    out.add(new Subdivision("EG-BNS", "Banī Suwayf", null, "Governorate"));
    out.add(new Subdivision("EG-C", "Al Qāhirah", null, "Governorate"));
    out.add(new Subdivision("EG-DK", "Ad Daqahlīyah", null, "Governorate"));
    out.add(new Subdivision("EG-DT", "Dumyāţ", null, "Governorate"));
    out.add(new Subdivision("EG-FYM", "Al Fayyūm", null, "Governorate"));
    out.add(new Subdivision("EG-GH", "Al Gharbīyah", null, "Governorate"));
    out.add(new Subdivision("EG-GZ", "Al Jīzah", null, "Governorate"));
    out.add(new Subdivision("EG-IS", "Al Ismā'īlīyah", null, "Governorate"));
    out.add(new Subdivision("EG-JS", "Janūb Sīnā'", null, "Governorate"));
    out.add(new Subdivision("EG-KB", "Al Qalyūbīyah", null, "Governorate"));
    out.add(new Subdivision("EG-KFS", "Kafr ash Shaykh", null, "Governorate"));
    out.add(new Subdivision("EG-KN", "Qinā", null, "Governorate"));
    out.add(new Subdivision("EG-LX", "Al Uqşur", null, "Governorate"));
    out.add(new Subdivision("EG-MN", "Al Minyā", null, "Governorate"));
    out.add(new Subdivision("EG-MNF", "Al Minūfīyah", null, "Governorate"));
    out.add(new Subdivision("EG-MT", "Maţrūḩ", null, "Governorate"));
    out.add(new Subdivision("EG-PTS", "Būr Sa‘īd", null, "Governorate"));
    out.add(new Subdivision("EG-SHG", "Sūhāj", null, "Governorate"));
    out.add(new Subdivision("EG-SHR", "Ash Sharqīyah", null, "Governorate"));
    out.add(new Subdivision("EG-SIN", "Shamāl Sīnā'", null, "Governorate"));
    out.add(new Subdivision("EG-SUZ", "As Suways", null, "Governorate"));
    out.add(new Subdivision("EG-WAD", "Al Wādī al Jadīd", null, "Governorate"));
    out.add(new Subdivision("ER-AN", "Ansabā", null, "Region"));
    out.add(new Subdivision("ER-DK", "Janūbī al Baḩrī al Aḩmar", null, "Region"));
    out.add(new Subdivision("ER-DU", "Al Janūbī", null, "Region"));
    out.add(new Subdivision("ER-GB", "Qāsh-Barkah", null, "Region"));
    out.add(new Subdivision("ER-MA", "Al Awsaţ", null, "Region"));
    out.add(new Subdivision("ER-SK", "Shimālī al Baḩrī al Aḩmar", null, "Region"));
    out.add(new Subdivision("ES-A", "Alicante", "ES-VC", "Province"));
    out.add(new Subdivision("ES-AB", "Albacete", "ES-CM", "Province"));
    out.add(new Subdivision("ES-AL", "Almería", "ES-AN", "Province"));
    out.add(new Subdivision("ES-AN", "Andalucía", null, "Autonomous community"));
    out.add(new Subdivision("ES-AR", "Aragón", null, "Autonomous community"));
    out.add(new Subdivision("ES-AS", "Asturias, Principado de", null, "Autonomous community"));
    out.add(new Subdivision("ES-AV", "Ávila", "ES-CL", "Province"));
    out.add(new Subdivision("ES-B", "Barcelona [Barcelona]", "ES-CT", "Province"));
    out.add(new Subdivision("ES-BA", "Badajoz", "ES-EX", "Province"));
    out.add(new Subdivision("ES-BI", "Bizkaia", "ES-PV", "Province"));
    out.add(new Subdivision("ES-BU", "Burgos", "ES-CL", "Province"));
    out.add(new Subdivision("ES-C", "A Coruña [La Coruña]", "ES-GA", "Province"));
    out.add(new Subdivision("ES-CA", "Cádiz", "ES-AN", "Province"));
    out.add(new Subdivision("ES-CB", "Cantabria", null, "Autonomous community"));
    out.add(new Subdivision("ES-CC", "Cáceres", "ES-EX", "Province"));
    out.add(new Subdivision("ES-CE", "Ceuta", null, "Autonomous city in north africa"));
    out.add(new Subdivision("ES-CL", "Castilla y León", null, "Autonomous community"));
    out.add(new Subdivision("ES-CM", "Castilla-La Mancha", null, "Autonomous community"));
    out.add(new Subdivision("ES-CN", "Canarias", null, "Autonomous community"));
    out.add(new Subdivision("ES-CO", "Córdoba", "ES-AN", "Province"));
    out.add(new Subdivision("ES-CR", "Ciudad Real", "ES-CM", "Province"));
    out.add(new Subdivision("ES-CS", "Castellón", "ES-VC", "Province"));
    out.add(new Subdivision("ES-CT", "Catalunya [Cataluña]", null, "Autonomous community"));
    out.add(new Subdivision("ES-CU", "Cuenca", "ES-CM", "Province"));
    out.add(new Subdivision("ES-EX", "Extremadura", null, "Autonomous community"));
    out.add(new Subdivision("ES-GA", "Galicia [Galicia]", null, "Autonomous community"));
    out.add(new Subdivision("ES-GC", "Las Palmas", "ES-CN", "Province"));
    out.add(new Subdivision("ES-GI", "Girona [Gerona]", "ES-CT", "Province"));
    out.add(new Subdivision("ES-GR", "Granada", "ES-AN", "Province"));
    out.add(new Subdivision("ES-GU", "Guadalajara", "ES-CM", "Province"));
    out.add(new Subdivision("ES-H", "Huelva", "ES-AN", "Province"));
    out.add(new Subdivision("ES-HU", "Huesca", "ES-AR", "Province"));
    out.add(new Subdivision("ES-IB", "Illes Balears [Islas Baleares]", null, "Autonomous community"));
    out.add(new Subdivision("ES-J", "Jaén", "ES-AN", "Province"));
    out.add(new Subdivision("ES-L", "Lleida [Lérida]", "ES-CT", "Province"));
    out.add(new Subdivision("ES-LE", "León", "ES-CL", "Province"));
    out.add(new Subdivision("ES-LO", "La Rioja", "ES-RI", "Province"));
    out.add(new Subdivision("ES-LU", "Lugo [Lugo]", "ES-GA", "Province"));
    out.add(new Subdivision("ES-M", "Madrid", "ES-MD", "Province"));
    out.add(new Subdivision("ES-MA", "Málaga", "ES-AN", "Province"));
    out.add(new Subdivision("ES-MC", "Murcia, Región de", null, "Autonomous community"));
    out.add(new Subdivision("ES-MD", "Madrid, Comunidad de", null, "Autonomous community"));
    out.add(new Subdivision("ES-ML", "Melilla", null, "Autonomous city in north africa"));
    out.add(new Subdivision("ES-MU", "Murcia", "ES-MC", "Province"));
    out.add(new Subdivision("ES-NA", "Navarra", "ES-NC", "Province"));
    out.add(new Subdivision("ES-NC", "Navarra, Comunidad Foral de", null, "Autonomous community"));
    out.add(new Subdivision("ES-O", "Asturias", "ES-AS", "Province"));
    out.add(new Subdivision("ES-OR", "Ourense [Orense]", "ES-GA", "Province"));
    out.add(new Subdivision("ES-P", "Palencia", "ES-CL", "Province"));
    out.add(new Subdivision("ES-PM", "Illes Balears [Islas Baleares]", "ES-IB", "Province"));
    out.add(new Subdivision("ES-PO", "Pontevedra [Pontevedra]", "ES-GA", "Province"));
    out.add(new Subdivision("ES-PV", "País Vasco", null, "Autonomous community"));
    out.add(new Subdivision("ES-RI", "La Rioja", null, "Autonomous community"));
    out.add(new Subdivision("ES-S", "Cantabria", "ES-CB", "Province"));
    out.add(new Subdivision("ES-SA", "Salamanca", "ES-CL", "Province"));
    out.add(new Subdivision("ES-SE", "Sevilla", "ES-AN", "Province"));
    out.add(new Subdivision("ES-SG", "Segovia", "ES-CL", "Province"));
    out.add(new Subdivision("ES-SO", "Soria", "ES-CL", "Province"));
    out.add(new Subdivision("ES-SS", "Gipuzkoa", "ES-PV", "Province"));
    out.add(new Subdivision("ES-T", "Tarragona [Tarragona]", "ES-CT", "Province"));
    out.add(new Subdivision("ES-TE", "Teruel", "ES-AR", "Province"));
    out.add(new Subdivision("ES-TF", "Santa Cruz de Tenerife", "ES-CN", "Province"));
    out.add(new Subdivision("ES-TO", "Toledo", "ES-CM", "Province"));
    out.add(new Subdivision("ES-V", "Valencia", "ES-VC", "Province"));
    out.add(new Subdivision("ES-VA", "Valladolid", "ES-CL", "Province"));
    out.add(new Subdivision("ES-VC", "Valenciana, Comunidad", null, "Autonomous community"));
    out.add(new Subdivision("ES-VI", "Álava", "ES-PV", "Province"));
    out.add(new Subdivision("ES-Z", "Zaragoza", "ES-AR", "Province"));
    out.add(new Subdivision("ES-ZA", "Zamora", "ES-CL", "Province"));
    out.add(new Subdivision("ET-AA", "Addis Ababa", null, "Administration"));
    out.add(new Subdivision("ET-AF", "Afar", null, "Regional state"));
    out.add(new Subdivision("ET-AM", "Amara", null, "Regional state"));
    out.add(new Subdivision("ET-BE", "Benshangul-Gumaz", null, "Regional state"));
    out.add(new Subdivision("ET-DD", "Dire Dawa", null, "Administration"));
    out.add(new Subdivision("ET-GA", "Gambela Peoples", null, "Regional state"));
    out.add(new Subdivision("ET-HA", "Harari People", null, "Regional state"));
    out.add(new Subdivision("ET-OR", "Oromia", null, "Regional state"));
    out.add(new Subdivision("ET-SI", "Sidama", null, "Regional state"));
    out.add(new Subdivision("ET-SN", "Southern Nations, Nationalities and Peoples", null, "Regional state"));
    out.add(new Subdivision("ET-SO", "Somali", null, "Regional state"));
    out.add(new Subdivision("ET-SW", "Southwest Ethiopia Peoples", null, "Regional state"));
    out.add(new Subdivision("ET-TI", "Tigrai", null, "Regional state"));
    out.add(new Subdivision("FI-01", "Landskapet Åland", null, "Region"));
    out.add(new Subdivision("FI-02", "Etelä-Karjala", null, "Region"));
    out.add(new Subdivision("FI-03", "Etelä-Pohjanmaa", null, "Region"));
    out.add(new Subdivision("FI-04", "Etelä-Savo", null, "Region"));
    out.add(new Subdivision("FI-05", "Kainuu", null, "Region"));
    out.add(new Subdivision("FI-06", "Kanta-Häme", null, "Region"));
    out.add(new Subdivision("FI-07", "Keski-Pohjanmaa", null, "Region"));
    out.add(new Subdivision("FI-08", "Keski-Suomi", null, "Region"));
    out.add(new Subdivision("FI-09", "Kymenlaakso", null, "Region"));
    out.add(new Subdivision("FI-10", "Lappi", null, "Region"));
    out.add(new Subdivision("FI-11", "Pirkanmaa", null, "Region"));
    out.add(new Subdivision("FI-12", "Pohjanmaa", null, "Region"));
    out.add(new Subdivision("FI-13", "Pohjois-Karjala", null, "Region"));
    out.add(new Subdivision("FI-14", "Pohjois-Pohjanmaa", null, "Region"));
    out.add(new Subdivision("FI-15", "Pohjois-Savo", null, "Region"));
    out.add(new Subdivision("FI-16", "Päijät-Häme", null, "Region"));
    out.add(new Subdivision("FI-17", "Satakunta", null, "Region"));
    out.add(new Subdivision("FI-18", "Uusimaa", null, "Region"));
    out.add(new Subdivision("FI-19", "Varsinais-Suomi", null, "Region"));
    out.add(new Subdivision("FJ-01", "Ba", "FJ-W", "Province"));
    out.add(new Subdivision("FJ-02", "Bua", "FJ-N", "Province"));
    out.add(new Subdivision("FJ-03", "Cakaudrove", "FJ-N", "Province"));
    out.add(new Subdivision("FJ-04", "Kadavu", "FJ-E", "Province"));
    out.add(new Subdivision("FJ-05", "Lau", "FJ-E", "Province"));
    out.add(new Subdivision("FJ-06", "Lomaiviti", "FJ-E", "Province"));
    out.add(new Subdivision("FJ-07", "Macuata", "FJ-N", "Province"));
    out.add(new Subdivision("FJ-08", "Nadroga and Navosa", "FJ-W", "Province"));
    out.add(new Subdivision("FJ-09", "Naitasiri", "FJ-C", "Province"));
    out.add(new Subdivision("FJ-10", "Namosi", "FJ-C", "Province"));
    out.add(new Subdivision("FJ-11", "Ra", "FJ-W", "Province"));
    out.add(new Subdivision("FJ-12", "Rewa", "FJ-C", "Province"));
    out.add(new Subdivision("FJ-13", "Serua", "FJ-C", "Province"));
    out.add(new Subdivision("FJ-14", "Tailevu", "FJ-C", "Province"));
    out.add(new Subdivision("FJ-C", "Central", null, "Division"));
    out.add(new Subdivision("FJ-E", "Eastern", null, "Division"));
    out.add(new Subdivision("FJ-N", "Northern", null, "Division"));
    out.add(new Subdivision("FJ-R", "Rotuma", null, "Dependency"));
    out.add(new Subdivision("FJ-W", "Western", null, "Division"));
    out.add(new Subdivision("FM-KSA", "Kosrae", null, "State"));
    out.add(new Subdivision("FM-PNI", "Pohnpei", null, "State"));
    out.add(new Subdivision("FM-TRK", "Chuuk", null, "State"));
    out.add(new Subdivision("FM-YAP", "Yap", null, "State"));
    out.add(new Subdivision("FR-01", "Ain", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-02", "Aisne", "FR-HDF", "Metropolitan department"));
    out.add(new Subdivision("FR-03", "Allier", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-04", "Alpes-de-Haute-Provence", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-05", "Hautes-Alpes", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-06", "Alpes-Maritimes", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-07", "Ardèche", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-08", "Ardennes", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-09", "Ariège", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-10", "Aube", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-11", "Aude", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-12", "Aveyron", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-13", "Bouches-du-Rhône", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-14", "Calvados", "FR-NOR", "Metropolitan department"));
    out.add(new Subdivision("FR-15", "Cantal", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-16", "Charente", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-17", "Charente-Maritime", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-18", "Cher", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-19", "Corrèze", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-20R", "Corse", null, "Metropolitan collectivity with special status"));
    out.add(new Subdivision("FR-21", "Côte-d'Or", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-22", "Côtes-d'Armor", "FR-BRE", "Metropolitan department"));
    out.add(new Subdivision("FR-23", "Creuse", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-24", "Dordogne", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-25", "Doubs", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-26", "Drôme", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-27", "Eure", "FR-NOR", "Metropolitan department"));
    out.add(new Subdivision("FR-28", "Eure-et-Loir", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-29", "Finistère", "FR-BRE", "Metropolitan department"));
    out.add(new Subdivision("FR-2A", "Corse-du-Sud", "FR-20R", "Metropolitan department"));
    out.add(new Subdivision("FR-2B", "Haute-Corse", "FR-20R", "Metropolitan department"));
    out.add(new Subdivision("FR-30", "Gard", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-31", "Haute-Garonne", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-32", "Gers", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-33", "Gironde", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-34", "Hérault", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-35", "Ille-et-Vilaine", "FR-BRE", "Metropolitan department"));
    out.add(new Subdivision("FR-36", "Indre", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-37", "Indre-et-Loire", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-38", "Isère", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-39", "Jura", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-40", "Landes", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-41", "Loir-et-Cher", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-42", "Loire", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-43", "Haute-Loire", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-44", "Loire-Atlantique", "FR-PDL", "Metropolitan department"));
    out.add(new Subdivision("FR-45", "Loiret", "FR-CVL", "Metropolitan department"));
    out.add(new Subdivision("FR-46", "Lot", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-47", "Lot-et-Garonne", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-48", "Lozère", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-49", "Maine-et-Loire", "FR-PDL", "Metropolitan department"));
    out.add(new Subdivision("FR-50", "Manche", "FR-NOR", "Metropolitan department"));
    out.add(new Subdivision("FR-51", "Marne", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-52", "Haute-Marne", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-53", "Mayenne", "FR-PDL", "Metropolitan department"));
    out.add(new Subdivision("FR-54", "Meurthe-et-Moselle", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-55", "Meuse", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-56", "Morbihan", "FR-BRE", "Metropolitan department"));
    out.add(new Subdivision("FR-57", "Moselle", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-58", "Nièvre", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-59", "Nord", "FR-HDF", "Metropolitan department"));
    out.add(new Subdivision("FR-60", "Oise", "FR-HDF", "Metropolitan department"));
    out.add(new Subdivision("FR-61", "Orne", "FR-NOR", "Metropolitan department"));
    out.add(new Subdivision("FR-62", "Pas-de-Calais", "FR-HDF", "Metropolitan department"));
    out.add(new Subdivision("FR-63", "Puy-de-Dôme", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-64", "Pyrénées-Atlantiques", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-65", "Hautes-Pyrénées", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-66", "Pyrénées-Orientales", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-67", "Bas-Rhin", "FR-6AE", "Metropolitan department"));
    out.add(new Subdivision("FR-68", "Haut-Rhin", "FR-6AE", "Metropolitan department"));
    out.add(new Subdivision("FR-69", "Rhône", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-69M", "Métropole de Lyon", "FR-ARA", "Metropolitan collectivity with special status"));
    out.add(new Subdivision("FR-6AE", "Alsace", "FR-GES", "European collectivity"));
    out.add(new Subdivision("FR-70", "Haute-Saône", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-71", "Saône-et-Loire", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-72", "Sarthe", "FR-PDL", "Metropolitan department"));
    out.add(new Subdivision("FR-73", "Savoie", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-74", "Haute-Savoie", "FR-ARA", "Metropolitan department"));
    out.add(new Subdivision("FR-75C", "Paris", "FR-IDF", "Metropolitan collectivity with special status"));
    out.add(new Subdivision("FR-76", "Seine-Maritime", "FR-NOR", "Metropolitan department"));
    out.add(new Subdivision("FR-77", "Seine-et-Marne", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-78", "Yvelines", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-79", "Deux-Sèvres", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-80", "Somme", "FR-HDF", "Metropolitan department"));
    out.add(new Subdivision("FR-81", "Tarn", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-82", "Tarn-et-Garonne", "FR-OCC", "Metropolitan department"));
    out.add(new Subdivision("FR-83", "Var", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-84", "Vaucluse", "FR-PAC", "Metropolitan department"));
    out.add(new Subdivision("FR-85", "Vendée", "FR-PDL", "Metropolitan department"));
    out.add(new Subdivision("FR-86", "Vienne", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-87", "Haute-Vienne", "FR-NAQ", "Metropolitan department"));
    out.add(new Subdivision("FR-88", "Vosges", "FR-GES", "Metropolitan department"));
    out.add(new Subdivision("FR-89", "Yonne", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-90", "Territoire de Belfort", "FR-BFC", "Metropolitan department"));
    out.add(new Subdivision("FR-91", "Essonne", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-92", "Hauts-de-Seine", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-93", "Seine-Saint-Denis", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-94", "Val-de-Marne", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-95", "Val-d'Oise", "FR-IDF", "Metropolitan department"));
    out.add(new Subdivision("FR-971", "Guadeloupe", null, "Overseas departmental collectivity"));
    out.add(new Subdivision("FR-972", "Martinique", null, "Overseas unique territorial collectivity"));
    out.add(new Subdivision("FR-973", "Guyane (française)", null, "Overseas unique territorial collectivity"));
    out.add(new Subdivision("FR-974", "La Réunion", null, "Overseas departmental collectivity"));
    out.add(new Subdivision("FR-976", "Mayotte", null, "Overseas departmental collectivity"));
    out.add(new Subdivision("FR-ARA", "Auvergne-Rhône-Alpes", null, "Metropolitan region"));
    out.add(new Subdivision("FR-BFC", "Bourgogne-Franche-Comté", null, "Metropolitan region"));
    out.add(new Subdivision("FR-BL", "Saint-Barthélemy", null, "Overseas collectivity"));
    out.add(new Subdivision("FR-BRE", "Bretagne", null, "Metropolitan region"));
    out.add(new Subdivision("FR-CP", "Clipperton", null, "Dependency"));
    out.add(new Subdivision("FR-CVL", "Centre-Val de Loire", null, "Metropolitan region"));
    out.add(new Subdivision("FR-GES", "Grand-Est", null, "Metropolitan region"));
    out.add(new Subdivision("FR-HDF", "Hauts-de-France", null, "Metropolitan region"));
    out.add(new Subdivision("FR-IDF", "Île-de-France", null, "Metropolitan region"));
    out.add(new Subdivision("FR-MF", "Saint-Martin", null, "Overseas collectivity"));
    out.add(new Subdivision("FR-NAQ", "Nouvelle-Aquitaine", null, "Metropolitan region"));
    out.add(new Subdivision("FR-NC", "Nouvelle-Calédonie", null, "Overseas collectivity with special status"));
    out.add(new Subdivision("FR-NOR", "Normandie", null, "Metropolitan region"));
    out.add(new Subdivision("FR-OCC", "Occitanie", null, "Metropolitan region"));
    out.add(new Subdivision("FR-PAC", "Provence-Alpes-Côte-d’Azur", null, "Metropolitan region"));
    out.add(new Subdivision("FR-PDL", "Pays-de-la-Loire", null, "Metropolitan region"));
    out.add(new Subdivision("FR-PF", "Polynésie française", null, "Overseas collectivity"));
    out.add(new Subdivision("FR-PM", "Saint-Pierre-et-Miquelon", null, "Overseas collectivity"));
    out.add(new Subdivision("FR-TF", "Terres australes françaises", null, "Overseas territory"));
    out.add(new Subdivision("FR-WF", "Wallis-et-Futuna", null, "Overseas collectivity"));
    out.add(new Subdivision("GA-1", "Estuaire", null, "Province"));
    out.add(new Subdivision("GA-2", "Haut-Ogooué", null, "Province"));
    out.add(new Subdivision("GA-3", "Moyen-Ogooué", null, "Province"));
    out.add(new Subdivision("GA-4", "Ngounié", null, "Province"));
    out.add(new Subdivision("GA-5", "Nyanga", null, "Province"));
    out.add(new Subdivision("GA-6", "Ogooué-Ivindo", null, "Province"));
    out.add(new Subdivision("GA-7", "Ogooué-Lolo", null, "Province"));
    out.add(new Subdivision("GA-8", "Ogooué-Maritime", null, "Province"));
    out.add(new Subdivision("GA-9", "Woleu-Ntem", null, "Province"));
    out.add(new Subdivision("GB-ABC", "Armagh City, Banbridge and Craigavon", "GB-NIR", "District"));
    out.add(new Subdivision("GB-ABD", "Aberdeenshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-ABE", "Aberdeen City", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-AGB", "Argyll and Bute", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-AGY", "Isle of Anglesey [Sir Ynys Môn GB-YNM]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-AND", "Ards and North Down", "GB-NIR", "District"));
    out.add(new Subdivision("GB-ANN", "Antrim and Newtownabbey", "GB-NIR", "District"));
    out.add(new Subdivision("GB-ANS", "Angus", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-BAS", "Bath and North East Somerset", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BBD", "Blackburn with Darwen", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BCP", "Bournemouth, Christchurch and Poole", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BDF", "Bedford", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BDG", "Barking and Dagenham", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-BEN", "Brent", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-BEX", "Bexley", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-BFS", "Belfast City", "GB-NIR", "District"));
    out.add(new Subdivision("GB-BGE", "Bridgend [Pen-y-bont ar Ogwr GB-POG]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-BGW", "Blaenau Gwent", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-BIR", "Birmingham", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-BKM", "Buckinghamshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BNE", "Barnet", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-BNH", "Brighton and Hove", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BNS", "Barnsley", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-BOL", "Bolton", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-BPL", "Blackpool", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BRC", "Bracknell Forest", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BRD", "Bradford", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-BRY", "Bromley", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-BST", "Bristol, City of", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-BUR", "Bury", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-CAM", "Cambridgeshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-CAY", "Caerphilly [Caerffili GB-CAF]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-CBF", "Central Bedfordshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-CCG", "Causeway Coast and Glens", "GB-NIR", "District"));
    out.add(new Subdivision("GB-CGN", "Ceredigion [Sir Ceredigion]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-CHE", "Cheshire East", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-CHW", "Cheshire West and Chester", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-CLD", "Calderdale", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-CLK", "Clackmannanshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-CMA", "Cumbria", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-CMD", "Camden", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-CMN", "Carmarthenshire [Sir Gaerfyrddin GB-GFY]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-CON", "Cornwall", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-COV", "Coventry", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-CRF", "Cardiff [Caerdydd GB-CRD]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-CRY", "Croydon", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-CWY", "Conwy", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-DAL", "Darlington", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-DBY", "Derbyshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-DEN", "Denbighshire [Sir Ddinbych GB-DDB]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-DER", "Derby", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-DEV", "Devon", "GB-ENG", "Two-tier county"));
  }
}
