// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 3500 to 3999 of {@link Subdivision}.
 */
final class SubdivisionData7 {
  private SubdivisionData7() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("PG-GPK", "Gulf", null, "Province"));
    out.add(new Subdivision("PG-HLA", "Hela", null, "Province"));
    out.add(new Subdivision("PG-JWK", "Jiwaka", null, "Province"));
    out.add(new Subdivision("PG-MBA", "Milne Bay", null, "Province"));
    out.add(new Subdivision("PG-MPL", "Morobe", null, "Province"));
    out.add(new Subdivision("PG-MPM", "Madang", null, "Province"));
    out.add(new Subdivision("PG-MRL", "Manus", null, "Province"));
    out.add(new Subdivision("PG-NCD", "National Capital District (Port Moresby)", null, "District"));
    out.add(new Subdivision("PG-NIK", "New Ireland", null, "Province"));
    out.add(new Subdivision("PG-NPP", "Northern", null, "Province"));
    out.add(new Subdivision("PG-NSB", "Bougainville", null, "Autonomous region"));
    out.add(new Subdivision("PG-SAN", "West Sepik", null, "Province"));
    out.add(new Subdivision("PG-SHM", "Southern Highlands", null, "Province"));
    out.add(new Subdivision("PG-WBK", "West New Britain", null, "Province"));
    out.add(new Subdivision("PG-WHM", "Western Highlands", null, "Province"));
    out.add(new Subdivision("PG-WPD", "Western", null, "Province"));
    out.add(new Subdivision("PH-00", "National Capital Region", null, "Region"));
    out.add(new Subdivision("PH-01", "Ilocos (Region I)", null, "Region"));
    out.add(new Subdivision("PH-02", "Cagayan Valley (Region II)", null, "Region"));
    out.add(new Subdivision("PH-03", "Central Luzon (Region III)", null, "Region"));
    out.add(new Subdivision("PH-05", "Bicol (Region V)", null, "Region"));
    out.add(new Subdivision("PH-06", "Western Visayas (Region VI)", null, "Region"));
    out.add(new Subdivision("PH-07", "Central Visayas (Region VII)", null, "Region"));
    out.add(new Subdivision("PH-08", "Eastern Visayas (Region VIII)", null, "Region"));
    out.add(new Subdivision("PH-09", "Zamboanga Peninsula (Region IX)", null, "Region"));
    out.add(new Subdivision("PH-10", "Northern Mindanao (Region X)", null, "Region"));
    out.add(new Subdivision("PH-11", "Davao (Region XI)", null, "Region"));
    out.add(new Subdivision("PH-12", "Soccsksargen (Region XII)", null, "Region"));
    out.add(new Subdivision("PH-13", "Caraga (Region XIII)", null, "Region"));
    out.add(new Subdivision("PH-14", "Autonomous Region in Muslim Mindanao (ARMM)", null, "Region"));
    out.add(new Subdivision("PH-15", "Cordillera Administrative Region (CAR)", null, "Region"));
    out.add(new Subdivision("PH-40", "Calabarzon (Region IV-A)", null, "Region"));
    out.add(new Subdivision("PH-41", "Mimaropa (Region IV-B)", null, "Region"));
    out.add(new Subdivision("PH-ABR", "Abra", "PH-15", "Province"));
    out.add(new Subdivision("PH-AGN", "Agusan del Norte", "PH-13", "Province"));
    out.add(new Subdivision("PH-AGS", "Agusan del Sur", "PH-13", "Province"));
    out.add(new Subdivision("PH-AKL", "Aklan", "PH-06", "Province"));
    out.add(new Subdivision("PH-ALB", "Albay", "PH-05", "Province"));
    out.add(new Subdivision("PH-ANT", "Antique", "PH-06", "Province"));
    out.add(new Subdivision("PH-APA", "Apayao", "PH-15", "Province"));
    out.add(new Subdivision("PH-AUR", "Aurora", "PH-03", "Province"));
    out.add(new Subdivision("PH-BAN", "Bataan", "PH-03", "Province"));
    out.add(new Subdivision("PH-BAS", "Basilan", "PH-09", "Province"));
    out.add(new Subdivision("PH-BEN", "Benguet", "PH-15", "Province"));
    out.add(new Subdivision("PH-BIL", "Biliran", "PH-08", "Province"));
    out.add(new Subdivision("PH-BOH", "Bohol", "PH-07", "Province"));
    out.add(new Subdivision("PH-BTG", "Batangas", "PH-40", "Province"));
    out.add(new Subdivision("PH-BTN", "Batanes", "PH-02", "Province"));
    out.add(new Subdivision("PH-BUK", "Bukidnon", "PH-10", "Province"));
    out.add(new Subdivision("PH-BUL", "Bulacan", "PH-03", "Province"));
    out.add(new Subdivision("PH-CAG", "Cagayan", "PH-02", "Province"));
    out.add(new Subdivision("PH-CAM", "Camiguin", "PH-10", "Province"));
    out.add(new Subdivision("PH-CAN", "Camarines Norte", "PH-05", "Province"));
    out.add(new Subdivision("PH-CAP", "Capiz", "PH-06", "Province"));
    out.add(new Subdivision("PH-CAS", "Camarines Sur", "PH-05", "Province"));
    out.add(new Subdivision("PH-CAT", "Catanduanes", "PH-05", "Province"));
    out.add(new Subdivision("PH-CAV", "Cavite", "PH-40", "Province"));
    out.add(new Subdivision("PH-CEB", "Cebu", "PH-07", "Province"));
    out.add(new Subdivision("PH-COM", "Davao de Oro", "PH-11", "Province"));
    out.add(new Subdivision("PH-DAO", "Davao Oriental", "PH-11", "Province"));
    out.add(new Subdivision("PH-DAS", "Davao del Sur", "PH-11", "Province"));
    out.add(new Subdivision("PH-DAV", "Davao del Norte", "PH-11", "Province"));
    out.add(new Subdivision("PH-DIN", "Dinagat Islands", "PH-13", "Province"));
    out.add(new Subdivision("PH-DVO", "Davao Occidental", "PH-11", "Province"));
    out.add(new Subdivision("PH-EAS", "Eastern Samar", "PH-08", "Province"));
    out.add(new Subdivision("PH-GUI", "Guimaras", "PH-06", "Province"));
    out.add(new Subdivision("PH-IFU", "Ifugao", "PH-15", "Province"));
    out.add(new Subdivision("PH-ILI", "Iloilo", "PH-06", "Province"));
    out.add(new Subdivision("PH-ILN", "Ilocos Norte", "PH-01", "Province"));
    out.add(new Subdivision("PH-ILS", "Ilocos Sur", "PH-01", "Province"));
    out.add(new Subdivision("PH-ISA", "Isabela", "PH-02", "Province"));
    out.add(new Subdivision("PH-KAL", "Kalinga", "PH-15", "Province"));
    out.add(new Subdivision("PH-LAG", "Laguna", "PH-40", "Province"));
    out.add(new Subdivision("PH-LAN", "Lanao del Norte", "PH-12", "Province"));
    out.add(new Subdivision("PH-LAS", "Lanao del Sur", "PH-14", "Province"));
    out.add(new Subdivision("PH-LEY", "Leyte", "PH-08", "Province"));
    out.add(new Subdivision("PH-LUN", "La Union", "PH-01", "Province"));
    out.add(new Subdivision("PH-MAD", "Marinduque", "PH-41", "Province"));
    out.add(new Subdivision("PH-MAS", "Masbate", "PH-05", "Province"));
    out.add(new Subdivision("PH-MDC", "Mindoro Occidental", "PH-41", "Province"));
    out.add(new Subdivision("PH-MDR", "Mindoro Oriental", "PH-41", "Province"));
    out.add(new Subdivision("PH-MGN", "Maguindanao del Norte", "PH-14", "Province"));
    out.add(new Subdivision("PH-MGS", "Maguindanao del Sur", "PH-14", "Province"));
    out.add(new Subdivision("PH-MOU", "Mountain Province", "PH-15", "Province"));
    out.add(new Subdivision("PH-MSC", "Misamis Occidental", "PH-10", "Province"));
    out.add(new Subdivision("PH-MSR", "Misamis Oriental", "PH-10", "Province"));
    out.add(new Subdivision("PH-NCO", "Cotabato", "PH-12", "Province"));
    out.add(new Subdivision("PH-NEC", "Negros Occidental", "PH-06", "Province"));
    out.add(new Subdivision("PH-NER", "Negros Oriental", "PH-07", "Province"));
    out.add(new Subdivision("PH-NSA", "Northern Samar", "PH-08", "Province"));
    out.add(new Subdivision("PH-NUE", "Nueva Ecija", "PH-03", "Province"));
    out.add(new Subdivision("PH-NUV", "Nueva Vizcaya", "PH-02", "Province"));
    out.add(new Subdivision("PH-PAM", "Pampanga", "PH-03", "Province"));
    out.add(new Subdivision("PH-PAN", "Pangasinan", "PH-01", "Province"));
    out.add(new Subdivision("PH-PLW", "Palawan", "PH-41", "Province"));
    out.add(new Subdivision("PH-QUE", "Quezon", "PH-40", "Province"));
    out.add(new Subdivision("PH-QUI", "Quirino", "PH-02", "Province"));
    out.add(new Subdivision("PH-RIZ", "Rizal", "PH-40", "Province"));
    out.add(new Subdivision("PH-ROM", "Romblon", "PH-41", "Province"));
    out.add(new Subdivision("PH-SAR", "Sarangani", "PH-11", "Province"));
    out.add(new Subdivision("PH-SCO", "South Cotabato", "PH-11", "Province"));
    out.add(new Subdivision("PH-SIG", "Siquijor", "PH-07", "Province"));
    out.add(new Subdivision("PH-SLE", "Southern Leyte", "PH-08", "Province"));
    out.add(new Subdivision("PH-SLU", "Sulu", "PH-14", "Province"));
    out.add(new Subdivision("PH-SOR", "Sorsogon", "PH-05", "Province"));
    out.add(new Subdivision("PH-SUK", "Sultan Kudarat", "PH-12", "Province"));
    out.add(new Subdivision("PH-SUN", "Surigao del Norte", "PH-13", "Province"));
    out.add(new Subdivision("PH-SUR", "Surigao del Sur", "PH-13", "Province"));
    out.add(new Subdivision("PH-TAR", "Tarlac", "PH-03", "Province"));
    out.add(new Subdivision("PH-TAW", "Tawi-Tawi", "PH-14", "Province"));
    out.add(new Subdivision("PH-WSA", "Samar", "PH-08", "Province"));
    out.add(new Subdivision("PH-ZAN", "Zamboanga del Norte", "PH-09", "Province"));
    out.add(new Subdivision("PH-ZAS", "Zamboanga del Sur", "PH-09", "Province"));
    out.add(new Subdivision("PH-ZMB", "Zambales", "PH-03", "Province"));
    out.add(new Subdivision("PH-ZSI", "Zamboanga Sibugay", "PH-09", "Province"));
    out.add(new Subdivision("PK-BA", "Balochistan", null, "Province"));
    out.add(new Subdivision("PK-GB", "Gilgit-Baltistan", null, "Pakistan administered area"));
    out.add(new Subdivision("PK-IS", "Islamabad", null, "Federal capital territory"));
    out.add(new Subdivision("PK-JK", "Azad Jammu and Kashmir", null, "Pakistan administered area"));
    out.add(new Subdivision("PK-KP", "Khyber Pakhtunkhwa", null, "Province"));
    out.add(new Subdivision("PK-PB", "Punjab", null, "Province"));
    out.add(new Subdivision("PK-SD", "Sindh", null, "Province"));
    out.add(new Subdivision("PL-02", "Dolnośląskie", null, "Voivodship"));
    out.add(new Subdivision("PL-04", "Kujawsko-Pomorskie", null, "Voivodship"));
    out.add(new Subdivision("PL-06", "Lubelskie", null, "Voivodship"));
    out.add(new Subdivision("PL-08", "Lubuskie", null, "Voivodship"));
    out.add(new Subdivision("PL-10", "Łódzkie", null, "Voivodship"));
    out.add(new Subdivision("PL-12", "Małopolskie", null, "Voivodship"));
    out.add(new Subdivision("PL-14", "Mazowieckie", null, "Voivodship"));
    out.add(new Subdivision("PL-16", "Opolskie", null, "Voivodship"));
    out.add(new Subdivision("PL-18", "Podkarpackie", null, "Voivodship"));
    out.add(new Subdivision("PL-20", "Podlaskie", null, "Voivodship"));
    out.add(new Subdivision("PL-22", "Pomorskie", null, "Voivodship"));
    out.add(new Subdivision("PL-24", "Śląskie", null, "Voivodship"));
    out.add(new Subdivision("PL-26", "Świętokrzyskie", null, "Voivodship"));
    out.add(new Subdivision("PL-28", "Warmińsko-Mazurskie", null, "Voivodship"));
    out.add(new Subdivision("PL-30", "Wielkopolskie", null, "Voivodship"));
    out.add(new Subdivision("PL-32", "Zachodniopomorskie", null, "Voivodship"));
    out.add(new Subdivision("PS-BTH", "Bethlehem", null, "Governorate"));
    out.add(new Subdivision("PS-DEB", "Deir El Balah", null, "Governorate"));
    out.add(new Subdivision("PS-GZA", "Gaza", null, "Governorate"));
    out.add(new Subdivision("PS-HBN", "Hebron", null, "Governorate"));
    out.add(new Subdivision("PS-JEM", "Jerusalem", null, "Governorate"));
    out.add(new Subdivision("PS-JEN", "Jenin", null, "Governorate"));
    out.add(new Subdivision("PS-JRH", "Jericho and Al Aghwar", null, "Governorate"));
    out.add(new Subdivision("PS-KYS", "Khan Yunis", null, "Governorate"));
    out.add(new Subdivision("PS-NBS", "Nablus", null, "Governorate"));
    out.add(new Subdivision("PS-NGZ", "North Gaza", null, "Governorate"));
    out.add(new Subdivision("PS-QQA", "Qalqilya", null, "Governorate"));
    out.add(new Subdivision("PS-RBH", "Ramallah", null, "Governorate"));
    out.add(new Subdivision("PS-RFH", "Rafah", null, "Governorate"));
    out.add(new Subdivision("PS-SLT", "Salfit", null, "Governorate"));
    out.add(new Subdivision("PS-TBS", "Tubas", null, "Governorate"));
    out.add(new Subdivision("PS-TKM", "Tulkarm", null, "Governorate"));
    out.add(new Subdivision("PT-01", "Aveiro", null, "District"));
    out.add(new Subdivision("PT-02", "Beja", null, "District"));
    out.add(new Subdivision("PT-03", "Braga", null, "District"));
    out.add(new Subdivision("PT-04", "Bragança", null, "District"));
    out.add(new Subdivision("PT-05", "Castelo Branco", null, "District"));
    out.add(new Subdivision("PT-06", "Coimbra", null, "District"));
    out.add(new Subdivision("PT-07", "Évora", null, "District"));
    out.add(new Subdivision("PT-08", "Faro", null, "District"));
    out.add(new Subdivision("PT-09", "Guarda", null, "District"));
    out.add(new Subdivision("PT-10", "Leiria", null, "District"));
    out.add(new Subdivision("PT-11", "Lisboa", null, "District"));
    out.add(new Subdivision("PT-12", "Portalegre", null, "District"));
    out.add(new Subdivision("PT-13", "Porto", null, "District"));
    out.add(new Subdivision("PT-14", "Santarém", null, "District"));
    out.add(new Subdivision("PT-15", "Setúbal", null, "District"));
    out.add(new Subdivision("PT-16", "Viana do Castelo", null, "District"));
    out.add(new Subdivision("PT-17", "Vila Real", null, "District"));
    out.add(new Subdivision("PT-18", "Viseu", null, "District"));
    out.add(new Subdivision("PT-20", "Região Autónoma dos Açores", null, "Autonomous region"));
    out.add(new Subdivision("PT-30", "Região Autónoma da Madeira", null, "Autonomous region"));
    out.add(new Subdivision("PW-002", "Aimeliik", null, "State"));
    out.add(new Subdivision("PW-004", "Airai", null, "State"));
    out.add(new Subdivision("PW-010", "Angaur", null, "State"));
    out.add(new Subdivision("PW-050", "Hatohobei", null, "State"));
    out.add(new Subdivision("PW-100", "Kayangel", null, "State"));
    out.add(new Subdivision("PW-150", "Koror", null, "State"));
    out.add(new Subdivision("PW-212", "Melekeok", null, "State"));
    out.add(new Subdivision("PW-214", "Ngaraard", null, "State"));
    out.add(new Subdivision("PW-218", "Ngarchelong", null, "State"));
    out.add(new Subdivision("PW-222", "Ngardmau", null, "State"));
    out.add(new Subdivision("PW-224", "Ngatpang", null, "State"));
    out.add(new Subdivision("PW-226", "Ngchesar", null, "State"));
    out.add(new Subdivision("PW-227", "Ngeremlengui", null, "State"));
    out.add(new Subdivision("PW-228", "Ngiwal", null, "State"));
    out.add(new Subdivision("PW-350", "Peleliu", null, "State"));
    out.add(new Subdivision("PW-370", "Sonsorol", null, "State"));
    out.add(new Subdivision("PY-1", "Concepción", null, "Department"));
    out.add(new Subdivision("PY-10", "Alto Paraná", null, "Department"));
    out.add(new Subdivision("PY-11", "Central", null, "Department"));
    out.add(new Subdivision("PY-12", "Ñeembucú", null, "Department"));
    out.add(new Subdivision("PY-13", "Amambay", null, "Department"));
    out.add(new Subdivision("PY-14", "Canindeyú", null, "Department"));
    out.add(new Subdivision("PY-15", "Presidente Hayes", null, "Department"));
    out.add(new Subdivision("PY-16", "Alto Paraguay", null, "Department"));
    out.add(new Subdivision("PY-19", "Boquerón", null, "Department"));
    out.add(new Subdivision("PY-2", "San Pedro", null, "Department"));
    out.add(new Subdivision("PY-3", "Cordillera", null, "Department"));
    out.add(new Subdivision("PY-4", "Guairá", null, "Department"));
    out.add(new Subdivision("PY-5", "Caaguazú", null, "Department"));
    out.add(new Subdivision("PY-6", "Caazapá", null, "Department"));
    out.add(new Subdivision("PY-7", "Itapúa", null, "Department"));
    out.add(new Subdivision("PY-8", "Misiones", null, "Department"));
    out.add(new Subdivision("PY-9", "Paraguarí", null, "Department"));
    out.add(new Subdivision("PY-ASU", "Asunción", null, "Capital"));
    out.add(new Subdivision("QA-DA", "Ad Dawḩah", null, "Municipality"));
    out.add(new Subdivision("QA-KH", "Al Khawr wa adh Dhakhīrah", null, "Municipality"));
    out.add(new Subdivision("QA-MS", "Ash Shamāl", null, "Municipality"));
    out.add(new Subdivision("QA-RA", "Ar Rayyān", null, "Municipality"));
    out.add(new Subdivision("QA-SH", "Ash Shīḩānīyah", null, "Municipality"));
    out.add(new Subdivision("QA-US", "Umm Şalāl", null, "Municipality"));
    out.add(new Subdivision("QA-WA", "Al Wakrah", null, "Municipality"));
    out.add(new Subdivision("QA-ZA", "Az̧ Z̧a‘āyin", null, "Municipality"));
    out.add(new Subdivision("RO-AB", "Alba", null, "Department"));
    out.add(new Subdivision("RO-AG", "Argeș", null, "Department"));
    out.add(new Subdivision("RO-AR", "Arad", null, "Department"));
    out.add(new Subdivision("RO-B", "București", null, "Municipality"));
    out.add(new Subdivision("RO-BC", "Bacău", null, "Department"));
    out.add(new Subdivision("RO-BH", "Bihor", null, "Department"));
    out.add(new Subdivision("RO-BN", "Bistrița-Năsăud", null, "Department"));
    out.add(new Subdivision("RO-BR", "Brăila", null, "Department"));
    out.add(new Subdivision("RO-BT", "Botoșani", null, "Department"));
    out.add(new Subdivision("RO-BV", "Brașov", null, "Department"));
    out.add(new Subdivision("RO-BZ", "Buzău", null, "Department"));
    out.add(new Subdivision("RO-CJ", "Cluj", null, "Department"));
    out.add(new Subdivision("RO-CL", "Călărași", null, "Department"));
    out.add(new Subdivision("RO-CS", "Caraș-Severin", null, "Department"));
    out.add(new Subdivision("RO-CT", "Constanța", null, "Department"));
    out.add(new Subdivision("RO-CV", "Covasna", null, "Department"));
    out.add(new Subdivision("RO-DB", "Dâmbovița", null, "Department"));
    out.add(new Subdivision("RO-DJ", "Dolj", null, "Department"));
    out.add(new Subdivision("RO-GJ", "Gorj", null, "Department"));
    out.add(new Subdivision("RO-GL", "Galați", null, "Department"));
    out.add(new Subdivision("RO-GR", "Giurgiu", null, "Department"));
    out.add(new Subdivision("RO-HD", "Hunedoara", null, "Department"));
    out.add(new Subdivision("RO-HR", "Harghita", null, "Department"));
    out.add(new Subdivision("RO-IF", "Ilfov", null, "Department"));
    out.add(new Subdivision("RO-IL", "Ialomița", null, "Department"));
    out.add(new Subdivision("RO-IS", "Iași", null, "Department"));
    out.add(new Subdivision("RO-MH", "Mehedinți", null, "Department"));
    out.add(new Subdivision("RO-MM", "Maramureș", null, "Department"));
    out.add(new Subdivision("RO-MS", "Mureș", null, "Department"));
    out.add(new Subdivision("RO-NT", "Neamț", null, "Department"));
    out.add(new Subdivision("RO-OT", "Olt", null, "Department"));
    out.add(new Subdivision("RO-PH", "Prahova", null, "Department"));
    out.add(new Subdivision("RO-SB", "Sibiu", null, "Department"));
    out.add(new Subdivision("RO-SJ", "Sălaj", null, "Department"));
    out.add(new Subdivision("RO-SM", "Satu Mare", null, "Department"));
    out.add(new Subdivision("RO-SV", "Suceava", null, "Department"));
    out.add(new Subdivision("RO-TL", "Tulcea", null, "Department"));
    out.add(new Subdivision("RO-TM", "Timiș", null, "Department"));
    out.add(new Subdivision("RO-TR", "Teleorman", null, "Department"));
    out.add(new Subdivision("RO-VL", "Vâlcea", null, "Department"));
    out.add(new Subdivision("RO-VN", "Vrancea", null, "Department"));
    out.add(new Subdivision("RO-VS", "Vaslui", null, "Department"));
    out.add(new Subdivision("RS-00", "Beograd", null, "City"));
    out.add(new Subdivision("RS-01", "Severnobački okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-02", "Srednjebanatski okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-03", "Severnobanatski okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-04", "Južnobanatski okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-05", "Zapadnobački okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-06", "Južnobački okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-07", "Sremski okrug", "RS-VO", "District"));
    out.add(new Subdivision("RS-08", "Mačvanski okrug", null, "District"));
    out.add(new Subdivision("RS-09", "Kolubarski okrug", null, "District"));
    out.add(new Subdivision("RS-10", "Podunavski okrug", null, "District"));
    out.add(new Subdivision("RS-11", "Braničevski okrug", null, "District"));
    out.add(new Subdivision("RS-12", "Šumadijski okrug", null, "District"));
    out.add(new Subdivision("RS-13", "Pomoravski okrug", null, "District"));
    out.add(new Subdivision("RS-14", "Borski okrug", null, "District"));
    out.add(new Subdivision("RS-15", "Zaječarski okrug", null, "District"));
    out.add(new Subdivision("RS-16", "Zlatiborski okrug", null, "District"));
    out.add(new Subdivision("RS-17", "Moravički okrug", null, "District"));
    out.add(new Subdivision("RS-18", "Raški okrug", null, "District"));
    out.add(new Subdivision("RS-19", "Rasinski okrug", null, "District"));
    out.add(new Subdivision("RS-20", "Nišavski okrug", null, "District"));
    out.add(new Subdivision("RS-21", "Toplički okrug", null, "District"));
    out.add(new Subdivision("RS-22", "Pirotski okrug", null, "District"));
    out.add(new Subdivision("RS-23", "Jablanički okrug", null, "District"));
    out.add(new Subdivision("RS-24", "Pčinjski okrug", null, "District"));
    out.add(new Subdivision("RS-25", "Kosovski okrug", "RS-KM", "District"));
    out.add(new Subdivision("RS-26", "Pećki okrug", "RS-KM", "District"));
    out.add(new Subdivision("RS-27", "Prizrenski okrug", "RS-KM", "District"));
    out.add(new Subdivision("RS-28", "Kosovsko-Mitrovački okrug", "RS-KM", "District"));
    out.add(new Subdivision("RS-29", "Kosovsko-Pomoravski okrug", "RS-KM", "District"));
    out.add(new Subdivision("RS-KM", "Kosovo-Metohija", null, "Autonomous province"));
    out.add(new Subdivision("RS-VO", "Vojvodina", null, "Autonomous province"));
    out.add(new Subdivision("RU-AD", "Adygeya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-AL", "Altay, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-ALT", "Altayskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-AMU", "Amurskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-ARK", "Arkhangel'skaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-AST", "Astrakhanskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-BA", "Bashkortostan, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-BEL", "Belgorodskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-BRY", "Bryanskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-BU", "Buryatiya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-CE", "Chechenskaya Respublika", null, "Republic"));
    out.add(new Subdivision("RU-CHE", "Chelyabinskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-CHU", "Chukotskiy avtonomnyy okrug", null, "Autonomous district"));
    out.add(new Subdivision("RU-CU", "Chuvashskaya Respublika", null, "Republic"));
    out.add(new Subdivision("RU-DA", "Dagestan, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-IN", "Ingushetiya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-IRK", "Irkutskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-IVA", "Ivanovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KAM", "Kamchatskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-KB", "Kabardino-Balkarskaya Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KC", "Karachayevo-Cherkesskaya Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KDA", "Krasnodarskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-KEM", "Kemerovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KGD", "Kaliningradskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KGN", "Kurganskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KHA", "Khabarovskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-KHM", "Khanty-Mansiyskiy avtonomnyy okrug", null, "Autonomous district"));
    out.add(new Subdivision("RU-KIR", "Kirovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KK", "Khakasiya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KL", "Kalmykiya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KLU", "Kaluzhskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KO", "Komi, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KOS", "Kostromskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KR", "Kareliya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-KRS", "Kurskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-KYA", "Krasnoyarskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-LEN", "Leningradskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-LIP", "Lipetskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-MAG", "Magadanskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-ME", "Mariy El, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-MO", "Mordoviya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-MOS", "Moskovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-MOW", "Moskva", null, "Autonomous city"));
    out.add(new Subdivision("RU-MUR", "Murmanskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-NEN", "Nenetskiy avtonomnyy okrug", null, "Autonomous district"));
    out.add(new Subdivision("RU-NGR", "Novgorodskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-NIZ", "Nizhegorodskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-NVS", "Novosibirskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-OMS", "Omskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-ORE", "Orenburgskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-ORL", "Orlovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-PER", "Permskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-PNZ", "Penzenskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-PRI", "Primorskiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-PSK", "Pskovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-ROS", "Rostovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-RYA", "Ryazanskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-SA", "Saha, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-SAK", "Sakhalinskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-SAM", "Samarskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-SAR", "Saratovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-SE", "Severnaya Osetiya, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-SMO", "Smolenskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-SPE", "Sankt-Peterburg", null, "Autonomous city"));
    out.add(new Subdivision("RU-STA", "Stavropol'skiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RU-SVE", "Sverdlovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-TA", "Tatarstan, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-TAM", "Tambovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-TOM", "Tomskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-TUL", "Tul'skaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-TVE", "Tverskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-TY", "Tyva, Respublika", null, "Republic"));
    out.add(new Subdivision("RU-TYU", "Tyumenskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-UD", "Udmurtskaya Respublika", null, "Republic"));
    out.add(new Subdivision("RU-ULY", "Ul'yanovskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-VGG", "Volgogradskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-VLA", "Vladimirskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-VLG", "Vologodskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-VOR", "Voronezhskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-YAN", "Yamalo-Nenetskiy avtonomnyy okrug", null, "Autonomous district"));
    out.add(new Subdivision("RU-YAR", "Yaroslavskaya oblast'", null, "Administrative region"));
    out.add(new Subdivision("RU-YEV", "Yevreyskaya avtonomnaya oblast'", null, "Autonomous region"));
    out.add(new Subdivision("RU-ZAB", "Zabaykal'skiy kray", null, "Administrative territory"));
    out.add(new Subdivision("RW-01", "City of Kigali", null, "City"));
    out.add(new Subdivision("RW-02", "Eastern", null, "Province"));
    out.add(new Subdivision("RW-03", "Northern", null, "Province"));
    out.add(new Subdivision("RW-04", "Western", null, "Province"));
    out.add(new Subdivision("RW-05", "Southern", null, "Province"));
    out.add(new Subdivision("SA-01", "Ar Riyāḑ", null, "Region"));
    out.add(new Subdivision("SA-02", "Makkah al Mukarramah", null, "Region"));
    out.add(new Subdivision("SA-03", "Al Madīnah al Munawwarah", null, "Region"));
    out.add(new Subdivision("SA-04", "Ash Sharqīyah", null, "Region"));
    out.add(new Subdivision("SA-05", "Al Qaşīm", null, "Region"));
    out.add(new Subdivision("SA-06", "Ḩā'il", null, "Region"));
    out.add(new Subdivision("SA-07", "Tabūk", null, "Region"));
    out.add(new Subdivision("SA-08", "Al Ḩudūd ash Shamālīyah", null, "Region"));
    out.add(new Subdivision("SA-09", "Jāzān", null, "Region"));
    out.add(new Subdivision("SA-10", "Najrān", null, "Region"));
    out.add(new Subdivision("SA-11", "Al Bāḩah", null, "Region"));
    out.add(new Subdivision("SA-12", "Al Jawf", null, "Region"));
    out.add(new Subdivision("SA-14", "'Asīr", null, "Region"));
    out.add(new Subdivision("SB-CE", "Central", null, "Province"));
    out.add(new Subdivision("SB-CH", "Choiseul", null, "Province"));
    out.add(new Subdivision("SB-CT", "Capital Territory (Honiara)", null, "Capital territory"));
    out.add(new Subdivision("SB-GU", "Guadalcanal", null, "Province"));
    out.add(new Subdivision("SB-IS", "Isabel", null, "Province"));
    out.add(new Subdivision("SB-MK", "Makira-Ulawa", null, "Province"));
    out.add(new Subdivision("SB-ML", "Malaita", null, "Province"));
    out.add(new Subdivision("SB-RB", "Rennell and Bellona", null, "Province"));
    out.add(new Subdivision("SB-TE", "Temotu", null, "Province"));
    out.add(new Subdivision("SB-WE", "Western", null, "Province"));
    out.add(new Subdivision("SC-01", "Anse aux Pins", null, "District"));
    out.add(new Subdivision("SC-02", "Anse Boileau", null, "District"));
    out.add(new Subdivision("SC-03", "Anse Etoile", null, "District"));
    out.add(new Subdivision("SC-04", "Au Cap", null, "District"));
    out.add(new Subdivision("SC-05", "Anse Royale", null, "District"));
    out.add(new Subdivision("SC-06", "Baie Lazare", null, "District"));
    out.add(new Subdivision("SC-07", "Baie Sainte Anne", null, "District"));
    out.add(new Subdivision("SC-08", "Beau Vallon", null, "District"));
    out.add(new Subdivision("SC-09", "Bel Air", null, "District"));
    out.add(new Subdivision("SC-10", "Bel Ombre", null, "District"));
    out.add(new Subdivision("SC-11", "Cascade", null, "District"));
    out.add(new Subdivision("SC-12", "Glacis", null, "District"));
    out.add(new Subdivision("SC-13", "Grand Anse Mahe", null, "District"));
    out.add(new Subdivision("SC-14", "Grand Anse Praslin", null, "District"));
    out.add(new Subdivision("SC-15", "La Digue", null, "District"));
    out.add(new Subdivision("SC-16", "English River", null, "District"));
    out.add(new Subdivision("SC-17", "Mont Buxton", null, "District"));
    out.add(new Subdivision("SC-18", "Mont Fleuri", null, "District"));
    out.add(new Subdivision("SC-19", "Plaisance", null, "District"));
    out.add(new Subdivision("SC-20", "Pointe Larue", null, "District"));
    out.add(new Subdivision("SC-21", "Port Glaud", null, "District"));
    out.add(new Subdivision("SC-22", "Saint Louis", null, "District"));
    out.add(new Subdivision("SC-23", "Takamaka", null, "District"));
    out.add(new Subdivision("SC-24", "Les Mamelles", null, "District"));
    out.add(new Subdivision("SC-25", "Roche Caiman", null, "District"));
    out.add(new Subdivision("SC-26", "Ile Perseverance I", null, "District"));
    out.add(new Subdivision("SC-27", "Ile Perseverance II", null, "District"));
    out.add(new Subdivision("SD-DC", "Central Darfur", null, "State"));
    out.add(new Subdivision("SD-DE", "East Darfur", null, "State"));
    out.add(new Subdivision("SD-DN", "North Darfur", null, "State"));
    out.add(new Subdivision("SD-DS", "South Darfur", null, "State"));
    out.add(new Subdivision("SD-DW", "West Darfur", null, "State"));
    out.add(new Subdivision("SD-GD", "Gedaref", null, "State"));
    out.add(new Subdivision("SD-GK", "West Kordofan", null, "State"));
    out.add(new Subdivision("SD-GZ", "Gezira", null, "State"));
    out.add(new Subdivision("SD-KA", "Kassala", null, "State"));
    out.add(new Subdivision("SD-KH", "Khartoum", null, "State"));
    out.add(new Subdivision("SD-KN", "North Kordofan", null, "State"));
    out.add(new Subdivision("SD-KS", "South Kordofan", null, "State"));
    out.add(new Subdivision("SD-NB", "Blue Nile", null, "State"));
    out.add(new Subdivision("SD-NO", "Northern", null, "State"));
    out.add(new Subdivision("SD-NR", "River Nile", null, "State"));
    out.add(new Subdivision("SD-NW", "White Nile", null, "State"));
    out.add(new Subdivision("SD-RS", "Red Sea", null, "State"));
    out.add(new Subdivision("SD-SI", "Sennar", null, "State"));
    out.add(new Subdivision("SE-AB", "Stockholms län [SE-01]", null, "County"));
    out.add(new Subdivision("SE-AC", "Västerbottens län [SE-24]", null, "County"));
    out.add(new Subdivision("SE-BD", "Norrbottens län [SE-25]", null, "County"));
    out.add(new Subdivision("SE-C", "Uppsala län [SE-03]", null, "County"));
    out.add(new Subdivision("SE-D", "Södermanlands län [SE-04]", null, "County"));
    out.add(new Subdivision("SE-E", "Östergötlands län [SE-05]", null, "County"));
    out.add(new Subdivision("SE-F", "Jönköpings län [SE-06]", null, "County"));
    out.add(new Subdivision("SE-G", "Kronobergs län [SE-07]", null, "County"));
    out.add(new Subdivision("SE-H", "Kalmar län [SE-08]", null, "County"));
    out.add(new Subdivision("SE-I", "Gotlands län [SE-09]", null, "County"));
    out.add(new Subdivision("SE-K", "Blekinge län [SE-10]", null, "County"));
    out.add(new Subdivision("SE-M", "Skåne län [SE-12]", null, "County"));
    out.add(new Subdivision("SE-N", "Hallands län [SE-13]", null, "County"));
    out.add(new Subdivision("SE-O", "Västra Götalands län [SE-14]", null, "County"));
    out.add(new Subdivision("SE-S", "Värmlands län [SE-17]", null, "County"));
    out.add(new Subdivision("SE-T", "Örebro län [SE-18]", null, "County"));
    out.add(new Subdivision("SE-U", "Västmanlands län [SE-19]", null, "County"));
    out.add(new Subdivision("SE-W", "Dalarnas län [SE-20]", null, "County"));
    out.add(new Subdivision("SE-X", "Gävleborgs län [SE-21]", null, "County"));
    out.add(new Subdivision("SE-Y", "Västernorrlands län [SE-22]", null, "County"));
    out.add(new Subdivision("SE-Z", "Jämtlands län [SE-23]", null, "County"));
    out.add(new Subdivision("SG-01", "Central Singapore", null, "District"));
    out.add(new Subdivision("SG-02", "North East", null, "District"));
    out.add(new Subdivision("SG-03", "North West", null, "District"));
    out.add(new Subdivision("SG-04", "South East", null, "District"));
    out.add(new Subdivision("SG-05", "South West", null, "District"));
    out.add(new Subdivision("SH-AC", "Ascension", null, "Geographical entity"));
    out.add(new Subdivision("SH-HL", "Saint Helena", null, "Geographical entity"));
    out.add(new Subdivision("SH-TA", "Tristan da Cunha", null, "Geographical entity"));
    out.add(new Subdivision("SI-001", "Ajdovščina", null, "Municipality"));
    out.add(new Subdivision("SI-002", "Beltinci", null, "Municipality"));
    out.add(new Subdivision("SI-003", "Bled", null, "Municipality"));
    out.add(new Subdivision("SI-004", "Bohinj", null, "Municipality"));
    out.add(new Subdivision("SI-005", "Borovnica", null, "Municipality"));
    out.add(new Subdivision("SI-006", "Bovec", null, "Municipality"));
    out.add(new Subdivision("SI-007", "Brda", null, "Municipality"));
    out.add(new Subdivision("SI-008", "Brezovica", null, "Municipality"));
    out.add(new Subdivision("SI-009", "Brežice", null, "Municipality"));
    out.add(new Subdivision("SI-010", "Tišina", null, "Municipality"));
    out.add(new Subdivision("SI-011", "Celje", null, "Urban municipality"));
    out.add(new Subdivision("SI-012", "Cerklje na Gorenjskem", null, "Municipality"));
    out.add(new Subdivision("SI-013", "Cerknica", null, "Municipality"));
    out.add(new Subdivision("SI-014", "Cerkno", null, "Municipality"));
    out.add(new Subdivision("SI-015", "Črenšovci", null, "Municipality"));
    out.add(new Subdivision("SI-016", "Črna na Koroškem", null, "Municipality"));
    out.add(new Subdivision("SI-017", "Črnomelj", null, "Municipality"));
    out.add(new Subdivision("SI-018", "Destrnik", null, "Municipality"));
    out.add(new Subdivision("SI-019", "Divača", null, "Municipality"));
    out.add(new Subdivision("SI-020", "Dobrepolje", null, "Municipality"));
    out.add(new Subdivision("SI-021", "Dobrova-Polhov Gradec", null, "Municipality"));
    out.add(new Subdivision("SI-022", "Dol pri Ljubljani", null, "Municipality"));
    out.add(new Subdivision("SI-023", "Domžale", null, "Municipality"));
    out.add(new Subdivision("SI-024", "Dornava", null, "Municipality"));
    out.add(new Subdivision("SI-025", "Dravograd", null, "Municipality"));
  }
}
