// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 3000 to 3499 of {@link Subdivision}.
 */
final class SubdivisionData6 {
  private SubdivisionData6() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("MK-408", "Novo Selo", null, "Municipality"));
    out.add(new Subdivision("MK-409", "Radoviš", null, "Municipality"));
    out.add(new Subdivision("MK-410", "Strumica", null, "Municipality"));
    out.add(new Subdivision("MK-501", "Bitola", null, "Municipality"));
    out.add(new Subdivision("MK-502", "Demir Hisar", null, "Municipality"));
    out.add(new Subdivision("MK-503", "Dolneni", null, "Municipality"));
    out.add(new Subdivision("MK-504", "Krivogaštani", null, "Municipality"));
    out.add(new Subdivision("MK-505", "Kruševo", null, "Municipality"));
    out.add(new Subdivision("MK-506", "Mogila", null, "Municipality"));
    out.add(new Subdivision("MK-507", "Novaci", null, "Municipality"));
    out.add(new Subdivision("MK-508", "Prilep", null, "Municipality"));
    out.add(new Subdivision("MK-509", "Resen", null, "Municipality"));
    out.add(new Subdivision("MK-601", "Bogovinje", null, "Municipality"));
    out.add(new Subdivision("MK-602", "Brvenica", null, "Municipality"));
    out.add(new Subdivision("MK-603", "Vrapčište", null, "Municipality"));
    out.add(new Subdivision("MK-604", "Gostivar", null, "Municipality"));
    out.add(new Subdivision("MK-605", "Želino", null, "Municipality"));
    out.add(new Subdivision("MK-606", "Jegunovce", null, "Municipality"));
    out.add(new Subdivision("MK-607", "Mavrovo i Rostuše", null, "Municipality"));
    out.add(new Subdivision("MK-608", "Tearce", null, "Municipality"));
    out.add(new Subdivision("MK-609", "Tetovo", null, "Municipality"));
    out.add(new Subdivision("MK-701", "Kratovo", null, "Municipality"));
    out.add(new Subdivision("MK-702", "Kriva Palanka", null, "Municipality"));
    out.add(new Subdivision("MK-703", "Kumanovo", null, "Municipality"));
    out.add(new Subdivision("MK-704", "Lipkovo", null, "Municipality"));
    out.add(new Subdivision("MK-705", "Rankovce", null, "Municipality"));
    out.add(new Subdivision("MK-706", "Staro Nagoričane", null, "Municipality"));
    out.add(new Subdivision("MK-801", "Aerodrom †", null, "Municipality"));
    out.add(new Subdivision("MK-802", "Aračinovo", null, "Municipality"));
    out.add(new Subdivision("MK-803", "Butel †", null, "Municipality"));
    out.add(new Subdivision("MK-804", "Gazi Baba †", null, "Municipality"));
    out.add(new Subdivision("MK-805", "Gjorče Petrov †", null, "Municipality"));
    out.add(new Subdivision("MK-806", "Zelenikovo", null, "Municipality"));
    out.add(new Subdivision("MK-807", "Ilinden", null, "Municipality"));
    out.add(new Subdivision("MK-808", "Karpoš †", null, "Municipality"));
    out.add(new Subdivision("MK-809", "Kisela Voda †", null, "Municipality"));
    out.add(new Subdivision("MK-810", "Petrovec", null, "Municipality"));
    out.add(new Subdivision("MK-811", "Saraj †", null, "Municipality"));
    out.add(new Subdivision("MK-812", "Sopište", null, "Municipality"));
    out.add(new Subdivision("MK-813", "Studeničani", null, "Municipality"));
    out.add(new Subdivision("MK-814", "Centar †", null, "Municipality"));
    out.add(new Subdivision("MK-815", "Čair †", null, "Municipality"));
    out.add(new Subdivision("MK-816", "Čučer-Sandevo", null, "Municipality"));
    out.add(new Subdivision("MK-817", "Šuto Orizari †", null, "Municipality"));
    out.add(new Subdivision("ML-1", "Kayes", null, "Region"));
    out.add(new Subdivision("ML-10", "Taoudénit", null, "Region"));
    out.add(new Subdivision("ML-2", "Koulikoro", null, "Region"));
    out.add(new Subdivision("ML-3", "Sikasso", null, "Region"));
    out.add(new Subdivision("ML-4", "Ségou", null, "Region"));
    out.add(new Subdivision("ML-5", "Mopti", null, "Region"));
    out.add(new Subdivision("ML-6", "Tombouctou", null, "Region"));
    out.add(new Subdivision("ML-7", "Gao", null, "Region"));
    out.add(new Subdivision("ML-8", "Kidal", null, "Region"));
    out.add(new Subdivision("ML-9", "Ménaka", null, "Region"));
    out.add(new Subdivision("ML-BKO", "Bamako", null, "District"));
    out.add(new Subdivision("MM-01", "Sagaing", null, "Region"));
    out.add(new Subdivision("MM-02", "Bago", null, "Region"));
    out.add(new Subdivision("MM-03", "Magway", null, "Region"));
    out.add(new Subdivision("MM-04", "Mandalay", null, "Region"));
    out.add(new Subdivision("MM-05", "Tanintharyi", null, "Region"));
    out.add(new Subdivision("MM-06", "Yangon", null, "Region"));
    out.add(new Subdivision("MM-07", "Ayeyarwady", null, "Region"));
    out.add(new Subdivision("MM-11", "Kachin", null, "State"));
    out.add(new Subdivision("MM-12", "Kayah", null, "State"));
    out.add(new Subdivision("MM-13", "Kayin", null, "State"));
    out.add(new Subdivision("MM-14", "Chin", null, "State"));
    out.add(new Subdivision("MM-15", "Mon", null, "State"));
    out.add(new Subdivision("MM-16", "Rakhine", null, "State"));
    out.add(new Subdivision("MM-17", "Shan", null, "State"));
    out.add(new Subdivision("MM-18", "Nay Pyi Taw", null, "Union territory"));
    out.add(new Subdivision("MN-035", "Orhon", null, "Province"));
    out.add(new Subdivision("MN-037", "Darhan uul", null, "Province"));
    out.add(new Subdivision("MN-039", "Hentiy", null, "Province"));
    out.add(new Subdivision("MN-041", "Hövsgöl", null, "Province"));
    out.add(new Subdivision("MN-043", "Hovd", null, "Province"));
    out.add(new Subdivision("MN-046", "Uvs", null, "Province"));
    out.add(new Subdivision("MN-047", "Töv", null, "Province"));
    out.add(new Subdivision("MN-049", "Selenge", null, "Province"));
    out.add(new Subdivision("MN-051", "Sühbaatar", null, "Province"));
    out.add(new Subdivision("MN-053", "Ömnögovĭ", null, "Province"));
    out.add(new Subdivision("MN-055", "Övörhangay", null, "Province"));
    out.add(new Subdivision("MN-057", "Dzavhan", null, "Province"));
    out.add(new Subdivision("MN-059", "Dundgovĭ", null, "Province"));
    out.add(new Subdivision("MN-061", "Dornod", null, "Province"));
    out.add(new Subdivision("MN-063", "Dornogovĭ", null, "Province"));
    out.add(new Subdivision("MN-064", "Govĭ-Sümber", null, "Province"));
    out.add(new Subdivision("MN-065", "Govĭ-Altay", null, "Province"));
    out.add(new Subdivision("MN-067", "Bulgan", null, "Province"));
    out.add(new Subdivision("MN-069", "Bayanhongor", null, "Province"));
    out.add(new Subdivision("MN-071", "Bayan-Ölgiy", null, "Province"));
    out.add(new Subdivision("MN-073", "Arhangay", null, "Province"));
    out.add(new Subdivision("MN-1", "Ulaanbaatar", null, "Capital city"));
    out.add(new Subdivision("MR-01", "Hodh ech Chargui", null, "Region"));
    out.add(new Subdivision("MR-02", "Hodh el Gharbi", null, "Region"));
    out.add(new Subdivision("MR-03", "Assaba", null, "Region"));
    out.add(new Subdivision("MR-04", "Gorgol", null, "Region"));
    out.add(new Subdivision("MR-05", "Brakna", null, "Region"));
    out.add(new Subdivision("MR-06", "Trarza", null, "Region"));
    out.add(new Subdivision("MR-07", "Adrar", null, "Region"));
    out.add(new Subdivision("MR-08", "Dakhlet Nouâdhibou", null, "Region"));
    out.add(new Subdivision("MR-09", "Tagant", null, "Region"));
    out.add(new Subdivision("MR-10", "Guidimaka", null, "Region"));
    out.add(new Subdivision("MR-11", "Tiris Zemmour", null, "Region"));
    out.add(new Subdivision("MR-12", "Inchiri", null, "Region"));
    out.add(new Subdivision("MR-13", "Nouakchott Ouest", null, "Region"));
    out.add(new Subdivision("MR-14", "Nouakchott Nord", null, "Region"));
    out.add(new Subdivision("MR-15", "Nouakchott Sud", null, "Region"));
    out.add(new Subdivision("MT-01", "Attard", null, "Local council"));
    out.add(new Subdivision("MT-02", "Balzan", null, "Local council"));
    out.add(new Subdivision("MT-03", "Birgu", null, "Local council"));
    out.add(new Subdivision("MT-04", "Birkirkara", null, "Local council"));
    out.add(new Subdivision("MT-05", "Birżebbuġa", null, "Local council"));
    out.add(new Subdivision("MT-06", "Bormla", null, "Local council"));
    out.add(new Subdivision("MT-07", "Dingli", null, "Local council"));
    out.add(new Subdivision("MT-08", "Fgura", null, "Local council"));
    out.add(new Subdivision("MT-09", "Floriana", null, "Local council"));
    out.add(new Subdivision("MT-10", "Fontana", null, "Local council"));
    out.add(new Subdivision("MT-11", "Gudja", null, "Local council"));
    out.add(new Subdivision("MT-12", "Gżira", null, "Local council"));
    out.add(new Subdivision("MT-13", "Għajnsielem", null, "Local council"));
    out.add(new Subdivision("MT-14", "Għarb", null, "Local council"));
    out.add(new Subdivision("MT-15", "Għargħur", null, "Local council"));
    out.add(new Subdivision("MT-16", "Għasri", null, "Local council"));
    out.add(new Subdivision("MT-17", "Għaxaq", null, "Local council"));
    out.add(new Subdivision("MT-18", "Ħamrun", null, "Local council"));
    out.add(new Subdivision("MT-19", "Iklin", null, "Local council"));
    out.add(new Subdivision("MT-20", "Isla", null, "Local council"));
    out.add(new Subdivision("MT-21", "Kalkara", null, "Local council"));
    out.add(new Subdivision("MT-22", "Kerċem", null, "Local council"));
    out.add(new Subdivision("MT-23", "Kirkop", null, "Local council"));
    out.add(new Subdivision("MT-24", "Lija", null, "Local council"));
    out.add(new Subdivision("MT-25", "Luqa", null, "Local council"));
    out.add(new Subdivision("MT-26", "Marsa", null, "Local council"));
    out.add(new Subdivision("MT-27", "Marsaskala", null, "Local council"));
    out.add(new Subdivision("MT-28", "Marsaxlokk", null, "Local council"));
    out.add(new Subdivision("MT-29", "Mdina", null, "Local council"));
    out.add(new Subdivision("MT-30", "Mellieħa", null, "Local council"));
    out.add(new Subdivision("MT-31", "Mġarr", null, "Local council"));
    out.add(new Subdivision("MT-32", "Mosta", null, "Local council"));
    out.add(new Subdivision("MT-33", "Mqabba", null, "Local council"));
    out.add(new Subdivision("MT-34", "Msida", null, "Local council"));
    out.add(new Subdivision("MT-35", "Mtarfa", null, "Local council"));
    out.add(new Subdivision("MT-36", "Munxar", null, "Local council"));
    out.add(new Subdivision("MT-37", "Nadur", null, "Local council"));
    out.add(new Subdivision("MT-38", "Naxxar", null, "Local council"));
    out.add(new Subdivision("MT-39", "Paola", null, "Local council"));
    out.add(new Subdivision("MT-40", "Pembroke", null, "Local council"));
    out.add(new Subdivision("MT-41", "Pietà", null, "Local council"));
    out.add(new Subdivision("MT-42", "Qala", null, "Local council"));
    out.add(new Subdivision("MT-43", "Qormi", null, "Local council"));
    out.add(new Subdivision("MT-44", "Qrendi", null, "Local council"));
    out.add(new Subdivision("MT-45", "Rabat Gozo", null, "Local council"));
    out.add(new Subdivision("MT-46", "Rabat Malta", null, "Local council"));
    out.add(new Subdivision("MT-47", "Safi", null, "Local council"));
    out.add(new Subdivision("MT-48", "Saint Julian's", null, "Local council"));
    out.add(new Subdivision("MT-49", "Saint John", null, "Local council"));
    out.add(new Subdivision("MT-50", "Saint Lawrence", null, "Local council"));
    out.add(new Subdivision("MT-51", "Saint Paul's Bay", null, "Local council"));
    out.add(new Subdivision("MT-52", "Sannat", null, "Local council"));
    out.add(new Subdivision("MT-53", "Saint Lucia's", null, "Local council"));
    out.add(new Subdivision("MT-54", "Santa Venera", null, "Local council"));
    out.add(new Subdivision("MT-55", "Siġġiewi", null, "Local council"));
    out.add(new Subdivision("MT-56", "Sliema", null, "Local council"));
    out.add(new Subdivision("MT-57", "Swieqi", null, "Local council"));
    out.add(new Subdivision("MT-58", "Ta' Xbiex", null, "Local council"));
    out.add(new Subdivision("MT-59", "Tarxien", null, "Local council"));
    out.add(new Subdivision("MT-60", "Valletta", null, "Local council"));
    out.add(new Subdivision("MT-61", "Xagħra", null, "Local council"));
    out.add(new Subdivision("MT-62", "Xewkija", null, "Local council"));
    out.add(new Subdivision("MT-63", "Xgħajra", null, "Local council"));
    out.add(new Subdivision("MT-64", "Żabbar", null, "Local council"));
    out.add(new Subdivision("MT-65", "Żebbuġ Gozo", null, "Local council"));
    out.add(new Subdivision("MT-66", "Żebbuġ Malta", null, "Local council"));
    out.add(new Subdivision("MT-67", "Żejtun", null, "Local council"));
    out.add(new Subdivision("MT-68", "Żurrieq", null, "Local council"));
    out.add(new Subdivision("MU-AG", "Agalega Islands", null, "Dependency"));
    out.add(new Subdivision("MU-BL", "Black River", null, "District"));
    out.add(new Subdivision("MU-CC", "Cargados Carajos Shoals", null, "Dependency"));
    out.add(new Subdivision("MU-FL", "Flacq", null, "District"));
    out.add(new Subdivision("MU-GP", "Grand Port", null, "District"));
    out.add(new Subdivision("MU-MO", "Moka", null, "District"));
    out.add(new Subdivision("MU-PA", "Pamplemousses", null, "District"));
    out.add(new Subdivision("MU-PL", "Port Louis", null, "District"));
    out.add(new Subdivision("MU-PW", "Plaines Wilhems", null, "District"));
    out.add(new Subdivision("MU-RO", "Rodrigues Island", null, "Dependency"));
    out.add(new Subdivision("MU-RR", "Rivière du Rempart", null, "District"));
    out.add(new Subdivision("MU-SA", "Savanne", null, "District"));
    out.add(new Subdivision("MV-00", "South Ari Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-01", "Addu City", null, "City"));
    out.add(new Subdivision("MV-02", "North Ari Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-03", "Faadhippolhu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-04", "Felidhu Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-05", "Hahdhunmathi", null, "Administrative atoll"));
    out.add(new Subdivision("MV-07", "North Thiladhunmathi", null, "Administrative atoll"));
    out.add(new Subdivision("MV-08", "Kolhumadulu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-12", "Mulaku Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-13", "North Maalhosmadulu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-14", "North Nilandhe Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-17", "South Nilandhe Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-20", "South Maalhosmadulu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-23", "South Thiladhunmathi", null, "Administrative atoll"));
    out.add(new Subdivision("MV-24", "North Miladhunmadulu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-25", "South Miladhunmadulu", null, "Administrative atoll"));
    out.add(new Subdivision("MV-26", "Male Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-27", "North Huvadhu Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-28", "South Huvadhu Atoll", null, "Administrative atoll"));
    out.add(new Subdivision("MV-29", "Fuvammulah", null, "Administrative atoll"));
    out.add(new Subdivision("MV-MLE", "Male", null, "City"));
    out.add(new Subdivision("MW-BA", "Balaka", "MW-S", "District"));
    out.add(new Subdivision("MW-BL", "Blantyre", "MW-S", "District"));
    out.add(new Subdivision("MW-C", "Central Region", null, "Region"));
    out.add(new Subdivision("MW-CK", "Chikwawa", "MW-S", "District"));
    out.add(new Subdivision("MW-CR", "Chiradzulu", "MW-S", "District"));
    out.add(new Subdivision("MW-CT", "Chitipa", "MW-N", "District"));
    out.add(new Subdivision("MW-DE", "Dedza", "MW-C", "District"));
    out.add(new Subdivision("MW-DO", "Dowa", "MW-C", "District"));
    out.add(new Subdivision("MW-KR", "Karonga", "MW-N", "District"));
    out.add(new Subdivision("MW-KS", "Kasungu", "MW-C", "District"));
    out.add(new Subdivision("MW-LI", "Lilongwe", "MW-C", "District"));
    out.add(new Subdivision("MW-LK", "Likoma", "MW-N", "District"));
    out.add(new Subdivision("MW-MC", "Mchinji", "MW-C", "District"));
    out.add(new Subdivision("MW-MG", "Mangochi", "MW-S", "District"));
    out.add(new Subdivision("MW-MH", "Machinga", "MW-S", "District"));
    out.add(new Subdivision("MW-MU", "Mulanje", "MW-S", "District"));
    out.add(new Subdivision("MW-MW", "Mwanza", "MW-S", "District"));
    out.add(new Subdivision("MW-MZ", "Mzimba", "MW-N", "District"));
    out.add(new Subdivision("MW-N", "Northern Region", null, "Region"));
    out.add(new Subdivision("MW-NB", "Nkhata Bay", "MW-N", "District"));
    out.add(new Subdivision("MW-NE", "Neno", "MW-S", "District"));
    out.add(new Subdivision("MW-NI", "Ntchisi", "MW-C", "District"));
    out.add(new Subdivision("MW-NK", "Nkhotakota", "MW-C", "District"));
    out.add(new Subdivision("MW-NS", "Nsanje", "MW-S", "District"));
    out.add(new Subdivision("MW-NU", "Ntcheu", "MW-C", "District"));
    out.add(new Subdivision("MW-PH", "Phalombe", "MW-S", "District"));
    out.add(new Subdivision("MW-RU", "Rumphi", "MW-N", "District"));
    out.add(new Subdivision("MW-S", "Southern Region", null, "Region"));
    out.add(new Subdivision("MW-SA", "Salima", "MW-C", "District"));
    out.add(new Subdivision("MW-TH", "Thyolo", "MW-S", "District"));
    out.add(new Subdivision("MW-ZO", "Zomba", "MW-S", "District"));
    out.add(new Subdivision("MX-AGU", "Aguascalientes", null, "State"));
    out.add(new Subdivision("MX-BCN", "Baja California", null, "State"));
    out.add(new Subdivision("MX-BCS", "Baja California Sur", null, "State"));
    out.add(new Subdivision("MX-CAM", "Campeche", null, "State"));
    out.add(new Subdivision("MX-CHH", "Chihuahua", null, "State"));
    out.add(new Subdivision("MX-CHP", "Chiapas", null, "State"));
    out.add(new Subdivision("MX-CMX", "Ciudad de México", null, "Federal entity"));
    out.add(new Subdivision("MX-COA", "Coahuila de Zaragoza", null, "State"));
    out.add(new Subdivision("MX-COL", "Colima", null, "State"));
    out.add(new Subdivision("MX-DUR", "Durango", null, "State"));
    out.add(new Subdivision("MX-GRO", "Guerrero", null, "State"));
    out.add(new Subdivision("MX-GUA", "Guanajuato", null, "State"));
    out.add(new Subdivision("MX-HID", "Hidalgo", null, "State"));
    out.add(new Subdivision("MX-JAL", "Jalisco", null, "State"));
    out.add(new Subdivision("MX-MEX", "México", null, "State"));
    out.add(new Subdivision("MX-MIC", "Michoacán de Ocampo", null, "State"));
    out.add(new Subdivision("MX-MOR", "Morelos", null, "State"));
    out.add(new Subdivision("MX-NAY", "Nayarit", null, "State"));
    out.add(new Subdivision("MX-NLE", "Nuevo León", null, "State"));
    out.add(new Subdivision("MX-OAX", "Oaxaca", null, "State"));
    out.add(new Subdivision("MX-PUE", "Puebla", null, "State"));
    out.add(new Subdivision("MX-QUE", "Querétaro", null, "State"));
    out.add(new Subdivision("MX-ROO", "Quintana Roo", null, "State"));
    out.add(new Subdivision("MX-SIN", "Sinaloa", null, "State"));
    out.add(new Subdivision("MX-SLP", "San Luis Potosí", null, "State"));
    out.add(new Subdivision("MX-SON", "Sonora", null, "State"));
    out.add(new Subdivision("MX-TAB", "Tabasco", null, "State"));
    out.add(new Subdivision("MX-TAM", "Tamaulipas", null, "State"));
    out.add(new Subdivision("MX-TLA", "Tlaxcala", null, "State"));
    out.add(new Subdivision("MX-VER", "Veracruz de Ignacio de la Llave", null, "State"));
    out.add(new Subdivision("MX-YUC", "Yucatán", null, "State"));
    out.add(new Subdivision("MX-ZAC", "Zacatecas", null, "State"));
    out.add(new Subdivision("MY-01", "Johor", null, "State"));
    out.add(new Subdivision("MY-02", "Kedah", null, "State"));
    out.add(new Subdivision("MY-03", "Kelantan", null, "State"));
    out.add(new Subdivision("MY-04", "Melaka", null, "State"));
    out.add(new Subdivision("MY-05", "Negeri Sembilan", null, "State"));
    out.add(new Subdivision("MY-06", "Pahang", null, "State"));
    out.add(new Subdivision("MY-07", "Pulau Pinang", null, "State"));
    out.add(new Subdivision("MY-08", "Perak", null, "State"));
    out.add(new Subdivision("MY-09", "Perlis", null, "State"));
    out.add(new Subdivision("MY-10", "Selangor", null, "State"));
    out.add(new Subdivision("MY-11", "Terengganu", null, "State"));
    out.add(new Subdivision("MY-12", "Sabah", null, "State"));
    out.add(new Subdivision("MY-13", "Sarawak", null, "State"));
    out.add(new Subdivision("MY-14", "Wilayah Persekutuan Kuala Lumpur", null, "Federal territory"));
    out.add(new Subdivision("MY-15", "Wilayah Persekutuan Labuan", null, "Federal territory"));
    out.add(new Subdivision("MY-16", "Wilayah Persekutuan Putrajaya", null, "Federal territory"));
    out.add(new Subdivision("MZ-A", "Niassa", null, "Province"));
    out.add(new Subdivision("MZ-B", "Manica", null, "Province"));
    out.add(new Subdivision("MZ-G", "Gaza", null, "Province"));
    out.add(new Subdivision("MZ-I", "Inhambane", null, "Province"));
    out.add(new Subdivision("MZ-L", "Maputo", null, "Province"));
    out.add(new Subdivision("MZ-MPM", "Maputo", null, "City"));
    out.add(new Subdivision("MZ-N", "Nampula", null, "Province"));
    out.add(new Subdivision("MZ-P", "Cabo Delgado", null, "Province"));
    out.add(new Subdivision("MZ-Q", "Zambézia", null, "Province"));
    out.add(new Subdivision("MZ-S", "Sofala", null, "Province"));
    out.add(new Subdivision("MZ-T", "Tete", null, "Province"));
    out.add(new Subdivision("NA-CA", "Zambezi", null, "Region"));
    out.add(new Subdivision("NA-ER", "Erongo", null, "Region"));
    out.add(new Subdivision("NA-HA", "Hardap", null, "Region"));
    out.add(new Subdivision("NA-KA", "//Karas", null, "Region"));
    out.add(new Subdivision("NA-KE", "Kavango East", null, "Region"));
    out.add(new Subdivision("NA-KH", "Khomas", null, "Region"));
    out.add(new Subdivision("NA-KU", "Kunene", null, "Region"));
    out.add(new Subdivision("NA-KW", "Kavango West", null, "Region"));
    out.add(new Subdivision("NA-OD", "Otjozondjupa", null, "Region"));
    out.add(new Subdivision("NA-OH", "Omaheke", null, "Region"));
    out.add(new Subdivision("NA-ON", "Oshana", null, "Region"));
    out.add(new Subdivision("NA-OS", "Omusati", null, "Region"));
    out.add(new Subdivision("NA-OT", "Oshikoto", null, "Region"));
    out.add(new Subdivision("NA-OW", "Ohangwena", null, "Region"));
    out.add(new Subdivision("NE-1", "Agadez", null, "Region"));
    out.add(new Subdivision("NE-2", "Diffa", null, "Region"));
    out.add(new Subdivision("NE-3", "Dosso", null, "Region"));
    out.add(new Subdivision("NE-4", "Maradi", null, "Region"));
    out.add(new Subdivision("NE-5", "Tahoua", null, "Region"));
    out.add(new Subdivision("NE-6", "Tillabéri", null, "Region"));
    out.add(new Subdivision("NE-7", "Zinder", null, "Region"));
    out.add(new Subdivision("NE-8", "Niamey", null, "Urban community"));
    out.add(new Subdivision("NG-AB", "Abia", null, "State"));
    out.add(new Subdivision("NG-AD", "Adamawa", null, "State"));
    out.add(new Subdivision("NG-AK", "Akwa Ibom", null, "State"));
    out.add(new Subdivision("NG-AN", "Anambra", null, "State"));
    out.add(new Subdivision("NG-BA", "Bauchi", null, "State"));
    out.add(new Subdivision("NG-BE", "Benue", null, "State"));
    out.add(new Subdivision("NG-BO", "Borno", null, "State"));
    out.add(new Subdivision("NG-BY", "Bayelsa", null, "State"));
    out.add(new Subdivision("NG-CR", "Cross River", null, "State"));
    out.add(new Subdivision("NG-DE", "Delta", null, "State"));
    out.add(new Subdivision("NG-EB", "Ebonyi", null, "State"));
    out.add(new Subdivision("NG-ED", "Edo", null, "State"));
    out.add(new Subdivision("NG-EK", "Ekiti", null, "State"));
    out.add(new Subdivision("NG-EN", "Enugu", null, "State"));
    out.add(new Subdivision("NG-FC", "Abuja Federal Capital Territory", null, "Capital territory"));
    out.add(new Subdivision("NG-GO", "Gombe", null, "State"));
    out.add(new Subdivision("NG-IM", "Imo", null, "State"));
    out.add(new Subdivision("NG-JI", "Jigawa", null, "State"));
    out.add(new Subdivision("NG-KD", "Kaduna", null, "State"));
    out.add(new Subdivision("NG-KE", "Kebbi", null, "State"));
    out.add(new Subdivision("NG-KN", "Kano", null, "State"));
    out.add(new Subdivision("NG-KO", "Kogi", null, "State"));
    out.add(new Subdivision("NG-KT", "Katsina", null, "State"));
    out.add(new Subdivision("NG-KW", "Kwara", null, "State"));
    out.add(new Subdivision("NG-LA", "Lagos", null, "State"));
    out.add(new Subdivision("NG-NA", "Nasarawa", null, "State"));
    out.add(new Subdivision("NG-NI", "Niger", null, "State"));
    out.add(new Subdivision("NG-OG", "Ogun", null, "State"));
    out.add(new Subdivision("NG-ON", "Ondo", null, "State"));
    out.add(new Subdivision("NG-OS", "Osun", null, "State"));
    out.add(new Subdivision("NG-OY", "Oyo", null, "State"));
    out.add(new Subdivision("NG-PL", "Plateau", null, "State"));
    out.add(new Subdivision("NG-RI", "Rivers", null, "State"));
    out.add(new Subdivision("NG-SO", "Sokoto", null, "State"));
    out.add(new Subdivision("NG-TA", "Taraba", null, "State"));
    out.add(new Subdivision("NG-YO", "Yobe", null, "State"));
    out.add(new Subdivision("NG-ZA", "Zamfara", null, "State"));
    out.add(new Subdivision("NI-AN", "Costa Caribe Norte", null, "Autonomous region"));
    out.add(new Subdivision("NI-AS", "Costa Caribe Sur", null, "Autonomous region"));
    out.add(new Subdivision("NI-BO", "Boaco", null, "Department"));
    out.add(new Subdivision("NI-CA", "Carazo", null, "Department"));
    out.add(new Subdivision("NI-CI", "Chinandega", null, "Department"));
    out.add(new Subdivision("NI-CO", "Chontales", null, "Department"));
    out.add(new Subdivision("NI-ES", "Estelí", null, "Department"));
    out.add(new Subdivision("NI-GR", "Granada", null, "Department"));
    out.add(new Subdivision("NI-JI", "Jinotega", null, "Department"));
    out.add(new Subdivision("NI-LE", "León", null, "Department"));
    out.add(new Subdivision("NI-MD", "Madriz", null, "Department"));
    out.add(new Subdivision("NI-MN", "Managua", null, "Department"));
    out.add(new Subdivision("NI-MS", "Masaya", null, "Department"));
    out.add(new Subdivision("NI-MT", "Matagalpa", null, "Department"));
    out.add(new Subdivision("NI-NS", "Nueva Segovia", null, "Department"));
    out.add(new Subdivision("NI-RI", "Rivas", null, "Department"));
    out.add(new Subdivision("NI-SJ", "Río San Juan", null, "Department"));
    out.add(new Subdivision("NL-AW", "Aruba", null, "Country"));
    out.add(new Subdivision("NL-BQ1", "Bonaire", null, "Special municipality"));
    out.add(new Subdivision("NL-BQ2", "Saba", null, "Special municipality"));
    out.add(new Subdivision("NL-BQ3", "Sint Eustatius", null, "Special municipality"));
    out.add(new Subdivision("NL-CW", "Curaçao", null, "Country"));
    out.add(new Subdivision("NL-DR", "Drenthe", null, "Province"));
    out.add(new Subdivision("NL-FL", "Flevoland", null, "Province"));
    out.add(new Subdivision("NL-FR", "Fryslân", null, "Province"));
    out.add(new Subdivision("NL-GE", "Gelderland", null, "Province"));
    out.add(new Subdivision("NL-GR", "Groningen", null, "Province"));
    out.add(new Subdivision("NL-LI", "Limburg", null, "Province"));
    out.add(new Subdivision("NL-NB", "Noord-Brabant", null, "Province"));
    out.add(new Subdivision("NL-NH", "Noord-Holland", null, "Province"));
    out.add(new Subdivision("NL-OV", "Overijssel", null, "Province"));
    out.add(new Subdivision("NL-SX", "Sint Maarten", null, "Country"));
    out.add(new Subdivision("NL-UT", "Utrecht", null, "Province"));
    out.add(new Subdivision("NL-ZE", "Zeeland", null, "Province"));
    out.add(new Subdivision("NL-ZH", "Zuid-Holland", null, "Province"));
    out.add(new Subdivision("NO-03", "Oslo", null, "County"));
    out.add(new Subdivision("NO-11", "Rogaland", null, "County"));
    out.add(new Subdivision("NO-15", "Møre og Romsdal", null, "County"));
    out.add(new Subdivision("NO-18", "Nordland", null, "County"));
    out.add(new Subdivision("NO-21", "Svalbard (Arctic Region)", null, "Arctic region"));
    out.add(new Subdivision("NO-22", "Jan Mayen (Arctic Region)", null, "Arctic region"));
    out.add(new Subdivision("NO-30", "Viken", null, "County"));
    out.add(new Subdivision("NO-34", "Innlandet", null, "County"));
    out.add(new Subdivision("NO-38", "Vestfold og Telemark", null, "County"));
    out.add(new Subdivision("NO-42", "Agder", null, "County"));
    out.add(new Subdivision("NO-46", "Vestland", null, "County"));
    out.add(new Subdivision("NO-50", "Trøndelag", null, "County"));
    out.add(new Subdivision("NO-54", "Troms og Finnmark", null, "County"));
    out.add(new Subdivision("NP-P1", "Koshi", null, "Province"));
    out.add(new Subdivision("NP-P2", "Madhesh", null, "Province"));
    out.add(new Subdivision("NP-P3", "Bagmati", null, "Province"));
    out.add(new Subdivision("NP-P4", "Gandaki", null, "Province"));
    out.add(new Subdivision("NP-P5", "Lumbini", null, "Province"));
    out.add(new Subdivision("NP-P6", "Karnali", null, "Province"));
    out.add(new Subdivision("NP-P7", "Sudurpashchim", null, "Province"));
    out.add(new Subdivision("NR-01", "Aiwo", null, "District"));
    out.add(new Subdivision("NR-02", "Anabar", null, "District"));
    out.add(new Subdivision("NR-03", "Anetan", null, "District"));
    out.add(new Subdivision("NR-04", "Anibare", null, "District"));
    out.add(new Subdivision("NR-05", "Baitsi", null, "District"));
    out.add(new Subdivision("NR-06", "Boe", null, "District"));
    out.add(new Subdivision("NR-07", "Buada", null, "District"));
    out.add(new Subdivision("NR-08", "Denigomodu", null, "District"));
    out.add(new Subdivision("NR-09", "Ewa", null, "District"));
    out.add(new Subdivision("NR-10", "Ijuw", null, "District"));
    out.add(new Subdivision("NR-11", "Meneng", null, "District"));
    out.add(new Subdivision("NR-12", "Nibok", null, "District"));
    out.add(new Subdivision("NR-13", "Uaboe", null, "District"));
    out.add(new Subdivision("NR-14", "Yaren", null, "District"));
    out.add(new Subdivision("NZ-AUK", "Auckland", null, "Region"));
    out.add(new Subdivision("NZ-BOP", "Bay of Plenty", null, "Region"));
    out.add(new Subdivision("NZ-CAN", "Canterbury", null, "Region"));
    out.add(new Subdivision("NZ-CIT", "Chatham Islands Territory", null, "Special island authority"));
    out.add(new Subdivision("NZ-GIS", "Gisborne", null, "Region"));
    out.add(new Subdivision("NZ-HKB", "Hawke's Bay", null, "Region"));
    out.add(new Subdivision("NZ-MBH", "Marlborough", null, "Region"));
    out.add(new Subdivision("NZ-MWT", "Manawatū-Whanganui", null, "Region"));
    out.add(new Subdivision("NZ-NSN", "Nelson", null, "Region"));
    out.add(new Subdivision("NZ-NTL", "Northland", null, "Region"));
    out.add(new Subdivision("NZ-OTA", "Otago", null, "Region"));
    out.add(new Subdivision("NZ-STL", "Southland", null, "Region"));
    out.add(new Subdivision("NZ-TAS", "Tasman", null, "Region"));
    out.add(new Subdivision("NZ-TKI", "Taranaki", null, "Region"));
    out.add(new Subdivision("NZ-WGN", "Greater Wellington", null, "Region"));
    out.add(new Subdivision("NZ-WKO", "Waikato", null, "Region"));
    out.add(new Subdivision("NZ-WTC", "West Coast", null, "Region"));
    out.add(new Subdivision("OM-BJ", "Janūb al Bāţinah", null, "Governorate"));
    out.add(new Subdivision("OM-BS", "Shamāl al Bāţinah", null, "Governorate"));
    out.add(new Subdivision("OM-BU", "Al Buraymī", null, "Governorate"));
    out.add(new Subdivision("OM-DA", "Ad Dākhilīyah", null, "Governorate"));
    out.add(new Subdivision("OM-MA", "Masqaţ", null, "Governorate"));
    out.add(new Subdivision("OM-MU", "Musandam", null, "Governorate"));
    out.add(new Subdivision("OM-SJ", "Janūb ash Sharqīyah", null, "Governorate"));
    out.add(new Subdivision("OM-SS", "Shamāl ash Sharqīyah", null, "Governorate"));
    out.add(new Subdivision("OM-WU", "Al Wusţá", null, "Governorate"));
    out.add(new Subdivision("OM-ZA", "Az̧ Z̧āhirah", null, "Governorate"));
    out.add(new Subdivision("OM-ZU", "Z̧ufār", null, "Governorate"));
    out.add(new Subdivision("PA-1", "Bocas del Toro", null, "Province"));
    out.add(new Subdivision("PA-10", "Panamá Oeste", null, "Province"));
    out.add(new Subdivision("PA-2", "Coclé", null, "Province"));
    out.add(new Subdivision("PA-3", "Colón", null, "Province"));
    out.add(new Subdivision("PA-4", "Chiriquí", null, "Province"));
    out.add(new Subdivision("PA-5", "Darién", null, "Province"));
    out.add(new Subdivision("PA-6", "Herrera", null, "Province"));
    out.add(new Subdivision("PA-7", "Los Santos", null, "Province"));
    out.add(new Subdivision("PA-8", "Panamá", null, "Province"));
    out.add(new Subdivision("PA-9", "Veraguas", null, "Province"));
    out.add(new Subdivision("PA-EM", "Emberá", null, "Indigenous region"));
    out.add(new Subdivision("PA-KY", "Guna Yala", null, "Indigenous region"));
    out.add(new Subdivision("PA-NB", "Ngäbe-Buglé", null, "Indigenous region"));
    out.add(new Subdivision("PA-NT", "Naso Tjër Di", null, "Indigenous region"));
    out.add(new Subdivision("PE-AMA", "Amazonas", null, "Region"));
    out.add(new Subdivision("PE-ANC", "Ancash", null, "Region"));
    out.add(new Subdivision("PE-APU", "Apurímac", null, "Region"));
    out.add(new Subdivision("PE-ARE", "Arequipa", null, "Region"));
    out.add(new Subdivision("PE-AYA", "Ayacucho", null, "Region"));
    out.add(new Subdivision("PE-CAJ", "Cajamarca", null, "Region"));
    out.add(new Subdivision("PE-CAL", "El Callao", null, "Region"));
    out.add(new Subdivision("PE-CUS", "Cusco", null, "Region"));
    out.add(new Subdivision("PE-HUC", "Huánuco", null, "Region"));
    out.add(new Subdivision("PE-HUV", "Huancavelica", null, "Region"));
    out.add(new Subdivision("PE-ICA", "Ica", null, "Region"));
    out.add(new Subdivision("PE-JUN", "Junín", null, "Region"));
    out.add(new Subdivision("PE-LAL", "La Libertad", null, "Region"));
    out.add(new Subdivision("PE-LAM", "Lambayeque", null, "Region"));
    out.add(new Subdivision("PE-LIM", "Lima", null, "Region"));
    out.add(new Subdivision("PE-LMA", "Municipalidad Metropolitana de Lima", null, "Municipality"));
    out.add(new Subdivision("PE-LOR", "Loreto", null, "Region"));
    out.add(new Subdivision("PE-MDD", "Madre de Dios", null, "Region"));
    out.add(new Subdivision("PE-MOQ", "Moquegua", null, "Region"));
    out.add(new Subdivision("PE-PAS", "Pasco", null, "Region"));
    out.add(new Subdivision("PE-PIU", "Piura", null, "Region"));
    out.add(new Subdivision("PE-PUN", "Puno", null, "Region"));
    out.add(new Subdivision("PE-SAM", "San Martín", null, "Region"));
    out.add(new Subdivision("PE-TAC", "Tacna", null, "Region"));
    out.add(new Subdivision("PE-TUM", "Tumbes", null, "Region"));
    out.add(new Subdivision("PE-UCA", "Ucayali", null, "Region"));
    out.add(new Subdivision("PG-CPK", "Chimbu", null, "Province"));
    out.add(new Subdivision("PG-CPM", "Central", null, "Province"));
    out.add(new Subdivision("PG-EBR", "East New Britain", null, "Province"));
    out.add(new Subdivision("PG-EHG", "Eastern Highlands", null, "Province"));
    out.add(new Subdivision("PG-EPW", "Enga", null, "Province"));
    out.add(new Subdivision("PG-ESW", "East Sepik", null, "Province"));
  }
}
