// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 4500 to 4999 of {@link Subdivision}.
 */
final class SubdivisionData9 {
  private SubdivisionData9() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("TR-42", "Konya", null, "Province"));
    out.add(new Subdivision("TR-43", "Kütahya", null, "Province"));
    out.add(new Subdivision("TR-44", "Malatya", null, "Province"));
    out.add(new Subdivision("TR-45", "Manisa", null, "Province"));
    out.add(new Subdivision("TR-46", "Kahramanmaraş", null, "Province"));
    out.add(new Subdivision("TR-47", "Mardin", null, "Province"));
    out.add(new Subdivision("TR-48", "Muğla", null, "Province"));
    out.add(new Subdivision("TR-49", "Muş", null, "Province"));
    out.add(new Subdivision("TR-50", "Nevşehir", null, "Province"));
    out.add(new Subdivision("TR-51", "Niğde", null, "Province"));
    out.add(new Subdivision("TR-52", "Ordu", null, "Province"));
    out.add(new Subdivision("TR-53", "Rize", null, "Province"));
    out.add(new Subdivision("TR-54", "Sakarya", null, "Province"));
    out.add(new Subdivision("TR-55", "Samsun", null, "Province"));
    out.add(new Subdivision("TR-56", "Siirt", null, "Province"));
    out.add(new Subdivision("TR-57", "Sinop", null, "Province"));
    out.add(new Subdivision("TR-58", "Sivas", null, "Province"));
    out.add(new Subdivision("TR-59", "Tekirdağ", null, "Province"));
    out.add(new Subdivision("TR-60", "Tokat", null, "Province"));
    out.add(new Subdivision("TR-61", "Trabzon", null, "Province"));
    out.add(new Subdivision("TR-62", "Tunceli", null, "Province"));
    out.add(new Subdivision("TR-63", "Şanlıurfa", null, "Province"));
    out.add(new Subdivision("TR-64", "Uşak", null, "Province"));
    out.add(new Subdivision("TR-65", "Van", null, "Province"));
    out.add(new Subdivision("TR-66", "Yozgat", null, "Province"));
    out.add(new Subdivision("TR-67", "Zonguldak", null, "Province"));
    out.add(new Subdivision("TR-68", "Aksaray", null, "Province"));
    out.add(new Subdivision("TR-69", "Bayburt", null, "Province"));
    out.add(new Subdivision("TR-70", "Karaman", null, "Province"));
    out.add(new Subdivision("TR-71", "Kırıkkale", null, "Province"));
    out.add(new Subdivision("TR-72", "Batman", null, "Province"));
    out.add(new Subdivision("TR-73", "Şırnak", null, "Province"));
    out.add(new Subdivision("TR-74", "Bartın", null, "Province"));
    out.add(new Subdivision("TR-75", "Ardahan", null, "Province"));
    out.add(new Subdivision("TR-76", "Iğdır", null, "Province"));
    out.add(new Subdivision("TR-77", "Yalova", null, "Province"));
    out.add(new Subdivision("TR-78", "Karabük", null, "Province"));
    out.add(new Subdivision("TR-79", "Kilis", null, "Province"));
    out.add(new Subdivision("TR-80", "Osmaniye", null, "Province"));
    out.add(new Subdivision("TR-81", "Düzce", null, "Province"));
    out.add(new Subdivision("TT-ARI", "Arima", null, "Borough"));
    out.add(new Subdivision("TT-CHA", "Chaguanas", null, "Borough"));
    out.add(new Subdivision("TT-CTT", "Couva-Tabaquite-Talparo", null, "Region"));
    out.add(new Subdivision("TT-DMN", "Diego Martin", null, "Region"));
    out.add(new Subdivision("TT-MRC", "Mayaro-Rio Claro", null, "Region"));
    out.add(new Subdivision("TT-PED", "Penal-Debe", null, "Region"));
    out.add(new Subdivision("TT-POS", "Port of Spain", null, "City"));
    out.add(new Subdivision("TT-PRT", "Princes Town", null, "Region"));
    out.add(new Subdivision("TT-PTF", "Point Fortin", null, "Borough"));
    out.add(new Subdivision("TT-SFO", "San Fernando", null, "City"));
    out.add(new Subdivision("TT-SGE", "Sangre Grande", null, "Region"));
    out.add(new Subdivision("TT-SIP", "Siparia", null, "Region"));
    out.add(new Subdivision("TT-SJL", "San Juan-Laventille", null, "Region"));
    out.add(new Subdivision("TT-TOB", "Tobago", null, "Ward"));
    out.add(new Subdivision("TT-TUP", "Tunapuna-Piarco", null, "Region"));
    out.add(new Subdivision("TV-FUN", "Funafuti", null, "Town council"));
    out.add(new Subdivision("TV-NIT", "Niutao", null, "Island council"));
    out.add(new Subdivision("TV-NKF", "Nukufetau", null, "Island council"));
    out.add(new Subdivision("TV-NKL", "Nukulaelae", null, "Island council"));
    out.add(new Subdivision("TV-NMA", "Nanumea", null, "Island council"));
    out.add(new Subdivision("TV-NMG", "Nanumaga", null, "Island council"));
    out.add(new Subdivision("TV-NUI", "Nui", null, "Island council"));
    out.add(new Subdivision("TV-VAI", "Vaitupu", null, "Island council"));
    out.add(new Subdivision("TW-CHA", "Changhua", null, "County"));
    out.add(new Subdivision("TW-CYI", "Chiayi", null, "City"));
    out.add(new Subdivision("TW-CYQ", "Chiayi", null, "County"));
    out.add(new Subdivision("TW-HSQ", "Hsinchu", null, "County"));
    out.add(new Subdivision("TW-HSZ", "Hsinchu", null, "City"));
    out.add(new Subdivision("TW-HUA", "Hualien", null, "County"));
    out.add(new Subdivision("TW-ILA", "Yilan", null, "County"));
    out.add(new Subdivision("TW-KEE", "Keelung", null, "City"));
    out.add(new Subdivision("TW-KHH", "Kaohsiung", null, "Special municipality"));
    out.add(new Subdivision("TW-KIN", "Kinmen", null, "County"));
    out.add(new Subdivision("TW-LIE", "Lienchiang", null, "County"));
    out.add(new Subdivision("TW-MIA", "Miaoli", null, "County"));
    out.add(new Subdivision("TW-NAN", "Nantou", null, "County"));
    out.add(new Subdivision("TW-NWT", "New Taipei", null, "Special municipality"));
    out.add(new Subdivision("TW-PEN", "Penghu", null, "County"));
    out.add(new Subdivision("TW-PIF", "Pingtung", null, "County"));
    out.add(new Subdivision("TW-TAO", "Taoyuan", null, "Special municipality"));
    out.add(new Subdivision("TW-TNN", "Tainan", null, "Special municipality"));
    out.add(new Subdivision("TW-TPE", "Taipei", null, "Special municipality"));
    out.add(new Subdivision("TW-TTT", "Taitung", null, "County"));
    out.add(new Subdivision("TW-TXG", "Taichung", null, "Special municipality"));
    out.add(new Subdivision("TW-YUN", "Yunlin", null, "County"));
    out.add(new Subdivision("TZ-01", "Arusha", null, "Region"));
    out.add(new Subdivision("TZ-02", "Dar es Salaam", null, "Region"));
    out.add(new Subdivision("TZ-03", "Dodoma", null, "Region"));
    out.add(new Subdivision("TZ-04", "Iringa", null, "Region"));
    out.add(new Subdivision("TZ-05", "Kagera", null, "Region"));
    out.add(new Subdivision("TZ-06", "Pemba North", null, "Region"));
    out.add(new Subdivision("TZ-07", "Zanzibar North", null, "Region"));
    out.add(new Subdivision("TZ-08", "Kigoma", null, "Region"));
    out.add(new Subdivision("TZ-09", "Kilimanjaro", null, "Region"));
    out.add(new Subdivision("TZ-10", "Pemba South", null, "Region"));
    out.add(new Subdivision("TZ-11", "Zanzibar South", null, "Region"));
    out.add(new Subdivision("TZ-12", "Lindi", null, "Region"));
    out.add(new Subdivision("TZ-13", "Mara", null, "Region"));
    out.add(new Subdivision("TZ-14", "Mbeya", null, "Region"));
    out.add(new Subdivision("TZ-15", "Zanzibar West", null, "Region"));
    out.add(new Subdivision("TZ-16", "Morogoro", null, "Region"));
    out.add(new Subdivision("TZ-17", "Mtwara", null, "Region"));
    out.add(new Subdivision("TZ-18", "Mwanza", null, "Region"));
    out.add(new Subdivision("TZ-19", "Coast", null, "Region"));
    out.add(new Subdivision("TZ-20", "Rukwa", null, "Region"));
    out.add(new Subdivision("TZ-21", "Ruvuma", null, "Region"));
    out.add(new Subdivision("TZ-22", "Shinyanga", null, "Region"));
    out.add(new Subdivision("TZ-23", "Singida", null, "Region"));
    out.add(new Subdivision("TZ-24", "Tabora", null, "Region"));
    out.add(new Subdivision("TZ-25", "Tanga", null, "Region"));
    out.add(new Subdivision("TZ-26", "Manyara", null, "Region"));
    out.add(new Subdivision("TZ-27", "Geita", null, "Region"));
    out.add(new Subdivision("TZ-28", "Katavi", null, "Region"));
    out.add(new Subdivision("TZ-29", "Njombe", null, "Region"));
    out.add(new Subdivision("TZ-30", "Simiyu", null, "Region"));
    out.add(new Subdivision("TZ-31", "Songwe", null, "Region"));
    out.add(new Subdivision("UA-05", "Vinnytska oblast", null, "Region"));
    out.add(new Subdivision("UA-07", "Volynska oblast", null, "Region"));
    out.add(new Subdivision("UA-09", "Luhanska oblast", null, "Region"));
    out.add(new Subdivision("UA-12", "Dnipropetrovska oblast", null, "Region"));
    out.add(new Subdivision("UA-14", "Donetska oblast", null, "Region"));
    out.add(new Subdivision("UA-18", "Zhytomyrska oblast", null, "Region"));
    out.add(new Subdivision("UA-21", "Zakarpatska oblast", null, "Region"));
    out.add(new Subdivision("UA-23", "Zaporizka oblast", null, "Region"));
    out.add(new Subdivision("UA-26", "Ivano-Frankivska oblast", null, "Region"));
    out.add(new Subdivision("UA-30", "Kyiv", null, "City"));
    out.add(new Subdivision("UA-32", "Kyivska oblast", null, "Region"));
    out.add(new Subdivision("UA-35", "Kirovohradska oblast", null, "Region"));
    out.add(new Subdivision("UA-40", "Sevastopol", null, "City"));
    out.add(new Subdivision("UA-43", "Avtonomna Respublika Krym", null, "Republic"));
    out.add(new Subdivision("UA-46", "Lvivska oblast", null, "Region"));
    out.add(new Subdivision("UA-48", "Mykolaivska oblast", null, "Region"));
    out.add(new Subdivision("UA-51", "Odeska oblast", null, "Region"));
    out.add(new Subdivision("UA-53", "Poltavska oblast", null, "Region"));
    out.add(new Subdivision("UA-56", "Rivnenska oblast", null, "Region"));
    out.add(new Subdivision("UA-59", "Sumska oblast", null, "Region"));
    out.add(new Subdivision("UA-61", "Ternopilska oblast", null, "Region"));
    out.add(new Subdivision("UA-63", "Kharkivska oblast", null, "Region"));
    out.add(new Subdivision("UA-65", "Khersonska oblast", null, "Region"));
    out.add(new Subdivision("UA-68", "Khmelnytska oblast", null, "Region"));
    out.add(new Subdivision("UA-71", "Cherkaska oblast", null, "Region"));
    out.add(new Subdivision("UA-74", "Chernihivska oblast", null, "Region"));
    out.add(new Subdivision("UA-77", "Chernivetska oblast", null, "Region"));
    out.add(new Subdivision("UG-101", "Kalangala", "UG-C", "District"));
    out.add(new Subdivision("UG-102", "Kampala", "UG-C", "City"));
    out.add(new Subdivision("UG-103", "Kiboga", "UG-C", "District"));
    out.add(new Subdivision("UG-104", "Luwero", "UG-C", "District"));
    out.add(new Subdivision("UG-105", "Masaka", "UG-C", "District"));
    out.add(new Subdivision("UG-106", "Mpigi", "UG-C", "District"));
    out.add(new Subdivision("UG-107", "Mubende", "UG-C", "District"));
    out.add(new Subdivision("UG-108", "Mukono", "UG-C", "District"));
    out.add(new Subdivision("UG-109", "Nakasongola", "UG-C", "District"));
    out.add(new Subdivision("UG-110", "Rakai", "UG-C", "District"));
    out.add(new Subdivision("UG-111", "Sembabule", "UG-C", "District"));
    out.add(new Subdivision("UG-112", "Kayunga", "UG-C", "District"));
    out.add(new Subdivision("UG-113", "Wakiso", "UG-C", "District"));
    out.add(new Subdivision("UG-114", "Lyantonde", "UG-C", "District"));
    out.add(new Subdivision("UG-115", "Mityana", "UG-C", "District"));
    out.add(new Subdivision("UG-116", "Nakaseke", "UG-C", "District"));
    out.add(new Subdivision("UG-117", "Buikwe", "UG-C", "District"));
    out.add(new Subdivision("UG-118", "Bukomansibi", "UG-C", "District"));
    out.add(new Subdivision("UG-119", "Butambala", "UG-C", "District"));
    out.add(new Subdivision("UG-120", "Buvuma", "UG-C", "District"));
    out.add(new Subdivision("UG-121", "Gomba", "UG-C", "District"));
    out.add(new Subdivision("UG-122", "Kalungu", "UG-C", "District"));
    out.add(new Subdivision("UG-123", "Kyankwanzi", "UG-C", "District"));
    out.add(new Subdivision("UG-124", "Lwengo", "UG-C", "District"));
    out.add(new Subdivision("UG-125", "Kyotera", "UG-C", "District"));
    out.add(new Subdivision("UG-126", "Kasanda", "UG-C", "District"));
    out.add(new Subdivision("UG-201", "Bugiri", "UG-E", "District"));
    out.add(new Subdivision("UG-202", "Busia", "UG-E", "District"));
    out.add(new Subdivision("UG-203", "Iganga", "UG-E", "District"));
    out.add(new Subdivision("UG-204", "Jinja", "UG-E", "District"));
    out.add(new Subdivision("UG-205", "Kamuli", "UG-E", "District"));
    out.add(new Subdivision("UG-206", "Kapchorwa", "UG-E", "District"));
    out.add(new Subdivision("UG-207", "Katakwi", "UG-E", "District"));
    out.add(new Subdivision("UG-208", "Kumi", "UG-E", "District"));
    out.add(new Subdivision("UG-209", "Mbale", "UG-E", "District"));
    out.add(new Subdivision("UG-210", "Pallisa", "UG-E", "District"));
    out.add(new Subdivision("UG-211", "Soroti", "UG-E", "District"));
    out.add(new Subdivision("UG-212", "Tororo", "UG-E", "District"));
    out.add(new Subdivision("UG-213", "Kaberamaido", "UG-E", "District"));
    out.add(new Subdivision("UG-214", "Mayuge", "UG-E", "District"));
    out.add(new Subdivision("UG-215", "Sironko", "UG-E", "District"));
    out.add(new Subdivision("UG-216", "Amuria", "UG-E", "District"));
    out.add(new Subdivision("UG-217", "Budaka", "UG-E", "District"));
    out.add(new Subdivision("UG-218", "Bududa", "UG-E", "District"));
    out.add(new Subdivision("UG-219", "Bukedea", "UG-E", "District"));
    out.add(new Subdivision("UG-220", "Bukwo", "UG-E", "District"));
    out.add(new Subdivision("UG-221", "Butaleja", "UG-E", "District"));
    out.add(new Subdivision("UG-222", "Kaliro", "UG-E", "District"));
    out.add(new Subdivision("UG-223", "Manafwa", "UG-E", "District"));
    out.add(new Subdivision("UG-224", "Namutumba", "UG-E", "District"));
    out.add(new Subdivision("UG-225", "Bulambuli", "UG-E", "District"));
    out.add(new Subdivision("UG-226", "Buyende", "UG-E", "District"));
    out.add(new Subdivision("UG-227", "Kibuku", "UG-E", "District"));
    out.add(new Subdivision("UG-228", "Kween", "UG-E", "District"));
    out.add(new Subdivision("UG-229", "Luuka", "UG-E", "District"));
    out.add(new Subdivision("UG-230", "Namayingo", "UG-E", "District"));
    out.add(new Subdivision("UG-231", "Ngora", "UG-E", "District"));
    out.add(new Subdivision("UG-232", "Serere", "UG-E", "District"));
    out.add(new Subdivision("UG-233", "Butebo", "UG-E", "District"));
    out.add(new Subdivision("UG-234", "Namisindwa", "UG-E", "District"));
    out.add(new Subdivision("UG-235", "Bugweri", "UG-E", "District"));
    out.add(new Subdivision("UG-236", "Kapelebyong", "UG-E", "District"));
    out.add(new Subdivision("UG-237", "Kalaki", "UG-E", "District"));
    out.add(new Subdivision("UG-301", "Adjumani", "UG-N", "District"));
    out.add(new Subdivision("UG-302", "Apac", "UG-N", "District"));
    out.add(new Subdivision("UG-303", "Arua", "UG-N", "District"));
    out.add(new Subdivision("UG-304", "Gulu", "UG-N", "District"));
    out.add(new Subdivision("UG-305", "Kitgum", "UG-N", "District"));
    out.add(new Subdivision("UG-306", "Kotido", "UG-N", "District"));
    out.add(new Subdivision("UG-307", "Lira", "UG-N", "District"));
    out.add(new Subdivision("UG-308", "Moroto", "UG-N", "District"));
    out.add(new Subdivision("UG-309", "Moyo", "UG-N", "District"));
    out.add(new Subdivision("UG-310", "Nebbi", "UG-N", "District"));
    out.add(new Subdivision("UG-311", "Nakapiripirit", "UG-N", "District"));
    out.add(new Subdivision("UG-312", "Pader", "UG-N", "District"));
    out.add(new Subdivision("UG-313", "Yumbe", "UG-N", "District"));
    out.add(new Subdivision("UG-314", "Abim", "UG-N", "District"));
    out.add(new Subdivision("UG-315", "Amolatar", "UG-N", "District"));
    out.add(new Subdivision("UG-316", "Amuru", "UG-N", "District"));
    out.add(new Subdivision("UG-317", "Dokolo", "UG-N", "District"));
    out.add(new Subdivision("UG-318", "Kaabong", "UG-N", "District"));
    out.add(new Subdivision("UG-319", "Koboko", "UG-N", "District"));
    out.add(new Subdivision("UG-320", "Maracha", "UG-N", "District"));
    out.add(new Subdivision("UG-321", "Oyam", "UG-N", "District"));
    out.add(new Subdivision("UG-322", "Agago", "UG-N", "District"));
    out.add(new Subdivision("UG-323", "Alebtong", "UG-N", "District"));
    out.add(new Subdivision("UG-324", "Amudat", "UG-N", "District"));
    out.add(new Subdivision("UG-325", "Kole", "UG-N", "District"));
    out.add(new Subdivision("UG-326", "Lamwo", "UG-N", "District"));
    out.add(new Subdivision("UG-327", "Napak", "UG-N", "District"));
    out.add(new Subdivision("UG-328", "Nwoya", "UG-N", "District"));
    out.add(new Subdivision("UG-329", "Otuke", "UG-N", "District"));
    out.add(new Subdivision("UG-330", "Zombo", "UG-N", "District"));
    out.add(new Subdivision("UG-331", "Omoro", "UG-N", "District"));
    out.add(new Subdivision("UG-332", "Pakwach", "UG-N", "District"));
    out.add(new Subdivision("UG-333", "Kwania", "UG-N", "District"));
    out.add(new Subdivision("UG-334", "Nabilatuk", "UG-N", "District"));
    out.add(new Subdivision("UG-335", "Karenga", "UG-N", "District"));
    out.add(new Subdivision("UG-336", "Madi-Okollo", "UG-N", "District"));
    out.add(new Subdivision("UG-337", "Obongi", "UG-N", "District"));
    out.add(new Subdivision("UG-401", "Bundibugyo", "UG-W", "District"));
    out.add(new Subdivision("UG-402", "Bushenyi", "UG-W", "District"));
    out.add(new Subdivision("UG-403", "Hoima", "UG-W", "District"));
    out.add(new Subdivision("UG-404", "Kabale", "UG-W", "District"));
    out.add(new Subdivision("UG-405", "Kabarole", "UG-W", "District"));
    out.add(new Subdivision("UG-406", "Kasese", "UG-W", "District"));
    out.add(new Subdivision("UG-407", "Kibaale", "UG-W", "District"));
    out.add(new Subdivision("UG-408", "Kisoro", "UG-W", "District"));
    out.add(new Subdivision("UG-409", "Masindi", "UG-W", "District"));
    out.add(new Subdivision("UG-410", "Mbarara", "UG-W", "District"));
    out.add(new Subdivision("UG-411", "Ntungamo", "UG-W", "District"));
    out.add(new Subdivision("UG-412", "Rukungiri", "UG-W", "District"));
    out.add(new Subdivision("UG-413", "Kamwenge", "UG-W", "District"));
    out.add(new Subdivision("UG-414", "Kanungu", "UG-W", "District"));
    out.add(new Subdivision("UG-415", "Kyenjojo", "UG-W", "District"));
    out.add(new Subdivision("UG-416", "Buliisa", "UG-W", "District"));
    out.add(new Subdivision("UG-417", "Ibanda", "UG-W", "District"));
    out.add(new Subdivision("UG-418", "Isingiro", "UG-W", "District"));
    out.add(new Subdivision("UG-419", "Kiruhura", "UG-W", "District"));
    out.add(new Subdivision("UG-420", "Buhweju", "UG-W", "District"));
    out.add(new Subdivision("UG-421", "Kiryandongo", "UG-W", "District"));
    out.add(new Subdivision("UG-422", "Kyegegwa", "UG-W", "District"));
    out.add(new Subdivision("UG-423", "Mitooma", "UG-W", "District"));
    out.add(new Subdivision("UG-424", "Ntoroko", "UG-W", "District"));
    out.add(new Subdivision("UG-425", "Rubirizi", "UG-W", "District"));
    out.add(new Subdivision("UG-426", "Sheema", "UG-W", "District"));
    out.add(new Subdivision("UG-427", "Kagadi", "UG-W", "District"));
    out.add(new Subdivision("UG-428", "Kakumiro", "UG-W", "District"));
    out.add(new Subdivision("UG-429", "Rubanda", "UG-W", "District"));
    out.add(new Subdivision("UG-430", "Bunyangabu", "UG-W", "District"));
    out.add(new Subdivision("UG-431", "Rukiga", "UG-W", "District"));
    out.add(new Subdivision("UG-432", "Kikuube", "UG-W", "District"));
    out.add(new Subdivision("UG-433", "Kazo", "UG-W", "District"));
    out.add(new Subdivision("UG-434", "Kitagwenda", "UG-W", "District"));
    out.add(new Subdivision("UG-435", "Rwampara", "UG-W", "District"));
    out.add(new Subdivision("UG-C", "Central", null, "Geographical region"));
    out.add(new Subdivision("UG-E", "Eastern", null, "Geographical region"));
    out.add(new Subdivision("UG-N", "Northern", null, "Geographical region"));
    out.add(new Subdivision("UG-W", "Western", null, "Geographical region"));
    out.add(new Subdivision("UM-67", "Johnston Atoll", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-71", "Midway Islands", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-76", "Navassa Island", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-79", "Wake Island", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-81", "Baker Island", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-84", "Howland Island", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-86", "Jarvis Island", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-89", "Kingman Reef", null, "Islands, groups of islands"));
    out.add(new Subdivision("UM-95", "Palmyra Atoll", null, "Islands, groups of islands"));
    out.add(new Subdivision("US-AK", "Alaska", null, "State"));
    out.add(new Subdivision("US-AL", "Alabama", null, "State"));
    out.add(new Subdivision("US-AR", "Arkansas", null, "State"));
    out.add(new Subdivision("US-AS", "American Samoa", null, "Outlying area"));
    out.add(new Subdivision("US-AZ", "Arizona", null, "State"));
    out.add(new Subdivision("US-CA", "California", null, "State"));
    out.add(new Subdivision("US-CO", "Colorado", null, "State"));
    out.add(new Subdivision("US-CT", "Connecticut", null, "State"));
    out.add(new Subdivision("US-DC", "District of Columbia", null, "District"));
    out.add(new Subdivision("US-DE", "Delaware", null, "State"));
    out.add(new Subdivision("US-FL", "Florida", null, "State"));
    out.add(new Subdivision("US-GA", "Georgia", null, "State"));
    out.add(new Subdivision("US-GU", "Guam", null, "Outlying area"));
    out.add(new Subdivision("US-HI", "Hawaii", null, "State"));
    out.add(new Subdivision("US-IA", "Iowa", null, "State"));
    out.add(new Subdivision("US-ID", "Idaho", null, "State"));
    out.add(new Subdivision("US-IL", "Illinois", null, "State"));
    out.add(new Subdivision("US-IN", "Indiana", null, "State"));
    out.add(new Subdivision("US-KS", "Kansas", null, "State"));
    out.add(new Subdivision("US-KY", "Kentucky", null, "State"));
    out.add(new Subdivision("US-LA", "Louisiana", null, "State"));
    out.add(new Subdivision("US-MA", "Massachusetts", null, "State"));
    out.add(new Subdivision("US-MD", "Maryland", null, "State"));
    out.add(new Subdivision("US-ME", "Maine", null, "State"));
    out.add(new Subdivision("US-MI", "Michigan", null, "State"));
    out.add(new Subdivision("US-MN", "Minnesota", null, "State"));
    out.add(new Subdivision("US-MO", "Missouri", null, "State"));
    out.add(new Subdivision("US-MP", "Northern Mariana Islands", null, "Outlying area"));
    out.add(new Subdivision("US-MS", "Mississippi", null, "State"));
    out.add(new Subdivision("US-MT", "Montana", null, "State"));
    out.add(new Subdivision("US-NC", "North Carolina", null, "State"));
    out.add(new Subdivision("US-ND", "North Dakota", null, "State"));
    out.add(new Subdivision("US-NE", "Nebraska", null, "State"));
    out.add(new Subdivision("US-NH", "New Hampshire", null, "State"));
    out.add(new Subdivision("US-NJ", "New Jersey", null, "State"));
    out.add(new Subdivision("US-NM", "New Mexico", null, "State"));
    out.add(new Subdivision("US-NV", "Nevada", null, "State"));
    out.add(new Subdivision("US-NY", "New York", null, "State"));
    out.add(new Subdivision("US-OH", "Ohio", null, "State"));
    out.add(new Subdivision("US-OK", "Oklahoma", null, "State"));
    out.add(new Subdivision("US-OR", "Oregon", null, "State"));
    out.add(new Subdivision("US-PA", "Pennsylvania", null, "State"));
    out.add(new Subdivision("US-PR", "Puerto Rico", null, "Outlying area"));
    out.add(new Subdivision("US-RI", "Rhode Island", null, "State"));
    out.add(new Subdivision("US-SC", "South Carolina", null, "State"));
    out.add(new Subdivision("US-SD", "South Dakota", null, "State"));
    out.add(new Subdivision("US-TN", "Tennessee", null, "State"));
    out.add(new Subdivision("US-TX", "Texas", null, "State"));
    out.add(new Subdivision("US-UM", "United States Minor Outlying Islands", null, "Outlying area"));
    out.add(new Subdivision("US-UT", "Utah", null, "State"));
    out.add(new Subdivision("US-VA", "Virginia", null, "State"));
    out.add(new Subdivision("US-VI", "Virgin Islands, U.S.", null, "Outlying area"));
    out.add(new Subdivision("US-VT", "Vermont", null, "State"));
    out.add(new Subdivision("US-WA", "Washington", null, "State"));
    out.add(new Subdivision("US-WI", "Wisconsin", null, "State"));
    out.add(new Subdivision("US-WV", "West Virginia", null, "State"));
    out.add(new Subdivision("US-WY", "Wyoming", null, "State"));
    out.add(new Subdivision("UY-AR", "Artigas", null, "Department"));
    out.add(new Subdivision("UY-CA", "Canelones", null, "Department"));
    out.add(new Subdivision("UY-CL", "Cerro Largo", null, "Department"));
    out.add(new Subdivision("UY-CO", "Colonia", null, "Department"));
    out.add(new Subdivision("UY-DU", "Durazno", null, "Department"));
    out.add(new Subdivision("UY-FD", "Florida", null, "Department"));
    out.add(new Subdivision("UY-FS", "Flores", null, "Department"));
    out.add(new Subdivision("UY-LA", "Lavalleja", null, "Department"));
    out.add(new Subdivision("UY-MA", "Maldonado", null, "Department"));
    out.add(new Subdivision("UY-MO", "Montevideo", null, "Department"));
    out.add(new Subdivision("UY-PA", "Paysandú", null, "Department"));
    out.add(new Subdivision("UY-RN", "Río Negro", null, "Department"));
    out.add(new Subdivision("UY-RO", "Rocha", null, "Department"));
    out.add(new Subdivision("UY-RV", "Rivera", null, "Department"));
    out.add(new Subdivision("UY-SA", "Salto", null, "Department"));
    out.add(new Subdivision("UY-SJ", "San José", null, "Department"));
    out.add(new Subdivision("UY-SO", "Soriano", null, "Department"));
    out.add(new Subdivision("UY-TA", "Tacuarembó", null, "Department"));
    out.add(new Subdivision("UY-TT", "Treinta y Tres", null, "Department"));
    out.add(new Subdivision("UZ-AN", "Andijon", null, "Region"));
    out.add(new Subdivision("UZ-BU", "Buxoro", null, "Region"));
    out.add(new Subdivision("UZ-FA", "Farg‘ona", null, "Region"));
    out.add(new Subdivision("UZ-JI", "Jizzax", null, "Region"));
    out.add(new Subdivision("UZ-NG", "Namangan", null, "Region"));
    out.add(new Subdivision("UZ-NW", "Navoiy", null, "Region"));
    out.add(new Subdivision("UZ-QA", "Qashqadaryo", null, "Region"));
    out.add(new Subdivision("UZ-QR", "Qoraqalpog‘iston Respublikasi", null, "Republic"));
    out.add(new Subdivision("UZ-SA", "Samarqand", null, "Region"));
    out.add(new Subdivision("UZ-SI", "Sirdaryo", null, "Region"));
    out.add(new Subdivision("UZ-SU", "Surxondaryo", null, "Region"));
    out.add(new Subdivision("UZ-TK", "Toshkent", null, "City"));
    out.add(new Subdivision("UZ-TO", "Toshkent", null, "Region"));
    out.add(new Subdivision("UZ-XO", "Xorazm", null, "Region"));
    out.add(new Subdivision("VC-01", "Charlotte", null, "Parish"));
    out.add(new Subdivision("VC-02", "Saint Andrew", null, "Parish"));
    out.add(new Subdivision("VC-03", "Saint David", null, "Parish"));
    out.add(new Subdivision("VC-04", "Saint George", null, "Parish"));
    out.add(new Subdivision("VC-05", "Saint Patrick", null, "Parish"));
    out.add(new Subdivision("VC-06", "Grenadines", null, "Parish"));
    out.add(new Subdivision("VE-A", "Distrito Capital", null, "Capital district"));
    out.add(new Subdivision("VE-B", "Anzoátegui", null, "State"));
    out.add(new Subdivision("VE-C", "Apure", null, "State"));
    out.add(new Subdivision("VE-D", "Aragua", null, "State"));
    out.add(new Subdivision("VE-E", "Barinas", null, "State"));
    out.add(new Subdivision("VE-F", "Bolívar", null, "State"));
    out.add(new Subdivision("VE-G", "Carabobo", null, "State"));
    out.add(new Subdivision("VE-H", "Cojedes", null, "State"));
    out.add(new Subdivision("VE-I", "Falcón", null, "State"));
    out.add(new Subdivision("VE-J", "Guárico", null, "State"));
    out.add(new Subdivision("VE-K", "Lara", null, "State"));
    out.add(new Subdivision("VE-L", "Mérida", null, "State"));
    out.add(new Subdivision("VE-M", "Miranda", null, "State"));
    out.add(new Subdivision("VE-N", "Monagas", null, "State"));
    out.add(new Subdivision("VE-O", "Nueva Esparta", null, "State"));
    out.add(new Subdivision("VE-P", "Portuguesa", null, "State"));
    out.add(new Subdivision("VE-R", "Sucre", null, "State"));
    out.add(new Subdivision("VE-S", "Táchira", null, "State"));
    out.add(new Subdivision("VE-T", "Trujillo", null, "State"));
    out.add(new Subdivision("VE-U", "Yaracuy", null, "State"));
    out.add(new Subdivision("VE-V", "Zulia", null, "State"));
    out.add(new Subdivision("VE-W", "Dependencias Federales", null, "Federal dependency"));
    out.add(new Subdivision("VE-X", "La Guaira", null, "State"));
    out.add(new Subdivision("VE-Y", "Delta Amacuro", null, "State"));
    out.add(new Subdivision("VE-Z", "Amazonas", null, "State"));
    out.add(new Subdivision("VN-01", "Lai Châu", null, "Province"));
    out.add(new Subdivision("VN-02", "Lào Cai", null, "Province"));
    out.add(new Subdivision("VN-03", "Hà Giang", null, "Province"));
    out.add(new Subdivision("VN-04", "Cao Bằng", null, "Province"));
    out.add(new Subdivision("VN-05", "Sơn La", null, "Province"));
    out.add(new Subdivision("VN-06", "Yên Bái", null, "Province"));
    out.add(new Subdivision("VN-07", "Tuyên Quang", null, "Province"));
    out.add(new Subdivision("VN-09", "Lạng Sơn", null, "Province"));
    out.add(new Subdivision("VN-13", "Quảng Ninh", null, "Province"));
    out.add(new Subdivision("VN-14", "Hòa Bình", null, "Province"));
    out.add(new Subdivision("VN-18", "Ninh Bình", null, "Province"));
    out.add(new Subdivision("VN-20", "Thái Bình", null, "Province"));
    out.add(new Subdivision("VN-21", "Thanh Hóa", null, "Province"));
    out.add(new Subdivision("VN-22", "Nghệ An", null, "Province"));
    out.add(new Subdivision("VN-23", "Hà Tĩnh", null, "Province"));
    out.add(new Subdivision("VN-24", "Quảng Bình", null, "Province"));
    out.add(new Subdivision("VN-25", "Quảng Trị", null, "Province"));
    out.add(new Subdivision("VN-26", "Thừa Thiên-Huế", null, "Province"));
    out.add(new Subdivision("VN-27", "Quảng Nam", null, "Province"));
    out.add(new Subdivision("VN-28", "Kon Tum", null, "Province"));
    out.add(new Subdivision("VN-29", "Quảng Ngãi", null, "Province"));
    out.add(new Subdivision("VN-30", "Gia Lai", null, "Province"));
    out.add(new Subdivision("VN-31", "Bình Định", null, "Province"));
    out.add(new Subdivision("VN-32", "Phú Yên", null, "Province"));
    out.add(new Subdivision("VN-33", "Đắk Lắk", null, "Province"));
    out.add(new Subdivision("VN-34", "Khánh Hòa", null, "Province"));
    out.add(new Subdivision("VN-35", "Lâm Đồng", null, "Province"));
    out.add(new Subdivision("VN-36", "Ninh Thuận", null, "Province"));
    out.add(new Subdivision("VN-37", "Tây Ninh", null, "Province"));
    out.add(new Subdivision("VN-39", "Đồng Nai", null, "Province"));
    out.add(new Subdivision("VN-40", "Bình Thuận", null, "Province"));
    out.add(new Subdivision("VN-41", "Long An", null, "Province"));
    out.add(new Subdivision("VN-43", "Bà Rịa - Vũng Tàu", null, "Province"));
    out.add(new Subdivision("VN-44", "An Giang", null, "Province"));
    out.add(new Subdivision("VN-45", "Đồng Tháp", null, "Province"));
    out.add(new Subdivision("VN-46", "Tiền Giang", null, "Province"));
    out.add(new Subdivision("VN-47", "Kiến Giang", null, "Province"));
    out.add(new Subdivision("VN-49", "Vĩnh Long", null, "Province"));
    out.add(new Subdivision("VN-50", "Bến Tre", null, "Province"));
    out.add(new Subdivision("VN-51", "Trà Vinh", null, "Province"));
    out.add(new Subdivision("VN-52", "Sóc Trăng", null, "Province"));
    out.add(new Subdivision("VN-53", "Bắc Kạn", null, "Province"));
    out.add(new Subdivision("VN-54", "Bắc Giang", null, "Province"));
    out.add(new Subdivision("VN-55", "Bạc Liêu", null, "Province"));
    out.add(new Subdivision("VN-56", "Bắc Ninh", null, "Province"));
    out.add(new Subdivision("VN-57", "Bình Dương", null, "Province"));
    out.add(new Subdivision("VN-58", "Bình Phước", null, "Province"));
    out.add(new Subdivision("VN-59", "Cà Mau", null, "Province"));
    out.add(new Subdivision("VN-61", "Hải Dương", null, "Province"));
    out.add(new Subdivision("VN-63", "Hà Nam", null, "Province"));
    out.add(new Subdivision("VN-66", "Hưng Yên", null, "Province"));
    out.add(new Subdivision("VN-67", "Nam Định", null, "Province"));
    out.add(new Subdivision("VN-68", "Phú Thọ", null, "Province"));
    out.add(new Subdivision("VN-69", "Thái Nguyên", null, "Province"));
    out.add(new Subdivision("VN-70", "Vĩnh Phúc", null, "Province"));
    out.add(new Subdivision("VN-71", "Điện Biên", null, "Province"));
    out.add(new Subdivision("VN-72", "Đắk Nông", null, "Province"));
    out.add(new Subdivision("VN-73", "Hậu Giang", null, "Province"));
    out.add(new Subdivision("VN-CT", "Cần Thơ", null, "Municipality"));
    out.add(new Subdivision("VN-DN", "Đà Nẵng", null, "Municipality"));
    out.add(new Subdivision("VN-HN", "Hà Nội", null, "Municipality"));
    out.add(new Subdivision("VN-HP", "Hải Phòng", null, "Municipality"));
    out.add(new Subdivision("VN-SG", "Hồ Chí Minh", null, "Municipality"));
    out.add(new Subdivision("VU-MAP", "Malampa", null, "Province"));
    out.add(new Subdivision("VU-PAM", "Pénama", null, "Province"));
    out.add(new Subdivision("VU-SAM", "Sanma", null, "Province"));
    out.add(new Subdivision("VU-SEE", "Shéfa", null, "Province"));
    out.add(new Subdivision("VU-TAE", "Taféa", null, "Province"));
    out.add(new Subdivision("VU-TOB", "Torba", null, "Province"));
    out.add(new Subdivision("WF-AL", "Alo", null, "Administrative precinct"));
    out.add(new Subdivision("WF-SG", "Sigave", null, "Administrative precinct"));
    out.add(new Subdivision("WF-UV", "Uvea", null, "Administrative precinct"));
    out.add(new Subdivision("WS-AA", "A'ana", null, "District"));
    out.add(new Subdivision("WS-AL", "Aiga-i-le-Tai", null, "District"));
    out.add(new Subdivision("WS-AT", "Atua", null, "District"));
    out.add(new Subdivision("WS-FA", "Fa'asaleleaga", null, "District"));
    out.add(new Subdivision("WS-GE", "Gaga'emauga", null, "District"));
    out.add(new Subdivision("WS-GI", "Gagaifomauga", null, "District"));
    out.add(new Subdivision("WS-PA", "Palauli", null, "District"));
    out.add(new Subdivision("WS-SA", "Satupa'itea", null, "District"));
    out.add(new Subdivision("WS-TU", "Tuamasaga", null, "District"));
    out.add(new Subdivision("WS-VF", "Va'a-o-Fonoti", null, "District"));
    out.add(new Subdivision("WS-VS", "Vaisigano", null, "District"));
    out.add(new Subdivision("YE-AB", "Abyan", null, "Governorate"));
    out.add(new Subdivision("YE-AD", "‘Adan", null, "Governorate"));
    out.add(new Subdivision("YE-AM", "‘Amrān", null, "Governorate"));
    out.add(new Subdivision("YE-BA", "Al Bayḑā’", null, "Governorate"));
    out.add(new Subdivision("YE-DA", "Aḑ Ḑāli‘", null, "Governorate"));
  }
}
