// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 2000 to 2499 of {@link Subdivision}.
 */
final class SubdivisionData4 {
  private SubdivisionData4() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("IN-AS", "Assam", null, "State"));
    out.add(new Subdivision("IN-BR", "Bihār", null, "State"));
    out.add(new Subdivision("IN-CG", "Chhattīsgarh", null, "State"));
    out.add(new Subdivision("IN-CH", "Chandīgarh", null, "Union territory"));
    out.add(new Subdivision("IN-DH", "Dādra and Nagar Haveli and Damān and Diu", null, "Union territory"));
    out.add(new Subdivision("IN-DL", "Delhi", null, "Union territory"));
    out.add(new Subdivision("IN-GA", "Goa", null, "State"));
    out.add(new Subdivision("IN-GJ", "Gujarāt", null, "State"));
    out.add(new Subdivision("IN-HP", "Himāchal Pradesh", null, "State"));
    out.add(new Subdivision("IN-HR", "Haryāna", null, "State"));
    out.add(new Subdivision("IN-JH", "Jhārkhand", null, "State"));
    out.add(new Subdivision("IN-JK", "Jammu and Kashmīr", null, "Union territory"));
    out.add(new Subdivision("IN-KA", "Karnātaka", null, "State"));
    out.add(new Subdivision("IN-KL", "Kerala", null, "State"));
    out.add(new Subdivision("IN-LA", "Ladākh", null, "Union territory"));
    out.add(new Subdivision("IN-LD", "Lakshadweep", null, "Union territory"));
    out.add(new Subdivision("IN-MH", "Mahārāshtra", null, "State"));
    out.add(new Subdivision("IN-ML", "Meghālaya", null, "State"));
    out.add(new Subdivision("IN-MN", "Manipur", null, "State"));
    out.add(new Subdivision("IN-MP", "Madhya Pradesh", null, "State"));
    out.add(new Subdivision("IN-MZ", "Mizoram", null, "State"));
    out.add(new Subdivision("IN-NL", "Nāgāland", null, "State"));
    out.add(new Subdivision("IN-OD", "Odisha", null, "State"));
    out.add(new Subdivision("IN-PB", "Punjab", null, "State"));
    out.add(new Subdivision("IN-PY", "Puducherry", null, "Union territory"));
    out.add(new Subdivision("IN-RJ", "Rājasthān", null, "State"));
    out.add(new Subdivision("IN-SK", "Sikkim", null, "State"));
    out.add(new Subdivision("IN-TN", "Tamil Nādu", null, "State"));
    out.add(new Subdivision("IN-TR", "Tripura", null, "State"));
    out.add(new Subdivision("IN-TS", "Telangāna", null, "State"));
    out.add(new Subdivision("IN-UK", "Uttarākhand", null, "State"));
    out.add(new Subdivision("IN-UP", "Uttar Pradesh", null, "State"));
    out.add(new Subdivision("IN-WB", "West Bengal", null, "State"));
    out.add(new Subdivision("IQ-AN", "Al Anbār", null, "Governorate"));
    out.add(new Subdivision("IQ-AR", "Arbīl", "IQ-KR", "Governorate"));
    out.add(new Subdivision("IQ-BA", "Al Başrah", null, "Governorate"));
    out.add(new Subdivision("IQ-BB", "Bābil", null, "Governorate"));
    out.add(new Subdivision("IQ-BG", "Baghdād", null, "Governorate"));
    out.add(new Subdivision("IQ-DA", "Dahūk", "IQ-KR", "Governorate"));
    out.add(new Subdivision("IQ-DI", "Diyālá", null, "Governorate"));
    out.add(new Subdivision("IQ-DQ", "Dhī Qār", null, "Governorate"));
    out.add(new Subdivision("IQ-KA", "Karbalā’", null, "Governorate"));
    out.add(new Subdivision("IQ-KI", "Kirkūk", null, "Governorate"));
    out.add(new Subdivision("IQ-KR", "Iqlīm Kūrdistān", null, "Region"));
    out.add(new Subdivision("IQ-MA", "Maysān", null, "Governorate"));
    out.add(new Subdivision("IQ-MU", "Al Muthanná", null, "Governorate"));
    out.add(new Subdivision("IQ-NA", "An Najaf", null, "Governorate"));
    out.add(new Subdivision("IQ-NI", "Nīnawá", null, "Governorate"));
    out.add(new Subdivision("IQ-QA", "Al Qādisīyah", null, "Governorate"));
    out.add(new Subdivision("IQ-SD", "Şalāḩ ad Dīn", null, "Governorate"));
    out.add(new Subdivision("IQ-SU", "As Sulaymānīyah", "IQ-KR", "Governorate"));
    out.add(new Subdivision("IQ-WA", "Wāsiţ", null, "Governorate"));
    out.add(new Subdivision("IR-00", "Markazī", null, "Province"));
    out.add(new Subdivision("IR-01", "Gīlān", null, "Province"));
    out.add(new Subdivision("IR-02", "Māzandarān", null, "Province"));
    out.add(new Subdivision("IR-03", "Āz̄ārbāyjān-e Shārqī", null, "Province"));
    out.add(new Subdivision("IR-04", "Āz̄ārbāyjān-e Ghārbī", null, "Province"));
    out.add(new Subdivision("IR-05", "Kermānshāh", null, "Province"));
    out.add(new Subdivision("IR-06", "Khūzestān", null, "Province"));
    out.add(new Subdivision("IR-07", "Fārs", null, "Province"));
    out.add(new Subdivision("IR-08", "Kermān", null, "Province"));
    out.add(new Subdivision("IR-09", "Khorāsān-e Raẕavī", null, "Province"));
    out.add(new Subdivision("IR-10", "Eşfahān", null, "Province"));
    out.add(new Subdivision("IR-11", "Sīstān va Balūchestān", null, "Province"));
    out.add(new Subdivision("IR-12", "Kordestān", null, "Province"));
    out.add(new Subdivision("IR-13", "Hamadān", null, "Province"));
    out.add(new Subdivision("IR-14", "Chahār Maḩāl va Bakhtīārī", null, "Province"));
    out.add(new Subdivision("IR-15", "Lorestān", null, "Province"));
    out.add(new Subdivision("IR-16", "Īlām", null, "Province"));
    out.add(new Subdivision("IR-17", "Kohgīlūyeh va Bowyer Aḩmad", null, "Province"));
    out.add(new Subdivision("IR-18", "Būshehr", null, "Province"));
    out.add(new Subdivision("IR-19", "Zanjān", null, "Province"));
    out.add(new Subdivision("IR-20", "Semnān", null, "Province"));
    out.add(new Subdivision("IR-21", "Yazd", null, "Province"));
    out.add(new Subdivision("IR-22", "Hormozgān", null, "Province"));
    out.add(new Subdivision("IR-23", "Tehrān", null, "Province"));
    out.add(new Subdivision("IR-24", "Ardabīl", null, "Province"));
    out.add(new Subdivision("IR-25", "Qom", null, "Province"));
    out.add(new Subdivision("IR-26", "Qazvīn", null, "Province"));
    out.add(new Subdivision("IR-27", "Golestān", null, "Province"));
    out.add(new Subdivision("IR-28", "Khorāsān-e Shomālī", null, "Province"));
    out.add(new Subdivision("IR-29", "Khorāsān-e Jonūbī", null, "Province"));
    out.add(new Subdivision("IR-30", "Alborz", null, "Province"));
    out.add(new Subdivision("IS-1", "Höfuðborgarsvæði", null, "Region"));
    out.add(new Subdivision("IS-2", "Suðurnes", null, "Region"));
    out.add(new Subdivision("IS-3", "Vesturland", null, "Region"));
    out.add(new Subdivision("IS-4", "Vestfirðir", null, "Region"));
    out.add(new Subdivision("IS-5", "Norðurland vestra", null, "Region"));
    out.add(new Subdivision("IS-6", "Norðurland eystra", null, "Region"));
    out.add(new Subdivision("IS-7", "Austurland", null, "Region"));
    out.add(new Subdivision("IS-8", "Suðurland", null, "Region"));
    out.add(new Subdivision("IS-AKN", "Akraneskaupstaður", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-AKU", "Akureyrarbær", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-ARN", "Árneshreppur", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-ASA", "Ásahreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-BLA", "Bláskógabyggð", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-BOG", "Borgarbyggð", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-BOL", "Bolungarvíkurkaupstaður", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-DAB", "Dalabyggð", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-DAV", "Dalvíkurbyggð", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-EOM", "Eyja- og Miklaholtshreppur", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-EYF", "Eyjafjarðarsveit", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-FJD", "Fjarðabyggð", "IS-7", "Municipality"));
    out.add(new Subdivision("IS-FJL", "Fjallabyggð", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-FLA", "Flóahreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-FLR", "Fljótsdalshreppur", "IS-7", "Municipality"));
    out.add(new Subdivision("IS-GAR", "Garðabær", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-GOG", "Grímsnes- og Grafningshreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-GRN", "Grindavíkurbær", "IS-2", "Municipality"));
    out.add(new Subdivision("IS-GRU", "Grundarfjarðarbær", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-GRY", "Grýtubakkahreppur", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-HAF", "Hafnarfjarðarkaupstaður", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-HRG", "Hörgársveit", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-HRU", "Hrunamannahreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-HUG", "Húnabyggð", "IS-5", "Municipality"));
    out.add(new Subdivision("IS-HUV", "Húnaþing vestra", "IS-5", "Municipality"));
    out.add(new Subdivision("IS-HVA", "Hvalfjarðarsveit", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-HVE", "Hveragerðisbær", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-ISA", "Ísafjarðarbær", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-KAL", "Kaldrananeshreppur", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-KJO", "Kjósarhreppur", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-KOP", "Kópavogsbær", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-LAN", "Langanesbyggð", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-MOS", "Mosfellsbær", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-MUL", "Múlaþing", "IS-7", "Municipality"));
    out.add(new Subdivision("IS-MYR", "Mýrdalshreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-NOR", "Norðurþing", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-RGE", "Rangárþing eystra", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-RGY", "Rangárþing ytra", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-RHH", "Reykhólahreppur", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-RKN", "Reykjanesbær", "IS-2", "Municipality"));
    out.add(new Subdivision("IS-RKV", "Reykjavíkurborg", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-SBT", "Svalbarðsstrandarhreppur", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-SDN", "Suðurnesjabær", "IS-2", "Municipality"));
    out.add(new Subdivision("IS-SDV", "Súðavíkurhreppur", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-SEL", "Seltjarnarnesbær", "IS-1", "Municipality"));
    out.add(new Subdivision("IS-SFA", "Sveitarfélagið Árborg", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-SHF", "Sveitarfélagið Hornafjörður", "IS-7", "Municipality"));
    out.add(new Subdivision("IS-SKF", "Skaftárhreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-SKG", "Skagabyggð", "IS-5", "Municipality"));
    out.add(new Subdivision("IS-SKO", "Skorradalshreppur", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-SKR", "Skagafjörður", "IS-5", "Municipality"));
    out.add(new Subdivision("IS-SNF", "Snæfellsbær", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-SOG", "Skeiða- og Gnúpverjahreppur", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-SOL", "Sveitarfélagið Ölfus", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-SSS", "Sveitarfélagið Skagaströnd", "IS-5", "Municipality"));
    out.add(new Subdivision("IS-STR", "Strandabyggð", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-STY", "Stykkishólmsbær", "IS-3", "Municipality"));
    out.add(new Subdivision("IS-SVG", "Sveitarfélagið Vogar", "IS-2", "Municipality"));
    out.add(new Subdivision("IS-TAL", "Tálknafjarðarhreppur", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-THG", "Þingeyjarsveit", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-TJO", "Tjörneshreppur", "IS-6", "Municipality"));
    out.add(new Subdivision("IS-VEM", "Vestmannaeyjabær", "IS-8", "Municipality"));
    out.add(new Subdivision("IS-VER", "Vesturbyggð", "IS-4", "Municipality"));
    out.add(new Subdivision("IS-VOP", "Vopnafjarðarhreppur", "IS-7", "Municipality"));
    out.add(new Subdivision("IT-21", "Piemonte", null, "Region"));
    out.add(new Subdivision("IT-23", "Valle d'Aosta", null, "Autonomous region"));
    out.add(new Subdivision("IT-25", "Lombardia", null, "Region"));
    out.add(new Subdivision("IT-32", "Trentino-Alto Adige", null, "Autonomous region"));
    out.add(new Subdivision("IT-34", "Veneto", null, "Region"));
    out.add(new Subdivision("IT-36", "Friuli Venezia Giulia", null, "Autonomous region"));
    out.add(new Subdivision("IT-42", "Liguria", null, "Region"));
    out.add(new Subdivision("IT-45", "Emilia-Romagna", null, "Region"));
    out.add(new Subdivision("IT-52", "Toscana", null, "Region"));
    out.add(new Subdivision("IT-55", "Umbria", null, "Region"));
    out.add(new Subdivision("IT-57", "Marche", null, "Region"));
    out.add(new Subdivision("IT-62", "Lazio", null, "Region"));
    out.add(new Subdivision("IT-65", "Abruzzo", null, "Region"));
    out.add(new Subdivision("IT-67", "Molise", null, "Region"));
    out.add(new Subdivision("IT-72", "Campania", null, "Region"));
    out.add(new Subdivision("IT-75", "Puglia", null, "Region"));
    out.add(new Subdivision("IT-77", "Basilicata", null, "Region"));
    out.add(new Subdivision("IT-78", "Calabria", null, "Region"));
    out.add(new Subdivision("IT-82", "Sicilia", null, "Autonomous region"));
    out.add(new Subdivision("IT-88", "Sardegna", null, "Autonomous region"));
    out.add(new Subdivision("IT-AG", "Agrigento", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-AL", "Alessandria", "IT-21", "Province"));
    out.add(new Subdivision("IT-AN", "Ancona", "IT-57", "Province"));
    out.add(new Subdivision("IT-AP", "Ascoli Piceno", "IT-57", "Province"));
    out.add(new Subdivision("IT-AQ", "L'Aquila", "IT-65", "Province"));
    out.add(new Subdivision("IT-AR", "Arezzo", "IT-52", "Province"));
    out.add(new Subdivision("IT-AT", "Asti", "IT-21", "Province"));
    out.add(new Subdivision("IT-AV", "Avellino", "IT-72", "Province"));
    out.add(new Subdivision("IT-BA", "Bari", "IT-75", "Metropolitan city"));
    out.add(new Subdivision("IT-BG", "Bergamo", "IT-25", "Province"));
    out.add(new Subdivision("IT-BI", "Biella", "IT-21", "Province"));
    out.add(new Subdivision("IT-BL", "Belluno", "IT-34", "Province"));
    out.add(new Subdivision("IT-BN", "Benevento", "IT-72", "Province"));
    out.add(new Subdivision("IT-BO", "Bologna", "IT-45", "Metropolitan city"));
    out.add(new Subdivision("IT-BR", "Brindisi", "IT-75", "Province"));
    out.add(new Subdivision("IT-BS", "Brescia", "IT-25", "Province"));
    out.add(new Subdivision("IT-BT", "Barletta-Andria-Trani", "IT-75", "Province"));
    out.add(new Subdivision("IT-BZ", "Bolzano", "IT-32", "Autonomous province"));
    out.add(new Subdivision("IT-CA", "Cagliari", "IT-88", "Metropolitan city"));
    out.add(new Subdivision("IT-CB", "Campobasso", "IT-67", "Province"));
    out.add(new Subdivision("IT-CE", "Caserta", "IT-72", "Province"));
    out.add(new Subdivision("IT-CH", "Chieti", "IT-65", "Province"));
    out.add(new Subdivision("IT-CL", "Caltanissetta", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-CN", "Cuneo", "IT-21", "Province"));
    out.add(new Subdivision("IT-CO", "Como", "IT-25", "Province"));
    out.add(new Subdivision("IT-CR", "Cremona", "IT-25", "Province"));
    out.add(new Subdivision("IT-CS", "Cosenza", "IT-78", "Province"));
    out.add(new Subdivision("IT-CT", "Catania", "IT-82", "Metropolitan city"));
    out.add(new Subdivision("IT-CZ", "Catanzaro", "IT-78", "Province"));
    out.add(new Subdivision("IT-EN", "Enna", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-FC", "Forlì-Cesena", "IT-45", "Province"));
    out.add(new Subdivision("IT-FE", "Ferrara", "IT-45", "Province"));
    out.add(new Subdivision("IT-FG", "Foggia", "IT-75", "Province"));
    out.add(new Subdivision("IT-FI", "Firenze", "IT-52", "Metropolitan city"));
    out.add(new Subdivision("IT-FM", "Fermo", "IT-57", "Province"));
    out.add(new Subdivision("IT-FR", "Frosinone", "IT-62", "Province"));
    out.add(new Subdivision("IT-GE", "Genova", "IT-42", "Metropolitan city"));
    out.add(new Subdivision("IT-GO", "Gorizia", "IT-36", "Decentralized regional entity"));
    out.add(new Subdivision("IT-GR", "Grosseto", "IT-52", "Province"));
    out.add(new Subdivision("IT-IM", "Imperia", "IT-42", "Province"));
    out.add(new Subdivision("IT-IS", "Isernia", "IT-67", "Province"));
    out.add(new Subdivision("IT-KR", "Crotone", "IT-78", "Province"));
    out.add(new Subdivision("IT-LC", "Lecco", "IT-25", "Province"));
    out.add(new Subdivision("IT-LE", "Lecce", "IT-75", "Province"));
    out.add(new Subdivision("IT-LI", "Livorno", "IT-52", "Province"));
    out.add(new Subdivision("IT-LO", "Lodi", "IT-25", "Province"));
    out.add(new Subdivision("IT-LT", "Latina", "IT-62", "Province"));
    out.add(new Subdivision("IT-LU", "Lucca", "IT-52", "Province"));
    out.add(new Subdivision("IT-MB", "Monza e Brianza", "IT-25", "Province"));
    out.add(new Subdivision("IT-MC", "Macerata", "IT-57", "Province"));
    out.add(new Subdivision("IT-ME", "Messina", "IT-82", "Metropolitan city"));
    out.add(new Subdivision("IT-MI", "Milano", "IT-25", "Metropolitan city"));
    out.add(new Subdivision("IT-MN", "Mantova", "IT-25", "Province"));
    out.add(new Subdivision("IT-MO", "Modena", "IT-45", "Province"));
    out.add(new Subdivision("IT-MS", "Massa-Carrara", "IT-52", "Province"));
    out.add(new Subdivision("IT-MT", "Matera", "IT-77", "Province"));
    out.add(new Subdivision("IT-NA", "Napoli", "IT-72", "Metropolitan city"));
    out.add(new Subdivision("IT-NO", "Novara", "IT-21", "Province"));
    out.add(new Subdivision("IT-NU", "Nuoro", "IT-88", "Province"));
    out.add(new Subdivision("IT-OR", "Oristano", "IT-88", "Province"));
    out.add(new Subdivision("IT-PA", "Palermo", "IT-82", "Metropolitan city"));
    out.add(new Subdivision("IT-PC", "Piacenza", "IT-45", "Province"));
    out.add(new Subdivision("IT-PD", "Padova", "IT-34", "Province"));
    out.add(new Subdivision("IT-PE", "Pescara", "IT-65", "Province"));
    out.add(new Subdivision("IT-PG", "Perugia", "IT-55", "Province"));
    out.add(new Subdivision("IT-PI", "Pisa", "IT-52", "Province"));
    out.add(new Subdivision("IT-PN", "Pordenone", "IT-36", "Decentralized regional entity"));
    out.add(new Subdivision("IT-PO", "Prato", "IT-52", "Province"));
    out.add(new Subdivision("IT-PR", "Parma", "IT-45", "Province"));
    out.add(new Subdivision("IT-PT", "Pistoia", "IT-52", "Province"));
    out.add(new Subdivision("IT-PU", "Pesaro e Urbino", "IT-57", "Province"));
    out.add(new Subdivision("IT-PV", "Pavia", "IT-25", "Province"));
    out.add(new Subdivision("IT-PZ", "Potenza", "IT-77", "Province"));
    out.add(new Subdivision("IT-RA", "Ravenna", "IT-45", "Province"));
    out.add(new Subdivision("IT-RC", "Reggio Calabria", "IT-78", "Metropolitan city"));
    out.add(new Subdivision("IT-RE", "Reggio Emilia", "IT-45", "Province"));
    out.add(new Subdivision("IT-RG", "Ragusa", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-RI", "Rieti", "IT-62", "Province"));
    out.add(new Subdivision("IT-RM", "Roma", "IT-62", "Metropolitan city"));
    out.add(new Subdivision("IT-RN", "Rimini", "IT-45", "Province"));
    out.add(new Subdivision("IT-RO", "Rovigo", "IT-34", "Province"));
    out.add(new Subdivision("IT-SA", "Salerno", "IT-72", "Province"));
    out.add(new Subdivision("IT-SI", "Siena", "IT-52", "Province"));
    out.add(new Subdivision("IT-SO", "Sondrio", "IT-25", "Province"));
    out.add(new Subdivision("IT-SP", "La Spezia", "IT-42", "Province"));
    out.add(new Subdivision("IT-SR", "Siracusa", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-SS", "Sassari", "IT-88", "Province"));
    out.add(new Subdivision("IT-SU", "Sud Sardegna", "IT-88", "Province"));
    out.add(new Subdivision("IT-SV", "Savona", "IT-42", "Province"));
    out.add(new Subdivision("IT-TA", "Taranto", "IT-75", "Province"));
    out.add(new Subdivision("IT-TE", "Teramo", "IT-65", "Province"));
    out.add(new Subdivision("IT-TN", "Trento", "IT-32", "Autonomous province"));
    out.add(new Subdivision("IT-TO", "Torino", "IT-21", "Metropolitan city"));
    out.add(new Subdivision("IT-TP", "Trapani", "IT-82", "Free municipal consortium"));
    out.add(new Subdivision("IT-TR", "Terni", "IT-55", "Province"));
    out.add(new Subdivision("IT-TS", "Trieste", "IT-36", "Decentralized regional entity"));
    out.add(new Subdivision("IT-TV", "Treviso", "IT-34", "Province"));
    out.add(new Subdivision("IT-UD", "Udine", "IT-36", "Decentralized regional entity"));
    out.add(new Subdivision("IT-VA", "Varese", "IT-25", "Province"));
    out.add(new Subdivision("IT-VB", "Verbano-Cusio-Ossola", "IT-21", "Province"));
    out.add(new Subdivision("IT-VC", "Vercelli", "IT-21", "Province"));
    out.add(new Subdivision("IT-VE", "Venezia", "IT-34", "Metropolitan city"));
    out.add(new Subdivision("IT-VI", "Vicenza", "IT-34", "Province"));
    out.add(new Subdivision("IT-VR", "Verona", "IT-34", "Province"));
    out.add(new Subdivision("IT-VT", "Viterbo", "IT-62", "Province"));
    out.add(new Subdivision("IT-VV", "Vibo Valentia", "IT-78", "Province"));
    out.add(new Subdivision("JM-01", "Kingston", null, "Parish"));
    out.add(new Subdivision("JM-02", "Saint Andrew", null, "Parish"));
    out.add(new Subdivision("JM-03", "Saint Thomas", null, "Parish"));
    out.add(new Subdivision("JM-04", "Portland", null, "Parish"));
    out.add(new Subdivision("JM-05", "Saint Mary", null, "Parish"));
    out.add(new Subdivision("JM-06", "Saint Ann", null, "Parish"));
    out.add(new Subdivision("JM-07", "Trelawny", null, "Parish"));
    out.add(new Subdivision("JM-08", "Saint James", null, "Parish"));
    out.add(new Subdivision("JM-09", "Hanover", null, "Parish"));
    out.add(new Subdivision("JM-10", "Westmoreland", null, "Parish"));
    out.add(new Subdivision("JM-11", "Saint Elizabeth", null, "Parish"));
    out.add(new Subdivision("JM-12", "Manchester", null, "Parish"));
    out.add(new Subdivision("JM-13", "Clarendon", null, "Parish"));
    out.add(new Subdivision("JM-14", "Saint Catherine", null, "Parish"));
    out.add(new Subdivision("JO-AJ", "‘Ajlūn", null, "Governorate"));
    out.add(new Subdivision("JO-AM", "Al ‘A̅şimah", null, "Governorate"));
    out.add(new Subdivision("JO-AQ", "Al ‘Aqabah", null, "Governorate"));
    out.add(new Subdivision("JO-AT", "Aţ Ţafīlah", null, "Governorate"));
    out.add(new Subdivision("JO-AZ", "Az Zarqā’", null, "Governorate"));
    out.add(new Subdivision("JO-BA", "Al Balqā’", null, "Governorate"));
    out.add(new Subdivision("JO-IR", "Irbid", null, "Governorate"));
    out.add(new Subdivision("JO-JA", "Jarash", null, "Governorate"));
    out.add(new Subdivision("JO-KA", "Al Karak", null, "Governorate"));
    out.add(new Subdivision("JO-MA", "Al Mafraq", null, "Governorate"));
    out.add(new Subdivision("JO-MD", "Mādabā", null, "Governorate"));
    out.add(new Subdivision("JO-MN", "Ma‘ān", null, "Governorate"));
    out.add(new Subdivision("JP-01", "Hokkaido", null, "Prefecture"));
    out.add(new Subdivision("JP-02", "Aomori", null, "Prefecture"));
    out.add(new Subdivision("JP-03", "Iwate", null, "Prefecture"));
    out.add(new Subdivision("JP-04", "Miyagi", null, "Prefecture"));
    out.add(new Subdivision("JP-05", "Akita", null, "Prefecture"));
    out.add(new Subdivision("JP-06", "Yamagata", null, "Prefecture"));
    out.add(new Subdivision("JP-07", "Fukushima", null, "Prefecture"));
    out.add(new Subdivision("JP-08", "Ibaraki", null, "Prefecture"));
    out.add(new Subdivision("JP-09", "Tochigi", null, "Prefecture"));
    out.add(new Subdivision("JP-10", "Gunma", null, "Prefecture"));
    out.add(new Subdivision("JP-11", "Saitama", null, "Prefecture"));
    out.add(new Subdivision("JP-12", "Chiba", null, "Prefecture"));
    out.add(new Subdivision("JP-13", "Tokyo", null, "Prefecture"));
    out.add(new Subdivision("JP-14", "Kanagawa", null, "Prefecture"));
    out.add(new Subdivision("JP-15", "Niigata", null, "Prefecture"));
    out.add(new Subdivision("JP-16", "Toyama", null, "Prefecture"));
    out.add(new Subdivision("JP-17", "Ishikawa", null, "Prefecture"));
    out.add(new Subdivision("JP-18", "Fukui", null, "Prefecture"));
    out.add(new Subdivision("JP-19", "Yamanashi", null, "Prefecture"));
    out.add(new Subdivision("JP-20", "Nagano", null, "Prefecture"));
    out.add(new Subdivision("JP-21", "Gifu", null, "Prefecture"));
    out.add(new Subdivision("JP-22", "Shizuoka", null, "Prefecture"));
    out.add(new Subdivision("JP-23", "Aichi", null, "Prefecture"));
    out.add(new Subdivision("JP-24", "Mie", null, "Prefecture"));
    out.add(new Subdivision("JP-25", "Shiga", null, "Prefecture"));
    out.add(new Subdivision("JP-26", "Kyoto", null, "Prefecture"));
    out.add(new Subdivision("JP-27", "Osaka", null, "Prefecture"));
    out.add(new Subdivision("JP-28", "Hyogo", null, "Prefecture"));
    out.add(new Subdivision("JP-29", "Nara", null, "Prefecture"));
    out.add(new Subdivision("JP-30", "Wakayama", null, "Prefecture"));
    out.add(new Subdivision("JP-31", "Tottori", null, "Prefecture"));
    out.add(new Subdivision("JP-32", "Shimane", null, "Prefecture"));
    out.add(new Subdivision("JP-33", "Okayama", null, "Prefecture"));
    out.add(new Subdivision("JP-34", "Hiroshima", null, "Prefecture"));
    out.add(new Subdivision("JP-35", "Yamaguchi", null, "Prefecture"));
    out.add(new Subdivision("JP-36", "Tokushima", null, "Prefecture"));
    out.add(new Subdivision("JP-37", "Kagawa", null, "Prefecture"));
    out.add(new Subdivision("JP-38", "Ehime", null, "Prefecture"));
    out.add(new Subdivision("JP-39", "Kochi", null, "Prefecture"));
    out.add(new Subdivision("JP-40", "Fukuoka", null, "Prefecture"));
    out.add(new Subdivision("JP-41", "Saga", null, "Prefecture"));
    out.add(new Subdivision("JP-42", "Nagasaki", null, "Prefecture"));
    out.add(new Subdivision("JP-43", "Kumamoto", null, "Prefecture"));
    out.add(new Subdivision("JP-44", "Oita", null, "Prefecture"));
    out.add(new Subdivision("JP-45", "Miyazaki", null, "Prefecture"));
    out.add(new Subdivision("JP-46", "Kagoshima", null, "Prefecture"));
    out.add(new Subdivision("JP-47", "Okinawa", null, "Prefecture"));
    out.add(new Subdivision("KE-01", "Baringo", null, "County"));
    out.add(new Subdivision("KE-02", "Bomet", null, "County"));
    out.add(new Subdivision("KE-03", "Bungoma", null, "County"));
    out.add(new Subdivision("KE-04", "Busia", null, "County"));
    out.add(new Subdivision("KE-05", "Elgeyo/Marakwet", null, "County"));
    out.add(new Subdivision("KE-06", "Embu", null, "County"));
    out.add(new Subdivision("KE-07", "Garissa", null, "County"));
    out.add(new Subdivision("KE-08", "Homa Bay", null, "County"));
    out.add(new Subdivision("KE-09", "Isiolo", null, "County"));
    out.add(new Subdivision("KE-10", "Kajiado", null, "County"));
    out.add(new Subdivision("KE-11", "Kakamega", null, "County"));
    out.add(new Subdivision("KE-12", "Kericho", null, "County"));
    out.add(new Subdivision("KE-13", "Kiambu", null, "County"));
    out.add(new Subdivision("KE-14", "Kilifi", null, "County"));
    out.add(new Subdivision("KE-15", "Kirinyaga", null, "County"));
    out.add(new Subdivision("KE-16", "Kisii", null, "County"));
    out.add(new Subdivision("KE-17", "Kisumu", null, "County"));
    out.add(new Subdivision("KE-18", "Kitui", null, "County"));
    out.add(new Subdivision("KE-19", "Kwale", null, "County"));
    out.add(new Subdivision("KE-20", "Laikipia", null, "County"));
    out.add(new Subdivision("KE-21", "Lamu", null, "County"));
    out.add(new Subdivision("KE-22", "Machakos", null, "County"));
    out.add(new Subdivision("KE-23", "Makueni", null, "County"));
    out.add(new Subdivision("KE-24", "Mandera", null, "County"));
    out.add(new Subdivision("KE-25", "Marsabit", null, "County"));
    out.add(new Subdivision("KE-26", "Meru", null, "County"));
    out.add(new Subdivision("KE-27", "Migori", null, "County"));
    out.add(new Subdivision("KE-28", "Mombasa", null, "County"));
    out.add(new Subdivision("KE-29", "Murang'a", null, "County"));
    out.add(new Subdivision("KE-30", "Nairobi City", null, "County"));
    out.add(new Subdivision("KE-31", "Nakuru", null, "County"));
    out.add(new Subdivision("KE-32", "Nandi", null, "County"));
    out.add(new Subdivision("KE-33", "Narok", null, "County"));
    out.add(new Subdivision("KE-34", "Nyamira", null, "County"));
    out.add(new Subdivision("KE-35", "Nyandarua", null, "County"));
    out.add(new Subdivision("KE-36", "Nyeri", null, "County"));
    out.add(new Subdivision("KE-37", "Samburu", null, "County"));
    out.add(new Subdivision("KE-38", "Siaya", null, "County"));
    out.add(new Subdivision("KE-39", "Taita/Taveta", null, "County"));
    out.add(new Subdivision("KE-40", "Tana River", null, "County"));
    out.add(new Subdivision("KE-41", "Tharaka-Nithi", null, "County"));
    out.add(new Subdivision("KE-42", "Trans Nzoia", null, "County"));
    out.add(new Subdivision("KE-43", "Turkana", null, "County"));
    out.add(new Subdivision("KE-44", "Uasin Gishu", null, "County"));
    out.add(new Subdivision("KE-45", "Vihiga", null, "County"));
    out.add(new Subdivision("KE-46", "Wajir", null, "County"));
    out.add(new Subdivision("KE-47", "West Pokot", null, "County"));
    out.add(new Subdivision("KG-B", "Batken", null, "Region"));
    out.add(new Subdivision("KG-C", "Chüy", null, "Region"));
    out.add(new Subdivision("KG-GB", "Bishkek Shaary", null, "City"));
    out.add(new Subdivision("KG-GO", "Osh Shaary", null, "City"));
    out.add(new Subdivision("KG-J", "Jalal-Abad", null, "Region"));
    out.add(new Subdivision("KG-N", "Naryn", null, "Region"));
    out.add(new Subdivision("KG-O", "Osh", null, "Region"));
    out.add(new Subdivision("KG-T", "Talas", null, "Region"));
    out.add(new Subdivision("KG-Y", "Ysyk-Köl", null, "Region"));
    out.add(new Subdivision("KH-1", "Banteay Mean Choăy", null, "Province"));
    out.add(new Subdivision("KH-10", "Kracheh", null, "Province"));
    out.add(new Subdivision("KH-11", "Mondol Kiri", null, "Province"));
    out.add(new Subdivision("KH-12", "Phnom Penh", null, "Autonomous municipality"));
    out.add(new Subdivision("KH-13", "Preah Vihear", null, "Province"));
    out.add(new Subdivision("KH-14", "Prey Veaeng", null, "Province"));
    out.add(new Subdivision("KH-15", "Pousaat", null, "Province"));
    out.add(new Subdivision("KH-16", "Rotanak Kiri", null, "Province"));
    out.add(new Subdivision("KH-17", "Siem Reab", null, "Province"));
    out.add(new Subdivision("KH-18", "Preah Sihanouk", null, "Province"));
    out.add(new Subdivision("KH-19", "Stueng Traeng", null, "Province"));
    out.add(new Subdivision("KH-2", "Baat Dambang", null, "Province"));
    out.add(new Subdivision("KH-20", "Svaay Rieng", null, "Province"));
    out.add(new Subdivision("KH-21", "Taakaev", null, "Province"));
    out.add(new Subdivision("KH-22", "Otdar Mean Chey", null, "Province"));
    out.add(new Subdivision("KH-23", "Kaeb", null, "Province"));
    out.add(new Subdivision("KH-24", "Pailin", null, "Province"));
    out.add(new Subdivision("KH-25", "Tbong Khmum", null, "Province"));
    out.add(new Subdivision("KH-3", "Kampong Chaam", null, "Province"));
    out.add(new Subdivision("KH-4", "Kampong Chhnang", null, "Province"));
    out.add(new Subdivision("KH-5", "Kampong Spueu", null, "Province"));
    out.add(new Subdivision("KH-6", "Kampong Thum", null, "Province"));
    out.add(new Subdivision("KH-7", "Kampot", null, "Province"));
    out.add(new Subdivision("KH-8", "Kandaal", null, "Province"));
    out.add(new Subdivision("KH-9", "Kaoh Kong", null, "Province"));
    out.add(new Subdivision("KI-G", "Gilbert Islands", null, "Group of islands (20 inhabited islands)"));
    out.add(new Subdivision("KI-L", "Line Islands", null, "Group of islands (20 inhabited islands)"));
    out.add(new Subdivision("KI-P", "Phoenix Islands", null, "Group of islands (20 inhabited islands)"));
    out.add(new Subdivision("KM-A", "Anjouan", null, "Island"));
    out.add(new Subdivision("KM-G", "Grande Comore", null, "Island"));
    out.add(new Subdivision("KM-M", "Mohéli", null, "Island"));
    out.add(new Subdivision("KN-01", "Christ Church Nichola Town", "KN-K", "Parish"));
    out.add(new Subdivision("KN-02", "Saint Anne Sandy Point", "KN-K", "Parish"));
    out.add(new Subdivision("KN-03", "Saint George Basseterre", "KN-K", "Parish"));
    out.add(new Subdivision("KN-04", "Saint George Gingerland", "KN-N", "Parish"));
    out.add(new Subdivision("KN-05", "Saint James Windward", "KN-N", "Parish"));
    out.add(new Subdivision("KN-06", "Saint John Capisterre", "KN-K", "Parish"));
    out.add(new Subdivision("KN-07", "Saint John Figtree", "KN-N", "Parish"));
    out.add(new Subdivision("KN-08", "Saint Mary Cayon", "KN-K", "Parish"));
    out.add(new Subdivision("KN-09", "Saint Paul Capisterre", "KN-K", "Parish"));
    out.add(new Subdivision("KN-10", "Saint Paul Charlestown", "KN-N", "Parish"));
    out.add(new Subdivision("KN-11", "Saint Peter Basseterre", "KN-K", "Parish"));
    out.add(new Subdivision("KN-12", "Saint Thomas Lowland", "KN-N", "Parish"));
    out.add(new Subdivision("KN-13", "Saint Thomas Middle Island", "KN-K", "Parish"));
    out.add(new Subdivision("KN-15", "Trinity Palmetto Point", "KN-K", "Parish"));
    out.add(new Subdivision("KN-K", "Saint Kitts", null, "State"));
    out.add(new Subdivision("KN-N", "Nevis", null, "State"));
    out.add(new Subdivision("KP-01", "Phyeongyang", null, "Capital city"));
    out.add(new Subdivision("KP-02", "Phyeongannamto", null, "Province"));
    out.add(new Subdivision("KP-03", "Phyeonganpukto", null, "Province"));
    out.add(new Subdivision("KP-04", "Jakangto", null, "Province"));
    out.add(new Subdivision("KP-05", "Hwanghainamto", null, "Province"));
    out.add(new Subdivision("KP-06", "Hwanghaipukto", null, "Province"));
    out.add(new Subdivision("KP-07", "Kangweonto", null, "Province"));
    out.add(new Subdivision("KP-08", "Hamkyeongnamto", null, "Province"));
    out.add(new Subdivision("KP-09", "Hamkyeongpukto", null, "Province"));
    out.add(new Subdivision("KP-10", "Ryangkangto", null, "Province"));
    out.add(new Subdivision("KP-13", "Raseon", null, "Special city"));
    out.add(new Subdivision("KP-14", "Nampho", null, "Metropolitan city"));
    out.add(new Subdivision("KP-15", "Kaeseong", null, "Metropolitan city"));
    out.add(new Subdivision("KR-11", "Seoul-teukbyeolsi", null, "Special city"));
    out.add(new Subdivision("KR-26", "Busan-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-27", "Daegu-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-28", "Incheon-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-29", "Gwangju-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-30", "Daejeon-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-31", "Ulsan-gwangyeoksi", null, "Metropolitan city"));
    out.add(new Subdivision("KR-41", "Gyeonggi-do", null, "Province"));
    out.add(new Subdivision("KR-42", "Gangwon-teukbyeoljachido", null, "Special self-governing province"));
    out.add(new Subdivision("KR-43", "Chungcheongbuk-do", null, "Province"));
    out.add(new Subdivision("KR-44", "Chungcheongnam-do", null, "Province"));
    out.add(new Subdivision("KR-45", "Jeollabuk-do", null, "Province"));
    out.add(new Subdivision("KR-46", "Jeollanam-do", null, "Province"));
    out.add(new Subdivision("KR-47", "Gyeongsangbuk-do", null, "Province"));
    out.add(new Subdivision("KR-48", "Gyeongsangnam-do", null, "Province"));
    out.add(new Subdivision("KR-49", "Jeju-teukbyeoljachido", null, "Special self-governing province"));
    out.add(new Subdivision("KR-50", "Sejong", null, "Special self-governing city"));
    out.add(new Subdivision("KW-AH", "Al Aḩmadī", null, "Governorate"));
    out.add(new Subdivision("KW-FA", "Al Farwānīyah", null, "Governorate"));
    out.add(new Subdivision("KW-HA", "Ḩawallī", null, "Governorate"));
    out.add(new Subdivision("KW-JA", "Al Jahrā’", null, "Governorate"));
    out.add(new Subdivision("KW-KU", "Al ‘Āşimah", null, "Governorate"));
    out.add(new Subdivision("KW-MU", "Mubārak al Kabīr", null, "Governorate"));
    out.add(new Subdivision("KZ-10", "Abay oblysy", null, "Region"));
    out.add(new Subdivision("KZ-11", "Aqmola oblysy", null, "Region"));
    out.add(new Subdivision("KZ-15", "Aqtöbe oblysy", null, "Region"));
    out.add(new Subdivision("KZ-19", "Almaty oblysy", null, "Region"));
    out.add(new Subdivision("KZ-23", "Atyraū oblysy", null, "Region"));
    out.add(new Subdivision("KZ-27", "Batys Qazaqstan oblysy", null, "Region"));
    out.add(new Subdivision("KZ-31", "Zhambyl oblysy", null, "Region"));
  }
}
