// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 2500 to 2999 of {@link Subdivision}.
 */
final class SubdivisionData5 {
  private SubdivisionData5() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("KZ-33", "Zhetisū oblysy", null, "Region"));
    out.add(new Subdivision("KZ-35", "Qaraghandy oblysy", null, "Region"));
    out.add(new Subdivision("KZ-39", "Qostanay oblysy", null, "Region"));
    out.add(new Subdivision("KZ-43", "Qyzylorda oblysy", null, "Region"));
    out.add(new Subdivision("KZ-47", "Mangghystaū oblysy", null, "Region"));
    out.add(new Subdivision("KZ-55", "Pavlodar oblysy", null, "Region"));
    out.add(new Subdivision("KZ-59", "Soltüstik Qazaqstan oblysy", null, "Region"));
    out.add(new Subdivision("KZ-61", "Türkistan oblysy", null, "Region"));
    out.add(new Subdivision("KZ-62", "Ulytaū oblysy", null, "Region"));
    out.add(new Subdivision("KZ-63", "Shyghys Qazaqstan oblysy", null, "Region"));
    out.add(new Subdivision("KZ-71", "Astana", null, "City"));
    out.add(new Subdivision("KZ-75", "Almaty", null, "City"));
    out.add(new Subdivision("KZ-79", "Shymkent", null, "City"));
    out.add(new Subdivision("LA-AT", "Attapu", null, "Province"));
    out.add(new Subdivision("LA-BK", "Bokèo", null, "Province"));
    out.add(new Subdivision("LA-BL", "Bolikhamxai", null, "Province"));
    out.add(new Subdivision("LA-CH", "Champasak", null, "Province"));
    out.add(new Subdivision("LA-HO", "Houaphan", null, "Province"));
    out.add(new Subdivision("LA-KH", "Khammouan", null, "Province"));
    out.add(new Subdivision("LA-LM", "Louang Namtha", null, "Province"));
    out.add(new Subdivision("LA-LP", "Louangphabang", null, "Province"));
    out.add(new Subdivision("LA-OU", "Oudômxai", null, "Province"));
    out.add(new Subdivision("LA-PH", "Phôngsali", null, "Province"));
    out.add(new Subdivision("LA-SL", "Salavan", null, "Province"));
    out.add(new Subdivision("LA-SV", "Savannakhét", null, "Province"));
    out.add(new Subdivision("LA-VI", "Viangchan", null, "Province"));
    out.add(new Subdivision("LA-VT", "Viangchan", null, "Prefecture"));
    out.add(new Subdivision("LA-XA", "Xaignabouli", null, "Province"));
    out.add(new Subdivision("LA-XE", "Xékong", null, "Province"));
    out.add(new Subdivision("LA-XI", "Xiangkhouang", null, "Province"));
    out.add(new Subdivision("LA-XS", "Xaisômboun", null, "Province"));
    out.add(new Subdivision("LB-AK", "‘Akkār", null, "Governorate"));
    out.add(new Subdivision("LB-AS", "Ash Shimāl", null, "Governorate"));
    out.add(new Subdivision("LB-BA", "Bayrūt", null, "Governorate"));
    out.add(new Subdivision("LB-BH", "B‘alabak-Al Hirmil", null, "Governorate"));
    out.add(new Subdivision("LB-BI", "Al Biqā‘", null, "Governorate"));
    out.add(new Subdivision("LB-JA", "Al Janūb", null, "Governorate"));
    out.add(new Subdivision("LB-JL", "Jabal Lubnān", null, "Governorate"));
    out.add(new Subdivision("LB-NA", "An Nabaţīyah", null, "Governorate"));
    out.add(new Subdivision("LC-01", "Anse la Raye", null, "District"));
    out.add(new Subdivision("LC-02", "Castries", null, "District"));
    out.add(new Subdivision("LC-03", "Choiseul", null, "District"));
    out.add(new Subdivision("LC-05", "Dennery", null, "District"));
    out.add(new Subdivision("LC-06", "Gros Islet", null, "District"));
    out.add(new Subdivision("LC-07", "Laborie", null, "District"));
    out.add(new Subdivision("LC-08", "Micoud", null, "District"));
    out.add(new Subdivision("LC-10", "Soufrière", null, "District"));
    out.add(new Subdivision("LC-11", "Vieux Fort", null, "District"));
    out.add(new Subdivision("LC-12", "Canaries", null, "District"));
    out.add(new Subdivision("LI-01", "Balzers", null, "Commune"));
    out.add(new Subdivision("LI-02", "Eschen", null, "Commune"));
    out.add(new Subdivision("LI-03", "Gamprin", null, "Commune"));
    out.add(new Subdivision("LI-04", "Mauren", null, "Commune"));
    out.add(new Subdivision("LI-05", "Planken", null, "Commune"));
    out.add(new Subdivision("LI-06", "Ruggell", null, "Commune"));
    out.add(new Subdivision("LI-07", "Schaan", null, "Commune"));
    out.add(new Subdivision("LI-08", "Schellenberg", null, "Commune"));
    out.add(new Subdivision("LI-09", "Triesen", null, "Commune"));
    out.add(new Subdivision("LI-10", "Triesenberg", null, "Commune"));
    out.add(new Subdivision("LI-11", "Vaduz", null, "Commune"));
    out.add(new Subdivision("LK-1", "Western Province", null, "Province"));
    out.add(new Subdivision("LK-11", "Colombo", "LK-1", "District"));
    out.add(new Subdivision("LK-12", "Gampaha", "LK-1", "District"));
    out.add(new Subdivision("LK-13", "Kalutara", "LK-1", "District"));
    out.add(new Subdivision("LK-2", "Central Province", null, "Province"));
    out.add(new Subdivision("LK-21", "Kandy", "LK-2", "District"));
    out.add(new Subdivision("LK-22", "Matale", "LK-2", "District"));
    out.add(new Subdivision("LK-23", "Nuwara Eliya", "LK-2", "District"));
    out.add(new Subdivision("LK-3", "Southern Province", null, "Province"));
    out.add(new Subdivision("LK-31", "Galle", "LK-3", "District"));
    out.add(new Subdivision("LK-32", "Matara", "LK-3", "District"));
    out.add(new Subdivision("LK-33", "Hambantota", "LK-3", "District"));
    out.add(new Subdivision("LK-4", "Northern Province", null, "Province"));
    out.add(new Subdivision("LK-41", "Jaffna", "LK-4", "District"));
    out.add(new Subdivision("LK-42", "Kilinochchi", "LK-4", "District"));
    out.add(new Subdivision("LK-43", "Mannar", "LK-4", "District"));
    out.add(new Subdivision("LK-44", "Vavuniya", "LK-4", "District"));
    out.add(new Subdivision("LK-45", "Mullaittivu", "LK-4", "District"));
    out.add(new Subdivision("LK-5", "Eastern Province", null, "Province"));
    out.add(new Subdivision("LK-51", "Batticaloa", "LK-5", "District"));
    out.add(new Subdivision("LK-52", "Ampara", "LK-5", "District"));
    out.add(new Subdivision("LK-53", "Trincomalee", "LK-5", "District"));
    out.add(new Subdivision("LK-6", "North Western Province", null, "Province"));
    out.add(new Subdivision("LK-61", "Kurunegala", "LK-6", "District"));
    out.add(new Subdivision("LK-62", "Puttalam", "LK-6", "District"));
    out.add(new Subdivision("LK-7", "North Central Province", null, "Province"));
    out.add(new Subdivision("LK-71", "Anuradhapura", "LK-7", "District"));
    out.add(new Subdivision("LK-72", "Polonnaruwa", "LK-7", "District"));
    out.add(new Subdivision("LK-8", "Uva Province", null, "Province"));
    out.add(new Subdivision("LK-81", "Badulla", "LK-8", "District"));
    out.add(new Subdivision("LK-82", "Monaragala", "LK-8", "District"));
    out.add(new Subdivision("LK-9", "Sabaragamuwa Province", null, "Province"));
    out.add(new Subdivision("LK-91", "Ratnapura", "LK-9", "District"));
    out.add(new Subdivision("LK-92", "Kegalla", "LK-9", "District"));
    out.add(new Subdivision("LR-BG", "Bong", null, "County"));
    out.add(new Subdivision("LR-BM", "Bomi", null, "County"));
    out.add(new Subdivision("LR-CM", "Grand Cape Mount", null, "County"));
    out.add(new Subdivision("LR-GB", "Grand Bassa", null, "County"));
    out.add(new Subdivision("LR-GG", "Grand Gedeh", null, "County"));
    out.add(new Subdivision("LR-GK", "Grand Kru", null, "County"));
    out.add(new Subdivision("LR-GP", "Gbarpolu", null, "County"));
    out.add(new Subdivision("LR-LO", "Lofa", null, "County"));
    out.add(new Subdivision("LR-MG", "Margibi", null, "County"));
    out.add(new Subdivision("LR-MO", "Montserrado", null, "County"));
    out.add(new Subdivision("LR-MY", "Maryland", null, "County"));
    out.add(new Subdivision("LR-NI", "Nimba", null, "County"));
    out.add(new Subdivision("LR-RG", "River Gee", null, "County"));
    out.add(new Subdivision("LR-RI", "River Cess", null, "County"));
    out.add(new Subdivision("LR-SI", "Sinoe", null, "County"));
    out.add(new Subdivision("LS-A", "Maseru", null, "District"));
    out.add(new Subdivision("LS-B", "Botha-Bothe", null, "District"));
    out.add(new Subdivision("LS-C", "Leribe", null, "District"));
    out.add(new Subdivision("LS-D", "Berea", null, "District"));
    out.add(new Subdivision("LS-E", "Mafeteng", null, "District"));
    out.add(new Subdivision("LS-F", "Mohale's Hoek", null, "District"));
    out.add(new Subdivision("LS-G", "Quthing", null, "District"));
    out.add(new Subdivision("LS-H", "Qacha's Nek", null, "District"));
    out.add(new Subdivision("LS-J", "Mokhotlong", null, "District"));
    out.add(new Subdivision("LS-K", "Thaba-Tseka", null, "District"));
    out.add(new Subdivision("LT-01", "Akmenė", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-02", "Alytaus miestas", "LT-AL", "City municipality"));
    out.add(new Subdivision("LT-03", "Alytus", "LT-AL", "District municipality"));
    out.add(new Subdivision("LT-04", "Anykščiai", "LT-UT", "District municipality"));
    out.add(new Subdivision("LT-05", "Birštonas", "LT-KU", "Municipality"));
    out.add(new Subdivision("LT-06", "Biržai", "LT-PN", "District municipality"));
    out.add(new Subdivision("LT-07", "Druskininkai", "LT-AL", "Municipality"));
    out.add(new Subdivision("LT-08", "Elektrėnai", "LT-VL", "Municipality"));
    out.add(new Subdivision("LT-09", "Ignalina", "LT-UT", "District municipality"));
    out.add(new Subdivision("LT-10", "Jonava", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-11", "Joniškis", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-12", "Jurbarkas", "LT-TA", "District municipality"));
    out.add(new Subdivision("LT-13", "Kaišiadorys", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-14", "Kalvarija", "LT-MR", "Municipality"));
    out.add(new Subdivision("LT-15", "Kauno miestas", "LT-KU", "City municipality"));
    out.add(new Subdivision("LT-16", "Kaunas", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-17", "Kazlų Rūdos", "LT-MR", "Municipality"));
    out.add(new Subdivision("LT-18", "Kėdainiai", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-19", "Kelmė", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-20", "Klaipėdos miestas", "LT-KL", "City municipality"));
    out.add(new Subdivision("LT-21", "Klaipėda", "LT-KL", "District municipality"));
    out.add(new Subdivision("LT-22", "Kretinga", "LT-KL", "District municipality"));
    out.add(new Subdivision("LT-23", "Kupiškis", "LT-PN", "District municipality"));
    out.add(new Subdivision("LT-24", "Lazdijai", "LT-AL", "District municipality"));
    out.add(new Subdivision("LT-25", "Marijampolė", "LT-MR", "District municipality"));
    out.add(new Subdivision("LT-26", "Mažeikiai", "LT-TE", "District municipality"));
    out.add(new Subdivision("LT-27", "Molėtai", "LT-UT", "District municipality"));
    out.add(new Subdivision("LT-28", "Neringa", "LT-KL", "Municipality"));
    out.add(new Subdivision("LT-29", "Pagėgiai", "LT-TA", "Municipality"));
    out.add(new Subdivision("LT-30", "Pakruojis", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-31", "Palangos miestas", "LT-KL", "City municipality"));
    out.add(new Subdivision("LT-32", "Panevėžio miestas", "LT-PN", "City municipality"));
    out.add(new Subdivision("LT-33", "Panevėžys", "LT-PN", "District municipality"));
    out.add(new Subdivision("LT-34", "Pasvalys", "LT-PN", "District municipality"));
    out.add(new Subdivision("LT-35", "Plungė", "LT-TE", "District municipality"));
    out.add(new Subdivision("LT-36", "Prienai", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-37", "Radviliškis", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-38", "Raseiniai", "LT-KU", "District municipality"));
    out.add(new Subdivision("LT-39", "Rietavas", "LT-TE", "Municipality"));
    out.add(new Subdivision("LT-40", "Rokiškis", "LT-PN", "District municipality"));
    out.add(new Subdivision("LT-41", "Šakiai", "LT-MR", "District municipality"));
    out.add(new Subdivision("LT-42", "Šalčininkai", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-43", "Šiaulių miestas", "LT-SA", "City municipality"));
    out.add(new Subdivision("LT-44", "Šiauliai", "LT-SA", "District municipality"));
    out.add(new Subdivision("LT-45", "Šilalė", "LT-TA", "District municipality"));
    out.add(new Subdivision("LT-46", "Šilutė", "LT-KL", "District municipality"));
    out.add(new Subdivision("LT-47", "Širvintos", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-48", "Skuodas", "LT-KL", "District municipality"));
    out.add(new Subdivision("LT-49", "Švenčionys", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-50", "Tauragė", "LT-TA", "District municipality"));
    out.add(new Subdivision("LT-51", "Telšiai", "LT-TE", "District municipality"));
    out.add(new Subdivision("LT-52", "Trakai", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-53", "Ukmergė", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-54", "Utena", "LT-UT", "District municipality"));
    out.add(new Subdivision("LT-55", "Varėna", "LT-AL", "District municipality"));
    out.add(new Subdivision("LT-56", "Vilkaviškis", "LT-MR", "District municipality"));
    out.add(new Subdivision("LT-57", "Vilniaus miestas", "LT-VL", "City municipality"));
    out.add(new Subdivision("LT-58", "Vilnius", "LT-VL", "District municipality"));
    out.add(new Subdivision("LT-59", "Visaginas", "LT-UT", "Municipality"));
    out.add(new Subdivision("LT-60", "Zarasai", "LT-UT", "District municipality"));
    out.add(new Subdivision("LT-AL", "Alytaus apskritis", null, "County"));
    out.add(new Subdivision("LT-KL", "Klaipėdos apskritis", null, "County"));
    out.add(new Subdivision("LT-KU", "Kauno apskritis", null, "County"));
    out.add(new Subdivision("LT-MR", "Marijampolės apskritis", null, "County"));
    out.add(new Subdivision("LT-PN", "Panevėžio apskritis", null, "County"));
    out.add(new Subdivision("LT-SA", "Šiaulių apskritis", null, "County"));
    out.add(new Subdivision("LT-TA", "Tauragės apskritis", null, "County"));
    out.add(new Subdivision("LT-TE", "Telšių apskritis", null, "County"));
    out.add(new Subdivision("LT-UT", "Utenos apskritis", null, "County"));
    out.add(new Subdivision("LT-VL", "Vilniaus apskritis", null, "County"));
    out.add(new Subdivision("LU-CA", "Capellen", null, "Canton"));
    out.add(new Subdivision("LU-CL", "Clervaux", null, "Canton"));
    out.add(new Subdivision("LU-DI", "Diekirch", null, "Canton"));
    out.add(new Subdivision("LU-EC", "Echternach", null, "Canton"));
    out.add(new Subdivision("LU-ES", "Esch-sur-Alzette", null, "Canton"));
    out.add(new Subdivision("LU-GR", "Grevenmacher", null, "Canton"));
    out.add(new Subdivision("LU-LU", "Luxembourg", null, "Canton"));
    out.add(new Subdivision("LU-ME", "Mersch", null, "Canton"));
    out.add(new Subdivision("LU-RD", "Redange", null, "Canton"));
    out.add(new Subdivision("LU-RM", "Remich", null, "Canton"));
    out.add(new Subdivision("LU-VD", "Vianden", null, "Canton"));
    out.add(new Subdivision("LU-WI", "Wiltz", null, "Canton"));
    out.add(new Subdivision("LV-002", "Aizkraukles novads", null, "Municipality"));
    out.add(new Subdivision("LV-007", "Alūksnes novads", null, "Municipality"));
    out.add(new Subdivision("LV-011", "Ādažu novads", null, "Municipality"));
    out.add(new Subdivision("LV-015", "Balvu novads", null, "Municipality"));
    out.add(new Subdivision("LV-016", "Bauskas novads", null, "Municipality"));
    out.add(new Subdivision("LV-022", "Cēsu novads", null, "Municipality"));
    out.add(new Subdivision("LV-026", "Dobeles novads", null, "Municipality"));
    out.add(new Subdivision("LV-033", "Gulbenes novads", null, "Municipality"));
    out.add(new Subdivision("LV-041", "Jelgavas novads", null, "Municipality"));
    out.add(new Subdivision("LV-042", "Jēkabpils novads", null, "Municipality"));
    out.add(new Subdivision("LV-047", "Krāslavas novads", null, "Municipality"));
    out.add(new Subdivision("LV-050", "Kuldīgas novads", null, "Municipality"));
    out.add(new Subdivision("LV-052", "Ķekavas novads", null, "Municipality"));
    out.add(new Subdivision("LV-054", "Limbažu novads", null, "Municipality"));
    out.add(new Subdivision("LV-056", "Līvānu novads", null, "Municipality"));
    out.add(new Subdivision("LV-058", "Ludzas novads", null, "Municipality"));
    out.add(new Subdivision("LV-059", "Madonas novads", null, "Municipality"));
    out.add(new Subdivision("LV-062", "Mārupes novads", null, "Municipality"));
    out.add(new Subdivision("LV-067", "Ogres novads", null, "Municipality"));
    out.add(new Subdivision("LV-068", "Olaines novads", null, "Municipality"));
    out.add(new Subdivision("LV-073", "Preiļu novads", null, "Municipality"));
    out.add(new Subdivision("LV-077", "Rēzeknes novads", null, "Municipality"));
    out.add(new Subdivision("LV-080", "Ropažu novads", null, "Municipality"));
    out.add(new Subdivision("LV-087", "Salaspils novads", null, "Municipality"));
    out.add(new Subdivision("LV-088", "Saldus novads", null, "Municipality"));
    out.add(new Subdivision("LV-089", "Saulkrastu novads", null, "Municipality"));
    out.add(new Subdivision("LV-091", "Siguldas novads", null, "Municipality"));
    out.add(new Subdivision("LV-094", "Smiltenes novads", null, "Municipality"));
    out.add(new Subdivision("LV-097", "Talsu novads", null, "Municipality"));
    out.add(new Subdivision("LV-099", "Tukuma novads", null, "Municipality"));
    out.add(new Subdivision("LV-101", "Valkas novads", null, "Municipality"));
    out.add(new Subdivision("LV-102", "Varakļānu novads", null, "Municipality"));
    out.add(new Subdivision("LV-106", "Ventspils novads", null, "Municipality"));
    out.add(new Subdivision("LV-111", "Augšdaugavas novads", null, "Municipality"));
    out.add(new Subdivision("LV-112", "Dienvidkurzemes Novads", null, "Municipality"));
    out.add(new Subdivision("LV-113", "Valmieras Novads", null, "Municipality"));
    out.add(new Subdivision("LV-DGV", "Daugavpils", null, "State city"));
    out.add(new Subdivision("LV-JEL", "Jelgava", null, "State city"));
    out.add(new Subdivision("LV-JUR", "Jūrmala", null, "State city"));
    out.add(new Subdivision("LV-LPX", "Liepāja", null, "State city"));
    out.add(new Subdivision("LV-REZ", "Rēzekne", null, "State city"));
    out.add(new Subdivision("LV-RIX", "Rīga", null, "State city"));
    out.add(new Subdivision("LV-VEN", "Ventspils", null, "State city"));
    out.add(new Subdivision("LY-BA", "Banghāzī", null, "Popularate"));
    out.add(new Subdivision("LY-BU", "Al Buţnān", null, "Popularate"));
    out.add(new Subdivision("LY-DR", "Darnah", null, "Popularate"));
    out.add(new Subdivision("LY-GT", "Ghāt", null, "Popularate"));
    out.add(new Subdivision("LY-JA", "Al Jabal al Akhḑar", null, "Popularate"));
    out.add(new Subdivision("LY-JG", "Al Jabal al Gharbī", null, "Popularate"));
    out.add(new Subdivision("LY-JI", "Al Jafārah", null, "Popularate"));
    out.add(new Subdivision("LY-JU", "Al Jufrah", null, "Popularate"));
    out.add(new Subdivision("LY-KF", "Al Kufrah", null, "Popularate"));
    out.add(new Subdivision("LY-MB", "Al Marqab", null, "Popularate"));
    out.add(new Subdivision("LY-MI", "Mişrātah", null, "Popularate"));
    out.add(new Subdivision("LY-MJ", "Al Marj", null, "Popularate"));
    out.add(new Subdivision("LY-MQ", "Murzuq", null, "Popularate"));
    out.add(new Subdivision("LY-NL", "Nālūt", null, "Popularate"));
    out.add(new Subdivision("LY-NQ", "An Nuqāţ al Khams", null, "Popularate"));
    out.add(new Subdivision("LY-SB", "Sabhā", null, "Popularate"));
    out.add(new Subdivision("LY-SR", "Surt", null, "Popularate"));
    out.add(new Subdivision("LY-TB", "Ţarābulus", null, "Popularate"));
    out.add(new Subdivision("LY-WA", "Al Wāḩāt", null, "Popularate"));
    out.add(new Subdivision("LY-WD", "Wādī al Ḩayāt", null, "Popularate"));
    out.add(new Subdivision("LY-WS", "Wādī ash Shāţi’", null, "Popularate"));
    out.add(new Subdivision("LY-ZA", "Az Zāwiyah", null, "Popularate"));
    out.add(new Subdivision("MA-01", "Tanger-Tétouan-Al Hoceïma", null, "Region"));
    out.add(new Subdivision("MA-02", "L'Oriental", null, "Region"));
    out.add(new Subdivision("MA-03", "Fès-Meknès", null, "Region"));
    out.add(new Subdivision("MA-04", "Rabat-Salé-Kénitra", null, "Region"));
    out.add(new Subdivision("MA-05", "Béni Mellal-Khénifra", null, "Region"));
    out.add(new Subdivision("MA-06", "Casablanca-Settat", null, "Region"));
    out.add(new Subdivision("MA-07", "Marrakech-Safi", null, "Region"));
    out.add(new Subdivision("MA-08", "Drâa-Tafilalet", null, "Region"));
    out.add(new Subdivision("MA-09", "Souss-Massa", null, "Region"));
    out.add(new Subdivision("MA-10", "Guelmim-Oued Noun (EH-partial)", null, "Region"));
    out.add(new Subdivision("MA-11", "Laâyoune-Sakia El Hamra (EH-partial)", null, "Region"));
    out.add(new Subdivision("MA-12", "Dakhla-Oued Ed-Dahab (EH)", null, "Region"));
    out.add(new Subdivision("MA-AGD", "Agadir-Ida-Ou-Tanane", "MA-09", "Prefecture"));
    out.add(new Subdivision("MA-AOU", "Aousserd (EH)", "MA-12", "Province"));
    out.add(new Subdivision("MA-ASZ", "Assa-Zag (EH-partial)", "MA-10", "Province"));
    out.add(new Subdivision("MA-AZI", "Azilal", "MA-05", "Province"));
    out.add(new Subdivision("MA-BEM", "Béni Mellal", "MA-05", "Province"));
    out.add(new Subdivision("MA-BER", "Berkane", "MA-02", "Province"));
    out.add(new Subdivision("MA-BES", "Benslimane", "MA-06", "Province"));
    out.add(new Subdivision("MA-BOD", "Boujdour (EH)", "MA-11", "Province"));
    out.add(new Subdivision("MA-BOM", "Boulemane", "MA-03", "Province"));
    out.add(new Subdivision("MA-BRR", "Berrechid", "MA-06", "Province"));
    out.add(new Subdivision("MA-CAS", "Casablanca", "MA-06", "Prefecture"));
    out.add(new Subdivision("MA-CHE", "Chefchaouen", "MA-01", "Province"));
    out.add(new Subdivision("MA-CHI", "Chichaoua", "MA-07", "Province"));
    out.add(new Subdivision("MA-CHT", "Chtouka-Ait Baha", "MA-06", "Province"));
    out.add(new Subdivision("MA-DRI", "Driouch", "MA-02", "Province"));
    out.add(new Subdivision("MA-ERR", "Errachidia", "MA-08", "Province"));
    out.add(new Subdivision("MA-ESI", "Essaouira", "MA-07", "Province"));
    out.add(new Subdivision("MA-ESM", "Es-Semara (EH-partial)", "MA-11", "Province"));
    out.add(new Subdivision("MA-FAH", "Fahs-Anjra", "MA-01", "Province"));
    out.add(new Subdivision("MA-FES", "Fès", "MA-03", "Prefecture"));
    out.add(new Subdivision("MA-FIG", "Figuig", "MA-02", "Province"));
    out.add(new Subdivision("MA-FQH", "Fquih Ben Salah", "MA-05", "Province"));
    out.add(new Subdivision("MA-GUE", "Guelmim", "MA-10", "Province"));
    out.add(new Subdivision("MA-GUF", "Guercif", "MA-02", "Province"));
    out.add(new Subdivision("MA-HAJ", "El Hajeb", "MA-03", "Province"));
    out.add(new Subdivision("MA-HAO", "Al Haouz", "MA-07", "Province"));
    out.add(new Subdivision("MA-HOC", "Al Hoceïma", "MA-01", "Province"));
    out.add(new Subdivision("MA-IFR", "Ifrane", "MA-03", "Province"));
    out.add(new Subdivision("MA-INE", "Inezgane-Ait Melloul", "MA-09", "Prefecture"));
    out.add(new Subdivision("MA-JDI", "El Jadida", "MA-06", "Province"));
    out.add(new Subdivision("MA-JRA", "Jerada", "MA-02", "Province"));
    out.add(new Subdivision("MA-KEN", "Kénitra", "MA-04", "Province"));
    out.add(new Subdivision("MA-KES", "El Kelâa des Sraghna", "MA-07", "Province"));
    out.add(new Subdivision("MA-KHE", "Khémisset", "MA-04", "Province"));
    out.add(new Subdivision("MA-KHN", "Khénifra", "MA-05", "Province"));
    out.add(new Subdivision("MA-KHO", "Khouribga", "MA-05", "Province"));
    out.add(new Subdivision("MA-LAA", "Laâyoune (EH)", "MA-11", "Province"));
    out.add(new Subdivision("MA-LAR", "Larache", "MA-01", "Province"));
    out.add(new Subdivision("MA-MAR", "Marrakech", "MA-07", "Prefecture"));
    out.add(new Subdivision("MA-MDF", "M’diq-Fnideq", "MA-01", "Prefecture"));
    out.add(new Subdivision("MA-MED", "Médiouna", "MA-06", "Province"));
    out.add(new Subdivision("MA-MEK", "Meknès", "MA-03", "Prefecture"));
    out.add(new Subdivision("MA-MID", "Midelt", "MA-08", "Province"));
    out.add(new Subdivision("MA-MOH", "Mohammadia", "MA-06", "Prefecture"));
    out.add(new Subdivision("MA-MOU", "Moulay Yacoub", "MA-03", "Province"));
    out.add(new Subdivision("MA-NAD", "Nador", "MA-02", "Province"));
    out.add(new Subdivision("MA-NOU", "Nouaceur", "MA-04", "Province"));
    out.add(new Subdivision("MA-OUA", "Ouarzazate", "MA-08", "Province"));
    out.add(new Subdivision("MA-OUD", "Oued Ed-Dahab (EH)", "MA-12", "Province"));
    out.add(new Subdivision("MA-OUJ", "Oujda-Angad", "MA-02", "Prefecture"));
    out.add(new Subdivision("MA-OUZ", "Ouezzane", "MA-01", "Province"));
    out.add(new Subdivision("MA-RAB", "Rabat", "MA-04", "Prefecture"));
    out.add(new Subdivision("MA-REH", "Rehamna", "MA-07", "Province"));
    out.add(new Subdivision("MA-SAF", "Safi", "MA-07", "Province"));
    out.add(new Subdivision("MA-SAL", "Salé", "MA-04", "Prefecture"));
    out.add(new Subdivision("MA-SEF", "Sefrou", "MA-03", "Province"));
    out.add(new Subdivision("MA-SET", "Settat", "MA-06", "Province"));
    out.add(new Subdivision("MA-SIB", "Sidi Bennour", "MA-06", "Province"));
    out.add(new Subdivision("MA-SIF", "Sidi Ifni", "MA-10", "Province"));
    out.add(new Subdivision("MA-SIK", "Sidi Kacem", "MA-04", "Province"));
    out.add(new Subdivision("MA-SIL", "Sidi Slimane", "MA-04", "Province"));
    out.add(new Subdivision("MA-SKH", "Skhirate-Témara", "MA-04", "Prefecture"));
    out.add(new Subdivision("MA-TAF", "Tarfaya (EH-partial)", "MA-11", "Province"));
    out.add(new Subdivision("MA-TAI", "Taourirt", "MA-02", "Province"));
    out.add(new Subdivision("MA-TAO", "Taounate", "MA-03", "Province"));
    out.add(new Subdivision("MA-TAR", "Taroudannt", "MA-09", "Province"));
    out.add(new Subdivision("MA-TAT", "Tata", "MA-09", "Province"));
    out.add(new Subdivision("MA-TAZ", "Taza", "MA-03", "Province"));
    out.add(new Subdivision("MA-TET", "Tétouan", "MA-01", "Province"));
    out.add(new Subdivision("MA-TIN", "Tinghir", "MA-08", "Province"));
    out.add(new Subdivision("MA-TIZ", "Tiznit", "MA-09", "Province"));
    out.add(new Subdivision("MA-TNG", "Tanger-Assilah", "MA-01", "Prefecture"));
    out.add(new Subdivision("MA-TNT", "Tan-Tan (EH-partial)", "MA-10", "Province"));
    out.add(new Subdivision("MA-YUS", "Youssoufia", "MA-07", "Province"));
    out.add(new Subdivision("MA-ZAG", "Zagora", "MA-08", "Province"));
    out.add(new Subdivision("MC-CL", "La Colle", null, "Quarter"));
    out.add(new Subdivision("MC-CO", "La Condamine", null, "Quarter"));
    out.add(new Subdivision("MC-FO", "Fontvieille", null, "Quarter"));
    out.add(new Subdivision("MC-GA", "La Gare", null, "Quarter"));
    out.add(new Subdivision("MC-JE", "Jardin Exotique", null, "Quarter"));
    out.add(new Subdivision("MC-LA", "Larvotto", null, "Quarter"));
    out.add(new Subdivision("MC-MA", "Malbousquet", null, "Quarter"));
    out.add(new Subdivision("MC-MC", "Monte-Carlo", null, "Quarter"));
    out.add(new Subdivision("MC-MG", "Moneghetti", null, "Quarter"));
    out.add(new Subdivision("MC-MO", "Monaco-Ville", null, "Quarter"));
    out.add(new Subdivision("MC-MU", "Moulins", null, "Quarter"));
    out.add(new Subdivision("MC-PH", "Port-Hercule", null, "Quarter"));
    out.add(new Subdivision("MC-SD", "Sainte-Dévote", null, "Quarter"));
    out.add(new Subdivision("MC-SO", "La Source", null, "Quarter"));
    out.add(new Subdivision("MC-SP", "Spélugues", null, "Quarter"));
    out.add(new Subdivision("MC-SR", "Saint-Roman", null, "Quarter"));
    out.add(new Subdivision("MC-VR", "Vallon de la Rousse", null, "Quarter"));
    out.add(new Subdivision("MD-AN", "Anenii Noi", null, "District"));
    out.add(new Subdivision("MD-BA", "Bălți", null, "City"));
    out.add(new Subdivision("MD-BD", "Bender [Tighina]", null, "City"));
    out.add(new Subdivision("MD-BR", "Briceni", null, "District"));
    out.add(new Subdivision("MD-BS", "Basarabeasca", null, "District"));
    out.add(new Subdivision("MD-CA", "Cahul", null, "District"));
    out.add(new Subdivision("MD-CL", "Călărași", null, "District"));
    out.add(new Subdivision("MD-CM", "Cimișlia", null, "District"));
    out.add(new Subdivision("MD-CR", "Criuleni", null, "District"));
    out.add(new Subdivision("MD-CS", "Căușeni", null, "District"));
    out.add(new Subdivision("MD-CT", "Cantemir", null, "District"));
    out.add(new Subdivision("MD-CU", "Chișinău", null, "City"));
    out.add(new Subdivision("MD-DO", "Dondușeni", null, "District"));
    out.add(new Subdivision("MD-DR", "Drochia", null, "District"));
    out.add(new Subdivision("MD-DU", "Dubăsari", null, "District"));
    out.add(new Subdivision("MD-ED", "Edineț", null, "District"));
    out.add(new Subdivision("MD-FA", "Fălești", null, "District"));
    out.add(new Subdivision("MD-FL", "Florești", null, "District"));
    out.add(new Subdivision("MD-GA", "Găgăuzia, Unitatea teritorială autonomă (UTAG)", null, "Autonomous territorial unit"));
    out.add(new Subdivision("MD-GL", "Glodeni", null, "District"));
    out.add(new Subdivision("MD-HI", "Hîncești", null, "District"));
    out.add(new Subdivision("MD-IA", "Ialoveni", null, "District"));
    out.add(new Subdivision("MD-LE", "Leova", null, "District"));
    out.add(new Subdivision("MD-NI", "Nisporeni", null, "District"));
    out.add(new Subdivision("MD-OC", "Ocnița", null, "District"));
    out.add(new Subdivision("MD-OR", "Orhei", null, "District"));
    out.add(new Subdivision("MD-RE", "Rezina", null, "District"));
    out.add(new Subdivision("MD-RI", "Rîșcani", null, "District"));
    out.add(new Subdivision("MD-SD", "Șoldănești", null, "District"));
    out.add(new Subdivision("MD-SI", "Sîngerei", null, "District"));
    out.add(new Subdivision("MD-SN", "Stînga Nistrului, unitatea teritorială din", null, "Territorial unit"));
    out.add(new Subdivision("MD-SO", "Soroca", null, "District"));
    out.add(new Subdivision("MD-ST", "Strășeni", null, "District"));
    out.add(new Subdivision("MD-SV", "Ștefan Vodă", null, "District"));
    out.add(new Subdivision("MD-TA", "Taraclia", null, "District"));
    out.add(new Subdivision("MD-TE", "Telenești", null, "District"));
    out.add(new Subdivision("MD-UN", "Ungheni", null, "District"));
    out.add(new Subdivision("ME-01", "Andrijevica", null, "Municipality"));
    out.add(new Subdivision("ME-02", "Bar", null, "Municipality"));
    out.add(new Subdivision("ME-03", "Berane", null, "Municipality"));
    out.add(new Subdivision("ME-04", "Bijelo Polje", null, "Municipality"));
    out.add(new Subdivision("ME-05", "Budva", null, "Municipality"));
    out.add(new Subdivision("ME-06", "Cetinje", null, "Municipality"));
    out.add(new Subdivision("ME-07", "Danilovgrad", null, "Municipality"));
    out.add(new Subdivision("ME-08", "Herceg-Novi", null, "Municipality"));
    out.add(new Subdivision("ME-09", "Kolašin", null, "Municipality"));
    out.add(new Subdivision("ME-10", "Kotor", null, "Municipality"));
    out.add(new Subdivision("ME-11", "Mojkovac", null, "Municipality"));
    out.add(new Subdivision("ME-12", "Nikšić", null, "Municipality"));
    out.add(new Subdivision("ME-13", "Plav", null, "Municipality"));
    out.add(new Subdivision("ME-14", "Pljevlja", null, "Municipality"));
    out.add(new Subdivision("ME-15", "Plužine", null, "Municipality"));
    out.add(new Subdivision("ME-16", "Podgorica", null, "Municipality"));
    out.add(new Subdivision("ME-17", "Rožaje", null, "Municipality"));
    out.add(new Subdivision("ME-18", "Šavnik", null, "Municipality"));
    out.add(new Subdivision("ME-19", "Tivat", null, "Municipality"));
    out.add(new Subdivision("ME-20", "Ulcinj", null, "Municipality"));
    out.add(new Subdivision("ME-21", "Žabljak", null, "Municipality"));
    out.add(new Subdivision("ME-22", "Gusinje", null, "Municipality"));
    out.add(new Subdivision("ME-23", "Petnjica", null, "Municipality"));
    out.add(new Subdivision("ME-24", "Tuzi", null, "Municipality"));
    out.add(new Subdivision("ME-25", "Zeta", null, "Municipality"));
    out.add(new Subdivision("MG-A", "Toamasina", null, "Province"));
    out.add(new Subdivision("MG-D", "Antsiranana", null, "Province"));
    out.add(new Subdivision("MG-F", "Fianarantsoa", null, "Province"));
    out.add(new Subdivision("MG-M", "Mahajanga", null, "Province"));
    out.add(new Subdivision("MG-T", "Antananarivo", null, "Province"));
    out.add(new Subdivision("MG-U", "Toliara", null, "Province"));
    out.add(new Subdivision("MH-ALK", "Ailuk", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-ALL", "Ailinglaplap", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-ARN", "Arno", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-AUR", "Aur", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-EBO", "Ebon", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-ENI", "Enewetak & Ujelang", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-JAB", "Jabat", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-JAL", "Jaluit", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-KIL", "Bikini & Kili", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-KWA", "Kwajalein", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-L", "Ralik chain", null, "Chain (of islands)"));
    out.add(new Subdivision("MH-LAE", "Lae", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-LIB", "Lib", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-LIK", "Likiep", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-MAJ", "Majuro", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-MAL", "Maloelap", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-MEJ", "Mejit", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-MIL", "Mili", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-NMK", "Namdrik", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-NMU", "Namu", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-RON", "Rongelap", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-T", "Ratak chain", null, "Chain (of islands)"));
    out.add(new Subdivision("MH-UJA", "Ujae", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-UTI", "Utrik", "MH-T", "Municipality"));
    out.add(new Subdivision("MH-WTH", "Wotho", "MH-L", "Municipality"));
    out.add(new Subdivision("MH-WTJ", "Wotje", "MH-T", "Municipality"));
    out.add(new Subdivision("MK-101", "Veles", null, "Municipality"));
    out.add(new Subdivision("MK-102", "Gradsko", null, "Municipality"));
    out.add(new Subdivision("MK-103", "Demir Kapija", null, "Municipality"));
    out.add(new Subdivision("MK-104", "Kavadarci", null, "Municipality"));
    out.add(new Subdivision("MK-105", "Lozovo", null, "Municipality"));
    out.add(new Subdivision("MK-106", "Negotino", null, "Municipality"));
    out.add(new Subdivision("MK-107", "Rosoman", null, "Municipality"));
    out.add(new Subdivision("MK-108", "Sveti Nikole", null, "Municipality"));
    out.add(new Subdivision("MK-109", "Čaška", null, "Municipality"));
    out.add(new Subdivision("MK-201", "Berovo", null, "Municipality"));
    out.add(new Subdivision("MK-202", "Vinica", null, "Municipality"));
    out.add(new Subdivision("MK-203", "Delčevo", null, "Municipality"));
    out.add(new Subdivision("MK-204", "Zrnovci", null, "Municipality"));
    out.add(new Subdivision("MK-205", "Karbinci", null, "Municipality"));
    out.add(new Subdivision("MK-206", "Kočani", null, "Municipality"));
    out.add(new Subdivision("MK-207", "Makedonska Kamenica", null, "Municipality"));
    out.add(new Subdivision("MK-208", "Pehčevo", null, "Municipality"));
    out.add(new Subdivision("MK-209", "Probištip", null, "Municipality"));
    out.add(new Subdivision("MK-210", "Češinovo-Obleševo", null, "Municipality"));
    out.add(new Subdivision("MK-211", "Štip", null, "Municipality"));
    out.add(new Subdivision("MK-301", "Vevčani", null, "Municipality"));
    out.add(new Subdivision("MK-303", "Debar", null, "Municipality"));
    out.add(new Subdivision("MK-304", "Debrca", null, "Municipality"));
    out.add(new Subdivision("MK-307", "Kičevo", null, "Municipality"));
    out.add(new Subdivision("MK-308", "Makedonski Brod", null, "Municipality"));
    out.add(new Subdivision("MK-310", "Ohrid", null, "Municipality"));
    out.add(new Subdivision("MK-311", "Plasnica", null, "Municipality"));
    out.add(new Subdivision("MK-312", "Struga", null, "Municipality"));
    out.add(new Subdivision("MK-313", "Centar Župa", null, "Municipality"));
    out.add(new Subdivision("MK-401", "Bogdanci", null, "Municipality"));
    out.add(new Subdivision("MK-402", "Bosilovo", null, "Municipality"));
    out.add(new Subdivision("MK-403", "Valandovo", null, "Municipality"));
    out.add(new Subdivision("MK-404", "Vasilevo", null, "Municipality"));
    out.add(new Subdivision("MK-405", "Gevgelija", null, "Municipality"));
    out.add(new Subdivision("MK-406", "Dojran", null, "Municipality"));
    out.add(new Subdivision("MK-407", "Konče", null, "Municipality"));
  }
}
