// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 1500 to 1999 of {@link Subdivision}.
 */
final class SubdivisionData3 {
  private SubdivisionData3() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("GB-DGY", "Dumfries and Galloway", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-DNC", "Doncaster", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-DND", "Dundee City", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-DOR", "Dorset", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-DRS", "Derry and Strabane", "GB-NIR", "District"));
    out.add(new Subdivision("GB-DUD", "Dudley", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-DUR", "Durham, County", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-EAL", "Ealing", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-EAY", "East Ayrshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-EDH", "Edinburgh, City of", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-EDU", "East Dunbartonshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-ELN", "East Lothian", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-ELS", "Eilean Siar", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-ENF", "Enfield", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-ENG", "England", null, "Country"));
    out.add(new Subdivision("GB-ERW", "East Renfrewshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-ERY", "East Riding of Yorkshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-ESS", "Essex", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-ESX", "East Sussex", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-FAL", "Falkirk", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-FIF", "Fife", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-FLN", "Flintshire [Sir y Fflint GB-FFL]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-FMO", "Fermanagh and Omagh", "GB-NIR", "District"));
    out.add(new Subdivision("GB-GAT", "Gateshead", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-GLG", "Glasgow City", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-GLS", "Gloucestershire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-GRE", "Greenwich", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-GWN", "Gwynedd", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-HAL", "Halton", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-HAM", "Hampshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-HAV", "Havering", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HCK", "Hackney", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HEF", "Herefordshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-HIL", "Hillingdon", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HLD", "Highland", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-HMF", "Hammersmith and Fulham", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HNS", "Hounslow", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HPL", "Hartlepool", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-HRT", "Hertfordshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-HRW", "Harrow", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-HRY", "Haringey", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-IOS", "Isles of Scilly", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-IOW", "Isle of Wight", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-ISL", "Islington", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-IVC", "Inverclyde", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-KEC", "Kensington and Chelsea", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-KEN", "Kent", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-KHL", "Kingston upon Hull", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-KIR", "Kirklees", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-KTT", "Kingston upon Thames", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-KWL", "Knowsley", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-LAN", "Lancashire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-LBC", "Lisburn and Castlereagh", "GB-NIR", "District"));
    out.add(new Subdivision("GB-LBH", "Lambeth", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-LCE", "Leicester", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-LDS", "Leeds", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-LEC", "Leicestershire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-LEW", "Lewisham", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-LIN", "Lincolnshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-LIV", "Liverpool", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-LND", "London, City of", "GB-ENG", "City corporation"));
    out.add(new Subdivision("GB-LUT", "Luton", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-MAN", "Manchester", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-MDB", "Middlesbrough", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-MDW", "Medway", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-MEA", "Mid and East Antrim", "GB-NIR", "District"));
    out.add(new Subdivision("GB-MIK", "Milton Keynes", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-MLN", "Midlothian", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-MON", "Monmouthshire [Sir Fynwy GB-FYN]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-MRT", "Merton", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-MRY", "Moray", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-MTY", "Merthyr Tydfil [Merthyr Tudful GB-MTU]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-MUL", "Mid-Ulster", "GB-NIR", "District"));
    out.add(new Subdivision("GB-NAY", "North Ayrshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-NBL", "Northumberland", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NEL", "North East Lincolnshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NET", "Newcastle upon Tyne", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-NFK", "Norfolk", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-NGM", "Nottingham", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NIR", "Northern Ireland", null, "Province"));
    out.add(new Subdivision("GB-NLK", "North Lanarkshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-NLN", "North Lincolnshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NMD", "Newry, Mourne and Down", "GB-NIR", "District"));
    out.add(new Subdivision("GB-NNH", "North Northamptonshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NSM", "North Somerset", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-NTL", "Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-NTT", "Nottinghamshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-NTY", "North Tyneside", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-NWM", "Newham", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-NWP", "Newport [Casnewydd GB-CNW]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-NYK", "North Yorkshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-OLD", "Oldham", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-ORK", "Orkney Islands", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-OXF", "Oxfordshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-PEM", "Pembrokeshire [Sir Benfro GB-BNF]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-PKN", "Perth and Kinross", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-PLY", "Plymouth", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-POR", "Portsmouth", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-POW", "Powys", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-PTE", "Peterborough", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-RCC", "Redcar and Cleveland", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-RCH", "Rochdale", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-RCT", "Rhondda Cynon Taff [Rhondda CynonTaf]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-RDB", "Redbridge", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-RDG", "Reading", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-RFW", "Renfrewshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-RIC", "Richmond upon Thames", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-ROT", "Rotherham", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-RUT", "Rutland", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SAW", "Sandwell", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SAY", "South Ayrshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-SCB", "Scottish Borders", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-SCT", "Scotland", null, "Country"));
    out.add(new Subdivision("GB-SFK", "Suffolk", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-SFT", "Sefton", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SGC", "South Gloucestershire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SHF", "Sheffield", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SHN", "St. Helens", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SHR", "Shropshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SKP", "Stockport", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SLF", "Salford", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SLG", "Slough", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SLK", "South Lanarkshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-SND", "Sunderland", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SOL", "Solihull", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SOM", "Somerset", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-SOS", "Southend-on-Sea", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SRY", "Surrey", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-STE", "Stoke-on-Trent", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-STG", "Stirling", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-STH", "Southampton", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-STN", "Sutton", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-STS", "Staffordshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-STT", "Stockton-on-Tees", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-STY", "South Tyneside", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-SWA", "Swansea [Abertawe GB-ATA]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-SWD", "Swindon", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-SWK", "Southwark", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-TAM", "Tameside", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-TFW", "Telford and Wrekin", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-THR", "Thurrock", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-TOB", "Torbay", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-TOF", "Torfaen [Tor-faen]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-TRF", "Trafford", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-TWH", "Tower Hamlets", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-VGL", "Vale of Glamorgan, The [Bro Morgannwg GB-BMG]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-WAR", "Warwickshire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-WBK", "West Berkshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WDU", "West Dunbartonshire", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-WFT", "Waltham Forest", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-WGN", "Wigan", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-WIL", "Wiltshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WKF", "Wakefield", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-WLL", "Walsall", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-WLN", "West Lothian", "GB-SCT", "Council area"));
    out.add(new Subdivision("GB-WLS", "Wales [Cymru GB-CYM]", null, "Country"));
    out.add(new Subdivision("GB-WLV", "Wolverhampton", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-WND", "Wandsworth", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-WNH", "West Northamptonshire", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WNM", "Windsor and Maidenhead", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WOK", "Wokingham", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WOR", "Worcestershire", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-WRL", "Wirral", "GB-ENG", "Metropolitan district"));
    out.add(new Subdivision("GB-WRT", "Warrington", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-WRX", "Wrexham [Wrecsam GB-WRC]", "GB-WLS", "Unitary authority"));
    out.add(new Subdivision("GB-WSM", "Westminster", "GB-ENG", "London borough"));
    out.add(new Subdivision("GB-WSX", "West Sussex", "GB-ENG", "Two-tier county"));
    out.add(new Subdivision("GB-YOR", "York", "GB-ENG", "Unitary authority"));
    out.add(new Subdivision("GB-ZET", "Shetland Islands", "GB-SCT", "Council area"));
    out.add(new Subdivision("GD-01", "Saint Andrew", null, "Parish"));
    out.add(new Subdivision("GD-02", "Saint David", null, "Parish"));
    out.add(new Subdivision("GD-03", "Saint George", null, "Parish"));
    out.add(new Subdivision("GD-04", "Saint John", null, "Parish"));
    out.add(new Subdivision("GD-05", "Saint Mark", null, "Parish"));
    out.add(new Subdivision("GD-06", "Saint Patrick", null, "Parish"));
    out.add(new Subdivision("GD-10", "Southern Grenadine Islands", null, "Dependency"));
    out.add(new Subdivision("GE-AB", "Abkhazia", null, "Autonomous republic"));
    out.add(new Subdivision("GE-AJ", "Ajaria", null, "Autonomous republic"));
    out.add(new Subdivision("GE-GU", "Guria", null, "Region"));
    out.add(new Subdivision("GE-IM", "Imereti", null, "Region"));
    out.add(new Subdivision("GE-KA", "K'akheti", null, "Region"));
    out.add(new Subdivision("GE-KK", "Kvemo Kartli", null, "Region"));
    out.add(new Subdivision("GE-MM", "Mtskheta-Mtianeti", null, "Region"));
    out.add(new Subdivision("GE-RL", "Rach'a-Lechkhumi-Kvemo Svaneti", null, "Region"));
    out.add(new Subdivision("GE-SJ", "Samtskhe-Javakheti", null, "Region"));
    out.add(new Subdivision("GE-SK", "Shida Kartli", null, "Region"));
    out.add(new Subdivision("GE-SZ", "Samegrelo-Zemo Svaneti", null, "Region"));
    out.add(new Subdivision("GE-TB", "Tbilisi", null, "City"));
    out.add(new Subdivision("GH-AA", "Greater Accra", null, "Region"));
    out.add(new Subdivision("GH-AF", "Ahafo", null, "Region"));
    out.add(new Subdivision("GH-AH", "Ashanti", null, "Region"));
    out.add(new Subdivision("GH-BE", "Bono East", null, "Region"));
    out.add(new Subdivision("GH-BO", "Bono", null, "Region"));
    out.add(new Subdivision("GH-CP", "Central", null, "Region"));
    out.add(new Subdivision("GH-EP", "Eastern", null, "Region"));
    out.add(new Subdivision("GH-NE", "North East", null, "Region"));
    out.add(new Subdivision("GH-NP", "Northern", null, "Region"));
    out.add(new Subdivision("GH-OT", "Oti", null, "Region"));
    out.add(new Subdivision("GH-SV", "Savannah", null, "Region"));
    out.add(new Subdivision("GH-TV", "Volta", null, "Region"));
    out.add(new Subdivision("GH-UE", "Upper East", null, "Region"));
    out.add(new Subdivision("GH-UW", "Upper West", null, "Region"));
    out.add(new Subdivision("GH-WN", "Western North", null, "Region"));
    out.add(new Subdivision("GH-WP", "Western", null, "Region"));
    out.add(new Subdivision("GL-AV", "Avannaata Kommunia", null, "Municipality"));
    out.add(new Subdivision("GL-KU", "Kommune Kujalleq", null, "Municipality"));
    out.add(new Subdivision("GL-QE", "Qeqqata Kommunia", null, "Municipality"));
    out.add(new Subdivision("GL-QT", "Kommune Qeqertalik", null, "Municipality"));
    out.add(new Subdivision("GL-SM", "Kommuneqarfik Sermersooq", null, "Municipality"));
    out.add(new Subdivision("GM-B", "Banjul", null, "City"));
    out.add(new Subdivision("GM-L", "Lower River", null, "Division"));
    out.add(new Subdivision("GM-M", "Central River", null, "Division"));
    out.add(new Subdivision("GM-N", "North Bank", null, "Division"));
    out.add(new Subdivision("GM-U", "Upper River", null, "Division"));
    out.add(new Subdivision("GM-W", "Western", null, "Division"));
    out.add(new Subdivision("GN-B", "Boké", null, "Administrative region"));
    out.add(new Subdivision("GN-BE", "Beyla", "GN-N", "Prefecture"));
    out.add(new Subdivision("GN-BF", "Boffa", "GN-B", "Prefecture"));
    out.add(new Subdivision("GN-BK", "Boké", "GN-B", "Prefecture"));
    out.add(new Subdivision("GN-C", "Conakry", null, "Governorate"));
    out.add(new Subdivision("GN-CO", "Coyah", "GN-D", "Prefecture"));
    out.add(new Subdivision("GN-D", "Kindia", null, "Administrative region"));
    out.add(new Subdivision("GN-DB", "Dabola", "GN-F", "Prefecture"));
    out.add(new Subdivision("GN-DI", "Dinguiraye", "GN-F", "Prefecture"));
    out.add(new Subdivision("GN-DL", "Dalaba", "GN-M", "Prefecture"));
    out.add(new Subdivision("GN-DU", "Dubréka", "GN-D", "Prefecture"));
    out.add(new Subdivision("GN-F", "Faranah", null, "Administrative region"));
    out.add(new Subdivision("GN-FA", "Faranah", "GN-F", "Prefecture"));
    out.add(new Subdivision("GN-FO", "Forécariah", "GN-D", "Prefecture"));
    out.add(new Subdivision("GN-FR", "Fria", "GN-B", "Prefecture"));
    out.add(new Subdivision("GN-GA", "Gaoual", "GN-B", "Prefecture"));
    out.add(new Subdivision("GN-GU", "Guékédou", "GN-N", "Prefecture"));
    out.add(new Subdivision("GN-K", "Kankan", null, "Administrative region"));
    out.add(new Subdivision("GN-KA", "Kankan", "GN-K", "Prefecture"));
    out.add(new Subdivision("GN-KB", "Koubia", "GN-L", "Prefecture"));
    out.add(new Subdivision("GN-KD", "Kindia", "GN-D", "Prefecture"));
    out.add(new Subdivision("GN-KE", "Kérouané", "GN-K", "Prefecture"));
    out.add(new Subdivision("GN-KN", "Koundara", "GN-B", "Prefecture"));
    out.add(new Subdivision("GN-KO", "Kouroussa", "GN-K", "Prefecture"));
    out.add(new Subdivision("GN-KS", "Kissidougou", "GN-F", "Prefecture"));
    out.add(new Subdivision("GN-L", "Labé", null, "Administrative region"));
    out.add(new Subdivision("GN-LA", "Labé", "GN-L", "Prefecture"));
    out.add(new Subdivision("GN-LE", "Lélouma", "GN-L", "Prefecture"));
    out.add(new Subdivision("GN-LO", "Lola", "GN-N", "Prefecture"));
    out.add(new Subdivision("GN-M", "Mamou", null, "Administrative region"));
    out.add(new Subdivision("GN-MC", "Macenta", "GN-N", "Prefecture"));
    out.add(new Subdivision("GN-MD", "Mandiana", "GN-K", "Prefecture"));
    out.add(new Subdivision("GN-ML", "Mali", "GN-L", "Prefecture"));
    out.add(new Subdivision("GN-MM", "Mamou", "GN-M", "Prefecture"));
    out.add(new Subdivision("GN-N", "Nzérékoré", null, "Administrative region"));
    out.add(new Subdivision("GN-NZ", "Nzérékoré", "GN-N", "Prefecture"));
    out.add(new Subdivision("GN-PI", "Pita", "GN-M", "Prefecture"));
    out.add(new Subdivision("GN-SI", "Siguiri", "GN-K", "Prefecture"));
    out.add(new Subdivision("GN-TE", "Télimélé", "GN-D", "Prefecture"));
    out.add(new Subdivision("GN-TO", "Tougué", "GN-L", "Prefecture"));
    out.add(new Subdivision("GN-YO", "Yomou", "GN-N", "Prefecture"));
    out.add(new Subdivision("GQ-AN", "Annobon", "GQ-I", "Province"));
    out.add(new Subdivision("GQ-BN", "Bioko Nord", "GQ-I", "Province"));
    out.add(new Subdivision("GQ-BS", "Bioko Sud", "GQ-I", "Province"));
    out.add(new Subdivision("GQ-C", "Région Continentale", null, "Region"));
    out.add(new Subdivision("GQ-CS", "Centro Sud", "GQ-C", "Province"));
    out.add(new Subdivision("GQ-DJ", "Djibloho", "GQ-C", "Province"));
    out.add(new Subdivision("GQ-I", "Région Insulaire", null, "Region"));
    out.add(new Subdivision("GQ-KN", "Kié-Ntem", "GQ-C", "Province"));
    out.add(new Subdivision("GQ-LI", "Littoral", "GQ-C", "Province"));
    out.add(new Subdivision("GQ-WN", "Wele-Nzas", "GQ-C", "Province"));
    out.add(new Subdivision("GR-69", "Ágion Óros", null, "Self-governed part"));
    out.add(new Subdivision("GR-A", "Anatolikí Makedonía kai Thráki", null, "Administrative region"));
    out.add(new Subdivision("GR-B", "Kentrikí Makedonía", null, "Administrative region"));
    out.add(new Subdivision("GR-C", "Dytikí Makedonía", null, "Administrative region"));
    out.add(new Subdivision("GR-D", "Ípeiros", null, "Administrative region"));
    out.add(new Subdivision("GR-E", "Thessalía", null, "Administrative region"));
    out.add(new Subdivision("GR-F", "Ionía Nísia", null, "Administrative region"));
    out.add(new Subdivision("GR-G", "Dytikí Elláda", null, "Administrative region"));
    out.add(new Subdivision("GR-H", "Stereá Elláda", null, "Administrative region"));
    out.add(new Subdivision("GR-I", "Attikí", null, "Administrative region"));
    out.add(new Subdivision("GR-J", "Pelopónnisos", null, "Administrative region"));
    out.add(new Subdivision("GR-K", "Vóreio Aigaío", null, "Administrative region"));
    out.add(new Subdivision("GR-L", "Nótio Aigaío", null, "Administrative region"));
    out.add(new Subdivision("GR-M", "Kríti", null, "Administrative region"));
    out.add(new Subdivision("GT-01", "Guatemala", null, "Department"));
    out.add(new Subdivision("GT-02", "El Progreso", null, "Department"));
    out.add(new Subdivision("GT-03", "Sacatepéquez", null, "Department"));
    out.add(new Subdivision("GT-04", "Chimaltenango", null, "Department"));
    out.add(new Subdivision("GT-05", "Escuintla", null, "Department"));
    out.add(new Subdivision("GT-06", "Santa Rosa", null, "Department"));
    out.add(new Subdivision("GT-07", "Sololá", null, "Department"));
    out.add(new Subdivision("GT-08", "Totonicapán", null, "Department"));
    out.add(new Subdivision("GT-09", "Quetzaltenango", null, "Department"));
    out.add(new Subdivision("GT-10", "Suchitepéquez", null, "Department"));
    out.add(new Subdivision("GT-11", "Retalhuleu", null, "Department"));
    out.add(new Subdivision("GT-12", "San Marcos", null, "Department"));
    out.add(new Subdivision("GT-13", "Huehuetenango", null, "Department"));
    out.add(new Subdivision("GT-14", "Quiché", null, "Department"));
    out.add(new Subdivision("GT-15", "Baja Verapaz", null, "Department"));
    out.add(new Subdivision("GT-16", "Alta Verapaz", null, "Department"));
    out.add(new Subdivision("GT-17", "Petén", null, "Department"));
    out.add(new Subdivision("GT-18", "Izabal", null, "Department"));
    out.add(new Subdivision("GT-19", "Zacapa", null, "Department"));
    out.add(new Subdivision("GT-20", "Chiquimula", null, "Department"));
    out.add(new Subdivision("GT-21", "Jalapa", null, "Department"));
    out.add(new Subdivision("GT-22", "Jutiapa", null, "Department"));
    out.add(new Subdivision("GW-BA", "Bafatá", "GW-L", "Region"));
    out.add(new Subdivision("GW-BL", "Bolama / Bijagós", "GW-S", "Region"));
    out.add(new Subdivision("GW-BM", "Biombo", "GW-N", "Region"));
    out.add(new Subdivision("GW-BS", "Bissau", null, "Autonomous sector"));
    out.add(new Subdivision("GW-CA", "Cacheu", "GW-N", "Region"));
    out.add(new Subdivision("GW-GA", "Gabú", "GW-L", "Region"));
    out.add(new Subdivision("GW-L", "Leste", null, "Province"));
    out.add(new Subdivision("GW-N", "Norte", null, "Province"));
    out.add(new Subdivision("GW-OI", "Oio", "GW-N", "Region"));
    out.add(new Subdivision("GW-QU", "Quinara", "GW-S", "Region"));
    out.add(new Subdivision("GW-S", "Sul", null, "Province"));
    out.add(new Subdivision("GW-TO", "Tombali", "GW-S", "Region"));
    out.add(new Subdivision("GY-BA", "Barima-Waini", null, "Region"));
    out.add(new Subdivision("GY-CU", "Cuyuni-Mazaruni", null, "Region"));
    out.add(new Subdivision("GY-DE", "Demerara-Mahaica", null, "Region"));
    out.add(new Subdivision("GY-EB", "East Berbice-Corentyne", null, "Region"));
    out.add(new Subdivision("GY-ES", "Essequibo Islands-West Demerara", null, "Region"));
    out.add(new Subdivision("GY-MA", "Mahaica-Berbice", null, "Region"));
    out.add(new Subdivision("GY-PM", "Pomeroon-Supenaam", null, "Region"));
    out.add(new Subdivision("GY-PT", "Potaro-Siparuni", null, "Region"));
    out.add(new Subdivision("GY-UD", "Upper Demerara-Berbice", null, "Region"));
    out.add(new Subdivision("GY-UT", "Upper Takutu-Upper Essequibo", null, "Region"));
    out.add(new Subdivision("HN-AT", "Atlántida", null, "Department"));
    out.add(new Subdivision("HN-CH", "Choluteca", null, "Department"));
    out.add(new Subdivision("HN-CL", "Colón", null, "Department"));
    out.add(new Subdivision("HN-CM", "Comayagua", null, "Department"));
    out.add(new Subdivision("HN-CP", "Copán", null, "Department"));
    out.add(new Subdivision("HN-CR", "Cortés", null, "Department"));
    out.add(new Subdivision("HN-EP", "El Paraíso", null, "Department"));
    out.add(new Subdivision("HN-FM", "Francisco Morazán", null, "Department"));
    out.add(new Subdivision("HN-GD", "Gracias a Dios", null, "Department"));
    out.add(new Subdivision("HN-IB", "Islas de la Bahía", null, "Department"));
    out.add(new Subdivision("HN-IN", "Intibucá", null, "Department"));
    out.add(new Subdivision("HN-LE", "Lempira", null, "Department"));
    out.add(new Subdivision("HN-LP", "La Paz", null, "Department"));
    out.add(new Subdivision("HN-OC", "Ocotepeque", null, "Department"));
    out.add(new Subdivision("HN-OL", "Olancho", null, "Department"));
    out.add(new Subdivision("HN-SB", "Santa Bárbara", null, "Department"));
    out.add(new Subdivision("HN-VA", "Valle", null, "Department"));
    out.add(new Subdivision("HN-YO", "Yoro", null, "Department"));
    out.add(new Subdivision("HR-01", "Zagrebačka županija", null, "County"));
    out.add(new Subdivision("HR-02", "Krapinsko-zagorska županija", null, "County"));
    out.add(new Subdivision("HR-03", "Sisačko-moslavačka županija", null, "County"));
    out.add(new Subdivision("HR-04", "Karlovačka županija", null, "County"));
    out.add(new Subdivision("HR-05", "Varaždinska županija", null, "County"));
    out.add(new Subdivision("HR-06", "Koprivničko-križevačka županija", null, "County"));
    out.add(new Subdivision("HR-07", "Bjelovarsko-bilogorska županija", null, "County"));
    out.add(new Subdivision("HR-08", "Primorsko-goranska županija", null, "County"));
    out.add(new Subdivision("HR-09", "Ličko-senjska županija", null, "County"));
    out.add(new Subdivision("HR-10", "Virovitičko-podravska županija", null, "County"));
    out.add(new Subdivision("HR-11", "Požeško-slavonska županija", null, "County"));
    out.add(new Subdivision("HR-12", "Brodsko-posavska županija", null, "County"));
    out.add(new Subdivision("HR-13", "Zadarska županija", null, "County"));
    out.add(new Subdivision("HR-14", "Osječko-baranjska županija", null, "County"));
    out.add(new Subdivision("HR-15", "Šibensko-kninska županija", null, "County"));
    out.add(new Subdivision("HR-16", "Vukovarsko-srijemska županija", null, "County"));
    out.add(new Subdivision("HR-17", "Splitsko-dalmatinska županija", null, "County"));
    out.add(new Subdivision("HR-18", "Istarska županija", null, "County"));
    out.add(new Subdivision("HR-19", "Dubrovačko-neretvanska županija", null, "County"));
    out.add(new Subdivision("HR-20", "Međimurska županija", null, "County"));
    out.add(new Subdivision("HR-21", "Grad Zagreb", null, "City"));
    out.add(new Subdivision("HT-AR", "Artibonite", null, "Department"));
    out.add(new Subdivision("HT-CE", "Centre", null, "Department"));
    out.add(new Subdivision("HT-GA", "Grande’Anse", null, "Department"));
    out.add(new Subdivision("HT-ND", "Nord", null, "Department"));
    out.add(new Subdivision("HT-NE", "Nord-Est", null, "Department"));
    out.add(new Subdivision("HT-NI", "Nippes", null, "Department"));
    out.add(new Subdivision("HT-NO", "Nord-Ouest", null, "Department"));
    out.add(new Subdivision("HT-OU", "Ouest", null, "Department"));
    out.add(new Subdivision("HT-SD", "Sud", null, "Department"));
    out.add(new Subdivision("HT-SE", "Sud-Est", null, "Department"));
    out.add(new Subdivision("HU-BA", "Baranya", null, "County"));
    out.add(new Subdivision("HU-BC", "Békéscsaba", null, "City with county rights"));
    out.add(new Subdivision("HU-BE", "Békés", null, "County"));
    out.add(new Subdivision("HU-BK", "Bács-Kiskun", null, "County"));
    out.add(new Subdivision("HU-BU", "Budapest", null, "Capital city"));
    out.add(new Subdivision("HU-BZ", "Borsod-Abaúj-Zemplén", null, "County"));
    out.add(new Subdivision("HU-CS", "Csongrád-Csanád", null, "County"));
    out.add(new Subdivision("HU-DE", "Debrecen", null, "City with county rights"));
    out.add(new Subdivision("HU-DU", "Dunaújváros", null, "City with county rights"));
    out.add(new Subdivision("HU-EG", "Eger", null, "City with county rights"));
    out.add(new Subdivision("HU-ER", "Érd", null, "City with county rights"));
    out.add(new Subdivision("HU-FE", "Fejér", null, "County"));
    out.add(new Subdivision("HU-GS", "Győr-Moson-Sopron", null, "County"));
    out.add(new Subdivision("HU-GY", "Győr", null, "City with county rights"));
    out.add(new Subdivision("HU-HB", "Hajdú-Bihar", null, "County"));
    out.add(new Subdivision("HU-HE", "Heves", null, "County"));
    out.add(new Subdivision("HU-HV", "Hódmezővásárhely", null, "City with county rights"));
    out.add(new Subdivision("HU-JN", "Jász-Nagykun-Szolnok", null, "County"));
    out.add(new Subdivision("HU-KE", "Komárom-Esztergom", null, "County"));
    out.add(new Subdivision("HU-KM", "Kecskemét", null, "City with county rights"));
    out.add(new Subdivision("HU-KV", "Kaposvár", null, "City with county rights"));
    out.add(new Subdivision("HU-MI", "Miskolc", null, "City with county rights"));
    out.add(new Subdivision("HU-NK", "Nagykanizsa", null, "City with county rights"));
    out.add(new Subdivision("HU-NO", "Nógrád", null, "County"));
    out.add(new Subdivision("HU-NY", "Nyíregyháza", null, "City with county rights"));
    out.add(new Subdivision("HU-PE", "Pest", null, "County"));
    out.add(new Subdivision("HU-PS", "Pécs", null, "City with county rights"));
    out.add(new Subdivision("HU-SD", "Szeged", null, "City with county rights"));
    out.add(new Subdivision("HU-SF", "Székesfehérvár", null, "City with county rights"));
    out.add(new Subdivision("HU-SH", "Szombathely", null, "City with county rights"));
    out.add(new Subdivision("HU-SK", "Szolnok", null, "City with county rights"));
    out.add(new Subdivision("HU-SN", "Sopron", null, "City with county rights"));
    out.add(new Subdivision("HU-SO", "Somogy", null, "County"));
    out.add(new Subdivision("HU-SS", "Szekszárd", null, "City with county rights"));
    out.add(new Subdivision("HU-ST", "Salgótarján", null, "City with county rights"));
    out.add(new Subdivision("HU-SZ", "Szabolcs-Szatmár-Bereg", null, "County"));
    out.add(new Subdivision("HU-TB", "Tatabánya", null, "City with county rights"));
    out.add(new Subdivision("HU-TO", "Tolna", null, "County"));
    out.add(new Subdivision("HU-VA", "Vas", null, "County"));
    out.add(new Subdivision("HU-VE", "Veszprém", null, "County"));
    out.add(new Subdivision("HU-VM", "Veszprém", null, "City with county rights"));
    out.add(new Subdivision("HU-ZA", "Zala", null, "County"));
    out.add(new Subdivision("HU-ZE", "Zalaegerszeg", null, "City with county rights"));
    out.add(new Subdivision("ID-AC", "Aceh", "ID-SM", "Province"));
    out.add(new Subdivision("ID-BA", "Bali", "ID-NU", "Province"));
    out.add(new Subdivision("ID-BB", "Kepulauan Bangka Belitung", "ID-SM", "Province"));
    out.add(new Subdivision("ID-BE", "Bengkulu", "ID-SM", "Province"));
    out.add(new Subdivision("ID-BT", "Banten", "ID-JW", "Province"));
    out.add(new Subdivision("ID-GO", "Gorontalo", "ID-SL", "Province"));
    out.add(new Subdivision("ID-JA", "Jambi", "ID-SM", "Province"));
    out.add(new Subdivision("ID-JB", "Jawa Barat", "ID-JW", "Province"));
    out.add(new Subdivision("ID-JI", "Jawa Timur", "ID-JW", "Province"));
    out.add(new Subdivision("ID-JK", "Jakarta Raya", "ID-JW", "Capital district"));
    out.add(new Subdivision("ID-JT", "Jawa Tengah", "ID-JW", "Province"));
    out.add(new Subdivision("ID-JW", "Jawa", null, "Geographical unit"));
    out.add(new Subdivision("ID-KA", "Kalimantan", null, "Geographical unit"));
    out.add(new Subdivision("ID-KB", "Kalimantan Barat", "ID-KA", "Province"));
    out.add(new Subdivision("ID-KI", "Kalimantan Timur", "ID-KA", "Province"));
    out.add(new Subdivision("ID-KR", "Kepulauan Riau", "ID-SM", "Province"));
    out.add(new Subdivision("ID-KS", "Kalimantan Selatan", "ID-KA", "Province"));
    out.add(new Subdivision("ID-KT", "Kalimantan Tengah", "ID-KA", "Province"));
    out.add(new Subdivision("ID-KU", "Kalimantan Utara", "ID-KA", "Province"));
    out.add(new Subdivision("ID-LA", "Lampung", "ID-SM", "Province"));
    out.add(new Subdivision("ID-MA", "Maluku", "ID-ML", "Province"));
    out.add(new Subdivision("ID-ML", "Maluku", null, "Geographical unit"));
    out.add(new Subdivision("ID-MU", "Maluku Utara", "ID-ML", "Province"));
    out.add(new Subdivision("ID-NB", "Nusa Tenggara Barat", "ID-NU", "Province"));
    out.add(new Subdivision("ID-NT", "Nusa Tenggara Timur", "ID-NU", "Province"));
    out.add(new Subdivision("ID-NU", "Nusa Tenggara", null, "Geographical unit"));
    out.add(new Subdivision("ID-PA", "Papua", "ID-PP", "Province"));
    out.add(new Subdivision("ID-PB", "Papua Barat", "ID-PP", "Province"));
    out.add(new Subdivision("ID-PD", "Papua Barat Daya", "ID-PP", "Province"));
    out.add(new Subdivision("ID-PE", "Papua Pengunungan", "ID-PP", "Province"));
    out.add(new Subdivision("ID-PP", "Papua", null, "Geographical unit"));
    out.add(new Subdivision("ID-PS", "Papua Selatan", "ID-PP", "Province"));
    out.add(new Subdivision("ID-PT", "Papua Tengah", "ID-PP", "Province"));
    out.add(new Subdivision("ID-RI", "Riau", "ID-SM", "Province"));
    out.add(new Subdivision("ID-SA", "Sulawesi Utara", "ID-SL", "Province"));
    out.add(new Subdivision("ID-SB", "Sumatera Barat", "ID-SM", "Province"));
    out.add(new Subdivision("ID-SG", "Sulawesi Tenggara", "ID-SL", "Province"));
    out.add(new Subdivision("ID-SL", "Sulawesi", null, "Geographical unit"));
    out.add(new Subdivision("ID-SM", "Sumatera", null, "Geographical unit"));
    out.add(new Subdivision("ID-SN", "Sulawesi Selatan", "ID-SL", "Province"));
    out.add(new Subdivision("ID-SR", "Sulawesi Barat", "ID-SL", "Province"));
    out.add(new Subdivision("ID-SS", "Sumatera Selatan", "ID-SM", "Province"));
    out.add(new Subdivision("ID-ST", "Sulawesi Tengah", "ID-SL", "Province"));
    out.add(new Subdivision("ID-SU", "Sumatera Utara", "ID-SM", "Province"));
    out.add(new Subdivision("ID-YO", "Yogyakarta", "ID-JW", "Special region"));
    out.add(new Subdivision("IE-C", "Connaught", null, "Province"));
    out.add(new Subdivision("IE-CE", "Clare", "IE-M", "County"));
    out.add(new Subdivision("IE-CN", "Cavan", "IE-U", "County"));
    out.add(new Subdivision("IE-CO", "Cork", "IE-M", "County"));
    out.add(new Subdivision("IE-CW", "Carlow", "IE-L", "County"));
    out.add(new Subdivision("IE-D", "Dublin", "IE-L", "County"));
    out.add(new Subdivision("IE-DL", "Donegal", "IE-U", "County"));
    out.add(new Subdivision("IE-G", "Galway", "IE-C", "County"));
    out.add(new Subdivision("IE-KE", "Kildare", "IE-L", "County"));
    out.add(new Subdivision("IE-KK", "Kilkenny", "IE-L", "County"));
    out.add(new Subdivision("IE-KY", "Kerry", "IE-M", "County"));
    out.add(new Subdivision("IE-L", "Leinster", null, "Province"));
    out.add(new Subdivision("IE-LD", "Longford", "IE-L", "County"));
    out.add(new Subdivision("IE-LH", "Louth", "IE-L", "County"));
    out.add(new Subdivision("IE-LK", "Limerick", "IE-M", "County"));
    out.add(new Subdivision("IE-LM", "Leitrim", "IE-C", "County"));
    out.add(new Subdivision("IE-LS", "Laois", "IE-L", "County"));
    out.add(new Subdivision("IE-M", "Munster", null, "Province"));
    out.add(new Subdivision("IE-MH", "Meath", "IE-L", "County"));
    out.add(new Subdivision("IE-MN", "Monaghan", "IE-U", "County"));
    out.add(new Subdivision("IE-MO", "Mayo", "IE-C", "County"));
    out.add(new Subdivision("IE-OY", "Offaly", "IE-L", "County"));
    out.add(new Subdivision("IE-RN", "Roscommon", "IE-C", "County"));
    out.add(new Subdivision("IE-SO", "Sligo", "IE-C", "County"));
    out.add(new Subdivision("IE-TA", "Tipperary", "IE-M", "County"));
    out.add(new Subdivision("IE-U", "Ulster", null, "Province"));
    out.add(new Subdivision("IE-WD", "Waterford", "IE-M", "County"));
    out.add(new Subdivision("IE-WH", "Westmeath", "IE-L", "County"));
    out.add(new Subdivision("IE-WW", "Wicklow", "IE-L", "County"));
    out.add(new Subdivision("IE-WX", "Wexford", "IE-L", "County"));
    out.add(new Subdivision("IL-D", "Al Janūbī", null, "District"));
    out.add(new Subdivision("IL-HA", "Ḩayfā", null, "District"));
    out.add(new Subdivision("IL-JM", "Al Quds", null, "District"));
    out.add(new Subdivision("IL-M", "Al Awsaţ", null, "District"));
    out.add(new Subdivision("IL-TA", "Tall Abīb", null, "District"));
    out.add(new Subdivision("IL-Z", "Ash Shamālī", null, "District"));
    out.add(new Subdivision("IN-AN", "Andaman and Nicobar Islands", null, "Union territory"));
    out.add(new Subdivision("IN-AP", "Andhra Pradesh", null, "State"));
    out.add(new Subdivision("IN-AR", "Arunāchal Pradesh", null, "State"));
  }
}
