// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 4000 to 4499 of {@link Subdivision}.
 */
final class SubdivisionData8 {
  private SubdivisionData8() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("SI-026", "Duplek", null, "Municipality"));
    out.add(new Subdivision("SI-027", "Gorenja vas-Poljane", null, "Municipality"));
    out.add(new Subdivision("SI-028", "Gorišnica", null, "Municipality"));
    out.add(new Subdivision("SI-029", "Gornja Radgona", null, "Municipality"));
    out.add(new Subdivision("SI-030", "Gornji Grad", null, "Municipality"));
    out.add(new Subdivision("SI-031", "Gornji Petrovci", null, "Municipality"));
    out.add(new Subdivision("SI-032", "Grosuplje", null, "Municipality"));
    out.add(new Subdivision("SI-033", "Šalovci", null, "Municipality"));
    out.add(new Subdivision("SI-034", "Hrastnik", null, "Municipality"));
    out.add(new Subdivision("SI-035", "Hrpelje-Kozina", null, "Municipality"));
    out.add(new Subdivision("SI-036", "Idrija", null, "Municipality"));
    out.add(new Subdivision("SI-037", "Ig", null, "Municipality"));
    out.add(new Subdivision("SI-038", "Ilirska Bistrica", null, "Municipality"));
    out.add(new Subdivision("SI-039", "Ivančna Gorica", null, "Municipality"));
    out.add(new Subdivision("SI-040", "Izola", null, "Municipality"));
    out.add(new Subdivision("SI-041", "Jesenice", null, "Municipality"));
    out.add(new Subdivision("SI-042", "Juršinci", null, "Municipality"));
    out.add(new Subdivision("SI-043", "Kamnik", null, "Municipality"));
    out.add(new Subdivision("SI-044", "Kanal ob Soči", null, "Municipality"));
    out.add(new Subdivision("SI-045", "Kidričevo", null, "Municipality"));
    out.add(new Subdivision("SI-046", "Kobarid", null, "Municipality"));
    out.add(new Subdivision("SI-047", "Kobilje", null, "Municipality"));
    out.add(new Subdivision("SI-048", "Kočevje", null, "Municipality"));
    out.add(new Subdivision("SI-049", "Komen", null, "Municipality"));
    out.add(new Subdivision("SI-050", "Koper", null, "Urban municipality"));
    out.add(new Subdivision("SI-051", "Kozje", null, "Municipality"));
    out.add(new Subdivision("SI-052", "Kranj", null, "Urban municipality"));
    out.add(new Subdivision("SI-053", "Kranjska Gora", null, "Municipality"));
    out.add(new Subdivision("SI-054", "Krško", null, "Urban municipality"));
    out.add(new Subdivision("SI-055", "Kungota", null, "Municipality"));
    out.add(new Subdivision("SI-056", "Kuzma", null, "Municipality"));
    out.add(new Subdivision("SI-057", "Laško", null, "Municipality"));
    out.add(new Subdivision("SI-058", "Lenart", null, "Municipality"));
    out.add(new Subdivision("SI-059", "Lendava", null, "Municipality"));
    out.add(new Subdivision("SI-060", "Litija", null, "Municipality"));
    out.add(new Subdivision("SI-061", "Ljubljana", null, "Urban municipality"));
    out.add(new Subdivision("SI-062", "Ljubno", null, "Municipality"));
    out.add(new Subdivision("SI-063", "Ljutomer", null, "Municipality"));
    out.add(new Subdivision("SI-064", "Logatec", null, "Municipality"));
    out.add(new Subdivision("SI-065", "Loška dolina", null, "Municipality"));
    out.add(new Subdivision("SI-066", "Loški Potok", null, "Municipality"));
    out.add(new Subdivision("SI-067", "Luče", null, "Municipality"));
    out.add(new Subdivision("SI-068", "Lukovica", null, "Municipality"));
    out.add(new Subdivision("SI-069", "Majšperk", null, "Municipality"));
    out.add(new Subdivision("SI-070", "Maribor", null, "Urban municipality"));
    out.add(new Subdivision("SI-071", "Medvode", null, "Municipality"));
    out.add(new Subdivision("SI-072", "Mengeš", null, "Municipality"));
    out.add(new Subdivision("SI-073", "Metlika", null, "Municipality"));
    out.add(new Subdivision("SI-074", "Mežica", null, "Municipality"));
    out.add(new Subdivision("SI-075", "Miren-Kostanjevica", null, "Municipality"));
    out.add(new Subdivision("SI-076", "Mislinja", null, "Municipality"));
    out.add(new Subdivision("SI-077", "Moravče", null, "Municipality"));
    out.add(new Subdivision("SI-078", "Moravske Toplice", null, "Municipality"));
    out.add(new Subdivision("SI-079", "Mozirje", null, "Municipality"));
    out.add(new Subdivision("SI-080", "Murska Sobota", null, "Urban municipality"));
    out.add(new Subdivision("SI-081", "Muta", null, "Municipality"));
    out.add(new Subdivision("SI-082", "Naklo", null, "Municipality"));
    out.add(new Subdivision("SI-083", "Nazarje", null, "Municipality"));
    out.add(new Subdivision("SI-084", "Nova Gorica", null, "Urban municipality"));
    out.add(new Subdivision("SI-085", "Novo Mesto", null, "Urban municipality"));
    out.add(new Subdivision("SI-086", "Odranci", null, "Municipality"));
    out.add(new Subdivision("SI-087", "Ormož", null, "Municipality"));
    out.add(new Subdivision("SI-088", "Osilnica", null, "Municipality"));
    out.add(new Subdivision("SI-089", "Pesnica", null, "Municipality"));
    out.add(new Subdivision("SI-090", "Piran", null, "Municipality"));
    out.add(new Subdivision("SI-091", "Pivka", null, "Municipality"));
    out.add(new Subdivision("SI-092", "Podčetrtek", null, "Municipality"));
    out.add(new Subdivision("SI-093", "Podvelka", null, "Municipality"));
    out.add(new Subdivision("SI-094", "Postojna", null, "Municipality"));
    out.add(new Subdivision("SI-095", "Preddvor", null, "Municipality"));
    out.add(new Subdivision("SI-096", "Ptuj", null, "Urban municipality"));
    out.add(new Subdivision("SI-097", "Puconci", null, "Municipality"));
    out.add(new Subdivision("SI-098", "Rače-Fram", null, "Municipality"));
    out.add(new Subdivision("SI-099", "Radeče", null, "Municipality"));
    out.add(new Subdivision("SI-100", "Radenci", null, "Municipality"));
    out.add(new Subdivision("SI-101", "Radlje ob Dravi", null, "Municipality"));
    out.add(new Subdivision("SI-102", "Radovljica", null, "Municipality"));
    out.add(new Subdivision("SI-103", "Ravne na Koroškem", null, "Municipality"));
    out.add(new Subdivision("SI-104", "Ribnica", null, "Municipality"));
    out.add(new Subdivision("SI-105", "Rogašovci", null, "Municipality"));
    out.add(new Subdivision("SI-106", "Rogaška Slatina", null, "Municipality"));
    out.add(new Subdivision("SI-107", "Rogatec", null, "Municipality"));
    out.add(new Subdivision("SI-108", "Ruše", null, "Municipality"));
    out.add(new Subdivision("SI-109", "Semič", null, "Municipality"));
    out.add(new Subdivision("SI-110", "Sevnica", null, "Municipality"));
    out.add(new Subdivision("SI-111", "Sežana", null, "Municipality"));
    out.add(new Subdivision("SI-112", "Slovenj Gradec", null, "Urban municipality"));
    out.add(new Subdivision("SI-113", "Slovenska Bistrica", null, "Municipality"));
    out.add(new Subdivision("SI-114", "Slovenske Konjice", null, "Municipality"));
    out.add(new Subdivision("SI-115", "Starše", null, "Municipality"));
    out.add(new Subdivision("SI-116", "Sveti Jurij ob Ščavnici", null, "Municipality"));
    out.add(new Subdivision("SI-117", "Šenčur", null, "Municipality"));
    out.add(new Subdivision("SI-118", "Šentilj", null, "Municipality"));
    out.add(new Subdivision("SI-119", "Šentjernej", null, "Municipality"));
    out.add(new Subdivision("SI-120", "Šentjur", null, "Municipality"));
    out.add(new Subdivision("SI-121", "Škocjan", null, "Municipality"));
    out.add(new Subdivision("SI-122", "Škofja Loka", null, "Municipality"));
    out.add(new Subdivision("SI-123", "Škofljica", null, "Municipality"));
    out.add(new Subdivision("SI-124", "Šmarje pri Jelšah", null, "Municipality"));
    out.add(new Subdivision("SI-125", "Šmartno ob Paki", null, "Municipality"));
    out.add(new Subdivision("SI-126", "Šoštanj", null, "Municipality"));
    out.add(new Subdivision("SI-127", "Štore", null, "Municipality"));
    out.add(new Subdivision("SI-128", "Tolmin", null, "Municipality"));
    out.add(new Subdivision("SI-129", "Trbovlje", null, "Municipality"));
    out.add(new Subdivision("SI-130", "Trebnje", null, "Municipality"));
    out.add(new Subdivision("SI-131", "Tržič", null, "Municipality"));
    out.add(new Subdivision("SI-132", "Turnišče", null, "Municipality"));
    out.add(new Subdivision("SI-133", "Velenje", null, "Urban municipality"));
    out.add(new Subdivision("SI-134", "Velike Lašče", null, "Municipality"));
    out.add(new Subdivision("SI-135", "Videm", null, "Municipality"));
    out.add(new Subdivision("SI-136", "Vipava", null, "Municipality"));
    out.add(new Subdivision("SI-137", "Vitanje", null, "Municipality"));
    out.add(new Subdivision("SI-138", "Vodice", null, "Municipality"));
    out.add(new Subdivision("SI-139", "Vojnik", null, "Municipality"));
    out.add(new Subdivision("SI-140", "Vrhnika", null, "Municipality"));
    out.add(new Subdivision("SI-141", "Vuzenica", null, "Municipality"));
    out.add(new Subdivision("SI-142", "Zagorje ob Savi", null, "Municipality"));
    out.add(new Subdivision("SI-143", "Zavrč", null, "Municipality"));
    out.add(new Subdivision("SI-144", "Zreče", null, "Municipality"));
    out.add(new Subdivision("SI-146", "Železniki", null, "Municipality"));
    out.add(new Subdivision("SI-147", "Žiri", null, "Municipality"));
    out.add(new Subdivision("SI-148", "Benedikt", null, "Municipality"));
    out.add(new Subdivision("SI-149", "Bistrica ob Sotli", null, "Municipality"));
    out.add(new Subdivision("SI-150", "Bloke", null, "Municipality"));
    out.add(new Subdivision("SI-151", "Braslovče", null, "Municipality"));
    out.add(new Subdivision("SI-152", "Cankova", null, "Municipality"));
    out.add(new Subdivision("SI-153", "Cerkvenjak", null, "Municipality"));
    out.add(new Subdivision("SI-154", "Dobje", null, "Municipality"));
    out.add(new Subdivision("SI-155", "Dobrna", null, "Municipality"));
    out.add(new Subdivision("SI-156", "Dobrovnik", null, "Municipality"));
    out.add(new Subdivision("SI-157", "Dolenjske Toplice", null, "Municipality"));
    out.add(new Subdivision("SI-158", "Grad", null, "Municipality"));
    out.add(new Subdivision("SI-159", "Hajdina", null, "Municipality"));
    out.add(new Subdivision("SI-160", "Hoče-Slivnica", null, "Municipality"));
    out.add(new Subdivision("SI-161", "Hodoš", null, "Municipality"));
    out.add(new Subdivision("SI-162", "Horjul", null, "Municipality"));
    out.add(new Subdivision("SI-163", "Jezersko", null, "Municipality"));
    out.add(new Subdivision("SI-164", "Komenda", null, "Municipality"));
    out.add(new Subdivision("SI-165", "Kostel", null, "Municipality"));
    out.add(new Subdivision("SI-166", "Križevci", null, "Municipality"));
    out.add(new Subdivision("SI-167", "Lovrenc na Pohorju", null, "Municipality"));
    out.add(new Subdivision("SI-168", "Markovci", null, "Municipality"));
    out.add(new Subdivision("SI-169", "Miklavž na Dravskem polju", null, "Municipality"));
    out.add(new Subdivision("SI-170", "Mirna Peč", null, "Municipality"));
    out.add(new Subdivision("SI-171", "Oplotnica", null, "Municipality"));
    out.add(new Subdivision("SI-172", "Podlehnik", null, "Municipality"));
    out.add(new Subdivision("SI-173", "Polzela", null, "Municipality"));
    out.add(new Subdivision("SI-174", "Prebold", null, "Municipality"));
    out.add(new Subdivision("SI-175", "Prevalje", null, "Municipality"));
    out.add(new Subdivision("SI-176", "Razkrižje", null, "Municipality"));
    out.add(new Subdivision("SI-177", "Ribnica na Pohorju", null, "Municipality"));
    out.add(new Subdivision("SI-178", "Selnica ob Dravi", null, "Municipality"));
    out.add(new Subdivision("SI-179", "Sodražica", null, "Municipality"));
    out.add(new Subdivision("SI-180", "Solčava", null, "Municipality"));
    out.add(new Subdivision("SI-181", "Sveta Ana", null, "Municipality"));
    out.add(new Subdivision("SI-182", "Sveti Andraž v Slovenskih goricah", null, "Municipality"));
    out.add(new Subdivision("SI-183", "Šempeter-Vrtojba", null, "Municipality"));
    out.add(new Subdivision("SI-184", "Tabor", null, "Municipality"));
    out.add(new Subdivision("SI-185", "Trnovska Vas", null, "Municipality"));
    out.add(new Subdivision("SI-186", "Trzin", null, "Municipality"));
    out.add(new Subdivision("SI-187", "Velika Polana", null, "Municipality"));
    out.add(new Subdivision("SI-188", "Veržej", null, "Municipality"));
    out.add(new Subdivision("SI-189", "Vransko", null, "Municipality"));
    out.add(new Subdivision("SI-190", "Žalec", null, "Municipality"));
    out.add(new Subdivision("SI-191", "Žetale", null, "Municipality"));
    out.add(new Subdivision("SI-192", "Žirovnica", null, "Municipality"));
    out.add(new Subdivision("SI-193", "Žužemberk", null, "Municipality"));
    out.add(new Subdivision("SI-194", "Šmartno pri Litiji", null, "Municipality"));
    out.add(new Subdivision("SI-195", "Apače", null, "Municipality"));
    out.add(new Subdivision("SI-196", "Cirkulane", null, "Municipality"));
    out.add(new Subdivision("SI-197", "Kostanjevica na Krki", null, "Municipality"));
    out.add(new Subdivision("SI-198", "Makole", null, "Municipality"));
    out.add(new Subdivision("SI-199", "Mokronog-Trebelno", null, "Municipality"));
    out.add(new Subdivision("SI-200", "Poljčane", null, "Municipality"));
    out.add(new Subdivision("SI-201", "Renče-Vogrsko", null, "Municipality"));
    out.add(new Subdivision("SI-202", "Središče ob Dravi", null, "Municipality"));
    out.add(new Subdivision("SI-203", "Straža", null, "Municipality"));
    out.add(new Subdivision("SI-204", "Sveta Trojica v Slovenskih goricah", null, "Municipality"));
    out.add(new Subdivision("SI-205", "Sveti Tomaž", null, "Municipality"));
    out.add(new Subdivision("SI-206", "Šmarješke Toplice", null, "Municipality"));
    out.add(new Subdivision("SI-207", "Gorje", null, "Municipality"));
    out.add(new Subdivision("SI-208", "Log-Dragomer", null, "Municipality"));
    out.add(new Subdivision("SI-209", "Rečica ob Savinji", null, "Municipality"));
    out.add(new Subdivision("SI-210", "Sveti Jurij v Slovenskih goricah", null, "Municipality"));
    out.add(new Subdivision("SI-211", "Šentrupert", null, "Municipality"));
    out.add(new Subdivision("SI-212", "Mirna", null, "Municipality"));
    out.add(new Subdivision("SI-213", "Ankaran", null, "Municipality"));
    out.add(new Subdivision("SK-BC", "Banskobystrický kraj", null, "Region"));
    out.add(new Subdivision("SK-BL", "Bratislavský kraj", null, "Region"));
    out.add(new Subdivision("SK-KI", "Košický kraj", null, "Region"));
    out.add(new Subdivision("SK-NI", "Nitriansky kraj", null, "Region"));
    out.add(new Subdivision("SK-PV", "Prešovský kraj", null, "Region"));
    out.add(new Subdivision("SK-TA", "Trnavský kraj", null, "Region"));
    out.add(new Subdivision("SK-TC", "Trenčiansky kraj", null, "Region"));
    out.add(new Subdivision("SK-ZI", "Žilinský kraj", null, "Region"));
    out.add(new Subdivision("SL-E", "Eastern", null, "Province"));
    out.add(new Subdivision("SL-N", "Northern", null, "Province"));
    out.add(new Subdivision("SL-NW", "North Western", null, "Province"));
    out.add(new Subdivision("SL-S", "Southern", null, "Province"));
    out.add(new Subdivision("SL-W", "Western Area (Freetown)", null, "Area"));
    out.add(new Subdivision("SM-01", "Acquaviva", null, "Municipality"));
    out.add(new Subdivision("SM-02", "Chiesanuova", null, "Municipality"));
    out.add(new Subdivision("SM-03", "Domagnano", null, "Municipality"));
    out.add(new Subdivision("SM-04", "Faetano", null, "Municipality"));
    out.add(new Subdivision("SM-05", "Fiorentino", null, "Municipality"));
    out.add(new Subdivision("SM-06", "Borgo Maggiore", null, "Municipality"));
    out.add(new Subdivision("SM-07", "Città di San Marino", null, "Municipality"));
    out.add(new Subdivision("SM-08", "Montegiardino", null, "Municipality"));
    out.add(new Subdivision("SM-09", "Serravalle", null, "Municipality"));
    out.add(new Subdivision("SN-DB", "Diourbel", null, "Region"));
    out.add(new Subdivision("SN-DK", "Dakar", null, "Region"));
    out.add(new Subdivision("SN-FK", "Fatick", null, "Region"));
    out.add(new Subdivision("SN-KA", "Kaffrine", null, "Region"));
    out.add(new Subdivision("SN-KD", "Kolda", null, "Region"));
    out.add(new Subdivision("SN-KE", "Kédougou", null, "Region"));
    out.add(new Subdivision("SN-KL", "Kaolack", null, "Region"));
    out.add(new Subdivision("SN-LG", "Louga", null, "Region"));
    out.add(new Subdivision("SN-MT", "Matam", null, "Region"));
    out.add(new Subdivision("SN-SE", "Sédhiou", null, "Region"));
    out.add(new Subdivision("SN-SL", "Saint-Louis", null, "Region"));
    out.add(new Subdivision("SN-TC", "Tambacounda", null, "Region"));
    out.add(new Subdivision("SN-TH", "Thiès", null, "Region"));
    out.add(new Subdivision("SN-ZG", "Ziguinchor", null, "Region"));
    out.add(new Subdivision("SO-AW", "Awdal", null, "Region"));
    out.add(new Subdivision("SO-BK", "Bakool", null, "Region"));
    out.add(new Subdivision("SO-BN", "Banaadir", null, "Region"));
    out.add(new Subdivision("SO-BR", "Bari", null, "Region"));
    out.add(new Subdivision("SO-BY", "Bay", null, "Region"));
    out.add(new Subdivision("SO-GA", "Galguduud", null, "Region"));
    out.add(new Subdivision("SO-GE", "Gedo", null, "Region"));
    out.add(new Subdivision("SO-HI", "Hiiraan", null, "Region"));
    out.add(new Subdivision("SO-JD", "Jubbada Dhexe", null, "Region"));
    out.add(new Subdivision("SO-JH", "Jubbada Hoose", null, "Region"));
    out.add(new Subdivision("SO-MU", "Mudug", null, "Region"));
    out.add(new Subdivision("SO-NU", "Nugaal", null, "Region"));
    out.add(new Subdivision("SO-SA", "Sanaag", null, "Region"));
    out.add(new Subdivision("SO-SD", "Shabeellaha Dhexe", null, "Region"));
    out.add(new Subdivision("SO-SH", "Shabeellaha Hoose", null, "Region"));
    out.add(new Subdivision("SO-SO", "Sool", null, "Region"));
    out.add(new Subdivision("SO-TO", "Togdheer", null, "Region"));
    out.add(new Subdivision("SO-WO", "Woqooyi Galbeed", null, "Region"));
    out.add(new Subdivision("SR-BR", "Brokopondo", null, "District"));
    out.add(new Subdivision("SR-CM", "Commewijne", null, "District"));
    out.add(new Subdivision("SR-CR", "Coronie", null, "District"));
    out.add(new Subdivision("SR-MA", "Marowijne", null, "District"));
    out.add(new Subdivision("SR-NI", "Nickerie", null, "District"));
    out.add(new Subdivision("SR-PM", "Paramaribo", null, "District"));
    out.add(new Subdivision("SR-PR", "Para", null, "District"));
    out.add(new Subdivision("SR-SA", "Saramacca", null, "District"));
    out.add(new Subdivision("SR-SI", "Sipaliwini", null, "District"));
    out.add(new Subdivision("SR-WA", "Wanica", null, "District"));
    out.add(new Subdivision("SS-BN", "Northern Bahr el Ghazal", null, "State"));
    out.add(new Subdivision("SS-BW", "Western Bahr el Ghazal", null, "State"));
    out.add(new Subdivision("SS-EC", "Central Equatoria", null, "State"));
    out.add(new Subdivision("SS-EE", "Eastern Equatoria", null, "State"));
    out.add(new Subdivision("SS-EW", "Western Equatoria", null, "State"));
    out.add(new Subdivision("SS-JG", "Jonglei", null, "State"));
    out.add(new Subdivision("SS-LK", "Lakes", null, "State"));
    out.add(new Subdivision("SS-NU", "Upper Nile", null, "State"));
    out.add(new Subdivision("SS-UY", "Unity", null, "State"));
    out.add(new Subdivision("SS-WR", "Warrap", null, "State"));
    out.add(new Subdivision("ST-01", "Água Grande", null, "District"));
    out.add(new Subdivision("ST-02", "Cantagalo", null, "District"));
    out.add(new Subdivision("ST-03", "Caué", null, "District"));
    out.add(new Subdivision("ST-04", "Lembá", null, "District"));
    out.add(new Subdivision("ST-05", "Lobata", null, "District"));
    out.add(new Subdivision("ST-06", "Mé-Zóchi", null, "District"));
    out.add(new Subdivision("ST-P", "Príncipe", null, "Autonomous region"));
    out.add(new Subdivision("SV-AH", "Ahuachapán", null, "Department"));
    out.add(new Subdivision("SV-CA", "Cabañas", null, "Department"));
    out.add(new Subdivision("SV-CH", "Chalatenango", null, "Department"));
    out.add(new Subdivision("SV-CU", "Cuscatlán", null, "Department"));
    out.add(new Subdivision("SV-LI", "La Libertad", null, "Department"));
    out.add(new Subdivision("SV-MO", "Morazán", null, "Department"));
    out.add(new Subdivision("SV-PA", "La Paz", null, "Department"));
    out.add(new Subdivision("SV-SA", "Santa Ana", null, "Department"));
    out.add(new Subdivision("SV-SM", "San Miguel", null, "Department"));
    out.add(new Subdivision("SV-SO", "Sonsonate", null, "Department"));
    out.add(new Subdivision("SV-SS", "San Salvador", null, "Department"));
    out.add(new Subdivision("SV-SV", "San Vicente", null, "Department"));
    out.add(new Subdivision("SV-UN", "La Unión", null, "Department"));
    out.add(new Subdivision("SV-US", "Usulután", null, "Department"));
    out.add(new Subdivision("SY-DI", "Dimashq", null, "Province"));
    out.add(new Subdivision("SY-DR", "Dar'ā", null, "Province"));
    out.add(new Subdivision("SY-DY", "Dayr az Zawr", null, "Province"));
    out.add(new Subdivision("SY-HA", "Al Ḩasakah", null, "Province"));
    out.add(new Subdivision("SY-HI", "Ḩimş", null, "Province"));
    out.add(new Subdivision("SY-HL", "Ḩalab", null, "Province"));
    out.add(new Subdivision("SY-HM", "Ḩamāh", null, "Province"));
    out.add(new Subdivision("SY-ID", "Idlib", null, "Province"));
    out.add(new Subdivision("SY-LA", "Al Lādhiqīyah", null, "Province"));
    out.add(new Subdivision("SY-QU", "Al Qunayţirah", null, "Province"));
    out.add(new Subdivision("SY-RA", "Ar Raqqah", null, "Province"));
    out.add(new Subdivision("SY-RD", "Rīf Dimashq", null, "Province"));
    out.add(new Subdivision("SY-SU", "As Suwaydā'", null, "Province"));
    out.add(new Subdivision("SY-TA", "Ţarţūs", null, "Province"));
    out.add(new Subdivision("SZ-HH", "Hhohho", null, "Region"));
    out.add(new Subdivision("SZ-LU", "Lubombo", null, "Region"));
    out.add(new Subdivision("SZ-MA", "Manzini", null, "Region"));
    out.add(new Subdivision("SZ-SH", "Shiselweni", null, "Region"));
    out.add(new Subdivision("TD-BA", "Batha", null, "Province"));
    out.add(new Subdivision("TD-BG", "Bahr el Ghazal", null, "Province"));
    out.add(new Subdivision("TD-BO", "Borkou", null, "Province"));
    out.add(new Subdivision("TD-CB", "Chari-Baguirmi", null, "Province"));
    out.add(new Subdivision("TD-EE", "Ennedi-Est", null, "Province"));
    out.add(new Subdivision("TD-EO", "Ennedi-Ouest", null, "Province"));
    out.add(new Subdivision("TD-GR", "Guéra", null, "Province"));
    out.add(new Subdivision("TD-HL", "Hadjer Lamis", null, "Province"));
    out.add(new Subdivision("TD-KA", "Kanem", null, "Province"));
    out.add(new Subdivision("TD-LC", "Lac", null, "Province"));
    out.add(new Subdivision("TD-LO", "Logone-Occidental", null, "Province"));
    out.add(new Subdivision("TD-LR", "Logone-Oriental", null, "Province"));
    out.add(new Subdivision("TD-MA", "Mandoul", null, "Province"));
    out.add(new Subdivision("TD-MC", "Moyen-Chari", null, "Province"));
    out.add(new Subdivision("TD-ME", "Mayo-Kebbi-Est", null, "Province"));
    out.add(new Subdivision("TD-MO", "Mayo-Kebbi-Ouest", null, "Province"));
    out.add(new Subdivision("TD-ND", "Ville de Ndjamena", null, "Province"));
    out.add(new Subdivision("TD-OD", "Ouaddaï", null, "Province"));
    out.add(new Subdivision("TD-SA", "Salamat", null, "Province"));
    out.add(new Subdivision("TD-SI", "Sila", null, "Province"));
    out.add(new Subdivision("TD-TA", "Tandjilé", null, "Province"));
    out.add(new Subdivision("TD-TI", "Tibesti", null, "Province"));
    out.add(new Subdivision("TD-WF", "Wadi Fira", null, "Province"));
    out.add(new Subdivision("TG-C", "Centrale", null, "Region"));
    out.add(new Subdivision("TG-K", "Kara", null, "Region"));
    out.add(new Subdivision("TG-M", "Maritime (Région)", null, "Region"));
    out.add(new Subdivision("TG-P", "Plateaux", null, "Region"));
    out.add(new Subdivision("TG-S", "Savanes", null, "Region"));
    out.add(new Subdivision("TH-10", "Krung Thep Maha Nakhon", null, "Metropolitan administration"));
    out.add(new Subdivision("TH-11", "Samut Prakan", null, "Province"));
    out.add(new Subdivision("TH-12", "Nonthaburi", null, "Province"));
    out.add(new Subdivision("TH-13", "Pathum Thani", null, "Province"));
    out.add(new Subdivision("TH-14", "Phra Nakhon Si Ayutthaya", null, "Province"));
    out.add(new Subdivision("TH-15", "Ang Thong", null, "Province"));
    out.add(new Subdivision("TH-16", "Lop Buri", null, "Province"));
    out.add(new Subdivision("TH-17", "Sing Buri", null, "Province"));
    out.add(new Subdivision("TH-18", "Chai Nat", null, "Province"));
    out.add(new Subdivision("TH-19", "Saraburi", null, "Province"));
    out.add(new Subdivision("TH-20", "Chon Buri", null, "Province"));
    out.add(new Subdivision("TH-21", "Rayong", null, "Province"));
    out.add(new Subdivision("TH-22", "Chanthaburi", null, "Province"));
    out.add(new Subdivision("TH-23", "Trat", null, "Province"));
    out.add(new Subdivision("TH-24", "Chachoengsao", null, "Province"));
    out.add(new Subdivision("TH-25", "Prachin Buri", null, "Province"));
    out.add(new Subdivision("TH-26", "Nakhon Nayok", null, "Province"));
    out.add(new Subdivision("TH-27", "Sa Kaeo", null, "Province"));
    out.add(new Subdivision("TH-30", "Nakhon Ratchasima", null, "Province"));
    out.add(new Subdivision("TH-31", "Buri Ram", null, "Province"));
    out.add(new Subdivision("TH-32", "Surin", null, "Province"));
    out.add(new Subdivision("TH-33", "Si Sa Ket", null, "Province"));
    out.add(new Subdivision("TH-34", "Ubon Ratchathani", null, "Province"));
    out.add(new Subdivision("TH-35", "Yasothon", null, "Province"));
    out.add(new Subdivision("TH-36", "Chaiyaphum", null, "Province"));
    out.add(new Subdivision("TH-37", "Amnat Charoen", null, "Province"));
    out.add(new Subdivision("TH-38", "Bueng Kan", null, "Province"));
    out.add(new Subdivision("TH-39", "Nong Bua Lam Phu", null, "Province"));
    out.add(new Subdivision("TH-40", "Khon Kaen", null, "Province"));
    out.add(new Subdivision("TH-41", "Udon Thani", null, "Province"));
    out.add(new Subdivision("TH-42", "Loei", null, "Province"));
    out.add(new Subdivision("TH-43", "Nong Khai", null, "Province"));
    out.add(new Subdivision("TH-44", "Maha Sarakham", null, "Province"));
    out.add(new Subdivision("TH-45", "Roi Et", null, "Province"));
    out.add(new Subdivision("TH-46", "Kalasin", null, "Province"));
    out.add(new Subdivision("TH-47", "Sakon Nakhon", null, "Province"));
    out.add(new Subdivision("TH-48", "Nakhon Phanom", null, "Province"));
    out.add(new Subdivision("TH-49", "Mukdahan", null, "Province"));
    out.add(new Subdivision("TH-50", "Chiang Mai", null, "Province"));
    out.add(new Subdivision("TH-51", "Lamphun", null, "Province"));
    out.add(new Subdivision("TH-52", "Lampang", null, "Province"));
    out.add(new Subdivision("TH-53", "Uttaradit", null, "Province"));
    out.add(new Subdivision("TH-54", "Phrae", null, "Province"));
    out.add(new Subdivision("TH-55", "Nan", null, "Province"));
    out.add(new Subdivision("TH-56", "Phayao", null, "Province"));
    out.add(new Subdivision("TH-57", "Chiang Rai", null, "Province"));
    out.add(new Subdivision("TH-58", "Mae Hong Son", null, "Province"));
    out.add(new Subdivision("TH-60", "Nakhon Sawan", null, "Province"));
    out.add(new Subdivision("TH-61", "Uthai Thani", null, "Province"));
    out.add(new Subdivision("TH-62", "Kamphaeng Phet", null, "Province"));
    out.add(new Subdivision("TH-63", "Tak", null, "Province"));
    out.add(new Subdivision("TH-64", "Sukhothai", null, "Province"));
    out.add(new Subdivision("TH-65", "Phitsanulok", null, "Province"));
    out.add(new Subdivision("TH-66", "Phichit", null, "Province"));
    out.add(new Subdivision("TH-67", "Phetchabun", null, "Province"));
    out.add(new Subdivision("TH-70", "Ratchaburi", null, "Province"));
    out.add(new Subdivision("TH-71", "Kanchanaburi", null, "Province"));
    out.add(new Subdivision("TH-72", "Suphan Buri", null, "Province"));
    out.add(new Subdivision("TH-73", "Nakhon Pathom", null, "Province"));
    out.add(new Subdivision("TH-74", "Samut Sakhon", null, "Province"));
    out.add(new Subdivision("TH-75", "Samut Songkhram", null, "Province"));
    out.add(new Subdivision("TH-76", "Phetchaburi", null, "Province"));
    out.add(new Subdivision("TH-77", "Prachuap Khiri Khan", null, "Province"));
    out.add(new Subdivision("TH-80", "Nakhon Si Thammarat", null, "Province"));
    out.add(new Subdivision("TH-81", "Krabi", null, "Province"));
    out.add(new Subdivision("TH-82", "Phangnga", null, "Province"));
    out.add(new Subdivision("TH-83", "Phuket", null, "Province"));
    out.add(new Subdivision("TH-84", "Surat Thani", null, "Province"));
    out.add(new Subdivision("TH-85", "Ranong", null, "Province"));
    out.add(new Subdivision("TH-86", "Chumphon", null, "Province"));
    out.add(new Subdivision("TH-90", "Songkhla", null, "Province"));
    out.add(new Subdivision("TH-91", "Satun", null, "Province"));
    out.add(new Subdivision("TH-92", "Trang", null, "Province"));
    out.add(new Subdivision("TH-93", "Phatthalung", null, "Province"));
    out.add(new Subdivision("TH-94", "Pattani", null, "Province"));
    out.add(new Subdivision("TH-95", "Yala", null, "Province"));
    out.add(new Subdivision("TH-96", "Narathiwat", null, "Province"));
    out.add(new Subdivision("TH-S", "Phatthaya", null, "Special administrative city"));
    out.add(new Subdivision("TJ-DU", "Dushanbe", null, "Capital territory"));
    out.add(new Subdivision("TJ-GB", "Kŭhistoni Badakhshon", null, "Autonomous region"));
    out.add(new Subdivision("TJ-KT", "Khatlon", null, "Region"));
    out.add(new Subdivision("TJ-RA", "nohiyahoi tobei jumhurí", null, "Districts under republic administration"));
    out.add(new Subdivision("TJ-SU", "Sughd", null, "Region"));
    out.add(new Subdivision("TL-AL", "Aileu", null, "Municipality"));
    out.add(new Subdivision("TL-AN", "Ainaro", null, "Municipality"));
    out.add(new Subdivision("TL-BA", "Baucau", null, "Municipality"));
    out.add(new Subdivision("TL-BO", "Bobonaro", null, "Municipality"));
    out.add(new Subdivision("TL-CO", "Cova Lima", null, "Municipality"));
    out.add(new Subdivision("TL-DI", "Díli", null, "Municipality"));
    out.add(new Subdivision("TL-ER", "Ermera", null, "Municipality"));
    out.add(new Subdivision("TL-LA", "Lautém", null, "Municipality"));
    out.add(new Subdivision("TL-LI", "Liquiça", null, "Municipality"));
    out.add(new Subdivision("TL-MF", "Manufahi", null, "Municipality"));
    out.add(new Subdivision("TL-MT", "Manatuto", null, "Municipality"));
    out.add(new Subdivision("TL-OE", "Oé-Cusse Ambeno", null, "Special administrative region"));
    out.add(new Subdivision("TL-VI", "Viqueque", null, "Municipality"));
    out.add(new Subdivision("TM-A", "Ahal", null, "Region"));
    out.add(new Subdivision("TM-B", "Balkan", null, "Region"));
    out.add(new Subdivision("TM-D", "Daşoguz", null, "Region"));
    out.add(new Subdivision("TM-L", "Lebap", null, "Region"));
    out.add(new Subdivision("TM-M", "Mary", null, "Region"));
    out.add(new Subdivision("TM-S", "Aşgabat", null, "City"));
    out.add(new Subdivision("TN-11", "Tunis", null, "Governorate"));
    out.add(new Subdivision("TN-12", "L'Ariana", null, "Governorate"));
    out.add(new Subdivision("TN-13", "Ben Arous", null, "Governorate"));
    out.add(new Subdivision("TN-14", "La Manouba", null, "Governorate"));
    out.add(new Subdivision("TN-21", "Nabeul", null, "Governorate"));
    out.add(new Subdivision("TN-22", "Zaghouan", null, "Governorate"));
    out.add(new Subdivision("TN-23", "Bizerte", null, "Governorate"));
    out.add(new Subdivision("TN-31", "Béja", null, "Governorate"));
    out.add(new Subdivision("TN-32", "Jendouba", null, "Governorate"));
    out.add(new Subdivision("TN-33", "Le Kef", null, "Governorate"));
    out.add(new Subdivision("TN-34", "Siliana", null, "Governorate"));
    out.add(new Subdivision("TN-41", "Kairouan", null, "Governorate"));
    out.add(new Subdivision("TN-42", "Kasserine", null, "Governorate"));
    out.add(new Subdivision("TN-43", "Sidi Bouzid", null, "Governorate"));
    out.add(new Subdivision("TN-51", "Sousse", null, "Governorate"));
    out.add(new Subdivision("TN-52", "Monastir", null, "Governorate"));
    out.add(new Subdivision("TN-53", "Mahdia", null, "Governorate"));
    out.add(new Subdivision("TN-61", "Sfax", null, "Governorate"));
    out.add(new Subdivision("TN-71", "Gafsa", null, "Governorate"));
    out.add(new Subdivision("TN-72", "Tozeur", null, "Governorate"));
    out.add(new Subdivision("TN-73", "Kébili", null, "Governorate"));
    out.add(new Subdivision("TN-81", "Gabès", null, "Governorate"));
    out.add(new Subdivision("TN-82", "Médenine", null, "Governorate"));
    out.add(new Subdivision("TN-83", "Tataouine", null, "Governorate"));
    out.add(new Subdivision("TO-01", "'Eua", null, "Division"));
    out.add(new Subdivision("TO-02", "Ha'apai", null, "Division"));
    out.add(new Subdivision("TO-03", "Niuas", null, "Division"));
    out.add(new Subdivision("TO-04", "Tongatapu", null, "Division"));
    out.add(new Subdivision("TO-05", "Vava'u", null, "Division"));
    out.add(new Subdivision("TR-01", "Adana", null, "Province"));
    out.add(new Subdivision("TR-02", "Adıyaman", null, "Province"));
    out.add(new Subdivision("TR-03", "Afyonkarahisar", null, "Province"));
    out.add(new Subdivision("TR-04", "Ağrı", null, "Province"));
    out.add(new Subdivision("TR-05", "Amasya", null, "Province"));
    out.add(new Subdivision("TR-06", "Ankara", null, "Province"));
    out.add(new Subdivision("TR-07", "Antalya", null, "Province"));
    out.add(new Subdivision("TR-08", "Artvin", null, "Province"));
    out.add(new Subdivision("TR-09", "Aydın", null, "Province"));
    out.add(new Subdivision("TR-10", "Balıkesir", null, "Province"));
    out.add(new Subdivision("TR-11", "Bilecik", null, "Province"));
    out.add(new Subdivision("TR-12", "Bingöl", null, "Province"));
    out.add(new Subdivision("TR-13", "Bitlis", null, "Province"));
    out.add(new Subdivision("TR-14", "Bolu", null, "Province"));
    out.add(new Subdivision("TR-15", "Burdur", null, "Province"));
    out.add(new Subdivision("TR-16", "Bursa", null, "Province"));
    out.add(new Subdivision("TR-17", "Çanakkale", null, "Province"));
    out.add(new Subdivision("TR-18", "Çankırı", null, "Province"));
    out.add(new Subdivision("TR-19", "Çorum", null, "Province"));
    out.add(new Subdivision("TR-20", "Denizli", null, "Province"));
    out.add(new Subdivision("TR-21", "Diyarbakır", null, "Province"));
    out.add(new Subdivision("TR-22", "Edirne", null, "Province"));
    out.add(new Subdivision("TR-23", "Elazığ", null, "Province"));
    out.add(new Subdivision("TR-24", "Erzincan", null, "Province"));
    out.add(new Subdivision("TR-25", "Erzurum", null, "Province"));
    out.add(new Subdivision("TR-26", "Eskişehir", null, "Province"));
    out.add(new Subdivision("TR-27", "Gaziantep", null, "Province"));
    out.add(new Subdivision("TR-28", "Giresun", null, "Province"));
    out.add(new Subdivision("TR-29", "Gümüşhane", null, "Province"));
    out.add(new Subdivision("TR-30", "Hakkâri", null, "Province"));
    out.add(new Subdivision("TR-31", "Hatay", null, "Province"));
    out.add(new Subdivision("TR-32", "Isparta", null, "Province"));
    out.add(new Subdivision("TR-33", "Mersin", null, "Province"));
    out.add(new Subdivision("TR-34", "İstanbul", null, "Province"));
    out.add(new Subdivision("TR-35", "İzmir", null, "Province"));
    out.add(new Subdivision("TR-36", "Kars", null, "Province"));
    out.add(new Subdivision("TR-37", "Kastamonu", null, "Province"));
    out.add(new Subdivision("TR-38", "Kayseri", null, "Province"));
    out.add(new Subdivision("TR-39", "Kırklareli", null, "Province"));
    out.add(new Subdivision("TR-40", "Kırşehir", null, "Province"));
    out.add(new Subdivision("TR-41", "Kocaeli", null, "Province"));
  }
}
