// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from Debian iso-codes 4.20.1. Do not edit.
package com.wwwdottheinternetdotcom.isocodes.iso3166;

import java.util.List;

/**
 * Entries 0 to 499 of {@link Subdivision}.
 */
final class SubdivisionData0 {
  private SubdivisionData0() {
  }

  static void addTo(List<Subdivision> out) {
    out.add(new Subdivision("AD-02", "Canillo", null, "Parish"));
    out.add(new Subdivision("AD-03", "Encamp", null, "Parish"));
    out.add(new Subdivision("AD-04", "La Massana", null, "Parish"));
    out.add(new Subdivision("AD-05", "Ordino", null, "Parish"));
    out.add(new Subdivision("AD-06", "Sant Julià de Lòria", null, "Parish"));
    out.add(new Subdivision("AD-07", "Andorra la Vella", null, "Parish"));
    out.add(new Subdivision("AD-08", "Escaldes-Engordany", null, "Parish"));
    out.add(new Subdivision("AE-AJ", "‘Ajmān", null, "Emirate"));
    out.add(new Subdivision("AE-AZ", "Abū Z̧aby", null, "Emirate"));
    out.add(new Subdivision("AE-DU", "Dubayy", null, "Emirate"));
    out.add(new Subdivision("AE-FU", "Al Fujayrah", null, "Emirate"));
    out.add(new Subdivision("AE-RK", "Ra’s al Khaymah", null, "Emirate"));
    out.add(new Subdivision("AE-SH", "Ash Shāriqah", null, "Emirate"));
    out.add(new Subdivision("AE-UQ", "Umm al Qaywayn", null, "Emirate"));
    out.add(new Subdivision("AF-BAL", "Balkh", null, "Province"));
    out.add(new Subdivision("AF-BAM", "Bāmyān", null, "Province"));
    out.add(new Subdivision("AF-BDG", "Bādghīs", null, "Province"));
    out.add(new Subdivision("AF-BDS", "Badakhshān", null, "Province"));
    out.add(new Subdivision("AF-BGL", "Baghlān", null, "Province"));
    out.add(new Subdivision("AF-DAY", "Dāykundī", null, "Province"));
    out.add(new Subdivision("AF-FRA", "Farāh", null, "Province"));
    out.add(new Subdivision("AF-FYB", "Fāryāb", null, "Province"));
    out.add(new Subdivision("AF-GHA", "Ghaznī", null, "Province"));
    out.add(new Subdivision("AF-GHO", "Ghōr", null, "Province"));
    out.add(new Subdivision("AF-HEL", "Helmand", null, "Province"));
    out.add(new Subdivision("AF-HER", "Herāt", null, "Province"));
    out.add(new Subdivision("AF-JOW", "Jowzjān", null, "Province"));
    out.add(new Subdivision("AF-KAB", "Kābul", null, "Province"));
    out.add(new Subdivision("AF-KAN", "Kandahār", null, "Province"));
    out.add(new Subdivision("AF-KAP", "Kāpīsā", null, "Province"));
    out.add(new Subdivision("AF-KDZ", "Kunduz", null, "Province"));
    out.add(new Subdivision("AF-KHO", "Khōst", null, "Province"));
    out.add(new Subdivision("AF-KNR", "Kunaṟ", null, "Province"));
    out.add(new Subdivision("AF-LAG", "Laghmān", null, "Province"));
    out.add(new Subdivision("AF-LOG", "Lōgar", null, "Province"));
    out.add(new Subdivision("AF-NAN", "Nangarhār", null, "Province"));
    out.add(new Subdivision("AF-NIM", "Nīmrōz", null, "Province"));
    out.add(new Subdivision("AF-NUR", "Nūristān", null, "Province"));
    out.add(new Subdivision("AF-PAN", "Panjshayr", null, "Province"));
    out.add(new Subdivision("AF-PAR", "Parwān", null, "Province"));
    out.add(new Subdivision("AF-PIA", "Paktiyā", null, "Province"));
    out.add(new Subdivision("AF-PKA", "Paktīkā", null, "Province"));
    out.add(new Subdivision("AF-SAM", "Samangān", null, "Province"));
    out.add(new Subdivision("AF-SAR", "Sar-e Pul", null, "Province"));
    out.add(new Subdivision("AF-TAK", "Takhār", null, "Province"));
    out.add(new Subdivision("AF-URU", "Uruzgān", null, "Province"));
    out.add(new Subdivision("AF-WAR", "Wardak", null, "Province"));
    out.add(new Subdivision("AF-ZAB", "Zābul", null, "Province"));
    out.add(new Subdivision("AG-03", "Saint George", null, "Parish"));
    out.add(new Subdivision("AG-04", "Saint John", null, "Parish"));
    out.add(new Subdivision("AG-05", "Saint Mary", null, "Parish"));
    out.add(new Subdivision("AG-06", "Saint Paul", null, "Parish"));
    out.add(new Subdivision("AG-07", "Saint Peter", null, "Parish"));
    out.add(new Subdivision("AG-08", "Saint Philip", null, "Parish"));
    out.add(new Subdivision("AG-10", "Barbuda", null, "Dependency"));
    out.add(new Subdivision("AG-11", "Redonda", null, "Dependency"));
    out.add(new Subdivision("AL-01", "Berat", null, "County"));
    out.add(new Subdivision("AL-02", "Durrës", null, "County"));
    out.add(new Subdivision("AL-03", "Elbasan", null, "County"));
    out.add(new Subdivision("AL-04", "Fier", null, "County"));
    out.add(new Subdivision("AL-05", "Gjirokastër", null, "County"));
    out.add(new Subdivision("AL-06", "Korçë", null, "County"));
    out.add(new Subdivision("AL-07", "Kukës", null, "County"));
    out.add(new Subdivision("AL-08", "Lezhë", null, "County"));
    out.add(new Subdivision("AL-09", "Dibër", null, "County"));
    out.add(new Subdivision("AL-10", "Shkodër", null, "County"));
    out.add(new Subdivision("AL-11", "Tiranë", null, "County"));
    out.add(new Subdivision("AL-12", "Vlorë", null, "County"));
    out.add(new Subdivision("AM-AG", "Aragac̣otn", null, "Region"));
    out.add(new Subdivision("AM-AR", "Ararat", null, "Region"));
    out.add(new Subdivision("AM-AV", "Armavir", null, "Region"));
    out.add(new Subdivision("AM-ER", "Erevan", null, "City"));
    out.add(new Subdivision("AM-GR", "Geġark'unik'", null, "Region"));
    out.add(new Subdivision("AM-KT", "Kotayk'", null, "Region"));
    out.add(new Subdivision("AM-LO", "Loṙi", null, "Region"));
    out.add(new Subdivision("AM-SH", "Širak", null, "Region"));
    out.add(new Subdivision("AM-SU", "Syunik'", null, "Region"));
    out.add(new Subdivision("AM-TV", "Tavuš", null, "Region"));
    out.add(new Subdivision("AM-VD", "Vayoć Jor", null, "Region"));
    out.add(new Subdivision("AO-BGO", "Bengo", null, "Province"));
    out.add(new Subdivision("AO-BGU", "Benguela", null, "Province"));
    out.add(new Subdivision("AO-BIE", "Bié", null, "Province"));
    out.add(new Subdivision("AO-CAB", "Cabinda", null, "Province"));
    out.add(new Subdivision("AO-CCU", "Cuando Cubango", null, "Province"));
    out.add(new Subdivision("AO-CNN", "Cunene", null, "Province"));
    out.add(new Subdivision("AO-CNO", "Cuanza-Norte", null, "Province"));
    out.add(new Subdivision("AO-CUS", "Cuanza-Sul", null, "Province"));
    out.add(new Subdivision("AO-HUA", "Huambo", null, "Province"));
    out.add(new Subdivision("AO-HUI", "Huíla", null, "Province"));
    out.add(new Subdivision("AO-LNO", "Lunda-Norte", null, "Province"));
    out.add(new Subdivision("AO-LSU", "Lunda-Sul", null, "Province"));
    out.add(new Subdivision("AO-LUA", "Luanda", null, "Province"));
    out.add(new Subdivision("AO-MAL", "Malange", null, "Province"));
    out.add(new Subdivision("AO-MOX", "Moxico", null, "Province"));
    out.add(new Subdivision("AO-NAM", "Namibe", null, "Province"));
    out.add(new Subdivision("AO-UIG", "Uíge", null, "Province"));
    out.add(new Subdivision("AO-ZAI", "Zaire", null, "Province"));
    out.add(new Subdivision("AR-A", "Salta", null, "Province"));
    out.add(new Subdivision("AR-B", "Buenos Aires", null, "Province"));
    out.add(new Subdivision("AR-C", "Ciudad Autónoma de Buenos Aires", null, "City"));
    out.add(new Subdivision("AR-D", "San Luis", null, "Province"));
    out.add(new Subdivision("AR-E", "Entre Ríos", null, "Province"));
    out.add(new Subdivision("AR-F", "La Rioja", null, "Province"));
    out.add(new Subdivision("AR-G", "Santiago del Estero", null, "Province"));
    out.add(new Subdivision("AR-H", "Chaco", null, "Province"));
    out.add(new Subdivision("AR-J", "San Juan", null, "Province"));
    out.add(new Subdivision("AR-K", "Catamarca", null, "Province"));
    out.add(new Subdivision("AR-L", "La Pampa", null, "Province"));
    out.add(new Subdivision("AR-M", "Mendoza", null, "Province"));
    out.add(new Subdivision("AR-N", "Misiones", null, "Province"));
    out.add(new Subdivision("AR-P", "Formosa", null, "Province"));
    out.add(new Subdivision("AR-Q", "Neuquén", null, "Province"));
    out.add(new Subdivision("AR-R", "Río Negro", null, "Province"));
    out.add(new Subdivision("AR-S", "Santa Fe", null, "Province"));
    out.add(new Subdivision("AR-T", "Tucumán", null, "Province"));
    out.add(new Subdivision("AR-U", "Chubut", null, "Province"));
    out.add(new Subdivision("AR-V", "Tierra del Fuego", null, "Province"));
    out.add(new Subdivision("AR-W", "Corrientes", null, "Province"));
    out.add(new Subdivision("AR-X", "Córdoba", null, "Province"));
    out.add(new Subdivision("AR-Y", "Jujuy", null, "Province"));
    out.add(new Subdivision("AR-Z", "Santa Cruz", null, "Province"));
    out.add(new Subdivision("AT-1", "Burgenland", null, "State"));
    out.add(new Subdivision("AT-2", "Kärnten", null, "State"));
    out.add(new Subdivision("AT-3", "Niederösterreich", null, "State"));
    out.add(new Subdivision("AT-4", "Oberösterreich", null, "State"));
    out.add(new Subdivision("AT-5", "Salzburg", null, "State"));
    out.add(new Subdivision("AT-6", "Steiermark", null, "State"));
    out.add(new Subdivision("AT-7", "Tirol", null, "State"));
    out.add(new Subdivision("AT-8", "Vorarlberg", null, "State"));
    out.add(new Subdivision("AT-9", "Wien", null, "State"));
    out.add(new Subdivision("AU-ACT", "Australian Capital Territory", null, "Territory"));
    out.add(new Subdivision("AU-NSW", "New South Wales", null, "State"));
    out.add(new Subdivision("AU-NT", "Northern Territory", null, "Territory"));
    out.add(new Subdivision("AU-QLD", "Queensland", null, "State"));
    out.add(new Subdivision("AU-SA", "South Australia", null, "State"));
    out.add(new Subdivision("AU-TAS", "Tasmania", null, "State"));
    out.add(new Subdivision("AU-VIC", "Victoria", null, "State"));
    out.add(new Subdivision("AU-WA", "Western Australia", null, "State"));
    out.add(new Subdivision("AZ-ABS", "Abşeron", null, "Rayon"));
    out.add(new Subdivision("AZ-AGA", "Ağstafa", null, "Rayon"));
    out.add(new Subdivision("AZ-AGC", "Ağcabədi", null, "Rayon"));
    out.add(new Subdivision("AZ-AGM", "Ağdam", null, "Rayon"));
    out.add(new Subdivision("AZ-AGS", "Ağdaş", null, "Rayon"));
    out.add(new Subdivision("AZ-AGU", "Ağsu", null, "Rayon"));
    out.add(new Subdivision("AZ-AST", "Astara", null, "Rayon"));
    out.add(new Subdivision("AZ-BA", "Bakı", null, "Municipality"));
    out.add(new Subdivision("AZ-BAB", "Babək", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-BAL", "Balakən", null, "Rayon"));
    out.add(new Subdivision("AZ-BAR", "Bərdə", null, "Rayon"));
    out.add(new Subdivision("AZ-BEY", "Beyləqan", null, "Rayon"));
    out.add(new Subdivision("AZ-BIL", "Biləsuvar", null, "Rayon"));
    out.add(new Subdivision("AZ-CAB", "Cəbrayıl", null, "Rayon"));
    out.add(new Subdivision("AZ-CAL", "Cəlilabad", null, "Rayon"));
    out.add(new Subdivision("AZ-CUL", "Culfa", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-DAS", "Daşkəsən", null, "Rayon"));
    out.add(new Subdivision("AZ-FUZ", "Füzuli", null, "Rayon"));
    out.add(new Subdivision("AZ-GA", "Gəncə", null, "Municipality"));
    out.add(new Subdivision("AZ-GAD", "Gədəbəy", null, "Rayon"));
    out.add(new Subdivision("AZ-GOR", "Goranboy", null, "Rayon"));
    out.add(new Subdivision("AZ-GOY", "Göyçay", null, "Rayon"));
    out.add(new Subdivision("AZ-GYG", "Göygöl", null, "Rayon"));
    out.add(new Subdivision("AZ-HAC", "Hacıqabul", null, "Rayon"));
    out.add(new Subdivision("AZ-IMI", "İmişli", null, "Rayon"));
    out.add(new Subdivision("AZ-ISM", "İsmayıllı", null, "Rayon"));
    out.add(new Subdivision("AZ-KAL", "Kəlbəcər", null, "Rayon"));
    out.add(new Subdivision("AZ-KAN", "Kǝngǝrli", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-KUR", "Kürdəmir", null, "Rayon"));
    out.add(new Subdivision("AZ-LA", "Lənkəran", null, "Municipality"));
    out.add(new Subdivision("AZ-LAC", "Laçın", null, "Rayon"));
    out.add(new Subdivision("AZ-LAN", "Lənkəran", null, "Rayon"));
    out.add(new Subdivision("AZ-LER", "Lerik", null, "Rayon"));
    out.add(new Subdivision("AZ-MAS", "Masallı", null, "Rayon"));
    out.add(new Subdivision("AZ-MI", "Mingəçevir", null, "Municipality"));
    out.add(new Subdivision("AZ-NA", "Naftalan", null, "Municipality"));
    out.add(new Subdivision("AZ-NEF", "Neftçala", null, "Rayon"));
    out.add(new Subdivision("AZ-NV", "Naxçıvan", "AZ-NX", "Municipality"));
    out.add(new Subdivision("AZ-NX", "Naxçıvan", null, "Autonomous republic"));
    out.add(new Subdivision("AZ-OGU", "Oğuz", null, "Rayon"));
    out.add(new Subdivision("AZ-ORD", "Ordubad", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-QAB", "Qəbələ", null, "Rayon"));
    out.add(new Subdivision("AZ-QAX", "Qax", null, "Rayon"));
    out.add(new Subdivision("AZ-QAZ", "Qazax", null, "Rayon"));
    out.add(new Subdivision("AZ-QBA", "Quba", null, "Rayon"));
    out.add(new Subdivision("AZ-QBI", "Qubadlı", null, "Rayon"));
    out.add(new Subdivision("AZ-QOB", "Qobustan", null, "Rayon"));
    out.add(new Subdivision("AZ-QUS", "Qusar", null, "Rayon"));
    out.add(new Subdivision("AZ-SA", "Şəki", null, "Municipality"));
    out.add(new Subdivision("AZ-SAB", "Sabirabad", null, "Rayon"));
    out.add(new Subdivision("AZ-SAD", "Sədərək", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-SAH", "Şahbuz", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-SAK", "Şəki", null, "Rayon"));
    out.add(new Subdivision("AZ-SAL", "Salyan", null, "Rayon"));
    out.add(new Subdivision("AZ-SAR", "Şərur", "AZ-NX", "Rayon"));
    out.add(new Subdivision("AZ-SAT", "Saatlı", null, "Rayon"));
    out.add(new Subdivision("AZ-SBN", "Şabran", null, "Rayon"));
    out.add(new Subdivision("AZ-SIY", "Siyəzən", null, "Rayon"));
    out.add(new Subdivision("AZ-SKR", "Şəmkir", null, "Rayon"));
    out.add(new Subdivision("AZ-SM", "Sumqayıt", null, "Municipality"));
    out.add(new Subdivision("AZ-SMI", "Şamaxı", null, "Rayon"));
    out.add(new Subdivision("AZ-SMX", "Samux", null, "Rayon"));
    out.add(new Subdivision("AZ-SR", "Şirvan", null, "Municipality"));
    out.add(new Subdivision("AZ-SUS", "Şuşa", null, "Rayon"));
    out.add(new Subdivision("AZ-TAR", "Tərtər", null, "Rayon"));
    out.add(new Subdivision("AZ-TOV", "Tovuz", null, "Rayon"));
    out.add(new Subdivision("AZ-UCA", "Ucar", null, "Rayon"));
    out.add(new Subdivision("AZ-XA", "Xankəndi", null, "Municipality"));
    out.add(new Subdivision("AZ-XAC", "Xaçmaz", null, "Rayon"));
    out.add(new Subdivision("AZ-XCI", "Xocalı", null, "Rayon"));
    out.add(new Subdivision("AZ-XIZ", "Xızı", null, "Rayon"));
    out.add(new Subdivision("AZ-XVD", "Xocavənd", null, "Rayon"));
    out.add(new Subdivision("AZ-YAR", "Yardımlı", null, "Rayon"));
    out.add(new Subdivision("AZ-YE", "Yevlax", null, "Municipality"));
    out.add(new Subdivision("AZ-YEV", "Yevlax", null, "Rayon"));
    out.add(new Subdivision("AZ-ZAN", "Zəngilan", null, "Rayon"));
    out.add(new Subdivision("AZ-ZAQ", "Zaqatala", null, "Rayon"));
    out.add(new Subdivision("AZ-ZAR", "Zərdab", null, "Rayon"));
    out.add(new Subdivision("BA-BIH", "Federacija Bosne i Hercegovine", null, "Entity"));
    out.add(new Subdivision("BA-BRC", "Brčko distrikt", null, "District with special status"));
    out.add(new Subdivision("BA-SRP", "Republika Srpska", null, "Entity"));
    out.add(new Subdivision("BB-01", "Christ Church", null, "Parish"));
    out.add(new Subdivision("BB-02", "Saint Andrew", null, "Parish"));
    out.add(new Subdivision("BB-03", "Saint George", null, "Parish"));
    out.add(new Subdivision("BB-04", "Saint James", null, "Parish"));
    out.add(new Subdivision("BB-05", "Saint John", null, "Parish"));
    out.add(new Subdivision("BB-06", "Saint Joseph", null, "Parish"));
    out.add(new Subdivision("BB-07", "Saint Lucy", null, "Parish"));
    out.add(new Subdivision("BB-08", "Saint Michael", null, "Parish"));
    out.add(new Subdivision("BB-09", "Saint Peter", null, "Parish"));
    out.add(new Subdivision("BB-10", "Saint Philip", null, "Parish"));
    out.add(new Subdivision("BB-11", "Saint Thomas", null, "Parish"));
    out.add(new Subdivision("BD-01", "Bandarban", "BD-B", "District"));
    out.add(new Subdivision("BD-02", "Barguna", "BD-A", "District"));
    out.add(new Subdivision("BD-03", "Bogura", "BD-E", "District"));
    out.add(new Subdivision("BD-04", "Brahmanbaria", "BD-B", "District"));
    out.add(new Subdivision("BD-05", "Bagerhat", "BD-D", "District"));
    out.add(new Subdivision("BD-06", "Barishal", "BD-A", "District"));
    out.add(new Subdivision("BD-07", "Bhola", "BD-A", "District"));
    out.add(new Subdivision("BD-08", "Cumilla", "BD-B", "District"));
    out.add(new Subdivision("BD-09", "Chandpur", "BD-B", "District"));
    out.add(new Subdivision("BD-10", "Chattogram", "BD-B", "District"));
    out.add(new Subdivision("BD-11", "Cox's Bazar", "BD-B", "District"));
    out.add(new Subdivision("BD-12", "Chuadanga", "BD-D", "District"));
    out.add(new Subdivision("BD-13", "Dhaka", "BD-C", "District"));
    out.add(new Subdivision("BD-14", "Dinajpur", "BD-F", "District"));
    out.add(new Subdivision("BD-15", "Faridpur", "BD-C", "District"));
    out.add(new Subdivision("BD-16", "Feni", "BD-B", "District"));
    out.add(new Subdivision("BD-17", "Gopalganj", "BD-C", "District"));
    out.add(new Subdivision("BD-18", "Gazipur", "BD-C", "District"));
    out.add(new Subdivision("BD-19", "Gaibandha", "BD-F", "District"));
    out.add(new Subdivision("BD-20", "Habiganj", "BD-G", "District"));
    out.add(new Subdivision("BD-21", "Jamalpur", "BD-H", "District"));
    out.add(new Subdivision("BD-22", "Jashore", "BD-D", "District"));
    out.add(new Subdivision("BD-23", "Jhenaidah", "BD-D", "District"));
    out.add(new Subdivision("BD-24", "Joypurhat", "BD-E", "District"));
    out.add(new Subdivision("BD-25", "Jhalakathi", "BD-A", "District"));
    out.add(new Subdivision("BD-26", "Kishoreganj", "BD-C", "District"));
    out.add(new Subdivision("BD-27", "Khulna", "BD-D", "District"));
    out.add(new Subdivision("BD-28", "Kurigram", "BD-F", "District"));
    out.add(new Subdivision("BD-29", "Khagrachhari", "BD-B", "District"));
    out.add(new Subdivision("BD-30", "Kushtia", "BD-D", "District"));
    out.add(new Subdivision("BD-31", "Lakshmipur", "BD-B", "District"));
    out.add(new Subdivision("BD-32", "Lalmonirhat", "BD-F", "District"));
    out.add(new Subdivision("BD-33", "Manikganj", "BD-C", "District"));
    out.add(new Subdivision("BD-34", "Mymensingh", "BD-H", "District"));
    out.add(new Subdivision("BD-35", "Munshiganj", "BD-C", "District"));
    out.add(new Subdivision("BD-36", "Madaripur", "BD-C", "District"));
    out.add(new Subdivision("BD-37", "Magura", "BD-D", "District"));
    out.add(new Subdivision("BD-38", "Moulvibazar", "BD-G", "District"));
    out.add(new Subdivision("BD-39", "Meherpur", "BD-D", "District"));
    out.add(new Subdivision("BD-40", "Narayanganj", "BD-C", "District"));
    out.add(new Subdivision("BD-41", "Netrakona", "BD-H", "District"));
    out.add(new Subdivision("BD-42", "Narsingdi", "BD-C", "District"));
    out.add(new Subdivision("BD-43", "Narail", "BD-D", "District"));
    out.add(new Subdivision("BD-44", "Natore", "BD-E", "District"));
    out.add(new Subdivision("BD-45", "Chapai Nawabganj", "BD-E", "District"));
    out.add(new Subdivision("BD-46", "Nilphamari", "BD-F", "District"));
    out.add(new Subdivision("BD-47", "Noakhali", "BD-B", "District"));
    out.add(new Subdivision("BD-48", "Naogaon", "BD-E", "District"));
    out.add(new Subdivision("BD-49", "Pabna", "BD-E", "District"));
    out.add(new Subdivision("BD-50", "Pirojpur", "BD-A", "District"));
    out.add(new Subdivision("BD-51", "Patuakhali", "BD-A", "District"));
    out.add(new Subdivision("BD-52", "Panchagarh", "BD-F", "District"));
    out.add(new Subdivision("BD-53", "Rajbari", "BD-C", "District"));
    out.add(new Subdivision("BD-54", "Rajshahi", "BD-E", "District"));
    out.add(new Subdivision("BD-55", "Rangpur", "BD-F", "District"));
    out.add(new Subdivision("BD-56", "Rangamati", "BD-B", "District"));
    out.add(new Subdivision("BD-57", "Sherpur", "BD-H", "District"));
    out.add(new Subdivision("BD-58", "Satkhira", "BD-D", "District"));
    out.add(new Subdivision("BD-59", "Sirajganj", "BD-E", "District"));
    out.add(new Subdivision("BD-60", "Sylhet", "BD-G", "District"));
    out.add(new Subdivision("BD-61", "Sunamganj", "BD-G", "District"));
    out.add(new Subdivision("BD-62", "Shariatpur", "BD-C", "District"));
    out.add(new Subdivision("BD-63", "Tangail", "BD-C", "District"));
    out.add(new Subdivision("BD-64", "Thakurgaon", "BD-F", "District"));
    out.add(new Subdivision("BD-A", "Barishal", null, "Division"));
    out.add(new Subdivision("BD-B", "Chattogram", null, "Division"));
    out.add(new Subdivision("BD-C", "Dhaka", null, "Division"));
    out.add(new Subdivision("BD-D", "Khulna", null, "Division"));
    out.add(new Subdivision("BD-E", "Rajshahi", null, "Division"));
    out.add(new Subdivision("BD-F", "Rangpur", null, "Division"));
    out.add(new Subdivision("BD-G", "Sylhet", null, "Division"));
    out.add(new Subdivision("BD-H", "Mymensingh", null, "Division"));
    out.add(new Subdivision("BE-BRU", "Bruxelles-Capitale, Région de", null, "Region"));
    out.add(new Subdivision("BE-VAN", "Antwerpen", "BE-VLG", "Province"));
    out.add(new Subdivision("BE-VBR", "Vlaams-Brabant", "BE-VLG", "Province"));
    out.add(new Subdivision("BE-VLG", "Vlaams Gewest", null, "Region"));
    out.add(new Subdivision("BE-VLI", "Limburg", "BE-VLG", "Province"));
    out.add(new Subdivision("BE-VOV", "Oost-Vlaanderen", "BE-VLG", "Province"));
    out.add(new Subdivision("BE-VWV", "West-Vlaanderen", "BE-VLG", "Province"));
    out.add(new Subdivision("BE-WAL", "wallonne, Région", null, "Region"));
    out.add(new Subdivision("BE-WBR", "Brabant wallon", "BE-WAL", "Province"));
    out.add(new Subdivision("BE-WHT", "Hainaut", "BE-WAL", "Province"));
    out.add(new Subdivision("BE-WLG", "Liège", "BE-WAL", "Province"));
    out.add(new Subdivision("BE-WLX", "Luxembourg", "BE-WAL", "Province"));
    out.add(new Subdivision("BE-WNA", "Namur", "BE-WAL", "Province"));
    out.add(new Subdivision("BF-01", "Boucle du Mouhoun", null, "Region"));
    out.add(new Subdivision("BF-02", "Cascades", null, "Region"));
    out.add(new Subdivision("BF-03", "Centre", null, "Region"));
    out.add(new Subdivision("BF-04", "Centre-Est", null, "Region"));
    out.add(new Subdivision("BF-05", "Centre-Nord", null, "Region"));
    out.add(new Subdivision("BF-06", "Centre-Ouest", null, "Region"));
    out.add(new Subdivision("BF-07", "Centre-Sud", null, "Region"));
    out.add(new Subdivision("BF-08", "Est", null, "Region"));
    out.add(new Subdivision("BF-09", "Hauts-Bassins", null, "Region"));
    out.add(new Subdivision("BF-10", "Nord", null, "Region"));
    out.add(new Subdivision("BF-11", "Plateau-Central", null, "Region"));
    out.add(new Subdivision("BF-12", "Sahel", null, "Region"));
    out.add(new Subdivision("BF-13", "Sud-Ouest", null, "Region"));
    out.add(new Subdivision("BF-BAL", "Balé", "BF-01", "Province"));
    out.add(new Subdivision("BF-BAM", "Bam", "BF-05", "Province"));
    out.add(new Subdivision("BF-BAN", "Banwa", "BF-01", "Province"));
    out.add(new Subdivision("BF-BAZ", "Bazèga", "BF-07", "Province"));
    out.add(new Subdivision("BF-BGR", "Bougouriba", "BF-13", "Province"));
    out.add(new Subdivision("BF-BLG", "Boulgou", "BF-04", "Province"));
    out.add(new Subdivision("BF-BLK", "Boulkiemdé", "BF-06", "Province"));
    out.add(new Subdivision("BF-COM", "Comoé", "BF-02", "Province"));
    out.add(new Subdivision("BF-GAN", "Ganzourgou", "BF-11", "Province"));
    out.add(new Subdivision("BF-GNA", "Gnagna", "BF-08", "Province"));
    out.add(new Subdivision("BF-GOU", "Gourma", "BF-08", "Province"));
    out.add(new Subdivision("BF-HOU", "Houet", "BF-09", "Province"));
    out.add(new Subdivision("BF-IOB", "Ioba", "BF-13", "Province"));
    out.add(new Subdivision("BF-KAD", "Kadiogo", "BF-03", "Province"));
    out.add(new Subdivision("BF-KEN", "Kénédougou", "BF-09", "Province"));
    out.add(new Subdivision("BF-KMD", "Komondjari", "BF-08", "Province"));
    out.add(new Subdivision("BF-KMP", "Kompienga", "BF-08", "Province"));
    out.add(new Subdivision("BF-KOP", "Koulpélogo", "BF-04", "Province"));
    out.add(new Subdivision("BF-KOS", "Kossi", "BF-01", "Province"));
    out.add(new Subdivision("BF-KOT", "Kouritenga", "BF-04", "Province"));
    out.add(new Subdivision("BF-KOW", "Kourwéogo", "BF-11", "Province"));
    out.add(new Subdivision("BF-LER", "Léraba", "BF-02", "Province"));
    out.add(new Subdivision("BF-LOR", "Loroum", "BF-10", "Province"));
    out.add(new Subdivision("BF-MOU", "Mouhoun", "BF-01", "Province"));
    out.add(new Subdivision("BF-NAM", "Namentenga", "BF-05", "Province"));
    out.add(new Subdivision("BF-NAO", "Nahouri", "BF-07", "Province"));
    out.add(new Subdivision("BF-NAY", "Nayala", "BF-01", "Province"));
    out.add(new Subdivision("BF-NOU", "Noumbiel", "BF-13", "Province"));
    out.add(new Subdivision("BF-OUB", "Oubritenga", "BF-11", "Province"));
    out.add(new Subdivision("BF-OUD", "Oudalan", "BF-12", "Province"));
    out.add(new Subdivision("BF-PAS", "Passoré", "BF-10", "Province"));
    out.add(new Subdivision("BF-PON", "Poni", "BF-13", "Province"));
    out.add(new Subdivision("BF-SEN", "Séno", "BF-12", "Province"));
    out.add(new Subdivision("BF-SIS", "Sissili", "BF-06", "Province"));
    out.add(new Subdivision("BF-SMT", "Sanmatenga", "BF-05", "Province"));
    out.add(new Subdivision("BF-SNG", "Sanguié", "BF-06", "Province"));
    out.add(new Subdivision("BF-SOM", "Soum", "BF-12", "Province"));
    out.add(new Subdivision("BF-SOR", "Sourou", "BF-01", "Province"));
    out.add(new Subdivision("BF-TAP", "Tapoa", "BF-08", "Province"));
    out.add(new Subdivision("BF-TUI", "Tuy", "BF-09", "Province"));
    out.add(new Subdivision("BF-YAG", "Yagha", "BF-12", "Province"));
    out.add(new Subdivision("BF-YAT", "Yatenga", "BF-10", "Province"));
    out.add(new Subdivision("BF-ZIR", "Ziro", "BF-06", "Province"));
    out.add(new Subdivision("BF-ZON", "Zondoma", "BF-10", "Province"));
    out.add(new Subdivision("BF-ZOU", "Zoundwéogo", "BF-07", "Province"));
    out.add(new Subdivision("BG-01", "Blagoevgrad", null, "District"));
    out.add(new Subdivision("BG-02", "Burgas", null, "District"));
    out.add(new Subdivision("BG-03", "Varna", null, "District"));
    out.add(new Subdivision("BG-04", "Veliko Tarnovo", null, "District"));
    out.add(new Subdivision("BG-05", "Vidin", null, "District"));
    out.add(new Subdivision("BG-06", "Vratsa", null, "District"));
    out.add(new Subdivision("BG-07", "Gabrovo", null, "District"));
    out.add(new Subdivision("BG-08", "Dobrich", null, "District"));
    out.add(new Subdivision("BG-09", "Kardzhali", null, "District"));
    out.add(new Subdivision("BG-10", "Kyustendil", null, "District"));
    out.add(new Subdivision("BG-11", "Lovech", null, "District"));
    out.add(new Subdivision("BG-12", "Montana", null, "District"));
    out.add(new Subdivision("BG-13", "Pazardzhik", null, "District"));
    out.add(new Subdivision("BG-14", "Pernik", null, "District"));
    out.add(new Subdivision("BG-15", "Pleven", null, "District"));
    out.add(new Subdivision("BG-16", "Plovdiv", null, "District"));
    out.add(new Subdivision("BG-17", "Razgrad", null, "District"));
    out.add(new Subdivision("BG-18", "Ruse", null, "District"));
    out.add(new Subdivision("BG-19", "Silistra", null, "District"));
    out.add(new Subdivision("BG-20", "Sliven", null, "District"));
    out.add(new Subdivision("BG-21", "Smolyan", null, "District"));
    out.add(new Subdivision("BG-22", "Sofia (stolitsa)", null, "District"));
    out.add(new Subdivision("BG-23", "Sofia", null, "District"));
    out.add(new Subdivision("BG-24", "Stara Zagora", null, "District"));
    out.add(new Subdivision("BG-25", "Targovishte", null, "District"));
    out.add(new Subdivision("BG-26", "Haskovo", null, "District"));
    out.add(new Subdivision("BG-27", "Shumen", null, "District"));
    out.add(new Subdivision("BG-28", "Yambol", null, "District"));
    out.add(new Subdivision("BH-13", "Al ‘Āşimah", null, "Governorate"));
    out.add(new Subdivision("BH-14", "Al Janūbīyah", null, "Governorate"));
    out.add(new Subdivision("BH-15", "Al Muḩarraq", null, "Governorate"));
    out.add(new Subdivision("BH-17", "Ash Shamālīyah", null, "Governorate"));
    out.add(new Subdivision("BI-BB", "Bubanza", null, "Province"));
    out.add(new Subdivision("BI-BL", "Bujumbura Rural", null, "Province"));
    out.add(new Subdivision("BI-BM", "Bujumbura Mairie", null, "Province"));
    out.add(new Subdivision("BI-BR", "Bururi", null, "Province"));
    out.add(new Subdivision("BI-CA", "Cankuzo", null, "Province"));
    out.add(new Subdivision("BI-CI", "Cibitoke", null, "Province"));
    out.add(new Subdivision("BI-GI", "Gitega", null, "Province"));
    out.add(new Subdivision("BI-KI", "Kirundo", null, "Province"));
    out.add(new Subdivision("BI-KR", "Karuzi", null, "Province"));
    out.add(new Subdivision("BI-KY", "Kayanza", null, "Province"));
    out.add(new Subdivision("BI-MA", "Makamba", null, "Province"));
    out.add(new Subdivision("BI-MU", "Muramvya", null, "Province"));
    out.add(new Subdivision("BI-MW", "Mwaro", null, "Province"));
    out.add(new Subdivision("BI-MY", "Muyinga", null, "Province"));
    out.add(new Subdivision("BI-NG", "Ngozi", null, "Province"));
    out.add(new Subdivision("BI-RM", "Rumonge", null, "Province"));
    out.add(new Subdivision("BI-RT", "Rutana", null, "Province"));
    out.add(new Subdivision("BI-RY", "Ruyigi", null, "Province"));
    out.add(new Subdivision("BJ-AK", "Atacora", null, "Department"));
    out.add(new Subdivision("BJ-AL", "Alibori", null, "Department"));
    out.add(new Subdivision("BJ-AQ", "Atlantique", null, "Department"));
    out.add(new Subdivision("BJ-BO", "Borgou", null, "Department"));
    out.add(new Subdivision("BJ-CO", "Collines", null, "Department"));
    out.add(new Subdivision("BJ-DO", "Donga", null, "Department"));
    out.add(new Subdivision("BJ-KO", "Couffo", null, "Department"));
    out.add(new Subdivision("BJ-LI", "Littoral", null, "Department"));
    out.add(new Subdivision("BJ-MO", "Mono", null, "Department"));
    out.add(new Subdivision("BJ-OU", "Ouémé", null, "Department"));
    out.add(new Subdivision("BJ-PL", "Plateau", null, "Department"));
    out.add(new Subdivision("BJ-ZO", "Zou", null, "Department"));
    out.add(new Subdivision("BN-BE", "Belait", null, "District"));
    out.add(new Subdivision("BN-BM", "Brunei-Muara", null, "District"));
    out.add(new Subdivision("BN-TE", "Temburong", null, "District"));
    out.add(new Subdivision("BN-TU", "Tutong", null, "District"));
    out.add(new Subdivision("BO-B", "El Beni", null, "Department"));
    out.add(new Subdivision("BO-C", "Cochabamba", null, "Department"));
    out.add(new Subdivision("BO-H", "Chuquisaca", null, "Department"));
    out.add(new Subdivision("BO-L", "La Paz", null, "Department"));
    out.add(new Subdivision("BO-N", "Pando", null, "Department"));
    out.add(new Subdivision("BO-O", "Oruro", null, "Department"));
    out.add(new Subdivision("BO-P", "Potosí", null, "Department"));
    out.add(new Subdivision("BO-S", "Santa Cruz", null, "Department"));
    out.add(new Subdivision("BO-T", "Tarija", null, "Department"));
    out.add(new Subdivision("BQ-BO", "Bonaire", null, "Special municipality"));
    out.add(new Subdivision("BQ-SA", "Saba", null, "Special municipality"));
    out.add(new Subdivision("BQ-SE", "Sint Eustatius", null, "Special municipality"));
    out.add(new Subdivision("BR-AC", "Acre", null, "State"));
    out.add(new Subdivision("BR-AL", "Alagoas", null, "State"));
    out.add(new Subdivision("BR-AM", "Amazonas", null, "State"));
    out.add(new Subdivision("BR-AP", "Amapá", null, "State"));
    out.add(new Subdivision("BR-BA", "Bahia", null, "State"));
    out.add(new Subdivision("BR-CE", "Ceará", null, "State"));
    out.add(new Subdivision("BR-DF", "Distrito Federal", null, "Federal district"));
    out.add(new Subdivision("BR-ES", "Espírito Santo", null, "State"));
    out.add(new Subdivision("BR-GO", "Goiás", null, "State"));
    out.add(new Subdivision("BR-MA", "Maranhão", null, "State"));
    out.add(new Subdivision("BR-MG", "Minas Gerais", null, "State"));
    out.add(new Subdivision("BR-MS", "Mato Grosso do Sul", null, "State"));
    out.add(new Subdivision("BR-MT", "Mato Grosso", null, "State"));
    out.add(new Subdivision("BR-PA", "Pará", null, "State"));
    out.add(new Subdivision("BR-PB", "Paraíba", null, "State"));
    out.add(new Subdivision("BR-PE", "Pernambuco", null, "State"));
    out.add(new Subdivision("BR-PI", "Piauí", null, "State"));
    out.add(new Subdivision("BR-PR", "Paraná", null, "State"));
    out.add(new Subdivision("BR-RJ", "Rio de Janeiro", null, "State"));
    out.add(new Subdivision("BR-RN", "Rio Grande do Norte", null, "State"));
    out.add(new Subdivision("BR-RO", "Rondônia", null, "State"));
    out.add(new Subdivision("BR-RR", "Roraima", null, "State"));
    out.add(new Subdivision("BR-RS", "Rio Grande do Sul", null, "State"));
    out.add(new Subdivision("BR-SC", "Santa Catarina", null, "State"));
    out.add(new Subdivision("BR-SE", "Sergipe", null, "State"));
    out.add(new Subdivision("BR-SP", "São Paulo", null, "State"));
    out.add(new Subdivision("BR-TO", "Tocantins", null, "State"));
    out.add(new Subdivision("BS-AK", "Acklins", null, "District"));
    out.add(new Subdivision("BS-BI", "Bimini", null, "District"));
    out.add(new Subdivision("BS-BP", "Black Point", null, "District"));
    out.add(new Subdivision("BS-BY", "Berry Islands", null, "District"));
    out.add(new Subdivision("BS-CE", "Central Eleuthera", null, "District"));
    out.add(new Subdivision("BS-CI", "Cat Island", null, "District"));
    out.add(new Subdivision("BS-CK", "Crooked Island and Long Cay", null, "District"));
    out.add(new Subdivision("BS-CO", "Central Abaco", null, "District"));
    out.add(new Subdivision("BS-CS", "Central Andros", null, "District"));
    out.add(new Subdivision("BS-EG", "East Grand Bahama", null, "District"));
    out.add(new Subdivision("BS-EX", "Exuma", null, "District"));
    out.add(new Subdivision("BS-FP", "City of Freeport", null, "District"));
    out.add(new Subdivision("BS-GC", "Grand Cay", null, "District"));
    out.add(new Subdivision("BS-HI", "Harbour Island", null, "District"));
    out.add(new Subdivision("BS-HT", "Hope Town", null, "District"));
    out.add(new Subdivision("BS-IN", "Inagua", null, "District"));
    out.add(new Subdivision("BS-LI", "Long Island", null, "District"));
    out.add(new Subdivision("BS-MC", "Mangrove Cay", null, "District"));
    out.add(new Subdivision("BS-MG", "Mayaguana", null, "District"));
    out.add(new Subdivision("BS-MI", "Moore's Island", null, "District"));
    out.add(new Subdivision("BS-NE", "North Eleuthera", null, "District"));
    out.add(new Subdivision("BS-NO", "North Abaco", null, "District"));
  }
}
